OrcaSlicer: Slic3r::GUI::SliceInfoPopup Class Reference
Slic3r::GUI::SliceInfoPopup Class Reference
#include <src/slic3r/GUI/SliceInfoPanel.hpp>
Public Member Functions
SliceInfoPopup (wxWindow *parent, wxBitmap bmp=wxNullBitmap, BBLSliceInfo *info=nullptr)
virtual ~SliceInfoPopup ()
virtual void Popup (wxWindow *focus=NULL) wxOVERRIDE
virtual void OnDismiss () wxOVERRIDE
virtual bool ProcessLeftDown (wxMouseEvent &event) wxOVERRIDE
virtual bool Show (bool show=true) wxOVERRIDE
bool Create (wxWindow *parent, int flags=wxBORDER_NONE)
Private Member Functions
void OnMouse (wxMouseEvent &event)
void OnSize (wxSizeEvent &event)
void OnSetFocus (wxFocusEvent &event)
void OnKillFocus (wxFocusEvent &event)
wxDECLARE_ABSTRACT_CLASS (SliceInfoPopup)
wxDECLARE_EVENT_TABLE ()
Private Attributes
wxScrolledWindow * m_panel
BBLSliceInfo * m_info { nullptr }
Detailed Description
Constructor & Destructor Documentation
SliceInfoPopup()
Slic3r::GUI::SliceInfoPopup::SliceInfoPopup (wxWindow * parent, wxBitmap bmp = wxNullBitmap, BBLSliceInfo * info = nullptr)
   : PopupWindow(parent, wxBORDER_NONE | wxPU_CONTAINS_CONTROLS)
{
#ifdef __WINDOWS__
    SetDoubleBuffered(true);
#endif
    m_panel = new wxScrolledWindow(this, wxID_ANY);
    m_panel->SetBackgroundColour(*wxWHITE);
    m_panel->Bind(wxEVT_MOTION, &SliceInfoPopup::OnMouse, this);
    wxBoxSizer * main_sizer = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer * topSizer   = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer * caption_sizer = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer * caption_left_sizer = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer * caption_right_sizer = new wxBoxSizer(wxHORIZONTAL);
    auto prediction_bitmap = new wxStaticBitmap(m_panel, wxID_ANY, create_scaled_bitmap("monitor_item_prediction", nullptr, 16));
    wxString predict_text;
    if (info)
        predict_text = get_bbl_monitor_time_dhm(info->prediction);
    auto prediction = new wxStaticText(m_panel, wxID_ANY, predict_text, wxDefaultPosition, wxDefaultSize, wxST_ELLIPSIZE_END);
    caption_left_sizer->Add(prediction_bitmap, 0, wxALIGN_CENTER_VERTICAL | wxALL, FromDIP(5));
    caption_left_sizer->Add(prediction, 1, wxALIGN_CENTER_VERTICAL | wxALL, FromDIP(5));
    prediction->Wrap(-1);
    auto cost_bitmap = new wxStaticBitmap(m_panel, wxID_ANY, create_scaled_bitmap("monitor_item_cost", nullptr, 16));
    wxString cost_text;
    if (info) {
        if (info->weight > 0) {
            cost_text = wxString::Format("%.2fg", info->weight);
        } else {
            cost_text = "0g";
        }
    }
    auto used_g_text = new wxStaticText(m_panel, wxID_ANY, cost_text, wxDefaultPosition, wxDefaultSize, wxST_ELLIPSIZE_END);
    caption_right_sizer->Add(cost_bitmap, 0, wxALIGN_CENTER_VERTICAL | wxALL, FromDIP(5));
    caption_right_sizer->Add(used_g_text, 1, wxALIGN_CENTER_VERTICAL | wxALL, FromDIP(5));
    caption_sizer->Add(caption_left_sizer, 1, 0, FromDIP(5));
    caption_sizer->Add(caption_right_sizer, 1, 0, FromDIP(5));
    topSizer->Add(caption_sizer, 0, wxEXPAND | wxALL, 0);
    auto static_line = new StaticLine(m_panel);
    topSizer->Add(static_line, 0, wxEXPAND | wxALL, 0);
    wxGridSizer *grid_sizer = new wxGridSizer(2, wxSize(FromDIP(10), 0));
    if (info) {
        for (auto f : info->filaments_info) {
            auto f_sizer = new wxBoxSizer(wxHORIZONTAL);
            auto f_type  = new Button(m_panel, f.type);
            f_type->SetBorderColor(BUTTON_BORDER_COL);
            wxColour color = decode_color(f.color);
            f_type->SetBackgroundColor(color);
            auto  textcolor = wxColour(0, 0, 0);
            if (calc_gray(color) <= 128)
                textcolor = wxColour(255, 255, 255);
            else
                textcolor = wxColour(0, 0, 0);
            f_type->SetTextColor(textcolor);
            f_type->SetSize(wxSize(FromDIP(40), FromDIP(20)));
            f_type->SetMinSize(wxSize(FromDIP(40), FromDIP(20)));
            f_type->SetMaxSize(wxSize(FromDIP(40), FromDIP(20)));
            f_type->SetCornerRadius(FromDIP(10));
            wxString used_g_text = wxString::Format("%.1fg", f.used_g);
            auto f_used_g = new wxStaticText(m_panel, wxID_ANY, used_g_text, wxDefaultPosition, wxDefaultSize, wxST_ELLIPSIZE_END);
            f_used_g->Wrap(-1);
            f_used_g->SetSize(wxSize(FromDIP(60), -1));
            f_sizer->Add(f_type, 0, wxEXPAND | wxALL, FromDIP(5));
            f_sizer->Add(f_used_g, 0, wxEXPAND | wxALL, FromDIP(5));
            grid_sizer->Add(f_sizer, 0, wxEXPAND, 0);
            f_type->Bind(wxEVT_LEFT_DOWN, [this](auto &e) {});
        }
    }
    topSizer->Add(grid_sizer, 0, wxALL, FromDIP(5));
    main_sizer->Add(FromDIP(13), 0, 0, 0);
    main_sizer->Add(topSizer, 0, wxEXPAND | wxALL, 0);
    main_sizer->Add(FromDIP(13), 0, 0, 0);
    main_sizer->SetMinSize(wxSize(FromDIP(200), -1));
    m_panel->SetSizer(main_sizer);
    m_panel->Layout();
    main_sizer->Fit(m_panel);
    SetClientSize(m_panel->GetSize());
}
References Slic3r::GUI::calc_gray(), create_scaled_bitmap(), Slic3r::GUI::decode_color(), Slic3r::f(), Slic3r::BBLSliceInfo::filaments_info, Slic3r::get_bbl_monitor_time_dhm(), m_panel, OnMouse(), Slic3r::BBLSliceInfo::prediction, Slic3r::BBLSliceInfo::weight, and wxStaticText.
~SliceInfoPopup()
virtual Slic3r::GUI::SliceInfoPopup::~SliceInfoPopup () inline virtual
{}
Member Function Documentation
Create()
bool PopupWindow::Create (wxWindow * parent, int flags = wxBORDER_NONE) inherited
{
    if (!wxPopupTransientWindow::Create(parent, style))
        return false;
#ifdef __WXGTK__
    GetTopParent(parent)->Bind(wxEVT_ACTIVATE, &PopupWindow::topWindowActiavate, this);
#endif
    return true;
}
References GetTopParent(), and style.
Referenced by PopupWindow::PopupWindow(), and DropDown::Create().
OnDismiss()
void Slic3r::GUI::SliceInfoPopup::OnDismiss () virtual
{
    PopupWindow::OnDismiss();
}
OnKillFocus()
void Slic3r::GUI::SliceInfoPopup::OnKillFocus (wxFocusEvent & event) private
{
    event.Skip();
}
OnMouse()
void Slic3r::GUI::SliceInfoPopup::OnMouse (wxMouseEvent & event) private
{
    event.Skip();
}
Referenced by SliceInfoPopup().
OnSetFocus()
void Slic3r::GUI::SliceInfoPopup::OnSetFocus (wxFocusEvent & event) private
{
    event.Skip();
}
OnSize()
void Slic3r::GUI::SliceInfoPopup::OnSize (wxSizeEvent & event) private
{
    event.Skip();
}
Popup()
void Slic3r::GUI::SliceInfoPopup::Popup (wxWindow * focus = NULL) virtual
{
    PopupWindow::Popup();
}
ProcessLeftDown()
bool Slic3r::GUI::SliceInfoPopup::ProcessLeftDown (wxMouseEvent & event) virtual
{
    return PopupWindow::ProcessLeftDown(event);
}
Show()
bool Slic3r::GUI::SliceInfoPopup::Show (bool show = true) virtual
{
    return PopupWindow::Show(show);
}
wxDECLARE_ABSTRACT_CLASS()
Slic3r::GUI::SliceInfoPopup::wxDECLARE_ABSTRACT_CLASS (SliceInfoPopup) private
wxDECLARE_EVENT_TABLE()
Slic3r::GUI::SliceInfoPopup::wxDECLARE_EVENT_TABLE () private
Member Data Documentation
m_info
BBLSliceInfo* Slic3r::GUI::SliceInfoPopup::m_info { nullptr } private
m_panel
wxScrolledWindow* Slic3r::GUI::SliceInfoPopup::m_panel private
Referenced by SliceInfoPopup().
The documentation for this class was generated from the following files:
src/slic3r/GUI/SliceInfoPanel.hpp
src/slic3r/GUI/SliceInfoPanel.cpp