OrcaSlicer: cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement > Class Template Reference
cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement > Class Template Reference
KD-tree holding points.
#include <src/mcut/include/mcut/internal/cdt/kdtree.h>
Public Member Functions
void initialize (const std::vector< vec2_< TCoordType > > &points)
Initialize KD-tree with points.
void add_point (const std::uint32_t i, const std::vector< vec2_< TCoordType > > &points)
Add point to KD-tree.
std::uint32_t nearPoint (const vec2_< TCoordType > &pos, const std::vector< vec2_< TCoordType > > &points) const
Find nearest point using R-tree.
Private Types
typedef kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement > kdtree_t
Private Attributes
kdtree_t m_tree
Detailed Description
template<typename TCoordType, size_t NumVerticesInLeaf = 32, size_t InitialStackDepth = 32, size_t StackDepthIncrement = 32>
class cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >
KD-tree holding points.
Member Typedef Documentation
kdtree_t
template<typename TCoordType , size_t NumVerticesInLeaf = 32, size_t InitialStackDepth = 32, size_t StackDepthIncrement = 32> typedef kdt::kdtree_t_<TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement> cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::kdtree_t private
Member Function Documentation
add_point()
template<typename TCoordType , size_t NumVerticesInLeaf = 32, size_t InitialStackDepth = 32, size_t StackDepthIncrement = 32> void cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::add_point (const std::uint32_t i, const std::vector< vec2_< TCoordType > > & points) inline
Add point to KD-tree.
    {
        m_tree.insert(i, points);
    }
References kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert(), and cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_tree.
initialize()
template<typename TCoordType , size_t NumVerticesInLeaf = 32, size_t InitialStackDepth = 32, size_t StackDepthIncrement = 32> void cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initialize (const std::vector< vec2_< TCoordType > > & points) inline
Initialize KD-tree with points.
    {
        vec2_<TCoordType> min = points.front();
        vec2_<TCoordType> max = min;
        for (typename std::vector<vec2_<TCoordType>>::const_iterator it = points.begin();
             it != points.end();
             ++it) {
            min = vec2_<TCoordType>::make(std::min(min.x(), it->x()), std::min(min.y(), it->y()));
            max = vec2_<TCoordType>::make(std::max(max.x(), it->x()), std::max(max.y(), it->y()));
        }
        m_tree = kdtree_t(min, max);
        for (std::uint32_t i = 0; i < (std::uint32_t)points.size(); ++i) {
            m_tree.insert(i, points);
        }
    }
References kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert(), cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_tree, vec2_< T >::make(), max(), and min().
nearPoint()
template<typename TCoordType , size_t NumVerticesInLeaf = 32, size_t InitialStackDepth = 32, size_t StackDepthIncrement = 32> std::uint32_t cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearPoint (const vec2_< TCoordType > & pos, const std::vector< vec2_< TCoordType > > & points) const inline
Find nearest point using R-tree.
    {
        return m_tree.nearest(pos, points).second;
    }
References cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_tree, and kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearest().
Member Data Documentation
m_tree
template<typename TCoordType , size_t NumVerticesInLeaf = 32, size_t InitialStackDepth = 32, size_t StackDepthIncrement = 32> kdtree_t cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_tree private
Referenced by cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::add_point(), cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initialize(), and cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearPoint().
The documentation for this class was generated from the following file:
src/mcut/include/mcut/internal/cdt/kdtree.h