OrcaSlicer: Slic3r::GUI::SendToPrinterDialog Class Reference
Slic3r::GUI::SendToPrinterDialog Class Reference
#include <src/slic3r/GUI/SendToPrinter.hpp>
Public Member Functions
SendToPrinterDialog (Plater *plater=nullptr)
~SendToPrinterDialog ()
void prepare_mode ()
void sending_mode ()
void prepare (int print_plate_idx)
bool Show (bool show)
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
int ShowModal ()
Public Attributes
wxObjectDataPtr< MachineListModel > machine_model
std::shared_ptr< BBLStatusBarSend > m_status_bar
bool m_export_3mf_cancel { false }
bool m_is_canceled { false }
Protected Member Functions
void on_rename_click (wxCommandEvent &event)
void on_rename_enter ()
void stripWhiteSpace (std::string &str)
wxString format_text (wxString &m_msg)
void check_focus (wxWindow *window)
void check_fcous_state (wxWindow *window)
void update_priner_status_msg (wxString msg, bool is_warning=false)
void update_print_status_msg (wxString msg, bool is_warning=false, bool is_printer=true)
bool is_timeout ()
void reset_timeout ()
void update_user_printer ()
void update_show_status ()
void update_printer_combobox (wxCommandEvent &event)
void on_cancel (wxCloseEvent &event)
void on_ok (wxCommandEvent &event)
void clear_ip_address_config (wxCommandEvent &e)
void on_refresh (wxCommandEvent &event)
void on_print_job_cancel (wxCommandEvent &evt)
void set_default ()
void on_timer (wxTimerEvent &event)
void on_selection_changed (wxCommandEvent &event)
void Enable_Refresh_Button (bool en)
void show_status (PrintDialogStatus status, std::vector< wxString > params=std::vector< wxString >())
void Enable_Send_Button (bool en)
void on_dpi_changed (const wxRect &suggested_rect) override
void update_user_machine_list ()
std::vector< std::string > sort_string (std::vector< std::string > strArray)
virtual void on_sys_color_changed ()
Protected Attributes
wxString m_current_project_name
wxBoxSizer * rename_sizer_v { nullptr }
wxBoxSizer * rename_sizer_h { nullptr }
wxStaticText * m_rename_text { nullptr }
TextInput * m_rename_input { nullptr }
Button * m_rename_button { nullptr }
wxPanel * m_rename_normal_panel { nullptr }
wxSimplebook * m_rename_switch_panel { nullptr }
Plater * m_plater { nullptr }
wxPanel * m_line_top { nullptr }
wxPanel * m_panel_image { nullptr }
wxStaticText * m_stext_time { nullptr }
wxStaticText * m_stext_weight { nullptr }
wxPanel * m_line_materia { nullptr }
wxStaticText * m_stext_printer_title { nullptr }
wxStaticText * m_statictext_printer_msg { nullptr }
wxStaticBitmap * m_staticbitmap { nullptr }
ThumbnailPanel * m_thumbnailPanel { nullptr }
::ComboBox * m_comboBox_printer { nullptr }
::ComboBox * m_comboBox_bed { nullptr }
wxStaticText * m_staticText_bed_title { nullptr }
wxPanel * m_line_schedule { nullptr }
wxPanel * m_panel_sending { nullptr }
wxStaticText * m_stext_sending { nullptr }
wxPanel * m_panel_prepare { nullptr }
Button * m_button_refresh { nullptr }
Button * m_button_ensure { nullptr }
wxPanel * m_panel_finish { nullptr }
wxSimplebook * m_simplebook { nullptr }
wxStaticText * m_statictext_finish { nullptr }
StateColor btn_bg_enable
int m_current_filament_id
bool m_is_in_sending_mode { false }
wxBoxSizer * sizer_thumbnail
wxBoxSizer * m_sizer_main
wxBoxSizer * m_sizer_bottom
wxStaticText * m_file_name
bool m_is_rename_mode {false}
bool enable_prepare_mode {true}
bool m_need_adaptation_screen { false }
wxPanel * m_scrollable_region
wxBoxSizer * m_sizer_scrollable_region
std::vector< MachineObject * > m_list
wxDataViewCtrl * m_dataViewListCtrl_machines { nullptr }
wxStaticText * m_staticText_left { nullptr }
wxHyperlinkCtrl * m_hyperlink_add_machine { nullptr }
wxGauge * m_gauge_job_progress { nullptr }
wxPanel * m_panel_status { nullptr }
wxButton * m_button_cancel { nullptr }
std::string m_print_info
int timeout_count = 0
wxTimer * m_refresh_timer { nullptr }
std::shared_ptr< SendJob > m_send_job {nullptr}
Private Member Functions
void init_model ()
void init_bind ()
void init_timer ()
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
int m_print_plate_idx
PrintDialogStatus m_print_status { PrintStatusInit }
std::string m_printer_last_select
std::vector< wxString > m_bedtype_list
std::map< std::string, ::CheckBox * > m_checkbox_list
wxColour m_colour_def_color { wxColour(255, 255, 255) }
wxColour m_colour_bold_color { wxColour(38, 46, 48) }
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Constructor & Destructor Documentation
SendToPrinterDialog()
Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog (Plater * plater = nullptr)
    : DPIDialog(static_cast<wxWindow *>(wxGetApp().mainframe), wxID_ANY, _L("Send to Printer SD card"), wxDefaultPosition, wxDefaultSize, wxCAPTION | wxCLOSE_BOX)
    , m_plater(plater), m_export_3mf_cancel(false)
{
#ifdef __WINDOWS__
    SetDoubleBuffered(true);
#endif //__WINDOWS__
    // bind
    Bind(wxEVT_CLOSE_WINDOW, &SendToPrinterDialog::on_cancel, this);
    // font
    SetFont(wxGetApp().normal_font());
    // icon
    std::string icon_path = (boost::format("%1%/images/OrcaSlicerTitle.ico") % resources_dir()).str();
    SetIcon(wxIcon(encode_path(icon_path.c_str()), wxBITMAP_TYPE_ICO));
    Freeze();
    SetBackgroundColour(m_colour_def_color);
    m_sizer_main = new wxBoxSizer(wxVERTICAL);
    m_sizer_main->SetMinSize(wxSize(0, -1));
    m_line_top = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1, 1), wxTAB_TRAVERSAL);
    m_line_top->SetBackgroundColour(wxColour(166, 169, 170));
    m_scrollable_region       = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_sizer_scrollable_region = new wxBoxSizer(wxVERTICAL);
    m_panel_image = new wxPanel(m_scrollable_region, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_panel_image->SetBackgroundColour(m_colour_def_color);
    sizer_thumbnail = new wxBoxSizer(wxVERTICAL);
    m_thumbnailPanel = new ThumbnailPanel(m_panel_image);
    m_thumbnailPanel->SetSize(wxSize(FromDIP(256), FromDIP(256)));
    m_thumbnailPanel->SetMinSize(wxSize(FromDIP(256), FromDIP(256)));
    m_thumbnailPanel->SetMaxSize(wxSize(FromDIP(256), FromDIP(256)));
    sizer_thumbnail->Add(m_thumbnailPanel, 0, wxEXPAND, 0);
    m_panel_image->SetSizer(sizer_thumbnail);
    m_panel_image->Layout();
    wxBoxSizer *m_sizer_basic        = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *m_sizer_basic_weight = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *m_sizer_basic_time   = new wxBoxSizer(wxHORIZONTAL);
    auto timeimg = new wxStaticBitmap(m_scrollable_region, wxID_ANY, create_scaled_bitmap("print-time", this, 18), wxDefaultPosition, wxSize(FromDIP(18), FromDIP(18)), 0);
    m_sizer_basic_weight->Add(timeimg, 1, wxEXPAND | wxALL, FromDIP(5));
    m_stext_time = new wxStaticText(m_scrollable_region, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxALIGN_RIGHT);
    m_sizer_basic_weight->Add(m_stext_time, 0, wxALL, FromDIP(5));
    m_sizer_basic->Add(m_sizer_basic_weight, 0, wxALIGN_CENTER, 0);
    m_sizer_basic->Add(0, 0, 0, wxEXPAND | wxLEFT | wxRIGHT, FromDIP(30));
    auto weightimg = new wxStaticBitmap(m_scrollable_region, wxID_ANY, create_scaled_bitmap("print-weight", this, 18), wxDefaultPosition, wxSize(FromDIP(18), FromDIP(18)), 0);
    m_sizer_basic_time->Add(weightimg, 1, wxEXPAND | wxALL, FromDIP(5));
    m_stext_weight = new wxStaticText(m_scrollable_region, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxALIGN_LEFT);
    m_sizer_basic_time->Add(m_stext_weight, 0, wxALL, FromDIP(5));
    m_sizer_basic->Add(m_sizer_basic_time, 0, wxALIGN_CENTER, 0);
    m_line_materia = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1, 1), wxTAB_TRAVERSAL);
    m_line_materia->SetForegroundColour(wxColour(238, 238, 238));
    m_line_materia->SetBackgroundColour(wxColour(238, 238, 238));
    wxBoxSizer *m_sizer_printer = new wxBoxSizer(wxHORIZONTAL);
    m_stext_printer_title = new wxStaticText(this, wxID_ANY, _L("Printer"), wxDefaultPosition, wxSize(-1, -1), 0);
    m_stext_printer_title->SetFont(::Label::Head_14);
    m_stext_printer_title->Wrap(-1);
    m_stext_printer_title->SetForegroundColour(m_colour_bold_color);
    m_stext_printer_title->SetBackgroundColour(m_colour_def_color);
    m_sizer_printer->Add(m_stext_printer_title, 0, wxALL | wxLEFT, FromDIP(5));
    m_sizer_printer->Add(0, 0, 0, wxEXPAND | wxLEFT, FromDIP(12));
    m_comboBox_printer = new ::ComboBox(this, wxID_ANY, "", wxDefaultPosition, wxSize(FromDIP(250), -1), 0, nullptr, wxCB_READONLY);
    m_comboBox_printer->Bind(wxEVT_COMBOBOX, &SendToPrinterDialog::on_selection_changed, this);
    m_sizer_printer->Add(m_comboBox_printer, 1, wxEXPAND | wxRIGHT, FromDIP(5));
    btn_bg_enable = StateColor(std::pair<wxColour, int>(wxColour(0, 137, 123), StateColor::Pressed), std::pair<wxColour, int>(wxColour(38, 166, 154), StateColor::Hovered),
                               std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal));
    m_button_refresh = new Button(this, _L("Refresh"));
    m_button_refresh->SetBackgroundColor(btn_bg_enable);
    m_button_refresh->SetBorderColor(btn_bg_enable);
    m_button_refresh->SetTextColor(StateColor::darkModeColorFor("#FFFFFE"));
    m_button_refresh->SetSize(SELECT_MACHINE_DIALOG_BUTTON_SIZE);
    m_button_refresh->SetMinSize(SELECT_MACHINE_DIALOG_BUTTON_SIZE);
    m_button_refresh->SetCornerRadius(FromDIP(10));
    m_button_refresh->Bind(wxEVT_BUTTON, &SendToPrinterDialog::on_refresh, this);
    m_sizer_printer->Add(m_button_refresh, 0, wxALL | wxLEFT, FromDIP(5));
    m_statictext_printer_msg = new wxStaticText(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER_HORIZONTAL);
    m_statictext_printer_msg->SetFont(::Label::Body_13);
    m_statictext_printer_msg->SetForegroundColour(*wxBLACK);
    m_statictext_printer_msg->Hide();
    // line schedule
    m_line_schedule = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1, 1));
    m_line_schedule->SetBackgroundColour(wxColour(238, 238, 238));
    m_sizer_bottom = new wxBoxSizer(wxVERTICAL);
    m_simplebook   = new wxSimplebook(this, wxID_ANY, wxDefaultPosition, SELECT_MACHINE_DIALOG_SIMBOOK_SIZE, 0);
    // perpare mode
    m_panel_prepare = new wxPanel(m_simplebook, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_panel_prepare->SetBackgroundColour(m_colour_def_color);
    // m_panel_prepare->SetBackgroundColour(wxColour(135,206,250));
    wxBoxSizer *m_sizer_prepare = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *m_sizer_pcont   = new wxBoxSizer(wxHORIZONTAL);
    m_sizer_prepare->Add(0, 0, 1, wxTOP, FromDIP(22));
    m_sizer_pcont->Add(0, 0, 1, wxEXPAND, 0);
    m_button_ensure = new Button(m_panel_prepare, _L("Send"));
    m_button_ensure->SetBackgroundColor(btn_bg_enable);
    m_button_ensure->SetBorderColor(btn_bg_enable);
    m_button_ensure->SetTextColor(StateColor::darkModeColorFor("#FFFFFE"));
    m_button_ensure->SetSize(SELECT_MACHINE_DIALOG_BUTTON_SIZE);
    m_button_ensure->SetMinSize(SELECT_MACHINE_DIALOG_BUTTON_SIZE);
    m_button_ensure->SetCornerRadius(FromDIP(12));
    m_button_ensure->Bind(wxEVT_BUTTON, &SendToPrinterDialog::on_ok, this);
    m_sizer_pcont->Add(m_button_ensure, 0, wxEXPAND | wxBOTTOM, FromDIP(10));
    m_sizer_prepare->Add(m_sizer_pcont, 0, wxEXPAND, 0);
    m_panel_prepare->SetSizer(m_sizer_prepare);
    m_panel_prepare->Layout();
    m_simplebook->AddPage(m_panel_prepare, wxEmptyString, true);
    // sending mode
    m_status_bar    = std::make_shared<BBLStatusBarSend>(m_simplebook);
    m_panel_sending = m_status_bar->get_panel();
    m_simplebook->AddPage(m_panel_sending, wxEmptyString, false);
    // finish mode
    m_panel_finish = new wxPanel(m_simplebook, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_panel_finish->SetBackgroundColour(wxColour(135, 206, 250));
    wxBoxSizer *m_sizer_finish   = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *m_sizer_finish_v = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *m_sizer_finish_h = new wxBoxSizer(wxHORIZONTAL);
    auto imgsize      = FromDIP(25);
    auto completedimg = new wxStaticBitmap(m_panel_finish, wxID_ANY, create_scaled_bitmap("completed", m_panel_finish, 25), wxDefaultPosition, wxSize(imgsize, imgsize), 0);
    m_sizer_finish_h->Add(completedimg, 0, wxALIGN_CENTER | wxALL, FromDIP(5));
    m_statictext_finish = new wxStaticText(m_panel_finish, wxID_ANY, L("send completed"), wxDefaultPosition, wxDefaultSize, 0);
    m_statictext_finish->Wrap(-1);
    m_statictext_finish->SetForegroundColour(wxColour(0, 150, 136));
    m_sizer_finish_h->Add(m_statictext_finish, 0, wxALIGN_CENTER | wxALL, FromDIP(5));
    m_sizer_finish_v->Add(m_sizer_finish_h, 1, wxALIGN_CENTER, 0);
    m_sizer_finish->Add(m_sizer_finish_v, 1, wxALIGN_CENTER, 0);
    m_panel_finish->SetSizer(m_sizer_finish);
    m_panel_finish->Layout();
    m_sizer_finish->Fit(m_panel_finish);
    m_simplebook->AddPage(m_panel_finish, wxEmptyString, false);
    // bind
    Bind(EVT_UPDATE_USER_MACHINE_LIST, &SendToPrinterDialog::update_printer_combobox, this);
    Bind(EVT_PRINT_JOB_CANCEL, &SendToPrinterDialog::on_print_job_cancel, this);
    m_sizer_scrollable_region->Add(m_panel_image, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    m_sizer_scrollable_region->Add(0, 0, 0, wxTOP, FromDIP(10));
    m_sizer_scrollable_region->Add(m_sizer_basic, 0, wxALIGN_CENTER_HORIZONTAL, 0);
  m_scrollable_region->SetSizer(m_sizer_scrollable_region);
  m_scrollable_region->Layout();
    //file name
    //rename normal
    m_rename_switch_panel = new wxSimplebook(this);
    m_rename_switch_panel->SetSize(wxSize(FromDIP(420), FromDIP(25)));
    m_rename_switch_panel->SetMinSize(wxSize(FromDIP(420), FromDIP(25)));
    m_rename_switch_panel->SetMaxSize(wxSize(FromDIP(420), FromDIP(25)));
    m_rename_normal_panel = new wxPanel(m_rename_switch_panel, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_rename_normal_panel->SetBackgroundColour(*wxWHITE);
    rename_sizer_v = new wxBoxSizer(wxVERTICAL);
    rename_sizer_h = new wxBoxSizer(wxHORIZONTAL);
    m_rename_text = new wxStaticText(m_rename_normal_panel, wxID_ANY, wxT("MyLabel"), wxDefaultPosition, wxDefaultSize, 0);
    m_rename_text->SetForegroundColour(*wxBLACK);
    m_rename_text->SetFont(::Label::Body_13);
    m_rename_text->SetMaxSize(wxSize(FromDIP(390), -1));
    m_rename_button = new Button(m_rename_normal_panel, "", "ams_editable", wxBORDER_NONE, FromDIP(10));
    m_rename_button->SetBackgroundColor(*wxWHITE);
    m_rename_button->SetBackgroundColour(*wxWHITE);
    rename_sizer_h->Add(m_rename_text, 0, wxALIGN_CENTER, 0);
    rename_sizer_h->Add(m_rename_button, 0, wxALIGN_CENTER, 0);
    rename_sizer_v->Add(rename_sizer_h, 1, wxALIGN_CENTER, 0);
    m_rename_normal_panel->SetSizer(rename_sizer_v);
    m_rename_normal_panel->Layout();
    rename_sizer_v->Fit(m_rename_normal_panel);
    //rename edit
    auto m_rename_edit_panel = new wxPanel(m_rename_switch_panel, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_rename_edit_panel->SetBackgroundColour(*wxWHITE);
    auto rename_edit_sizer_v = new wxBoxSizer(wxVERTICAL);
    m_rename_input = new ::TextInput(m_rename_edit_panel, wxEmptyString, wxEmptyString, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    m_rename_input->GetTextCtrl()->SetFont(::Label::Body_13);
    m_rename_input->SetSize(wxSize(FromDIP(380), FromDIP(24)));
    m_rename_input->SetMinSize(wxSize(FromDIP(380), FromDIP(24)));
    m_rename_input->SetMaxSize(wxSize(FromDIP(380), FromDIP(24)));
    m_rename_input->Bind(wxEVT_TEXT_ENTER, [this](auto& e) {on_rename_enter();});
    m_rename_input->Bind(wxEVT_KILL_FOCUS, [this](auto& e) {
        if (!m_rename_input->HasFocus() && !m_rename_text->HasFocus())
            on_rename_enter();
        else
            e.Skip(); });
    rename_edit_sizer_v->Add(m_rename_input, 1, wxALIGN_CENTER, 0);
    m_rename_edit_panel->SetSizer(rename_edit_sizer_v);
    m_rename_edit_panel->Layout();
    rename_edit_sizer_v->Fit(m_rename_edit_panel);
    m_rename_button->Bind(wxEVT_BUTTON, &SendToPrinterDialog::on_rename_click, this);
    m_rename_switch_panel->AddPage(m_rename_normal_panel, wxEmptyString, true);
    m_rename_switch_panel->AddPage(m_rename_edit_panel, wxEmptyString, false);
    Bind(wxEVT_CHAR_HOOK, [this](wxKeyEvent& e) {
        if (e.GetKeyCode() == WXK_ESCAPE) {
            if (m_rename_switch_panel->GetSelection() == 0) {
                e.Skip();
            }
            else {
                m_rename_switch_panel->SetSelection(0);
                m_rename_text->SetLabel(m_current_project_name);
                m_rename_normal_panel->Layout();
            }
        }
        else {
            e.Skip();
        }
        });
    m_panel_prepare->Bind(wxEVT_LEFT_DOWN, [this](auto& e) {
        check_fcous_state(this);
        e.Skip();
        });
    m_scrollable_region->Bind(wxEVT_LEFT_DOWN, [this](auto& e) {
        check_fcous_state(this);
        e.Skip();
        });
    Bind(wxEVT_LEFT_DOWN, [this](auto& e) {
        check_fcous_state(this);
        e.Skip();
        });
    m_sizer_main->Add(m_line_top, 0, wxEXPAND, 0);
    m_sizer_main->Add(0, 0, 0, wxTOP, FromDIP(22));
    m_sizer_main->Add(m_scrollable_region, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    m_sizer_main->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(8));
    m_sizer_main->Add(m_rename_switch_panel, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    m_sizer_main->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(8));
    m_sizer_main->Add(m_line_materia, 0, wxEXPAND | wxLEFT | wxRIGHT, FromDIP(30));
    m_sizer_main->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(15));
    m_sizer_main->Add(m_sizer_printer, 0, wxEXPAND | wxLEFT | wxRIGHT, FromDIP(30));
    m_sizer_main->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(13));
    m_sizer_main->Add(m_statictext_printer_msg, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    m_sizer_main->Add(0, 1, 0, wxTOP, FromDIP(32));
    m_sizer_main->Add(m_line_schedule, 0, wxEXPAND | wxLEFT | wxRIGHT, FromDIP(30));
    m_sizer_main->Add(m_simplebook, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    m_sizer_main->Add(m_sizer_bottom, 0, wxALIGN_CENTER_HORIZONTAL);
    m_sizer_main->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(15));
    SetSizer(m_sizer_main);
    Layout();
    Fit();
    Thaw();
    init_bind();
    init_timer();
    // CenterOnParent();
    Centre(wxBOTH);
    wxGetApp().UpdateDlgDarkUI(this);
}
References _L, Label::Body_13, btn_bg_enable, create_scaled_bitmap(), StateColor::darkModeColorFor(), Slic3r::encode_path(), TextInput::GetTextCtrl(), Label::Head_14, StateColor::Hovered, L, m_button_ensure, m_button_refresh, m_colour_bold_color, m_colour_def_color, m_comboBox_printer, m_line_materia, m_line_schedule, m_line_top, m_panel_finish, m_panel_image, m_panel_prepare, m_panel_sending, m_rename_button, m_rename_input, m_rename_normal_panel, m_rename_switch_panel, m_rename_text, m_scrollable_region, m_simplebook, m_sizer_bottom, m_sizer_main, m_sizer_scrollable_region, m_statictext_finish, m_statictext_printer_msg, m_status_bar, m_stext_printer_title, m_stext_time, m_stext_weight, m_thumbnailPanel, StateColor::Normal, Slic3r::GUI::DPIAware< P >::normal_font(), on_cancel(), on_ok(), on_print_job_cancel(), on_refresh(), on_rename_click(), on_rename_enter(), on_selection_changed(), StateColor::Pressed, rename_sizer_h, rename_sizer_v, Slic3r::resources_dir(), SELECT_MACHINE_DIALOG_BUTTON_SIZE, SELECT_MACHINE_DIALOG_SIMBOOK_SIZE, StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), StaticBox::SetCornerRadius(), Button::SetMinSize(), TextInput::SetMinSize(), Button::SetTextColor(), sizer_thumbnail, update_printer_combobox(), wxEVT_BUTTON, and wxStaticText.
~SendToPrinterDialog()
Slic3r::GUI::SendToPrinterDialog::~SendToPrinterDialog ()
{
    delete m_refresh_timer;
}
Member Function Documentation
check_fcous_state()
void Slic3r::GUI::SendToPrinterDialog::check_fcous_state (wxWindow * window) protected
{
    check_focus(window);
    auto children = window->GetChildren();
    for (auto child : children) {
        check_fcous_state(child);
    }
}
References check_fcous_state(), and check_focus().
Referenced by check_fcous_state().
check_focus()
void Slic3r::GUI::SendToPrinterDialog::check_focus (wxWindow * window) protected
{
    if (window == m_rename_input || window == m_rename_input->GetTextCtrl()) {
        on_rename_enter();
    }
}
References TextInput::GetTextCtrl(), m_rename_input, and on_rename_enter().
Referenced by check_fcous_state().
clear_ip_address_config()
void Slic3r::GUI::SendToPrinterDialog::clear_ip_address_config (wxCommandEvent & e) protected
{
    enable_prepare_mode = true;
    prepare_mode();
    /*DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    if (!dev->get_selected_machine()) return;
    auto obj = dev->get_selected_machine();
    Slic3r::GUI::wxGetApp().app_config->set_str("ip_address", obj->dev_id, "");
    Slic3r::GUI::wxGetApp().app_config->save();
    wxGetApp().show_ip_address_enter_dialog();*/
}
Referenced by init_bind().
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AuxiliaryDialog::AuxiliaryDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::ParamsDialog::ParamsDialog(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), em_unit(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::AuxiliaryDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ObjectTableDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::ParamsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
Enable_Refresh_Button()
void Slic3r::GUI::SendToPrinterDialog::Enable_Refresh_Button (bool en) protected
{
    if (!en) {
        if (m_button_refresh->IsEnabled()) {
            m_button_refresh->Disable();
            m_button_refresh->SetBackgroundColor(wxColour(0x90, 0x90, 0x90));
            m_button_refresh->SetBorderColor(wxColour(0x90, 0x90, 0x90));
        }
    } else {
        if (!m_button_refresh->IsEnabled()) {
            m_button_refresh->Enable();
            m_button_refresh->SetBackgroundColor(btn_bg_enable);
            m_button_refresh->SetBorderColor(btn_bg_enable);
        }
    }
}
Enable_Send_Button()
void Slic3r::GUI::SendToPrinterDialog::Enable_Send_Button (bool en) protected
{
    if (!en) {
        if (m_button_ensure->IsEnabled()) {
            m_button_ensure->Disable();
            m_button_ensure->SetBackgroundColor(wxColour(0x90, 0x90, 0x90));
            m_button_ensure->SetBorderColor(wxColour(0x90, 0x90, 0x90));
        }
    } else {
        if (!m_button_ensure->IsEnabled()) {
            m_button_ensure->Enable();
            m_button_ensure->SetBackgroundColor(btn_bg_enable);
            m_button_ensure->SetBorderColor(btn_bg_enable);
        }
    }
}
format_text()
wxString Slic3r::GUI::SendToPrinterDialog::format_text (wxString & m_msg) protected
{
  if (wxGetApp().app_config->get("language") != "zh_CN") { return m_msg; }
  wxString out_txt = m_msg;
  wxString count_txt = "";
  int      new_line_pos = 0;
  for (int i = 0; i < m_msg.length(); i++) {
    auto text_size = m_statictext_printer_msg->GetTextExtent(count_txt);
    if (text_size.x < (FromDIP(400))) {
      count_txt += m_msg[i];
    }
    else {
      out_txt.insert(i - 1, '\n');
      count_txt = "";
    }
  }
  return out_txt;
}
References m_statictext_printer_msg.
init_bind()
void Slic3r::GUI::SendToPrinterDialog::init_bind () private
{
    Bind(wxEVT_TIMER, &SendToPrinterDialog::on_timer, this);
    Bind(EVT_CLEAR_IPADDRESS, &SendToPrinterDialog::clear_ip_address_config, this);
}
References clear_ip_address_config(), and on_timer().
init_model()
void Slic3r::GUI::SendToPrinterDialog::init_model () private
{
    machine_model = new MachineListModel;
    m_dataViewListCtrl_machines->AssociateModel(machine_model.get());
    m_dataViewListCtrl_machines->AppendTextColumn("Printer Name", MachineListModel::Col_MachineName, wxDATAVIEW_CELL_INERT, wxCOL_WIDTH_AUTOSIZE, wxALIGN_NOT,
                                                  wxDATAVIEW_COL_SORTABLE);
    m_dataViewListCtrl_machines->AppendTextColumn("SN(dev_id)", MachineListModel::Col_MachineSN, wxDATAVIEW_CELL_INERT, wxCOL_WIDTH_AUTOSIZE, wxALIGN_NOT,
                                                  wxDATAVIEW_COL_RESIZABLE);
    m_dataViewListCtrl_machines->AppendTextColumn("Status", MachineListModel::Col_MachinePrintingStatus, wxDATAVIEW_CELL_INERT, wxCOL_WIDTH_AUTOSIZE, wxALIGN_NOT,
                                                  wxDATAVIEW_COL_RESIZABLE);
    m_dataViewListCtrl_machines->AppendTextColumn("TaskName", MachineListModel::Col_MachineTaskName, wxDATAVIEW_CELL_INERT, wxCOL_WIDTH_AUTOSIZE, wxALIGN_NOT,
                                                  wxDATAVIEW_COL_RESIZABLE);
    m_dataViewListCtrl_machines->AppendTextColumn("Connection", MachineListModel::Col_MachineConnection, wxDATAVIEW_CELL_INERT, wxCOL_WIDTH_AUTOSIZE, wxALIGN_NOT,
                                                  wxDATAVIEW_COL_RESIZABLE);
}
References Slic3r::GUI::MachineListModel::Col_MachineConnection, Slic3r::GUI::MachineListModel::Col_MachineName, Slic3r::GUI::MachineListModel::Col_MachinePrintingStatus, Slic3r::GUI::MachineListModel::Col_MachineSN, and Slic3r::GUI::MachineListModel::Col_MachineTaskName.
init_timer()
void Slic3r::GUI::SendToPrinterDialog::init_timer () private
{
    m_refresh_timer = new wxTimer();
    m_refresh_timer->SetOwner(this);
}
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
is_timeout()
bool Slic3r::GUI::SendToPrinterDialog::is_timeout () protected
{
    if (timeout_count > 15 * 1000 / LIST_REFRESH_INTERVAL) {
        return true;
    }
    return false;
}
References LIST_REFRESH_INTERVAL.
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), SendToPrinterDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
on_cancel()
void Slic3r::GUI::SendToPrinterDialog::on_cancel (wxCloseEvent & event) protected
{
    if (m_send_job) {
        if (m_send_job->is_running()) {
            m_send_job->cancel();
            m_send_job->join();
        }
    }
    this->EndModal(wxID_CANCEL);
}
Referenced by SendToPrinterDialog().
on_dpi_changed()
void Slic3r::GUI::SendToPrinterDialog::on_dpi_changed (const wxRect & suggested_rect) override protected virtual
Implements Slic3r::GUI::DPIAware< P >.
{
    m_button_refresh->SetMinSize(SELECT_MACHINE_DIALOG_BUTTON_SIZE);
    m_button_refresh->SetCornerRadius(FromDIP(12));
    m_button_ensure->SetMinSize(SELECT_MACHINE_DIALOG_BUTTON_SIZE);
    m_button_ensure->SetCornerRadius(FromDIP(12));
    m_status_bar->msw_rescale();
    Fit();
    Refresh();
}
References SELECT_MACHINE_DIALOG_BUTTON_SIZE.
on_ok()
void Slic3r::GUI::SendToPrinterDialog::on_ok (wxCommandEvent & event) protected
{
    BOOST_LOG_TRIVIAL(info) << "print_job: on_ok to send";
    m_is_canceled = false;
    Enable_Send_Button(false);
    if (m_is_in_sending_mode)
        return;
    int result = 0;
    if (m_printer_last_select.empty()) {
        return;
    }
    DeviceManager *dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    MachineObject *obj_ = dev->get_selected_machine();
    if (obj_ == nullptr) {
        m_printer_last_select = "";
        m_comboBox_printer->SetTextLabel("");
        return;
    }
    assert(obj_->dev_id == m_printer_last_select);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ", print_job: for send task, current printer id =  " << m_printer_last_select << std::endl;
    show_status(PrintDialogStatus::PrintStatusSending);
    m_status_bar->reset();
    m_status_bar->set_prog_block();
    m_status_bar->set_cancel_callback_fina([this]() {
        BOOST_LOG_TRIVIAL(info) << "print_job: enter canceled";
        if (m_send_job) {
            if (m_send_job->is_running()) {
                BOOST_LOG_TRIVIAL(info) << "send_job: canceled";
                m_send_job->cancel();
            }
            m_send_job->join();
        }
        m_is_canceled = true;
        wxCommandEvent* event = new wxCommandEvent(EVT_PRINT_JOB_CANCEL);
        wxQueueEvent(this, event);
    });
    if (m_is_canceled) {
        BOOST_LOG_TRIVIAL(info) << "send_job: m_is_canceled";
        //m_status_bar->set_status_text(task_canceled_text);
        return;
    }
    // enter sending mode
    sending_mode();
    result = m_plater->send_gcode(m_print_plate_idx, [this](int export_stage, int current, int total, bool &cancel) {
        if (this->m_is_canceled) return;
        bool     cancelled = false;
        wxString msg       = _L("Preparing print job");
        m_status_bar->update_status(msg, cancelled, 10, true);
        m_export_3mf_cancel = cancel = cancelled;
    });
    if (m_is_canceled || m_export_3mf_cancel) {
        BOOST_LOG_TRIVIAL(info) << "send_job: m_export_3mf_cancel or m_is_canceled";
        //m_status_bar->set_status_text(task_canceled_text);
        return;
    }
    if (result < 0) {
        wxString msg = _L("Abnormal print file data. Please slice again");
        m_status_bar->set_status_text(msg);
        return;
    }
    // export config 3mf if needed
    if (!obj_->is_lan_mode_printer()) {
        result = m_plater->export_config_3mf(m_print_plate_idx);
        if (result < 0) {
            BOOST_LOG_TRIVIAL(trace) << "export_config_3mf failed, result = " << result;
            return;
        }
    }
    if (m_is_canceled || m_export_3mf_cancel) {
        BOOST_LOG_TRIVIAL(info) << "send_job: m_export_3mf_cancel or m_is_canceled";
        //m_status_bar->set_status_text(task_canceled_text);
        return;
    }
   /* std::string  file_name       = "";
  auto default_output_file    = wxGetApp().plater()->get_export_gcode_filename(".3mf");
    if (!default_output_file.empty()) {
    fs::path default_output_file_path = boost::filesystem::path(default_output_file.c_str());
    file_name = default_output_file_path.filename().string();
    }*/
    m_send_job                      = std::make_shared<SendJob>(m_status_bar, m_plater, m_printer_last_select);
    m_send_job->m_dev_ip            = obj_->dev_ip;
    m_send_job->m_access_code       = obj_->get_access_code();
    m_send_job->m_local_use_ssl     = obj_->local_use_ssl;
    m_send_job->connection_type     = obj_->connection_type();
    m_send_job->cloud_print_only    = true;
    m_send_job->has_sdcard          = obj_->has_sdcard();
    m_send_job->set_project_name(m_current_project_name.utf8_string());
    enable_prepare_mode = false;
    m_send_job->on_check_ip_address_fail([this]() {
        wxCommandEvent* evt = new wxCommandEvent(EVT_CLEAR_IPADDRESS);
        wxQueueEvent(this, evt);
        wxGetApp().show_ip_address_enter_dialog();
    });
    if (obj_->is_lan_mode_printer()) {
        m_send_job->set_check_mode();
        m_send_job->check_and_continue();
        m_send_job->start();
    }
    else {
        m_send_job->start();
    }
    BOOST_LOG_TRIVIAL(info) << "send_job: send print job";
}
References _L, Slic3r::MachineObject::connection_type(), Slic3r::MachineObject::dev_id, Slic3r::MachineObject::dev_ip, Slic3r::MachineObject::get_access_code(), Slic3r::DeviceManager::get_selected_machine(), Slic3r::MachineObject::has_sdcard(), Slic3r::MachineObject::is_lan_mode_printer(), Slic3r::MachineObject::local_use_ssl, and Slic3r::trace().
Referenced by SendToPrinterDialog().
on_print_job_cancel()
void Slic3r::GUI::SendToPrinterDialog::on_print_job_cancel (wxCommandEvent & evt) protected
{
    BOOST_LOG_TRIVIAL(info) << "print_job: canceled";
    show_status(PrintDialogStatus::PrintStatusSendingCanceled);
    // enter prepare mode
    prepare_mode();
}
Referenced by SendToPrinterDialog().
on_refresh()
void Slic3r::GUI::SendToPrinterDialog::on_refresh (wxCommandEvent & event) protected
{
    BOOST_LOG_TRIVIAL(info) << "m_printer_last_select: on_refresh";
    show_status(PrintDialogStatus::PrintStatusRefreshingMachineList);
    update_user_machine_list();
}
Referenced by SendToPrinterDialog().
on_rename_click()
void Slic3r::GUI::SendToPrinterDialog::on_rename_click (wxCommandEvent & event) protected
{
    m_is_rename_mode = true;
    m_rename_input->GetTextCtrl()->SetValue(m_current_project_name);
    m_rename_switch_panel->SetSelection(1);
    m_rename_input->GetTextCtrl()->SetFocus();
    m_rename_input->GetTextCtrl()->SetInsertionPointEnd();
}
References TextInput::GetTextCtrl(), m_current_project_name, m_is_rename_mode, m_rename_input, and m_rename_switch_panel.
Referenced by SendToPrinterDialog().
on_rename_enter()
void Slic3r::GUI::SendToPrinterDialog::on_rename_enter () protected
{
    if (m_is_rename_mode == false) {
        return;
    }
    else {
        m_is_rename_mode = false;
    }
    auto     new_file_name = m_rename_input->GetTextCtrl()->GetValue();
    auto     m_valid_type = Valid;
    wxString info_line;
    const char* unusable_symbols = "<>[]:/\\|?*\"";
    const std::string unusable_suffix = PresetCollection::get_suffix_modified(); //"(modified)";
    for (size_t i = 0; i < std::strlen(unusable_symbols); i++) {
        if (new_file_name.find_first_of(unusable_symbols[i]) != std::string::npos) {
            info_line = _L("Name is invalid;") + "\n" + _L("illegal characters:") + " " + unusable_symbols;
            m_valid_type = NoValid;
            break;
        }
    }
    if (m_valid_type == Valid && new_file_name.find(unusable_suffix) != std::string::npos) {
        info_line = _L("Name is invalid;") + "\n" + _L("illegal suffix:") + "\n\t" + from_u8(PresetCollection::get_suffix_modified());
        m_valid_type = NoValid;
    }
    if (m_valid_type == Valid && new_file_name.empty()) {
        info_line = _L("The name is not allowed to be empty.");
        m_valid_type = NoValid;
    }
    if (m_valid_type == Valid && new_file_name.find_first_of(' ') == 0) {
        info_line = _L("The name is not allowed to start with space character.");
        m_valid_type = NoValid;
    }
    if (m_valid_type == Valid && new_file_name.find_last_of(' ') == new_file_name.length() - 1) {
        info_line = _L("The name is not allowed to end with space character.");
        m_valid_type = NoValid;
    }
    if (m_valid_type != Valid) {
        MessageDialog msg_wingow(nullptr, info_line, "", wxICON_WARNING | wxOK);
        if (msg_wingow.ShowModal() == wxID_OK) {
            m_rename_switch_panel->SetSelection(0);
            m_rename_text->SetLabel(m_current_project_name);
            m_rename_normal_panel->Layout();
            return;
        }
    }
    m_current_project_name = new_file_name;
    m_rename_switch_panel->SetSelection(0);
    m_rename_text->SetLabel(m_current_project_name);
    m_rename_normal_panel->Layout();
}
References _L, Slic3r::GUI::from_u8(), Slic3r::PresetCollection::get_suffix_modified(), TextInput::GetTextCtrl(), m_current_project_name, m_is_rename_mode, m_rename_input, m_rename_normal_panel, m_rename_switch_panel, m_rename_text, NoValid, Slic3r::GUI::DPIAware< P >::ShowModal(), and Valid.
Referenced by SendToPrinterDialog(), and check_focus().
on_selection_changed()
void Slic3r::GUI::SendToPrinterDialog::on_selection_changed (wxCommandEvent & event) protected
{
    /* reset timeout and reading printer info */
    //m_status_bar->reset();
    timeout_count      = 0;
    auto selection = m_comboBox_printer->GetSelection();
    DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    MachineObject* obj = nullptr;
    for (int i = 0; i < m_list.size(); i++) {
        if (i == selection) {
            m_printer_last_select = m_list[i]->dev_id;
            obj = m_list[i];
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << "for send task, current printer id =  " << m_printer_last_select << std::endl;
            break;
        }
    }
    if (obj) {
        obj->command_get_version();
        dev->set_selected_machine(m_printer_last_select);
    } else {
        BOOST_LOG_TRIVIAL(error) << "on_selection_changed dev_id not found";
        return;
    }
    update_show_status();
}
References Slic3r::MachineObject::command_get_version(), Slic3r::MachineObject::dev_id, error, and Slic3r::DeviceManager::set_selected_machine().
Referenced by SendToPrinterDialog().
on_sys_color_changed()
template<class P > virtual void Slic3r::GUI::DPIAware< P >::on_sys_color_changed () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ConfigWizard, Slic3r::GUI::ObjectTableDialog, Slic3r::GUI::MainFrame, Slic3r::GUI::PhysicalPrinterDialog, Slic3r::GUI::PrintHostQueueDialog, Slic3r::GUI::SavePresetDialog, Slic3r::GUI::UnsavedChangesDialog, and Slic3r::GUI::DiffPresetDialog.
{};
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
on_timer()
void Slic3r::GUI::SendToPrinterDialog::on_timer (wxTimerEvent & event) protected
{
    wxGetApp().reset_to_active();
    update_show_status();
}
Referenced by init_bind().
prepare()
void Slic3r::GUI::SendToPrinterDialog::prepare (int print_plate_idx)
{
    m_print_plate_idx = print_plate_idx;
}
prepare_mode()
void Slic3r::GUI::SendToPrinterDialog::prepare_mode ()
{
  m_is_in_sending_mode = false;
  if (m_send_job) {
    m_send_job->join();
  }
  if (wxIsBusy())
    wxEndBusyCursor();
  Enable_Send_Button(true);
    m_status_bar->reset();
  if (m_simplebook->GetSelection() != 0) {
    m_simplebook->SetSelection(0);
  }
}
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
reset_timeout()
void Slic3r::GUI::SendToPrinterDialog::reset_timeout () protected
{
    timeout_count = 0;
}
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
sending_mode()
void Slic3r::GUI::SendToPrinterDialog::sending_mode ()
{
    m_is_in_sending_mode = true;
    if (m_simplebook->GetSelection() != 1){
        m_simplebook->SetSelection(1);
        Layout();
        Fit();
    }
}
set_default()
void Slic3r::GUI::SendToPrinterDialog::set_default () protected
{
    //project name
    m_rename_switch_panel->SetSelection(0);
    wxString filename = m_plater->get_export_gcode_filename("", false,
        m_print_plate_idx == PLATE_ALL_IDX ? true : false);
    if (m_print_plate_idx == PLATE_ALL_IDX && filename.empty()) {
        filename = _L("Untitled");
    }
    if (filename.empty()) {
        filename = m_plater->get_export_gcode_filename("", true);
        if (std::strstr(filename.c_str(), _L("Untitled").c_str()) == NULL) {
            filename = wxString::Format("Untitled%s", filename);
        }
    }
    fs::path filename_path(filename.ToStdWstring());
    m_current_project_name = wxString::FromUTF8(filename_path.filename().string());
    m_rename_text->SetLabelText(m_current_project_name);
    m_rename_normal_panel->Layout();
    enable_prepare_mode = true;
    prepare_mode();
    //clear combobox
    m_list.clear();
    m_comboBox_printer->Clear();
    m_printer_last_select = "";
    m_print_info = "";
    m_comboBox_printer->SetValue(wxEmptyString);
    m_comboBox_printer->Enable();
    // rset status bar
    m_status_bar->reset();
    NetworkAgent* agent = wxGetApp().getAgent();
    if (agent) {
        if (agent->is_user_login()) {
            show_status(PrintDialogStatus::PrintStatusInit);
        } else {
            show_status(PrintDialogStatus::PrintStatusNoUserLogin);
        }
    }
    // thumbmail
    //wxBitmap bitmap;
    ThumbnailData &data   = m_plater->get_partplate_list().get_curr_plate()->thumbnail_data;
    if (data.is_valid()) {
        wxImage image(data.width, data.height);
        image.InitAlpha();
        for (unsigned int r = 0; r < data.height; ++r) {
            unsigned int rr = (data.height - 1 - r) * data.width;
            for (unsigned int c = 0; c < data.width; ++c) {
                unsigned char *px = (unsigned char *) data.pixels.data() + 4 * (rr + c);
                image.SetRGB((int) c, (int) r, px[0], px[1], px[2]);
                image.SetAlpha((int) c, (int) r, px[3]);
            }
        }
        image  = image.Rescale(FromDIP(256), FromDIP(256));
        m_thumbnailPanel->set_thumbnail(image);
    }
    std::vector<std::string> materials;
    std::vector<std::string> display_materials;
    {
        auto preset_bundle = wxGetApp().preset_bundle;
        for (auto filament_name : preset_bundle->filament_presets) {
            for (auto iter = preset_bundle->filaments.lbegin(); iter != preset_bundle->filaments.end(); iter++) {
                if (filament_name.compare(iter->name) == 0) {
                    std::string display_filament_type;
                    std::string filament_type = iter->config.get_filament_type(display_filament_type);
                    display_materials.push_back(display_filament_type);
                    materials.push_back(filament_type);
                }
            }
        }
    }
    m_scrollable_region->Layout();
    m_scrollable_region->Fit();
    Layout();
    Fit();
    wxSize screenSize = wxGetDisplaySize();
    auto dialogSize = this->GetSize();
    // basic info
    auto       aprint_stats = m_plater->get_partplate_list().get_current_fff_print().print_statistics();
    wxString   time;
    PartPlate *plate = m_plater->get_partplate_list().get_curr_plate();
    if (plate) {
        if (plate->get_slice_result()) { time = wxString::Format("%s", get_bbl_monitor_time_dhm(plate->get_slice_result()->print_statistics.modes[0].time)); }
    }
    char weight[64];
    ::sprintf(weight, "  %.2f g", aprint_stats.total_weight);
    m_stext_time->SetLabel(time);
    m_stext_weight->SetLabel(weight);
}
References _L, Slic3r::get_bbl_monitor_time_dhm(), Slic3r::GUI::PartPlate::get_slice_result(), Slic3r::ThumbnailData::height, int, Slic3r::NetworkAgent::is_user_login(), Slic3r::ThumbnailData::is_valid(), Slic3r::PrintEstimatedStatistics::modes, NULL, Slic3r::ThumbnailData::pixels, PLATE_ALL_IDX, Slic3r::GCodeProcessorResult::print_statistics, and Slic3r::ThumbnailData::width.
Show()
bool Slic3r::GUI::SendToPrinterDialog::Show (bool show)
{
    show_status(PrintDialogStatus::PrintStatusInit);
    // set default value when show this dialog
    if (show) {
        wxGetApp().reset_to_active();
        set_default();
        update_user_machine_list();
    }
    if (show) {
        m_refresh_timer->Start(LIST_REFRESH_INTERVAL);
    } else {
        m_refresh_timer->Stop();
    }
    Layout();
    Fit();
    if (show) { CenterOnParent(); }
    return DPIDialog::Show(show);
}
References LIST_REFRESH_INTERVAL.
show_status()
void Slic3r::GUI::SendToPrinterDialog::show_status (PrintDialogStatus status, std::vector< wxString > params = std::vector<wxString>()) protected
{
  if (m_print_status != status)
    BOOST_LOG_TRIVIAL(info) << "select_machine_dialog: show_status = " << status;
  m_print_status = status;
  // m_comboBox_printer
  if (status == PrintDialogStatus::PrintStatusRefreshingMachineList)
    m_comboBox_printer->Disable();
  else
    m_comboBox_printer->Enable();
  // m_panel_warn m_simplebook
  if (status == PrintDialogStatus::PrintStatusSending) {
    sending_mode();
  }
  // other
  if (status == PrintDialogStatus::PrintStatusInit) {
    update_print_status_msg(wxEmptyString, false, false);
    Enable_Send_Button(false);
    Enable_Refresh_Button(true);
  }
  else if (status == PrintDialogStatus::PrintStatusNoUserLogin) {
    wxString msg_text = _L("No login account, only printers in LAN mode are displayed");
    update_print_status_msg(msg_text, false, true);
    Enable_Send_Button(false);
    Enable_Refresh_Button(true);
  }
  else if (status == PrintDialogStatus::PrintStatusInvalidPrinter) {
    update_print_status_msg(wxEmptyString, true, true);
    Enable_Send_Button(false);
    Enable_Refresh_Button(true);
  }
  else if (status == PrintDialogStatus::PrintStatusConnectingServer) {
    wxString msg_text = _L("Connecting to server");
    update_print_status_msg(msg_text, true, true);
    Enable_Send_Button(true);
    Enable_Refresh_Button(true);
  }
  else if (status == PrintDialogStatus::PrintStatusReading) {
    wxString msg_text = _L("Synchronizing device information");
    update_print_status_msg(msg_text, false, true);
    Enable_Send_Button(false);
    Enable_Refresh_Button(true);
  }
  else if (status == PrintDialogStatus::PrintStatusReadingFinished) {
    update_print_status_msg(wxEmptyString, false, true);
    Enable_Send_Button(true);
    Enable_Refresh_Button(true);
  }
  else if (status == PrintDialogStatus::PrintStatusReadingTimeout) {
    wxString msg_text = _L("Synchronizing device information time out");
    update_print_status_msg(msg_text, true, true);
    Enable_Send_Button(true);
    Enable_Refresh_Button(true);
  }
  else if (status == PrintDialogStatus::PrintStatusInUpgrading) {
    wxString msg_text = _L("Cannot send the print task when the upgrade is in progress");
    update_print_status_msg(msg_text, true, true);
    Enable_Send_Button(false);
    Enable_Refresh_Button(true);
  }
  else if (status == PrintDialogStatus::PrintStatusRefreshingMachineList) {
    update_print_status_msg(wxEmptyString, false, true);
    Enable_Send_Button(false);
    Enable_Refresh_Button(false);
  }
  else if (status == PrintDialogStatus::PrintStatusSending) {
    Enable_Send_Button(false);
    Enable_Refresh_Button(false);
  }
  else if (status == PrintDialogStatus::PrintStatusSendingCanceled) {
    Enable_Send_Button(true);
    Enable_Refresh_Button(true);
  }
  else if (status == PrintDialogStatus::PrintStatusNoSdcard) {
    wxString msg_text = _L("An SD card needs to be inserted before send to printer SD card.");
    update_print_status_msg(msg_text, true, true);
    Enable_Send_Button(false);
    Enable_Refresh_Button(true);
    }
    else if (status == PrintDialogStatus::PrintStatusNotOnTheSameLAN) {
        wxString msg_text = _L("The printer is required to be in the same LAN as Orca Slicer.");
        update_print_status_msg(msg_text, true, true);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    }
    else if (status == PrintDialogStatus::PrintStatusNotSupportedSendToSDCard) {
        wxString msg_text = _L("The printer does not support sending to printer SD card.");
        update_print_status_msg(msg_text, true, true);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    }
    else {
    Enable_Send_Button(true);
    Enable_Refresh_Button(true);
    }
}
References _L.
ShowModal()
template<class P > int Slic3r::GUI::DPIAware< P >::ShowModal () inline inherited
    {
        dialogStack.push_front(this);
        int r = wxDialog::ShowModal();
        dialogStack.pop_front();
        return r;
    }
References Slic3r::GUI::dialogStack.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::Sidebar::Sidebar(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), WipingPanel::WipingPanel(), Slic3r::GUI::about(), Slic3r::GUI::GLGizmoSlaSupports::ask_about_changes_call_after(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::GUI_App::check_print_host_queue(), Slic3r::GUI::GUI_App::check_updates(), Slic3r::GUI::Plater::close_with_confirm(), Slic3r::PresetUpdater::config_update(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_language_combobox(), Slic3r::GUI::PreferencesDialog::create_item_region_combobox(), Slic3r::GUI::ObjectList::del_from_cut_object(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::ImageGrid::DoAction(), Slic3r::GUI::MainFrame::export_config(), Slic3r::GUI::generate_help_menu(), Slic3r::GUI::Field::get_value_by_opt_type(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::GUI_App::keyboard_shortcuts(), Slic3r::GUI::MainFrame::load_config_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::load_gcode(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::StatusPanel::on_ams_filament_backup(), Slic3r::GUI::StatusPanel::on_ams_refresh_rfid(), Slic3r::GUI::BindMachineDialog::on_bind_success(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), Slic3r::GUI::GUI_App::on_http_error(), Slic3r::GUI::SelectMachineDialog::on_rename_enter(), on_rename_enter(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::MainFrame::on_select_default_preset(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::AMSMaterialsSetting::on_select_reset(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::PrivacyUpdateDialog::on_show(), Slic3r::GUI::ConfirmBeforeSendDialog::on_show(), Slic3r::GUI::StatusPanel::on_show_print_options(), Slic3r::GUI::MachineInfoPanel::on_show_release_note(), Slic3r::GUI::PA_Calibration_Dlg::on_start(), Slic3r::GUI::Temp_Calibration_Dlg::on_start(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::on_start(), Slic3r::GUI::VFA_Test_Dlg::on_start(), Slic3r::GUI::Retraction_Test_Dlg::on_start(), Slic3r::GUI::StatusPanel::on_start_calibration(), Slic3r::PresetUpdater::on_update_notification_confirm(), Slic3r::GUI::Tab::on_value_change(), Slic3r::GUI::AboutDialog::onCopyrightBtn(), Slic3r::GUI::Plater::open_3mf_file(), Slic3r::GUI::GUI_App::open_preferences(), Slic3r::GUI::MainFrame::open_recent_project(), Slic3r::GUI::ExtrusionCalibration::Popup(), Slic3r::GUI::ObjectTableDialog::Popup(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::GUI::SelectMachineDialog::popup_filament_backup(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::GuideFrame::run(), Slic3r::GUI::ConfigWizard::run(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Plater::save_project(), Slic3r::GUI::Plater::priv::save_project_if_dirty(), Slic3r::GUI::ConfigWizard::priv::select_default_materials_for_printer_models(), Slic3r::GUI::Plater::select_plate_by_hover_id(), Slic3r::GUI::Plater::send_gcode_legacy(), Slic3r::GUI::MachineObjectPanel::show_bind_dialog(), Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), Slic3r::GUI::GUI_App::show_modal_ip_address_enter_dialog(), Slic3r::GUI::StatusPanel::show_recenter_dialog(), Slic3r::GUI::show_send_system_info_dialog_if_needed(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::Tab::show_timelapse_warning_dialog(), Slic3r::GUI::GUI_App::ShowDownNetPluginDlg(), Slic3r::GUI::ObjectList::switch_to_object_process(), Slic3r::GUI::Sidebar::sync_ams_list(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::MediaPlayCtrl::ToggleStream(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), Slic3r::GUI::Plater::priv::update_plugin_when_launch(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::GUI::ConfigManipulation::update_print_sla_config(), Slic3r::GUI::GUI_App::updating_bambu_networking(), Slic3r::GUI::Tab::validate_custom_gcode(), Slic3r::GUI::warning_catcher(), and Slic3r::GUI::Plater::priv::warnings_dialog().
sort_string()
std::vector< std::string > Slic3r::GUI::SendToPrinterDialog::sort_string (std::vector< std::string > strArray) protected
{
    std::vector<std::string> outputArray;
    std::sort(strArray.begin(), strArray.end());
    std::vector<std::string>::iterator st;
    for (st = strArray.begin(); st != strArray.end(); st++) { outputArray.push_back(*st); }
    return outputArray;
}
stripWhiteSpace()
void Slic3r::GUI::SendToPrinterDialog::stripWhiteSpace (std::string & str) protected
{
    if (str == "") { return; }
    string::iterator cur_it;
    cur_it = str.begin();
    while (cur_it != str.end()) {
        if ((*cur_it) == '\n' || (*cur_it) == ' ') {
            cur_it = str.erase(cur_it);
        }
        else {
            cur_it++;
        }
    }
}
update_priner_status_msg()
void Slic3r::GUI::SendToPrinterDialog::update_priner_status_msg (wxString msg, bool is_warning = false) protected
{
    auto colour = is_warning ? wxColour(0xFF, 0x6F, 0x00) : wxColour(0x6B, 0x6B, 0x6B);
    m_statictext_printer_msg->SetForegroundColour(colour);
    if (msg.empty()) {
        if (!m_statictext_printer_msg->GetLabel().empty()) {
            m_statictext_printer_msg->SetLabel(wxEmptyString);
            m_statictext_printer_msg->Hide();
            Layout();
            Fit();
        }
    } else {
        msg          = format_text(msg);
        auto str_new = msg.ToStdString();
        stripWhiteSpace(str_new);
        auto str_old = m_statictext_printer_msg->GetLabel().ToStdString();
        stripWhiteSpace(str_old);
        if (str_new != str_old) {
            if (m_statictext_printer_msg->GetLabel() != msg) {
                m_statictext_printer_msg->SetLabel(msg);
                m_statictext_printer_msg->SetMinSize(wxSize(FromDIP(400), -1));
                m_statictext_printer_msg->SetMaxSize(wxSize(FromDIP(400), -1));
                m_statictext_printer_msg->Wrap(FromDIP(400));
                m_statictext_printer_msg->Show();
                Layout();
                Fit();
            }
        }
    }
}
update_print_status_msg()
void Slic3r::GUI::SendToPrinterDialog::update_print_status_msg (wxString msg, bool is_warning = false, bool is_printer = true) protected
{
    if (is_printer_msg) {
        update_priner_status_msg(msg, is_warning);
    } else {
        update_priner_status_msg(wxEmptyString, false);
    }
}
update_printer_combobox()
void Slic3r::GUI::SendToPrinterDialog::update_printer_combobox (wxCommandEvent & event) protected
{
    show_status(PrintDialogStatus::PrintStatusInit);
    update_user_printer();
}
Referenced by SendToPrinterDialog().
update_show_status()
void Slic3r::GUI::SendToPrinterDialog::update_show_status () protected
{
    NetworkAgent* agent = Slic3r::GUI::wxGetApp().getAgent();
    DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!agent) return;
    if (!dev) return;
    MachineObject* obj_ = dev->get_my_machine(m_printer_last_select);
    if (!obj_) {
        if (agent) {
            if (agent->is_user_login()) {
                show_status(PrintDialogStatus::PrintStatusInvalidPrinter);
            }
            else {
                show_status(PrintDialogStatus::PrintStatusNoUserLogin);
            }
        }
        return;
    }
    /* check cloud machine connections */
    if (!obj_->is_lan_mode_printer()) {
        if (!agent->is_server_connected()) {
            agent->refresh_connection();
            show_status(PrintDialogStatus::PrintStatusConnectingServer);
            reset_timeout();
            return;
        }
    }
    if (!obj_->is_info_ready()) {
        if (is_timeout()) {
            (PrintDialogStatus::PrintStatusReadingTimeout);
            return;
        }
        else {
            timeout_count++;
            show_status(PrintDialogStatus::PrintStatusReading);
            return;
        }
        return;
    }
    reset_timeout();
    bool is_suppt = obj_->is_function_supported(PrinterFunction::FUNC_SEND_TO_SDCARD);
    if (!is_suppt) {
        show_status(PrintDialogStatus::PrintStatusNotSupportedSendToSDCard);
        return;
    }
    // reading done
    if (obj_->is_in_upgrading()) {
        show_status(PrintDialogStatus::PrintStatusInUpgrading);
        return;
    }
    else if (obj_->is_system_printing()) {
        show_status(PrintDialogStatus::PrintStatusInSystemPrinting);
        return;
    }
    // check sdcard when if lan mode printer
   /* if (obj_->is_lan_mode_printer()) {
    }*/
  if (obj_->get_sdcard_state() == MachineObject::SdcardState::NO_SDCARD) {
    show_status(PrintDialogStatus::PrintStatusNoSdcard);
    return;
  }
    if (obj_->dev_ip.empty()) {
        show_status(PrintDialogStatus::PrintStatusNotOnTheSameLAN);
        return;
    }
    show_status(PrintDialogStatus::PrintStatusReadingFinished);
}
References Slic3r::MachineObject::dev_ip, Slic3r::FUNC_SEND_TO_SDCARD, Slic3r::DeviceManager::get_my_machine(), Slic3r::MachineObject::get_sdcard_state(), Slic3r::MachineObject::is_function_supported(), Slic3r::MachineObject::is_in_upgrading(), Slic3r::MachineObject::is_info_ready(), Slic3r::MachineObject::is_lan_mode_printer(), Slic3r::NetworkAgent::is_server_connected(), Slic3r::MachineObject::is_system_printing(), Slic3r::NetworkAgent::is_user_login(), Slic3r::MachineObject::NO_SDCARD, and Slic3r::NetworkAgent::refresh_connection().
update_user_machine_list()
void Slic3r::GUI::SendToPrinterDialog::update_user_machine_list () protected
{
    NetworkAgent* m_agent = wxGetApp().getAgent();
    if (m_agent && m_agent->is_user_login()) {
        boost::thread get_print_info_thread = Slic3r::create_thread([&] {
            NetworkAgent* agent = wxGetApp().getAgent();
            unsigned int http_code;
            std::string body;
            int result = agent->get_user_print_info(&http_code, &body);
            if (result == 0) {
                m_print_info = body;
            }
            else {
                m_print_info = "";
            }
            wxCommandEvent event(EVT_UPDATE_USER_MACHINE_LIST);
            event.SetEventObject(this);
            wxPostEvent(this, event);
        });
    } else {
        wxCommandEvent event(EVT_UPDATE_USER_MACHINE_LIST);
        event.SetEventObject(this);
        wxPostEvent(this, event);
    }
}
References Slic3r::create_thread(), Slic3r::NetworkAgent::get_user_print_info(), and Slic3r::NetworkAgent::is_user_login().
update_user_printer()
void Slic3r::GUI::SendToPrinterDialog::update_user_printer () protected
{
    Slic3r::DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    // update user print info
    if (!m_print_info.empty()) {
        dev->parse_user_print_info(m_print_info);
        m_print_info = "";
    }
    // clear machine list
    m_list.clear();
    m_comboBox_printer->Clear();
    std::vector<std::string>              machine_list;
    wxArrayString                         machine_list_name;
    std::map<std::string, MachineObject*> option_list;
    option_list = dev->get_my_machine_list();
    // same machine only appear once
    for (auto it = option_list.begin(); it != option_list.end(); it++) {
        if (it->second && (it->second->is_online() || it->second->is_connected())) {
            machine_list.push_back(it->second->dev_name);
        }
    }
    machine_list = sort_string(machine_list);
    for (auto tt = machine_list.begin(); tt != machine_list.end(); tt++) {
        for (auto it = option_list.begin(); it != option_list.end(); it++) {
            if (it->second->dev_name == *tt) {
                m_list.push_back(it->second);
                wxString dev_name_text = from_u8(it->second->dev_name);
                if (it->second->is_lan_mode_printer()) {
                    dev_name_text += "(LAN)";
                }
                machine_list_name.Add(dev_name_text);
                break;
            }
        }
    }
    m_comboBox_printer->Set(machine_list_name);
    MachineObject* obj = dev->get_selected_machine();
    if (obj) {
        m_printer_last_select = obj->dev_id;
    } else {
        m_printer_last_select = "";
    }
    if (m_list.size() > 0) {
        // select a default machine
        if (m_printer_last_select.empty()) {
            m_printer_last_select = m_list[0]->dev_id;
            m_comboBox_printer->SetSelection(0);
            wxCommandEvent event(wxEVT_COMBOBOX);
            event.SetEventObject(m_comboBox_printer);
            wxPostEvent(m_comboBox_printer, event);
        }
        for (auto i = 0; i < m_list.size(); i++) {
            if (m_list[i]->dev_id == m_printer_last_select) {
                m_comboBox_printer->SetSelection(i);
                wxCommandEvent event(wxEVT_COMBOBOX);
                event.SetEventObject(m_comboBox_printer);
                wxPostEvent(m_comboBox_printer, event);
            }
        }
    }
    else {
        m_printer_last_select = "";
        m_comboBox_printer->SetTextLabel("");
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << "for send task, current printer id =  " << m_printer_last_select << std::endl;
}
References Slic3r::MachineObject::dev_id, Slic3r::GUI::from_u8(), Slic3r::DeviceManager::get_my_machine_list(), Slic3r::DeviceManager::get_selected_machine(), and Slic3r::DeviceManager::parse_user_print_info().
Member Data Documentation
btn_bg_enable
StateColor Slic3r::GUI::SendToPrinterDialog::btn_bg_enable protected
Referenced by SendToPrinterDialog().
enable_prepare_mode
bool Slic3r::GUI::SendToPrinterDialog::enable_prepare_mode {true} protected
m_bedtype_list
std::vector<wxString> Slic3r::GUI::SendToPrinterDialog::m_bedtype_list private
m_button_cancel
wxButton* Slic3r::GUI::SendToPrinterDialog::m_button_cancel { nullptr } protected
m_button_ensure
Button* Slic3r::GUI::SendToPrinterDialog::m_button_ensure { nullptr } protected
Referenced by SendToPrinterDialog().
m_button_refresh
Button* Slic3r::GUI::SendToPrinterDialog::m_button_refresh { nullptr } protected
Referenced by SendToPrinterDialog().
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_checkbox_list
std::map<std::string, ::CheckBox*> Slic3r::GUI::SendToPrinterDialog::m_checkbox_list private
m_colour_bold_color
wxColour Slic3r::GUI::SendToPrinterDialog::m_colour_bold_color { wxColour(38, 46, 48) } private
Referenced by SendToPrinterDialog().
m_colour_def_color
wxColour Slic3r::GUI::SendToPrinterDialog::m_colour_def_color { wxColour(255, 255, 255) } private
Referenced by SendToPrinterDialog().
m_comboBox_bed
::ComboBox* Slic3r::GUI::SendToPrinterDialog::m_comboBox_bed { nullptr } protected
m_comboBox_printer
::ComboBox* Slic3r::GUI::SendToPrinterDialog::m_comboBox_printer { nullptr } protected
Referenced by SendToPrinterDialog().
m_current_filament_id
int Slic3r::GUI::SendToPrinterDialog::m_current_filament_id protected
m_current_project_name
wxString Slic3r::GUI::SendToPrinterDialog::m_current_project_name protected
Referenced by on_rename_click(), and on_rename_enter().
m_dataViewListCtrl_machines
wxDataViewCtrl* Slic3r::GUI::SendToPrinterDialog::m_dataViewListCtrl_machines { nullptr } protected
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_export_3mf_cancel
bool Slic3r::GUI::SendToPrinterDialog::m_export_3mf_cancel { false }
m_file_name
wxStaticText* Slic3r::GUI::SendToPrinterDialog::m_file_name protected
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_gauge_job_progress
wxGauge* Slic3r::GUI::SendToPrinterDialog::m_gauge_job_progress { nullptr } protected
m_hyperlink_add_machine
wxHyperlinkCtrl* Slic3r::GUI::SendToPrinterDialog::m_hyperlink_add_machine { nullptr } protected
m_is_canceled
bool Slic3r::GUI::SendToPrinterDialog::m_is_canceled { false }
m_is_in_sending_mode
bool Slic3r::GUI::SendToPrinterDialog::m_is_in_sending_mode { false } protected
m_is_rename_mode
bool Slic3r::GUI::SendToPrinterDialog::m_is_rename_mode {false} protected
Referenced by on_rename_click(), and on_rename_enter().
m_line_materia
wxPanel* Slic3r::GUI::SendToPrinterDialog::m_line_materia { nullptr } protected
Referenced by SendToPrinterDialog().
m_line_schedule
wxPanel* Slic3r::GUI::SendToPrinterDialog::m_line_schedule { nullptr } protected
Referenced by SendToPrinterDialog().
m_line_top
wxPanel* Slic3r::GUI::SendToPrinterDialog::m_line_top { nullptr } protected
Referenced by SendToPrinterDialog().
m_list
std::vector<MachineObject*> Slic3r::GUI::SendToPrinterDialog::m_list protected
m_need_adaptation_screen
bool Slic3r::GUI::SendToPrinterDialog::m_need_adaptation_screen { false } protected
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_panel_finish
wxPanel* Slic3r::GUI::SendToPrinterDialog::m_panel_finish { nullptr } protected
Referenced by SendToPrinterDialog().
m_panel_image
wxPanel* Slic3r::GUI::SendToPrinterDialog::m_panel_image { nullptr } protected
Referenced by SendToPrinterDialog().
m_panel_prepare
wxPanel* Slic3r::GUI::SendToPrinterDialog::m_panel_prepare { nullptr } protected
Referenced by SendToPrinterDialog().
m_panel_sending
wxPanel* Slic3r::GUI::SendToPrinterDialog::m_panel_sending { nullptr } protected
Referenced by SendToPrinterDialog().
m_panel_status
wxPanel* Slic3r::GUI::SendToPrinterDialog::m_panel_status { nullptr } protected
m_plater
Plater* Slic3r::GUI::SendToPrinterDialog::m_plater { nullptr } protected
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_print_info
std::string Slic3r::GUI::SendToPrinterDialog::m_print_info protected
m_print_plate_idx
int Slic3r::GUI::SendToPrinterDialog::m_print_plate_idx private
m_print_status
PrintDialogStatus Slic3r::GUI::SendToPrinterDialog::m_print_status { PrintStatusInit } private
m_printer_last_select
std::string Slic3r::GUI::SendToPrinterDialog::m_printer_last_select private
m_refresh_timer
wxTimer* Slic3r::GUI::SendToPrinterDialog::m_refresh_timer { nullptr } protected
m_rename_button
Button* Slic3r::GUI::SendToPrinterDialog::m_rename_button { nullptr } protected
Referenced by SendToPrinterDialog().
m_rename_input
TextInput* Slic3r::GUI::SendToPrinterDialog::m_rename_input { nullptr } protected
Referenced by SendToPrinterDialog(), check_focus(), on_rename_click(), and on_rename_enter().
m_rename_normal_panel
wxPanel* Slic3r::GUI::SendToPrinterDialog::m_rename_normal_panel { nullptr } protected
Referenced by SendToPrinterDialog(), and on_rename_enter().
m_rename_switch_panel
wxSimplebook* Slic3r::GUI::SendToPrinterDialog::m_rename_switch_panel { nullptr } protected
Referenced by SendToPrinterDialog(), on_rename_click(), and on_rename_enter().
m_rename_text
wxStaticText* Slic3r::GUI::SendToPrinterDialog::m_rename_text { nullptr } protected
Referenced by SendToPrinterDialog(), and on_rename_enter().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
m_scrollable_region
wxPanel* Slic3r::GUI::SendToPrinterDialog::m_scrollable_region protected
Referenced by SendToPrinterDialog().
m_send_job
std::shared_ptr<SendJob> Slic3r::GUI::SendToPrinterDialog::m_send_job {nullptr} protected
m_simplebook
wxSimplebook* Slic3r::GUI::SendToPrinterDialog::m_simplebook { nullptr } protected
Referenced by SendToPrinterDialog().
m_sizer_bottom
wxBoxSizer* Slic3r::GUI::SendToPrinterDialog::m_sizer_bottom protected
Referenced by SendToPrinterDialog().
m_sizer_main
wxBoxSizer* Slic3r::GUI::SendToPrinterDialog::m_sizer_main protected
Referenced by SendToPrinterDialog().
m_sizer_scrollable_region
wxBoxSizer* Slic3r::GUI::SendToPrinterDialog::m_sizer_scrollable_region protected
Referenced by SendToPrinterDialog().
m_staticbitmap
wxStaticBitmap* Slic3r::GUI::SendToPrinterDialog::m_staticbitmap { nullptr } protected
m_staticText_bed_title
wxStaticText* Slic3r::GUI::SendToPrinterDialog::m_staticText_bed_title { nullptr } protected
m_statictext_finish
wxStaticText* Slic3r::GUI::SendToPrinterDialog::m_statictext_finish { nullptr } protected
Referenced by SendToPrinterDialog().
m_staticText_left
wxStaticText* Slic3r::GUI::SendToPrinterDialog::m_staticText_left { nullptr } protected
m_statictext_printer_msg
wxStaticText* Slic3r::GUI::SendToPrinterDialog::m_statictext_printer_msg { nullptr } protected
Referenced by SendToPrinterDialog(), and format_text().
m_status_bar
std::shared_ptr<BBLStatusBarSend> Slic3r::GUI::SendToPrinterDialog::m_status_bar
Referenced by SendToPrinterDialog().
m_stext_printer_title
wxStaticText* Slic3r::GUI::SendToPrinterDialog::m_stext_printer_title { nullptr } protected
Referenced by SendToPrinterDialog().
m_stext_sending
wxStaticText* Slic3r::GUI::SendToPrinterDialog::m_stext_sending { nullptr } protected
m_stext_time
wxStaticText* Slic3r::GUI::SendToPrinterDialog::m_stext_time { nullptr } protected
Referenced by SendToPrinterDialog().
m_stext_weight
wxStaticText* Slic3r::GUI::SendToPrinterDialog::m_stext_weight { nullptr } protected
Referenced by SendToPrinterDialog().
m_thumbnailPanel
ThumbnailPanel* Slic3r::GUI::SendToPrinterDialog::m_thumbnailPanel { nullptr } protected
Referenced by SendToPrinterDialog().
machine_model
wxObjectDataPtr<MachineListModel> Slic3r::GUI::SendToPrinterDialog::machine_model
rename_sizer_h
wxBoxSizer* Slic3r::GUI::SendToPrinterDialog::rename_sizer_h { nullptr } protected
Referenced by SendToPrinterDialog().
rename_sizer_v
wxBoxSizer* Slic3r::GUI::SendToPrinterDialog::rename_sizer_v { nullptr } protected
Referenced by SendToPrinterDialog().
sizer_thumbnail
wxBoxSizer* Slic3r::GUI::SendToPrinterDialog::sizer_thumbnail protected
Referenced by SendToPrinterDialog().
timeout_count
int Slic3r::GUI::SendToPrinterDialog::timeout_count = 0 protected
The documentation for this class was generated from the following files:
src/slic3r/GUI/SendToPrinter.hpp
src/slic3r/GUI/SendToPrinter.cpp