OrcaSlicer: Slic3r::GUI::GuideFrame Class Reference
Slic3r::GUI::GuideFrame Class Reference
#include <src/slic3r/GUI/WebGuideDialog.hpp>
Public Types
enum GuidePage {
BBL_WELCOME , BBL_REGION , BBL_MODELS , BBL_FILAMENTS ,
BBL_FILAMENT_ONLY , BBL_MODELS_ONLY
}
Public Member Functions
GuideFrame (GUI_App *pGUI, long style=wxCAPTION|wxCLOSE_BOX|wxSYSTEM_MENU)
virtual ~GuideFrame ()
void load_url (wxString &url)
wxString SetStartPage (GuidePage startpage=BBL_WELCOME, bool load=true)
void UpdateState ()
void OnIdle (wxIdleEvent &evt)
void OnNavigationRequest (wxWebViewEvent &evt)
void OnNavigationComplete (wxWebViewEvent &evt)
void OnDocumentLoaded (wxWebViewEvent &evt)
void OnNewWindow (wxWebViewEvent &evt)
void OnError (wxWebViewEvent &evt)
void OnTitleChanged (wxWebViewEvent &evt)
void OnFullScreenChanged (wxWebViewEvent &evt)
void OnScriptMessage (wxWebViewEvent &evt)
void OnScriptResponseMessage (wxCommandEvent &evt)
void RunScript (const wxString &javascript)
bool IsFirstUse ()
int LoadProfile ()
int LoadProfileFamily (std::string strVendor, std::string strFilePath)
int SaveProfile ()
int GetFilamentInfo (std::string VendorDirectory, json &pFilaList, std::string filepath, std::string &sVendor, std::string &sType)
bool apply_config (AppConfig *app_config, PresetBundle *preset_bundle, const PresetUpdater *updater, bool &apply_keeped_changes)
bool run ()
void StrReplace (std::string &strBase, std::string strSrc, std::string strDes)
std::string w2s (wxString sSrc)
void GetStardardFilePath (std::string &FilePath)
bool LoadFile (std::string jPath, std::string &sContent)
int DownloadPlugin ()
int InstallPlugin ()
int ShowPluginStatus (int status, int percent, bool &cancel)
void on_dpi_changed (const wxRect &suggested_rect)
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
int ShowModal ()
Public Attributes
enum Slic3r::GUI::GuideFrame::GuidePage m_page
Protected Member Functions
virtual void on_sys_color_changed ()
Private Member Functions
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
GUI_App * m_MainPtr
AppConfig m_appconfig_new
wxWebView * m_browser
wxButton * m_TestBtn
wxString m_SectionName
bool bbl_bundle_rsrc
boost::filesystem::path vendor_dir
boost::filesystem::path rsrc_vendor_dir
bool PrivacyUse
std::string m_Region
bool InstallNetplugin
bool network_plugin_ready {false}
wxString m_javascript
wxString m_response_js
wxString m_bbl_user_agent
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Member Enumeration Documentation
GuidePage
enum Slic3r::GUI::GuideFrame::GuidePage
Enumerator
BBL_WELCOME
BBL_REGION
BBL_MODELS
BBL_FILAMENTS
BBL_FILAMENT_ONLY
BBL_MODELS_ONLY
                   {
        BBL_WELCOME,
        BBL_REGION,
        BBL_MODELS,
        BBL_FILAMENTS,
        BBL_FILAMENT_ONLY,
        BBL_MODELS_ONLY
    }m_page;
Constructor & Destructor Documentation
GuideFrame()
Slic3r::GUI::GuideFrame::GuideFrame (GUI_App * pGUI, long style = wxCAPTION | wxCLOSE_BOX | wxSYSTEM_MENU)
    : DPIDialog((wxWindow *) (pGUI->mainframe), wxID_ANY, "OrcaSlicer", wxDefaultPosition, wxDefaultSize, style),
  m_appconfig_new()
{
    SetBackgroundColour(*wxWHITE);
    // INI
    m_SectionName = "firstguide";
    PrivacyUse    = false;
    InstallNetplugin = false;
    m_MainPtr = pGUI;
    // set the frame icon
    wxBoxSizer *topsizer = new wxBoxSizer(wxVERTICAL);
    wxString TargetUrl = SetStartPage(BBL_WELCOME, false);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(",  set start page to welcome ");
    // Create the webview
    m_browser = WebView::CreateWebView(this, TargetUrl);
    if (m_browser == nullptr) {
        wxLogError("Could not init m_browser");
        return;
    }
    m_browser->Hide();
    m_browser->SetSize(0, 0);
    SetSizer(topsizer);
    topsizer->Add(m_browser, wxSizerFlags().Expand().Proportion(1));
    // Log backend information
    // wxLogMessage(wxWebView::GetBackendVersionInfo().ToString());
    // wxLogMessage("Backend: %s Version: %s",
    // m_browser->GetClassInfo()->GetClassName(),wxWebView::GetBackendVersionInfo().ToString());
    // wxLogMessage("User Agent: %s", m_browser->GetUserAgent());
    // Set a more sensible size for web browsing
    wxSize pSize = FromDIP(wxSize(820, 660));
    SetSize(pSize);
    int screenheight = wxSystemSettings::GetMetric(wxSYS_SCREEN_Y, NULL);
    int screenwidth  = wxSystemSettings::GetMetric(wxSYS_SCREEN_X, NULL);
    int MaxY         = (screenheight - pSize.y) > 0 ? (screenheight - pSize.y) / 2 : 0;
    wxPoint tmpPT((screenwidth - pSize.x) / 2, MaxY);
    Move(tmpPT);
#ifdef __WXMSW__
    this->Bind(wxEVT_CHAR_HOOK, [this](wxKeyEvent& e) {
        if ((m_page == BBL_FILAMENT_ONLY || m_page == BBL_MODELS_ONLY) && e.GetKeyCode() == WXK_ESCAPE) {
            if (this->IsModal())
                this->EndModal(wxID_CANCEL);
            else
                this->Close();
        }
        else
            e.Skip();
        });
#endif
    // Connect the webview events
    Bind(wxEVT_WEBVIEW_NAVIGATING, &GuideFrame::OnNavigationRequest, this, m_browser->GetId());
    Bind(wxEVT_WEBVIEW_NAVIGATED, &GuideFrame::OnNavigationComplete, this, m_browser->GetId());
    Bind(wxEVT_WEBVIEW_LOADED, &GuideFrame::OnDocumentLoaded, this, m_browser->GetId());
    Bind(wxEVT_WEBVIEW_ERROR, &GuideFrame::OnError, this, m_browser->GetId());
    Bind(wxEVT_WEBVIEW_NEWWINDOW, &GuideFrame::OnNewWindow, this, m_browser->GetId());
    Bind(wxEVT_WEBVIEW_TITLE_CHANGED, &GuideFrame::OnTitleChanged, this, m_browser->GetId());
    Bind(wxEVT_WEBVIEW_FULLSCREEN_CHANGED, &GuideFrame::OnFullScreenChanged, this, m_browser->GetId());
    Bind(wxEVT_WEBVIEW_SCRIPT_MESSAGE_RECEIVED, &GuideFrame::OnScriptMessage, this, m_browser->GetId());
    // Connect the idle events
    // Bind(wxEVT_IDLE, &GuideFrame::OnIdle, this);
    // Bind(wxEVT_CLOSE_WINDOW, &GuideFrame::OnClose, this);
    LoadProfile();
    // UI
    SetStartPage(BBL_REGION);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(",  finished");
    wxGetApp().UpdateDlgDarkUI(this);
}
References BBL_FILAMENT_ONLY, BBL_MODELS_ONLY, BBL_REGION, BBL_WELCOME, WebView::CreateWebView(), InstallNetplugin, LoadProfile(), m_browser, m_MainPtr, m_page, m_SectionName, NULL, OnDocumentLoaded(), OnError(), OnFullScreenChanged(), OnNavigationComplete(), OnNavigationRequest(), OnNewWindow(), OnScriptMessage(), OnTitleChanged(), PrivacyUse, and SetStartPage().
~GuideFrame()
Slic3r::GUI::GuideFrame::~GuideFrame () virtual
{
    if (m_browser) {
        delete m_browser;
        m_browser = nullptr;
    }
}
References m_browser.
Member Function Documentation
apply_config()
bool Slic3r::GUI::GuideFrame::apply_config (AppConfig * app_config, PresetBundle * preset_bundle, const PresetUpdater * updater, bool & apply_keeped_changes)
{
    const auto enabled_vendors = m_appconfig_new.vendors();
    const auto old_enabled_vendors = app_config->vendors();
    const auto enabled_filaments = m_appconfig_new.has_section(AppConfig::SECTION_FILAMENTS) ? m_appconfig_new.get_section(AppConfig::SECTION_FILAMENTS) : std::map<std::string, std::string>();
    const auto old_enabled_filaments = app_config->has_section(AppConfig::SECTION_FILAMENTS) ? app_config->get_section(AppConfig::SECTION_FILAMENTS) : std::map<std::string, std::string>();
    bool check_unsaved_preset_changes = false;
    std::vector<std::string> install_bundles;
    std::vector<std::string> remove_bundles;
    const auto vendor_dir = (boost::filesystem::path(Slic3r::data_dir()) / PRESET_SYSTEM_DIR).make_preferred();
    for (const auto &it : enabled_vendors) {
        if (it.second.size() > 0) {
            auto vendor_file = vendor_dir/(it.first + ".json");
            if (!fs::exists(vendor_file)) {
                install_bundles.emplace_back(it.first);
            }
        }
    }
    //add the removed vendor bundles
    for (const auto &it : old_enabled_vendors) {
        if (it.second.size() > 0) {
            if (enabled_vendors.find(it.first) != enabled_vendors.end())
                continue;
            auto vendor_file = vendor_dir/(it.first + ".json");
            if (fs::exists(vendor_file)) {
                remove_bundles.emplace_back(it.first);
            }
        }
    }
    check_unsaved_preset_changes = (enabled_vendors != old_enabled_vendors) || (enabled_filaments != old_enabled_filaments);
    wxString header = _L("The configuration package is changed in previous Config Guide");
    wxString caption = _L("Configuration package changed");
    int act_btns = UnsavedChangesDialog::ActionButtons::KEEP|UnsavedChangesDialog::ActionButtons::SAVE;
    if (check_unsaved_preset_changes &&
        !wxGetApp().check_and_keep_current_preset_changes(caption, header, act_btns, &apply_keeped_changes))
        return false;
    if (install_bundles.size() > 0) {
        // Install bundles from resources.
        // Don't create snapshot - we've already done that above if applicable.
        if (! updater->install_bundles_rsrc(std::move(install_bundles), false))
            return false;
    } else {
        BOOST_LOG_TRIVIAL(info) << "No bundles need to be installed from resource directory";
    }
    if (remove_bundles.size() > 0) {
        //remove unused bundles
        for (const auto &it : remove_bundles) {
            auto vendor_file = vendor_dir/(it + ".json");
            auto sub_dir = vendor_dir/(it);
            if (fs::exists(vendor_file))
                fs::remove(vendor_file);
            if (fs::exists(sub_dir))
                fs::remove_all(sub_dir);
        }
    } else {
        BOOST_LOG_TRIVIAL(info) << "No bundles need to be removed";
    }
    std::string preferred_model;
    std::string preferred_variant;
    PrinterTechnology preferred_pt = ptFFF;
    auto get_preferred_printer_model = [preset_bundle, enabled_vendors, old_enabled_vendors, preferred_pt](const std::string& bundle_name, std::string& variant) {
        const auto config = enabled_vendors.find(bundle_name);
        if (config == enabled_vendors.end())
            return std::string();
        const std::map<std::string, std::set<std::string>>& model_maps = config->second;
        //for (const auto& vendor_profile : preset_bundle->vendors) {
        for (const auto model_it: model_maps) {
            if (model_it.second.size() > 0) {
                variant = *model_it.second.begin();
                const auto config_old = old_enabled_vendors.find(bundle_name);
                if (config_old == old_enabled_vendors.end())
                    return model_it.first;
                const auto model_it_old = config_old->second.find(model_it.first);
                if (model_it_old == config_old->second.end())
                    return model_it.first;
                else if (model_it_old->second != model_it.second) {
                    for (const auto& var : model_it.second)
                        if (model_it_old->second.find(var) == model_it_old->second.end()) {
                            variant = var;
                            return model_it.first;
                        }
                }
            }
        }
        //}
        if (!variant.empty())
            variant.clear();
        return std::string();
    };
    // Prusa printers are considered first, then 3rd party.
    if (preferred_model = get_preferred_printer_model(PresetBundle::BBL_BUNDLE, preferred_variant);
        preferred_model.empty()) {
        for (const auto& bundle : enabled_vendors) {
            if (bundle.first == PresetBundle::BBL_BUNDLE) { continue; }
            if (preferred_model = get_preferred_printer_model(bundle.first, preferred_variant);
                !preferred_model.empty())
                    break;
        }
    }
    std::string first_added_filament;
    auto get_first_added_material_preset = [this, app_config](const std::string& section_name, std::string& first_added_preset) {
        if (m_appconfig_new.has_section(section_name)) {
            // get first of new added preset names
            const std::map<std::string, std::string>& old_presets = app_config->has_section(section_name) ? app_config->get_section(section_name) : std::map<std::string, std::string>();
            first_added_preset = get_first_added_preset(old_presets, m_appconfig_new.get_section(section_name));
        }
    };
    // Not switch filament
    //get_first_added_material_preset(AppConfig::SECTION_FILAMENTS, first_added_filament);
    //update the app_config
    app_config->set_section(AppConfig::SECTION_FILAMENTS, enabled_filaments);
    app_config->set_vendors(m_appconfig_new);
    if (check_unsaved_preset_changes)
        preset_bundle->load_presets(*app_config, ForwardCompatibilitySubstitutionRule::EnableSilentDisableSystem,
                                    {preferred_model, preferred_variant, first_added_filament, std::string()});
    // Update the selections from the compatibilty.
    preset_bundle->export_selections(*app_config);
    return true;
}
References _L, Slic3r::PresetBundle::BBL_BUNDLE, Slic3r::data_dir(), Slic3r::EnableSilentDisableSystem, Slic3r::PresetBundle::export_selections(), Slic3r::GUI::get_first_added_preset(), Slic3r::AppConfig::get_section(), Slic3r::AppConfig::has_section(), Slic3r::PresetUpdater::install_bundles_rsrc(), Slic3r::GUI::UnsavedChangesDialog::KEEP, Slic3r::PresetBundle::load_presets(), m_appconfig_new, PRESET_SYSTEM_DIR, Slic3r::ptFFF, Slic3r::GUI::UnsavedChangesDialog::SAVE, Slic3r::AppConfig::SECTION_FILAMENTS, Slic3r::AppConfig::set_section(), Slic3r::AppConfig::set_vendors(), Slic3r::var(), vendor_dir, and Slic3r::AppConfig::vendors().
Referenced by run().
DownloadPlugin()
int Slic3r::GUI::GuideFrame::DownloadPlugin ()
{
    return wxGetApp().download_plugin(
        "plugins", "network_plugin.zip",
        [this](int status, int percent, bool& cancel) {
            return ShowPluginStatus(status, percent, cancel);
        }
    , nullptr);
}
References ShowPluginStatus().
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AuxiliaryDialog::AuxiliaryDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::ParamsDialog::ParamsDialog(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), em_unit(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::AuxiliaryDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ObjectTableDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::ParamsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
GetFilamentInfo()
int Slic3r::GUI::GuideFrame::GetFilamentInfo (std::string VendorDirectory, json & pFilaList, std::string filepath, std::string & sVendor, std::string & sType)
{
    //GetStardardFilePath(filepath);
    try {
        std::string contents;
        LoadFile(filepath, contents);
        json jLocal = json::parse(contents);
        if (sVendor == "") {
            if (jLocal.contains("filament_vendor"))
                sVendor = jLocal["filament_vendor"][0];
        }
        if (sType == "") {
            if (jLocal.contains("filament_type"))
                sType = jLocal["filament_type"][0];
        }
        if (sVendor == "" || sType == "")
        {
            if (jLocal.contains("inherits")) {
                std::string FName = jLocal["inherits"];
                if (!pFilaList.contains(FName))
                    return -1;
                std::string FPath = pFilaList[FName]["sub_path"];
                wxString                strNewFile    = wxString::Format("%s%c%s", VendorDirectory, boost::filesystem::path::preferred_separator, FPath);
                boost::filesystem::path inherits_path = boost::filesystem::absolute(w2s(strNewFile)).make_preferred();
                //boost::filesystem::path nf(strNewFile.c_str());
                if (boost::filesystem::exists(inherits_path))
                    return GetFilamentInfo(VendorDirectory,pFilaList, inherits_path.string(), sVendor, sType);
                else
                    return -1;
            } else {
                if (sType == "")
                    return -1;
                else
                    sVendor = "Generic";
                    return 0;
            }
        }
        else
            return 0;
    }
    catch(nlohmann::detail::parse_error &err) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<<filepath <<" got a nlohmann::detail::parse_error, reason = " << err.what();
        return -1;
    }
    catch (std::exception &e)
    {
        // wxLogMessage("GUIDE: load_profile_error  %s ", e.what());
        // wxMessageBox(e.what(), "", MB_OK);
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse " << filepath <<" got exception: "<<e.what();
        return -1;
    }
    return 0;
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), error, GetFilamentInfo(), LoadFile(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::string, w2s(), and nlohmann::detail::exception::what().
Referenced by GetFilamentInfo(), and LoadProfileFamily().
GetStardardFilePath()
void Slic3r::GUI::GuideFrame::GetStardardFilePath (std::string & FilePath)
{
    StrReplace(FilePath, "\\", w2s(wxString::Format("%c", boost::filesystem::path::preferred_separator)));
    StrReplace(FilePath, "\/", w2s(wxString::Format("%c", boost::filesystem::path::preferred_separator)));
}
References StrReplace(), and w2s().
InstallPlugin()
int Slic3r::GUI::GuideFrame::InstallPlugin ()
{
    return wxGetApp().install_plugin("plugins", "network_plugin.zip",
        [this](int status, int percent, bool &cancel) {
            return ShowPluginStatus(status, percent, cancel);
        }
    );
}
References ShowPluginStatus().
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
IsFirstUse()
bool Slic3r::GUI::GuideFrame::IsFirstUse ()
{
    wxString    strUse;
    std::string strVal = wxGetApp().app_config->get(std::string(m_SectionName.mb_str()), "finish");
    if (strVal == "1")
        return false;
    if (bbl_bundle_rsrc == true)
        return true;
    return true;
}
References bbl_bundle_rsrc, and m_SectionName.
load_url()
void Slic3r::GUI::GuideFrame::load_url (wxString & url)
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< " enter, url=" << url.ToStdString();
    WebView::LoadUrl(m_browser, url);
    m_browser->SetFocus();
    UpdateState();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< " exit";
}
References WebView::LoadUrl(), m_browser, and UpdateState().
Referenced by SetStartPage().
LoadFile()
bool Slic3r::GUI::GuideFrame::LoadFile (std::string jPath, std::string & sContent)
{
    try {
        boost::nowide::ifstream t(jPath);
        std::stringstream buffer;
        buffer << t.rdbuf();
        sContent=buffer.str();
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", load %1% into buffer")% jPath;
    }
    catch (std::exception &e)
    {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ",  got exception: "<<e.what();
        return false;
    }
    return true;
}
References buffer, and error.
Referenced by GetFilamentInfo(), and LoadProfileFamily().
LoadProfile()
int Slic3r::GUI::GuideFrame::LoadProfile ()
{
    try {
        //wxString ExePath            = boost::dll::program_location().parent_path().string();
        //wxString TargetFolder       = ExePath + "\\resources\\profiles\\";
        //wxString TargetFolderSearch = ExePath + "\\resources\\profiles\\*.json";
        //intptr_t    handle;
        //_finddata_t findData;
        //handle = _findfirst(TargetFolderSearch.mb_str(), &findData); //
        //if (handle == -1) { return -1; }
        //do {
        //    if (findData.attrib & _A_SUBDIR && strcmp(findData.name, ".") == 0 && strcmp(findData.name, "..") == 0) // "."".."
        //    {
        //        // cout << findData.name << "\t<dir>\n";
        //    } else {
        //        wxString strVendor = wxString(findData.name).BeforeLast('.');
        //        LoadProfileFamily(strVendor, TargetFolder + findData.name);
        //    }
        //} while (_findnext(handle, &findData) == 0); //
        // BBS: change directories by design
        //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(",  will load config from %1%.") % bbl_bundle_path;
        m_ProfileJson             = json::parse("{}");
        m_ProfileJson["model"]    = json::array();
        m_ProfileJson["machine"]  = json::object();
        m_ProfileJson["filament"] = json::object();
        m_ProfileJson["process"]  = json::array();
        vendor_dir      = (boost::filesystem::path(Slic3r::data_dir()) / PRESET_SYSTEM_DIR ).make_preferred();
        rsrc_vendor_dir = (boost::filesystem::path(resources_dir()) / "profiles").make_preferred();
        // BBS: add BBL as default
        // BBS: add json logic for vendor bundle
        auto bbl_bundle_path = vendor_dir;
        bbl_bundle_rsrc = false;
        if (!boost::filesystem::exists((vendor_dir / PresetBundle::BBL_BUNDLE).replace_extension(".json"))) {
            bbl_bundle_path = rsrc_vendor_dir;
            bbl_bundle_rsrc = true;
        }
        // intptr_t    handle;
        //_finddata_t findData;
        //handle = _findfirst((bbl_bundle_path / "*.json").make_preferred().string().c_str(), &findData); //
        // if (handle == -1) { return -1; }
        // do {
        //    if (findData.attrib & _A_SUBDIR && strcmp(findData.name, ".") == 0 && strcmp(findData.name, "..") == 0) // "."".."
        //    {
        //        // cout << findData.name << "\t<dir>\n";
        //    } else {
        //        wxString strVendor = wxString(findData.name).BeforeLast('.');
        //        LoadProfileFamily(w2s(strVendor), vendor_dir.make_preferred().string() + "\\"+ findData.name);
        //    }
        //} while (_findnext(handle, &findData) == 0); //
        //load BBL bundle from user data path
        string                                targetPath = bbl_bundle_path.make_preferred().string();
        boost::filesystem::path               myPath(targetPath);
        boost::filesystem::directory_iterator endIter;
        for (boost::filesystem::directory_iterator iter(myPath); iter != endIter; iter++) {
            if (boost::filesystem::is_directory(*iter)) {
                //cout << "is dir" << endl;
                //cout << iter->path().string() << endl;
            } else {
                //cout << "is a file" << endl;
                //cout << iter->path().string() << endl;
                wxString strVendor = from_u8(iter->path().string()).BeforeLast('.');
                strVendor          = strVendor.AfterLast( '\\');
                strVendor          = strVendor.AfterLast('\/');
                if (w2s(strVendor) == PresetBundle::BBL_BUNDLE)
                    LoadProfileFamily(w2s(strVendor), iter->path().string());
            }
        }
        //string                                others_targetPath = rsrc_vendor_dir.string();
        boost::filesystem::directory_iterator others_endIter;
        for (boost::filesystem::directory_iterator iter(rsrc_vendor_dir); iter != others_endIter; iter++) {
            if (boost::filesystem::is_directory(*iter)) {
                //cout << "is dir" << endl;
                //cout << iter->path().string() << endl;
            } else {
                //cout << "is a file" << endl;
                //cout << iter->path().string() << endl;
                wxString strVendor = from_u8(iter->path().string()).BeforeLast('.');
                strVendor          = strVendor.AfterLast( '\\');
                strVendor          = strVendor.AfterLast('\/');
                if (w2s(strVendor) != PresetBundle::BBL_BUNDLE)
                    LoadProfileFamily(w2s(strVendor), iter->path().string());
            }
        }
        //LoadProfileFamily(PresetBundle::BBL_BUNDLE, bbl_bundle_path.string());
        const auto enabled_filaments = wxGetApp().app_config->has_section(AppConfig::SECTION_FILAMENTS) ? wxGetApp().app_config->get_section(AppConfig::SECTION_FILAMENTS) : std::map<std::string, std::string>();
        m_appconfig_new.set_vendors(*wxGetApp().app_config);
        m_appconfig_new.set_section(AppConfig::SECTION_FILAMENTS, enabled_filaments);
        for (auto it = m_ProfileJson["model"].begin(); it != m_ProfileJson["model"].end(); ++it)
        {
            if (it.value().is_object()) {
                json& temp_model = it.value();
                std::string model_name = temp_model["model"];
                std::string vendor_name = temp_model["vendor"];
                std::string nozzle_diameter = temp_model["nozzle_diameter"];
                std::string selected;
                boost::trim(nozzle_diameter);
                std::string nozzle;
                bool enabled = false, first=true;
                while (nozzle_diameter.size() > 0) {
                    auto pos = nozzle_diameter.find(';');
                    if (pos != std::string::npos) {
                        nozzle   = nozzle_diameter.substr(0, pos);
                        enabled = m_appconfig_new.get_variant(vendor_name, model_name, nozzle);
                        if (enabled) {
                            if (!first)
                                selected += ";";
                            selected += nozzle;
                            first = false;
                        }
                        nozzle_diameter = nozzle_diameter.substr(pos + 1);
                        boost::trim(nozzle_diameter);
                    }
                    else {
                        enabled = m_appconfig_new.get_variant(vendor_name, model_name, nozzle_diameter);
                        if (enabled) {
                            if (!first)
                                selected += ";";
                            selected += nozzle_diameter;
                        }
                        break;
                    }
                }
                temp_model["nozzle_selected"] = selected;
                //m_ProfileJson["model"][a]["nozzle_selected"]
            }
        }
        if (m_ProfileJson["model"].size() == 1) {
            std::string strNozzle = m_ProfileJson["model"][0]["nozzle_diameter"];
            m_ProfileJson["model"][0]["nozzle_selected"]=strNozzle;
        }
        for (auto it = m_ProfileJson["filament"].begin(); it != m_ProfileJson["filament"].end(); ++it) {
            //json temp_filament = it.value();
            std::string filament_name = it.key();
            if (enabled_filaments.find(filament_name) != enabled_filaments.end())
                m_ProfileJson["filament"][filament_name]["selected"] = 1;
        }
        //----region
        m_Region = wxGetApp().app_config->get("region");
        m_ProfileJson["region"] = m_Region;
        m_ProfileJson["network_plugin_install"] = wxGetApp().app_config->get("app","installed_networking");
        m_ProfileJson["network_plugin_compability"] = wxGetApp().is_compatibility_version() ? "1" : "0";
        network_plugin_ready = wxGetApp().is_compatibility_version();
    }
    catch (std::exception &e) {
        //wxLogMessage("GUIDE: load_profile_error  %s ", e.what());
        // wxMessageBox(e.what(), "", MB_OK);
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ", error: "<< e.what() <<std::endl;
    }
    std::string strAll = m_ProfileJson.dump(-1, ' ', false, json::error_handler_t::ignore);
    //wxLogMessage("GUIDE: profile_json_s2  %s ", m_ProfileJson.dump(-1, ' ', false, json::error_handler_t::ignore));
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ", finished, json contents: "<< std::endl<<strAll;
    return 0;
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::array, Slic3r::PresetBundle::BBL_BUNDLE, bbl_bundle_rsrc, Slic3r::data_dir(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::end(), error, Slic3r::GUI::from_u8(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), Slic3r::AppConfig::get_variant(), LoadProfileFamily(), m_appconfig_new, Slic3r::GUI::m_ProfileJson, m_Region, network_plugin_ready, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::object(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), PRESET_SYSTEM_DIR, Slic3r::resources_dir(), rsrc_vendor_dir, Slic3r::AppConfig::SECTION_FILAMENTS, Slic3r::AppConfig::set_section(), Slic3r::AppConfig::set_vendors(), size, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::value(), vendor_dir, and w2s().
Referenced by GuideFrame().
LoadProfileFamily()
int Slic3r::GUI::GuideFrame::LoadProfileFamily (std::string strVendor, std::string strFilePath)
{
    // wxString strFolder = strFilePath.BeforeLast(boost::filesystem::path::preferred_separator);
    boost::filesystem::path file_path(strFilePath);
    boost::filesystem::path vendor_dir = boost::filesystem::absolute(file_path.parent_path() / strVendor).make_preferred();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(",  vendor path %1%.") % vendor_dir.string();
    try {
        // wxLogMessage("GUIDE: json_path1  %s", w2s(strFilePath));
        std::string contents;
        LoadFile(strFilePath, contents);
        // wxLogMessage("GUIDE: json_path1 content: %s", contents);
        json jLocal = json::parse(contents);
        // wxLogMessage("GUIDE: json_path1 Loaded");
        // BBS:models
        json pmodels = jLocal["machine_model_list"];
        int  nsize   = pmodels.size();
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(",  got %1% machine models") % nsize;
        for (int n = 0; n < nsize; n++) {
            json OneModel = pmodels.at(n);
            OneModel["model"] = OneModel["name"];
            OneModel.erase("name");
            std::string s1 = OneModel["model"];
            std::string s2 = OneModel["sub_path"];
            boost::filesystem::path sub_path = boost::filesystem::absolute(vendor_dir / s2).make_preferred();
            std::string             sub_file = sub_path.string();
            // wxLogMessage("GUIDE: json_path2  %s", w2s(ModelFilePath));
            LoadFile(sub_file, contents);
            // wxLogMessage("GUIDE: json_path2 content: %s", contents);
            json pm = json::parse(contents);
            // wxLogMessage("GUIDE: json_path2  loaded");
            OneModel["vendor"]    = strVendor;
            std::string NozzleOpt = pm["nozzle_diameter"];
            StringReplace(NozzleOpt, " ", "");
            OneModel["nozzle_diameter"] = NozzleOpt;
            OneModel["materials"]       = pm["default_materials"];
            // wxString strCoverPath = wxString::Format("%s\\%s\\%s_cover.png", strFolder, strVendor, std::string(s1.mb_str()));
            std::string             cover_file = s1 + "_cover.png";
            boost::filesystem::path cover_path = boost::filesystem::absolute(boost::filesystem::path(resources_dir()) / "/profiles/" / strVendor / cover_file).make_preferred();
            if (!boost::filesystem::exists(cover_path)) {
                cover_path =
                    (boost::filesystem::absolute(boost::filesystem::path(resources_dir()) / "/web/image/printer/") /
                     cover_file)
                        .make_preferred();
            }
            OneModel["cover"]                  = cover_path.string();
            OneModel["nozzle_selected"] = "";
            m_ProfileJson["model"].push_back(OneModel);
        }
        // BBS:Machine
        json pmachine = jLocal["machine_list"];
        nsize         = pmachine.size();
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(",  got %1% machines") % nsize;
        for (int n = 0; n < nsize; n++) {
            json OneMachine = pmachine.at(n);
            std::string s1 = OneMachine["name"];
            std::string s2 = OneMachine["sub_path"];
            // wxString ModelFilePath = wxString::Format("%s\\%s\\%s", strFolder, strVendor, s2);
            boost::filesystem::path sub_path = boost::filesystem::absolute(vendor_dir / s2).make_preferred();
            std::string             sub_file = sub_path.string();
            LoadFile(sub_file, contents);
            json pm = json::parse(contents);
            std::string strInstant = pm["instantiation"];
            if (strInstant.compare("true") == 0) {
                OneMachine["model"] = pm["printer_model"];
                OneMachine["nozzle"] = pm["nozzle_diameter"][0];
                m_ProfileJson["machine"][s1]=OneMachine;
            }
        }
        // BBS:Filament
        json pFilament = jLocal["filament_list"];
        json tFilaList = json::object();
        nsize          = pFilament.size();
        for (int n = 0; n < nsize; n++) {
            json OneFF = pFilament.at(n);
            std::string s1    = OneFF["name"];
            std::string s2    = OneFF["sub_path"];
            tFilaList[s1] = OneFF;
        }
        int nFalse  = 0;
        int nModel  = 0;
        int nFinish = 0;
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(",  got %1% filaments") % nsize;
        for (int n = 0; n < nsize; n++) {
            json OneFF = pFilament.at(n);
            std::string s1 = OneFF["name"];
            std::string s2 = OneFF["sub_path"];
            if (!m_ProfileJson["filament"].contains(s1)) {
                // wxString ModelFilePath = wxString::Format("%s\\%s\\%s", strFolder, strVendor, s2);
                boost::filesystem::path sub_path = boost::filesystem::absolute(vendor_dir / s2).make_preferred();
                std::string             sub_file = sub_path.string();
                LoadFile(sub_file, contents);
                json pm = json::parse(contents);
                std::string strInstant = pm["instantiation"];
                if (strInstant == "true") {
                    std::string sV;
                    std::string sT;
                    int nRet = GetFilamentInfo(vendor_dir.string(),tFilaList, sub_file, sV, sT);
                    if (nRet != 0) continue;
                    OneFF["vendor"] = sV;
                    OneFF["type"]   = sT;
                    OneFF["models"]   = "";
                    json pPrinters = pm["compatible_printers"];
                    int nPrinter   = pPrinters.size();
                    std::string ModelList = "";
                    for (int i = 0; i < nPrinter; i++)
                    {
                        std::string sP = pPrinters.at(i);
                        if (m_ProfileJson["machine"].contains(sP))
{
                            std::string mModel = m_ProfileJson["machine"][sP]["model"];
                            std::string mNozzle = m_ProfileJson["machine"][sP]["nozzle"];
                            std::string NewModel = mModel + "++" + mNozzle;
                            ModelList = (boost::format("%1%[%2%]") % ModelList % NewModel).str();
                        }
                    }
                    OneFF["models"]    = ModelList;
                    OneFF["selected"] = 0;
                    m_ProfileJson["filament"][s1] = OneFF;
                } else
                    continue;
            }
        }
        // process
        json pProcess = jLocal["process_list"];
        nsize         = pProcess.size();
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(",  got %1% processes") % nsize;
        for (int n = 0; n < nsize; n++) {
            json OneProcess = pProcess.at(n);
            std::string s2 = OneProcess["sub_path"];
            // wxString ModelFilePath = wxString::Format("%s\\%s\\%s", strFolder, strVendor, s2);
            boost::filesystem::path sub_path = boost::filesystem::absolute(vendor_dir / s2).make_preferred();
            std::string             sub_file = sub_path.string();
            LoadFile(sub_file, contents);
            json pm = json::parse(contents);
            std::string bInstall = pm["instantiation"];
            if (bInstall == "true") { m_ProfileJson["process"].push_back(OneProcess); }
        }
    } catch (nlohmann::detail::parse_error &err) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ": parse " << strFilePath << " got a nlohmann::detail::parse_error, reason = " << err.what();
        return -1;
    } catch (std::exception &e) {
        // wxMessageBox(e.what(), "", MB_OK);
        // wxLogMessage("GUIDE: LoadFamily Error: %s", e.what());
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ": parse " << strFilePath << " got exception: " << e.what();
        return -1;
    }
    return 0;
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::at(), Slic3r::contains(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::erase(), error, GetFilamentInfo(), LoadFile(), Slic3r::GUI::m_ProfileJson, n, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::object(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::push_back(), Slic3r::resources_dir(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::size(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::string, Slic3r::GUI::StringReplace(), vendor_dir, and nlohmann::detail::exception::what().
Referenced by LoadProfile().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
on_dpi_changed()
void Slic3r::GUI::GuideFrame::on_dpi_changed (const wxRect & suggested_rect) inline virtual
Implements Slic3r::GUI::DPIAware< P >.
{}
on_sys_color_changed()
template<class P > virtual void Slic3r::GUI::DPIAware< P >::on_sys_color_changed () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ConfigWizard, Slic3r::GUI::ObjectTableDialog, Slic3r::GUI::MainFrame, Slic3r::GUI::PhysicalPrinterDialog, Slic3r::GUI::PrintHostQueueDialog, Slic3r::GUI::SavePresetDialog, Slic3r::GUI::UnsavedChangesDialog, and Slic3r::GUI::DiffPresetDialog.
{};
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
OnDocumentLoaded()
void Slic3r::GUI::GuideFrame::OnDocumentLoaded (wxWebViewEvent & evt)
Callback invoked when a page is finished loading
{
    // Only notify if the document is the main frame, not a subframe
    wxString tmpUrl = evt.GetURL();
    wxString NowUrl = m_browser->GetCurrentURL();
    if (evt.GetURL() == m_browser->GetCurrentURL()) {
        // wxLogMessage("%s", "Document loaded; url='" + evt.GetURL() + "'");
    }
    UpdateState();
    // wxCommandEvent *event = new
    // wxCommandEvent(EVT_WEB_RESPONSE_MESSAGE,this->GetId()); wxQueueEvent(this,
    // event);
}
References m_browser, and UpdateState().
Referenced by GuideFrame().
OnError()
void Slic3r::GUI::GuideFrame::OnError (wxWebViewEvent & evt)
Callback invoked when a loading error occurs
{
#define WX_ERROR_CASE(type) \
    case type: category = #type; break;
    wxString category;
    switch (evt.GetInt()) {
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_CONNECTION);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_CERTIFICATE);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_AUTH);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_SECURITY);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_NOT_FOUND);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_REQUEST);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_USER_CANCELLED);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_OTHER);
    }
    // wxLogMessage("%s", "Error; url='" + evt.GetURL() + "', error='" +
    // category + " (" + evt.GetString() + ")'");
    // Show the info bar with an error
    // m_info->ShowMessage(_L("An error occurred loading ") + evt.GetURL() +
    // "\n" + "'" + category + "'", wxICON_ERROR);
    BOOST_LOG_TRIVIAL(info) << "GuideFrame::OnError: An error occurred loading " << evt.GetURL() << category;
    UpdateState();
}
References UpdateState(), and WX_ERROR_CASE.
Referenced by GuideFrame().
OnFullScreenChanged()
void Slic3r::GUI::GuideFrame::OnFullScreenChanged (wxWebViewEvent & evt)
{
    // wxLogMessage("Full screen changed; status = %d", evt.GetInt());
    ShowFullScreen(evt.GetInt() != 0);
}
Referenced by GuideFrame().
OnIdle()
void Slic3r::GUI::GuideFrame::OnIdle (wxIdleEvent & evt)
{
    if (m_browser->IsBusy()) {
        wxSetCursor(wxCURSOR_ARROWWAIT);
    } else {
        wxSetCursor(wxNullCursor);
    }
}
References m_browser.
OnNavigationComplete()
void Slic3r::GUI::GuideFrame::OnNavigationComplete (wxWebViewEvent & evt)
Callback invoked when a navigation request was accepted
{
    //wxLogMessage("%s", "Navigation complete; url='" + evt.GetURL() + "'");
    m_browser->Show();
    Layout();
    wxString NewUrl = evt.GetURL();
    UpdateState();
}
References m_browser, and UpdateState().
Referenced by GuideFrame().
OnNavigationRequest()
void Slic3r::GUI::GuideFrame::OnNavigationRequest (wxWebViewEvent & evt)
Callback invoked when there is a request to load a new page (for instance when the user clicks a link)
{
    // wxLogMessage("%s", "Navigation request to '" + evt.GetURL() + "'
    // (target='" + evt.GetTarget() + "')");
    UpdateState();
}
References UpdateState().
Referenced by GuideFrame().
OnNewWindow()
void Slic3r::GUI::GuideFrame::OnNewWindow (wxWebViewEvent & evt)
On new window, we veto to stop extra windows appearing
{
    wxString flag = " (other)";
    wxString NewUrl= evt.GetURL();
    wxLaunchDefaultBrowser(NewUrl);
    //if (evt.GetNavigationAction() == wxWEBVIEW_NAV_ACTION_USER) { flag = " (user)"; }
    // wxLogMessage("%s", "New window; url='" + evt.GetURL() + "'" + flag);
    // If we handle new window events then just load them in this window as we
    // are a single window browser
    // if (m_tools_handle_new_window->IsChecked())
    //    m_browser->LoadURL(evt.GetURL());
    UpdateState();
}
References UpdateState().
Referenced by GuideFrame().
OnScriptMessage()
void Slic3r::GUI::GuideFrame::OnScriptMessage (wxWebViewEvent & evt)
{
    try {
        wxString strInput = evt.GetString();
        json     j        = json::parse(strInput);
        wxString strCmd = j["command"];
        if (strCmd == "close_page") {
            this->EndModal(wxID_CANCEL);
        }
        if (strCmd == "user_clause") {
            wxString strAction = j["data"]["action"];
            if (strAction == "refuse") {
                // CloseTheApp
                this->EndModal(wxID_OK);
                m_MainPtr->mainframe->Close(); // Refuse Clause, App quit immediately
            }
        } else if (strCmd == "user_private_choice") {
            wxString strAction = j["data"]["action"];
            if (strAction == "agree") {
                PrivacyUse = true;
            } else {
                PrivacyUse = false;
            }
        }
        else if (strCmd == "request_userguide_profile") {
            json m_Res = json::object();
            m_Res["command"] = "response_userguide_profile";
            m_Res["sequence_id"] = "10001";
            m_Res["response"]        = m_ProfileJson;
            wxString strJS = wxString::Format("HandleStudio(%s)", m_Res.dump(-1, ' ', false, json::error_handler_t::ignore));
            wxGetApp().CallAfter([this,strJS] { RunScript(strJS); });
        }
        else if (strCmd == "save_userguide_models")
        {
            json MSelected = j["data"];
            int nModel = m_ProfileJson["model"].size();
            for (int m = 0; m < nModel; m++) {
                json TmpModel = m_ProfileJson["model"][m];
                m_ProfileJson["model"][m]["nozzle_selected"] = "";
                for (auto it = MSelected.begin(); it != MSelected.end(); ++it) {
                    json OneSelect = it.value();
                    wxString s1 = TmpModel["model"];
                    wxString s2 = OneSelect["model"];
                    if (s1.compare(s2) == 0) {
                        m_ProfileJson["model"][m]["nozzle_selected"] = OneSelect["nozzle_diameter"];
                        break;
                    }
                }
            }
        }
        else if (strCmd == "save_userguide_filaments") {
            //reset
            for (auto it = m_ProfileJson["filament"].begin(); it != m_ProfileJson["filament"].end(); ++it)
            {
                m_ProfileJson["filament"][it.key()]["selected"] = 0;
            }
            json fSelected = j["data"]["filament"];
            int nF = fSelected.size();
            for (int m = 0; m < nF; m++)
            {
                std::string fName = fSelected[m];
                m_ProfileJson["filament"][fName]["selected"] = 1;
            }
        }
        else if (strCmd == "user_guide_finish") {
            SaveProfile();
            std::string oldregion = m_ProfileJson["region"];
            bool        bLogin    = false;
            if (m_Region != oldregion) {
                AppConfig* config = GUI::wxGetApp().app_config;
                std::string country_code = config->get_country_code();
                NetworkAgent* agent = wxGetApp().getAgent();
                if (agent) {
                    agent->set_country_code(country_code);
                    if (wxGetApp().is_user_login()) {
                        bLogin = true;
                        agent->user_logout();
                    }
                }
            }
            this->EndModal(wxID_OK);
            if (InstallNetplugin)
                GUI::wxGetApp().CallAfter([this] { GUI::wxGetApp().ShowDownNetPluginDlg(); });
            if (bLogin)
                GUI::wxGetApp().CallAfter([this] { login(); });
        }
        else if (strCmd == "user_guide_cancel") {
            this->EndModal(wxID_CANCEL);
            this->Close();
        } else if (strCmd == "save_region") {
            m_Region = j["region"];
        }
        else if (strCmd == "network_plugin_install") {
            std::string sAction = j["data"]["action"];
            if (sAction == "yes") {
                if (!network_plugin_ready)
                    InstallNetplugin = true;
                else //already ready
                    InstallNetplugin = false;
            }
            else
                InstallNetplugin = false;
        }
    } catch (std::exception &e) {
        // wxMessageBox(e.what(), "json Exception", MB_OK);
    }
    wxString strAll = m_ProfileJson.dump(-1,' ',false, json::error_handler_t::ignore);
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::begin(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::end(), Slic3r::AppConfig::get_country_code(), InstallNetplugin, Slic3r::GUI::login(), m_MainPtr, Slic3r::GUI::m_ProfileJson, m_Region, Slic3r::GUI::GUI_App::mainframe, network_plugin_ready, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::object(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), PrivacyUse, RunScript(), SaveProfile(), Slic3r::NetworkAgent::set_country_code(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::size(), Slic3r::NetworkAgent::user_logout(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::value().
Referenced by GuideFrame().
OnScriptResponseMessage()
void Slic3r::GUI::GuideFrame::OnScriptResponseMessage (wxCommandEvent & evt)
{
    // if (!m_response_js.empty())
    //{
    //    RunScript(m_response_js);
    //}
    // RunScript("This is a message to Web!");
    // RunScript("postMessage(\"AABBCCDD\");");
}
OnTitleChanged()
void Slic3r::GUI::GuideFrame::OnTitleChanged (wxWebViewEvent & evt)
{
    // SetTitle(evt.GetString());
    // wxLogMessage("%s", "Title changed; title='" + evt.GetString() + "'");
}
Referenced by GuideFrame().
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
run()
bool Slic3r::GUI::GuideFrame::run ()
{
    //BOOST_LOG_TRIVIAL(info) << boost::format("Running ConfigWizard, reason: %1%, start_page: %2%") % reason % start_page;
    GUI_App &app = wxGetApp();
    //p->set_run_reason(reason);
    //p->set_start_page(start_page);
    app.preset_bundle->export_selections(*app.app_config);
    BOOST_LOG_TRIVIAL(info) << "GuideFrame before ShowModal";
    int result = this->ShowModal();
    if (result == wxID_OK) {
        bool apply_keeped_changes = false;
        BOOST_LOG_TRIVIAL(info) << "GuideFrame returned ok";
        if (! this->apply_config(app.app_config, app.preset_bundle, app.preset_updater, apply_keeped_changes))
            return false;
        if (apply_keeped_changes)
            app.apply_keeped_preset_modifications();
        app.app_config->set_legacy_datadir(false);
        app.update_mode();
        // BBS
        //app.obj_manipul()->update_ui_from_settings();
        BOOST_LOG_TRIVIAL(info) << "GuideFrame applied";
        this->Close();
        return true;
    } else if (result == wxID_CANCEL) {
        BOOST_LOG_TRIVIAL(info) << "GuideFrame cancelled";
        if (app.preset_bundle->printers.only_default_printers()) {
            //we install the default here
            bool apply_keeped_changes = false;
            //clear filament section and use default materials
            app.app_config->set_variant(PresetBundle::BBL_BUNDLE,
                PresetBundle::BBL_DEFAULT_PRINTER_MODEL, PresetBundle::BBL_DEFAULT_PRINTER_VARIANT, "true");
            app.app_config->clear_section(AppConfig::SECTION_FILAMENTS);
            app.preset_bundle->load_selections(*app.app_config, {PresetBundle::BBL_DEFAULT_PRINTER_MODEL, PresetBundle::BBL_DEFAULT_PRINTER_VARIANT, PresetBundle::BBL_DEFAULT_FILAMENT, std::string()});
            app.app_config->set_legacy_datadir(false);
            app.update_mode();
            return true;
        }
        else
            return false;
    }
    else
        return false;
}
References Slic3r::GUI::GUI_App::app_config, apply_config(), Slic3r::GUI::GUI_App::apply_keeped_preset_modifications(), Slic3r::PresetBundle::BBL_BUNDLE, Slic3r::PresetBundle::BBL_DEFAULT_PRINTER_MODEL, Slic3r::PresetBundle::BBL_DEFAULT_PRINTER_VARIANT, Slic3r::AppConfig::clear_section(), Slic3r::PresetBundle::export_selections(), Slic3r::PresetBundle::load_selections(), Slic3r::PrinterPresetCollection::only_default_printers(), Slic3r::GUI::GUI_App::preset_bundle, Slic3r::GUI::GUI_App::preset_updater, Slic3r::PresetBundle::printers, Slic3r::AppConfig::SECTION_FILAMENTS, Slic3r::AppConfig::set_legacy_datadir(), Slic3r::AppConfig::set_variant(), Slic3r::GUI::DPIAware< P >::ShowModal(), and Slic3r::GUI::GUI_App::update_mode().
Referenced by Slic3r::GUI::GUI_App::run_wizard(), Slic3r::GUI::GUI_App::ShowOnlyFilament(), and Slic3r::GUI::GUI_App::ShowUserGuide().
RunScript()
void Slic3r::GUI::GuideFrame::RunScript (const wxString & javascript)
{
    // Remember the script we run in any case, so the next time the user opens
    // the "Run Script" dialog box, it is shown there for convenient updating.
    //m_javascript = javascript;
    // wxLogMessage("Running JavaScript:\n%s\n", javascript);
    if (!m_browser) return;
    WebView::RunScript(m_browser, javascript);
}
References m_browser, and WebView::RunScript().
Referenced by OnScriptMessage().
SaveProfile()
int Slic3r::GUI::GuideFrame::SaveProfile ()
{
    // SoftFever: don't collect info
    //privacy
    // if (PrivacyUse == true) {
    //     m_MainPtr->app_config->set(std::string(m_SectionName.mb_str()), "privacyuse", "1");
    // } else
    //     m_MainPtr->app_config->set(std::string(m_SectionName.mb_str()), "privacyuse", "0");
    m_MainPtr->app_config->set("region", m_Region);
    //finish
    m_MainPtr->app_config->set(std::string(m_SectionName.mb_str()), "finish", "1");
    m_MainPtr->app_config->save();
    //Load BBS Conf
    /*wxString strConfPath = wxGetApp().app_config->config_path();
    json     jCfg;
    std::ifstream(w2s(strConfPath)) >> jCfg;
    //model
    jCfg["models"] = json::array();
    int nM         = m_ProfileJson["model"].size();
    int nModelChoose    = 0;
    for (int m = 0; m < nM; m++)
    {
        json amodel = m_ProfileJson["model"][m];
        amodel["nozzle_diameter"] = amodel["nozzle_selected"];
        amodel.erase("nozzle_selected");
        amodel.erase("preview");
        amodel.erase("sub_path");
        amodel.erase("cover");
        amodel.erase("materials");
        std::string ss = amodel["nozzle_diameter"];
        if (ss.compare("") != 0) {
            nModelChoose++;
            jCfg["models"].push_back(amodel);
        }
    }
    if (nModelChoose == 0)
        jCfg.erase("models");
    if (nModelChoose > 0) {
        // filament
        jCfg["filaments"] = json::array();
        for (auto it = m_ProfileJson["filament"].begin(); it != m_ProfileJson["filament"].end(); ++it) {
            if (it.value()["selected"] == 1) { jCfg["filaments"].push_back(it.key()); }
        }
        // Preset
        jCfg["presets"]["filaments"] = json::array();
        jCfg["presets"]["filaments"].push_back(jCfg["filaments"][0]);
        std::string PresetMachine  = m_ProfileJson["machine"][0]["name"];
        jCfg["presets"]["machine"] = PresetMachine;
        int nTotal = m_ProfileJson["process"].size();
        int nSet   = nTotal / 2;
        if (nSet > 0) nSet--;
        std::string sMode          = m_ProfileJson["process"][nSet]["name"];
        jCfg["presets"]["process"] = sMode;
    } else {
        jCfg["presets"]["filaments"] = json::array();
        jCfg["presets"]["filaments"].push_back("Default Filament");
        jCfg["presets"]["machine"] = "Default Printer";
        jCfg["presets"]["process"] = "Default Setting";
    }
    std::string sOut = jCfg.dump(4, ' ', false);
    std::ofstream output_file(w2s(strConfPath));
    output_file << sOut;
    output_file.close();
    //Copy Profiles
    if (bbl_bundle_rsrc)
    {
        CopyDir(rsrc_vendor_dir,vendor_dir);
    }*/
    std::string strAll = m_ProfileJson.dump(-1, ' ', false, json::error_handler_t::ignore);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << "before save to app_config: "<< std::endl<<strAll;
    //set filaments to app_config
    const std::string &section_name = AppConfig::SECTION_FILAMENTS;
    std::map<std::string, std::string> section_new;
    m_appconfig_new.clear_section(section_name);
    for (auto it = m_ProfileJson["filament"].begin(); it != m_ProfileJson["filament"].end(); ++it) {
        if (it.value()["selected"] == 1){
            section_new[it.key()] = "true";
        }
    }
    m_appconfig_new.set_section(section_name, section_new);
    //set vendors to app_config
    Slic3r::AppConfig::VendorMap empty_vendor_map;
    m_appconfig_new.set_vendors(empty_vendor_map);
    for (auto it = m_ProfileJson["model"].begin(); it != m_ProfileJson["model"].end(); ++it)
    {
        if (it.value().is_object()) {
            json temp_model = it.value();
            std::string model_name = temp_model["model"];
            std::string vendor_name = temp_model["vendor"];
            std::string selected = temp_model["nozzle_selected"];
            boost::trim(selected);
            std::string nozzle;
            while (selected.size() > 0) {
                auto pos = selected.find(';');
                if (pos != std::string::npos) {
                    nozzle   = selected.substr(0, pos);
                    m_appconfig_new.set_variant(vendor_name, model_name, nozzle, "true");
                    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("vendor_name %1%, model_name %2%, nozzle %3% selected")%vendor_name %model_name %nozzle;
                    selected = selected.substr(pos + 1);
                    boost::trim(selected);
                }
                else {
                    m_appconfig_new.set_variant(vendor_name, model_name, selected, "true");
                    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("vendor_name %1%, model_name %2%, nozzle %3% selected")%vendor_name %model_name %selected;
                    break;
                }
            }
        }
    }
    //m_appconfig_new
    return 0;
}
References Slic3r::GUI::GUI_App::app_config, Slic3r::AppConfig::clear_section(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::end(), m_appconfig_new, m_MainPtr, Slic3r::GUI::m_ProfileJson, m_Region, m_SectionName, Slic3r::AppConfig::save(), Slic3r::AppConfig::SECTION_FILAMENTS, Slic3r::AppConfig::set(), Slic3r::AppConfig::set_section(), Slic3r::AppConfig::set_variant(), Slic3r::AppConfig::set_vendors(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::value().
Referenced by OnScriptMessage().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
SetStartPage()
wxString Slic3r::GUI::GuideFrame::SetStartPage (GuidePage startpage = BBL_WELCOME, bool load = true)
{
    m_page = startpage;
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(" enter, load=%1%, start_page=%2%")%load%int(startpage);
    //wxLogMessage("GUIDE: webpage_1  %s", (boost::filesystem::path(resources_dir()) / "web\\guide\\1\\index.html").make_preferred().string().c_str() );
    wxString TargetUrl = from_u8( (boost::filesystem::path(resources_dir()) / "web/guide/1/index.html").make_preferred().string() );
    //wxLogMessage("GUIDE: webpage_2  %s", TargetUrl.mb_str());
    if (startpage == BBL_WELCOME){
        SetTitle(_L("Setup Wizard"));
        TargetUrl = from_u8((boost::filesystem::path(resources_dir()) / "web/guide/1/index.html").make_preferred().string());
    } else if (startpage == BBL_REGION) {
        SetTitle(_L("Setup Wizard"));
        TargetUrl = from_u8((boost::filesystem::path(resources_dir()) / "web/guide/11/index.html").make_preferred().string());
    } else if (startpage == BBL_MODELS) {
        SetTitle(_L("Setup Wizard"));
        TargetUrl = from_u8((boost::filesystem::path(resources_dir()) / "web/guide/21/index.html").make_preferred().string());
    } else if (startpage == BBL_FILAMENTS) {
        SetTitle(_L("Setup Wizard"));
        int nSize = m_ProfileJson["model"].size();
        if (nSize>0)
            TargetUrl = from_u8((boost::filesystem::path(resources_dir()) / "web/guide/22/index.html").make_preferred().string());
        else
            TargetUrl = from_u8((boost::filesystem::path(resources_dir()) / "web/guide/21/index.html").make_preferred().string());
    } else if (startpage == BBL_FILAMENT_ONLY) {
        SetTitle("");
        TargetUrl = from_u8((boost::filesystem::path(resources_dir()) / "web/guide/23/index.html").make_preferred().string());
    } else if (startpage == BBL_MODELS_ONLY) {
        SetTitle("");
        TargetUrl = from_u8((boost::filesystem::path(resources_dir()) / "web/guide/24/index.html").make_preferred().string());
    }
    else {
        SetTitle(_L("Setup Wizard"));
        TargetUrl = from_u8((boost::filesystem::path(resources_dir()) / "web/guide/21/index.html").make_preferred().string());
    }
    std::string strlang = wxGetApp().app_config->get("language");
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(", strlang=%1%")%strlang;
    if (strlang != "")
        TargetUrl = wxString::Format("%s?lang=%s", w2s(TargetUrl), strlang);
    TargetUrl = "file://" + TargetUrl;
    if (load)
        load_url(TargetUrl);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< " exit";
    return TargetUrl;
}
References _L, BBL_FILAMENT_ONLY, BBL_FILAMENTS, BBL_MODELS, BBL_MODELS_ONLY, BBL_REGION, BBL_WELCOME, Slic3r::GUI::from_u8(), int, load_url(), m_page, Slic3r::GUI::m_ProfileJson, Slic3r::resources_dir(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::size(), and w2s().
Referenced by GuideFrame(), Slic3r::GUI::GUI_App::run_wizard(), and Slic3r::GUI::GUI_App::ShowOnlyFilament().
ShowModal()
template<class P > int Slic3r::GUI::DPIAware< P >::ShowModal () inline inherited
    {
        dialogStack.push_front(this);
        int r = wxDialog::ShowModal();
        dialogStack.pop_front();
        return r;
    }
References Slic3r::GUI::dialogStack.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::Sidebar::Sidebar(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), WipingPanel::WipingPanel(), Slic3r::GUI::about(), Slic3r::GUI::GLGizmoSlaSupports::ask_about_changes_call_after(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::GUI_App::check_print_host_queue(), Slic3r::GUI::GUI_App::check_updates(), Slic3r::GUI::Plater::close_with_confirm(), Slic3r::PresetUpdater::config_update(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_language_combobox(), Slic3r::GUI::PreferencesDialog::create_item_region_combobox(), Slic3r::GUI::ObjectList::del_from_cut_object(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::ImageGrid::DoAction(), Slic3r::GUI::MainFrame::export_config(), Slic3r::GUI::generate_help_menu(), Slic3r::GUI::Field::get_value_by_opt_type(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::GUI_App::keyboard_shortcuts(), Slic3r::GUI::MainFrame::load_config_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::load_gcode(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::StatusPanel::on_ams_filament_backup(), Slic3r::GUI::StatusPanel::on_ams_refresh_rfid(), Slic3r::GUI::BindMachineDialog::on_bind_success(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), Slic3r::GUI::GUI_App::on_http_error(), Slic3r::GUI::SelectMachineDialog::on_rename_enter(), Slic3r::GUI::SendToPrinterDialog::on_rename_enter(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::MainFrame::on_select_default_preset(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::AMSMaterialsSetting::on_select_reset(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::PrivacyUpdateDialog::on_show(), Slic3r::GUI::ConfirmBeforeSendDialog::on_show(), Slic3r::GUI::StatusPanel::on_show_print_options(), Slic3r::GUI::MachineInfoPanel::on_show_release_note(), Slic3r::GUI::PA_Calibration_Dlg::on_start(), Slic3r::GUI::Temp_Calibration_Dlg::on_start(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::on_start(), Slic3r::GUI::VFA_Test_Dlg::on_start(), Slic3r::GUI::Retraction_Test_Dlg::on_start(), Slic3r::GUI::StatusPanel::on_start_calibration(), Slic3r::PresetUpdater::on_update_notification_confirm(), Slic3r::GUI::Tab::on_value_change(), Slic3r::GUI::AboutDialog::onCopyrightBtn(), Slic3r::GUI::Plater::open_3mf_file(), Slic3r::GUI::GUI_App::open_preferences(), Slic3r::GUI::MainFrame::open_recent_project(), Slic3r::GUI::ExtrusionCalibration::Popup(), Slic3r::GUI::ObjectTableDialog::Popup(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::GUI::SelectMachineDialog::popup_filament_backup(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::replace_with_stl(), run(), Slic3r::GUI::ConfigWizard::run(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Plater::save_project(), Slic3r::GUI::Plater::priv::save_project_if_dirty(), Slic3r::GUI::ConfigWizard::priv::select_default_materials_for_printer_models(), Slic3r::GUI::Plater::select_plate_by_hover_id(), Slic3r::GUI::Plater::send_gcode_legacy(), Slic3r::GUI::MachineObjectPanel::show_bind_dialog(), Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), Slic3r::GUI::GUI_App::show_modal_ip_address_enter_dialog(), Slic3r::GUI::StatusPanel::show_recenter_dialog(), Slic3r::GUI::show_send_system_info_dialog_if_needed(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::Tab::show_timelapse_warning_dialog(), Slic3r::GUI::GUI_App::ShowDownNetPluginDlg(), Slic3r::GUI::ObjectList::switch_to_object_process(), Slic3r::GUI::Sidebar::sync_ams_list(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::MediaPlayCtrl::ToggleStream(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), Slic3r::GUI::Plater::priv::update_plugin_when_launch(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::GUI::ConfigManipulation::update_print_sla_config(), Slic3r::GUI::GUI_App::updating_bambu_networking(), Slic3r::GUI::Tab::validate_custom_gcode(), Slic3r::GUI::warning_catcher(), and Slic3r::GUI::Plater::priv::warnings_dialog().
ShowPluginStatus()
int Slic3r::GUI::GuideFrame::ShowPluginStatus (int status, int percent, bool & cancel)
{
    //TODO
    return 0;
}
Referenced by DownloadPlugin(), and InstallPlugin().
StrReplace()
void Slic3r::GUI::GuideFrame::StrReplace (std::string & strBase, std::string strSrc, std::string strDes)
{
    int pos    = 0;
    int srcLen = strSrc.size();
    int desLen = strDes.size();
    pos = strBase.find(strSrc, pos);
    while ((pos != std::string::npos)) {
        strBase.replace(pos, srcLen, strDes);
        pos = strBase.find(strSrc, (pos + desLen));
    }
}
Referenced by GetStardardFilePath().
UpdateState()
void Slic3r::GUI::GuideFrame::UpdateState ()
Method that retrieves the current state from the web control and updates the GUI the reflect this current state.
{
    // SetTitle(m_browser->GetCurrentTitle());
}
Referenced by load_url(), OnDocumentLoaded(), OnError(), OnNavigationComplete(), OnNavigationRequest(), and OnNewWindow().
w2s()
std::string Slic3r::GUI::GuideFrame::w2s (wxString sSrc)
{
    return std::string(sSrc.mb_str());
}
Referenced by GetFilamentInfo(), GetStardardFilePath(), LoadProfile(), and SetStartPage().
Member Data Documentation
bbl_bundle_rsrc
bool Slic3r::GUI::GuideFrame::bbl_bundle_rsrc private
Referenced by IsFirstUse(), and LoadProfile().
InstallNetplugin
bool Slic3r::GUI::GuideFrame::InstallNetplugin private
Referenced by GuideFrame(), and OnScriptMessage().
m_appconfig_new
AppConfig Slic3r::GUI::GuideFrame::m_appconfig_new private
Referenced by apply_config(), LoadProfile(), and SaveProfile().
m_bbl_user_agent
wxString Slic3r::GUI::GuideFrame::m_bbl_user_agent private
m_browser
wxWebView* Slic3r::GUI::GuideFrame::m_browser private
Referenced by GuideFrame(), ~GuideFrame(), load_url(), OnDocumentLoaded(), OnIdle(), OnNavigationComplete(), and RunScript().
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_javascript
wxString Slic3r::GUI::GuideFrame::m_javascript private
m_MainPtr
GUI_App* Slic3r::GUI::GuideFrame::m_MainPtr private
Referenced by GuideFrame(), OnScriptMessage(), and SaveProfile().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_page
enum Slic3r::GUI::GuideFrame::GuidePage Slic3r::GUI::GuideFrame::m_page
Referenced by GuideFrame(), and SetStartPage().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_Region
std::string Slic3r::GUI::GuideFrame::m_Region private
Referenced by LoadProfile(), OnScriptMessage(), and SaveProfile().
m_response_js
wxString Slic3r::GUI::GuideFrame::m_response_js private
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
m_SectionName
wxString Slic3r::GUI::GuideFrame::m_SectionName private
Referenced by GuideFrame(), IsFirstUse(), and SaveProfile().
m_TestBtn
wxButton* Slic3r::GUI::GuideFrame::m_TestBtn private
network_plugin_ready
bool Slic3r::GUI::GuideFrame::network_plugin_ready {false} private
Referenced by LoadProfile(), and OnScriptMessage().
PrivacyUse
bool Slic3r::GUI::GuideFrame::PrivacyUse private
Referenced by GuideFrame(), and OnScriptMessage().
rsrc_vendor_dir
boost::filesystem::path Slic3r::GUI::GuideFrame::rsrc_vendor_dir private
Referenced by LoadProfile().
vendor_dir
boost::filesystem::path Slic3r::GUI::GuideFrame::vendor_dir private
Referenced by apply_config(), LoadProfile(), and LoadProfileFamily().
The documentation for this class was generated from the following files:
src/slic3r/GUI/WebGuideDialog.hpp
src/slic3r/GUI/WebGuideDialog.cpp