OrcaSlicer: Slic3r::PresetUpdater::priv Struct Reference
Slic3r::PresetUpdater::priv Struct Reference
Classes
struct Resource
Public Member Functions
priv ()
void set_download_prefs (AppConfig *app_config)
bool get_file (const std::string &url, const fs::path &target_path) const
bool extract_file (const fs::path &source_path, const fs::path &dest_path={})
void prune_tmps () const
void sync_version () const
void parse_version_string (const std::string &body) const
void sync_resources (std::string http_url, std::map< std::string, Resource > &resources, bool check_patch=false, std::string current_version="", std::string changelog_file="")
void sync_config (std::string http_url, const VendorMap vendors)
void sync_tooltip (std::string http_url, std::string language)
void sync_plugins (std::string http_url, std::string plugin_version)
bool get_cached_plugins_version (std::string &cached_version)
bool install_bundles_rsrc (std::vector< std::string > bundles, bool snapshot) const
void check_installed_vendor_profiles () const
Updates get_config_updates (const Semver &old_slic3r_version) const
bool perform_updates (Updates &&updates, bool snapshot=true) const
void set_waiting_updates (Updates u)
Public Attributes
std::vector< Index > index_db
bool enabled_version_check
bool enabled_config_update
std::string version_check_url
fs::path cache_path
fs::path rsrc_path
fs::path vendor_path
bool cancel
std::thread thread
bool has_waiting_updates { false }
Updates waiting_updates
Detailed Description
Class Documentation
Slic3r::PresetUpdater::priv::Resource
struct Slic3r::PresetUpdater::priv::Resource
Class Members
string cache_root
string description
vector< string > sub_caches
string url
string version
Constructor & Destructor Documentation
priv()
Slic3r::PresetUpdater::priv::priv ()
  : cache_path(fs::path(Slic3r::data_dir()) / "ota")
  , rsrc_path(fs::path(resources_dir()) / "profiles")
  , vendor_path(fs::path(Slic3r::data_dir()) / PRESET_SYSTEM_DIR)
  , cancel(false)
{
  //BBS: refine preset updater logic
  enabled_version_check = true;
  set_download_prefs(GUI::wxGetApp().app_config);
  // Install indicies from resources. Only installs those that are either missing or older than in resources.
  check_installed_vendor_profiles();
  // Load indices from the cache directory.
  //index_db = Index::load_db();
}
References check_installed_vendor_profiles(), enabled_version_check, and set_download_prefs().
Member Function Documentation
check_installed_vendor_profiles()
void Slic3r::PresetUpdater::priv::check_installed_vendor_profiles () const
{
    BOOST_LOG_TRIVIAL(info) << "[BBL Updater]:Checking whether the profile from resource is newer";
    AppConfig *app_config = GUI::wxGetApp().app_config;
    const auto enabled_vendors = app_config->vendors();
    //BBS: refine the init check logic
    std::vector<std::string> bundles;
    for (auto &dir_entry : boost::filesystem::directory_iterator(rsrc_path)) {
        const auto &path = dir_entry.path();
        std::string file_path = path.string();
        if (is_json_file(file_path)) {
            const auto path_in_vendor = vendor_path / path.filename();
            std::string vendor_name = path.filename().string();
            // Remove the .json suffix.
            vendor_name.erase(vendor_name.size() - 5);
            if (enabled_config_update) {
                if ( fs::exists(path_in_vendor)) {
                    if (enabled_vendors.find(vendor_name) != enabled_vendors.end()) {
                        Semver resource_ver = get_version_from_json(file_path);
                        Semver vendor_ver = get_version_from_json(path_in_vendor.string());
                        bool version_match = ((resource_ver.maj() == vendor_ver.maj()) && (resource_ver.min() == vendor_ver.min()));
                        if (!version_match || (vendor_ver < resource_ver)) {
                            BOOST_LOG_TRIVIAL(info) << "[BBL Updater]:found vendor "<<vendor_name<<" newer version "<<resource_ver.to_string() <<" from resource, old version "<<vendor_ver.to_string();
                            bundles.push_back(vendor_name);
                        }
                    }
                    else {
                        //need to be removed because not installed
                        fs::remove(path_in_vendor);
                        const auto path_of_vendor = vendor_path / vendor_name;
                        if (fs::exists(path_of_vendor))
                            fs::remove_all(path_of_vendor);
                    }
                }
                else if ((vendor_name == PresetBundle::BBL_BUNDLE) || (enabled_vendors.find(vendor_name) != enabled_vendors.end())) {//if vendor has no file, copy it from resource for BBL
                    bundles.push_back(vendor_name);
                }
            }
            else if ((vendor_name == PresetBundle::BBL_BUNDLE) || (enabled_vendors.find(vendor_name) != enabled_vendors.end())) { //always update configs from resource to vendor for BBL
                bundles.push_back(vendor_name);
            }
        }
    }
    if (bundles.size() > 0)
        install_bundles_rsrc(bundles, false);
}
References Slic3r::PresetBundle::BBL_BUNDLE, Slic3r::get_version_from_json(), Slic3r::PresetUpdater::install_bundles_rsrc(), Slic3r::is_json_file(), Slic3r::Semver::maj(), Slic3r::Semver::min(), Slic3r::Semver::to_string(), and Slic3r::AppConfig::vendors().
Referenced by priv().
extract_file()
bool Slic3r::PresetUpdater::priv::extract_file (const fs::path & source_path, const fs::path & dest_path = {})
{
    bool res = true;
    std::string file_path = source_path.string();
    std::string parent_path = (!dest_path.empty() ? dest_path : source_path.parent_path()).string();
    mz_zip_archive archive;
    mz_zip_zero_struct(&archive);
    if (!open_zip_reader(&archive, file_path))
    {
        BOOST_LOG_TRIVIAL(error) << "Unable to open zip reader for "<<file_path;
        return false;
    }
    mz_uint num_entries = mz_zip_reader_get_num_files(&archive);
    mz_zip_archive_file_stat stat;
    // we first loop the entries to read from the archive the .amf file only, in order to extract the version from it
    for (mz_uint i = 0; i < num_entries; ++i)
    {
        if (mz_zip_reader_file_stat(&archive, i, &stat))
        {
            std::string dest_file = parent_path+"/"+stat.m_filename;
            if (stat.m_is_directory) {
                fs::path dest_path(dest_file);
                if (!fs::exists(dest_path))
                    fs::create_directories(dest_path);
        continue;
            }
            else if (stat.m_uncomp_size == 0) {
                BOOST_LOG_TRIVIAL(warning) << "[BBL Updater]Unzip: invalid size for file "<<stat.m_filename;
                continue;
            }
            try
            {
                res = mz_zip_reader_extract_to_file(&archive, stat.m_file_index, dest_file.c_str(), 0);
                if (!res) {
                    BOOST_LOG_TRIVIAL(error) << "[BBL Updater]extract file "<<stat.m_filename<<" to dest "<<dest_file<<" failed";
                    close_zip_reader(&archive);
                    return res;
                }
                BOOST_LOG_TRIVIAL(info) << "[BBL Updater]successfully extract file " << stat.m_file_index << " to "<<dest_file;
            }
            catch (const std::exception& e)
            {
                // ensure the zip archive is closed and rethrow the exception
                close_zip_reader(&archive);
                BOOST_LOG_TRIVIAL(error) << "[BBL Updater]Archive read exception:"<<e.what();
                return false;
            }
        }
        else {
            BOOST_LOG_TRIVIAL(warning) << "[BBL Updater]Unzip: read file stat failed";
        }
    }
    close_zip_reader(&archive);
  return true;
}
References Slic3r::close_zip_reader(), error, mz_zip_archive_file_stat::m_file_index, mz_zip_archive_file_stat::m_filename, mz_zip_archive_file_stat::m_is_directory, mz_zip_archive_file_stat::m_uncomp_size, mz_zip_reader_extract_to_file(), mz_zip_reader_file_stat(), mz_zip_reader_get_num_files(), mz_zip_zero_struct(), and Slic3r::open_zip_reader().
get_cached_plugins_version()
bool Slic3r::PresetUpdater::priv::get_cached_plugins_version (std::string & cached_version)
{
    std::string data_dir_str = data_dir();
    boost::filesystem::path data_dir_path(data_dir_str);
    auto cache_folder = data_dir_path / "ota";
    std::string network_library, player_library;
    bool has_plugins = false;
#if defined(_MSC_VER) || defined(_WIN32)
    network_library = cache_folder.string() + "/bambu_networking.dll";
    player_library = cache_folder.string() + "/BambuSource.dll";
#elif defined(__WXMAC__)
    network_library = cache_folder.string() + "/libbambu_networking.dylib";
    player_library = cache_folder.string() + "/libBambuSource.dylib";
#else
    network_library = cache_folder.string() + "/libbambu_networking.so";
    player_library = cache_folder.string() + "/libBambuSource.so";
#endif
    if (boost::filesystem::exists(network_library)
        && boost::filesystem::exists(player_library))
    {
        std::string changelog_file = cache_folder.string() + "/network_plugins.json";
        has_plugins = true;
        try {
            boost::nowide::ifstream ifs(changelog_file);
            json j;
            ifs >> j;
            cached_version = j["version"];
        }
        catch(nlohmann::detail::parse_error &err) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<<changelog_file<<" got a nlohmann::detail::parse_error, reason = " << err.what();
            //throw ConfigurationError(format("Failed loading json file \"%1%\": %2%", file_path, err.what()));
        }
    }
    return has_plugins;
}
References Slic3r::data_dir(), error, and nlohmann::detail::exception::what().
get_config_updates()
Updates Slic3r::PresetUpdater::priv::get_config_updates (const Semver & old_slic3r_version) const
{
  Updates updates;
  BOOST_LOG_TRIVIAL(info) << "[BBL Updater]:Checking for cached configuration updates...";
    for (auto &dir_entry : boost::filesystem::directory_iterator(cache_path)) {
        const auto &path = dir_entry.path();
        std::string file_path = path.string();
        if (is_json_file(file_path)) {
            const auto path_in_vendor = vendor_path / path.filename();
            std::string vendor_name = path.filename().string();
            // Remove the .json suffix.
            vendor_name.erase(vendor_name.size() - 5);
            auto print_in_cache = (cache_path / vendor_name / PRESET_PRINT_NAME);
            auto filament_in_cache = (cache_path / vendor_name / PRESET_FILAMENT_NAME);
            auto machine_in_cache = (cache_path / vendor_name / PRESET_PRINTER_NAME);
            if (( fs::exists(path_in_vendor))
                &&( fs::exists(print_in_cache))
                &&( fs::exists(filament_in_cache))
                &&( fs::exists(machine_in_cache))) {
                Semver vendor_ver = get_version_from_json(path_in_vendor.string());
                std::map<std::string, std::string> key_values;
                std::vector<std::string> keys(3);
        Semver cache_ver;
                keys[0] = BBL_JSON_KEY_VERSION;
                keys[1] = BBL_JSON_KEY_DESCRIPTION;
                keys[2] = BBL_JSON_KEY_FORCE_UPDATE;
                get_values_from_json(file_path, keys, key_values);
                std::string description = key_values[BBL_JSON_KEY_DESCRIPTION];
                bool force_update = false;
                if (key_values.find(BBL_JSON_KEY_FORCE_UPDATE) != key_values.end())
                    force_update = (key_values[BBL_JSON_KEY_FORCE_UPDATE] == "1")?true:false;
                auto config_version = Semver::parse(key_values[BBL_JSON_KEY_VERSION]);
                if (config_version)
                    cache_ver = *config_version;
                std::string changelog;
                std::string changelog_file = (cache_path / (vendor_name + ".changelog")).string();
                boost::nowide::ifstream ifs(changelog_file);
                if (ifs) {
                    std::ostringstream oss;
                    oss<< ifs.rdbuf();
                    changelog = oss.str();
                    //ifs>>changelog;
                    ifs.close();
                }
                bool version_match = ((vendor_ver.maj() == cache_ver.maj()) && (vendor_ver.min() == cache_ver.min()));
                if (version_match && (vendor_ver < cache_ver)) {
                    Semver app_ver = *Semver::parse(SLIC3R_VERSION);
                    if (cache_ver.maj() == app_ver.maj()){
                        BOOST_LOG_TRIVIAL(info) << "[BBL Updater]:need to update settings from "<<vendor_ver.to_string()<<" to newer version "<<cache_ver.to_string() <<", app version "<<SLIC3R_VERSION;
                        Version version;
                        version.config_version = cache_ver;
                        version.comment = description;
                        updates.updates.emplace_back(std::move(file_path), std::move(path_in_vendor.string()), std::move(version), vendor_name, changelog, description, force_update, false);
                        //BBS: add directory support
                        auto print_in_vendors = (vendor_path / vendor_name / PRESET_PRINT_NAME);
                        updates.updates.emplace_back(std::move(print_in_cache), std::move(print_in_vendors.string()), Version(), vendor_name, "", "", force_update, true);
                        auto filament_in_vendors = (vendor_path / vendor_name / PRESET_FILAMENT_NAME);
                        updates.updates.emplace_back(std::move(filament_in_cache), std::move(filament_in_vendors.string()), Version(), vendor_name, "", "", force_update, true);
                        auto machine_in_vendors = (vendor_path / vendor_name / PRESET_PRINTER_NAME);
                        updates.updates.emplace_back(std::move(machine_in_cache), std::move(machine_in_vendors.string()), Version(), vendor_name, "", "", force_update, true);
                    }
                }
            }
        }
    }
  return updates;
}
References BBL_JSON_KEY_DESCRIPTION, BBL_JSON_KEY_FORCE_UPDATE, BBL_JSON_KEY_VERSION, Slic3r::GUI::Config::Version::comment, Slic3r::GUI::Config::Version::config_version, Slic3r::get_values_from_json(), Slic3r::get_version_from_json(), Slic3r::is_json_file(), Slic3r::Semver::maj(), Slic3r::Semver::min(), Slic3r::Semver::parse(), PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, PRESET_PRINTER_NAME, Slic3r::Semver::to_string(), and Slic3r::Updates::updates.
get_file()
bool Slic3r::PresetUpdater::priv::get_file (const std::string & url, const fs::path & target_path) const
{
    bool res = false;
    fs::path tmp_path = target_path;
    tmp_path += format(".%1%%2%", get_current_pid(), TMP_EXTENSION);
    BOOST_LOG_TRIVIAL(info) << format("[BBS Updater]download file `%1%`, stored to `%2%`, tmp path `%3%`",
        url,
        target_path.string(),
        tmp_path.string());
    Slic3r::Http::get(url)
        .on_progress([this](Slic3r::Http::Progress, bool &cancel_http) {
            if (cancel) {
                cancel_http = true;
            }
        })
        .on_error([&](std::string body, std::string error, unsigned http_status) {
            (void)body;
            BOOST_LOG_TRIVIAL(error) << format("[BBS Updater]getting: `%1%`: http status %2%, %3%",
                url,
                http_status,
                error);
        })
        .on_complete([&](std::string body, unsigned /* http_status */) {
            fs::fstream file(tmp_path, std::ios::out | std::ios::binary | std::ios::trunc);
            file.write(body.c_str(), body.size());
            file.close();
            fs::rename(tmp_path, target_path);
            res = true;
        })
        .perform_sync();
    return res;
}
References error, Slic3r::format(), Slic3r::Http::get(), Slic3r::get_current_pid(), Slic3r::Http::on_progress(), Slic3r::TMP_EXTENSION, and void().
install_bundles_rsrc()
bool Slic3r::PresetUpdater::priv::install_bundles_rsrc (std::vector< std::string > bundles, bool snapshot) const
{
  Updates updates;
  BOOST_LOG_TRIVIAL(info) << format("Installing %1% bundles from resources ...", bundles.size());
  for (const auto &bundle : bundles) {
    auto path_in_rsrc = (this->rsrc_path / bundle).replace_extension(".json");
    auto path_in_vendors = (this->vendor_path / bundle).replace_extension(".json");
    updates.updates.emplace_back(std::move(path_in_rsrc), std::move(path_in_vendors), Version(), bundle, "", "");
        //BBS: add directory support
        auto print_in_rsrc = (this->rsrc_path / bundle / PRESET_PRINT_NAME);
    auto print_in_vendors = (this->vendor_path / bundle / PRESET_PRINT_NAME);
        fs::path print_folder(print_in_vendors);
        if (fs::exists(print_folder))
            fs::remove_all(print_folder);
        fs::create_directories(print_folder);
    updates.updates.emplace_back(std::move(print_in_rsrc), std::move(print_in_vendors), Version(), bundle, "", "", false, true);
        auto filament_in_rsrc = (this->rsrc_path / bundle / PRESET_FILAMENT_NAME);
    auto filament_in_vendors = (this->vendor_path / bundle / PRESET_FILAMENT_NAME);
        fs::path filament_folder(filament_in_vendors);
        if (fs::exists(filament_folder))
            fs::remove_all(filament_folder);
        fs::create_directories(filament_folder);
    updates.updates.emplace_back(std::move(filament_in_rsrc), std::move(filament_in_vendors), Version(), bundle, "", "", false, true);
        auto machine_in_rsrc = (this->rsrc_path / bundle / PRESET_PRINTER_NAME);
    auto machine_in_vendors = (this->vendor_path / bundle / PRESET_PRINTER_NAME);
        fs::path machine_folder(machine_in_vendors);
        if (fs::exists(machine_folder))
            fs::remove_all(machine_folder);
        fs::create_directories(machine_folder);
    updates.updates.emplace_back(std::move(machine_in_rsrc), std::move(machine_in_vendors), Version(), bundle, "", "", false, true);
  }
  return perform_updates(std::move(updates), snapshot);
}
References Slic3r::format(), PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, PRESET_PRINTER_NAME, and Slic3r::Updates::updates.
parse_version_string()
void Slic3r::PresetUpdater::priv::parse_version_string (const std::string & body) const
{
#if 0
  // release version
  std::string version;
  const auto first_nl_pos = body.find_first_of("\n\r");
  if (first_nl_pos != std::string::npos)
    version = body.substr(0, first_nl_pos);
  else
    version = body;
  boost::optional<Semver> release_version = Semver::parse(version);
  if (!release_version) {
    BOOST_LOG_TRIVIAL(error) << format("Received invalid contents from `%1%`: Not a correct semver: `%2%`", SLIC3R_APP_NAME, version);
    return;
  }
  BOOST_LOG_TRIVIAL(info) << format("Got %1% online version: `%2%`. Sending to GUI thread...", SLIC3R_APP_NAME, version);
  wxCommandEvent* evt = new wxCommandEvent(EVT_SLIC3R_VERSION_ONLINE);
  evt->SetString(GUI::from_u8(version));
  GUI::wxGetApp().QueueEvent(evt);
  // alpha / beta version
  std::vector<std::string> prerelease_versions;
  size_t nexn_nl_pos = first_nl_pos;
  while (nexn_nl_pos != std::string::npos && body.size() > nexn_nl_pos + 1) {
    const auto last_nl_pos = nexn_nl_pos;
    nexn_nl_pos = body.find_first_of("\n\r", last_nl_pos + 1);
    std::string line;
    if (nexn_nl_pos == std::string::npos)
      line = body.substr(last_nl_pos + 1);
    else
      line = body.substr(last_nl_pos + 1, nexn_nl_pos - last_nl_pos - 1);
    // alpha
    if (line.substr(0, 6) == "alpha=") {
      version = line.substr(6);
      if (!Semver::parse(version)) {
        BOOST_LOG_TRIVIAL(error) << format("Received invalid contents for alpha release from `%1%`: Not a correct semver: `%2%`", SLIC3R_APP_NAME, version);
        return;
      }
      prerelease_versions.emplace_back(version);
    // beta
    }
    else if (line.substr(0, 5) == "beta=") {
      version = line.substr(5);
      if (!Semver::parse(version)) {
        BOOST_LOG_TRIVIAL(error) << format("Received invalid contents for beta release from `%1%`: Not a correct semver: `%2%`", SLIC3R_APP_NAME, version);
        return;
      }
      prerelease_versions.emplace_back(version);
    }
  }
  // find recent version that is newer than last full release.
  boost::optional<Semver> recent_version;
  for (const std::string& ver_string : prerelease_versions) {
    boost::optional<Semver> ver = Semver::parse(ver_string);
    if (ver && *release_version < *ver && ((recent_version && *recent_version < *ver) || !recent_version)) {
      recent_version = ver;
      version = ver_string;
    }
  }
  if (recent_version) {
    BOOST_LOG_TRIVIAL(info) << format("Got %1% online version: `%2%`. Sending to GUI thread...", SLIC3R_APP_NAME, version);
    wxCommandEvent* evt = new wxCommandEvent(EVT_SLIC3R_EXPERIMENTAL_VERSION_ONLINE);
    evt->SetString(GUI::from_u8(version));
    GUI::wxGetApp().QueueEvent(evt);
  }
#endif
    return;
}
References error, Slic3r::format(), Slic3r::GUI::from_u8(), and Slic3r::Semver::parse().
perform_updates()
bool Slic3r::PresetUpdater::priv::perform_updates (Updates && updates, bool snapshot = true) const
{
    //std::string vendor_path;
    //std::string vendor_name;
    if (updates.incompats.size() > 0) {
        //if (snapshot) {
        //  BOOST_LOG_TRIVIAL(info) << "Taking a snapshot...";
        //  if (! GUI::Config::take_config_snapshot_cancel_on_error(*GUI::wxGetApp().app_config, Snapshot::SNAPSHOT_DOWNGRADE, "",
        //    _u8L("Continue and install configuration updates?")))
        //    return false;
        //}
        BOOST_LOG_TRIVIAL(info) << format("[BBL Updater]:Deleting %1% incompatible bundles", updates.incompats.size());
        for (auto &incompat : updates.incompats) {
            BOOST_LOG_TRIVIAL(info) << '\t' << incompat;
            incompat.remove();
        }
    } else if (updates.updates.size() > 0) {
        //if (snapshot) {
        //  BOOST_LOG_TRIVIAL(info) << "Taking a snapshot...";
        //  if (! GUI::Config::take_config_snapshot_cancel_on_error(*GUI::wxGetApp().app_config, Snapshot::SNAPSHOT_UPGRADE, "",
        //    _u8L("Continue and install configuration updates?")))
        //    return false;
        //}
        BOOST_LOG_TRIVIAL(info) << format("[BBL Updater]:Performing %1% updates", updates.updates.size());
        for (const auto &update : updates.updates) {
            BOOST_LOG_TRIVIAL(info) << '\t' << update;
            update.install();
            //if (!update.is_directory) {
            //    vendor_path = update.source.parent_path().string();
            //    vendor_name = update.vendor;
            //}
        }
        //if (!vendor_path.empty()) {
        //    PresetBundle bundle;
        //    // Throw when parsing invalid configuration. Only valid configuration is supposed to be provided over the air.
        //    bundle.load_vendor_configs_from_json(vendor_path, vendor_name, PresetBundle::LoadConfigBundleAttribute::LoadSystem, ForwardCompatibilitySubstitutionRule::Disable);
        //    BOOST_LOG_TRIVIAL(info) << format("Deleting %1% conflicting presets", bundle.prints.size() + bundle.filaments.size() + bundle.printers.size());
        //    auto preset_remover = [](const Preset& preset) {
        //        BOOST_LOG_TRIVIAL(info) << '\t' << preset.file;
        //        fs::remove(preset.file);
        //    };
        //    for (const auto &preset : bundle.prints)    { preset_remover(preset); }
        //    for (const auto &preset : bundle.filaments) { preset_remover(preset); }
        //    for (const auto &preset : bundle.printers)  { preset_remover(preset); }
        //}
    }
    return true;
}
References Slic3r::format().
prune_tmps()
void Slic3r::PresetUpdater::priv::prune_tmps () const
{
    for (auto &dir_entry : boost::filesystem::directory_iterator(cache_path))
    if (is_plain_file(dir_entry) && dir_entry.path().extension() == TMP_EXTENSION) {
      BOOST_LOG_TRIVIAL(debug) << "[BBL Updater]remove old cached files: " << dir_entry.path().string();
      fs::remove(dir_entry.path());
    }
}
References Slic3r::is_plain_file(), and Slic3r::TMP_EXTENSION.
set_download_prefs()
void Slic3r::PresetUpdater::priv::set_download_prefs (AppConfig * app_config)
{
  version_check_url = app_config->version_check_url();
  //TODO: for debug currently
  if (version_check_url.empty())
    enabled_config_update = true;
  else
    enabled_config_update = false;
}
References Slic3r::AppConfig::version_check_url().
Referenced by priv().
set_waiting_updates()
void Slic3r::PresetUpdater::priv::set_waiting_updates (Updates u)
{
  waiting_updates = u;
  has_waiting_updates = true;
}
sync_config()
void Slic3r::PresetUpdater::priv::sync_config (std::string http_url, const VendorMap vendors)
{
    std::map<std::string, std::pair<Semver, std::string>> vendor_list;
    std::map<std::string, std::string> vendor_descriptions;
  BOOST_LOG_TRIVIAL(info) << "[BBL Updater]: sync_config Syncing configuration cache";
  if (!enabled_config_update) { return; }
    BOOST_LOG_TRIVIAL(info) << boost::format("[BBL Updater]: sync_config get preferred setting version for app version %1%, http_url: %2%")%SLIC3R_APP_NAME%http_url;
    std::string query_params = "?";
    bool first = true;
    for (auto vendor_it :vendors) {
        if (cancel) { return; }
        const VendorProfile& vendor_profile = vendor_it.second;
        std::string vendor_name = vendor_profile.id;
        boost::to_lower(vendor_name);
        std::string query_vendor = (boost::format("slicer/settings/%1%=%2%")
            % vendor_name
            % GUI::VersionInfo::convert_full_version(SLIC3R_VERSION)
            ).str();
        if (!first)
            query_params += "&";
        query_params += query_vendor;
    }
    std::string url = http_url;
    url += query_params;
    Slic3r::Http http = Slic3r::Http::get(url);
    BOOST_LOG_TRIVIAL(info) << boost::format("[BBL Updater]: sync_config request_url: %1%")%url;
    http.on_progress([this](Slic3r::Http::Progress, bool &cancel_http) {
            if (cancel) {
                cancel_http = true;
            }
        })
        .on_complete(
        [this, &vendor_list, &vendor_descriptions, vendors](std::string body, unsigned) {
            try {
                BOOST_LOG_TRIVIAL(info) << "[BBL Updater]::body=" << body;
                json j = json::parse(body);
                std::string message = j["message"].get<std::string>();
                if (message == "success") {
                    json resource =j.at("resources");
                    if (resource.is_array()) {
                        for (auto iter = resource.begin(); iter != resource.end(); iter++) {
                            Semver version;
                            std::string url;
                            std::string type;
                            std::string vendor;
                            std::string description;
                            for (auto sub_iter = iter.value().begin(); sub_iter != iter.value().end(); sub_iter++) {
                                if (boost::iequals(sub_iter.key(),"type")) {
                                    type = sub_iter.value();
                                    BOOST_LOG_TRIVIAL(trace) << "[BBL Updater]: get version of settings's type, " << sub_iter.value();
                                }
                                else if (boost::iequals(sub_iter.key(),"version")) {
                                    version = *(Semver::parse(sub_iter.value()));
                                }
                                else if (boost::iequals(sub_iter.key(),"description")) {
                                    description = sub_iter.value();
                                }
                                else if (boost::iequals(sub_iter.key(),"url")) {
                                    url = sub_iter.value();
                                }
                            }
                            BOOST_LOG_TRIVIAL(info) << "[BBL Updater]: get type "<< type <<", version "<<version.to_string()<<", url " << url;
                            for (auto vendor_it :vendors) {
                                const VendorProfile& vendor_profile = vendor_it.second;
                                std::string vendor_name = vendor_profile.id;
                                boost::to_lower(vendor_name);
                                if (type.find(vendor_name) != std::string::npos) {
                                    vendor = vendor_profile.id;
                                    break;
                                }
                            }
                            if (!vendor.empty()) {
                                vendor_list.emplace(vendor, std::pair<Semver, std::string>(version, url));
                                vendor_descriptions.emplace(vendor, description);
                            }
                        }
                    }
                }
                else {
                    BOOST_LOG_TRIVIAL(error) << "[BBL Updater]: get version of settings failed, body=" << body;
                }
            }
            catch (std::exception& e) {
                BOOST_LOG_TRIVIAL(error) << (boost::format("[BBL Updater]: get version of settings failed, exception=%1% body=%2%")
                    % e.what()
                    % body).str();
            }
            catch (...) {
                BOOST_LOG_TRIVIAL(error) << "[BBL Updater]: get version of settings failed,, body=" << body;
            }
        }
    )
    .on_error([&](std::string body, std::string error, unsigned status) {
            BOOST_LOG_TRIVIAL(error) << boost::format("[BBL Updater]: status=%1%, error=%2%, body=%3%")
                % status
                % error
                % body;
        }
    )
    .perform_sync();
    for (auto vendor_it :vendors) {
        if (cancel) { return; }
        const VendorProfile& vendor_profile = vendor_it.second;
        std::string vendor_name = vendor_profile.id;
        auto vendor_update = vendor_list.find(vendor_name);
        if (vendor_update == vendor_list.end()) {
      BOOST_LOG_TRIVIAL(info) << "[BBL Updater]Vendor " << vendor_name << " can not get setting versions online";
      continue;
    }
        Semver online_version = vendor_update->second.first;
        //Semver current_version = get_version_from_json(vendor_root_config.string());
        Semver current_version = vendor_profile.config_version;
        bool version_match = ((online_version.maj() == current_version.maj()) && (online_version.min() == current_version.min()));
        if (version_match && (current_version < online_version)) {
            auto cache_file = cache_path / (vendor_name+".json");
            auto cache_print_dir = (cache_path / vendor_name / PRESET_PRINT_NAME);
            auto cache_filament_dir = (cache_path / vendor_name / PRESET_FILAMENT_NAME);
            auto cache_machine_dir = (cache_path / vendor_name / PRESET_PRINTER_NAME);
            if (( fs::exists(cache_file))
                &&( fs::exists(cache_print_dir))
                &&( fs::exists(cache_filament_dir))
                &&( fs::exists(cache_machine_dir))) {
                Semver version = get_version_from_json(cache_file.string());
                bool cached_version_match = ((online_version.maj() == version.maj()) && (online_version.min() == version.min()));
                if (cached_version_match && (version >= online_version)) {
                    //already downloaded before
                    BOOST_LOG_TRIVIAL(info) << "[BBL Updater]Vendor " << vendor_name << ", already cached a version "<<version.to_string();
                    continue;
                }
            }
            if (cancel) { return; }
            //need to download the online files
            std::string online_url = vendor_update->second.second;
            std::string cache_file_path = (cache_path / (vendor_name + TMP_EXTENSION)).string();
            BOOST_LOG_TRIVIAL(info) << "[BBL Updater]Downloading online settings for vendor: " << vendor_name<<", version "<<online_version.to_string();
            if (!get_file(online_url, cache_file_path)) {
                BOOST_LOG_TRIVIAL(warning) << "[BBL Updater]download settings for vendor "<<vendor_name<<" failed, url: " << online_url;
                continue;
            }
        if (cancel) { return; }
            //remove previous files before
            if (fs::exists(cache_print_dir))
                fs::remove_all(cache_print_dir);
            if (fs::exists(cache_filament_dir))
                fs::remove_all(cache_filament_dir);
            if (fs::exists(cache_machine_dir))
                fs::remove_all(cache_machine_dir);
            //extract the file downloaded
            BOOST_LOG_TRIVIAL(info) << "[BBL Updater]start to unzip the downloaded file "<< cache_file_path;
            if (!extract_file(cache_file_path)) {
                BOOST_LOG_TRIVIAL(warning) << "[BBL Updater]extract settings for vendor "<<vendor_name<<" failed, path: " << cache_file_path;
                continue;
            }
            BOOST_LOG_TRIVIAL(info) << "[BBL Updater]finished unzip the downloaded file "<< cache_file_path;
            auto vendor_description = vendor_descriptions.find(vendor_name);
            if (vendor_description != vendor_descriptions.end()) {
                //save the description to disk
                std::string changelog_file = (cache_path / (vendor_name + ".changelog")).string();
                boost::nowide::ofstream c;
                c.open(changelog_file, std::ios::out | std::ios::trunc);
                c << vendor_description->second << std::endl;
                c.close();
            }
        }
    }
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::at(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::begin(), Slic3r::VendorProfile::config_version, Slic3r::GUI::VersionInfo::convert_full_version(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::end(), error, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), Slic3r::Http::get(), Slic3r::get_version_from_json(), Slic3r::VendorProfile::id, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::is_array(), Slic3r::Semver::maj(), Slic3r::Semver::min(), Slic3r::Http::on_progress(), Slic3r::Semver::parse(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, PRESET_PRINTER_NAME, Slic3r::TMP_EXTENSION, Slic3r::Semver::to_string(), and Slic3r::trace().
sync_plugins()
void Slic3r::PresetUpdater::priv::sync_plugins (std::string http_url, std::string plugin_version)
{
    if (plugin_version == "00.00.00.00") {
        BOOST_LOG_TRIVIAL(info) << "non need to sync plugins for there is no plugins currently.";
        return;
    }
    std::string curr_version = SLIC3R_VERSION;
    std::string using_version = curr_version.substr(0, 9) + "00";
    std::string cached_version;
    get_cached_plugins_version(cached_version);
    if (!cached_version.empty()) {
        bool need_delete_cache = false;
        Semver current_semver = curr_version;
        Semver cached_semver = cached_version;
        int curent_patch_cc = current_semver.patch()/100;
        int cached_patch_cc = cached_semver.patch()/100;
        int curent_patch_dd = current_semver.patch()%100;
        int cached_patch_dd = cached_semver.patch()%100;
        if ((cached_semver.maj() != current_semver.maj())
            || (cached_semver.min() != current_semver.min())
            || (curent_patch_cc != cached_patch_cc))
        {
            need_delete_cache = true;
            BOOST_LOG_TRIVIAL(info) << boost::format("cached plugins version %1% not match with current %2%")%cached_version%curr_version;
        }
        else if (cached_patch_dd <= curent_patch_dd) {
            need_delete_cache = true;
            BOOST_LOG_TRIVIAL(info) << boost::format("cached plugins version %1% not newer than current %2%")%cached_version%curr_version;
        }
        else {
            plugin_version = cached_version;
        }
        if (need_delete_cache) {
            std::string data_dir_str = data_dir();
            boost::filesystem::path data_dir_path(data_dir_str);
            auto cache_folder = data_dir_path / "ota";
#if defined(_MSC_VER) || defined(_WIN32)
            auto network_library = cache_folder / "bambu_networking.dll";
            auto player_library = cache_folder / "BambuSource.dll";
#elif defined(__WXMAC__)
            auto network_library = cache_folder / "libbambu_networking.dylib";
            auto player_library = cache_folder / "libBambuSource.dylib";
#else
            auto network_library = cache_folder / "libbambu_networking.so";
            auto player_library = cache_folder / "libBambuSource.so";
#endif
            auto changelog_file = cache_folder / "network_plugins.json";
            if (boost::filesystem::exists(network_library))
            {
                BOOST_LOG_TRIVIAL(info) << "[remove_old_networking_plugins] remove the file "<<network_library.string();
                try {
                    fs::remove(network_library);
                } catch (...) {
                    BOOST_LOG_TRIVIAL(error) << "Failed  removing the plugins file " << network_library.string();
                }
            }
            if (boost::filesystem::exists(player_library))
            {
                BOOST_LOG_TRIVIAL(info) << "[remove_old_networking_plugins] remove the file "<<player_library.string();
                try {
                    fs::remove(player_library);
                } catch (...) {
                    BOOST_LOG_TRIVIAL(error) << "Failed  removing the plugins file " << player_library.string();
                }
            }
            if (boost::filesystem::exists(changelog_file))
            {
                BOOST_LOG_TRIVIAL(info) << "[remove_old_networking_plugins] remove the file "<<changelog_file.string();
                try {
                    fs::remove(changelog_file);
                } catch (...) {
                    BOOST_LOG_TRIVIAL(error) << "Failed  removing the plugins file " << changelog_file.string();
                }
            }
        }
    }
    try {
        std::map<std::string, Resource> resources
        {
            {"slicer/plugins/cloud", { using_version, "", "", cache_path.string(), {"plugins"}}}
        };
        sync_resources(http_url, resources, true, plugin_version, "network_plugins.json");
    }
    catch (std::exception& e) {
        BOOST_LOG_TRIVIAL(warning) << format("[BBL Updater] sync_plugins: %1%", e.what());
    }
    bool result = get_cached_plugins_version(cached_version);
    if (result) {
        BOOST_LOG_TRIVIAL(info) << format("[BBL Updater] found new plugins: %1%, prompt to update", cached_version);
        GUI::wxGetApp().plater()->get_notification_manager()->push_notification(GUI::NotificationType::BBLPluginUpdateAvailable);
    }
}
References Slic3r::GUI::BBLPluginUpdateAvailable, Slic3r::data_dir(), error, Slic3r::format(), Slic3r::Semver::maj(), Slic3r::Semver::min(), and Slic3r::Semver::patch().
sync_resources()
void Slic3r::PresetUpdater::priv::sync_resources (std::string http_url, std::map< std::string, Resource > & resources, bool check_patch = false, std::string current_version = "", std::string changelog_file = "")
{
    std::map<std::string, Resource>    resource_list;
    BOOST_LOG_TRIVIAL(info) << boost::format("[BBL Updater]: sync_resources get preferred setting version for app version %1%, url: %2%, current_version_str %3%, check_patch %4%")%SLIC3R_APP_NAME%http_url%current_version_str%check_patch;
    std::string query_params = "?";
    bool        first        = true;
    for (auto resource_it : resources) {
        if (cancel) { return; }
        auto resource_name = resource_it.first;
        boost::to_lower(resource_name);
        std::string query_resource = (boost::format("%1%=%2%")
            % resource_name % resource_it.second.version).str();
        if (!first) query_params += "&";
        query_params += query_resource;
        first = false;
    }
    std::string url = http_url;
    url += query_params;
    Slic3r::Http http = Slic3r::Http::get(url);
    BOOST_LOG_TRIVIAL(info) << boost::format("[BBL Updater]: sync_resources request_url: %1%")%url;
    http.on_progress([this](Slic3r::Http::Progress, bool &cancel_http) {
            if (cancel) {
                cancel_http = true;
            }
        })
        .on_complete([this, &resource_list, resources](std::string body, unsigned) {
            try {
                BOOST_LOG_TRIVIAL(info) << "[BBL Updater]: request_resources, body=" << body;
                json        j       = json::parse(body);
                std::string message = j["message"].get<std::string>();
                if (message == "success") {
                    json resource = j.at("resources");
                    if (resource.is_array()) {
                        for (auto iter = resource.begin(); iter != resource.end(); iter++) {
                            std::string version;
                            std::string url;
                            std::string resource;
                            std::string description;
                            for (auto sub_iter = iter.value().begin(); sub_iter != iter.value().end(); sub_iter++) {
                                if (boost::iequals(sub_iter.key(), "type")) {
                                    resource = sub_iter.value();
                                    BOOST_LOG_TRIVIAL(trace) << "[BBL Updater]: get version of settings's type, " << sub_iter.value();
                                } else if (boost::iequals(sub_iter.key(), "version")) {
                                    version = sub_iter.value();
                                } else if (boost::iequals(sub_iter.key(), "description")) {
                                    description = sub_iter.value();
                                } else if (boost::iequals(sub_iter.key(), "url")) {
                                    url = sub_iter.value();
                                }
                            }
                            BOOST_LOG_TRIVIAL(info) << "[BBL Updater]: get type " << resource << ", version " << version << ", url " << url;
                            resource_list.emplace(resource, Resource{version, description, url});
                        }
                    }
                } else {
                    BOOST_LOG_TRIVIAL(error) << "[BBL Updater]: get version of settings failed, body=" << body;
                }
            } catch (std::exception &e) {
                BOOST_LOG_TRIVIAL(error) << (boost::format("[BBL Updater]: get version of settings failed, exception=%1% body=%2%") % e.what() % body).str();
            } catch (...) {
                BOOST_LOG_TRIVIAL(error) << "[BBL Updater]: get version of settings failed, body=" << body;
            }
        })
        .on_error([&](std::string body, std::string error, unsigned status) {
            BOOST_LOG_TRIVIAL(error) << boost::format("[BBL Updater]: status=%1%, error=%2%, body=%3%") % status % error % body;
        })
        .perform_sync();
    for (auto & resource_it : resources) {
        if (cancel) { return; }
        auto resource = resource_it.second;
        std::string resource_name = resource_it.first;
        boost::to_lower(resource_name);
        auto        resource_update = resource_list.find(resource_name);
        if (resource_update == resource_list.end()) {
            BOOST_LOG_TRIVIAL(info) << "[BBL Updater]Vendor " << resource_name << " can not get setting versions online";
            continue;
        }
        Semver online_version = resource_update->second.version;
        // Semver current_version = get_version_from_json(vendor_root_config.string());
        Semver current_version = current_version_str.empty()?resource.version:current_version_str;
        bool version_match = ((online_version.maj() == current_version.maj()) && (online_version.min() == current_version.min()));
        if (version_match && check_patch) {
            int online_cc_patch = online_version.patch()/100;
            int current_cc_patch = current_version.patch()/100;
            if (online_cc_patch != current_cc_patch) {
                version_match = false;
                BOOST_LOG_TRIVIAL(warning) << boost::format("[BBL Updater]: online patch CC not match: online_cc_patch=%1%, current_cc_patch=%2%") % online_cc_patch % current_cc_patch;
            }
        }
        if (version_match && (current_version < online_version)) {
            if (cancel) { return; }
            // need to download the online files
            fs::path cache_path(resource.cache_root);
            std::string online_url      = resource_update->second.url;
            std::string cache_file_path = (fs::temp_directory_path() / (fs::unique_path().string() + TMP_EXTENSION)).string();
            BOOST_LOG_TRIVIAL(info) << "[BBL Updater]Downloading resource: " << resource_name << ", version " << online_version.to_string();
            if (!get_file(online_url, cache_file_path)) {
                BOOST_LOG_TRIVIAL(warning) << "[BBL Updater]download resource " << resource_name << " failed, url: " << online_url;
                continue;
            }
            if (cancel) { return; }
            // remove previous files before
            if (resource.sub_caches.empty()) {
                if (fs::exists(cache_path)) {
                    fs::remove_all(cache_path);
                    BOOST_LOG_TRIVIAL(info) << "[BBL Updater]remove cache path " << cache_path.string();
                }
            } else {
                for (auto sub : resource.sub_caches) {
                    if (fs::exists(cache_path / sub)) {
                        fs::remove_all(cache_path / sub);
                        BOOST_LOG_TRIVIAL(info) << "[BBL Updater]remove cache path " << (cache_path / sub).string();
                    }
                }
            }
            // extract the file downloaded
            BOOST_LOG_TRIVIAL(info) << "[BBL Updater]start to unzip the downloaded file " << cache_file_path << " to "<<cache_path;
            fs::create_directories(cache_path);
            if (!extract_file(cache_file_path, cache_path)) {
                BOOST_LOG_TRIVIAL(warning) << "[BBL Updater]extract resource " << resource_it.first << " failed, path: " << cache_file_path;
                continue;
            }
            BOOST_LOG_TRIVIAL(info) << "[BBL Updater]finished unzip the downloaded file " << cache_file_path;
            // save the description to disk
            if (changelog_file.empty())
                changelog_file = (cache_path / "changelog.json").string();
            else
                changelog_file = (cache_path / changelog_file).string();
            try {
                json j;
                //record the headers
                j["version"] = resource_update->second.version;
                j["description"] = resource_update->second.description;
                boost::nowide::ofstream c;
                c.open(changelog_file, std::ios::out | std::ios::trunc);
                c << std::setw(4) << j << std::endl;
                c.close();
            }
            catch(std::exception &err) {
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": save to "<<changelog_file<<" got a generic exception, reason = " << err.what();
            }
            resource_it.second = resource_update->second;
        }
        else {
            BOOST_LOG_TRIVIAL(warning) << boost::format("[BBL Updater]: online version=%1%, current_version=%2%, no need to download") % online_version.to_string() % current_version.to_string();
        }
    }
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::at(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::begin(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::end(), error, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), Slic3r::Http::get(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::is_array(), Slic3r::Semver::maj(), Slic3r::Semver::min(), Slic3r::Http::on_progress(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), Slic3r::Semver::patch(), Slic3r::TMP_EXTENSION, Slic3r::Semver::to_string(), Slic3r::trace(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::value().
sync_tooltip()
void Slic3r::PresetUpdater::priv::sync_tooltip (std::string http_url, std::string language)
{
    try {
        std::string common_version = "00.00.00.00";
        std::string language_version = "00.00.00.00";
        fs::path cache_root = fs::path(data_dir()) / "resources/tooltip";
        try {
            auto vf = cache_root / "common" / "version";
            if (fs::exists(vf)) fs::load_string_file(vf, common_version);
            vf = cache_root / language / "version";
            if (fs::exists(vf)) fs::load_string_file(vf, language_version);
        } catch (...) {}
        std::map<std::string, Resource> resources
        {
            {"slicer/tooltip/common", { common_version, "", "", (cache_root / "common").string() }},
            {"slicer/tooltip/" + language, { language_version, "", "", (cache_root / language).string() }}
        };
        sync_resources(http_url, resources);
        for (auto &r : resources) {
            if (!r.second.url.empty()) {
                GUI::MarkdownTip::Reload();
                break;
            }
        }
    }
    catch (std::exception& e) {
        BOOST_LOG_TRIVIAL(warning) << format("[BBL Updater] sync_tooltip: %1%", e.what());
    }
}
References Slic3r::data_dir(), Slic3r::format(), and Slic3r::GUI::MarkdownTip::Reload().
sync_version()
void Slic3r::PresetUpdater::priv::sync_version () const
{
  if (! enabled_version_check) { return; }
#if 0
  Http::get(version_check_url)
    .size_limit(SLIC3R_VERSION_BODY_MAX)
    .on_progress([this](Http::Progress, bool &cancel) {
      cancel = this->cancel;
    })
    .on_error([&](std::string body, std::string error, unsigned http_status) {
      (void)body;
      BOOST_LOG_TRIVIAL(error) << format("Error getting: `%1%`: HTTP %2%, %3%",
        version_check_url,
        http_status,
        error);
    })
    .on_complete([&](std::string body, unsigned /* http_status */) {
      boost::trim(body);
      parse_version_string(body);
    })
    .perform_sync();
#endif
}
References error, Slic3r::format(), Slic3r::Http::get(), Slic3r::Http::on_progress(), Slic3r::Http::size_limit(), Slic3r::SLIC3R_VERSION_BODY_MAX, and void().
Member Data Documentation
cache_path
fs::path Slic3r::PresetUpdater::priv::cache_path
cancel
bool Slic3r::PresetUpdater::priv::cancel
enabled_config_update
bool Slic3r::PresetUpdater::priv::enabled_config_update
enabled_version_check
bool Slic3r::PresetUpdater::priv::enabled_version_check
Referenced by priv().
has_waiting_updates
bool Slic3r::PresetUpdater::priv::has_waiting_updates { false }
index_db
std::vector<Index> Slic3r::PresetUpdater::priv::index_db
rsrc_path
fs::path Slic3r::PresetUpdater::priv::rsrc_path
thread
std::thread Slic3r::PresetUpdater::priv::thread
vendor_path
fs::path Slic3r::PresetUpdater::priv::vendor_path
version_check_url
std::string Slic3r::PresetUpdater::priv::version_check_url
waiting_updates
Updates Slic3r::PresetUpdater::priv::waiting_updates
The documentation for this struct was generated from the following file:
src/slic3r/Utils/PresetUpdater.cpp