OrcaSlicer: matrix_t< T > Class Template Reference
matrix_t< T > Class Template Reference
#include <src/mcut/include/mcut/internal/math.h>
Public Member Functions
matrix_t ()
matrix_t (unsigned int rows, unsigned int cols)
T & operator() (unsigned int row, unsigned int col)
T operator() (unsigned int row, unsigned int col) const
matrix_t< T > operator* (const matrix_t< T > &other) const
matrix_t< T > operator* (const double &s) const
matrix_t< T > operator/ (const double &s) const
matrix_t< T > operator- (const matrix_t< T > &m) const
vec2 operator* (const vec3 &v) const
int rows () const
int cols () const
Private Attributes
int m_rows
int m_cols
std::vector< T > m_entries
Detailed Description
template<typename T = int>
class matrix_t< T >
Constructor & Destructor Documentation
matrix_t() [1/2]
template<typename T = int> matrix_t< T >::matrix_t () inline
        : m_rows(-1)
        , m_cols(-1)
    {
    }
matrix_t() [2/2]
template<typename T = int> matrix_t< T >::matrix_t (unsigned int rows, unsigned int cols) inline
        : m_rows(rows)
        , m_cols(cols)
        , m_entries(std::vector<T>((size_t)rows * cols, T(0.0))) // zeroes
    {
    }
Member Function Documentation
cols()
template<typename T = int> int matrix_t< T >::cols () const inline
    {
        return m_cols;
    }
References matrix_t< T >::m_cols.
Referenced by matrix_t< T >::operator*(), matrix_t< T >::operator*(), matrix_t< T >::operator-(), and operator<<().
operator()() [1/2]
template<typename T = int> T & matrix_t< T >::operator() (unsigned int row, unsigned int col) inline
    {
        return m_entries[(size_t)row * m_cols + col];
    }
References col(), matrix_t< T >::m_cols, matrix_t< T >::m_entries, and row().
operator()() [2/2]
template<typename T = int> T matrix_t< T >::operator() (unsigned int row, unsigned int col) const inline
    {
        return m_entries[(size_t)row * m_cols + col];
    }
References col(), matrix_t< T >::m_cols, matrix_t< T >::m_entries, and row().
operator*() [1/3]
template<typename T = int> matrix_t< T > matrix_t< T >::operator* (const double & s) const inline
    {
        matrix_t<T> result(m_rows, m_cols);
        for (int i = 0; i < m_rows; ++i) {
            for (int j = 0; j < m_cols; ++j) {
                result(i, j) = (*this)(i, j) * s;
            }
        }
        return result;
    }
References matrix_t< T >::m_cols, and matrix_t< T >::m_rows.
operator*() [2/3]
template<typename T = int> matrix_t< T > matrix_t< T >::operator* (const matrix_t< T > & other) const inline
    {
        matrix_t<T> result(this->rows(), other.cols());
        for (int i = 0; i < this->rows(); ++i) {
            for (int j = 0; j < other.cols(); ++j) {
                for (int k = 0; k < this->cols(); ++k) {
                    result(i, j) += (*this)(i, k) * other(k, j);
                }
            }
        }
        return result;
    }
References matrix_t< T >::cols(), and matrix_t< T >::rows().
operator*() [3/3]
template<typename T = int> vec2 matrix_t< T >::operator* (const vec3 & v) const inline
    {
        MCUT_ASSERT(this->cols() == vec3::cardinality());
        vec2 result(double(0.0));
        MCUT_ASSERT(this->rows() == vec2::cardinality());
        for (int col = 0; col < this->cols(); ++col) {
            for (int row = 0; row < vec2::cardinality(); ++row) {
                result[row] = result[row] + ((*this)(row, col) * v[col]);
            }
        }
#if 0
        // columns
        const Vec c0((*this)(0, 0), (*this)(1, 0), (*this)(2, 0));
        const Vec c1((*this)(0, 1), (*this)(1, 1), (*this)(2, 1));
        result = c0 * v[0] + c1 * v[1];
        if (this->rows() == 3 && (this->cols() == 3)
        {
            const Vec c2((*this)(0, 2), (*this)(1, 2), (*this)(2, 2));
            result = result + c2 * v[2];
        }
#endif
        return result;
    }
References vec2_< T >::cardinality(), vec3_< T >::cardinality(), col(), matrix_t< T >::cols(), MCUT_ASSERT, row(), and matrix_t< T >::rows().
operator-()
template<typename T = int> matrix_t< T > matrix_t< T >::operator- (const matrix_t< T > & m) const inline
    {
        MCUT_ASSERT(m.rows() == this->rows());
        MCUT_ASSERT(m.cols() == this->cols());
        matrix_t<T> result(m_rows, m_cols);
        for (int i = 0; i < m_rows; ++i) {
            for (int j = 0; j < m_cols; ++j) {
                result(i, j) = (*this)(i, j) - m(i, j);
            }
        }
        return result;
    }
References matrix_t< T >::cols(), matrix_t< T >::m_cols, matrix_t< T >::m_rows, MCUT_ASSERT, and matrix_t< T >::rows().
operator/()
template<typename T = int> matrix_t< T > matrix_t< T >::operator/ (const double & s) const inline
    {
        matrix_t<T> result(m_rows, m_cols);
        for (int i = 0; i < m_rows; ++i) {
            for (int j = 0; j < m_cols; ++j) {
                result(i, j) = (*this)(i, j) / s;
            }
        }
        return result;
    }
References matrix_t< T >::m_cols, and matrix_t< T >::m_rows.
rows()
template<typename T = int> int matrix_t< T >::rows () const inline
    {
        return m_rows;
    }
References matrix_t< T >::m_rows.
Referenced by matrix_t< T >::operator*(), matrix_t< T >::operator*(), matrix_t< T >::operator-(), and operator<<().
Member Data Documentation
m_cols
template<typename T = int> int matrix_t< T >::m_cols private
Referenced by matrix_t< T >::cols(), matrix_t< T >::operator()(), matrix_t< T >::operator()(), matrix_t< T >::operator*(), matrix_t< T >::operator-(), and matrix_t< T >::operator/().
m_entries
template<typename T = int> std::vector<T> matrix_t< T >::m_entries private
Referenced by matrix_t< T >::operator()(), and matrix_t< T >::operator()().
m_rows
template<typename T = int> int matrix_t< T >::m_rows private
Referenced by matrix_t< T >::operator*(), matrix_t< T >::operator-(), matrix_t< T >::operator/(), and matrix_t< T >::rows().
The documentation for this class was generated from the following file:
src/mcut/include/mcut/internal/math.h