OrcaSlicer: src/mcut/source/mcut.cpp File Reference
mcut.cpp File Reference
#include "mcut/mcut.h"
#include "mcut/internal/frontend.h"
#include "mcut/internal/timer.h"
#include "mcut/internal/utils.h"
#include <exception>
#include <stdexcept>
Functions
MCAPI_ATTR McResult MCAPI_CALL mcCreateContext (McContext *pOutContext, McFlags contextFlags)
Create an MCUT context.
MCAPI_ATTR McResult MCAPI_CALL mcCreateContextWithHelpers (McContext *pOutContext, McFlags contextFlags, uint32_t helperThreadCount)
Create an MCUT context object with N helper threads.
MCAPI_ATTR McResult MCAPI_CALL mcDebugMessageCallback (McContext pContext, pfn_mcDebugOutput_CALLBACK cb, const McVoid *userParam)
Specify a callback to receive debugging messages from the MCUT library.
MCAPI_ATTR McResult MCAPI_CALL mcGetDebugMessageLog (McContext context, McUint32 count, McSize bufSize, McDebugSource *sources, McDebugType *types, McDebugSeverity *severities, McSize *lengths, McChar *messageLog, McUint32 *numFetched)
Returns messages stored in an internal log.
MCAPI_ATTR McResult MCAPI_CALL mcDebugMessageControl (McContext pContext, McDebugSource source, McDebugType type, McDebugSeverity severity, bool enabled)
MCAPI_ATTR McResult MCAPI_CALL mcGetInfo (const McContext context, McFlags info, McSize bytes, McVoid *pMem, McSize *pNumBytes)
Return the value of a selected parameter.
MCAPI_ATTR McResult MCAPI_CALL mcBindState (const McContext context, McFlags stateInfo, McSize bytes, const McVoid *pMem)
Set the value of a selected parameter of a context.
MCAPI_ATTR McResult MCAPI_CALL mcCreateUserEvent (McEvent *event, McContext context)
To create a user event object, call the function.
MCAPI_ATTR McResult MCAPI_CALL mcSetUserEventStatus (McEvent event, McInt32 execution_status)
To set the execution status of a user event object, call the function.
MCAPI_ATTR McResult MCAPI_CALL mcGetEventInfo (const McEvent event, McFlags info, McSize bytes, McVoid *pMem, McSize *pNumBytes)
Returns information about the event object..
MCAPI_ATTR McResult MCAPI_CALL mcWaitForEvents (uint32_t numEventsInWaitlist, const McEvent *pEventWaitList)
Waits on the user thread for commands identified by event objects to complete.
MCAPI_ATTR McResult MCAPI_CALL mcSetEventCallback (McEvent eventHandle, pfn_McEvent_CALLBACK eventCallback, McVoid *data)
Registers a user callback function.
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueDispatch (const McContext context, McFlags dispatchFlags, const McVoid *pSrcMeshVertices, const uint32_t *pSrcMeshFaceIndices, const uint32_t *pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McVoid *pCutMeshVertices, const uint32_t *pCutMeshFaceIndices, const uint32_t *pCutMeshFaceSizes, uint32_t numCutMeshVertices, uint32_t numCutMeshFaces, uint32_t numEventsInWaitlist, const McEvent *pEventWaitList, McEvent *pEvent)
Execute a cutting operation with two meshes - the source mesh, and the cut mesh.
MCAPI_ATTR McResult MCAPI_CALL mcDispatch (const McContext context, McFlags dispatchFlags, const McVoid *pSrcMeshVertices, const uint32_t *pSrcMeshFaceIndices, const uint32_t *pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McVoid *pCutMeshVertices, const uint32_t *pCutMeshFaceIndices, const uint32_t *pCutMeshFaceSizes, uint32_t numCutMeshVertices, uint32_t numCutMeshFaces)
Blocking version of mcEnqueueDispatch.
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueDispatchPlanarSection (const McContext context, McFlags dispatchFlags, const McVoid *pSrcMeshVertices, const uint32_t *pSrcMeshFaceIndices, const uint32_t *pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McDouble *pNormalVector, const McDouble sectionOffset, uint32_t numEventsInWaitlist, const McEvent *pEventWaitList, McEvent *pEvent)
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueGetConnectedComponents (const McContext context, const McConnectedComponentType connectedComponentType, const uint32_t numEntries, McConnectedComponent *pConnComps, uint32_t *numConnComps, uint32_t numEventsInWaitlist, const McEvent *pEventWaitList, McEvent *pEvent)
Query the connected components available in a context.
MCAPI_ATTR McResult MCAPI_CALL mcGetConnectedComponents (const McContext context, const McConnectedComponentType connectedComponentType, const uint32_t numEntries, McConnectedComponent *pConnComps, uint32_t *numConnComps)
Blocking version of mcEnqueueGetConnectedComponents.
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueGetConnectedComponentData (const McContext context, const McConnectedComponent connCompId, McFlags queryFlags, McSize bytes, McVoid *pMem, McSize *pNumBytes, uint32_t numEventsInWaitlist, const McEvent *pEventWaitList, McEvent *pEvent)
Query specific information about a connected component.
MCAPI_ATTR McResult MCAPI_CALL mcGetConnectedComponentData (const McContext context, const McConnectedComponent connCompId, McFlags queryFlags, McSize bytes, McVoid *pMem, McSize *pNumBytes)
Blocking version of mcEnqueueGetConnectedComponents.
MCAPI_ATTR McResult MCAPI_CALL mcReleaseEvents (uint32_t numEvents, const McEvent *pEvents)
Decrements the event reference count.
MCAPI_ATTR McResult MCAPI_CALL mcReleaseConnectedComponents (const McContext context, uint32_t numConnComps, const McConnectedComponent *pConnComps)
To release the memory of a connected component, call this function.
MCAPI_ATTR McResult MCAPI_CALL mcReleaseContext (const McContext context)
To release the memory of a context, call this function.
Function Documentation
mcBindState()
MCAPI_ATTR McResult MCAPI_CALL mcBindState (const McContext context, McFlags stateInfo, McSize bytes, const McVoid * pMem)
Set the value of a selected parameter of a context.
Parameters
[in] context The context handle that was created by a previous call to mcCreateContext.
[in] info Information being set. McQueryFlags
[in] bytes Size in bytes of memory pointed to by pMem.
[out] pMem Pointer to memory from where the appropriate result being copied.
This function effectively sets state variables of a context. All API functions using the respective context shall be effected by this state.
An example of usage:
McDouble epsilon = 1e-4;
McResult err =  mcBindState(context, MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT, sizeof(McDouble), &epsilon);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
stateInfo is not an accepted flag.
bytes is 0
pMem is NULL
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (bytes == 0) {
        per_thread_api_log_str = "invalid bytes ";
    } else if (pMem == nullptr) {
        per_thread_api_log_str = "invalid ptr (pMem)";
    } else if (false == //
        (stateInfo == MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT || //
            stateInfo == MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS ||//
            stateInfo == MC_CONTEXT_CONNECTED_COMPONENT_FACE_WINDING_ORDER)) // check all possible values
    {
        per_thread_api_log_str = "invalid stateInfo ";
    } else if (
        ((stateInfo == MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT) && bytes != sizeof(McDouble)) || //
        ((stateInfo == MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS) && bytes != sizeof(McUint32))|| //
        ((stateInfo == MC_CONTEXT_CONNECTED_COMPONENT_FACE_WINDING_ORDER) && bytes != sizeof(McConnectedComponentFaceWindingOrder))) {
        per_thread_api_log_str = "invalid num bytes"; // leads to e.g. "out of bounds" memory access during memcpy
    } else {
        try {
            bind_state_impl(context, stateInfo, bytes, pMem);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References bind_state_impl(), CATCH_POSSIBLE_EXCEPTIONS, MC_CONTEXT_CONNECTED_COMPONENT_FACE_WINDING_ORDER, MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS, MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT, and per_thread_api_log_str.
mcCreateContext()
MCAPI_ATTR McResult MCAPI_CALL mcCreateContext (McContext * pOutContext, McFlags contextFlags)
Create an MCUT context.
Copyright (c) 2021-2022 Floyd M. Chitalu. All rights reserved.
NOTE: This file is licensed under GPL-3.0-or-later (default). A commercial license can be purchased from Floyd M. Chitalu.
License details:
(A) GNU General Public License ("GPL"); a copy of which you should have recieved with this file.
see also: http://www.gnu.org/licenses/ (B) Commercial license.
email: floyd.nosp@m..m.c.nosp@m.hital.nosp@m.u@gm.nosp@m.ail.c.nosp@m.om
The commercial license options is for users that wish to use MCUT in their products for comercial purposes but do not wish to release their software products under the GPL license.
Author(s) : Floyd M. Chitalu
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (pOutContext == nullptr) {
        per_thread_api_log_str = "context ptr undef (NULL)";
        return_value = McResult::MC_INVALID_VALUE;
    } else {
        try {
            // no helper threads
            // only manager threads (2 managers if context is created with MC_OUT_OF_ORDER_EXEC_MODE_ENABLE, otherwise 1 manager)
            create_context_impl(pOutContext, contextFlags, 0);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (return_value != McResult::MC_NO_ERROR) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, create_context_impl(), and per_thread_api_log_str.
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcCreateContextWithHelpers()
MCAPI_ATTR McResult MCAPI_CALL mcCreateContextWithHelpers (McContext * pOutContext, McFlags contextFlags, uint32_t helperThreadCount)
Create an MCUT context object with N helper threads.
This method creates a context object with an additonal number of threads that assist the internal scheduler with compute workloads. The returned a handle shall be used by a client applications to control the API state and access data.
Unless otherwise stated, MCUT runs asynchronously with the user application. Non-blocking commands issued with a given context run on a conceptual "device", which executes independently of the client application. This device is associated with one logical thread by default. Two logical threads will be associated with the device if MC_OUT_OF_ORDER_EXEC_MODE_ENABLE is provided as a flag.
Having one logical device thread means that MCUT commands shall execute in the order that they are provided by a client application. And if two logical threads are associated with the device then multiple API commands may also run concurrently subject to their dependency list.
Concurrent commands share the pool of N helper threads.
Parameters
[out] pContext a pointer to the allocated context handle
[in] flags bitfield containing the context creation flags
[in] helperThreadCount Number of helper-threads to assist device-threads with parallel work.
An example of usage:
McContext myContext = MC_NULL_HANDLE;
McResult err = mcCreateContextWithHelpers(&myContext, MC_OUT_OF_ORDER_EXEC_MODE_ENABLE, 2);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL
Failure to allocate resources
flags defines an invalid bitfield.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (pOutContext == nullptr) {
        per_thread_api_log_str = "context ptr undef (NULL)";
        return_value = McResult::MC_INVALID_VALUE;
    } else {
        try {
            create_context_impl(pOutContext, contextFlags, helperThreadCount);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (return_value != McResult::MC_NO_ERROR) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, create_context_impl(), and per_thread_api_log_str.
mcCreateUserEvent()
MCAPI_ATTR McResult MCAPI_CALL mcCreateUserEvent (McEvent * event, McContext context)
To create a user event object, call the function.
Parameters
event Event handle
context must be a valid MCUT context.
User events allow applications to enqueue commands that wait on a user event to finish before the command is executed by the MCUT engine
mcCreateUserEvent returns a valid non-zero event object and return code is set to MC_NO_ERROR if the user event object is created successfully. Otherwise, it returns a NULL value with an error values.
Returns
MCAPI_ATTR
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (event == nullptr) {
        per_thread_api_log_str = "event ptr (param0) undef (NULL)";
    } else if (context == nullptr) {
        per_thread_api_log_str = "context handle undefined (NULL)";
    } else {
        try {
            create_user_event_impl(event, context);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, create_user_event_impl(), and per_thread_api_log_str.
mcDebugMessageCallback()
MCAPI_ATTR McResult MCAPI_CALL mcDebugMessageCallback (McContext context, pfn_mcDebugOutput_CALLBACK cb, const McVoid * userParam)
Specify a callback to receive debugging messages from the MCUT library.
mcDebugMessageCallback sets the current debug output callback function to the function whose address is given in callback.
This function is defined to have the same calling convention as the MCUT API functions. In most cases this is defined as MCAPI_ATTR, although it will vary depending on platform, language and compiler.
Each time a debug message is generated the debug callback function will be invoked with source, type, and severity associated with the message, and length set to the length of debug message whose character string is in the array pointed to by message userParam will be set to the value passed in the userParam parameter to the most recent call to mcDebugMessageCallback.
Parameters
[in] context The context handle that was created by a previous call to mcCreateContext.
[in] cb The address of a callback function that will be called when a debug message is generated.
[in] userParam A user supplied pointer that will be passed on each invocation of callback.
An example of usage:
// define my callback (with type pfn_mcDebugOutput_CALLBACK)
void mcDebugOutput(McDebugSource source,   McDebugType type, unsigned int id, McDebugSeverity severity,size_t length, const char* message,const McVoid* userParam)
{
 // do stuff
}
// ...
McVoid* someData = NULL;
McResult err = mcDebugMessageCallback(myContext, mcDebugOutput, someData);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
cb is NULL.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (pContext == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (cb == nullptr) {
        per_thread_api_log_str = "callback function ptr (param1) undef (NULL)";
    } else {
        try {
            debug_message_callback_impl(pContext, cb, userParam);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, debug_message_callback_impl(), and per_thread_api_log_str.
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcDebugMessageControl()
MCAPI_ATTR McResult MCAPI_CALL mcDebugMessageControl (McContext context, McDebugSource source, McDebugType type, McDebugSeverity severity, bool enabled)
Control the reporting of debug messages in a debug context.
Parameters
[in] context The context handle that was created by a previous call to
See also
mcCreateContext.
Parameters
[in] source The source of debug messages to enable or disable.
[in] type The type of debug messages to enable or disable.
[in] severity The severity of debug messages to enable or disable.
[in] enabled A Boolean flag determining whether the selected messages should be enabled or disabled.
mcDebugMessageControl controls the reporting of debug messages generated by a debug context. The parameters source, type and severity form a filter to select messages from the pool of potential messages generated by the MCUT library.
source may be MC_DEBUG_SOURCE_API, MC_DEBUG_SOURCE_KERNEL to select messages generated by usage of the MCUT API, the MCUT kernel or by the input, respectively. It may also take the value MC_DEBUG_SOURCE_ALL. If source is not MC_DEBUG_SOURCE_ALL then only messages whose source matches source will be referenced.
type may be one of MC_DEBUG_TYPE_ERROR, MC_DEBUG_TYPE_DEPRECATED_BEHAVIOR, or MC_DEBUG_TYPE_OTHER to indicate the type of messages describing MCUT errors, attempted use of deprecated features, and other types of messages, respectively. It may also take the value MC_DONT_CARE. If type is not MC_DEBUG_TYPE_ALL then only messages whose type matches type will be referenced.
severity may be one of MC_DEBUG_SEVERITY_LOW, MC_DEBUG_SEVERITY_MEDIUM, or MC_DEBUG_SEVERITY_HIGH to select messages of low, medium or high severity messages or to MC_DEBUG_SEVERITY_NOTIFICATION for notifications. It may also take the value MC_DEBUG_SEVERITY_ALL. If severity is not MC_DEBUG_SEVERITY_ALL then only messages whose severity matches severity will be referenced.
If enabled is true then messages that match the filter formed by source, type and severity are enabled. Otherwise, those messages are disabled.
An example of usage:
// ... typically after setting debug callback with ::mcDebugMessageCallback
McResult err = mcDebugMessageControl(myContext, MC_DEBUG_SOURCE_ALL, MC_DEBUG_TYPE_ALL, MC_DEBUG_SEVERITY_ALL, true);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
source is not a value define in McDebugSource.
type is not a value define in McDebugType.
severity is not a value define in McDebugSeverity.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (pContext == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (
        false == (source == McDebugSource::MC_DEBUG_SOURCE_ALL || //
            source == McDebugSource::MC_DEBUG_SOURCE_KERNEL || //
            source == McDebugSource::MC_DEBUG_SOURCE_ALL)) {
        per_thread_api_log_str = "debug source val (param1) invalid";
    } else if (
        false == (type == McDebugType::MC_DEBUG_TYPE_ALL || //
            type == McDebugType::MC_DEBUG_TYPE_DEPRECATED_BEHAVIOR || //
            type == McDebugType::MC_DEBUG_TYPE_ERROR || //
            type == McDebugType::MC_DEBUG_TYPE_OTHER)) {
        per_thread_api_log_str = "debug type val (param2) invalid";
    } else if (
        false == (severity == McDebugSeverity::MC_DEBUG_SEVERITY_HIGH || //
            severity == McDebugSeverity::MC_DEBUG_SEVERITY_MEDIUM || //
            severity == McDebugSeverity::MC_DEBUG_SEVERITY_LOW || //
            severity == McDebugSeverity::MC_DEBUG_SEVERITY_NOTIFICATION || //
            severity == McDebugSeverity::MC_DEBUG_SEVERITY_ALL)) {
        per_thread_api_log_str = "debug severity val (param3) invalid";
    } else {
        try {
            debug_message_control_impl(pContext, source, type, severity, enabled);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, debug_message_control_impl(), and per_thread_api_log_str.
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcDispatch()
MCAPI_ATTR McResult MCAPI_CALL mcDispatch (const McContext context, McFlags dispatchFlags, const McVoid * pSrcMeshVertices, const uint32_t * pSrcMeshFaceIndices, const uint32_t * pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McVoid * pCutMeshVertices, const uint32_t * pCutMeshFaceIndices, const uint32_t * pCutMeshFaceSizes, uint32_t numCutMeshVertices, uint32_t numCutMeshFaces)
Blocking version of mcEnqueueDispatch.
{
    McEvent event = MC_NULL_HANDLE;
    McResult return_value = mcEnqueueDispatch(
        context,
        dispatchFlags,
        pSrcMeshVertices,
        pSrcMeshFaceIndices,
        pSrcMeshFaceSizes,
        numSrcMeshVertices,
        numSrcMeshFaces,
        pCutMeshVertices,
        pCutMeshFaceIndices,
        pCutMeshFaceSizes,
        numCutMeshVertices,
        numCutMeshFaces,
        0,
        nullptr,
        &event);
    if (return_value == MC_NO_ERROR) { // API parameter checks are fine
        if (event != MC_NULL_HANDLE) // event must exist to wait on and query
        {
            McResult waitliststatus = MC_NO_ERROR;
            wait_for_events_impl(1, &event, waitliststatus); // block until event of mcEnqueueDispatch is completed!
            if (waitliststatus != McResult::MC_NO_ERROR) {
                return_value = waitliststatus;
            }
            release_events_impl(1, &event); // destroy
        }
    }
    return return_value;
}
References MC_NO_ERROR, MC_NULL_HANDLE, mcEnqueueDispatch(), release_events_impl(), and wait_for_events_impl().
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcEnqueueDispatch()
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueDispatch (const McContext context, McFlags dispatchFlags, const McVoid * pSrcMeshVertices, const uint32_t * pSrcMeshFaceIndices, const uint32_t * pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McVoid * pCutMeshVertices, const uint32_t * pCutMeshFaceIndices, const uint32_t * pCutMeshFaceSizes, uint32_t numCutMeshVertices, uint32_t numCutMeshFaces, uint32_t numEventsInWaitlist, const McEvent * pEventWaitList, McEvent * pEvent)
Execute a cutting operation with two meshes - the source mesh, and the cut mesh.
Parameters
[in] context The context handle that was created by a previous call to mcCreateContext.
[in] flags The flags indicating how to interprete input data and configure the execution.
[in] pSrcMeshVertices The array of vertex coordinates (i.e. in xyzxyzxyz... format) of the source mesh.
[in] pSrcMeshFaceIndices The array of vertex indices of the faces (polygons) in the source mesh.
[in] pSrcMeshFaceSizes The array of the sizes (in terms of number of vertex indices) of the faces in the source mesh.
[in] numSrcMeshVertices The number of vertices in the source mesh.
[in] numSrcMeshFaces The number of faces in the source mesh.
[in] pCutMeshVertices The array of vertex coordinates (i.e. in xyzxyzxyz... format) of the cut mesh.
[in] pCutMeshFaceIndices The array of vertex indices of the faces (polygons) in the cut mesh.
[in] pCutMeshFaceSizes The array of the sizes (in terms of number of vertex indices) of the faces in the cut mesh.
[in] numCutMeshVertices The number of vertices in the cut mesh.
[in] numCutMeshFaces The number of faces in the cut mesh.
[in] numEventsInWaitlist Number of events in the waitlist.
[in] pEventWaitList Events that need to complete before this particular command can be executed.
[out] pEvent Returns an event object that identifies this particular command and can be used to query or queue a wait for this particular command to complete. pEvent can be NULL in which case it will not be possible for the application to query the status of this command or queue a wait for this command to complete. If the pEventWaitList and the event arguments are not NULL, the pEvent argument should not refer to an element of the pEventWaitList array.
This function specifies the two mesh objects to operate on. The 'source mesh' is the mesh to be cut (i.e. partitioned) along intersection paths prescribed by the 'cut mesh'.
If pEventWaitList is NULL, then this particular command does not wait on any event to complete. If pEventWaitList is NULL, numEventsInWaitlist must be 0. If pEventWaitList is not NULL, the list of events pointed to by pEventWaitList must be valid and numEventsInWaitlist must be greater than 0. The events specified in pEventWaitList act as synchronization points. The memory associated with pEventWaitList can be reused or freed after the function returns.
An example of usage:
 McEvent event;
 //...
 McResult err = mcEnqueueDispatch(..., 0, NULL, &event);
if(err != MC_NO_ERROR)
{
 // deal with error...
}
err = mcWaitForEvents(1, &event);
if(err != MC_NO_ERROR)
{
 // deal with error...
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
flags contains an invalid value.
A vertex index in pSrcMeshFaceIndices or pCutMeshFaceIndices is out of bounds.
Invalid face/polygon definition (vertex list) implying non-manifold mesh pSrcMeshFaceIndices or pCutMeshFaceIndices is out of bounds.
The MC_DISPATCH_VERTEX_ARRAY_... value has not been specified in flags
An input mesh contains multiple connected components.
pSrcMeshVertices is NULL.
pSrcMeshFaceIndices is NULL.
pSrcMeshFaceSizes is NULL.
numSrcMeshVertices is less than three.
numSrcMeshFaces is less than one.
pCutMeshVertices is NULL.
pCutMeshFaceIndices is NULL.
pCutMeshFaceSizes is NULL.
numCutMeshVertices is less than three.
numCutMeshFaces is less than one.
numEventsInWaitlist Number of events in the waitlist.
pEventWaitList events that need to complete before this particular command can be executed
MC_DISPATCH_ENFORCE_GENERAL_POSITION or MC_DISPATCH_ENFORCE_GENERAL_POSITION_ABSOLUTE is not set and: 1) Found two intersecting edges between the source-mesh and the cut-mesh and/or 2) An intersection test between a face and an edge failed because an edge vertex only touches (but does not penetrate) the face, and/or 3) One or more source-mesh vertices are colocated with one or more cut-mesh vertices.
MC_OUT_OF_MEMORY
Insufficient memory to perform operation.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (dispatchFlags == 0) {
        per_thread_api_log_str = "dispatch flags unspecified";
    } else if ((dispatchFlags & MC_DISPATCH_REQUIRE_THROUGH_CUTS) && //
        (dispatchFlags & MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED)) {
        // The user states that she does not want a partial cut but yet also states that she
        // wants to keep fragments with partial cuts. These two options are mutually exclusive!
        per_thread_api_log_str = "use of mutually-exclusive flags: MC_DISPATCH_REQUIRE_THROUGH_CUTS & MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED";
    } else if ((dispatchFlags & MC_DISPATCH_VERTEX_ARRAY_FLOAT) == 0 && (dispatchFlags & MC_DISPATCH_VERTEX_ARRAY_DOUBLE) == 0) {
        per_thread_api_log_str = "dispatch vertex aray type unspecified";
    } else if (pSrcMeshVertices == nullptr) {
        per_thread_api_log_str = "source-mesh vertex-position array ptr undef (NULL)";
    } else if (numSrcMeshVertices < 3) {
        per_thread_api_log_str = "invalid source-mesh vertex count";
    } else if (pSrcMeshFaceIndices == nullptr) {
        per_thread_api_log_str = "source-mesh face-index array ptr undef (NULL)";
    } /*else if (pSrcMeshFaceSizes == nullptr) {
        per_thread_api_log_str = "source-mesh face-size array ptr undef (NULL)";
    }*/
    else if (numSrcMeshFaces < 1) {
        per_thread_api_log_str = "invalid source-mesh vertex count";
    } else if (pCutMeshVertices == nullptr) {
        per_thread_api_log_str = "cut-mesh vertex-position array ptr undef (NULL)";
    } else if (numCutMeshVertices < 3) {
        per_thread_api_log_str = "invalid cut-mesh vertex count";
    } else if (pCutMeshFaceIndices == nullptr) {
        per_thread_api_log_str = "cut-mesh face-index array ptr undef (NULL)";
    } /*else if (pCutMeshFaceSizes == nullptr) {
        per_thread_api_log_str = "cut-mesh face-size array ptr undef (NULL)";
    } */
    else if (numCutMeshFaces < 1) {
        per_thread_api_log_str = "invalid cut-mesh vertex count";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist > 0) {
        per_thread_api_log_str = "invalid event waitlist ptr (NULL)";
    } else if (pEventWaitList != nullptr && numEventsInWaitlist == 0) {
        per_thread_api_log_str = "invalid event waitlist size (zero)";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist == 0 && pEvent == nullptr) {
        per_thread_api_log_str = "invalid event ptr (zero)";
    } else {
        try {
            dispatch_impl(
                context,
                dispatchFlags,
                pSrcMeshVertices,
                pSrcMeshFaceIndices,
                pSrcMeshFaceSizes,
                numSrcMeshVertices,
                numSrcMeshFaces,
                pCutMeshVertices,
                pCutMeshFaceIndices,
                pCutMeshFaceSizes,
                numCutMeshVertices,
                numCutMeshFaces,
                numEventsInWaitlist,
                pEventWaitList,
                pEvent);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, dispatch_impl(), MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED, MC_DISPATCH_REQUIRE_THROUGH_CUTS, MC_DISPATCH_VERTEX_ARRAY_DOUBLE, MC_DISPATCH_VERTEX_ARRAY_FLOAT, and per_thread_api_log_str.
Referenced by mcDispatch().
mcEnqueueDispatchPlanarSection()
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueDispatchPlanarSection (const McContext context, McFlags dispatchFlags, const McVoid * pSrcMeshVertices, const uint32_t * pSrcMeshFaceIndices, const uint32_t * pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McDouble * pNormalVector, const McDouble sectionOffset, uint32_t numEventsInWaitlist, const McEvent * pEventWaitList, McEvent * pEvent)
    {
        McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (dispatchFlags == 0) {
        per_thread_api_log_str = "dispatch flags unspecified";
    } else if ((dispatchFlags & MC_DISPATCH_REQUIRE_THROUGH_CUTS) && //
        (dispatchFlags & MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED)) {
        // The user states that she does not want a partial cut but yet also states that she
        // wants to keep fragments with partial cuts. These two options are mutually exclusive!
        per_thread_api_log_str = "use of mutually-exclusive flags: MC_DISPATCH_REQUIRE_THROUGH_CUTS & MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED";
    } else if ((dispatchFlags & MC_DISPATCH_VERTEX_ARRAY_FLOAT) == 0 && (dispatchFlags & MC_DISPATCH_VERTEX_ARRAY_DOUBLE) == 0) {
        per_thread_api_log_str = "dispatch vertex aray type unspecified";
    } else if (pSrcMeshVertices == nullptr) {
        per_thread_api_log_str = "source-mesh vertex-position array ptr undef (NULL)";
    } else if (numSrcMeshVertices < 3) {
        per_thread_api_log_str = "invalid source-mesh vertex count";
    } else if (pSrcMeshFaceIndices == nullptr) {
        per_thread_api_log_str = "source-mesh face-index array ptr undef (NULL)";
    } /*else if (pSrcMeshFaceSizes == nullptr) {
        per_thread_api_log_str = "source-mesh face-size array ptr undef (NULL)";
    }*/
    else if (numSrcMeshFaces < 1) {
        per_thread_api_log_str = "invalid source-mesh vertex count";
    } else if (pNormalVector == nullptr) {
        per_thread_api_log_str = "normal vector ptr undef (NULL)";
    } else if (pNormalVector[0] == 0.0 && pNormalVector[1] == 0.0 && pNormalVector[2] == 0.0) {
        per_thread_api_log_str = "invalid normal vector (zero vector)";
    }else if (sectionOffset <= 0 && sectionOffset >= 1.0) {
        per_thread_api_log_str = "invalid section offset parameter";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist > 0) {
        per_thread_api_log_str = "invalid event waitlist ptr (NULL)";
    } else if (pEventWaitList != nullptr && numEventsInWaitlist == 0) {
        per_thread_api_log_str = "invalid event waitlist size (zero)";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist == 0 && pEvent == nullptr) {
        per_thread_api_log_str = "invalid event ptr (zero)";
    } else {
        try {
            dispatch_planar_section_impl(
                context,
                dispatchFlags,
                pSrcMeshVertices,
                pSrcMeshFaceIndices,
                pSrcMeshFaceSizes,
                numSrcMeshVertices,
                numSrcMeshFaces,
                pNormalVector,
                sectionOffset,
                numEventsInWaitlist,
                pEventWaitList,
                pEvent);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
    }
References CATCH_POSSIBLE_EXCEPTIONS, dispatch_planar_section_impl(), MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED, MC_DISPATCH_REQUIRE_THROUGH_CUTS, MC_DISPATCH_VERTEX_ARRAY_DOUBLE, MC_DISPATCH_VERTEX_ARRAY_FLOAT, and per_thread_api_log_str.
mcEnqueueGetConnectedComponentData()
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueGetConnectedComponentData (const McContext context, const McConnectedComponent connCompId, McFlags queryFlags, McSize bytes, McVoid * pMem, McSize * pNumBytes, uint32_t numEventsInWaitlist, const McEvent * pEventWaitList, McEvent * pEvent)
Query specific information about a connected component.
Parameters
[in] context The context handle that was created by a previous call to mcCreateContext.
[in] connCompId A connected component returned by mcGetConnectedComponents whose data is to be read.
[in] flags An enumeration constant that identifies the connected component information being queried.
[in] bytes Specifies the size in bytes of memory pointed to by flags.
[out] pMem A pointer to memory location where appropriate values for a given flags will be returned. If pMem is NULL, it is ignored.
[out] pNumBytes Returns the actual size in bytes of data being queried by flags. If pNumBytes is NULL, it is ignored.
The connected component queries described in the McConnectedComponentData should return the same information for a connected component returned by mcGetConnectedComponents. If pEventWaitList is NULL, then this particular command does not wait on any event to complete. If pEventWaitList is NULL, numEventsInWaitlist must be 0. If pEventWaitList is not NULL, the list of events pointed to by pEventWaitList must be valid and numEventsInWaitlist must be greater than 0. The events specified in pEventWaitList act as synchronization points. The memory associated with pEventWaitList can be reused or freed after the function returns.
An example of usage:
McSize numBytes = 0;
McEvent bytesQueryEvent=MC_NULL_HANDLE;
McEvent ev = MC_NULL_HANDLE;
McResult err = mcEnqueueGetConnectedComponentData(myContext,  connCompHandle, MC_CONNECTED_COMPONENT_DATA_VERTEX_DOUBLE, 0, NULL, &numBytes, 0, NULL, &bytesQueryEvent, 0, NULL, &ev);
if(err != MC_NO_ERROR)
{
 // deal with error
}
double* pVertices = (double*)malloc(numBytes);
// this operation shall happen AFTER the preceding operation associated with "bytesQueryEvent".
err = mcEnqueueGetConnectedComponentData(context, connCompHandle, MC_CONNECTED_COMPONENT_DATA_VERTEX_DOUBLE, numBytes, (McVoid*)pVertices, NULL, 1, &bytesQueryEvent, NULL, 1, &ev, NULL);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
connectedComponentType is not a value in McConnectedComponentType.
pMem and pNumBytes are both NULL (or not NULL).
bytes is zero and pMem is not NULL.
flag is MC_CONNECTED_COMPONENT_DATA_VERTEX_MAP when context dispatch flags did not include flag MC_DISPATCH_INCLUDE_VERTEX_MAP
flag is MC_CONNECTED_COMPONENT_DATA_FACE_MAP when context dispatch flags did not include flag MC_DISPATCH_INCLUDE_FACE_MAP
numEventsInWaitlist Number of events in the waitlist.
pEventWaitList events that need to complete before this particular command can be executed
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    }
    if (connCompId == nullptr) {
        per_thread_api_log_str = "connected component ptr (param1) undef (NULL)";
    } else if (queryFlags == 0) {
        per_thread_api_log_str = "flags (param1) undef (0)";
    } else if (bytes != 0 && pMem == nullptr) {
        per_thread_api_log_str = "null parameter (param3 & param4)";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist > 0) {
        per_thread_api_log_str = "invalid event waitlist ptr (NULL)";
    } else if (pEventWaitList != nullptr && numEventsInWaitlist == 0) {
        per_thread_api_log_str = "invalid event waitlist size (zero)";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist == 0 && pEvent == nullptr) {
        per_thread_api_log_str = "invalid event ptr (zero)";
    } else {
        try {
            get_connected_component_data_impl(context, connCompId, queryFlags, bytes, pMem, pNumBytes, numEventsInWaitlist, pEventWaitList, pEvent);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, get_connected_component_data_impl(), and per_thread_api_log_str.
Referenced by mcGetConnectedComponentData().
mcEnqueueGetConnectedComponents()
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueGetConnectedComponents (const McContext context, const McConnectedComponentType connectedComponentType, const uint32_t numEntries, McConnectedComponent * pConnComps, uint32_t * numConnComps, uint32_t numEventsInWaitlist, const McEvent * pEventWaitList, McEvent * pEvent)
Query the connected components available in a context.
This function will return an array of connected components matching the given description of flags.
Parameters
[in] context The context handle
[in] connectedComponentType The type(s) of connected component sought. See also McConnectedComponentType.
[in] numEntries The number of McConnectedComponent entries that can be added to pConnComps. If pConnComps is not NULL, numEntries must be the number of elements in pConnComps.
[out] pConnComps Returns a list of connected components found. The McConnectedComponentType values returned in pConnComps can be used to identify a specific connected component. If pConnComps is NULL, this argument is ignored. The number of connected components returned is the minimum of the value specified by numEntries or the number of connected components whose type matches connectedComponentType.
[out] numConnComps Returns the number of connected components available that match connectedComponentType. If numConnComps is NULL, this argument is ignored.
[in] numEventsInWaitlist Number of events in the waitlist.
[in] pEventWaitList Events that need to complete before this particular command can be executed.
[out] pEvent Returns an event object that identifies this particular command and can be used to query or queue a wait for this particular command to complete. pEvent can be NULL in which case it will not be possible for the application to query the status of this command or queue a wait for this command to complete. If the pEventWaitList and the event arguments are not NULL, the pEvent argument should not refer to an element of the pEventWaitList array.
If pEventWaitList is NULL, then this particular command does not wait on any event to complete. If pEventWaitList is NULL, numEventsInWaitlist must be 0. If pEventWaitList is not NULL, the list of events pointed to by pEventWaitList must be valid and numEventsInWaitlist must be greater than 0. The events specified in pEventWaitList act as synchronization points. The memory associated with pEventWaitList can be reused or freed after the function returns.
An example of usage:
uint32_t numConnComps = 0;
McConnectedComponent* pConnComps;
McEvent ev = MC_NULL_HANDLE;
McResult err =  err = mcGetConnectedComponents(myContext, MC_CONNECTED_COMPONENT_TYPE_ALL, 0, NULL, &numConnComps, 0, NULL, &ev);
if(err != MC_NO_ERROR)
{
 // deal with error
}
if (numConnComps == 0) {
   // ...
}
pConnComps = (McConnectedComponent*)malloc(sizeof(McConnectedComponent) * numConnComps);
err = mcGetConnectedComponents(myContext, MC_CONNECTED_COMPONENT_TYPE_ALL, numConnComps, pConnComps, NULL, 1, &ev, NULL);
if(err != MC_NO_ERROR)
{
 // deal with error
}
...
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
connectedComponentType is not a value in McConnectedComponentType.
numConnComps and pConnComps are both NULL.
numConnComps is zero and pConnComps is not NULL.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (connectedComponentType == 0) {
        per_thread_api_log_str = "invalid type-parameter (param1) (0)";
    } else if (numConnComps == nullptr && pConnComps == nullptr) {
        per_thread_api_log_str = "output parameters undef (param3 & param4)";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist > 0) {
        per_thread_api_log_str = "invalid event waitlist ptr (NULL)";
    } else if (pEventWaitList != nullptr && numEventsInWaitlist == 0) {
        per_thread_api_log_str = "invalid event waitlist size (zero)";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist == 0 && pEvent == nullptr) {
        per_thread_api_log_str = "invalid event ptr (zero)";
    } else {
        try {
            get_connected_components_impl(context, connectedComponentType, numEntries, pConnComps, numConnComps, numEventsInWaitlist, pEventWaitList, pEvent);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, get_connected_components_impl(), and per_thread_api_log_str.
Referenced by mcGetConnectedComponents().
mcGetConnectedComponentData()
MCAPI_ATTR McResult MCAPI_CALL mcGetConnectedComponentData (const McContext context, const McConnectedComponent connCompId, McFlags queryFlags, McSize bytes, McVoid * pMem, McSize * pNumBytes)
Blocking version of mcEnqueueGetConnectedComponents.
{
    McEvent event = MC_NULL_HANDLE;
    McResult return_value = mcEnqueueGetConnectedComponentData(context, connCompId, queryFlags, bytes, pMem, pNumBytes, 0, nullptr, &event);
    if (event != MC_NULL_HANDLE) // event must exist to wait on and query
    {
        McResult waitliststatus = MC_NO_ERROR;
        wait_for_events_impl(1, &event, waitliststatus); // block until event of mcEnqueueDispatch is completed!
        if (waitliststatus != McResult::MC_NO_ERROR) {
            return_value = waitliststatus;
        }
        release_events_impl(1, &event); // destroy
    }
    return return_value;
}
References MC_NO_ERROR, MC_NULL_HANDLE, mcEnqueueGetConnectedComponentData(), release_events_impl(), and wait_for_events_impl().
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcGetConnectedComponents()
MCAPI_ATTR McResult MCAPI_CALL mcGetConnectedComponents (const McContext context, const McConnectedComponentType connectedComponentType, const uint32_t numEntries, McConnectedComponent * pConnComps, uint32_t * numConnComps)
Blocking version of mcEnqueueGetConnectedComponents.
{
    McEvent event = MC_NULL_HANDLE;
    McResult return_value = mcEnqueueGetConnectedComponents(context, connectedComponentType, numEntries, pConnComps, numConnComps, 0, nullptr, &event);
    if (event != MC_NULL_HANDLE) // event must exist to wait on and query
    {
        McResult waitliststatus = MC_NO_ERROR;
        wait_for_events_impl(1, &event, waitliststatus); // block until event of mcEnqueueDispatch is completed!
        if (waitliststatus != McResult::MC_NO_ERROR) {
            return_value = waitliststatus;
        }
        release_events_impl(1, &event); // destroy
    }
    return return_value;
}
References MC_NO_ERROR, MC_NULL_HANDLE, mcEnqueueGetConnectedComponents(), release_events_impl(), and wait_for_events_impl().
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcGetDebugMessageLog()
MCAPI_ATTR McResult MCAPI_CALL mcGetDebugMessageLog (McContext context, McUint32 count, McSize bufSize, McDebugSource * sources, McDebugType * types, McDebugSeverity * severities, McSize * lengths, McChar * messageLog, McUint32 * numFetched)
Returns messages stored in an internal log.
Parameters
context The context handle that was created by a previous call to
See also
mcCreateContext.
Parameters
count The number of debug messages to retrieve from the log.
bufSize The size of the buffer whose address is given by messageLog.
sources The address of an array of variables to receive the sources of the retrieved messages.
types The address of an array of variables to receive the types of the retrieved messages.
severities The address of an array of variables to receive the severites of the retrieved messages.
lengths The address of an array of variables to receive the lengths of the received messages.
messageLog The address of an array of variables to receive the lengths of the received messages..
mcGetDebugMessageLog retrieves messages from the debug message log. A maximum of count messages are retrieved from the log. If sources is not NULL then the source of each message is written into up to count elements of the array. If types is not NULL then the type of each message is written into up to count elements of the array. If severities is not NULL then the severity of each message is written into up to count elements of the array. If lengths is not NULL then the length of each message is written into up to count elements of the array.
messageLog specifies the address of a character array into which the debug messages will be written. Each message will be concatenated onto the array starting at the first element of messageLog. bufSize specifies the size of the array messageLog. If a message will not fit into the remaining space in messageLog then the function terminates and returns the number of messages written so far, which may be zero.
If mcGetDebugMessageLog returns zero then no messages are present in the debug log, or there was not enough space in messageLog to retrieve the first message in the queue. If messageLog is NULL then no messages are written and the value of bufSize is ignored..
Here is an example of code that can get the first N messages:
 {.c++}
McResult GetFirstNMessages(McContext context, McUint32 numMsgs)
{
     McSize maxMsgLen = 0;
     mcGetInfo(MC_CONTEXT_MAX_DEBUG_MESSAGE_LENGTH, &maxMsgLen);
      std::vector<McChar> msgData(numMsgs * maxMsgLen);
     std::vector<McDebugSource> sources(numMsgs);
     std::vector<McDebugType> types(numMsgs);
     std::vector<McDebugSeverity> severities(numMsgs);
     std::vector<McSize> lengths(numMsgs);
     McUint32 numFound;
     McResult err = mcGetDebugMessageLog(context, numMsgs, numMsgs, &sources[0], &types[0], &severities[0], &lengths[0], &msgData[0], &numFound);
     if(err != MC_NO_ERROR)
     {
         // deal with error ...
     }
     sources.resize(numFound);
     types.resize(numFound);
     severities.resize(numFound);
     ids.resize(numFound);
     lengths.resize(numFound);
     std::vector<std::string> messages;
     messages.reserve(numFound);
     std::vector<McChar>::iterator currPos = msgData.begin();
     for(size_t msg = 0; msg < lengths.size(); ++msg)
     {
         messages.push_back(std::string(currPos, currPos + lengths[msg] - 1));
         currPos = currPos + lengths[msg];
     }
 }
Returns
error code
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (
        count == 0) {
        per_thread_api_log_str = "count must be > 0";
    } else if (bufSize == 0) {
        per_thread_api_log_str = "bufSize must be > 0";
    } else if (numFetched == nullptr) {
        per_thread_api_log_str = "numFetched  undef (NULL)";
    } else {
        try {
            get_debug_message_log_impl(context,
                count, bufSize,
                sources, types, severities,
                lengths, messageLog, *numFetched);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, count, get_debug_message_log_impl(), and per_thread_api_log_str.
mcGetEventInfo()
MCAPI_ATTR McResult MCAPI_CALL mcGetEventInfo (const McEvent event, McFlags info, McSize bytes, McVoid * pMem, McSize * pNumBytes)
Returns information about the event object..
Parameters
[in] event Specifies the event object being queried..
[in] info Specifies the information to query. See::
[in] bytes Specifies the size in bytes of memory pointed to by pMem. This size must be >= size of the return type as described in the table below..
[in] pMem A pointer to memory where the appropriate result being queried is returned. If param_value is NULL, it is ignored.
[in] pNumBytes Returns the actual size in bytes of data copied to pMem. If pNumBytes is NULL, it is ignored.
Using mcGetEventInfo to determine if a operation identified by event has finished execution (i.e. MC_EVENT_COMMAND_EXECUTION_STATUS returns MC_COMPLETE) is not a synchronization point. There are no guarantees that the memory objects being modified by the operation associated with event will be visible to other enqueued commands.
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
event is not a valid object
bytes is greater than zero but pMem is null.
bytes is zero but pMem is not null.
bytes is zero pMem is null and pNumBytes is null.
bytes is incompatible with info.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (event == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (bytes != 0 && pMem == nullptr) {
        per_thread_api_log_str = "invalid specification (param2 & param3)";
    } else if ((info == MC_EVENT_RUNTIME_EXECUTION_STATUS) && (pMem != nullptr && bytes != sizeof(McResult))) {
        per_thread_api_log_str = "invalid byte size (param2)"; // leads to e.g. "out of bounds" memory access during memcpy
    } else if ((info == MC_EVENT_COMMAND_EXECUTION_STATUS) && (pMem != nullptr && bytes != sizeof(McFlags))) {
        per_thread_api_log_str = "invalid byte size (param2)"; // leads to e.g. "out of bounds" memory access during memcpy
    } else if ((info == MC_EVENT_TIMESTAMP_SUBMIT || info == MC_EVENT_TIMESTAMP_START || info == MC_EVENT_TIMESTAMP_END) && (pMem != nullptr && bytes != sizeof(McSize))) {
        per_thread_api_log_str = "invalid byte size (param2)"; // leads to e.g. "out of bounds" memory access during memcpy
    } else {
        try {
            get_event_info_impl(event, info, bytes, pMem, pNumBytes);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, get_event_info_impl(), MC_EVENT_COMMAND_EXECUTION_STATUS, MC_EVENT_RUNTIME_EXECUTION_STATUS, MC_EVENT_TIMESTAMP_END, MC_EVENT_TIMESTAMP_START, MC_EVENT_TIMESTAMP_SUBMIT, and per_thread_api_log_str.
mcGetInfo()
MCAPI_ATTR McResult MCAPI_CALL mcGetInfo (const McContext context, McFlags info, McSize bytes, McVoid * pMem, McSize * pNumBytes)
Return the value of a selected parameter.
Parameters
[in] context The context handle that was created by a previous call to mcCreateContext.
[in] info Information object being queried. McQueryFlags
[in] bytes Size in bytes of memory pointed to by pMem. This size must be great than or equal to the return type size of data type queried.
[out] pMem Pointer to memory where the appropriate result being queried is returned. If pMem is NULL, it is ignored.
[out] pNumBytes returns the actual size in bytes of data being queried by info. If pNumBytes is NULL, it is ignored.
An example of usage:
McSize numBytes = 0;
McFlags contextFlags;
McResult err =  mcGetInfo(context, MC_CONTEXT_FLAGS, 0, nullptr, &numBytes);
if(err != MC_NO_ERROR)
{
 // deal with error
}
  err = mcGetInfo(context, MC_CONTEXT_FLAGS, numBytes, &contextFlags, nullptr);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
bytes is greater than the returned size of data type queried
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (bytes != 0 && pMem == nullptr) {
        per_thread_api_log_str = "invalid specification (param2 & param3)";
    } else if (false == //
        (info == MC_CONTEXT_FLAGS || //
            info == MC_CONTEXT_MAX_DEBUG_MESSAGE_LENGTH || //
            info == MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT || //
            info == MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS)) // check all possible values
    {
        per_thread_api_log_str = "invalid info flag val (param1)";
    } else if ((info == MC_CONTEXT_FLAGS) && (pMem != nullptr && bytes != sizeof(McFlags))) {
        per_thread_api_log_str = "invalid byte size (param2)"; // leads to e.g. "out of bounds" memory access during memcpy
    } else {
        try {
            get_info_impl(context, info, bytes, pMem, pNumBytes);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, get_info_impl(), MC_CONTEXT_FLAGS, MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS, MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT, MC_CONTEXT_MAX_DEBUG_MESSAGE_LENGTH, and per_thread_api_log_str.
mcReleaseConnectedComponents()
MCAPI_ATTR McResult MCAPI_CALL mcReleaseConnectedComponents (const McContext context, uint32_t numConnComps, const McConnectedComponent * pConnComps)
To release the memory of a connected component, call this function.
If numConnComps is zero and pConnComps is NULL, the memory of all connected components associated with the context is freed.
Parameters
[in] context The context handle that was created by a previous call to mcCreateContext.
[in] numConnComps Number of connected components in pConnComps whose memory to release.
[in] pConnComps The connected components whose memory will be released.
An example of usage:
McResult err = mcReleaseConnectedComponents(myContext, pConnComps, numConnComps);
// OR (delete all connected components in context)
//McResult err = mcReleaseConnectedComponents(myContext, NULL, 0);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
numConnComps is zero and pConnComps is not NULL (and vice versa).
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (numConnComps > 0 && pConnComps == NULL) {
        per_thread_api_log_str = "invalid pointer to connected components";
    } else if (numConnComps == 0 && pConnComps != NULL) {
        per_thread_api_log_str = "number of connected components not set";
    } else {
        try {
            release_connected_components_impl(context, numConnComps, pConnComps);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, NULL, per_thread_api_log_str, and release_connected_components_impl().
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcReleaseContext()
MCAPI_ATTR McResult MCAPI_CALL mcReleaseContext (McContext context)
To release the memory of a context, call this function.
This function ensures that all the state attached to context (such as unreleased connected components, and threads) are released, and the memory is deleted.
Parameters
[in] context The context handle that was created by a previous call to mcCreateContext.
An example of usage:
McResult err = mcReleaseContext(myContext);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else {
        try {
            release_context_impl(context);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, per_thread_api_log_str, and release_context_impl().
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcReleaseEvents()
MCAPI_ATTR McResult MCAPI_CALL mcReleaseEvents (uint32_t numEvents, const McEvent * pEvents)
Decrements the event reference count.
Parameters
numEvents Number of event objects to release
pEvents Array of event objects to release
The event object is deleted once the reference count becomes zero, the specific command identified by this event has completed (or terminated) and there are no commands in the internal-queue of a context that require a wait for this event to complete.
Returns
Error code.
proper exit
MC_INVALID_VALUE
numEvents is greater than 0 and pEvents is NULL (and vice versa).
If an event object in pEvents is not a valid event object.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (numEvents > 0 && pEvents == NULL) {
        per_thread_api_log_str = "invalid pointer to events";
    } else if (numEvents == 0 && pEvents != NULL) {
        per_thread_api_log_str = "number of events not set";
    } else {
        try {
            release_events_impl(numEvents, pEvents);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, NULL, per_thread_api_log_str, and release_events_impl().
mcSetEventCallback()
MCAPI_ATTR McResult MCAPI_CALL mcSetEventCallback (McEvent event, pfn_McEvent_CALLBACK pfn_notify, McVoid * user_data)
Registers a user callback function.
Parameters
[in] event A valid event object returned by the MCUT API.
[in] pfn_notify The event callback function that can be registered by the application..
[in] user_data Will be passed as the user_data argument when pfn_notify is called. user_data can be NULL.
The registered callback function will be called when the execution of the command associated with event is complete. Each call to clSetEventCallback registers the specified user callback function and replaces any previously specified callback. An enqueued callback shall be called before the event object is destroyed. The callback must return promptly. The behavior of calling expensive system routines, or calling blocking MCUT operations etc. in a callback is undefined. It is the application's responsibility to ensure that the callback function is thread-safe.
An example of usage:
McResult err = mcSetEventCallback(ev, someFunctionPointer, NULL);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
event is not a valid object
eventCallback is NULL
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (eventHandle == nullptr) {
        per_thread_api_log_str = "invalid event ptr (NULL)";
    }
    if (eventCallback == nullptr) {
        per_thread_api_log_str = "invalid event callback function ptr (NULL)";
    } else {
        try {
            set_event_callback_impl(eventHandle, eventCallback, data);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, per_thread_api_log_str, and set_event_callback_impl().
mcSetUserEventStatus()
MCAPI_ATTR McResult MCAPI_CALL mcSetUserEventStatus (McEvent event, McInt32 execution_status)
To set the execution status of a user event object, call the function.
Parameters
event is a user event object created using mcCreateUserEvent.
execution_status specifies the new execution status to be set and can be MC_COMPLETE or an McResult value to indicate an error. Thus a negative integer value causes all enqueued commands that wait on this user event to be terminated. mcSetUserEventStatus can only be called once to change the execution status of event.
If there are enqueued commands with user events in the event_wait_list argument of mcEnqueue* commands, the user must ensure that the status of these user events being waited on are set using mcSetUserEventStatus before any MCUT APIs that release MCUT objects except for event objects are called; otherwise the behavior is undefined.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (event == nullptr) {
        per_thread_api_log_str = "event ptr (param0) undef (NULL)";
    } else {
        try {
            set_user_event_status_impl(event, execution_status);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, per_thread_api_log_str, and set_user_event_status_impl().
mcWaitForEvents()
MCAPI_ATTR McResult MCAPI_CALL mcWaitForEvents (uint32_t numEventsInWaitlist, const McEvent * pEventWaitList)
Waits on the user thread for commands identified by event objects to complete.
Parameters
[in] numEventsInWaitlist Number of events to wait for
[in] pEventWaitList List of events to wait for
Waits on the user thread for commands identified by event objects in pEventWaitList to complete. The events specified in pEventWaitList act as synchronization points.
Returns
Error code.
proper exit
MC_INVALID_VALUE
numEventsInWaitlist is greater than 0 and pEventWaitList is NULL (and vice versa).
If an event object in pEventWaitList is not a valid event object.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (pEventWaitList == nullptr && numEventsInWaitlist > 0) {
        per_thread_api_log_str = "invalid event waitlist ptr (NULL)";
    } else if (pEventWaitList != nullptr && numEventsInWaitlist == 0) {
        per_thread_api_log_str = "invalid event waitlist size (zero)";
    } else {
        try {
            McResult waitliststatus = MC_NO_ERROR;
            wait_for_events_impl(numEventsInWaitlist, pEventWaitList, waitliststatus);
            if (waitliststatus != McResult::MC_NO_ERROR) {
                per_thread_api_log_str = "event in waitlist has an error";
            }
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, MC_NO_ERROR, per_thread_api_log_str, and wait_for_events_impl().