OrcaSlicer: Slic3r::WipeTower Class Reference
Slic3r::WipeTower Class Reference
#include <src/libslic3r/GCode/WipeTower.hpp>
Classes
struct box_coordinates
struct Extrusion
struct FilamentParameters
struct ToolChangeResult
struct WipeTowerInfo
Public Member Functions
ToolChangeResult construct_tcr (WipeTowerWriter &writer, bool priming, size_t old_tool, bool is_finish, float purge_volume) const
WipeTower (const PrintConfig &config, int plate_idx, Vec3d plate_origin, const float wipe_volume, size_t initial_tool, const float wipe_tower_height)
void set_extruder (size_t idx, const PrintConfig &config)
void plan_toolchange (float z_par, float layer_height_par, unsigned int old_tool, unsigned int new_tool, float wipe_volume=0.f, float prime_volume=0.f)
void generate (std::vector< std::vector< ToolChangeResult > > &result)
WipeTower::ToolChangeResult only_generate_out_wall ()
float get_depth () const
float get_brim_width () const
float get_height () const
float get_layer_height () const
void set_last_layer_extruder_fill (bool extruder_fill)
void set_layer (float print_z, float layer_height, size_t max_tool_changes, bool is_first_layer, bool is_last_layer)
const Vec2f & position () const
float width () const
bool finished () const
std::vector< ToolChangeResult > prime (float initial_layer_print_height, const std::vector< unsigned int > &tools, bool last_wipe_inside_wipe_tower)
ToolChangeResult tool_change (size_t new_tool, bool extrude_perimeter=false, bool first_toolchange_to_nonsoluble=false)
ToolChangeResult finish_layer (bool extruder_perimeter=true, bool extruder_fill=true)
float extrusion_flow (float layer_height=-1.f) const
bool get_floating_area (float &start_pos_y, float &end_pos_y) const
bool need_thick_bridge_flow (float pos_y) const
float get_extrusion_flow () const
bool layer_finished () const
std::vector< float > get_used_filament () const
int get_number_of_toolchanges () const
Static Public Member Functions
static const std::string never_skip_tag ()
Static Public Attributes
static const std::map< float, float > min_depth_per_height
Private Types
enum wipe_shape { SHAPE_NORMAL = 1 , SHAPE_REVERSED = -1 }
enum { RectangularBed , CircularBed , CustomBed }
Private Member Functions
float filament_area () const
bool is_first_layer () const
float volume_to_length (float volume, float line_width, float layer_height) const
void plan_tower ()
void make_wipe_tower_square ()
void save_on_last_wipe ()
box_coordinates align_perimeter (const box_coordinates &perimeter_box)
int first_toolchange_to_nonsoluble_nonsupport (const std::vector< WipeTowerInfo::ToolChange > &tool_changes) const
void toolchange_Unload (WipeTowerWriter &writer, const box_coordinates &cleaning_box, const std::string &current_material, const int new_temperature)
void toolchange_Change (WipeTowerWriter &writer, const size_t new_tool, const std::string &new_material)
void toolchange_Load (WipeTowerWriter &writer, const box_coordinates &cleaning_box)
void toolchange_Wipe (WipeTowerWriter &writer, const box_coordinates &cleaning_box, float wipe_volume)
Private Attributes
const float Width_To_Nozzle_Ratio = 1.25f
const float WT_EPSILON = 1e-3f
bool m_enable_timelapse_print = false
bool m_semm = true
Vec2f m_wipe_tower_pos
float m_wipe_tower_width
float m_wipe_tower_depth = 0.f
float m_wipe_tower_height = 0.f
float m_wipe_tower_brim_width = 0.f
float m_wipe_tower_brim_width_real = 0.f
float m_wipe_tower_rotation_angle = 0.f
float m_internal_rotation = 0.f
float m_y_shift = 0.f
float m_z_pos = 0.f
float m_layer_height = 0.f
size_t m_max_color_changes = 0
int m_old_temperature = -1
float m_travel_speed = 0.f
float m_first_layer_speed = 0.f
size_t m_first_layer_idx = size_t(-1)
float m_bridging = 0.f
bool m_no_sparse_layers = false
bool m_adhesion = true
GCodeFlavor m_gcode_flavor
enum Slic3r::WipeTower:: { ... } m_bed_shape
float m_bed_width
Vec2f m_bed_bottom_left
float m_perimeter_width = 0.4f * Width_To_Nozzle_Ratio
float m_extrusion_flow = 0.038f
std::vector< FilamentParameters > m_filpar
unsigned int m_num_layer_changes = 0
unsigned int m_num_tool_changes = 0
bool m_print_brim = true
unsigned int m_idx_tool_change_in_layer = 0; // Layer change counter in this layer. Counting up to m_max_color_changes.
wipe_shape m_current_shape = SHAPE_NORMAL
size_t m_current_tool = 0
const float m_wipe_volume
float m_depth_traversed = 0.f
bool m_current_layer_finished = false
bool m_left_to_right = true
float m_extra_spacing = 1.f
std::vector< WipeTowerInfo > m_plan
std::vector< WipeTowerInfo >::iterator m_layer_info = m_plan.end()
std::vector< float > m_used_filament_length
Detailed Description
Class Documentation
Slic3r::WipeTower::FilamentParameters
struct Slic3r::WipeTower::FilamentParameters
Class Members
float filament_area
bool is_soluble = false
bool is_support = false
string material = "PLA"
float max_e_speed = std::numeric_limits<float>::max()
float nozzle_diameter
int nozzle_temperature = 0
int nozzle_temperature_initial_layer = 0
float ramming_line_width_multiplicator = 1.f
vector< float > ramming_speed
float ramming_step_multiplicator = 1.f
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
RectangularBed
CircularBed
CustomBed
         {
        RectangularBed,
        CircularBed,
        CustomBed
    } m_bed_shape;
wipe_shape
enum Slic3r::WipeTower::wipe_shape private
Enumerator
SHAPE_NORMAL
SHAPE_REVERSED
  {
    SHAPE_NORMAL = 1,
    SHAPE_REVERSED = -1
  };
Constructor & Destructor Documentation
WipeTower()
Slic3r::WipeTower::WipeTower (const PrintConfig & config, int plate_idx, Vec3d plate_origin, const float wipe_volume, size_t initial_tool, const float wipe_tower_height)
                                                                                                                                                               :
    m_semm(config.single_extruder_multi_material.value),
    m_wipe_tower_pos(config.wipe_tower_x.get_at(plate_idx), config.wipe_tower_y.get_at(plate_idx)),
    m_wipe_tower_width(float(config.prime_tower_width)),
    // BBS
    m_wipe_tower_height(wipe_tower_height),
    m_wipe_tower_rotation_angle(float(config.wipe_tower_rotation_angle)),
    m_wipe_tower_brim_width(float(config.prime_tower_brim_width)),
    m_y_shift(0.f),
    m_z_pos(0.f),
    //m_bridging(float(config.wipe_tower_bridging)),
    m_bridging(10.f),
    m_no_sparse_layers(config.wipe_tower_no_sparse_layers),
    m_gcode_flavor(config.gcode_flavor),
    m_travel_speed(config.travel_speed),
    m_current_tool(initial_tool),
    //wipe_volumes(flush_matrix)
    m_wipe_volume(prime_volume),
    m_enable_timelapse_print(config.timelapse_type.value == TimelapseType::tlSmooth)
{
    // Read absolute value of first layer speed, if given as percentage,
    // it is taken over following default. Speeds from config are not
    // easily accessible here.
    const float default_speed = 60.f;
    m_first_layer_speed = config.get_abs_value("initial_layer_speed");
    if (m_first_layer_speed == 0.f) // just to make sure autospeed doesn't break it.
        m_first_layer_speed = default_speed / 2.f;
    // If this is a single extruder MM printer, we will use all the SE-specific config values.
    // Otherwise, the defaults will be used to turn off the SE stuff.
    // BBS: remove useless config
#if 0
    if (m_semm) {
        m_cooling_tube_retraction = float(config.cooling_tube_retraction);
        m_cooling_tube_length     = float(config.cooling_tube_length);
        m_parking_pos_retraction  = float(config.parking_pos_retraction);
        m_extra_loading_move      = float(config.extra_loading_move);
        m_set_extruder_trimpot    = config.high_current_on_filament_swap;
    }
#endif
    // Calculate where the priming lines should be - very naive test not detecting parallelograms etc.
    const std::vector<Vec2d>& bed_points = config.printable_area.values;
    BoundingBoxf bb(bed_points);
    m_bed_width = float(bb.size().x());
    m_bed_shape = (bed_points.size() == 4 ? RectangularBed : CircularBed);
    if (m_bed_shape == CircularBed) {
        // this may still be a custom bed, check that the points are roughly on a circle
        double r2 = std::pow(m_bed_width/2., 2.);
        double lim2 = std::pow(m_bed_width/10., 2.);
        Vec2d center = bb.center();
        for (const Vec2d& pt : bed_points)
            if (std::abs(std::pow(pt.x()-center.x(), 2.) + std::pow(pt.y()-center.y(), 2.) - r2) > lim2) {
                m_bed_shape = CustomBed;
                break;
            }
    }
    m_bed_bottom_left = m_bed_shape == RectangularBed
                  ? Vec2f(bed_points.front().x(), bed_points.front().y())
                  : Vec2f::Zero();
}
References Slic3r::BoundingBoxBase< PointClass >::center(), CircularBed, CustomBed, m_bed_bottom_left, m_bed_shape, m_bed_width, m_first_layer_speed, m_semm, RectangularBed, and Slic3r::BoundingBoxBase< PointClass >::size().
Member Function Documentation
align_perimeter()
WipeTower::box_coordinates Slic3r::WipeTower::align_perimeter (const box_coordinates & perimeter_box) private
{
    box_coordinates aligned_box = perimeter_box;
    float spacing = m_extra_spacing * m_perimeter_width;
    float up = perimeter_box.lu(1) - m_perimeter_width;
    up = align_ceil(up, spacing);
    up += m_perimeter_width;
    up = std::min(up, m_wipe_tower_depth);
    float down = perimeter_box.ld(1) - m_perimeter_width;
    down = align_floor(down, spacing);
    down += m_perimeter_width;
    down = std::max(down, -m_y_shift);
    aligned_box.lu(1) = aligned_box.ru(1) = up;
    aligned_box.ld(1) = aligned_box.rd(1) = down;
    return aligned_box;
}
References Slic3r::align_ceil(), Slic3r::align_floor(), Slic3r::WipeTower::box_coordinates::ld, Slic3r::WipeTower::box_coordinates::lu, m_extra_spacing, m_perimeter_width, m_wipe_tower_depth, m_y_shift, Slic3r::WipeTower::box_coordinates::rd, and Slic3r::WipeTower::box_coordinates::ru.
Referenced by finish_layer(), only_generate_out_wall(), and tool_change().
construct_tcr()
WipeTower::ToolChangeResult Slic3r::WipeTower::construct_tcr (WipeTowerWriter & writer, bool priming, size_t old_tool, bool is_finish, float purge_volume) const
{
    ToolChangeResult result;
    result.priming      = priming;
    result.initial_tool = int(old_tool);
    result.new_tool     = int(m_current_tool);
    result.print_z      = m_z_pos;
    result.layer_height = m_layer_height;
    result.elapsed_time = writer.elapsed_time();
    result.start_pos    = writer.start_pos_rotated();
    result.end_pos      = priming ? writer.pos() : writer.pos_rotated();
    result.gcode        = std::move(writer.gcode());
    result.extrusions   = std::move(writer.extrusions());
    result.wipe_path    = std::move(writer.wipe_path());
    result.is_finish_first = is_finish;
    // BBS
    result.purge_volume = purge_volume;
    return result;
}
References Slic3r::WipeTowerWriter::elapsed_time(), Slic3r::WipeTower::ToolChangeResult::elapsed_time, Slic3r::WipeTower::ToolChangeResult::end_pos, Slic3r::WipeTowerWriter::extrusions(), Slic3r::WipeTower::ToolChangeResult::extrusions, Slic3r::WipeTowerWriter::gcode(), Slic3r::WipeTower::ToolChangeResult::gcode, Slic3r::WipeTower::ToolChangeResult::initial_tool, int, Slic3r::WipeTower::ToolChangeResult::is_finish_first, Slic3r::WipeTower::ToolChangeResult::layer_height, m_current_tool, m_layer_height, m_z_pos, Slic3r::WipeTower::ToolChangeResult::new_tool, Slic3r::WipeTowerWriter::pos(), Slic3r::WipeTowerWriter::pos_rotated(), Slic3r::WipeTower::ToolChangeResult::priming, Slic3r::WipeTower::ToolChangeResult::print_z, Slic3r::WipeTower::ToolChangeResult::purge_volume, Slic3r::WipeTower::ToolChangeResult::start_pos, Slic3r::WipeTowerWriter::start_pos_rotated(), Slic3r::WipeTowerWriter::wipe_path(), and Slic3r::WipeTower::ToolChangeResult::wipe_path.
Referenced by finish_layer(), only_generate_out_wall(), and tool_change().
extrusion_flow()
float Slic3r::WipeTower::extrusion_flow (float layer_height = -1.f) const inline
    {
        if (layer_height < 0) return m_extrusion_flow;
        return layer_height * (m_perimeter_width - layer_height * (1.f - float(M_PI) / 4.f)) / filament_area();
    }
References filament_area(), Slic3r::layer_height(), m_extrusion_flow, m_perimeter_width, and M_PI.
Referenced by need_thick_bridge_flow(), Slic3r::WipeTowerWriter::rectangle_fill_box(), set_layer(), and toolchange_Wipe().
filament_area()
float Slic3r::WipeTower::filament_area () const inline private
{
        return m_filpar[0].filament_area; // all extruders are assumed to have the same filament diameter at this point
    }
References m_filpar.
Referenced by extrusion_flow(), set_extruder(), and toolchange_Unload().
finish_layer()
WipeTower::ToolChangeResult Slic3r::WipeTower::finish_layer (bool extruder_perimeter = true, bool extruder_fill = true)
{
  assert(! this->layer_finished());
    m_current_layer_finished = true;
    size_t old_tool = m_current_tool;
  WipeTowerWriter writer(m_layer_height, m_perimeter_width, m_gcode_flavor, m_filpar);
  writer.set_extrusion_flow(m_extrusion_flow)
    .set_z(m_z_pos)
    .set_initial_tool(m_current_tool)
        .set_y_shift(m_y_shift - (m_current_shape == SHAPE_REVERSED ? m_layer_info->toolchanges_depth() : 0.f));
  // Slow down on the 1st layer.
    bool first_layer = is_first_layer();
    // BBS: speed up perimeter speed to 90mm/s for non-first layer
    float           feedrate   = first_layer ? std::min(m_first_layer_speed * 60.f, 5400.f) : std::min(60.0f * m_filpar[m_current_tool].max_e_speed / m_extrusion_flow, 5400.f);
    float fill_box_y = m_layer_info->toolchanges_depth() + m_perimeter_width;
    box_coordinates fill_box(Vec2f(m_perimeter_width, fill_box_y),
                             m_wipe_tower_width - 2 * m_perimeter_width, m_layer_info->depth - fill_box_y);
    writer.set_initial_position((m_left_to_right ? fill_box.ru : fill_box.lu), // so there is never a diagonal travel
                                 m_wipe_tower_width, m_wipe_tower_depth, m_internal_rotation);
    bool toolchanges_on_layer = m_layer_info->toolchanges_depth() > WT_EPSILON;
    // inner perimeter of the sparse section, if there is space for it:
    if (fill_box.ru.y() - fill_box.rd.y() > m_perimeter_width - WT_EPSILON)
        writer.rectangle_fill_box(this, fill_box.ld, fill_box.rd.x() - fill_box.ld.x(), fill_box.ru.y() - fill_box.rd.y(), feedrate);
    // we are in one of the corners, travel to ld along the perimeter:
    // BBS: Delete some unnecessary travel
    //if (writer.x() > fill_box.ld.x() + EPSILON) writer.travel(fill_box.ld.x(), writer.y());
    //if (writer.y() > fill_box.ld.y() + EPSILON) writer.travel(writer.x(), fill_box.ld.y());
    // Extrude infill to support the material to be printed above.
    const float dy = (fill_box.lu.y() - fill_box.ld.y() - m_perimeter_width);
    float left = fill_box.lu.x() + 2*m_perimeter_width;
    float right = fill_box.ru.x() - 2 * m_perimeter_width;
    std::vector<Vec2f> finish_rect_wipe_path;
    if (extruder_fill && dy > m_perimeter_width)
    {
        writer.travel(fill_box.ld + Vec2f(m_perimeter_width * 2, 0.f))
              .append(";--------------------\n"
                      "; CP EMPTY GRID START\n")
              .comment_with_value(" layer #", m_num_layer_changes + 1);
        // Is there a soluble filament wiped/rammed at the next layer?
        // If so, the infill should not be sparse.
        bool solid_infill = m_layer_info+1 == m_plan.end()
                          ? false
                          : std::any_of((m_layer_info+1)->tool_changes.begin(),
                                        (m_layer_info+1)->tool_changes.end(),
                                   [this](const WipeTowerInfo::ToolChange& tch) {
                                       return m_filpar[tch.new_tool].is_soluble
                                           || m_filpar[tch.old_tool].is_soluble;
                                   });
        solid_infill |= first_layer && m_adhesion;
        if (solid_infill) {
            float sparse_factor = 1.5f; // 1=solid, 2=every other line, etc.
            if (first_layer) { // the infill should touch perimeters
                left  -= m_perimeter_width;
                right += m_perimeter_width;
                sparse_factor = 1.f;
            }
            float y = fill_box.ld.y() + m_perimeter_width;
            int n = dy / (m_perimeter_width * sparse_factor);
            float spacing = (dy-m_perimeter_width)/(n-1);
            int i=0;
            for (i=0; i<n; ++i) {
                writer.extrude(writer.x(), y, feedrate)
                      .extrude(i%2 ? left : right, y);
                y = y + spacing;
            }
            writer.extrude(writer.x(), fill_box.lu.y());
        } else {
            // Extrude an inverse U at the left of the region and the sparse infill.
            writer.extrude(fill_box.lu + Vec2f(m_perimeter_width * 2, 0.f), feedrate);
            const int n = 1+int((right-left)/m_bridging);
            const float dx = (right-left)/n;
            for (int i=1;i<=n;++i) {
                float x=left+dx*i;
                writer.travel(x,writer.y());
                writer.extrude(x,i%2 ? fill_box.rd.y() : fill_box.ru.y());
            }
            // BBS: add wipe_path for this case: only with finish rectangle
            finish_rect_wipe_path.emplace_back(writer.pos());
            finish_rect_wipe_path.emplace_back(Vec2f(left + dx * n, n % 2 ? fill_box.ru.y() : fill_box.rd.y()));
        }
        writer.append("; CP EMPTY GRID END\n"
                      ";------------------\n\n\n\n\n\n\n");
    }
    // outer perimeter (always):
    // BBS
    box_coordinates wt_box(Vec2f(0.f, (m_current_shape == SHAPE_REVERSED ? m_layer_info->toolchanges_depth() : 0.f)),
        m_wipe_tower_width, m_layer_info->depth + m_perimeter_width);
    wt_box = align_perimeter(wt_box);
    if (extrude_perimeter) {
        writer.rectangle(wt_box, feedrate);
    }
    // brim chamfer
    float spacing = m_perimeter_width - m_layer_height * float(1. - M_PI_4);
    // How many perimeters shall the brim have?
    int loops_num = (m_wipe_tower_brim_width + spacing / 2.f) / spacing;
    const float max_chamfer_width = 3.f;
    if (!first_layer) {
        // stop print chamfer if depth changes
        if (m_layer_info->depth != m_plan.front().depth) {
            loops_num = 0;
        }
        else {
            // limit max chamfer width to 3 mm
            int chamfer_loops_num = (int)(max_chamfer_width / spacing);
            int dist_to_1st = m_layer_info - m_plan.begin() - m_first_layer_idx;
            loops_num = std::min(loops_num, chamfer_loops_num) - dist_to_1st;
        }
    }
    if (loops_num > 0) {
        box_coordinates box = wt_box;
        for (size_t i = 0; i < loops_num; ++i) {
            box.expand(spacing);
            writer.rectangle(box);
        }
        if (first_layer) {
            // Save actual brim width to be later passed to the Print object, which will use it
            // for skirt calculation and pass it to GLCanvas for precise preview box
            m_wipe_tower_brim_width_real = wt_box.ld.x() - box.ld.x() + spacing / 2.f;
        }
        wt_box = box;
    }
    // Now prepare future wipe. box contains rectangle that was extruded last (ccw).
    Vec2f target = (writer.pos() == wt_box.ld ? wt_box.rd :
                   (writer.pos() == wt_box.rd ? wt_box.ru :
                   (writer.pos() == wt_box.ru ? wt_box.lu :
                    wt_box.ld)));
    // BBS: add wipe_path for this case: only with finish rectangle
    if (finish_rect_wipe_path.size() == 2 && finish_rect_wipe_path[0] == writer.pos())
        target = finish_rect_wipe_path[1];
    writer.add_wipe_point(writer.pos())
          .add_wipe_point(target);
    // Ask our writer about how much material was consumed.
    // Skip this in case the layer is sparse and config option to not print sparse layers is enabled.
    if (! m_no_sparse_layers || toolchanges_on_layer)
        if (m_current_tool < m_used_filament_length.size())
            m_used_filament_length[m_current_tool] += writer.get_and_reset_used_filament_length();
    return construct_tcr(writer, false, old_tool, true, 0.f);
}
References Slic3r::WipeTowerWriter::add_wipe_point(), align_perimeter(), Slic3r::WipeTowerWriter::append(), Slic3r::append(), construct_tcr(), Slic3r::WipeTower::box_coordinates::expand(), Slic3r::WipeTowerWriter::extrude(), Slic3r::WipeTowerWriter::get_and_reset_used_filament_length(), int, is_first_layer(), layer_finished(), Slic3r::WipeTower::box_coordinates::ld, Slic3r::WipeTower::box_coordinates::lu, m_adhesion, m_bridging, m_current_layer_finished, m_current_shape, m_current_tool, m_extrusion_flow, m_filpar, m_first_layer_idx, m_first_layer_speed, m_gcode_flavor, m_internal_rotation, m_layer_height, m_layer_info, m_left_to_right, m_no_sparse_layers, m_num_layer_changes, m_perimeter_width, m_plan, m_used_filament_length, m_wipe_tower_brim_width, m_wipe_tower_brim_width_real, m_wipe_tower_depth, m_wipe_tower_width, m_y_shift, m_z_pos, n, Slic3r::WipeTowerWriter::pos(), Slic3r::WipeTower::box_coordinates::rd, Slic3r::WipeTowerWriter::rectangle(), Slic3r::WipeTowerWriter::rectangle_fill_box(), Slic3r::WipeTower::box_coordinates::ru, Slic3r::WipeTowerWriter::set_extrusion_flow(), Slic3r::WipeTowerWriter::set_initial_position(), Slic3r::WipeTowerWriter::set_initial_tool(), Slic3r::WipeTowerWriter::set_y_shift(), Slic3r::WipeTowerWriter::set_z(), SHAPE_REVERSED, Slic3r::WipeTowerWriter::travel(), WT_EPSILON, Slic3r::WipeTowerWriter::x(), and Slic3r::WipeTowerWriter::y().
Referenced by generate(), and save_on_last_wipe().
finished()
bool Slic3r::WipeTower::finished () const inline
{ return m_max_color_changes == 0; }
References m_max_color_changes.
first_toolchange_to_nonsoluble_nonsupport()
int Slic3r::WipeTower::first_toolchange_to_nonsoluble_nonsupport (const std::vector< WipeTowerInfo::ToolChange > & tool_changes) const private
{
    for (size_t idx=0; idx<tool_changes.size(); ++idx)
        if (! m_filpar[tool_changes[idx].new_tool].is_soluble && ! m_filpar[tool_changes[idx].new_tool].is_support)
            return idx;
    return -1;
}
References m_filpar.
Referenced by generate(), and save_on_last_wipe().
generate()
void Slic3r::WipeTower::generate (std::vector< std::vector< ToolChangeResult > > & result)
{
  if (m_plan.empty())
        return;
    m_extra_spacing = 1.f;
  plan_tower();
    // BBS
#if 0
    for (int i=0;i<5;++i) {
        save_on_last_wipe();
        plan_tower();
    }
#endif
    m_layer_info = m_plan.begin();
    // we don't know which extruder to start with - we'll set it according to the first toolchange
    for (const auto& layer : m_plan) {
        if (!layer.tool_changes.empty()) {
            m_current_tool = layer.tool_changes.front().old_tool;
            break;
        }
    }
    for (auto& used : m_used_filament_length) // reset used filament stats
        used = 0.f;
    m_old_temperature = -1; // reset last temperature written in the gcode
    std::vector<WipeTower::ToolChangeResult> layer_result;
  for (auto layer : m_plan)
  {
        set_layer(layer.z, layer.height, 0, false/*layer.z == m_plan.front().z*/, layer.z == m_plan.back().z);
        // BBS
        //m_internal_rotation += 180.f;
        if (m_layer_info->depth < m_wipe_tower_depth - m_perimeter_width) {
            // align y shift to perimeter width
            float dy = m_extra_spacing * m_perimeter_width;
            m_y_shift = (m_wipe_tower_depth - m_layer_info->depth) / 2.f;
            m_y_shift = align_round(m_y_shift, dy);
        }
        // BBS: consider both soluable and support properties
        int idx = first_toolchange_to_nonsoluble_nonsupport (layer.tool_changes);
        ToolChangeResult finish_layer_tcr;
        ToolChangeResult timelapse_wall;
        if (idx == -1) {
            // if there is no toolchange switching to non-soluble, finish layer
            // will be called at the very beginning. That's the last possibility
            // where a nonsoluble tool can be.
            if (m_enable_timelapse_print) {
                timelapse_wall = only_generate_out_wall();
            }
            finish_layer_tcr = finish_layer(m_enable_timelapse_print ? false : true, layer.extruder_fill);
        }
        for (int i=0; i<int(layer.tool_changes.size()); ++i) {
            if (i == 0 && m_enable_timelapse_print) {
                timelapse_wall = only_generate_out_wall();
            }
            if (i == idx) {
                layer_result.emplace_back(tool_change(layer.tool_changes[i].new_tool, m_enable_timelapse_print ? false : true));
                // finish_layer will be called after this toolchange
                finish_layer_tcr = finish_layer(false, layer.extruder_fill);
            }
            else {
                if (idx == -1 && i == 0) {
                    layer_result.emplace_back(tool_change(layer.tool_changes[i].new_tool, false, true));
                } else {
                    layer_result.emplace_back(tool_change(layer.tool_changes[i].new_tool));
                }
            }
        }
        if (layer_result.empty()) {
            // there is nothing to merge finish_layer with
            layer_result.emplace_back(std::move(finish_layer_tcr));
        }
        else {
            if (idx == -1)
                layer_result[0] = merge_tcr(finish_layer_tcr, layer_result[0]);
            else if (is_valid_gcode(finish_layer_tcr.gcode))
                layer_result[idx] = merge_tcr(layer_result[idx], finish_layer_tcr);
        }
        if (m_enable_timelapse_print) {
            layer_result.insert(layer_result.begin(), std::move(timelapse_wall));
        }
    result.emplace_back(std::move(layer_result));
  }
}
References Slic3r::align_round(), finish_layer(), first_toolchange_to_nonsoluble_nonsupport(), Slic3r::WipeTower::ToolChangeResult::gcode, int, Slic3r::is_valid_gcode(), m_current_tool, m_enable_timelapse_print, m_extra_spacing, m_layer_info, m_old_temperature, m_perimeter_width, m_plan, m_used_filament_length, m_wipe_tower_depth, m_y_shift, Slic3r::merge_tcr(), only_generate_out_wall(), plan_tower(), save_on_last_wipe(), set_layer(), and tool_change().
get_brim_width()
float Slic3r::WipeTower::get_brim_width () const inline
{ return m_wipe_tower_brim_width_real; }
References m_wipe_tower_brim_width_real.
get_depth()
float Slic3r::WipeTower::get_depth () const inline
{ return m_wipe_tower_depth; }
References m_wipe_tower_depth.
get_extrusion_flow()
float Slic3r::WipeTower::get_extrusion_flow () const inline
{ return m_extrusion_flow; }
References m_extrusion_flow.
Referenced by Slic3r::WipeTowerWriter::rectangle_fill_box().
get_floating_area()
bool Slic3r::WipeTower::get_floating_area (float & start_pos_y, float & end_pos_y) const
{
    if (m_layer_info == m_plan.begin() || (m_layer_info - 1) == m_plan.begin())
        return false;
    float last_layer_fill_box_y = (m_layer_info - 1)->toolchanges_depth() + m_perimeter_width;
    float last_layer_wipe_depth = (m_layer_info - 1)->depth;
    if (last_layer_wipe_depth - last_layer_fill_box_y <= 2 * m_perimeter_width)
        return false;
    start_pos_y = last_layer_fill_box_y + m_perimeter_width;
    end_pos_y   = last_layer_wipe_depth - m_perimeter_width;
    return true;
}
References m_layer_info, m_perimeter_width, and m_plan.
Referenced by need_thick_bridge_flow().
get_height()
float Slic3r::WipeTower::get_height () const inline
{ return m_wipe_tower_height; }
References m_wipe_tower_height.
get_layer_height()
float Slic3r::WipeTower::get_layer_height () const inline
{ return m_layer_height; }
References m_layer_height.
get_number_of_toolchanges()
int Slic3r::WipeTower::get_number_of_toolchanges () const inline
{ return m_num_tool_changes; }
References m_num_tool_changes.
get_used_filament()
std::vector< float > Slic3r::WipeTower::get_used_filament () const inline
{ return m_used_filament_length; }
References m_used_filament_length.
is_first_layer()
bool Slic3r::WipeTower::is_first_layer () const inline private
{ return size_t(m_layer_info - m_plan.begin()) == m_first_layer_idx; }
References m_first_layer_idx, m_layer_info, and m_plan.
Referenced by finish_layer(), only_generate_out_wall(), set_layer(), tool_change(), toolchange_Unload(), and toolchange_Wipe().
layer_finished()
bool Slic3r::WipeTower::layer_finished () const inline
{
        return m_current_layer_finished;
  }
References m_current_layer_finished.
Referenced by finish_layer().
make_wipe_tower_square()
void Slic3r::WipeTower::make_wipe_tower_square () private
need_thick_bridge_flow()
bool Slic3r::WipeTower::need_thick_bridge_flow (float pos_y) const
{
    if (m_extrusion_flow >= extrusion_flow(0.2))
        return false;
    float y_min = 0., y_max = 0.;
    if (get_floating_area(y_min, y_max)) {
        return pos_y > y_min && pos_y < y_max;
    }
    return false;
}
References extrusion_flow(), get_floating_area(), and m_extrusion_flow.
Referenced by Slic3r::WipeTowerWriter::rectangle_fill_box(), and toolchange_Wipe().
never_skip_tag()
static const std::string Slic3r::WipeTower::never_skip_tag () inline static
{ return "_GCODE_WIPE_TOWER_NEVER_SKIP_TAG"; }
Referenced by Slic3r::WipeTowerIntegration::post_process_wipe_tower_moves(), and toolchange_Change().
only_generate_out_wall()
WipeTower::ToolChangeResult Slic3r::WipeTower::only_generate_out_wall ()
{
    size_t old_tool = m_current_tool;
    WipeTowerWriter writer(m_layer_height, m_perimeter_width, m_gcode_flavor, m_filpar);
    writer.set_extrusion_flow(m_extrusion_flow)
        .set_z(m_z_pos)
        .set_initial_tool(m_current_tool)
        .set_y_shift(m_y_shift - (m_current_shape == SHAPE_REVERSED ? m_layer_info->toolchanges_depth() : 0.f));
    // Slow down on the 1st layer.
    bool first_layer = is_first_layer();
    // BBS: speed up perimeter speed to 90mm/s for non-first layer
    float           feedrate   = first_layer ? std::min(m_first_layer_speed * 60.f, 5400.f) : std::min(60.0f * m_filpar[m_current_tool].max_e_speed / m_extrusion_flow, 5400.f);
    float           fill_box_y = m_layer_info->toolchanges_depth() + m_perimeter_width;
    box_coordinates fill_box(Vec2f(m_perimeter_width, fill_box_y), m_wipe_tower_width - 2 * m_perimeter_width, m_layer_info->depth - fill_box_y);
    writer.set_initial_position((m_left_to_right ? fill_box.ru : fill_box.lu), // so there is never a diagonal travel
                                m_wipe_tower_width, m_wipe_tower_depth, m_internal_rotation);
    bool toolchanges_on_layer = m_layer_info->toolchanges_depth() > WT_EPSILON;
    // we are in one of the corners, travel to ld along the perimeter:
    // BBS: Delete some unnecessary travel
    //if (writer.x() > fill_box.ld.x() + EPSILON) writer.travel(fill_box.ld.x(), writer.y());
    //if (writer.y() > fill_box.ld.y() + EPSILON) writer.travel(writer.x(), fill_box.ld.y());
    // outer perimeter (always):
    // BBS
    box_coordinates wt_box(Vec2f(0.f, (m_current_shape == SHAPE_REVERSED ? m_layer_info->toolchanges_depth() : 0.f)), m_wipe_tower_width, m_layer_info->depth + m_perimeter_width);
    wt_box = align_perimeter(wt_box);
    writer.rectangle(wt_box, feedrate);
    // Now prepare future wipe. box contains rectangle that was extruded last (ccw).
    Vec2f target = (writer.pos() == wt_box.ld ? wt_box.rd : (writer.pos() == wt_box.rd ? wt_box.ru : (writer.pos() == wt_box.ru ? wt_box.lu : wt_box.ld)));
    writer.add_wipe_point(writer.pos()).add_wipe_point(target);
    // Ask our writer about how much material was consumed.
    // Skip this in case the layer is sparse and config option to not print sparse layers is enabled.
    if (!m_no_sparse_layers || toolchanges_on_layer)
        if (m_current_tool < m_used_filament_length.size()) m_used_filament_length[m_current_tool] += writer.get_and_reset_used_filament_length();
    return construct_tcr(writer, false, old_tool, true, 0.f);
}
References Slic3r::WipeTowerWriter::add_wipe_point(), align_perimeter(), construct_tcr(), Slic3r::WipeTowerWriter::get_and_reset_used_filament_length(), is_first_layer(), Slic3r::WipeTower::box_coordinates::lu, m_current_shape, m_current_tool, m_extrusion_flow, m_filpar, m_first_layer_speed, m_gcode_flavor, m_internal_rotation, m_layer_height, m_layer_info, m_left_to_right, m_no_sparse_layers, m_perimeter_width, m_used_filament_length, m_wipe_tower_depth, m_wipe_tower_width, m_y_shift, m_z_pos, Slic3r::WipeTowerWriter::pos(), Slic3r::WipeTowerWriter::rectangle(), Slic3r::WipeTower::box_coordinates::ru, Slic3r::WipeTowerWriter::set_extrusion_flow(), Slic3r::WipeTowerWriter::set_initial_position(), Slic3r::WipeTowerWriter::set_initial_tool(), Slic3r::WipeTowerWriter::set_y_shift(), Slic3r::WipeTowerWriter::set_z(), SHAPE_REVERSED, and WT_EPSILON.
Referenced by generate().
plan_toolchange()
void Slic3r::WipeTower::plan_toolchange (float z_par, float layer_height_par, unsigned int old_tool, unsigned int new_tool, float wipe_volume = 0.f, float prime_volume = 0.f)
{
  assert(m_plan.empty() || m_plan.back().z <= z_par + WT_EPSILON);  // refuses to add a layer below the last one
  if (m_plan.empty() || m_plan.back().z + WT_EPSILON < z_par) // if we moved to a new layer, we'll add it to m_plan first
    m_plan.push_back(WipeTowerInfo(z_par, layer_height_par));
    if (m_first_layer_idx == size_t(-1) && (! m_no_sparse_layers || old_tool != new_tool))
        m_first_layer_idx = m_plan.size() - 1;
    if (old_tool == new_tool) // new layer without toolchanges - we are done
        return;
  // this is an actual toolchange - let's calculate depth to reserve on the wipe tower
    float depth = 0.f;
    float width = m_wipe_tower_width - 2 * m_perimeter_width;
    // BBS: if the wipe tower width is too small, the depth will be infinity
    if (width <= EPSILON)
        return;
    // BBS: remove old filament ramming and first line
#if 0
  float length_to_extrude = volume_to_length(0.25f * std::accumulate(m_filpar[old_tool].ramming_speed.begin(), m_filpar[old_tool].ramming_speed.end(), 0.f),
                    m_perimeter_width * m_filpar[old_tool].ramming_line_width_multiplicator,
                    layer_height_par);
  depth = (int(length_to_extrude / width) + 1) * (m_perimeter_width * m_filpar[old_tool].ramming_line_width_multiplicator * m_filpar[old_tool].ramming_step_multiplicator);
    float ramming_depth = depth;
    length_to_extrude = width*((length_to_extrude / width)-int(length_to_extrude / width)) - width;
    float first_wipe_line = -length_to_extrude;
    length_to_extrude += volume_to_length(wipe_volume, m_perimeter_width, layer_height_par);
    length_to_extrude = std::max(length_to_extrude,0.f);
    depth += (int(length_to_extrude / width) + 1) * m_perimeter_width;
    depth *= m_extra_spacing;
    m_plan.back().tool_changes.push_back(WipeTowerInfo::ToolChange(old_tool, new_tool, depth, ramming_depth, first_wipe_line, wipe_volume));
#else
    float length_to_extrude = volume_to_length(wipe_volume, m_perimeter_width, layer_height_par);
    depth += std::ceil(length_to_extrude / width) * m_perimeter_width;
    //depth *= m_extra_spacing;
    m_plan.back().tool_changes.push_back(WipeTowerInfo::ToolChange(old_tool, new_tool, depth, 0.f, 0.f, wipe_volume, length_to_extrude, purge_volume));
#endif
}
References EPSILON, int, m_extra_spacing, m_filpar, m_first_layer_idx, m_no_sparse_layers, m_perimeter_width, m_plan, m_wipe_tower_width, volume_to_length(), width(), and WT_EPSILON.
plan_tower()
void Slic3r::WipeTower::plan_tower () private
{
    // BBS
    // calculate extra spacing
    float max_depth = 0.f;
    for (auto& info : m_plan)
        max_depth = std::max(max_depth, info.toolchanges_depth());
    float min_wipe_tower_depth = 0.f;
    auto iter = WipeTower::min_depth_per_height.begin();
    while (iter != WipeTower::min_depth_per_height.end()) {
        auto curr_height_to_depth = *iter;
        // This is the case that wipe tower height is lower than the first min_depth_to_height member.
        if (curr_height_to_depth.first >= m_wipe_tower_height) {
            min_wipe_tower_depth = curr_height_to_depth.second;
            break;
        }
        iter++;
        // If curr_height_to_depth is the last member, use its min_depth.
        if (iter == WipeTower::min_depth_per_height.end()) {
            min_wipe_tower_depth = curr_height_to_depth.second;
            break;
        }
        // If wipe tower height is between the current and next member, set the min_depth as linear interpolation between them
        auto next_height_to_depth = *iter;
        if (next_height_to_depth.first > m_wipe_tower_height) {
            float height_base = curr_height_to_depth.first;
            float height_diff = next_height_to_depth.first - curr_height_to_depth.first;
            float min_depth_base = curr_height_to_depth.second;
            float depth_diff = next_height_to_depth.second - curr_height_to_depth.second;
            min_wipe_tower_depth = min_depth_base + (m_wipe_tower_height - curr_height_to_depth.first) / height_diff * depth_diff;
            break;
        }
    }
    {
        if (m_enable_timelapse_print && max_depth < EPSILON)
            max_depth = min_wipe_tower_depth;
        if (max_depth + EPSILON < min_wipe_tower_depth)
            m_extra_spacing = min_wipe_tower_depth / max_depth;
        else
            m_extra_spacing = 1.f;
        for (int idx = 0; idx < m_plan.size(); idx++) {
            auto& info = m_plan[idx];
            if (idx == 0 && m_extra_spacing > 1.f + EPSILON) {
                // apply solid fill for the first layer
                info.extra_spacing = 1.f;
                for (auto& toolchange : info.tool_changes) {
                    float x_to_wipe = volume_to_length(toolchange.wipe_volume, m_perimeter_width, info.height);
                    float line_len = m_wipe_tower_width - 2 * m_perimeter_width;
                    float x_to_wipe_new = x_to_wipe * m_extra_spacing;
                    x_to_wipe_new = std::floor(x_to_wipe_new / line_len) * line_len;
                    x_to_wipe_new = std::max(x_to_wipe_new, x_to_wipe);
                    int line_count = std::ceil((x_to_wipe_new - WT_EPSILON) / line_len);
                    toolchange.required_depth = line_count * m_perimeter_width;
                    toolchange.wipe_volume = x_to_wipe_new / x_to_wipe * toolchange.wipe_volume;
                    toolchange.wipe_length = x_to_wipe_new;
                }
            }
            else {
                info.extra_spacing = m_extra_spacing;
                for (auto& toolchange : info.tool_changes) {
                    toolchange.required_depth *= m_extra_spacing;
                    toolchange.wipe_length = volume_to_length(toolchange.wipe_volume, m_perimeter_width, info.height);
                }
            }
        }
    }
  // Calculate m_wipe_tower_depth (maximum depth for all the layers) and propagate depths downwards
  m_wipe_tower_depth = 0.f;
  for (auto& layer : m_plan)
    layer.depth = 0.f;
    float max_depth_for_all = 0;
    for (int layer_index = int(m_plan.size()) - 1; layer_index >= 0; --layer_index)
  {
    float this_layer_depth = std::max(m_plan[layer_index].depth, m_plan[layer_index].toolchanges_depth());
        if (m_enable_timelapse_print && this_layer_depth < EPSILON)
            this_layer_depth = min_wipe_tower_depth;
    m_plan[layer_index].depth = this_layer_depth;
    if (this_layer_depth > m_wipe_tower_depth - m_perimeter_width)
      m_wipe_tower_depth = this_layer_depth + m_perimeter_width;
    for (int i = layer_index - 1; i >= 0 ; i--)
    {
      if (m_plan[i].depth - this_layer_depth < 2*m_perimeter_width )
        m_plan[i].depth = this_layer_depth;
    }
        if (m_enable_timelapse_print && layer_index == 0)
            max_depth_for_all = m_plan[0].depth;
    }
    if (m_enable_timelapse_print) {
        for (int i = int(m_plan.size()) - 1; i >= 0; i--) {
            m_plan[i].depth = max_depth_for_all;
        }
    }
}
References end, EPSILON, m_enable_timelapse_print, m_extra_spacing, m_perimeter_width, m_plan, m_wipe_tower_depth, m_wipe_tower_height, m_wipe_tower_width, min_depth_per_height, volume_to_length(), and WT_EPSILON.
Referenced by generate().
position()
const Vec2f & Slic3r::WipeTower::position () const inline
{ return m_wipe_tower_pos; }
References m_wipe_tower_pos.
prime()
std::vector< WipeTower::ToolChangeResult > Slic3r::WipeTower::prime (float initial_layer_print_height, const std::vector< unsigned int > & tools, bool last_wipe_inside_wipe_tower)
{
    return std::vector<ToolChangeResult>();
}
save_on_last_wipe()
void Slic3r::WipeTower::save_on_last_wipe () private
{
    for (m_layer_info=m_plan.begin();m_layer_info<m_plan.end();++m_layer_info) {
        set_layer(m_layer_info->z, m_layer_info->height, 0, m_layer_info->z == m_plan.front().z, m_layer_info->z == m_plan.back().z);
        if (m_layer_info->tool_changes.size()==0)   // we have no way to save anything on an empty layer
            continue;
        // Which toolchange will finish_layer extrusions be subtracted from?
        // BBS: consider both soluable and support properties
        int idx = first_toolchange_to_nonsoluble_nonsupport(m_layer_info->tool_changes);
        for (int i=0; i<int(m_layer_info->tool_changes.size()); ++i) {
            auto& toolchange = m_layer_info->tool_changes[i];
            tool_change(toolchange.new_tool);
            if (i == idx) {
                float width = m_wipe_tower_width - 3*m_perimeter_width; // width we draw into
                float length_to_save = finish_layer().total_extrusion_length_in_plane();
                float length_to_wipe = volume_to_length(toolchange.wipe_volume,
                                      m_perimeter_width, m_layer_info->height)  - toolchange.first_wipe_line - length_to_save;
                length_to_wipe = std::max(length_to_wipe,0.f);
                float depth_to_wipe = m_perimeter_width * (std::floor(length_to_wipe/width) + ( length_to_wipe > 0.f ? 1.f : 0.f ) ) * m_extra_spacing;
                toolchange.required_depth = toolchange.ramming_depth + depth_to_wipe;
            }
        }
    }
}
References finish_layer(), first_toolchange_to_nonsoluble_nonsupport(), int, m_extra_spacing, m_layer_info, m_perimeter_width, m_plan, m_wipe_tower_width, set_layer(), tool_change(), Slic3r::WipeTower::ToolChangeResult::total_extrusion_length_in_plane(), volume_to_length(), and width().
Referenced by generate().
set_extruder()
void Slic3r::WipeTower::set_extruder (size_t idx, const PrintConfig & config)
{
    //while (m_filpar.size() < idx+1)   // makes sure the required element is in the vector
    m_filpar.push_back(FilamentParameters());
    m_filpar[idx].material = config.filament_type.get_at(idx);
    m_filpar[idx].is_soluble = config.filament_soluble.get_at(idx);
    // BBS
    m_filpar[idx].is_support = config.filament_is_support.get_at(idx);
    m_filpar[idx].nozzle_temperature = config.nozzle_temperature.get_at(idx);
    m_filpar[idx].nozzle_temperature_initial_layer = config.nozzle_temperature_initial_layer.get_at(idx);
    // If this is a single extruder MM printer, we will use all the SE-specific config values.
    // Otherwise, the defaults will be used to turn off the SE stuff.
    // BBS: remove useless config
#if 0
    if (m_semm) {
        m_filpar[idx].loading_speed           = float(config.filament_loading_speed.get_at(idx));
        m_filpar[idx].loading_speed_start     = float(config.filament_loading_speed_start.get_at(idx));
        m_filpar[idx].unloading_speed         = float(config.filament_unloading_speed.get_at(idx));
        m_filpar[idx].unloading_speed_start   = float(config.filament_unloading_speed_start.get_at(idx));
        m_filpar[idx].delay                   = float(config.filament_toolchange_delay.get_at(idx));
        m_filpar[idx].cooling_moves           = config.filament_cooling_moves.get_at(idx);
        m_filpar[idx].cooling_initial_speed   = float(config.filament_cooling_initial_speed.get_at(idx));
        m_filpar[idx].cooling_final_speed     = float(config.filament_cooling_final_speed.get_at(idx));
    }
#endif
    m_filpar[idx].filament_area = float((M_PI/4.f) * pow(config.filament_diameter.get_at(idx), 2)); // all extruders are assumed to have the same filament diameter at this point
    float nozzle_diameter = float(config.nozzle_diameter.get_at(idx));
    m_filpar[idx].nozzle_diameter = nozzle_diameter; // to be used in future with (non-single) multiextruder MM
    float max_vol_speed = float(config.filament_max_volumetric_speed.get_at(idx));
    if (max_vol_speed!= 0.f)
        m_filpar[idx].max_e_speed = (max_vol_speed / filament_area());
    m_perimeter_width = nozzle_diameter * Width_To_Nozzle_Ratio; // all extruders are now assumed to have the same diameter
    // BBS: remove useless config
#if 0
    if (m_semm) {
        std::istringstream stream{config.filament_ramming_parameters.get_at(idx)};
        float speed = 0.f;
        stream >> m_filpar[idx].ramming_line_width_multiplicator >> m_filpar[idx].ramming_step_multiplicator;
        m_filpar[idx].ramming_line_width_multiplicator /= 100;
        m_filpar[idx].ramming_step_multiplicator /= 100;
        while (stream >> speed)
            m_filpar[idx].ramming_speed.push_back(speed);
    }
#endif
    m_used_filament_length.resize(std::max(m_used_filament_length.size(), idx + 1)); // makes sure that the vector is big enough so we don't have to check later
}
References filament_area(), m_filpar, m_perimeter_width, M_PI, m_semm, m_used_filament_length, and Width_To_Nozzle_Ratio.
Referenced by Slic3r::Print::_make_wipe_tower().
set_last_layer_extruder_fill()
void Slic3r::WipeTower::set_last_layer_extruder_fill (bool extruder_fill) inline
{
        if (!m_plan.empty()) {
      m_plan.back().extruder_fill = extruder_fill;
    }
  }
References m_plan.
set_layer()
void Slic3r::WipeTower::set_layer (float print_z, float layer_height, size_t max_tool_changes, bool is_first_layer, bool is_last_layer) inline
  {
    m_z_pos         = print_z;
    m_layer_height      = layer_height;
    m_depth_traversed  = 0.f;
        m_current_layer_finished = false;
    //m_current_shape = (! is_first_layer && m_current_shape == SHAPE_NORMAL) ? SHAPE_REVERSED : SHAPE_NORMAL;
    m_current_shape = SHAPE_NORMAL;
    if (is_first_layer) {
            m_num_layer_changes = 0;
            m_num_tool_changes  = 0;
        } else
            ++ m_num_layer_changes;
    // Calculate extrusion flow from desired line width, nozzle diameter, filament diameter and layer_height:
    m_extrusion_flow = extrusion_flow(layer_height);
        // Advance m_layer_info iterator, making sure we got it right
    while (!m_plan.empty() && m_layer_info->z < print_z - WT_EPSILON && m_layer_info+1 != m_plan.end())
      ++m_layer_info;
  }
References extrusion_flow(), is_first_layer(), Slic3r::layer_height(), m_current_layer_finished, m_current_shape, m_depth_traversed, m_extrusion_flow, m_layer_height, m_layer_info, m_num_layer_changes, m_num_tool_changes, m_plan, m_z_pos, SHAPE_NORMAL, and WT_EPSILON.
Referenced by generate(), and save_on_last_wipe().
tool_change()
WipeTower::ToolChangeResult Slic3r::WipeTower::tool_change (size_t new_tool, bool extrude_perimeter = false, bool first_toolchange_to_nonsoluble = false)
{
    size_t old_tool = m_current_tool;
    float wipe_depth = 0.f;
  float wipe_length = 0.f;
    float purge_volume = 0.f;
  // Finds this toolchange info
  if (tool != (unsigned int)(-1))
  {
    for (const auto &b : m_layer_info->tool_changes)
      if ( b.new_tool == tool ) {
                wipe_length = b.wipe_length;
                wipe_depth = b.required_depth;
                purge_volume = b.purge_volume;
        break;
      }
  }
  else {
    // Otherwise we are going to Unload only. And m_layer_info would be invalid.
  }
    box_coordinates cleaning_box(
    Vec2f(m_perimeter_width, m_perimeter_width),
    m_wipe_tower_width - 2 * m_perimeter_width,
        (tool != (unsigned int)(-1) ? wipe_depth + m_depth_traversed - m_perimeter_width
                                    : m_wipe_tower_depth - m_perimeter_width));
  WipeTowerWriter writer(m_layer_height, m_perimeter_width, m_gcode_flavor, m_filpar);
  writer.set_extrusion_flow(m_extrusion_flow)
    .set_z(m_z_pos)
    .set_initial_tool(m_current_tool)
        .set_y_shift(m_y_shift + (tool!=(unsigned int)(-1) && (m_current_shape == SHAPE_REVERSED) ? m_layer_info->depth - m_layer_info->toolchanges_depth(): 0.f))
    .append(";--------------------\n"
        "; CP TOOLCHANGE START\n")
    .comment_with_value(" toolchange #", m_num_tool_changes + 1); // the number is zero-based
    if (tool != (unsigned)(-1))
        writer.append(std::string("; material : " + (m_current_tool < m_filpar.size() ? m_filpar[m_current_tool].material : "(NONE)") + " -> " + m_filpar[tool].material + "\n").c_str())
              .append(";--------------------\n");
    writer.speed_override_backup();
  writer.speed_override(100);
  Vec2f initial_position = cleaning_box.ld + Vec2f(0.f, m_depth_traversed);
    writer.set_initial_position(initial_position, m_wipe_tower_width, m_wipe_tower_depth, m_internal_rotation);
    // Increase the extruder driver current to allow fast ramming.
    //BBS
  //if (m_set_extruder_trimpot)
  //  writer.set_extruder_trimpot(750);
    // Ram the hot material out of the melt zone, retract the filament into the cooling tubes and let it cool.
    if (tool != (unsigned int)-1){      // This is not the last change.
        toolchange_Unload(writer, cleaning_box, m_filpar[m_current_tool].material,
                          is_first_layer() ? m_filpar[tool].nozzle_temperature_initial_layer : m_filpar[tool].nozzle_temperature);
        toolchange_Change(writer, tool, m_filpar[tool].material); // Change the tool, set a speed override for soluble and flex materials.
        toolchange_Load(writer, cleaning_box);
        // BBS
        //writer.travel(writer.x(), writer.y()-m_perimeter_width); // cooling and loading were done a bit down the road
        if (extrude_perimeter) {
            box_coordinates wt_box(Vec2f(0.f, (m_current_shape == SHAPE_REVERSED) ? m_layer_info->toolchanges_depth() - m_layer_info->depth : 0.f),
                m_wipe_tower_width, m_layer_info->depth + m_perimeter_width);
            // align the perimeter
            wt_box = align_perimeter(wt_box);
            writer.rectangle(wt_box);
            writer.travel(initial_position);
        }
        if (first_toolchange_to_nonsoluble) {
            writer.travel(Vec2f(0, 0));
            writer.travel(initial_position);
        }
        toolchange_Wipe(writer, cleaning_box, wipe_length);     // Wipe the newly loaded filament until the end of the assigned wipe area.
        ++ m_num_tool_changes;
    } else
        toolchange_Unload(writer, cleaning_box, m_filpar[m_current_tool].material, m_filpar[m_current_tool].nozzle_temperature);
    m_depth_traversed += wipe_depth;
    //BBS
  //if (m_set_extruder_trimpot)
  //  writer.set_extruder_trimpot(550);    // Reset the extruder current to a normal value.
  writer.speed_override_restore();
    writer.feedrate(m_travel_speed * 60.f)
          .flush_planner_queue()
          .reset_extruder()
          .append("; CP TOOLCHANGE END\n"
                  ";------------------\n"
                  "\n\n");
    // Ask our writer about how much material was consumed:
    if (m_current_tool < m_used_filament_length.size())
        m_used_filament_length[m_current_tool] += writer.get_and_reset_used_filament_length();
    return construct_tcr(writer, false, old_tool, false, purge_volume);
}
References align_perimeter(), Slic3r::WipeTowerWriter::append(), Slic3r::append(), Slic3r::WipeTowerWriter::comment_with_value(), construct_tcr(), Slic3r::WipeTowerWriter::feedrate(), Slic3r::WipeTowerWriter::flush_planner_queue(), Slic3r::WipeTowerWriter::get_and_reset_used_filament_length(), is_first_layer(), Slic3r::WipeTower::box_coordinates::ld, m_current_shape, m_current_tool, m_depth_traversed, m_extrusion_flow, m_filpar, m_gcode_flavor, m_internal_rotation, m_layer_height, m_layer_info, m_num_tool_changes, m_perimeter_width, m_travel_speed, m_used_filament_length, m_wipe_tower_depth, m_wipe_tower_width, m_y_shift, m_z_pos, Slic3r::WipeTowerWriter::rectangle(), Slic3r::WipeTowerWriter::reset_extruder(), Slic3r::WipeTowerWriter::set_extrusion_flow(), Slic3r::WipeTowerWriter::set_initial_position(), Slic3r::WipeTowerWriter::set_initial_tool(), Slic3r::WipeTowerWriter::set_y_shift(), Slic3r::WipeTowerWriter::set_z(), SHAPE_REVERSED, Slic3r::WipeTowerWriter::speed_override(), Slic3r::WipeTowerWriter::speed_override_backup(), Slic3r::WipeTowerWriter::speed_override_restore(), toolchange_Change(), toolchange_Load(), toolchange_Unload(), toolchange_Wipe(), and Slic3r::WipeTowerWriter::travel().
Referenced by generate(), and save_on_last_wipe().
toolchange_Change()
void Slic3r::WipeTower::toolchange_Change (WipeTowerWriter & writer, const size_t new_tool, const std::string & new_material) private
{
    // Ask the writer about how much of the old filament we consumed:
    if (m_current_tool < m_used_filament_length.size())
      m_used_filament_length[m_current_tool] += writer.get_and_reset_used_filament_length();
    // This is where we want to place the custom gcodes. We will use placeholders for this.
    // These will be substituted by the actual gcodes when the gcode is generated.
    writer.append("[filament_end_gcode]\n");
    writer.append("[change_filament_gcode]\n");
    // BBS: do travel in GCode::append_tcr() for lazy_lift
#if 0
    // Travel to where we assume we are. Custom toolchange or some special T code handling (parking extruder etc)
    // gcode could have left the extruder somewhere, we cannot just start extruding. We should also inform the
    // postprocessor that we absolutely want to have this in the gcode, even if it thought it is the same as before.
    Vec2f current_pos = writer.pos_rotated();
    writer.feedrate(m_travel_speed * 60.f)
          .append(std::string("G1 X") + Slic3r::float_to_string_decimal_point(current_pos.x())
                             +  " Y"  + Slic3r::float_to_string_decimal_point(current_pos.y())
                             + never_skip_tag() + "\n");
#endif
    // The toolchange Tn command will be inserted later, only in case that the user does
    // not provide a custom toolchange gcode.
  writer.set_tool(new_tool); // This outputs nothing, the writer just needs to know the tool has changed.
    writer.append("[filament_start_gcode]\n");
  writer.flush_planner_queue();
  m_current_tool = new_tool;
}
References Slic3r::WipeTowerWriter::append(), Slic3r::WipeTowerWriter::feedrate(), Slic3r::float_to_string_decimal_point(), Slic3r::WipeTowerWriter::flush_planner_queue(), Slic3r::WipeTowerWriter::get_and_reset_used_filament_length(), m_current_tool, m_travel_speed, m_used_filament_length, never_skip_tag(), Slic3r::WipeTowerWriter::pos_rotated(), and Slic3r::WipeTowerWriter::set_tool().
Referenced by tool_change().
toolchange_Load()
void Slic3r::WipeTower::toolchange_Load (WipeTowerWriter & writer, const box_coordinates & cleaning_box) private
{
    // BBS: tool load is done in change_filament_gcode
#if 0
    if (m_semm && (m_parking_pos_retraction != 0 || m_extra_loading_move != 0)) {
        float xl = cleaning_box.ld.x() + m_perimeter_width * 0.75f;
        float xr = cleaning_box.rd.x() - m_perimeter_width * 0.75f;
        float oldx = writer.x();  // the nozzle is in place to do the first wiping moves, we will remember the position
        // Load the filament while moving left / right, so the excess material will not create a blob at a single position.
        float turning_point = ( oldx-xl < xr-oldx ? xr : xl );
        float edist = m_parking_pos_retraction+m_extra_loading_move;
        writer.append("; CP TOOLCHANGE LOAD\n")
              .suppress_preview()
              .load(0.2f * edist, 60.f * m_filpar[m_current_tool].loading_speed_start)
              .load_move_x_advanced(turning_point, 0.7f * edist,        m_filpar[m_current_tool].loading_speed)  // Fast phase
              .load_move_x_advanced(oldx,          0.1f * edist, 0.1f * m_filpar[m_current_tool].loading_speed)  // Super slow*/
              .travel(oldx, writer.y()) // in case last move was shortened to limit x feedrate
              .resume_preview();
        // Reset the extruder current to the normal value.
        if (m_set_extruder_trimpot)
            writer.set_extruder_trimpot(550);
    }
#endif
}
References Slic3r::WipeTowerWriter::append(), Slic3r::WipeTower::box_coordinates::ld, Slic3r::WipeTowerWriter::load(), Slic3r::WipeTowerWriter::load_move_x_advanced(), m_current_tool, m_filpar, m_perimeter_width, m_semm, Slic3r::WipeTower::box_coordinates::rd, Slic3r::WipeTowerWriter::set_extruder_trimpot(), Slic3r::WipeTowerWriter::suppress_preview(), Slic3r::WipeTowerWriter::travel(), Slic3r::WipeTowerWriter::x(), and Slic3r::WipeTowerWriter::y().
Referenced by tool_change().
toolchange_Unload()
void Slic3r::WipeTower::toolchange_Unload (WipeTowerWriter & writer, const box_coordinates & cleaning_box, const std::string & current_material, const int new_temperature) private
{
    // BBS: toolchange unload is done in change_filament_gcode
#if 0
  float xl = cleaning_box.ld.x() + 1.f * m_perimeter_width;
  float xr = cleaning_box.rd.x() - 1.f * m_perimeter_width;
  const float line_width = m_perimeter_width * m_filpar[m_current_tool].ramming_line_width_multiplicator;       // desired ramming line thickness
  const float y_step = line_width * m_filpar[m_current_tool].ramming_step_multiplicator * m_extra_spacing; // spacing between lines in mm
    writer.append("; CP TOOLCHANGE UNLOAD\n")
        .change_analyzer_line_width(line_width);
  unsigned i = 0;                   // iterates through ramming_speed
  m_left_to_right = true;               // current direction of ramming
  float remaining = xr - xl ;             // keeps track of distance to the next turnaround
  float e_done = 0;                 // measures E move done from each segment
  writer.travel(xl, cleaning_box.ld.y() + m_depth_traversed + y_step/2.f ); // move to starting position
    // if the ending point of the ram would end up in mid air, align it with the end of the wipe tower:
    if (m_layer_info > m_plan.begin() && m_layer_info < m_plan.end() && (m_layer_info-1!=m_plan.begin() || !m_adhesion )) {
        // this is y of the center of previous sparse infill border
        float sparse_beginning_y = 0.f;
        if (m_current_shape == SHAPE_REVERSED)
            sparse_beginning_y += ((m_layer_info-1)->depth - (m_layer_info-1)->toolchanges_depth())
                                      - ((m_layer_info)->depth-(m_layer_info)->toolchanges_depth()) ;
        else
            sparse_beginning_y += (m_layer_info-1)->toolchanges_depth() + m_perimeter_width;
        float sum_of_depths = 0.f;
        for (const auto& tch : m_layer_info->tool_changes) {  // let's find this toolchange
            if (tch.old_tool == m_current_tool) {
                sum_of_depths += tch.ramming_depth;
                float ramming_end_y = sum_of_depths;
                ramming_end_y -= (y_step/m_extra_spacing-m_perimeter_width) / 2.f;   // center of final ramming line
                if ( (m_current_shape == SHAPE_REVERSED   && ramming_end_y < sparse_beginning_y - 0.5f*m_perimeter_width  ) ||
                     (m_current_shape == SHAPE_NORMAL && ramming_end_y > sparse_beginning_y + 0.5f*m_perimeter_width  )  )
                {
                    writer.extrude(xl + tch.first_wipe_line-1.f*m_perimeter_width,writer.y());
                    remaining -= tch.first_wipe_line-1.f*m_perimeter_width;
                }
                break;
            }
            sum_of_depths += tch.required_depth;
        }
    }
    writer.disable_linear_advance();
    // now the ramming itself:
    while (i < m_filpar[m_current_tool].ramming_speed.size())
    {
        const float x = volume_to_length(m_filpar[m_current_tool].ramming_speed[i] * 0.25f, line_width, m_layer_height);
        const float e = m_filpar[m_current_tool].ramming_speed[i] * 0.25f / filament_area(); // transform volume per sec to E move;
        const float dist = std::min(x - e_done, remaining);     // distance to travel for either the next 0.25s, or to the next turnaround
        const float actual_time = dist/x * 0.25f;
        writer.ram(writer.x(), writer.x() + (m_left_to_right ? 1.f : -1.f) * dist, 0.f, 0.f, e * (dist / x), dist / (actual_time / 60.f));
        remaining -= dist;
    if (remaining < WT_EPSILON) { // we reached a turning point
      writer.travel(writer.x(), writer.y() + y_step, 7200);
      m_left_to_right = !m_left_to_right;
      remaining = xr - xl;
    }
    e_done += dist; // subtract what was actually done
    if (e_done > x - WT_EPSILON) { // current segment finished
      ++i;
      e_done = 0;
    }
  }
  Vec2f end_of_ramming(writer.x(),writer.y());
    writer.change_analyzer_line_width(m_perimeter_width);   // so the next lines are not affected by ramming_line_width_multiplier
    // Retraction:
    float old_x = writer.x();
    float turning_point = (!m_left_to_right ? xl : xr );
    if (m_semm && (m_cooling_tube_retraction != 0 || m_cooling_tube_length != 0)) {
        float total_retraction_distance = m_cooling_tube_retraction + m_cooling_tube_length/2.f - 15.f; // the 15mm is reserved for the first part after ramming
        writer.suppress_preview()
              .retract(15.f, m_filpar[m_current_tool].unloading_speed_start * 60.f) // feedrate 5000mm/min = 83mm/s
              .retract(0.70f * total_retraction_distance, 1.0f * m_filpar[m_current_tool].unloading_speed * 60.f)
              .retract(0.20f * total_retraction_distance, 0.5f * m_filpar[m_current_tool].unloading_speed * 60.f)
              .retract(0.10f * total_retraction_distance, 0.3f * m_filpar[m_current_tool].unloading_speed * 60.f)
              .resume_preview();
    }
    // Wipe tower should only change temperature with single extruder MM. Otherwise, all temperatures should
    // be already set and there is no need to change anything. Also, the temperature could be changed
    // for wrong extruder.
    if (m_semm) {
        if (new_temperature != 0 && (new_temperature != m_old_temperature || is_first_layer()) ) {  // Set the extruder temperature, but don't wait.
            // If the required temperature is the same as last time, don't emit the M104 again (if user adjusted the value, it would be reset)
            // However, always change temperatures on the first layer (this is to avoid issues with priming lines turned off).
            writer.set_extruder_temp(new_temperature, false);
            m_old_temperature = new_temperature;
        }
    }
    // Cooling:
    const int& number_of_moves = m_filpar[m_current_tool].cooling_moves;
    if (number_of_moves > 0) {
        const float& initial_speed = m_filpar[m_current_tool].cooling_initial_speed;
        const float& final_speed   = m_filpar[m_current_tool].cooling_final_speed;
        float speed_inc = (final_speed - initial_speed) / (2.f * number_of_moves - 1.f);
        writer.suppress_preview()
              .travel(writer.x(), writer.y() + y_step);
        old_x = writer.x();
        turning_point = xr-old_x > old_x-xl ? xr : xl;
        for (int i=0; i<number_of_moves; ++i) {
            float speed = initial_speed + speed_inc * 2*i;
            writer.load_move_x_advanced(turning_point, m_cooling_tube_length, speed);
            speed += speed_inc;
            writer.load_move_x_advanced(old_x, -m_cooling_tube_length, speed);
        }
    }
    // let's wait is necessary:
    writer.wait(m_filpar[m_current_tool].delay);
    // we should be at the beginning of the cooling tube again - let's move to parking position:
    writer.retract(-m_cooling_tube_length/2.f+m_parking_pos_retraction-m_cooling_tube_retraction, 2000);
  // this is to align ramming and future wiping extrusions, so the future y-steps can be uniform from the start:
    // the perimeter_width will later be subtracted, it is there to not load while moving over just extruded material
  writer.travel(end_of_ramming.x(), end_of_ramming.y() + (y_step/m_extra_spacing-m_perimeter_width) / 2.f + m_perimeter_width, 2400.f);
  writer.resume_preview()
      .flush_planner_queue();
#endif
}
References Slic3r::WipeTowerWriter::append(), Slic3r::WipeTowerWriter::change_analyzer_line_width(), Slic3r::WipeTowerWriter::disable_linear_advance(), Slic3r::WipeTowerWriter::extrude(), filament_area(), Slic3r::WipeTowerWriter::flush_planner_queue(), is_first_layer(), Slic3r::WipeTower::box_coordinates::ld, Slic3r::WipeTowerWriter::load_move_x_advanced(), m_adhesion, m_current_shape, m_current_tool, m_depth_traversed, m_extra_spacing, m_filpar, m_layer_height, m_layer_info, m_left_to_right, m_old_temperature, m_perimeter_width, m_plan, m_semm, Slic3r::WipeTowerWriter::ram(), Slic3r::WipeTower::box_coordinates::rd, Slic3r::WipeTowerWriter::resume_preview(), Slic3r::WipeTowerWriter::retract(), Slic3r::WipeTowerWriter::set_extruder_temp(), SHAPE_NORMAL, SHAPE_REVERSED, Slic3r::WipeTowerWriter::suppress_preview(), Slic3r::WipeTowerWriter::travel(), volume_to_length(), Slic3r::WipeTowerWriter::wait(), WT_EPSILON, Slic3r::WipeTowerWriter::x(), and Slic3r::WipeTowerWriter::y().
Referenced by tool_change().
toolchange_Wipe()
void Slic3r::WipeTower::toolchange_Wipe (WipeTowerWriter & writer, const box_coordinates & cleaning_box, float wipe_volume) private
{
  // Increase flow on first layer, slow down print.
    writer.set_extrusion_flow(m_extrusion_flow * (is_first_layer() ? 1.15f : 1.f))
      .append("; CP TOOLCHANGE WIPE\n");
    // BBS: add the note for gcode-check, when the flow changed, the width should follow the change
    if (is_first_layer()) {
        writer.append(";" + GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Width) + std::to_string(1.15 * m_perimeter_width) + "\n");
    }
  const float& xl = cleaning_box.ld.x();
  const float& xr = cleaning_box.rd.x();
  // Variables x_to_wipe and traversed_x are here to be able to make sure it always wipes at least
    //   the ordered volume, even if it means violating the box. This can later be removed and simply
    // wipe until the end of the assigned area.
    float x_to_wipe = wipe_length;
    float dy = m_layer_info->extra_spacing * m_perimeter_width;
    const float target_speed = is_first_layer() ? std::min(m_first_layer_speed * 60.f, 4800.f) : 4800.f;
    float wipe_speed = 0.33f * target_speed;
    float start_y = writer.y();
#if 0
    // if there is less than 2.5*m_perimeter_width to the edge, advance straightaway (there is likely a blob anyway)
    if ((m_left_to_right ? xr-writer.x() : writer.x()-xl) < 2.5f*m_perimeter_width) {
        writer.travel((m_left_to_right ? xr-m_perimeter_width : xl+m_perimeter_width),writer.y()+dy);
        m_left_to_right = !m_left_to_right;
    }
#endif
    m_left_to_right = true;
    // BBS: do not need to move dy
#if 0
    if (m_depth_traversed != 0)
        writer.travel(xl, writer.y() + dy);
#endif
    bool need_change_flow = false;
    // now the wiping itself:
  for (int i = 0; true; ++i)  {
    if (i!=0) {
            if      (wipe_speed < 0.34f * target_speed) wipe_speed = 0.375f * target_speed;
            else if (wipe_speed < 0.377 * target_speed) wipe_speed = 0.458f * target_speed;
            else if (wipe_speed < 0.46f * target_speed) wipe_speed = 0.875f * target_speed;
            else wipe_speed = std::min(target_speed, wipe_speed + 50.f);
    }
        // BBS: check the bridging area and use the bridge flow
        if (need_change_flow || need_thick_bridge_flow(writer.y())) {
            writer.set_extrusion_flow(extrusion_flow(0.2));
            writer.append(";" + GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Height) + std::to_string(0.2) + "\n");
            need_change_flow = true;
        }
        if (m_left_to_right)
            writer.extrude(xr + 0.25f * m_perimeter_width, writer.y(), wipe_speed);
        else
            writer.extrude(xl - 0.25f * m_perimeter_width, writer.y(), wipe_speed);
        // BBS: recover the flow in non-bridging area
        if (need_change_flow) {
            writer.set_extrusion_flow(m_extrusion_flow);
            writer.append(";" + GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Height) + std::to_string(m_layer_height) + "\n");
        }
        if (writer.y() - float(EPSILON) > cleaning_box.lu.y())
            break;    // in case next line would not fit
        x_to_wipe -= (xr - xl);
    if (x_to_wipe < WT_EPSILON) {
            // BBS: Delete some unnecessary travel
            //writer.travel(m_left_to_right ? xl + 1.5f*m_perimeter_width : xr - 1.5f*m_perimeter_width, writer.y(), 7200);
      break;
    }
    // stepping to the next line:
        writer.extrude(writer.x(), writer.y() + dy);
    m_left_to_right = !m_left_to_right;
  }
    float end_y = writer.y();
    // We may be going back to the model - wipe the nozzle. If this is followed
    // by finish_layer, this wipe path will be overwritten.
    //writer.add_wipe_point(writer.x(), writer.y())
    //      .add_wipe_point(writer.x(), writer.y() - dy)
    //      .add_wipe_point(! m_left_to_right ? m_wipe_tower_width : 0.f, writer.y() - dy);
    // BBS: modify the wipe_path after toolchange
    writer.add_wipe_point(writer.x(), writer.y())
          .add_wipe_point(! m_left_to_right ? m_wipe_tower_width : 0.f, writer.y());
    if (m_layer_info != m_plan.end() && m_current_tool != m_layer_info->tool_changes.back().new_tool)
        m_left_to_right = !m_left_to_right;
    writer.set_extrusion_flow(m_extrusion_flow); // Reset the extrusion flow.
    // BBS: add the note for gcode-check when the flow changed
    if (is_first_layer()) {
        writer.append(";" + GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Width) + std::to_string(m_perimeter_width) + "\n");
    }
}
References Slic3r::WipeTowerWriter::add_wipe_point(), Slic3r::WipeTowerWriter::append(), EPSILON, Slic3r::WipeTowerWriter::extrude(), extrusion_flow(), Slic3r::GCodeProcessor::Height, is_first_layer(), Slic3r::WipeTower::box_coordinates::ld, Slic3r::WipeTower::box_coordinates::lu, m_current_tool, m_depth_traversed, m_extrusion_flow, m_first_layer_speed, m_layer_height, m_layer_info, m_left_to_right, m_perimeter_width, m_plan, m_wipe_tower_width, need_thick_bridge_flow(), Slic3r::WipeTower::box_coordinates::rd, Slic3r::GCodeProcessor::reserved_tag(), Slic3r::WipeTowerWriter::set_extrusion_flow(), Slic3r::WipeTowerWriter::travel(), Slic3r::GCodeProcessor::Width, Slic3r::wipe_speed(), WT_EPSILON, Slic3r::WipeTowerWriter::x(), and Slic3r::WipeTowerWriter::y().
Referenced by tool_change().
volume_to_length()
float Slic3r::WipeTower::volume_to_length (float volume, float line_width, float layer_height) const inline private
{
    return std::max(0.f, volume / (layer_height * (line_width - layer_height * (1.f - float(M_PI) / 4.f))));
  }
References Slic3r::layer_height(), and M_PI.
Referenced by plan_toolchange(), plan_tower(), save_on_last_wipe(), and toolchange_Unload().
width()
float Slic3r::WipeTower::width () const inline
{ return m_wipe_tower_width; }
References m_wipe_tower_width.
Referenced by plan_toolchange(), and save_on_last_wipe().
Member Data Documentation
m_adhesion
bool Slic3r::WipeTower::m_adhesion = true private
Referenced by finish_layer(), and toolchange_Unload().
m_bed_bottom_left
Vec2f Slic3r::WipeTower::m_bed_bottom_left private
Referenced by WipeTower().
[]
enum { ... } Slic3r::WipeTower::m_bed_shape
Referenced by WipeTower().
m_bed_width
float Slic3r::WipeTower::m_bed_width private
Referenced by WipeTower().
m_bridging
float Slic3r::WipeTower::m_bridging = 0.f private
Referenced by finish_layer().
m_current_layer_finished
bool Slic3r::WipeTower::m_current_layer_finished = false private
Referenced by finish_layer(), layer_finished(), and set_layer().
m_current_shape
wipe_shape Slic3r::WipeTower::m_current_shape = SHAPE_NORMAL private
Referenced by finish_layer(), only_generate_out_wall(), set_layer(), tool_change(), and toolchange_Unload().
m_current_tool
size_t Slic3r::WipeTower::m_current_tool = 0 private
Referenced by construct_tcr(), finish_layer(), generate(), only_generate_out_wall(), tool_change(), toolchange_Change(), toolchange_Load(), toolchange_Unload(), and toolchange_Wipe().
m_depth_traversed
float Slic3r::WipeTower::m_depth_traversed = 0.f private
Referenced by set_layer(), tool_change(), toolchange_Unload(), and toolchange_Wipe().
m_enable_timelapse_print
bool Slic3r::WipeTower::m_enable_timelapse_print = false private
Referenced by generate(), and plan_tower().
m_extra_spacing
float Slic3r::WipeTower::m_extra_spacing = 1.f private
Referenced by align_perimeter(), generate(), plan_toolchange(), plan_tower(), save_on_last_wipe(), and toolchange_Unload().
m_extrusion_flow
float Slic3r::WipeTower::m_extrusion_flow = 0.038f private
Referenced by extrusion_flow(), finish_layer(), get_extrusion_flow(), need_thick_bridge_flow(), only_generate_out_wall(), set_layer(), tool_change(), and toolchange_Wipe().
m_filpar
std::vector<FilamentParameters> Slic3r::WipeTower::m_filpar private
Referenced by filament_area(), finish_layer(), first_toolchange_to_nonsoluble_nonsupport(), only_generate_out_wall(), plan_toolchange(), set_extruder(), tool_change(), toolchange_Load(), and toolchange_Unload().
m_first_layer_idx
size_t Slic3r::WipeTower::m_first_layer_idx = size_t(-1) private
Referenced by finish_layer(), is_first_layer(), and plan_toolchange().
m_first_layer_speed
float Slic3r::WipeTower::m_first_layer_speed = 0.f private
Referenced by WipeTower(), finish_layer(), only_generate_out_wall(), and toolchange_Wipe().
m_gcode_flavor
GCodeFlavor Slic3r::WipeTower::m_gcode_flavor private
Referenced by finish_layer(), only_generate_out_wall(), and tool_change().
m_internal_rotation
float Slic3r::WipeTower::m_internal_rotation = 0.f private
Referenced by finish_layer(), only_generate_out_wall(), and tool_change().
m_layer_height
float Slic3r::WipeTower::m_layer_height = 0.f private
Referenced by construct_tcr(), finish_layer(), get_layer_height(), only_generate_out_wall(), set_layer(), tool_change(), toolchange_Unload(), and toolchange_Wipe().
m_layer_info
std::vector<WipeTowerInfo>::iterator Slic3r::WipeTower::m_layer_info = m_plan.end() private
Referenced by finish_layer(), generate(), get_floating_area(), is_first_layer(), only_generate_out_wall(), save_on_last_wipe(), set_layer(), tool_change(), toolchange_Unload(), and toolchange_Wipe().
m_left_to_right
bool Slic3r::WipeTower::m_left_to_right = true private
Referenced by finish_layer(), only_generate_out_wall(), toolchange_Unload(), and toolchange_Wipe().
m_max_color_changes
size_t Slic3r::WipeTower::m_max_color_changes = 0 private
Referenced by finished().
m_no_sparse_layers
bool Slic3r::WipeTower::m_no_sparse_layers = false private
Referenced by finish_layer(), only_generate_out_wall(), and plan_toolchange().
m_num_layer_changes
unsigned int Slic3r::WipeTower::m_num_layer_changes = 0 private
Referenced by finish_layer(), and set_layer().
m_num_tool_changes
unsigned int Slic3r::WipeTower::m_num_tool_changes = 0 private
Referenced by get_number_of_toolchanges(), set_layer(), and tool_change().
m_old_temperature
int Slic3r::WipeTower::m_old_temperature = -1 private
Referenced by generate(), and toolchange_Unload().
m_perimeter_width
float Slic3r::WipeTower::m_perimeter_width = 0.4f * Width_To_Nozzle_Ratio private
Referenced by align_perimeter(), extrusion_flow(), finish_layer(), generate(), get_floating_area(), only_generate_out_wall(), plan_toolchange(), plan_tower(), save_on_last_wipe(), set_extruder(), tool_change(), toolchange_Load(), toolchange_Unload(), and toolchange_Wipe().
m_plan
std::vector<WipeTowerInfo> Slic3r::WipeTower::m_plan private
Referenced by finish_layer(), generate(), get_floating_area(), is_first_layer(), plan_toolchange(), plan_tower(), save_on_last_wipe(), set_last_layer_extruder_fill(), set_layer(), toolchange_Unload(), and toolchange_Wipe().
m_print_brim
bool Slic3r::WipeTower::m_print_brim = true private
unsigned int m_idx_tool_change_in_layer = 0; // Layer change counter in this layer. Counting up to m_max_color_changes.
m_semm
bool Slic3r::WipeTower::m_semm = true private
Referenced by WipeTower(), set_extruder(), toolchange_Load(), and toolchange_Unload().
m_travel_speed
float Slic3r::WipeTower::m_travel_speed = 0.f private
Referenced by tool_change(), and toolchange_Change().
m_used_filament_length
std::vector<float> Slic3r::WipeTower::m_used_filament_length private
Referenced by finish_layer(), generate(), get_used_filament(), only_generate_out_wall(), set_extruder(), tool_change(), and toolchange_Change().
m_wipe_tower_brim_width
float Slic3r::WipeTower::m_wipe_tower_brim_width = 0.f private
Referenced by finish_layer().
m_wipe_tower_brim_width_real
float Slic3r::WipeTower::m_wipe_tower_brim_width_real = 0.f private
Referenced by finish_layer(), and get_brim_width().
m_wipe_tower_depth
float Slic3r::WipeTower::m_wipe_tower_depth = 0.f private
Referenced by align_perimeter(), finish_layer(), generate(), get_depth(), only_generate_out_wall(), plan_tower(), and tool_change().
m_wipe_tower_height
float Slic3r::WipeTower::m_wipe_tower_height = 0.f private
Referenced by get_height(), and plan_tower().
m_wipe_tower_pos
Vec2f Slic3r::WipeTower::m_wipe_tower_pos private
Referenced by position().
m_wipe_tower_rotation_angle
float Slic3r::WipeTower::m_wipe_tower_rotation_angle = 0.f private
m_wipe_tower_width
float Slic3r::WipeTower::m_wipe_tower_width private
Referenced by finish_layer(), only_generate_out_wall(), plan_toolchange(), plan_tower(), save_on_last_wipe(), tool_change(), toolchange_Wipe(), and width().
m_wipe_volume
const float Slic3r::WipeTower::m_wipe_volume private
m_y_shift
float Slic3r::WipeTower::m_y_shift = 0.f private
Referenced by align_perimeter(), finish_layer(), generate(), only_generate_out_wall(), and tool_change().
m_z_pos
float Slic3r::WipeTower::m_z_pos = 0.f private
Referenced by construct_tcr(), finish_layer(), only_generate_out_wall(), set_layer(), and tool_change().
min_depth_per_height
const std::map< float, float > Slic3r::WipeTower::min_depth_per_height static
Initial value:
= {
    {100.f, 20.f}, {250.f, 40.f}
}
Referenced by Slic3r::GUI::PartPlate::estimate_wipe_tower_size(), and plan_tower().
Width_To_Nozzle_Ratio
const float Slic3r::WipeTower::Width_To_Nozzle_Ratio = 1.25f private
Referenced by set_extruder().
WT_EPSILON
const float Slic3r::WipeTower::WT_EPSILON = 1e-3f private
Referenced by finish_layer(), only_generate_out_wall(), plan_toolchange(), plan_tower(), set_layer(), toolchange_Unload(), and toolchange_Wipe().
The documentation for this class was generated from the following files:
src/libslic3r/GCode/WipeTower.hpp
src/libslic3r/GCode/WipeTower.cpp