OrcaSlicer: Slic3r::GUI::AmsCans Class Reference
Slic3r::GUI::AmsCans Class Reference
#include <src/slic3r/GUI/Widgets/AMSControl.hpp>
Public Member Functions
AmsCans ()
AmsCans (wxWindow *parent, wxWindowID id, AMSinfo info, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
void Update (AMSinfo info)
void create (wxWindow *parent, wxWindowID id, AMSinfo info, const wxPoint &pos, const wxSize &size)
void AddCan (Caninfo caninfo, int canindex, int maxcan)
void SetDefSelectCan ()
void SelectCan (std::string canid)
wxColour GetTagColr (wxString canid)
void SetAmsStep (wxString canid, AMSPassRoadType type, AMSPassRoadSTEP step)
void PlayRridLoading (wxString canid)
void StopRridLoading (wxString canid)
void msw_rescale ()
void show_sn_value (bool show)
std::string GetCurrentCan ()
Public Attributes
std::string m_canlib_id
int m_canlib_selection = {-1}
int m_selection = {0}
int m_can_count = {0}
CanLibsHash m_can_lib_list
CansRoadsHash m_can_road_list
CanrefreshsHash m_can_refresh_list
AMSinfo m_info
wxBoxSizer * sizer_can = {nullptr}
AMSPassRoadSTEP m_step = {AMSPassRoadSTEP ::AMS_ROAD_STEP_NONE}
Detailed Description
Constructor & Destructor Documentation
AmsCans() [1/2]
Slic3r::GUI::AmsCans::AmsCans ()
{}
AmsCans() [2/2]
Slic3r::GUI::AmsCans::AmsCans (wxWindow * parent, wxWindowID id, AMSinfo info, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
                                                                                                      : AmsCans()
{
    wxWindow::Create(parent, wxID_ANY, pos, AMS_CANS_WINDOW_SIZE);
    create(parent, id, info, pos, size);
}
References AMS_CANS_WINDOW_SIZE, create(), and size.
Member Function Documentation
AddCan()
void Slic3r::GUI::AmsCans::AddCan (Caninfo caninfo, int canindex, int maxcan)
{
    auto        amscan      = new wxWindow(this, wxID_ANY);
    amscan->SetBackgroundColour(AMS_CONTROL_DEF_BLOCK_BK_COLOUR);
    wxBoxSizer *m_sizer_ams = new wxBoxSizer(wxVERTICAL);
    m_sizer_ams->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(14));
    auto m_panel_refresh = new AMSrefresh(amscan, wxID_ANY, m_can_count, caninfo);
    m_sizer_ams->Add(m_panel_refresh, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    m_sizer_ams->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(2));
    auto m_panel_lib = new AMSLib(amscan, wxID_ANY, caninfo);
    m_panel_lib->Bind(wxEVT_LEFT_DOWN, [this, canindex](wxMouseEvent &ev) {
        m_canlib_selection = canindex;
        // m_canlib_id        = caninfo.can_id;
        for (auto i = 0; i < m_can_lib_list.GetCount(); i++) {
            CanLibs *lib = m_can_lib_list[i];
            if (lib->canLib->m_can_index == m_canlib_selection) {
                wxCommandEvent evt(EVT_AMS_UNSELETED_VAMS);
                evt.SetString(m_info.ams_id);
                wxPostEvent(GetParent()->GetParent(), evt);
                lib->canLib->OnSelected();
            } else {
                lib->canLib->UnSelected();
            }
        }
        ev.Skip();
    });
    m_panel_lib->m_info.can_id = caninfo.can_id;
    m_panel_lib->m_can_index   = canindex;
    auto m_panel_road          = new AMSRoad(amscan, wxID_ANY, caninfo, canindex, maxcan, wxDefaultPosition, AMS_CAN_ROAD_SIZE);
    m_sizer_ams->Add(m_panel_lib, 1, wxEXPAND | wxTOP | wxLEFT | wxRIGHT, FromDIP(4));
    m_sizer_ams->Add(m_panel_road, 0, wxALL, 0);
    amscan->SetSizer(m_sizer_ams);
    amscan->Layout();
    amscan->Fit();
    sizer_can->Add(amscan, 0, wxALL, 0);
    Canrefreshs *canrefresh = new Canrefreshs;
    canrefresh->canID       = caninfo.can_id;
    canrefresh->canrefresh  = m_panel_refresh;
    m_can_refresh_list.Add(canrefresh);
    CanLibs *canlib = new CanLibs;
    canlib->canID   = caninfo.can_id;
    canlib->canLib  = m_panel_lib;
    m_can_lib_list.Add(canlib);
    CanRoads *canroad = new CanRoads;
    canroad->canID    = caninfo.can_id;
    canroad->canRoad  = m_panel_road;
    m_can_road_list.Add(canroad);
}
References AMS_CAN_ROAD_SIZE, AMS_CONTROL_DEF_BLOCK_BK_COLOUR, Slic3r::GUI::Caninfo::can_id, Slic3r::GUI::Canrefreshs::canID, Slic3r::GUI::CanLibs::canID, Slic3r::GUI::CanRoads::canID, Slic3r::GUI::CanLibs::canLib, Slic3r::GUI::Canrefreshs::canrefresh, Slic3r::GUI::CanRoads::canRoad, m_can_count, Slic3r::GUI::AMSLib::m_can_index, m_can_lib_list, m_can_refresh_list, m_can_road_list, m_canlib_selection, sizer_can, and Slic3r::GUI::wxMouseEvent.
Referenced by create().
create()
void Slic3r::GUI::AmsCans::create (wxWindow * parent, wxWindowID id, AMSinfo info, const wxPoint & pos, const wxSize & size)
{
    sizer_can = new wxBoxSizer(wxHORIZONTAL);
    m_info    = info;
    Freeze();
    for (auto it = m_info.cans.begin(); it != m_info.cans.end(); it++) {
        AddCan(*it, m_can_count, m_info.cans.size());
        m_can_count++;
    }
    SetSizer(sizer_can);
    Layout();
    Fit();
    Thaw();
}
References AddCan(), Slic3r::GUI::AMSinfo::cans, m_can_count, m_info, and sizer_can.
Referenced by AmsCans().
GetCurrentCan()
std::string Slic3r::GUI::AmsCans::GetCurrentCan ()
{
    if (m_canlib_selection < 0)
        return "";
    return wxString::Format("%d", m_canlib_selection).ToStdString();
}
References m_canlib_selection.
Referenced by Slic3r::GUI::AMSControl::GetCurrentCan().
GetTagColr()
wxColour Slic3r::GUI::AmsCans::GetTagColr (wxString canid)
{
    auto tag_colour = *wxWHITE;
    for (auto i = 0; i < m_can_lib_list.GetCount(); i++) {
        CanLibs* lib = m_can_lib_list[i];
        if (canid == lib->canLib->m_info.can_id) tag_colour = lib->canLib->GetLibColour();
    }
    return tag_colour;
}
References Slic3r::GUI::Caninfo::can_id, Slic3r::GUI::CanLibs::canLib, Slic3r::GUI::AMSLib::GetLibColour(), m_can_lib_list, and Slic3r::GUI::AMSLib::m_info.
Referenced by Slic3r::GUI::AMSControl::SetAmsStep().
msw_rescale()
void Slic3r::GUI::AmsCans::msw_rescale ()
{
    for (auto i = 0; i < m_can_refresh_list.GetCount(); i++) {
        Canrefreshs *refresh = m_can_refresh_list[i];
        refresh->canrefresh->msw_rescale();
    }
}
References Slic3r::GUI::Canrefreshs::canrefresh, m_can_refresh_list, and Slic3r::GUI::AMSrefresh::msw_rescale().
Referenced by Slic3r::GUI::AMSControl::msw_rescale().
PlayRridLoading()
void Slic3r::GUI::AmsCans::PlayRridLoading (wxString canid)
{
    for (auto i = 0; i < m_can_refresh_list.GetCount(); i++) {
        Canrefreshs *refresh = m_can_refresh_list[i];
        if (refresh->canrefresh->m_info.can_id == canid) { refresh->canrefresh->PlayLoading(); }
    }
}
References Slic3r::GUI::Caninfo::can_id, Slic3r::GUI::Canrefreshs::canrefresh, m_can_refresh_list, Slic3r::GUI::AMSrefresh::m_info, and Slic3r::GUI::AMSrefresh::PlayLoading().
Referenced by Slic3r::GUI::AMSControl::PlayRridLoading().
SelectCan()
void Slic3r::GUI::AmsCans::SelectCan (std::string canid)
{
    for (auto i = 0; i < m_can_lib_list.GetCount(); i++) {
        CanLibs *lib = m_can_lib_list[i];
        if (lib->canLib->m_info.can_id == canid) { m_canlib_selection = lib->canLib->m_can_index; }
    }
    m_canlib_id = canid;
    for (auto i = 0; i < m_can_lib_list.GetCount(); i++) {
        CanLibs *lib = m_can_lib_list[i];
        if (lib->canLib->m_info.can_id == m_canlib_id) {
            wxCommandEvent evt(EVT_AMS_UNSELETED_VAMS);
            evt.SetString(m_info.ams_id);
            wxPostEvent(GetParent()->GetParent(), evt);
            lib->canLib->OnSelected();
        } else {
            lib->canLib->UnSelected();
        }
    }
}
References Slic3r::GUI::AMSinfo::ams_id, Slic3r::GUI::Caninfo::can_id, Slic3r::GUI::CanLibs::canLib, Slic3r::GUI::AMSLib::m_can_index, m_can_lib_list, m_canlib_id, m_canlib_selection, Slic3r::GUI::AMSLib::m_info, m_info, Slic3r::GUI::AMSLib::OnSelected(), and Slic3r::GUI::AMSLib::UnSelected().
Referenced by Slic3r::GUI::AMSControl::AMSControl(), and SetDefSelectCan().
SetAmsStep()
void Slic3r::GUI::AmsCans::SetAmsStep (wxString canid, AMSPassRoadType type, AMSPassRoadSTEP step)
{
    if (step == AMSPassRoadSTEP::AMS_ROAD_STEP_NONE) {
        for (auto i = 0; i < m_can_road_list.GetCount(); i++) {
            CanRoads *road = m_can_road_list[i];
            auto      pr   = std::vector<AMSPassRoadMode>{};
            pr.push_back(AMSPassRoadMode::AMS_ROAD_MODE_NONE);
            road->canRoad->OnPassRoad(pr);
        }
        return;
    }
    auto tag_can_index = -1;
    for (auto i = 0; i < m_can_road_list.GetCount(); i++) {
        CanRoads *road = m_can_road_list[i];
        if (canid == road->canRoad->m_info.can_id) { tag_can_index = road->canRoad->m_canindex; }
    }
    if (tag_can_index == -1) return;
    // get colour
    auto tag_colour = *wxWHITE;
    for (auto i = 0; i < m_can_lib_list.GetCount(); i++) {
        CanLibs *lib = m_can_lib_list[i];
        if (canid == lib->canLib->m_info.can_id) tag_colour = lib->canLib->GetLibColour();
    }
    // unload
    if (type == AMSPassRoadType::AMS_ROAD_TYPE_UNLOAD) {
        for (auto i = 0; i < m_can_road_list.GetCount(); i++) {
            CanRoads *road = m_can_road_list[i];
            auto index = road->canRoad->m_canindex;
            auto pr    = std::vector<AMSPassRoadMode>{};
            pr.push_back(AMSPassRoadMode::AMS_ROAD_MODE_END_BOTTOM);
            if (step == AMSPassRoadSTEP::AMS_ROAD_STEP_2) { pr.push_back(AMSPassRoadMode::AMS_ROAD_MODE_END_BOTTOM); }
            if (step == AMSPassRoadSTEP::AMS_ROAD_STEP_3) {
                if (index == tag_can_index && index > 0) { pr.push_back(AMSPassRoadMode::AMS_ROAD_MODE_LEFT); }
                if (index < tag_can_index && index > 0) { pr.push_back(AMSPassRoadMode::AMS_ROAD_MODE_LEFT_RIGHT); }
                if (index == 0 && tag_can_index == index) { pr.push_back(AMSPassRoadMode::AMS_ROAD_MODE_END_TOP); }
                if (index == 0 && tag_can_index > index) { pr.push_back(AMSPassRoadMode::AMS_ROAD_MODE_END_RIGHT); }
            }
            road->canRoad->SetPassRoadColour(tag_colour);
            road->canRoad->OnPassRoad(pr);
        }
    }
    // load
    if (type == AMSPassRoadType::AMS_ROAD_TYPE_LOAD) {
        for (auto i = 0; i < m_can_road_list.GetCount(); i++) {
            CanRoads *road = m_can_road_list[i];
            auto index = road->canRoad->m_canindex;
            auto pr    = std::vector<AMSPassRoadMode>{};
            if (index == tag_can_index && index > 0) { pr.push_back(AMSPassRoadMode::AMS_ROAD_MODE_LEFT); }
            if (index < tag_can_index && index > 0) { pr.push_back(AMSPassRoadMode::AMS_ROAD_MODE_LEFT_RIGHT); }
            if (index == 0 && tag_can_index == index) { pr.push_back(AMSPassRoadMode::AMS_ROAD_MODE_END_TOP); }
            if (index == 0 && tag_can_index > index) { pr.push_back(AMSPassRoadMode::AMS_ROAD_MODE_END_RIGHT); }
            if (step == AMSPassRoadSTEP::AMS_ROAD_STEP_2) { pr.push_back(AMSPassRoadMode::AMS_ROAD_MODE_END_BOTTOM); }
            road->canRoad->SetPassRoadColour(tag_colour);
            road->canRoad->OnPassRoad(pr);
        }
    }
}
References Slic3r::GUI::AMS_ROAD_MODE_END_BOTTOM, Slic3r::GUI::AMS_ROAD_MODE_END_RIGHT, Slic3r::GUI::AMS_ROAD_MODE_END_TOP, Slic3r::GUI::AMS_ROAD_MODE_LEFT, Slic3r::GUI::AMS_ROAD_MODE_LEFT_RIGHT, Slic3r::GUI::AMS_ROAD_MODE_NONE, Slic3r::GUI::AMS_ROAD_STEP_2, Slic3r::GUI::AMS_ROAD_STEP_3, Slic3r::GUI::AMS_ROAD_STEP_NONE, Slic3r::GUI::AMS_ROAD_TYPE_LOAD, Slic3r::GUI::AMS_ROAD_TYPE_UNLOAD, Slic3r::GUI::Caninfo::can_id, Slic3r::GUI::CanLibs::canLib, Slic3r::GUI::CanRoads::canRoad, Slic3r::GUI::AMSLib::GetLibColour(), m_can_lib_list, m_can_road_list, Slic3r::GUI::AMSRoad::m_canindex, Slic3r::GUI::AMSLib::m_info, Slic3r::GUI::AMSRoad::m_info, Slic3r::GUI::AMSRoad::OnPassRoad(), and Slic3r::GUI::AMSRoad::SetPassRoadColour().
Referenced by Slic3r::GUI::AMSControl::SetAmsStep().
SetDefSelectCan()
void Slic3r::GUI::AmsCans::SetDefSelectCan ()
{
    if (m_can_lib_list.GetCount() > 0) {
        CanLibs* lib = m_can_lib_list[0];
        m_canlib_selection =lib->canLib->m_can_index;
        m_canlib_id = lib->canLib->m_info.can_id;
        SelectCan(m_canlib_id);
    }
}
References Slic3r::GUI::Caninfo::can_id, Slic3r::GUI::CanLibs::canLib, Slic3r::GUI::AMSLib::m_can_index, m_can_lib_list, m_canlib_id, m_canlib_selection, Slic3r::GUI::AMSLib::m_info, and SelectCan().
Referenced by Slic3r::GUI::AMSControl::SwitchAms().
show_sn_value()
void Slic3r::GUI::AmsCans::show_sn_value (bool show)
{
    for (auto i = 0; i < m_can_lib_list.GetCount(); i++) {
        CanLibs* lib = m_can_lib_list[i];
        lib->canLib->show_kn_value(show);
    }
}
References Slic3r::GUI::CanLibs::canLib, m_can_lib_list, and Slic3r::GUI::AMSLib::show_kn_value().
Referenced by Slic3r::GUI::AMSControl::UpdateAms().
StopRridLoading()
void Slic3r::GUI::AmsCans::StopRridLoading (wxString canid)
{
    for (auto i = 0; i < m_can_refresh_list.GetCount(); i++) {
        Canrefreshs *refresh = m_can_refresh_list[i];
        if (refresh->canrefresh->m_info.can_id == canid) { refresh->canrefresh->StopLoading(); }
    }
}
References Slic3r::GUI::Caninfo::can_id, Slic3r::GUI::Canrefreshs::canrefresh, m_can_refresh_list, Slic3r::GUI::AMSrefresh::m_info, and Slic3r::GUI::AMSrefresh::StopLoading().
Referenced by Slic3r::GUI::AMSControl::StopRridLoading().
Update()
void Slic3r::GUI::AmsCans::Update (AMSinfo info)
{
    m_info      = info;
    m_can_count = info.cans.size();
    for (auto i = 0; i < m_can_refresh_list.GetCount(); i++) {
        Canrefreshs *refresh = m_can_refresh_list[i];
        if (i < m_can_count) {
            refresh->canrefresh->Update(info.ams_id, info.cans[i]);
            refresh->canrefresh->Show();
        } else {
            refresh->canrefresh->Hide();
        }
    }
    for (auto i = 0; i < m_can_lib_list.GetCount(); i++) {
        CanLibs *lib = m_can_lib_list[i];
        if (i < m_can_count) {
            lib->canLib->Update(info.cans[i]);
            lib->canLib->Show();
        } else {
            lib->canLib->Hide();
        }
    }
    for (auto i = 0; i < m_can_road_list.GetCount(); i++) {
        CanRoads *road = m_can_road_list[i];
        if (i < m_can_count) {
            road->canRoad->Update(m_info, info.cans[i], i, m_can_count);
            road->canRoad->Show();
        } else {
            road->canRoad->Hide();
        }
    }
    Layout();
}
References Slic3r::GUI::AMSinfo::ams_id, Slic3r::GUI::CanLibs::canLib, Slic3r::GUI::Canrefreshs::canrefresh, Slic3r::GUI::CanRoads::canRoad, Slic3r::GUI::AMSinfo::cans, m_can_count, m_can_lib_list, m_can_refresh_list, m_can_road_list, m_info, Slic3r::GUI::AMSRoad::Update(), Slic3r::GUI::AMSLib::Update(), and Slic3r::GUI::AMSrefresh::Update().
Referenced by Slic3r::GUI::AMSControl::UpdateAms().
Member Data Documentation
m_can_count
int Slic3r::GUI::AmsCans::m_can_count = {0}
Referenced by AddCan(), create(), and Update().
m_can_lib_list
CanLibsHash Slic3r::GUI::AmsCans::m_can_lib_list
Referenced by AddCan(), GetTagColr(), SelectCan(), SetAmsStep(), SetDefSelectCan(), show_sn_value(), and Update().
m_can_refresh_list
CanrefreshsHash Slic3r::GUI::AmsCans::m_can_refresh_list
Referenced by AddCan(), msw_rescale(), PlayRridLoading(), StopRridLoading(), and Update().
m_can_road_list
CansRoadsHash Slic3r::GUI::AmsCans::m_can_road_list
Referenced by AddCan(), SetAmsStep(), and Update().
m_canlib_id
std::string Slic3r::GUI::AmsCans::m_canlib_id
Referenced by SelectCan(), and SetDefSelectCan().
m_canlib_selection
int Slic3r::GUI::AmsCans::m_canlib_selection = {-1}
Referenced by AddCan(), GetCurrentCan(), SelectCan(), and SetDefSelectCan().
m_info
AMSinfo Slic3r::GUI::AmsCans::m_info
Referenced by create(), Slic3r::GUI::AMSControl::GetCurrentCan(), Slic3r::GUI::AMSControl::PlayRridLoading(), SelectCan(), Slic3r::GUI::AMSControl::SetAmsStep(), Slic3r::GUI::AMSControl::StopRridLoading(), Slic3r::GUI::AMSControl::SwitchAms(), Update(), and Slic3r::GUI::AMSControl::UpdateAms().
m_selection
int Slic3r::GUI::AmsCans::m_selection = {0}
Referenced by Slic3r::GUI::AMSControl::SwitchAms().
m_step
AMSPassRoadSTEP Slic3r::GUI::AmsCans::m_step = {AMSPassRoadSTEP ::AMS_ROAD_STEP_NONE}
sizer_can
wxBoxSizer* Slic3r::GUI::AmsCans::sizer_can = {nullptr}
Referenced by AddCan(), and create().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/AMSControl.hpp
src/slic3r/GUI/Widgets/AMSControl.cpp