OrcaSlicer: FanSwitchButton Class Reference
FanSwitchButton Class Reference
#include <src/slic3r/GUI/Widgets/ImageSwitchButton.hpp>
Public Member Functions
FanSwitchButton (wxWindow *parent, ScalableBitmap &img_on, ScalableBitmap &img_off, long style=0)
void SetLabels (wxString const &lbl_on, wxString const &lbl_off)
void SetImages (ScalableBitmap &img_on, ScalableBitmap &img_off)
void SetTextColor (StateColor const &color)
void SetValue (bool value)
void SetPadding (int padding)
bool GetValue ()
void Rescale ()
void setFanValue (int val)
bool Create (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
void SetCornerRadius (double radius)
void SetBorderWidth (int width)
void SetBorderColor (StateColor const &color)
void SetBorderColorNormal (wxColor const &color)
void SetBackgroundColor (StateColor const &color)
void SetBackgroundColorNormal (wxColor const &color)
void SetBackgroundColor2 (StateColor const &color)
Static Public Member Functions
static wxColor GetParentBackgroundColor (wxWindow *parent)
Protected Member Functions
void eraseEvent (wxEraseEvent &evt)
virtual void doRender (wxDC &dc)
Protected Attributes
double radius
int border_width = 1
StateHandler state_handler
StateColor border_color
StateColor background_color
StateColor background_color2
Private Member Functions
void messureSize ()
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void mouseDown (wxMouseEvent &event)
void mouseReleased (wxMouseEvent &event)
void mouseEnterWindow (wxMouseEvent &event)
void mouseLeaveWindow (wxMouseEvent &event)
void sendButtonEvent ()
Private Attributes
ScalableBitmap m_on
ScalableBitmap m_off
bool m_on_off
int m_padding
bool pressedDown = false
bool hover = false
wxSize textSize
wxSize minSize
int m_speed
wxString labels [2]
StateColor text_color
Detailed Description
Constructor & Destructor Documentation
FanSwitchButton()
FanSwitchButton::FanSwitchButton (wxWindow * parent, ScalableBitmap & img_on, ScalableBitmap & img_off, long style = 0)
    : text_color(std::make_pair(0x6B6B6B, (int)StateColor::Disabled), std::make_pair(*wxBLACK, (int)StateColor::Normal))
{
    radius = 0;
    m_padding = 0;
    m_speed = 0;
    m_on = img_on;
    m_off = img_off;
    background_color = StateColor(std::make_pair(*wxWHITE, (int)StateColor::Disabled), std::make_pair(DEFAULT_PRESS_COL, (int)StateColor::Pressed),
        std::make_pair(*wxWHITE, (int)StateColor::Normal));
    border_color = StateColor(std::make_pair(*wxWHITE, (int)StateColor::Disabled), std::make_pair(DEFAULT_HOVER_COL, (int)StateColor::Focused),
        std::make_pair(DEFAULT_HOVER_COL, (int)StateColor::Hovered), std::make_pair(*wxWHITE, (int)StateColor::Normal));
    StaticBox::Create(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, style);
    messureSize();
    Refresh();
}
References StaticBox::background_color, StaticBox::border_color, StaticBox::Create(), DEFAULT_HOVER_COL, DEFAULT_PRESS_COL, StateColor::Disabled, StateColor::Focused, StateColor::Hovered, m_off, m_on, m_padding, m_speed, messureSize(), StateColor::Normal, StateColor::Pressed, StaticBox::radius, and style.
Member Function Documentation
Create()
bool StaticBox::Create (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0) inherited
{
    if (style & wxBORDER_NONE)
        border_width = 0;
    wxWindow::Create(parent, id, pos, size, style);
    state_handler.attach({&border_color, &background_color, &background_color2});
    state_handler.update_binds();
    SetBackgroundColour(GetParentBackgroundColor(parent));
    return true;
}
References StateHandler::attach(), StaticBox::background_color, StaticBox::background_color2, StaticBox::border_color, StaticBox::border_width, StaticBox::GetParentBackgroundColor(), size, StaticBox::state_handler, style, and StateHandler::update_binds().
Referenced by FanSwitchButton(), ImageSwitchButton::ImageSwitchButton(), StaticBox::StaticBox(), Button::Create(), SpinInput::Create(), TextInput::Create(), and TempInput::Create().
doRender()
void StaticBox::doRender (wxDC & dc) protected virtual inherited
Reimplemented in StepCtrl, StepIndicator, and TabCtrl.
{
    wxSize size = GetSize();
    int states = state_handler.states();
    if (background_color2.count() == 0) {
        if ((border_width && border_color.count() > 0) || background_color.count() > 0) {
            wxRect rc(0, 0, size.x, size.y);
            if (border_width && border_color.count() > 0) {
                if (dc.GetContentScaleFactor() == 1.0) {
                    int d  = floor(border_width / 2.0);
                    int d2 = floor(border_width - 1);
                    rc.x += d;
                    rc.width -= d2;
                    rc.y += d;
                    rc.height -= d2;
                } else {
                    int d  = 1;
                    rc.x += d;
                    rc.width -= d;
                    rc.y += d;
                    rc.height -= d;
                }
                dc.SetPen(wxPen(border_color.colorForStates(states), border_width));
            } else {
                dc.SetPen(wxPen(background_color.colorForStates(states)));
            }
            if (background_color.count() > 0)
                dc.SetBrush(wxBrush(background_color.colorForStates(states)));
            else
                dc.SetBrush(wxBrush(GetBackgroundColour()));
            if (radius == 0) {
                dc.DrawRectangle(rc);
            }
            else {
                dc.DrawRoundedRectangle(rc, radius - border_width);
            }
        }
    }
    else {
        wxColor start = background_color.colorForStates(states);
        wxColor stop = background_color2.colorForStates(states);
        int r = start.Red(), g = start.Green(), b = start.Blue();
        int dr = (int) stop.Red() - r, dg = (int) stop.Green() - g, db = (int) stop.Blue() - b;
        int lr = 0, lg = 0, lb = 0;
        for (int y = 0; y < size.y; ++y) {
            dc.SetPen(wxPen(wxColor(r, g, b)));
            dc.DrawLine(0, y, size.x, y);
            lr += dr; while (lr >= size.y) { ++r, lr -= size.y; } while (lr <= -size.y) { --r, lr += size.y; }
            lg += dg; while (lg >= size.y) { ++g, lg -= size.y; } while (lg <= -size.y) { --g, lg += size.y; }
            lb += db; while (lb >= size.y) { ++b, lb -= size.y; } while (lb <= -size.y) { --b, lb += size.y; }
        }
    }
}
References StaticBox::background_color, StaticBox::background_color2, StaticBox::border_color, StaticBox::border_width, StateColor::colorForStates(), StateColor::count(), floor(), int, StaticBox::radius, size, start, StaticBox::state_handler, and StateHandler::states().
Referenced by StepCtrl::doRender(), StepIndicator::doRender(), and StaticBox::render().
eraseEvent()
void StaticBox::eraseEvent (wxEraseEvent & evt) protected inherited
{
    // for transparent background, but not work
#ifdef __WXMSW__
    wxDC *dc = evt.GetDC();
    wxSize size = GetSize();
    wxClientDC dc2(GetParent());
    dc->Blit({0, 0}, size, &dc2, GetPosition());
#endif
}
References size.
GetParentBackgroundColor()
wxColor StaticBox::GetParentBackgroundColor (wxWindow * parent) static inherited
{
    if (auto box = dynamic_cast<StaticBox*>(parent)) {
        if (box->background_color.count() > 0) {
            if (box->background_color2.count() == 0)
                return box->background_color.defaultColor();
            auto s = box->background_color.defaultColor();
            auto e = box->background_color2.defaultColor();
            int r = (s.Red() + e.Red()) / 2;
            int g = (s.Green() + e.Green()) / 2;
            int b = (s.Blue() + e.Blue()) / 2;
            return wxColor(r, g, b);
        }
    }
    if (parent)
        return parent->GetBackgroundColour();
    return *wxWHITE;
}
Referenced by Label::Label(), ScalableButton::ScalableButton(), SwitchButton::SwitchButton(), StaticBox::Create(), and SwitchButton::Rescale().
GetValue()
bool FanSwitchButton::GetValue () inline
{ return m_on_off; }
References ImageSwitchButton::m_on_off.
Referenced by messureSize(), render(), and SetLabels().
messureSize()
void FanSwitchButton::messureSize () private
{
    wxClientDC dc(this);
    dc.SetFont(GetFont());
    textSize = dc.GetTextExtent(GetValue() ? labels[0] : labels[1]);
}
References GetValue(), labels, and textSize.
Referenced by FanSwitchButton(), Rescale(), SetImages(), SetLabels(), SetPadding(), SetTextColor(), and SetValue().
mouseDown()
void FanSwitchButton::mouseDown (wxMouseEvent & event) private
{
    event.Skip();
    pressedDown = true;
    SetFocus();
    CaptureMouse();
}
References pressedDown.
mouseEnterWindow()
void FanSwitchButton::mouseEnterWindow (wxMouseEvent & event) private
{
    if (!hover) {
        hover = true;
        Refresh();
    }
}
References hover.
mouseLeaveWindow()
void FanSwitchButton::mouseLeaveWindow (wxMouseEvent & event) private
{
    if (hover) {
        hover = false;
        Refresh();
    }
}
References hover.
mouseReleased()
void FanSwitchButton::mouseReleased (wxMouseEvent & event) private
{
    event.Skip();
    if (pressedDown) {
        pressedDown = false;
        ReleaseMouse();
        //m_on_off = !m_on_off;
        Refresh();
        sendButtonEvent();
    }
}
References pressedDown, and sendButtonEvent().
paintEvent()
void FanSwitchButton::paintEvent (wxPaintEvent & evt) private
{
    wxPaintDC dc(this);
    render(dc);
}
References render().
render()
void FanSwitchButton::render (wxDC & dc) private
{
    StaticBox::render(dc);
    int states = state_handler.states();
    wxSize size = GetSize();
    wxSize szIcon;
    wxSize szContent = textSize;
    ScalableBitmap& icon = GetValue() ? m_on : m_off;
    //int content_height = icon.GetBmpHeight() + textSize.y + m_padding;
    int content_height = m_padding;
    wxPoint pt = wxPoint((size.x - icon.GetBmpWidth()) / 2, (size.y - content_height) / 2);
    pt.x = (size.x - textSize.x) / 2;
    dc.SetFont(GetFont());
    if (!IsEnabled())
        dc.SetTextForeground(text_color.colorForStates(StateColor::Disabled));
    else
        dc.SetTextForeground(text_color.colorForStates(states));
    auto fina_txt = GetValue() ? labels[0] : labels[1];
    if (dc.GetTextExtent(fina_txt).x > size.x) {
        wxString forment_txt = wxEmptyString;
        for (auto i = 0; i < fina_txt.length(); i++) {
            forment_txt = fina_txt.SubString(0, i) + "...";
            if (dc.GetTextExtent(forment_txt).x > size.x) {
                pt.x = (size.x - dc.GetTextExtent(forment_txt).x) / 2;
                dc.DrawText(forment_txt, wxPoint(pt.x, content_height));
                break;
            }
        }
    }
    else {
        dc.DrawText(fina_txt,  wxPoint(pt.x, content_height));
    }
    pt = wxPoint((size.x - icon.GetBmpWidth()) / 2, content_height + textSize.y);
    if (icon.bmp().IsOk()) {
        dc.DrawBitmap(icon.bmp(), pt);
        pt.y += m_padding + icon.GetBmpHeight();
    }
    auto speed = wxString::Format("%d%%", m_speed);
    dc.SetFont(GetFont());
    if (!IsEnabled())
        dc.SetTextForeground(text_color.colorForStates(StateColor::Disabled));
    else
        dc.SetTextForeground(text_color.colorForStates(states));
    pt.x = (size.x - dc.GetTextExtent(speed).x) / 2;
    pt.y += FromDIP(1);
    dc.DrawText(speed, pt);
}
References ScalableBitmap::bmp(), StateColor::colorForStates(), StateColor::Disabled, ScalableBitmap::GetBmpHeight(), ScalableBitmap::GetBmpWidth(), GetValue(), labels, m_off, m_on, m_padding, m_speed, StaticBox::render(), size, StaticBox::state_handler, StateHandler::states(), text_color, and textSize.
Referenced by paintEvent().
Rescale()
void FanSwitchButton::Rescale ()
{
    messureSize();
}
References messureSize().
Referenced by Slic3r::GUI::StatusPanel::msw_rescale().
sendButtonEvent()
void FanSwitchButton::sendButtonEvent () private
{
    wxCommandEvent event(wxEVT_COMMAND_BUTTON_CLICKED, GetId());
    event.SetEventObject(this);
    GetEventHandler()->ProcessEvent(event);
}
Referenced by mouseReleased().
SetBackgroundColor()
void StaticBox::SetBackgroundColor (StateColor const & color) inherited
{
    background_color = color;
    state_handler.update_binds();
    Refresh();
}
References StaticBox::background_color, StaticBox::state_handler, and StateHandler::update_binds().
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::BBLStatusBarSend::BBLStatusBarSend(), Slic3r::GUI::BindMachineDialog::BindMachineDialog(), Slic3r::GUI::CalibrationDialog::CalibrationDialog(), Slic3r::GUI::ColorPickerPopup::ColorPickerPopup(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::ParamsPanel::ParamsPanel(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), TabCtrl::AppendItem(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::StatusBasePanel::create_ams_group(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_machine_control_page(), Slic3r::GUI::StatusBasePanel::create_misc_control(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Slic3r::GUI::PublishDialog::create_publish_step_sizer(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), Slic3r::GUI::SelectMachineDialog::Enable_Refresh_Button(), Slic3r::GUI::SelectMachineDialog::Enable_Send_Button(), Slic3r::GUI::BedShapePanel::init_model_panel(), Slic3r::GUI::MonitorPanel::init_tabpanel(), Slic3r::GUI::BedShapePanel::init_texture_panel(), TabButtonsListCtrl::InsertPage(), ButtonsListCtrl::InsertPage(), Slic3r::GUI::InputIpAddressDialog::on_check_ip_address_failed(), Slic3r::GUI::ColorPickerPopup::on_custom_clr_picker(), Slic3r::GUI::InputIpAddressDialog::on_ok(), Slic3r::GUI::InputIpAddressDialog::on_text(), ButtonsListCtrl::OnPaint(), TabButtonsListCtrl::OnPaint(), Slic3r::GUI::ColorPickerPopup::set_def_colour(), and Slic3r::GUI::MonitorPanel::show_status().
SetBackgroundColor2()
void StaticBox::SetBackgroundColor2 (StateColor const & color) inherited
{
    background_color2 = color;
    state_handler.update_binds();
    Refresh();
}
References StaticBox::background_color2, StaticBox::state_handler, and StateHandler::update_binds().
Referenced by Slic3r::GUI::ParamsPanel::ParamsPanel().
SetBackgroundColorNormal()
void StaticBox::SetBackgroundColorNormal (wxColor const & color) inherited
{
    background_color.setColorForStates(color, 0);
    Refresh();
}
References StaticBox::background_color, and StateColor::setColorForStates().
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel().
SetBorderColor()
void StaticBox::SetBorderColor (StateColor const & color) inherited
{
    border_color = color;
    state_handler.update_binds();
    Refresh();
}
References StaticBox::border_color, StaticBox::state_handler, and StateHandler::update_binds().
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::BBLStatusBarSend::BBLStatusBarSend(), Slic3r::GUI::CalibrationDialog::CalibrationDialog(), Slic3r::GUI::ColorPickerPopup::ColorPickerPopup(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), TabCtrl::TabCtrl(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::StatusBasePanel::create_ams_group(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_machine_control_page(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), Slic3r::GUI::SelectMachineDialog::Enable_Refresh_Button(), Slic3r::GUI::SelectMachineDialog::Enable_Send_Button(), Slic3r::GUI::BedShapePanel::init_model_panel(), Slic3r::GUI::MonitorPanel::init_tabpanel(), Slic3r::GUI::BedShapePanel::init_texture_panel(), Slic3r::GUI::InputIpAddressDialog::on_ok(), Slic3r::GUI::InputIpAddressDialog::on_text(), and Slic3r::GUI::MonitorPanel::show_status().
SetBorderColorNormal()
void StaticBox::SetBorderColorNormal (wxColor const & color) inherited
{
    border_color.setColorForStates(color, 0);
    Refresh();
}
References StaticBox::border_color, and StateColor::setColorForStates().
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel().
SetBorderWidth()
void StaticBox::SetBorderWidth (int width) inherited
{
    border_width = width;
    Refresh();
}
References StaticBox::border_width.
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::StatusBasePanel::create_bed_control(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), and Slic3r::GUI::StatusBasePanel::create_misc_control().
SetCornerRadius()
void StaticBox::SetCornerRadius (double radius) inherited
{
    this->radius = radius;
    Refresh();
}
References StaticBox::radius.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::BBLStatusBarSend::BBLStatusBarSend(), Slic3r::GUI::BindMachineDialog::BindMachineDialog(), Slic3r::GUI::ColorPickerPopup::ColorPickerPopup(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), TabCtrl::AppendItem(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::ProgressDialog::Create(), Slic3r::GUI::StatusBasePanel::create_ams_group(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_misc_control(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), SpinInput::createButton(), Slic3r::GUI::StatusPanel::init_scaled_buttons(), Slic3r::GUI::AMSControl::init_scaled_buttons(), Slic3r::GUI::MonitorPanel::init_tabpanel(), TabButtonsListCtrl::InsertPage(), ButtonsListCtrl::InsertPage(), Slic3r::GUI::MonitorPanel::msw_rescale(), Slic3r::GUI::ConnectPrinterDialog::on_dpi_changed(), Slic3r::GUI::RecenterDialog::on_dpi_changed(), and Slic3r::GUI::SelectMachineDialog::on_dpi_changed().
setFanValue()
void FanSwitchButton::setFanValue (int val)
{
    m_speed = val;
    Refresh();
}
References m_speed.
Referenced by Slic3r::GUI::StatusPanel::on_fan_changed(), and Slic3r::GUI::StatusPanel::update_misc_ctrl().
SetImages()
void FanSwitchButton::SetImages (ScalableBitmap & img_on, ScalableBitmap & img_off)
{
    m_on = img_on;
    m_off = img_off;
    messureSize();
    Refresh();
}
References m_off, m_on, and messureSize().
Referenced by Slic3r::GUI::StatusPanel::msw_rescale().
SetLabels()
void FanSwitchButton::SetLabels (wxString const & lbl_on, wxString const & lbl_off)
{
    labels[0] = lbl_on;
    labels[1] = lbl_off;
    auto fina_txt = GetValue() ? labels[0] : labels[1];
    SetToolTip(fina_txt);
    messureSize();
    Refresh();
}
References GetValue(), labels, and messureSize().
Referenced by Slic3r::GUI::StatusBasePanel::create_misc_control().
SetPadding()
void FanSwitchButton::SetPadding (int padding)
{
    m_padding = padding;
    messureSize();
    Refresh();
}
References m_padding, and messureSize().
Referenced by Slic3r::GUI::StatusBasePanel::create_misc_control().
SetTextColor()
void FanSwitchButton::SetTextColor (StateColor const & color)
{
    text_color = color;
    state_handler.update_binds();
    messureSize();
    Refresh();
}
References messureSize(), StaticBox::state_handler, text_color, and StateHandler::update_binds().
Referenced by Slic3r::GUI::StatusBasePanel::create_misc_control().
SetValue()
void FanSwitchButton::SetValue (bool value)
{
    m_on_off = value;
    messureSize();
    Refresh();
}
References m_on_off, and messureSize().
Referenced by Slic3r::GUI::StatusPanel::StatusPanel(), Slic3r::GUI::StatusBasePanel::create_misc_control(), Slic3r::GUI::StatusPanel::on_fan_changed(), Slic3r::GUI::StatusBasePanel::reset_temp_misc_control(), and Slic3r::GUI::StatusPanel::update_misc_ctrl().
Member Data Documentation
background_color
StateColor StaticBox::background_color protected inherited
Referenced by FanSwitchButton(), StaticBox::Create(), StaticBox::doRender(), StaticBox::SetBackgroundColor(), and StaticBox::SetBackgroundColorNormal().
background_color2
StateColor StaticBox::background_color2 protected inherited
Referenced by StaticBox::Create(), StaticBox::doRender(), and StaticBox::SetBackgroundColor2().
border_color
StateColor StaticBox::border_color protected inherited
Referenced by FanSwitchButton(), StaticBox::Create(), StaticBox::doRender(), TabCtrl::doRender(), StaticBox::SetBorderColor(), and StaticBox::SetBorderColorNormal().
border_width
int StaticBox::border_width = 1 protected inherited
Referenced by StepCtrl::StepCtrl(), StepIndicator::StepIndicator(), TabCtrl::TabCtrl(), StaticBox::Create(), StaticBox::doRender(), TabCtrl::doRender(), and StaticBox::SetBorderWidth().
hover
bool FanSwitchButton::hover = false private
Referenced by mouseEnterWindow(), and mouseLeaveWindow().
labels
wxString FanSwitchButton::labels[2] private
Referenced by messureSize(), render(), and SetLabels().
m_off
ScalableBitmap FanSwitchButton::m_off private
Referenced by FanSwitchButton(), render(), and SetImages().
m_on
ScalableBitmap FanSwitchButton::m_on private
Referenced by FanSwitchButton(), render(), and SetImages().
m_on_off
bool FanSwitchButton::m_on_off private
Referenced by SetValue().
m_padding
int FanSwitchButton::m_padding private
Referenced by FanSwitchButton(), render(), and SetPadding().
m_speed
int FanSwitchButton::m_speed private
Referenced by FanSwitchButton(), render(), and setFanValue().
minSize
wxSize FanSwitchButton::minSize private
pressedDown
bool FanSwitchButton::pressedDown = false private
Referenced by mouseDown(), and mouseReleased().
radius
double StaticBox::radius protected inherited
Referenced by FanSwitchButton(), StepCtrlBase::StepCtrlBase(), TabCtrl::TabCtrl(), StaticBox::doRender(), TabCtrl::doRender(), StaticBox::render(), and StaticBox::SetCornerRadius().
state_handler
StateHandler StaticBox::state_handler protected inherited
Referenced by Button::Create(), StaticBox::Create(), StaticBox::doRender(), StepCtrl::doRender(), StepIndicator::doRender(), TabCtrl::doRender(), Button::GetValue(), Button::render(), ImageSwitchButton::render(), render(), StaticBox::SetBackgroundColor(), StaticBox::SetBackgroundColor2(), StaticBox::SetBorderColor(), Button::SetTextColor(), ImageSwitchButton::SetTextColor(), SetTextColor(), and Button::SetValue().
text_color
StateColor FanSwitchButton::text_color private
Referenced by render(), and SetTextColor().
textSize
wxSize FanSwitchButton::textSize private
Referenced by messureSize(), and render().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/ImageSwitchButton.hpp
src/slic3r/GUI/Widgets/ImageSwitchButton.cpp