OrcaSlicer: Slic3r::GUI::GridCellSupportEditor Class Reference
Slic3r::GUI::GridCellSupportEditor Class Reference
#include <src/slic3r/GUI/GUI_ObjectTable.hpp>
Public Member Functions
GridCellSupportEditor ()
virtual void DoActivate (int row, int col, wxGrid *grid) wxOVERRIDE
Private Member Functions
void SetValueFromGrid (int row, int col, wxGrid *grid)
void SetGridFromValue (int row, int col, wxGrid *grid) const
wxString GetStringValue () const
wxDECLARE_NO_COPY_CLASS (GridCellSupportEditor)
Static Private Member Functions
static wxString GetStringValue (bool value)
Private Attributes
bool m_value
Static Private Attributes
static wxString ms_stringValues [2] = { wxT(""), wxT("") }
Detailed Description
Constructor & Destructor Documentation
GridCellSupportEditor()
Slic3r::GUI::GridCellSupportEditor::GridCellSupportEditor () inline
{ }
Member Function Documentation
DoActivate()
void Slic3r::GUI::GridCellSupportEditor::DoActivate (int row, int col, wxGrid * grid) virtual
{
    ObjectGrid* local_table = dynamic_cast<ObjectGrid*>(grid);
    wxGridBlocks cell_array = grid->GetSelectedBlocks();
    auto left_col = cell_array.begin()->GetLeftCol();
    auto right_col = cell_array.begin()->GetRightCol();
    auto top_row = cell_array.begin()->GetTopRow();
    auto bottom_row = cell_array.begin()->GetBottomRow();
  if ((left_col == right_col) &&
    (top_row == bottom_row)) {
    wxGridCellBoolEditor::DoActivate(row, col, grid);
    grid->SelectBlock(row, col, row, col, true);
        return;
    }
    else if( (left_col == right_col) &&
        (top_row != bottom_row)){
        for (auto i = top_row; i <= bottom_row; i++) {
            //grid->GetTable()->SetValueAsBool(i, left_col, false);
            wxGridCellBoolEditor::DoActivate(i, left_col, grid);
        }
    }
    wxGridCellBoolEditor::DoActivate(row, col, grid);
    grid->SelectBlock(row, col, row, col, true);
}
References col(), Slic3r::grid(), and row().
GetStringValue() [1/2]
wxString Slic3r::GUI::GridCellSupportEditor::GetStringValue () const inline private
{ return GetStringValue(m_value); }
References GetStringValue(), and m_value.
Referenced by GetStringValue(), and SetGridFromValue().
GetStringValue() [2/2]
static wxString Slic3r::GUI::GridCellSupportEditor::GetStringValue (bool value) inline static private
{ return ms_stringValues[value]; }
References ms_stringValues.
SetGridFromValue()
void Slic3r::GUI::GridCellSupportEditor::SetGridFromValue (int row, int col, wxGrid * grid) const private
{
    wxGridTableBase * const table = grid->GetTable();
    if ( table->CanSetValueAs(row, col, wxGRID_VALUE_BOOL) )
        table->SetValueAsBool(row, col, m_value);
    else
        table->SetValue(row, col, GetStringValue());
}
References col(), GetStringValue(), Slic3r::grid(), m_value, and row().
SetValueFromGrid()
void Slic3r::GUI::GridCellSupportEditor::SetValueFromGrid (int row, int col, wxGrid * grid) private
{
    if (grid->GetTable()->CanGetValueAs(row, col, wxGRID_VALUE_BOOL))
    {
        m_value = grid->GetTable()->GetValueAsBool(row, col);
    }
    else
    {
        wxString cellval( grid->GetTable()->GetValue(row, col) );
        if ( cellval == ms_stringValues[false] )
            m_value = false;
        else if ( cellval == ms_stringValues[true] )
            m_value = true;
        else
        {
            // do not try to be smart here and convert it to true or false
            // because we'll still overwrite it with something different and
            // this risks to be very surprising for the user code, let them
            // know about it
            wxFAIL_MSG( wxT("invalid value for a cell with bool editor!") );
            // Still need to initialize it to something.
            m_value = false;
        }
    }
}
References col(), Slic3r::grid(), m_value, ms_stringValues, and row().
wxDECLARE_NO_COPY_CLASS()
Slic3r::GUI::GridCellSupportEditor::wxDECLARE_NO_COPY_CLASS (GridCellSupportEditor) private
Member Data Documentation
m_value
bool Slic3r::GUI::GridCellSupportEditor::m_value private
Referenced by GetStringValue(), SetGridFromValue(), and SetValueFromGrid().
ms_stringValues
wxString Slic3r::GUI::GridCellSupportEditor::ms_stringValues = { wxT(""), wxT("") } static private
Referenced by GetStringValue(), and SetValueFromGrid().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectTable.hpp
src/slic3r/GUI/GUI_ObjectTable.cpp