OrcaSlicer: Slic3r::PrintEstimatedStatistics Struct Reference
Slic3r::PrintEstimatedStatistics Struct Reference
#include <src/libslic3r/GCode/GCodeProcessor.hpp>
Classes
struct Mode
Public Types
enum class ETimeMode : unsigned char { Normal , Stealth , Count }
Public Member Functions
PrintEstimatedStatistics ()
void reset ()
Public Attributes
std::vector< double > volumes_per_color_change
std::map< size_t, double > volumes_per_extruder
std::map< size_t, double > flush_per_filament
std::map< ExtrusionRole, std::pair< double, double > > used_filaments_per_role
std::array< Mode, static_cast< size_t >(ETimeMode::Count)> modes
unsigned int total_filamentchanges
Detailed Description
Member Enumeration Documentation
ETimeMode
enum class Slic3r::PrintEstimatedStatistics::ETimeMode : unsigned char strong
Enumerator
Normal
Stealth
Count
        {
            Normal,
            Stealth,
            Count
        };
Constructor & Destructor Documentation
PrintEstimatedStatistics()
Slic3r::PrintEstimatedStatistics::PrintEstimatedStatistics () inline
{ reset(); }
References reset().
Member Function Documentation
reset()
void Slic3r::PrintEstimatedStatistics::reset () inline
                     {
            for (auto m : modes) {
                m.reset();
            }
            volumes_per_color_change.clear();
            volumes_per_color_change.shrink_to_fit();
            volumes_per_extruder.clear();
            flush_per_filament.clear();
            used_filaments_per_role.clear();
            total_filamentchanges = 0;
        }
References flush_per_filament, modes, total_filamentchanges, used_filaments_per_role, volumes_per_color_change, and volumes_per_extruder.
Referenced by PrintEstimatedStatistics(), and Slic3r::GUI::GCodeViewer::reset().
Member Data Documentation
flush_per_filament
std::map<size_t, double> Slic3r::PrintEstimatedStatistics::flush_per_filament
Referenced by Slic3r::PlateData::parse_filament_info(), Slic3r::GUI::GCodeViewer::render_legend(), reset(), Slic3r::GCodeProcessor::update_estimated_times_stats(), and Slic3r::DoExport::update_print_estimated_stats().
modes
std::array<Mode, static_cast<size_t>(ETimeMode::Count)> Slic3r::PrintEstimatedStatistics::modes
Referenced by Slic3r::GCodeProcessor::finalize(), Slic3r::GUI::GCodeViewer::load(), Slic3r::GUI::PartPlateList::load_from_3mf_structure(), Slic3r::GUI::GCodeViewer::render_legend(), reset(), Slic3r::GUI::SelectMachineDialog::set_default(), Slic3r::GUI::SendToPrinterDialog::set_default(), Slic3r::GCodeProcessor::update_estimated_times_stats(), Slic3r::GUI::Preview::update_layers_slider(), and Slic3r::DoExport::update_print_estimated_stats().
total_filamentchanges
unsigned int Slic3r::PrintEstimatedStatistics::total_filamentchanges
Referenced by Slic3r::GCodeProcessor::process_T(), and reset().
used_filaments_per_role
std::map<ExtrusionRole, std::pair<double, double> > Slic3r::PrintEstimatedStatistics::used_filaments_per_role
Referenced by Slic3r::GUI::GCodeViewer::render_legend(), reset(), and Slic3r::GCodeProcessor::update_estimated_times_stats().
volumes_per_color_change
std::vector<double> Slic3r::PrintEstimatedStatistics::volumes_per_color_change
Referenced by reset(), and Slic3r::GCodeProcessor::update_estimated_times_stats().
volumes_per_extruder
std::map<size_t, double> Slic3r::PrintEstimatedStatistics::volumes_per_extruder
Referenced by Slic3r::GUI::PartPlate::get_used_extruders(), Slic3r::PlateData::parse_filament_info(), Slic3r::GUI::GCodeViewer::render_legend(), reset(), Slic3r::GCodeProcessor::update_estimated_times_stats(), and Slic3r::DoExport::update_print_estimated_stats().
The documentation for this struct was generated from the following file:
src/libslic3r/GCode/GCodeProcessor.hpp