OrcaSlicer: src/OrcaSlicer.cpp File Reference
OrcaSlicer.cpp File Reference
#include <cstdio>
#include <string>
#include <cstring>
#include <iostream>
#include <math.h>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/filesystem.hpp>
#include <boost/nowide/args.hpp>
#include <boost/nowide/cenv.hpp>
#include <boost/nowide/iostream.hpp>
#include <boost/nowide/integration/filesystem.hpp>
#include <boost/dll/runtime_symbol_info.hpp>
#include <boost/log/trivial.hpp>
#include "unix/fhs.hpp"
#include "libslic3r/libslic3r.h"
#include "libslic3r/Config.hpp"
#include "libslic3r/Geometry.hpp"
#include "libslic3r/GCode/PostProcessor.hpp"
#include "libslic3r/Model.hpp"
#include "libslic3r/ModelArrange.hpp"
#include "libslic3r/Platform.hpp"
#include "libslic3r/Print.hpp"
#include "libslic3r/SLAPrint.hpp"
#include "libslic3r/TriangleMesh.hpp"
#include "libslic3r/Format/AMF.hpp"
#include "libslic3r/Format/3mf.hpp"
#include "libslic3r/Format/STL.hpp"
#include "libslic3r/Format/OBJ.hpp"
#include "libslic3r/Format/SL1.hpp"
#include "libslic3r/Utils.hpp"
#include "libslic3r/Time.hpp"
#include "libslic3r/Thread.hpp"
#include "libslic3r/BlacklistedLibraryCheck.hpp"
#include "libslic3r/Orient.hpp"
#include "OrcaSlicer.hpp"
#include <wx/stdpaths.h>
#include "slic3r/GUI/PartPlate.hpp"
#include "slic3r/GUI/BitmapCache.hpp"
#include "slic3r/GUI/OpenGLManager.hpp"
#include "slic3r/GUI/GLCanvas3D.hpp"
#include "slic3r/GUI/Camera.hpp"
#include <GLFW/glfw3.h>
Macros
#define flush_and_exit(ret)
Functions
static PrinterTechnology get_printer_technology (const DynamicConfig &config)
static void glfw_callback (int error_code, const char *description)
int main (int argc, char **argv)
Variables
std::map< int, std::string > cli_errors
const float bed3d_ax3s_default_stem_radius = 0.5f
const float bed3d_ax3s_default_stem_length = 25.0f
const float bed3d_ax3s_default_tip_radius = 2.5f * bed3d_ax3s_default_stem_radius
const float bed3d_ax3s_default_tip_length = 5.0f
Macro Definition Documentation
flush_and_exit
#define flush_and_exit (ret)
Value:
    { boost::nowide::cout << __FUNCTION__ << " found error, exit" << std::endl;\
    boost::nowide::cout.flush();\
    boost::nowide::cerr.flush();\
    for (Model &model : m_models) {\
       model.remove_backup_path_if_exist();\
    }\
    return(ret);}
Function Documentation
get_printer_technology()
static PrinterTechnology get_printer_technology (const DynamicConfig & config) static
{
    const ConfigOptionEnum<PrinterTechnology> *opt = config.option<ConfigOptionEnum<PrinterTechnology>>("printer_technology");
    return (opt == nullptr) ? ptUnknown : opt->value;
}
References Slic3r::ConfigBase::option(), Slic3r::ptUnknown, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::CLI::run().
glfw_callback()
static void glfw_callback (int error_code, const char * description) static
{
    BOOST_LOG_TRIVIAL(error) << "error_code " <<error_code <<", description: " <<description<< std::endl;
}
References error.
Referenced by Slic3r::CLI::run().
main()
int main (int argc, char ** argv)
{
    return CLI().run(argc, argv);
}
References Slic3r::CLI::run().
Variable Documentation
bed3d_ax3s_default_stem_length
const float bed3d_ax3s_default_stem_length = 25.0f
bed3d_ax3s_default_stem_radius
const float bed3d_ax3s_default_stem_radius = 0.5f
bed3d_ax3s_default_tip_length
const float bed3d_ax3s_default_tip_length = 5.0f
bed3d_ax3s_default_tip_radius
const float bed3d_ax3s_default_tip_radius = 2.5f * bed3d_ax3s_default_stem_radius
Referenced by Slic3r::CLI::run().
cli_errors
std::map<int, std::string> cli_errors
Initial value:
= {
    {CLI_SUCCESS, "Success"},
    {CLI_ENVIRONMENT_ERROR, "Environment setup failed"},
    {CLI_INVALID_PARAMS, "Input param invalid"},
    {CLI_FILE_NOTFOUND, "Input file not found"},
    {CLI_FILELIST_INVALID_ORDER, "File list order invalid(please make sure 3mf in the first place)"},
    {CLI_CONFIG_FILE_ERROR, "Invalid config file, could not be parsed"},
    {CLI_DATA_FILE_ERROR, "Invalid model file, could not be loaded"},
    {CLI_INVALID_PRINTER_TECH, "Invalid printer technoledge"},
    {CLI_UNSUPPORTED_OPERATION, "Unsupported operation"},
    {CLI_COPY_OBJECTS_ERROR, "Copy objects error"},
    {CLI_SCALE_TO_FIT_ERROR, "Scale to fit error"},
    {CLI_EXPORT_STL_ERROR, "Export stl error"},
    {CLI_EXPORT_OBJ_ERROR, "Export obj error"},
    {CLI_EXPORT_3MF_ERROR, "Export 3mf error"},
    {CLI_OUT_OF_MEMORY, "Out of memory"},
    {CLI_NO_SUITABLE_OBJECTS, "Found no objects in print volume to slice"},
    {CLI_VALIDATE_ERROR, "Validate print error"},
    {CLI_OBJECTS_PARTLY_INSIDE, "Objects partly inside"},
    {CLI_EXPORT_CACHE_DIRECTORY_CREATE_FAILED, "Objects partly inside"},
    {CLI_EXPORT_CACHE_WRITE_FAILED, "export cached slicedata failed"},
    {CLI_IMPORT_CACHE_NOT_FOUND, "cached slicedata can not be found"},
    {CLI_IMPORT_CACHE_DATA_CAN_NOT_USE, "cached slicedata can not be used"},
    {CLI_IMPORT_CACHE_LOAD_FAILED, "load cached slicedata failed"},
    {CLI_SLICING_ERROR, "Slice error"}
}