OrcaSlicer: ComboBox Class Reference
ComboBox Class Reference
#include <src/slic3r/GUI/Widgets/ComboBox.hpp>
Public Member Functions
ComboBox (wxWindow *parent, wxWindowID id, const wxString &value=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, int n=0, const wxString choices[]=NULL, long style=0)
DropDown & GetDropDown ()
virtual bool SetFont (wxFont const &font) override
int Append (const wxString &item, const wxBitmap &bitmap=wxNullBitmap)
int Append (const wxString &item, const wxBitmap &bitmap, void *clientData)
unsigned int GetCount () const override
int GetSelection () const override
void SetSelection (int n) override
void SelectAndNotify (int n)
virtual void Rescale () override
wxString GetValue () const
void SetValue (const wxString &value)
void SetLabel (const wxString &label) override
wxString GetLabel () const override
void SetTextLabel (const wxString &label)
wxString GetTextLabel () const
wxString GetString (unsigned int n) const override
void SetString (unsigned int n, wxString const &value) override
wxBitmap GetItemBitmap (unsigned int n)
void SetItemBitmap (unsigned int n, wxBitmap const &bitmap)
Protected Member Functions
virtual int DoInsertItems (const wxArrayStringsAdapter &items, unsigned int pos, void **clientData, wxClientDataType type) override
virtual void DoClear () override
void DoDeleteOneItem (unsigned int pos) override
void * DoGetItemClientData (unsigned int n) const override
void DoSetItemClientData (unsigned int n, void *data) override
void OnEdit () override
void sendComboBoxEvent ()
Private Member Functions
void mouseDown (wxMouseEvent &event)
void mouseWheelMoved (wxMouseEvent &event)
void keyDown (wxKeyEvent &event)
Private Attributes
std::vector< wxString > texts
std::vector< wxBitmap > icons
std::vector< void * > datas
std::vector< wxClientDataType > types
DropDown drop
bool drop_down = false
bool text_off = false
Detailed Description
Constructor & Destructor Documentation
ComboBox()
ComboBox::ComboBox (wxWindow * parent, wxWindowID id, const wxString & value = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, int n = 0, const wxString choices[] = NULL, long style = 0)
    : drop(texts, icons)
{
    if (style & wxCB_READONLY)
        style |= wxRIGHT;
    text_off = style & CB_NO_TEXT;
    TextInput::Create(parent, "", value, (style & CB_NO_DROP_ICON) ? "" : "drop_down", pos, size,
                      style | wxTE_PROCESS_ENTER);
    drop.Create(this, style & DD_STYLE_MASK);
    if (style & wxCB_READONLY) {
        GetTextCtrl()->Hide();
        TextInput::SetFont(Label::Body_14);
        TextInput::SetBorderColor(StateColor(std::make_pair(0xDBDBDB, (int) StateColor::Disabled),
            std::make_pair(0x009688, (int) StateColor::Hovered),
            std::make_pair(0xDBDBDB, (int) StateColor::Normal)));
        TextInput::SetBackgroundColor(StateColor(std::make_pair(0xF0F0F1, (int) StateColor::Disabled),
            std::make_pair(0xEDFAF2, (int) StateColor::Focused),
            std::make_pair(*wxWHITE, (int) StateColor::Normal)));
        TextInput::SetLabelColor(StateColor(std::make_pair(0x909090, (int) StateColor::Disabled),
            std::make_pair(0x262E30, (int) StateColor::Normal)));
    } else {
        GetTextCtrl()->Bind(wxEVT_KEY_DOWN, &ComboBox::keyDown, this);
    }
    drop.Bind(wxEVT_COMBOBOX, [this](wxCommandEvent &e) {
        SetSelection(e.GetInt());
        e.SetEventObject(this);
        e.SetId(GetId());
        GetEventHandler()->ProcessEvent(e);
    });
    drop.Bind(EVT_DISMISS, [this](auto &) {
        drop_down = false;
        wxCommandEvent e(wxEVT_COMBOBOX_CLOSEUP);
        GetEventHandler()->ProcessEvent(e);
    });
    for (int i = 0; i < n; ++i) Append(choices[i]);
}
References Label::Body_14, CB_NO_DROP_ICON, CB_NO_TEXT, TextInput::Create(), DD_STYLE_MASK, StateColor::Disabled, StateColor::Focused, StateColor::Hovered, keyDown(), n, StateColor::Normal, TextInput::SetLabelColor(), size, and style.
Member Function Documentation
Append() [1/2]
int ComboBox::Append (const wxString & item, const wxBitmap & bitmap, void * clientData)
{
    texts.push_back(item);
    icons.push_back(bitmap);
    datas.push_back(clientData);
    types.push_back(wxClientData_None);
    drop.Invalidate();
    return texts.size() - 1;
}
References datas, drop, icons, DropDown::Invalidate(), texts, and types.
Append() [2/2]
int ComboBox::Append (const wxString & item, const wxBitmap & bitmap = wxNullBitmap)
{
    return Append(item, bitmap, nullptr);
}
References Append().
Referenced by Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PresetComboBox::add_ams_filaments(), Append(), Slic3r::GUI::Choice::BUILD(), Slic3r::GUI::GridCellFilamentsEditor::Create(), Slic3r::GUI::GridCellChoiceEditor::Create(), Slic3r::GUI::PrintOptionsDialog::create_settings_group(), BitmapChoiceRenderer::CreateEditorCtrl(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update().
DoClear()
void ComboBox::DoClear () override protected virtual
{
    texts.clear();
    icons.clear();
    datas.clear();
    types.clear();
    drop.Invalidate(true);
}
References datas, drop, icons, DropDown::Invalidate(), texts, and types.
DoDeleteOneItem()
void ComboBox::DoDeleteOneItem (unsigned int pos) override protected
{
    if (pos >= texts.size()) return;
    texts.erase(texts.begin() + pos);
    icons.erase(icons.begin() + pos);
    datas.erase(datas.begin() + pos);
    types.erase(types.begin() + pos);
    drop.Invalidate(true);
}
References datas, drop, icons, DropDown::Invalidate(), texts, and types.
DoGetItemClientData()
void * ComboBox::DoGetItemClientData (unsigned int n) const override protected
{ return n < texts.size() ? datas[n] : NULL; }
References datas, n, NULL, and texts.
DoInsertItems()
int ComboBox::DoInsertItems (const wxArrayStringsAdapter & items, unsigned int pos, void ** clientData, wxClientDataType type) override protected virtual
{
    if (pos > texts.size()) return -1;
    for (int i = 0; i < items.GetCount(); ++i) {
        texts.insert(texts.begin() + pos, items[i]);
        icons.insert(icons.begin() + pos, wxNullBitmap);
        datas.insert(datas.begin() + pos, clientData ? clientData[i] : NULL);
        types.insert(types.begin() + pos, type);
        ++pos;
    }
    drop.Invalidate(true);
    return pos - 1;
}
References datas, drop, icons, DropDown::Invalidate(), NULL, texts, and types.
DoSetItemClientData()
void ComboBox::DoSetItemClientData (unsigned int n, void * data) override protected
{
    if (n < texts.size())
        datas[n] = data;
}
References datas, n, and texts.
GetCount()
unsigned int ComboBox::GetCount () const override
{ return texts.size(); }
References texts.
Referenced by Slic3r::GUI::PresetComboBox::add_ams_filaments(), Slic3r::GUI::Choice::get_value(), mouseWheelMoved(), Slic3r::GUI::Choice::set_value(), Slic3r::GUI::TabPresetComboBox::update_dirty(), and Slic3r::GUI::PresetComboBox::validate_selection().
GetDropDown()
DropDown & ComboBox::GetDropDown () inline
{ return drop; }
References drop.
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::GUI::Choice::BUILD(), and BitmapChoiceRenderer::CreateEditorCtrl().
GetItemBitmap()
wxBitmap ComboBox::GetItemBitmap (unsigned int n)
{ return icons[n]; }
References icons, and n.
GetLabel()
wxString ComboBox::GetLabel () const override
{
    if (GetTextCtrl()->IsShown() || text_off)
        return GetTextCtrl()->GetValue();
    else
        return TextInput::GetLabel();
}
References text_off.
Referenced by GetValue(), and Slic3r::GUI::PresetComboBox::update_ams_color().
GetSelection()
int ComboBox::GetSelection () const override
{ return drop.GetSelection(); }
References drop, and DropDown::GetSelection().
Referenced by Slic3r::GUI::PrintOptionsDialog::PrintOptionsDialog(), Slic3r::GUI::ExtrusionCalibration::get_bed_temp(), Slic3r::GUI::PlateSettingsDialog::get_bed_type_choice(), Slic3r::GUI::PlateSettingsDialog::get_print_seq_choice(), Slic3r::GUI::get_selection(), Slic3r::GUI::Choice::get_value(), Slic3r::GUI::PresetComboBox::is_selected_physical_printer(), keyDown(), mouseWheelMoved(), Slic3r::GUI::Plater::priv::on_select_bed_type(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::PrintOptionsDialog::set_ai_monitor_sensitivity(), Slic3r::GUI::PlaterPresetComboBox::switch_to_tab(), Slic3r::GUI::PresetComboBox::update(), and Slic3r::GUI::TabPresetComboBox::update_dirty().
GetString()
wxString ComboBox::GetString (unsigned int n) const override
{
    return n < texts.size() ? texts[n] : wxString{};
}
References n, and texts.
Referenced by Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::get_selection(), Slic3r::GUI::Plater::priv::on_select_preset(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::PlaterPresetComboBox::switch_to_tab(), Slic3r::GUI::PresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update_dirty(), and Slic3r::GUI::PresetComboBox::update_selection().
GetTextLabel()
wxString ComboBox::GetTextLabel () const
{
    return TextInput::GetLabel();
}
GetValue()
wxString ComboBox::GetValue () const
{
    return drop.GetSelection() >= 0 ? drop.GetValue() : GetLabel();
}
References drop, GetLabel(), DropDown::GetSelection(), and DropDown::GetValue().
Referenced by Slic3r::GUI::Choice::BUILD(), Slic3r::GUI::GridCellFilamentsEditor::EndEdit(), Slic3r::GUI::GridCellChoiceEditor::EndEdit(), Slic3r::GUI::ExtrusionCalibration::get_bed_type_incompatible(), Slic3r::GUI::Choice::get_value(), Slic3r::GUI::Choice::msw_rescale(), Slic3r::GUI::ExtrusionCalibration::on_click_cali(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::AMSMaterialsSetting::on_select_filament(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::ExtrusionCalibration::update_combobox_filaments(), and Slic3r::GUI::ExtrusionCalibration::update_filament_info().
keyDown()
void ComboBox::keyDown (wxKeyEvent & event) private
{
    switch (event.GetKeyCode()) {
        case WXK_RETURN:
        case WXK_SPACE:
            if (drop_down) {
                drop.DismissAndNotify();
            } else if (drop.HasDismissLongTime()) {
                drop.autoPosition();
                drop_down = true;
                drop.Popup();
                wxCommandEvent e(wxEVT_COMBOBOX_DROPDOWN);
                GetEventHandler()->ProcessEvent(e);
            }
            break;
        case WXK_UP:
        case WXK_DOWN:
        case WXK_LEFT:
        case WXK_RIGHT:
            if ((event.GetKeyCode() == WXK_UP || event.GetKeyCode() == WXK_LEFT) && GetSelection() > 0) {
                SetSelection(GetSelection() - 1);
            } else if ((event.GetKeyCode() == WXK_DOWN || event.GetKeyCode() == WXK_RIGHT) && GetSelection() + 1 < texts.size()) {
                SetSelection(GetSelection() + 1);
            } else {
                break;
            }
            sendComboBoxEvent();
            break;
        case WXK_TAB:
            HandleAsNavigationKey(event);
            break;
        default:
            event.Skip();
            break;
    }
}
References DropDown::autoPosition(), drop, drop_down, GetSelection(), DropDown::HasDismissLongTime(), sendComboBoxEvent(), SetSelection(), and texts.
Referenced by ComboBox().
mouseDown()
void ComboBox::mouseDown (wxMouseEvent & event) private
{
    SetFocus();
    if (drop_down) {
        drop.Hide();
    } else if (drop.HasDismissLongTime()) {
        drop.autoPosition();
        drop_down = true;
        drop.Popup(&drop);
        wxCommandEvent e(wxEVT_COMBOBOX_DROPDOWN);
        GetEventHandler()->ProcessEvent(e);
    }
}
References DropDown::autoPosition(), drop, drop_down, and DropDown::HasDismissLongTime().
mouseWheelMoved()
void ComboBox::mouseWheelMoved (wxMouseEvent & event) private
{
    event.Skip();
    if (drop_down) return;
    auto delta = event.GetWheelRotation() < 0 ? 1 : -1;
    unsigned int n = GetSelection() + delta;
    if (n < GetCount()) {
        SetSelection((int) n);
        sendComboBoxEvent();
    }
}
References drop_down, GetCount(), GetSelection(), n, sendComboBoxEvent(), and SetSelection().
OnEdit()
void ComboBox::OnEdit () override protected
{
    auto value = GetTextCtrl()->GetValue();
    SetValue(value);
}
References SetValue().
Rescale()
void ComboBox::Rescale () override virtual
{
    TextInput::Rescale();
    drop.Rescale();
}
References drop, DropDown::Rescale(), and TextInput::Rescale().
Referenced by Slic3r::GUI::PresetComboBox::msw_rescale().
SelectAndNotify()
void ComboBox::SelectAndNotify (int n)
{
    SetSelection(n);
    sendComboBoxEvent();
}
References n, sendComboBoxEvent(), and SetSelection().
sendComboBoxEvent()
void ComboBox::sendComboBoxEvent () protected
{
    wxCommandEvent event(wxEVT_COMBOBOX, GetId());
    event.SetEventObject(this);
    event.SetInt(drop.GetSelection());
    event.SetString(drop.GetValue());
    GetEventHandler()->ProcessEvent(event);
}
References drop, DropDown::GetSelection(), and DropDown::GetValue().
Referenced by keyDown(), mouseWheelMoved(), and SelectAndNotify().
SetFont()
bool ComboBox::SetFont (wxFont const & font) override virtual
{
    if (GetTextCtrl() && GetTextCtrl()->IsShown())
        return GetTextCtrl()->SetFont(font);
    else
        return TextInput::SetFont(font);
}
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox(), and Slic3r::GUI::GridCellChoiceEditor::Create().
SetItemBitmap()
void ComboBox::SetItemBitmap (unsigned int n, wxBitmap const & bitmap)
{
    if (n >= texts.size()) return;
    icons[n] = bitmap;
    drop.Invalidate();
}
References drop, icons, DropDown::Invalidate(), n, and texts.
Referenced by Slic3r::GUI::TabPresetComboBox::update_dirty().
SetLabel()
void ComboBox::SetLabel (const wxString & label) override
{
    if (GetTextCtrl()->IsShown() || text_off)
        GetTextCtrl()->SetValue(value);
    else
        TextInput::SetLabel(value);
}
References TextInput::SetLabel(), and text_off.
Referenced by SetSelection(), SetString(), and SetValue().
SetSelection()
void ComboBox::SetSelection (int n) override
{
    drop.SetSelection(n);
    SetLabel(drop.GetValue());
    if (drop.selection >= 0)
        SetIcon(icons[drop.selection]);
}
References drop, DropDown::GetValue(), icons, n, DropDown::selection, SetLabel(), and DropDown::SetSelection().
Referenced by Slic3r::GUI::GridCellFilamentsEditor::BeginEdit(), Slic3r::GUI::GridCellChoiceEditor::BeginEdit(), Slic3r::GUI::ExtrusionCalibration::create(), BitmapChoiceRenderer::CreateEditorCtrl(), keyDown(), mouseWheelMoved(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::PresetComboBox::OnSelect(), Slic3r::GUI::PlaterPresetComboBox::OnSelect(), Slic3r::GUI::TabPresetComboBox::OnSelect(), Slic3r::GUI::AMSMaterialsSetting::Popup(), SelectAndNotify(), Slic3r::GUI::Choice::set_selection(), Slic3r::GUI::Choice::set_value(), Slic3r::GUI::Choice::set_value(), Slic3r::GUI::PlateSettingsDialog::sync_bed_type(), Slic3r::GUI::PlateSettingsDialog::sync_print_seq(), Slic3r::GUI::ExtrusionCalibration::update_combobox_filaments(), Slic3r::GUI::TabPresetComboBox::update_dirty(), Slic3r::GUI::PrintOptionsDialog::update_options(), Slic3r::GUI::PresetComboBox::update_selection(), and Slic3r::GUI::SelectMachineDialog::update_user_printer().
SetString()
void ComboBox::SetString (unsigned int n, wxString const & value) override
{
    if (n >= texts.size()) return;
    texts[n]  = value;
    drop.Invalidate();
    if (n == drop.GetSelection()) SetLabel(value);
}
References drop, DropDown::GetSelection(), DropDown::Invalidate(), n, SetLabel(), and texts.
Referenced by Slic3r::GUI::TabPresetComboBox::update_dirty().
SetTextLabel()
void ComboBox::SetTextLabel (const wxString & label)
{
    TextInput::SetLabel(label);
}
References TextInput::SetLabel().
Referenced by Slic3r::GUI::Choice::BUILD(), and Slic3r::GUI::SelectMachineDialog::update_user_printer().
SetValue()
void ComboBox::SetValue (const wxString & value)
{
    drop.SetValue(value);
    SetLabel(value);
    if (drop.selection >= 0)
        SetIcon(icons[drop.selection]);
}
References drop, icons, DropDown::selection, SetLabel(), and DropDown::SetValue().
Referenced by OnEdit(), Slic3r::GUI::SelectMachineDialog::set_default(), Slic3r::GUI::Choice::set_selection(), Slic3r::GUI::Choice::set_value(), Slic3r::GUI::Choice::set_value(), and Slic3r::GUI::ExtrusionCalibration::update_combobox_filaments().
Member Data Documentation
datas
std::vector<void *> ComboBox::datas private
Referenced by Append(), DoClear(), DoDeleteOneItem(), DoGetItemClientData(), DoInsertItems(), and DoSetItemClientData().
drop
DropDown ComboBox::drop private
Referenced by Append(), DoClear(), DoDeleteOneItem(), DoInsertItems(), GetDropDown(), GetSelection(), GetValue(), keyDown(), mouseDown(), Rescale(), sendComboBoxEvent(), SetItemBitmap(), SetSelection(), SetString(), and SetValue().
drop_down
bool ComboBox::drop_down = false private
Referenced by keyDown(), mouseDown(), and mouseWheelMoved().
icons
std::vector<wxBitmap> ComboBox::icons private
Referenced by Append(), DoClear(), DoDeleteOneItem(), DoInsertItems(), GetItemBitmap(), SetItemBitmap(), SetSelection(), and SetValue().
text_off
bool ComboBox::text_off = false private
Referenced by GetLabel(), and SetLabel().
texts
std::vector<wxString> ComboBox::texts private
Referenced by Append(), DoClear(), DoDeleteOneItem(), DoGetItemClientData(), DoInsertItems(), DoSetItemClientData(), GetCount(), GetString(), keyDown(), SetItemBitmap(), and SetString().
types
std::vector<wxClientDataType> ComboBox::types private
Referenced by Append(), DoClear(), DoDeleteOneItem(), and DoInsertItems().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/ComboBox.hpp
src/slic3r/GUI/Widgets/ComboBox.cpp