OrcaSlicer: orgQhull::QhullPoints::iterator Class Reference
orgQhull::QhullPoints::iterator Class Reference
#include <src/qhull/src/libqhullcpp/QhullPoints.h>
Public Types
typedef std::random_access_iterator_tag iterator_category
typedef QhullPoint value_type
typedef value_type * pointer
typedef value_type & reference
typedef ptrdiff_t difference_type
Iterators
typedef coordT * base_type
typedef const coordT * iterator
typedef const coordT * const_iterator
typedef QhullPoint::iterator Iterator
typedef QhullPoint::const_iterator ConstIterator
Public Member Functions
iterator (const QhullPoints &ps)
iterator (const int pointDimension, coordT *c)
iterator (const Qhull &q, coordT *c)
iterator (const Qhull &q, int pointDimension, coordT *c)
iterator (QhullQh *qqh, coordT *c)
iterator (QhullQh *qqh, int pointDimension, coordT *c)
iterator (const iterator &other)
iterator & operator= (const iterator &other)
const QhullPoint & operator* () const
QhullPoint & operator* ()
const QhullPoint * operator-> () const
QhullPoint * operator-> ()
QhullPoint operator[] (countT idx) const
bool operator== (const iterator &o) const
bool operator!= (const iterator &o) const
bool operator< (const iterator &o) const
bool operator<= (const iterator &o) const
bool operator> (const iterator &o) const
bool operator>= (const iterator &o) const
bool operator== (const QhullPoints::const_iterator &o) const
bool operator!= (const QhullPoints::const_iterator &o) const
bool operator< (const QhullPoints::const_iterator &o) const
bool operator<= (const QhullPoints::const_iterator &o) const
bool operator> (const QhullPoints::const_iterator &o) const
bool operator>= (const QhullPoints::const_iterator &o) const
iterator & operator++ ()
iterator operator++ (int)
iterator & operator-- ()
iterator operator-- (int)
iterator & operator+= (countT idx)
iterator & operator-= (countT idx)
iterator operator+ (countT idx) const
iterator operator- (countT idx) const
difference_type operator- (iterator o) const
Conversions
std::vector< coordT > toStdVector () const
GetSet
const coordT * coordinates () const
0 if undefined
coordT * coordinates ()
0 if undefined
void defineAs (coordT *c)
void defineAs (int pointDimension, coordT *c)
void defineAs (QhullPoint &other)
int dimension () const
coordT * getBaseT () const
countT id () const
bool isValid () const
bool operator== (const QhullPoint &other) const
QhullPoint is equal if it has the same address and dimension If !qh_qh, returns true if dimension and coordinates are equal If qh_qh, returns true if the distance between points is less than qh_qh->distanceEpsilon()
bool operator!= (const QhullPoint &other) const
coordT & operator[] (int idx)
0 to hull_dim-1
QhullQh * qh ()
void setCoordinates (coordT *c)
void setDimension (int pointDimension)
foreach
iterator begin ()
const_iterator begin () const
const_iterator constBegin () const
const_iterator constEnd () const
int count ()
iterator end ()
const_iterator end () const
size_t size ()
Methods
void advancePoint (countT idx)
double distance (const QhullPoint &p) const
Return distance between two points.
IO
PrintPoint print (const char *message) const
PrintPoint printWithIdentifier (const char *message) const
Protected Attributes
Fields
coordT * point_coordinates
Pointer to first coordinate, 0 if undefined.
QhullQh * qh_qh
qhT for this instance of Qhull. 0 if undefined. operator==() returns true if points within sqrt(qh_qh->distanceEpsilon()) If !qh_qh, id() is -3, and operator==() requires equal coordinates
int point_dimension
Default dimension is qh_qh->hull_dim.
Detailed Description
Member Typedef Documentation
base_type
typedef coordT* orgQhull::QhullPoint::base_type inherited
const_iterator
typedef const coordT* orgQhull::QhullPoint::const_iterator inherited
ConstIterator
typedef QhullPoint::const_iterator orgQhull::QhullPoint::ConstIterator inherited
difference_type
typedef ptrdiff_t orgQhull::QhullPoints::iterator::difference_type
iterator
typedef const coordT* orgQhull::QhullPoint::iterator inherited
Iterator
typedef QhullPoint::iterator orgQhull::QhullPoint::Iterator inherited
iterator_category
typedef std::random_access_iterator_tag orgQhull::QhullPoints::iterator::iterator_category
pointer
typedef value_type* orgQhull::QhullPoints::iterator::pointer
reference
typedef value_type& orgQhull::QhullPoints::iterator::reference
value_type
typedef QhullPoint orgQhull::QhullPoints::iterator::value_type
Constructor & Destructor Documentation
iterator() [1/7]
orgQhull::QhullPoints::iterator::iterator (const QhullPoints & ps) inline explicit
: QhullPoint(ps.qh(), ps.dimension(), ps.coordinates()) {}
iterator() [2/7]
orgQhull::QhullPoints::iterator::iterator (const int pointDimension, coordT * c) inline
: QhullPoint(pointDimension, c) {}
iterator() [3/7]
orgQhull::QhullPoints::iterator::iterator (const Qhull & q, coordT * c) inline
: QhullPoint(q, c) {}
iterator() [4/7]
orgQhull::QhullPoints::iterator::iterator (const Qhull & q, int pointDimension, coordT * c) inline
: QhullPoint(q, pointDimension, c) {}
iterator() [5/7]
orgQhull::QhullPoints::iterator::iterator (QhullQh * qqh, coordT * c) inline
: QhullPoint(qqh, c) {}
iterator() [6/7]
orgQhull::QhullPoints::iterator::iterator (QhullQh * qqh, int pointDimension, coordT * c) inline
: QhullPoint(qqh, pointDimension, c) {}
iterator() [7/7]
orgQhull::QhullPoints::iterator::iterator (const iterator & other) inline
: QhullPoint(*other) {}
Member Function Documentation
advancePoint()
void orgQhull::QhullPoint::advancePoint (countT idx) inline inherited
{ if(point_coordinates) { point_coordinates += idx*point_dimension; } }
References orgQhull::QhullPoint::point_coordinates, and orgQhull::QhullPoint::point_dimension.
Referenced by operator++(), orgQhull::QhullPoints::const_iterator::operator++(), operator+=(), orgQhull::QhullPoints::const_iterator::operator+=(), operator--(), orgQhull::QhullPoints::const_iterator::operator--(), operator-=(), orgQhull::QhullPoints::const_iterator::operator-=(), operator[](), and orgQhull::QhullPoint_test::t_define().
begin() [1/2]
iterator orgQhull::QhullPoint::begin () inline inherited
{ return point_coordinates; }
References orgQhull::QhullPoint::point_coordinates.
Referenced by orgQhull::QhullPoint_test::t_const_iterator(), orgQhull::QhullPoint_test::t_construct(), and orgQhull::QhullPoint_test::t_iterator().
begin() [2/2]
const_iterator orgQhull::QhullPoint::begin () const inline inherited
{ return point_coordinates; }
References orgQhull::QhullPoint::point_coordinates.
constBegin()
const_iterator orgQhull::QhullPoint::constBegin () const inline inherited
{ return point_coordinates; }
References orgQhull::QhullPoint::point_coordinates.
Referenced by orgQhull::QhullPoint_test::t_const_iterator(), and orgQhull::QhullPoint_test::t_construct().
constEnd()
const_iterator orgQhull::QhullPoint::constEnd () const inline inherited
{ return (point_coordinates ? point_coordinates+point_dimension : 0); }
References orgQhull::QhullPoint::point_coordinates, and orgQhull::QhullPoint::point_dimension.
Referenced by orgQhull::QhullPoint_test::t_const_iterator(), and orgQhull::QhullPoint_test::t_construct().
coordinates() [1/2]
coordT * orgQhull::QhullPoint::coordinates () inline inherited
0 if undefined
References orgQhull::QhullPoint::point_coordinates.
coordinates() [2/2]
const coordT * orgQhull::QhullPoint::coordinates () const inline inherited
0 if undefined
References orgQhull::QhullPoint::point_coordinates.
Referenced by orgQhull::PointCoordinates::append(), orgQhull::QhullHyperplane::distance(), operator<<(), operator<<(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::QhullPoint_test::t_construct(), orgQhull::QhullPoint_test::t_define(), orgQhull::QhullPoints_test::t_iterator(), orgQhull::QhullPoint_test::t_operator(), and orgQhull::QhullPoint_test::t_readonly().
count()
int orgQhull::QhullPoint::count () inline inherited
{ return (point_coordinates ? point_dimension : 0); }
References orgQhull::QhullPoint::point_coordinates, and orgQhull::QhullPoint::point_dimension.
defineAs() [1/3]
void orgQhull::QhullPoint::defineAs (coordT * c) inline inherited
{ QHULL_ASSERT(point_dimension>0); point_coordinates= c; }
References orgQhull::QhullPoint::point_coordinates, orgQhull::QhullPoint::point_dimension, and QHULL_ASSERT.
Referenced by orgQhull::QhullPoints::const_iterator::operator=(), operator=(), orgQhull::QhullPoint_test::t_define(), orgQhull::QhullPoints_test::t_search(), orgQhull::QhullPoints::value(), and orgQhull::QhullPoints::value().
defineAs() [2/3]
void orgQhull::QhullPoint::defineAs (int pointDimension, coordT * c) inline inherited
{ QHULL_ASSERT(pointDimension>=0); point_coordinates= c; point_dimension= pointDimension; }
References orgQhull::QhullPoint::point_coordinates, orgQhull::QhullPoint::point_dimension, and QHULL_ASSERT.
defineAs() [3/3]
void orgQhull::QhullPoint::defineAs (QhullPoint & other) inline inherited
{ point_coordinates= other.point_coordinates; qh_qh= other.qh_qh; point_dimension= other.point_dimension; }
References orgQhull::QhullPoint::point_coordinates, orgQhull::QhullPoint::point_dimension, and orgQhull::QhullPoint::qh_qh.
dimension()
int orgQhull::QhullPoint::dimension () const inline inherited
{ return point_dimension; }
References orgQhull::QhullPoint::point_dimension.
Referenced by orgQhull::PointCoordinates::append(), orgQhull::QhullHyperplane::distance(), operator<<(), operator<<(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::QhullPointSet_test::t_const_iterator(), orgQhull::QhullPoint_test::t_construct(), orgQhull::QhullPoint_test::t_define(), orgQhull::QhullPoints_test::t_element(), orgQhull::QhullPointSet_test::t_element(), orgQhull::Qhull_test::t_getSet(), orgQhull::QhullFacet_test::t_getSet(), orgQhull::QhullPoints_test::t_iterator(), orgQhull::QhullPointSet_test::t_iterator(), orgQhull::QhullPoint_test::t_operator(), orgQhull::QhullPoint_test::t_qhullpoint_iterator(), and orgQhull::QhullPoint_test::t_readonly().
distance()
double orgQhull::QhullPoint::distance (const QhullPoint & p) const inherited
Return distance between two points.
{
    const coordT *c= point_coordinates;
    const coordT *c2= p.point_coordinates;
    int dim= point_dimension;
    if(dim!=p.point_dimension){
        throw QhullError(10075, "QhullPoint error: Expecting dimension %d for distance().  Got %d", dim, p.point_dimension);
    }
    if(!c || !c2){
        throw QhullError(10076, "QhullPoint error: Cannot compute distance() for undefined point");
    }
    double dist;
    switch(dim){
  case 2:
      dist= (c[0]-c2[0])*(c[0]-c2[0]) + (c[1]-c2[1])*(c[1]-c2[1]);
      break;
  case 3:
      dist= (c[0]-c2[0])*(c[0]-c2[0]) + (c[1]-c2[1])*(c[1]-c2[1]) + (c[2]-c2[2])*(c[2]-c2[2]);
      break;
  case 4:
      dist= (c[0]-c2[0])*(c[0]-c2[0]) + (c[1]-c2[1])*(c[1]-c2[1]) + (c[2]-c2[2])*(c[2]-c2[2]) + (c[3]-c2[3])*(c[3]-c2[3]);
      break;
  case 5:
      dist= (c[0]-c2[0])*(c[0]-c2[0]) + (c[1]-c2[1])*(c[1]-c2[1]) + (c[2]-c2[2])*(c[2]-c2[2]) + (c[3]-c2[3])*(c[3]-c2[3]) + (c[4]-c2[4])*(c[4]-c2[4]);
      break;
  case 6:
      dist= (c[0]-c2[0])*(c[0]-c2[0]) + (c[1]-c2[1])*(c[1]-c2[1]) + (c[2]-c2[2])*(c[2]-c2[2]) + (c[3]-c2[3])*(c[3]-c2[3]) + (c[4]-c2[4])*(c[4]-c2[4]) + (c[5]-c2[5])*(c[5]-c2[5]);
      break;
  case 7:
      dist= (c[0]-c2[0])*(c[0]-c2[0]) + (c[1]-c2[1])*(c[1]-c2[1]) + (c[2]-c2[2])*(c[2]-c2[2]) + (c[3]-c2[3])*(c[3]-c2[3]) + (c[4]-c2[4])*(c[4]-c2[4]) + (c[5]-c2[5])*(c[5]-c2[5]) + (c[6]-c2[6])*(c[6]-c2[6]);
      break;
  case 8:
      dist= (c[0]-c2[0])*(c[0]-c2[0]) + (c[1]-c2[1])*(c[1]-c2[1]) + (c[2]-c2[2])*(c[2]-c2[2]) + (c[3]-c2[3])*(c[3]-c2[3]) + (c[4]-c2[4])*(c[4]-c2[4]) + (c[5]-c2[5])*(c[5]-c2[5]) + (c[6]-c2[6])*(c[6]-c2[6]) + (c[7]-c2[7])*(c[7]-c2[7]);
      break;
  default:
      dist= 0.0;
      for(int k=dim; k--; ){
          dist += (*c - *c2) * (*c - *c2);
          ++c;
          ++c2;
      }
      break;
    }
    return sqrt(dist);
}//distance
References coordT, orgQhull::QhullPoint::point_coordinates, orgQhull::QhullPoint::point_dimension, and sqrt().
Referenced by orgQhull::QhullPoint_test::t_method().
end() [1/2]
iterator orgQhull::QhullPoint::end () inline inherited
{ return (point_coordinates ? point_coordinates+point_dimension : 0); }
References orgQhull::QhullPoint::point_coordinates, and orgQhull::QhullPoint::point_dimension.
Referenced by orgQhull::QhullPoint_test::t_const_iterator(), orgQhull::QhullPoint_test::t_construct(), and orgQhull::QhullPoint_test::t_iterator().
end() [2/2]
const_iterator orgQhull::QhullPoint::end () const inline inherited
{ return (point_coordinates ? point_coordinates+point_dimension : 0); }
References orgQhull::QhullPoint::point_coordinates, and orgQhull::QhullPoint::point_dimension.
getBaseT()
coordT * orgQhull::QhullPoint::getBaseT () const inline inherited
{ return point_coordinates; } // for QhullPointSet
References orgQhull::QhullPoint::point_coordinates.
id()
countT orgQhull::QhullPoint::id () const inline inherited
{ return qh_pointid(qh_qh, point_coordinates); } // NOerrors
References orgQhull::QhullPoint::point_coordinates, qh_pointid(), and orgQhull::QhullPoint::qh_qh.
Referenced by operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), orgQhull::QhullPoint_test::t_construct(), orgQhull::QhullVertex_test::t_getSet(), and orgQhull::QhullPoint_test::t_readonly().
isValid()
bool orgQhull::QhullPoint::isValid () const inline inherited
{ return (point_coordinates!=0 && point_dimension>0); };
References orgQhull::QhullPoint::point_coordinates, and orgQhull::QhullPoint::point_dimension.
Referenced by orgQhull::QhullPoint_test::t_construct(), and orgQhull::QhullPoint_test::t_readonly().
operator!=() [1/3]
bool orgQhull::QhullPoints::iterator::operator!= (const iterator & o) const inline
{ return !operator==(o); }
References operator==().
operator!=() [2/3]
bool orgQhull::QhullPoint::operator!= (const QhullPoint & other) const inline inherited
{ return ! operator==(other); }
References orgQhull::QhullPoint::operator==().
operator!=() [3/3]
bool orgQhull::QhullPoints::iterator::operator!= (const QhullPoints::const_iterator & o) const inline
{ return !operator==(reinterpret_cast<const iterator &>(o)); }
References operator==().
operator*() [1/2]
QhullPoint & orgQhull::QhullPoints::iterator::operator* () inline
{ return *this; }
operator*() [2/2]
const QhullPoint & orgQhull::QhullPoints::iterator::operator* () const inline
{ return *this; }
operator+()
iterator orgQhull::QhullPoints::iterator::operator+ (countT idx) const inline
{ iterator n= *this; n.advancePoint(idx); return n; }
References n.
operator++() [1/2]
iterator & orgQhull::QhullPoints::iterator::operator++ () inline
{ advancePoint(1); return *this; }
References orgQhull::QhullPoint::advancePoint().
operator++() [2/2]
iterator orgQhull::QhullPoints::iterator::operator++ (int) inline
{ iterator n= *this; operator++(); return iterator(n); }
References n, and operator++().
Referenced by operator++().
operator+=()
iterator & orgQhull::QhullPoints::iterator::operator+= (countT idx) inline
{ advancePoint(idx); return *this; }
References orgQhull::QhullPoint::advancePoint().
operator-() [1/2]
iterator orgQhull::QhullPoints::iterator::operator- (countT idx) const inline
{ iterator n= *this; n.advancePoint(-idx); return n; }
References n.
operator-() [2/2]
difference_type orgQhull::QhullPoints::iterator::operator- (iterator o) const inline
{ QHULL_ASSERT(qh_qh==o.qh_qh && point_dimension==o.point_dimension); return (point_dimension ? (point_coordinates-o.point_coordinates)/point_dimension : 0); }
References orgQhull::QhullPoint::point_coordinates, orgQhull::QhullPoint::point_dimension, orgQhull::QhullPoint::qh_qh, and QHULL_ASSERT.
operator--() [1/2]
iterator & orgQhull::QhullPoints::iterator::operator-- () inline
{ advancePoint(-1); return *this; }
References orgQhull::QhullPoint::advancePoint().
operator--() [2/2]
iterator orgQhull::QhullPoints::iterator::operator-- (int) inline
{ iterator n= *this; operator--(); return iterator(n); }
References n, and operator--().
Referenced by operator--().
operator-=()
iterator & orgQhull::QhullPoints::iterator::operator-= (countT idx) inline
{ advancePoint(-idx); return *this; }
References orgQhull::QhullPoint::advancePoint().
operator->() [1/2]
QhullPoint * orgQhull::QhullPoints::iterator::operator-> () inline
{ return this; }
operator->() [2/2]
const QhullPoint * orgQhull::QhullPoints::iterator::operator-> () const inline
{ return this; }
operator<() [1/2]
bool orgQhull::QhullPoints::iterator::operator< (const iterator & o) const inline
{ QHULL_ASSERT(qh_qh==o.qh_qh); return point_coordinates < o.point_coordinates; }
References orgQhull::QhullPoint::point_coordinates, orgQhull::QhullPoint::qh_qh, and QHULL_ASSERT.
operator<() [2/2]
bool orgQhull::QhullPoints::iterator::operator< (const QhullPoints::const_iterator & o) const inline
{ QHULL_ASSERT(qh_qh==reinterpret_cast<const iterator &>(o).qh_qh); return point_coordinates < reinterpret_cast<const iterator &>(o).point_coordinates; }
References orgQhull::QhullPoint::qh_qh, and QHULL_ASSERT.
operator<=() [1/2]
bool orgQhull::QhullPoints::iterator::operator<= (const iterator & o) const inline
{ QHULL_ASSERT(qh_qh==o.qh_qh); return point_coordinates <= o.point_coordinates; }
References orgQhull::QhullPoint::point_coordinates, orgQhull::QhullPoint::qh_qh, and QHULL_ASSERT.
operator<=() [2/2]
bool orgQhull::QhullPoints::iterator::operator<= (const QhullPoints::const_iterator & o) const inline
{ QHULL_ASSERT(qh_qh==reinterpret_cast<const iterator &>(o).qh_qh); return point_coordinates <= reinterpret_cast<const iterator &>(o).point_coordinates; }
References orgQhull::QhullPoint::qh_qh, and QHULL_ASSERT.
operator=()
iterator & orgQhull::QhullPoints::iterator::operator= (const iterator & other) inline
{ defineAs(const_cast<iterator &>(other)); return *this; }
References orgQhull::QhullPoint::defineAs().
operator==() [1/3]
bool orgQhull::QhullPoints::iterator::operator== (const iterator & o) const inline
{ QHULL_ASSERT(qh_qh==o.qh_qh); return (point_coordinates==o.point_coordinates && point_dimension==o.point_dimension); }
References orgQhull::QhullPoint::point_coordinates, orgQhull::QhullPoint::point_dimension, orgQhull::QhullPoint::qh_qh, and QHULL_ASSERT.
Referenced by operator!=(), and operator!=().
operator==() [2/3]
bool orgQhull::QhullPoint::operator== (const QhullPoint & other) const inherited
QhullPoint is equal if it has the same address and dimension If !qh_qh, returns true if dimension and coordinates are equal If qh_qh, returns true if the distance between points is less than qh_qh->distanceEpsilon()
{
    if(point_dimension!=other.point_dimension){
        return false;
    }
    const coordT *c= point_coordinates;
    const coordT *c2= other.point_coordinates;
    if(c==c2){
        return true;
    }
    if(!c || !c2){
        return false;
    }
    if(!qh_qh || qh_qh->hull_dim==0){
        for(int k= point_dimension; k--; ){
            if(*c++ != *c2++){
                return false;
            }
        }
        return true;
    }
    double dist2= 0.0;
    for(int k= point_dimension; k--; ){
        double diff= *c++ - *c2++;
        dist2 += diff*diff;
    }
    dist2= sqrt(dist2);
    return (dist2 < qh_qh->distanceEpsilon());
}//operator==
References coordT, qhT::hull_dim, orgQhull::QhullPoint::point_coordinates, orgQhull::QhullPoint::point_dimension, orgQhull::QhullPoint::qh_qh, and sqrt().
Referenced by orgQhull::QhullPoint::operator!=().
operator==() [3/3]
bool orgQhull::QhullPoints::iterator::operator== (const QhullPoints::const_iterator & o) const inline
{ QHULL_ASSERT(qh_qh==reinterpret_cast<const iterator &>(o).qh_qh); return (point_coordinates==reinterpret_cast<const iterator &>(o).point_coordinates && point_dimension==reinterpret_cast<const iterator &>(o).point_dimension); }
References orgQhull::QhullPoint::point_coordinates, orgQhull::QhullPoint::point_dimension, orgQhull::QhullPoint::qh_qh, and QHULL_ASSERT.
operator>() [1/2]
bool orgQhull::QhullPoints::iterator::operator> (const iterator & o) const inline
{ QHULL_ASSERT(qh_qh==o.qh_qh); return point_coordinates > o.point_coordinates; }
References orgQhull::QhullPoint::point_coordinates, orgQhull::QhullPoint::qh_qh, and QHULL_ASSERT.
operator>() [2/2]
bool orgQhull::QhullPoints::iterator::operator> (const QhullPoints::const_iterator & o) const inline
{ QHULL_ASSERT(qh_qh==reinterpret_cast<const iterator &>(o).qh_qh); return point_coordinates > reinterpret_cast<const iterator &>(o).point_coordinates; }
References orgQhull::QhullPoint::point_coordinates, orgQhull::QhullPoint::qh_qh, and QHULL_ASSERT.
operator>=() [1/2]
bool orgQhull::QhullPoints::iterator::operator>= (const iterator & o) const inline
{ QHULL_ASSERT(qh_qh==o.qh_qh); return point_coordinates >= o.point_coordinates; }
References orgQhull::QhullPoint::point_coordinates, orgQhull::QhullPoint::qh_qh, and QHULL_ASSERT.
operator>=() [2/2]
bool orgQhull::QhullPoints::iterator::operator>= (const QhullPoints::const_iterator & o) const inline
{ QHULL_ASSERT(qh_qh==reinterpret_cast<const iterator &>(o).qh_qh); return point_coordinates >= reinterpret_cast<const iterator &>(o).point_coordinates; }
References orgQhull::QhullPoint::point_coordinates, orgQhull::QhullPoint::qh_qh, and QHULL_ASSERT.
operator[]() [1/2]
QhullPoint orgQhull::QhullPoints::iterator::operator[] (countT idx) const inline
{ QhullPoint result= *this; result.advancePoint(idx); return result; }
References orgQhull::QhullPoint::advancePoint().
operator[]() [2/2]
coordT & orgQhull::QhullPoint::operator[] (int idx) inline inherited
0 to hull_dim-1
References orgQhull::QhullPoint::point_coordinates, orgQhull::QhullPoint::point_dimension, and QHULL_ASSERT.
print()
PrintPoint orgQhull::QhullPoint::print (const char * message) const inline inherited
{ return PrintPoint(message, false, *this); }
Referenced by operator<<(), operator<<(), operator<<(), orgQhull::QhullFacet_test::t_getSet(), and orgQhull::QhullPoint_test::t_io().
printWithIdentifier()
PrintPoint orgQhull::QhullPoint::printWithIdentifier (const char * message) const inline inherited
{ return PrintPoint(message, true, *this); }
Referenced by operator<<(), and orgQhull::QhullPoint_test::t_io().
qh()
QhullQh * orgQhull::QhullPoint::qh () inline inherited
{ return qh_qh; }
References orgQhull::QhullPoint::qh_qh.
Referenced by orgQhull::QhullPoint_test::t_construct(), and orgQhull::QhullPoint_test::t_readonly().
setCoordinates()
void orgQhull::QhullPoint::setCoordinates (coordT * c) inline inherited
{ point_coordinates= c; }
References orgQhull::QhullPoint::point_coordinates.
Referenced by orgQhull::QhullPoint_test::t_define().
setDimension()
void orgQhull::QhullPoint::setDimension (int pointDimension) inline inherited
{ point_dimension= pointDimension; }
References orgQhull::QhullPoint::point_dimension.
Referenced by orgQhull::Qhull::inputOrigin(), and orgQhull::QhullPoint_test::t_define().
size()
size_t orgQhull::QhullPoint::size () inline inherited
{ return (size_t)(point_coordinates ? point_dimension : 0); }
References orgQhull::QhullPoint::point_coordinates, and orgQhull::QhullPoint::point_dimension.
toStdVector()
std::vector< coordT > orgQhull::QhullPoint::toStdVector () const inherited
{
    QhullPointIterator i(*this);
    std::vector<coordT> vs;
    while(i.hasNext()){
        vs.push_back(i.next());
    }
    return vs;
}//toStdVector
Referenced by orgQhull::QhullPoint_test::t_convert().
Member Data Documentation
point_coordinates
coordT* orgQhull::QhullPoint::point_coordinates protected inherited
Pointer to first coordinate, 0 if undefined.
Referenced by orgQhull::QhullPoint::advancePoint(), orgQhull::QhullPoint::begin(), orgQhull::QhullPoint::begin(), orgQhull::QhullPoint::constBegin(), orgQhull::QhullPoint::constEnd(), orgQhull::QhullPoint::coordinates(), orgQhull::QhullPoint::coordinates(), orgQhull::QhullPoint::count(), orgQhull::QhullPoint::defineAs(), orgQhull::QhullPoint::defineAs(), orgQhull::QhullPoint::defineAs(), orgQhull::QhullPoint::distance(), orgQhull::QhullPoint::end(), orgQhull::QhullPoint::end(), orgQhull::QhullPoint::getBaseT(), orgQhull::QhullPoint::id(), orgQhull::QhullPoint::isValid(), orgQhull::QhullPoints::const_iterator::operator-(), operator-(), orgQhull::QhullPoints::const_iterator::operator<(), operator<(), orgQhull::QhullPoints::const_iterator::operator<=(), operator<=(), orgQhull::QhullPoint::operator=(), orgQhull::QhullPoints::const_iterator::operator==(), operator==(), orgQhull::QhullPoint::operator==(), operator==(), orgQhull::QhullPoints::const_iterator::operator>(), operator>(), operator>(), orgQhull::QhullPoints::const_iterator::operator>=(), operator>=(), operator>=(), orgQhull::QhullPoint::operator[](), orgQhull::QhullPoint::operator[](), orgQhull::QhullPoint::setCoordinates(), and orgQhull::QhullPoint::size().
point_dimension
int orgQhull::QhullPoint::point_dimension protected inherited
Default dimension is qh_qh->hull_dim.
Referenced by orgQhull::QhullPoint::advancePoint(), orgQhull::QhullPoint::constEnd(), orgQhull::QhullPoint::count(), orgQhull::QhullPoint::defineAs(), orgQhull::QhullPoint::defineAs(), orgQhull::QhullPoint::defineAs(), orgQhull::QhullPoint::dimension(), orgQhull::QhullPoint::distance(), orgQhull::QhullPoint::end(), orgQhull::QhullPoint::end(), orgQhull::QhullPoint::isValid(), orgQhull::QhullPoints::const_iterator::operator-(), operator-(), orgQhull::QhullPoint::operator=(), orgQhull::QhullPoints::const_iterator::operator==(), operator==(), orgQhull::QhullPoint::operator==(), operator==(), orgQhull::QhullPoint::operator[](), orgQhull::QhullPoint::operator[](), orgQhull::QhullPoint::setDimension(), and orgQhull::QhullPoint::size().
qh_qh
QhullQh* orgQhull::QhullPoint::qh_qh protected inherited
qhT for this instance of Qhull. 0 if undefined. operator==() returns true if points within sqrt(qh_qh->distanceEpsilon()) If !qh_qh, id() is -3, and operator==() requires equal coordinates
Referenced by orgQhull::QhullPoint::defineAs(), orgQhull::QhullPoint::id(), orgQhull::QhullPoints::const_iterator::operator-(), operator-(), orgQhull::QhullPoints::const_iterator::operator<(), operator<(), operator<(), orgQhull::QhullPoints::const_iterator::operator<=(), operator<=(), operator<=(), orgQhull::QhullPoint::operator=(), orgQhull::QhullPoints::const_iterator::operator==(), operator==(), orgQhull::QhullPoint::operator==(), operator==(), orgQhull::QhullPoints::const_iterator::operator>(), operator>(), operator>(), orgQhull::QhullPoints::const_iterator::operator>=(), operator>=(), operator>=(), and orgQhull::QhullPoint::qh().
The documentation for this class was generated from the following file:
src/qhull/src/libqhullcpp/QhullPoints.h