OrcaSlicer: Slic3r::GUI::Line Class Reference
Slic3r::GUI::Line Class Reference
Represents option lines.
#include <src/slic3r/GUI/OptionsGroup.hpp>
Public Member Functions
std::string & get_first_option_key ()
void append_option (const Option &option)
void append_widget (const widget_t widget)
Line (wxString label, wxString tooltip)
Line ()
bool is_separator () const
const std::vector< widget_t > & get_extra_widgets () const
const std::vector< Option > & get_options () const
bool * get_blink_ptr ()
Public Attributes
wxString label
wxString label_tooltip
std::string label_path
bool undo_to_sys {false}
bool toggle_visible {true}
size_t full_width {0}
wxColour * full_Label_color {nullptr}
bool blink {false}
widget_t widget {nullptr}
std::function< wxWindow *(wxWindow *)> near_label_widget { nullptr }
wxWindow * near_label_widget_win {nullptr}
wxSizer * widget_sizer {nullptr}
wxSizer * extra_widget_sizer {nullptr}
wxWindow * extra_widget_win {nullptr}
Private Attributes
bool m_is_separator { false }
std::vector< Option > m_options
std::vector< widget_t > m_extra_widgets
{std::vector<Option>()};
Detailed Description
Represents option lines.
Constructor & Destructor Documentation
Line() [1/2]
Slic3r::GUI::Line::Line (wxString label, wxString tooltip) inline
                                         :
    label(_(label)), label_tooltip(_(tooltip)) {}
Line() [2/2]
Slic3r::GUI::Line::Line () inline
: m_is_separator(true) {}
Member Function Documentation
append_option()
void Slic3r::GUI::Line::append_option (const Option & option) inline
{
        m_options.push_back(option);
    }
References m_options.
Referenced by Slic3r::GUI::TabPrinter::append_option_line(), Slic3r::GUI::TabPrint::build(), Slic3r::GUI::TabFilament::build(), and Slic3r::GUI::TabPrinter::build_fff().
append_widget()
void Slic3r::GUI::Line::append_widget (const widget_t widget) inline
{
    m_extra_widgets.push_back(widget);
    }
References m_extra_widgets, and widget.
Referenced by Slic3r::GUI::Tab::build_preset_description_line(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
get_blink_ptr()
bool * Slic3r::GUI::Line::get_blink_ptr () inline
{ return &blink; }
References blink.
get_extra_widgets()
const std::vector< widget_t > & Slic3r::GUI::Line::get_extra_widgets () const inline
{return m_extra_widgets;}
References m_extra_widgets.
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::append_line(), and Slic3r::GUI::OG_CustomCtrl::get_pos().
get_first_option_key()
std::string & Slic3r::GUI::Line::get_first_option_key () inline
{
        return m_options[0].opt_id;
    }
References m_options.
get_options()
const std::vector< Option > & Slic3r::GUI::Line::get_options () const inline
{ return m_options; }
References m_options.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::CtrlLine(), Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::append_line(), Slic3r::GUI::OG_CustomCtrl::correct_window_position(), and Slic3r::GUI::OG_CustomCtrl::get_pos().
is_separator()
bool Slic3r::GUI::Line::is_separator () const inline
{ return m_is_separator; }
References m_is_separator.
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), and Slic3r::GUI::OG_CustomCtrl::CtrlLine::is_separator().
Member Data Documentation
blink
bool Slic3r::GUI::Line::blink {false}
Referenced by get_blink_ptr().
extra_widget_sizer
wxSizer* Slic3r::GUI::Line::extra_widget_sizer {nullptr}
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), and Slic3r::GUI::OG_CustomCtrl::correct_widgets_position().
extra_widget_win
wxWindow* Slic3r::GUI::Line::extra_widget_win {nullptr}
full_Label_color
wxColour* Slic3r::GUI::Line::full_Label_color {nullptr}
Referenced by Slic3r::GUI::Tab::create_line_with_widget().
full_width
size_t Slic3r::GUI::Line::full_width {0}
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::append_line(), Slic3r::GUI::BedShapePanel::build_panel(), Slic3r::GUI::Tab::build_preset_description_line(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::GUI::BedShapePanel::init_model_panel(), and Slic3r::GUI::BedShapePanel::init_texture_panel().
label
wxString Slic3r::GUI::Line::label
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OG_CustomCtrl::get_pos(), and Slic3r::GUI::OG_CustomCtrl::OnMotion().
label_path
std::string Slic3r::GUI::Line::label_path
Referenced by Slic3r::GUI::TabPrint::build(), Slic3r::GUI::TabFilament::build(), and Slic3r::GUI::Tab::create_line_with_widget().
label_tooltip
wxString Slic3r::GUI::Line::label_tooltip
Referenced by Slic3r::GUI::OptionsGroup::activate_line().
m_extra_widgets
std::vector<widget_t> Slic3r::GUI::Line::m_extra_widgets private
{std::vector<Option>()};
Referenced by append_widget(), and get_extra_widgets().
m_is_separator
bool Slic3r::GUI::Line::m_is_separator { false } private
Referenced by is_separator().
m_options
std::vector<Option> Slic3r::GUI::Line::m_options private
Referenced by append_option(), get_first_option_key(), and get_options().
near_label_widget
std::function<wxWindow*(wxWindow*)> Slic3r::GUI::Line::near_label_widget { nullptr }
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), and Slic3r::GUI::TabFilament::add_filament_overrides_page().
near_label_widget_win
wxWindow* Slic3r::GUI::Line::near_label_widget_win {nullptr}
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), and Slic3r::GUI::OG_CustomCtrl::get_pos().
toggle_visible
bool Slic3r::GUI::Line::toggle_visible {true}
Referenced by Slic3r::GUI::Tab::toggle_line().
undo_to_sys
bool Slic3r::GUI::Line::undo_to_sys {false}
widget
widget_t Slic3r::GUI::Line::widget {nullptr}
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::OptionsGroup::append_line(), append_widget(), Slic3r::GUI::Tab::create_line_with_widget(), and Slic3r::GUI::OG_CustomCtrl::get_pos().
widget_sizer
wxSizer* Slic3r::GUI::Line::widget_sizer {nullptr}
Referenced by Slic3r::GUI::OptionsGroup::activate_line(), and Slic3r::GUI::OG_CustomCtrl::get_pos().
The documentation for this class was generated from the following file:
src/slic3r/GUI/OptionsGroup.hpp