OrcaSlicer: orgQhull::QhullRidge Class Reference
orgQhull::QhullRidge Class Reference
#include <src/qhull/src/libqhullcpp/QhullRidge.h>
Classes
struct PrintRidge
Public Types
Defined here
typedef ridgeT * base_type
Public Member Functions
Constructors
QhullRidge ()
QhullRidge (const Qhull &q)
QhullRidge (const Qhull &q, ridgeT *r)
QhullRidge (QhullQh *qqh)
QhullRidge (QhullQh *qqh, ridgeT *r)
QhullRidge (const QhullRidge &other)
QhullRidge & operator= (const QhullRidge &other)
~QhullRidge ()
GetSet
QhullFacet bottomFacet () const
int dimension () const
ridgeT * getBaseT () const
For QhullSet<QhullRidge>
ridgeT * getRidgeT () const
countT id () const
bool isValid () const
bool operator== (const QhullRidge &other) const
bool operator!= (const QhullRidge &other) const
QhullFacet otherFacet (const QhullFacet &f) const
QhullFacet topFacet () const
foreach
bool hasNextRidge3d (const QhullFacet &f) const
Return True if nextRidge3d Simplicial facets may have incomplete ridgeSets Does not use qh_errexit()
QhullRidge nextRidge3d (const QhullFacet &f) const
QhullRidge nextRidge3d (const QhullFacet &f, QhullVertex *nextVertex) const
Return next ridge and optional vertex for a 3d facet and ridge Does not use qh_errexit()
QhullVertexSet vertices () const
IO
PrintRidge print (const char *message) const
Private Attributes
Fields
ridgeT * qh_ridge
Corresponding ridgeT, never 0.
QhullQh * qh_qh
QhullQh/qhT for ridgeT, may be 0.
Static Private Attributes
Class objects
static ridgeT s_empty_ridge
Detailed Description
Member Typedef Documentation
base_type
typedef ridgeT* orgQhull::QhullRidge::base_type
Constructor & Destructor Documentation
QhullRidge() [1/6]
orgQhull::QhullRidge::QhullRidge () inline
: qh_ridge(&s_empty_ridge), qh_qh(0) {}
Referenced by nextRidge3d().
QhullRidge() [2/6]
orgQhull::QhullRidge::QhullRidge (const Qhull & q) explicit
: qh_ridge(&s_empty_ridge)
, qh_qh(q.qh())
{
}//Default
QhullRidge() [3/6]
orgQhull::QhullRidge::QhullRidge (const Qhull & q, ridgeT * r)
: qh_ridge(r ? r : &s_empty_ridge)
, qh_qh(q.qh())
{
}//ridgeT
QhullRidge() [4/6]
orgQhull::QhullRidge::QhullRidge (QhullQh * qqh) inline explicit
: qh_ridge(&s_empty_ridge), qh_qh(qqh) {}
QhullRidge() [5/6]
orgQhull::QhullRidge::QhullRidge (QhullQh * qqh, ridgeT * r) inline
: qh_ridge(r ? r : &s_empty_ridge), qh_qh(qqh) {}
QhullRidge() [6/6]
orgQhull::QhullRidge::QhullRidge (const QhullRidge & other) inline
: qh_ridge(other.qh_ridge), qh_qh(other.qh_qh) {}
~QhullRidge()
orgQhull::QhullRidge::~QhullRidge () inline
{}
Member Function Documentation
bottomFacet()
QhullFacet orgQhull::QhullRidge::bottomFacet () const inline
{ return QhullFacet(qh_qh, qh_ridge->bottom); }
References ridgeT::bottom, qh_qh, and qh_ridge.
Referenced by operator<<(), and orgQhull::QhullRidge_test::t_getSet().
dimension()
int orgQhull::QhullRidge::dimension () const inline
{ return ((qh_qh && qh_qh->hull_dim) ? qh_qh->hull_dim-1 : 0); }
References qhT::hull_dim, and qh_qh.
Referenced by orgQhull::QhullRidge_test::t_construct(), and orgQhull::QhullRidge_test::t_getSet().
getBaseT()
ridgeT * orgQhull::QhullRidge::getBaseT () const inline
For QhullSet<QhullRidge>
References getRidgeT().
Referenced by orgQhull::QhullRidge_test::t_construct().
getRidgeT()
ridgeT * orgQhull::QhullRidge::getRidgeT () const inline
{ return qh_ridge; }
References qh_ridge.
Referenced by getBaseT(), hasNextRidge3d(), nextRidge3d(), operator<<(), operator<<(), and orgQhull::QhullRidge_test::t_construct().
hasNextRidge3d()
bool orgQhull::QhullRidge::hasNextRidge3d (const QhullFacet & f) const
Return True if nextRidge3d Simplicial facets may have incomplete ridgeSets Does not use qh_errexit()
{
    if(!qh_qh){
        return false;
    }
    vertexT *v= 0;
    // Does not call qh_errexit(), TRY_QHULL_ not needed
    ridgeT *ridge= qh_nextridge3d(getRidgeT(), f.getFacetT(), &v);
    return (ridge!=0);
}//hasNextRidge3d
References orgQhull::QhullFacet::getFacetT(), getRidgeT(), qh_nextridge3d(), and qh_qh.
Referenced by orgQhull::QhullFacet_test::t_foreach(), and orgQhull::QhullRidge_test::t_foreach().
id()
countT orgQhull::QhullRidge::id () const inline
{ return qh_ridge->id; }
References ridgeT::id, and qh_ridge.
Referenced by operator<<(), operator<<(), orgQhull::QhullFacet_test::t_foreach(), and orgQhull::QhullRidge_test::t_getSet().
isValid()
bool orgQhull::QhullRidge::isValid () const inline
{ return (qh_qh && qh_ridge != &s_empty_ridge); }
References qh_qh, qh_ridge, and s_empty_ridge.
Referenced by orgQhull::QhullRidge_test::t_construct(), and orgQhull::QhullRidge_test::t_getSet().
nextRidge3d() [1/2]
QhullRidge orgQhull::QhullRidge::nextRidge3d (const QhullFacet & f) const inline
{ return nextRidge3d(f, 0); }
References nextRidge3d().
Referenced by nextRidge3d(), orgQhull::QhullFacet_test::t_foreach(), and orgQhull::QhullRidge_test::t_foreach().
nextRidge3d() [2/2]
QhullRidge orgQhull::QhullRidge::nextRidge3d (const QhullFacet & f, QhullVertex * nextVertex) const
Return next ridge and optional vertex for a 3d facet and ridge Does not use qh_errexit()
{
    vertexT *v= 0;
    ridgeT *ridge= 0;
    if(qh_qh){
        // Does not call qh_errexit(), TRY_QHULL_ not needed
        ridge= qh_nextridge3d(getRidgeT(), f.getFacetT(), &v);
        if(!ridge){
            throw QhullError(10030, "Qhull error nextRidge3d:  missing next ridge for facet %d ridge %d.  Does facet contain ridge?", f.id(), id());
        }
    }
    if(nextVertex!=0){
        *nextVertex= QhullVertex(qh_qh, v);
    }
    return QhullRidge(qh_qh, ridge);
}//nextRidge3d
References QhullRidge(), orgQhull::QhullFacet::getFacetT(), getRidgeT(), orgQhull::QhullFacet::id(), qh_nextridge3d(), and qh_qh.
operator!=()
bool orgQhull::QhullRidge::operator!= (const QhullRidge & other) const inline
{ return !operator==(other); }
References operator==().
operator=()
QhullRidge & orgQhull::QhullRidge::operator= (const QhullRidge & other) inline
{ qh_ridge= other.qh_ridge; qh_qh= other.qh_qh; return *this; }
References qh_qh, and qh_ridge.
operator==()
bool orgQhull::QhullRidge::operator== (const QhullRidge & other) const inline
{ return qh_ridge==other.qh_ridge; }
References qh_ridge.
Referenced by operator!=().
otherFacet()
QhullFacet orgQhull::QhullRidge::otherFacet (const QhullFacet & f) const inline
{ return QhullFacet(qh_qh, (qh_ridge->top==f.getFacetT() ? qh_ridge->bottom : qh_ridge->top)); }
References ridgeT::bottom, orgQhull::QhullFacet::getFacetT(), qh_qh, qh_ridge, and ridgeT::top.
Referenced by operator<<(), and orgQhull::QhullRidge_test::t_getSet().
print()
PrintRidge orgQhull::QhullRidge::print (const char * message) const inline
{ return PrintRidge(message, *this); }
Referenced by operator<<(), operator<<(), and orgQhull::QhullRidge_test::t_io().
topFacet()
QhullFacet orgQhull::QhullRidge::topFacet () const inline
{ return QhullFacet(qh_qh, qh_ridge->top); }
References qh_qh, qh_ridge, and ridgeT::top.
Referenced by operator<<(), and orgQhull::QhullRidge_test::t_getSet().
vertices()
QhullVertexSet orgQhull::QhullRidge::vertices () const inline
{ return QhullVertexSet(qh_qh, qh_ridge->vertices); }
References qh_qh, qh_ridge, and ridgeT::vertices.
Referenced by operator<<(), and orgQhull::QhullRidge_test::t_foreach().
Member Data Documentation
qh_qh
QhullQh* orgQhull::QhullRidge::qh_qh private
QhullQh/qhT for ridgeT, may be 0.
Referenced by bottomFacet(), dimension(), hasNextRidge3d(), isValid(), nextRidge3d(), operator=(), otherFacet(), topFacet(), and vertices().
qh_ridge
ridgeT* orgQhull::QhullRidge::qh_ridge private
Corresponding ridgeT, never 0.
Referenced by bottomFacet(), getRidgeT(), id(), isValid(), operator=(), operator==(), otherFacet(), topFacet(), and vertices().
s_empty_ridge
ridgeT orgQhull::QhullRidge::s_empty_ridge static private
Initial value:
= {0,0,0,0,0,
                0,0}
Referenced by isValid().
The documentation for this class was generated from the following files:
src/qhull/src/libqhullcpp/QhullRidge.h
src/qhull/src/libqhullcpp/QhullRidge.cpp