OrcaSlicer: SpinInput Class Reference
SpinInput Class Reference
#include <src/slic3r/GUI/Widgets/SpinInput.hpp>
Public Member Functions
SpinInput ()
SpinInput (wxWindow *parent, wxString text, wxString label="", const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0, int min=0, int max=100, int initial=0)
void Create (wxWindow *parent, wxString text, wxString label="", const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0, int min=0, int max=100, int initial=0)
void SetCornerRadius (double radius)
void SetLabel (const wxString &label) wxOVERRIDE
void SetLabelColor (StateColor const &color)
void SetTextColor (StateColor const &color)
void SetSize (wxSize const &size)
void Rescale ()
virtual bool Enable (bool enable=true) wxOVERRIDE
wxTextCtrl * GetTextCtrl ()
void SetValue (const wxString &text)
void SetValue (int value)
int GetValue () const
void SetRange (int min, int max)
Protected Member Functions
void DoSetToolTipText (wxString const &tip) override
Private Member Functions
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void messureSize ()
Button * createButton (bool inc)
void mouseWheelMoved (wxMouseEvent &event)
void keyPressed (wxKeyEvent &event)
void onTimer (wxTimerEvent &evnet)
void onTextLostFocus (wxEvent &event)
void onTextEnter (wxCommandEvent &event)
void sendSpinEvent ()
Private Attributes
wxSize labelSize
StateColor label_color
StateColor text_color
wxTextCtrl * text_ctrl
Button * button_inc
Button * button_dec
wxTimer timer
int val
int min
int max
int delta
Static Private Attributes
static const int SpinInputWidth = 200
static const int SpinInputHeight = 50
Detailed Description
Constructor & Destructor Documentation
SpinInput() [1/2]
SpinInput::SpinInput ()
    : label_color(std::make_pair(0x909090, (int) StateColor::Disabled), std::make_pair(0x6B6B6B, (int) StateColor::Normal))
    , text_color(std::make_pair(0x909090, (int) StateColor::Disabled), std::make_pair(0x262E30, (int) StateColor::Normal))
{
    radius = 0;
    border_width     = 1;
    border_color     = StateColor(std::make_pair(0xDBDBDB, (int) StateColor::Disabled), std::make_pair(0x009688, (int) StateColor::Hovered),
                              std::make_pair(0xDBDBDB, (int) StateColor::Normal));
    background_color = StateColor(std::make_pair(0xF0F0F1, (int) StateColor::Disabled), std::make_pair(*wxWHITE, (int) StateColor::Normal));
}
References StateColor::Disabled, StateColor::Hovered, and StateColor::Normal.
SpinInput() [2/2]
SpinInput::SpinInput (wxWindow * parent, wxString text, wxString label = "", const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0, int min = 0, int max = 100, int initial = 0)
    : SpinInput()
{
    Create(parent, text, label, pos, size, style, min, max, initial);
}
References Create(), max, min, size, and style.
Member Function Documentation
Create()
void SpinInput::Create (wxWindow * parent, wxString text, wxString label = "", const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0, int min = 0, int max = 100, int initial = 0)
{
    StaticBox::Create(parent, wxID_ANY, pos, size);
    SetFont(Label::Body_12);
    wxWindow::SetLabel(label);
    state_handler.attach({&label_color, &text_color});
    state_handler.update_binds();
    text_ctrl = new TextCtrl(this, wxID_ANY, text, {20, 4}, wxDefaultSize, style | wxBORDER_NONE | wxTE_PROCESS_ENTER, wxTextValidator(wxFILTER_DIGITS));
    text_ctrl->SetFont(Label::Body_14);
    text_ctrl->SetBackgroundColour(background_color.colorForStates(state_handler.states()));
    text_ctrl->SetForegroundColour(text_color.colorForStates(state_handler.states()));
    text_ctrl->SetInitialSize(text_ctrl->GetBestSize());
    state_handler.attach_child(text_ctrl);
    text_ctrl->Bind(wxEVT_KILL_FOCUS, &SpinInput::onTextLostFocus, this);
    text_ctrl->Bind(wxEVT_TEXT_ENTER, &SpinInput::onTextEnter, this);
    text_ctrl->Bind(wxEVT_KEY_DOWN, &SpinInput::keyPressed, this);
    text_ctrl->Bind(wxEVT_RIGHT_DOWN, [this](auto &e) {}); // disable context menu
    button_inc = createButton(true);
    button_dec = createButton(false);
    delta      = 0;
    timer.Bind(wxEVT_TIMER, &SpinInput::onTimer, this);
    long initialFromText;
    if (text.ToLong(&initialFromText)) initial = initialFromText;
    SetRange(min, max);
    SetValue(initial);
    messureSize();
}
References Label::Body_12, Label::Body_14, button_dec, button_inc, StateColor::colorForStates(), StaticBox::Create(), createButton(), delta, keyPressed(), label_color, max, messureSize(), min, onTextEnter(), onTextLostFocus(), onTimer(), SetRange(), SetValue(), size, style, text_color, text_ctrl, and timer.
Referenced by SpinInput().
createButton()
Button * SpinInput::createButton (bool inc) private
{
    auto btn = new Button(this, "", inc ? "spin_inc" : "spin_dec", wxBORDER_NONE, 6);
    btn->SetCornerRadius(0);
    btn->DisableFocusFromKeyboard();
    btn->Bind(wxEVT_LEFT_DOWN, [=](auto &e) {
        delta = inc ? 1 : -1;
        SetValue(val + delta);
        text_ctrl->SetFocus();
        if (!btn->HasCapture())
            btn->CaptureMouse();
        delta *= 8;
        timer.Start(100);
        sendSpinEvent();
    });
    btn->Bind(wxEVT_LEFT_DCLICK, [=](auto &e) {
        delta = inc ? 1 : -1;
        if (!btn->HasCapture())
            btn->CaptureMouse();
        SetValue(val + delta);
        sendSpinEvent();
    });
    btn->Bind(wxEVT_LEFT_UP, [=](auto &e) {
        if (btn->HasCapture())
            btn->ReleaseMouse();
        timer.Stop();
        text_ctrl->SelectAll();
        delta = 0;
    });
    return btn;
}
References delta, sendSpinEvent(), StaticBox::SetCornerRadius(), SetValue(), text_ctrl, timer, and val.
Referenced by Create().
DoSetToolTipText()
void SpinInput::DoSetToolTipText (wxString const & tip) override protected
{
    wxWindow::DoSetToolTipText(tip);
    text_ctrl->SetToolTip(tip);
}
References text_ctrl.
Enable()
bool SpinInput::Enable (bool enable = true) virtual
{
    bool result = text_ctrl->Enable(enable) && wxWindow::Enable(enable);
    if (result) {
        wxCommandEvent e(EVT_ENABLE_CHANGED);
        e.SetEventObject(this);
        GetEventHandler()->ProcessEvent(e);
        text_ctrl->SetBackgroundColour(background_color.colorForStates(state_handler.states()));
        text_ctrl->SetForegroundColour(text_color.colorForStates(state_handler.states()));
        button_inc->Enable(enable);
        button_dec->Enable(enable);
    }
    return result;
}
References button_dec, button_inc, StateColor::colorForStates(), Button::Enable(), text_color, and text_ctrl.
GetTextCtrl()
wxTextCtrl * SpinInput::GetTextCtrl () inline
{ return text_ctrl; }
References text_ctrl.
Referenced by Slic3r::GUI::SpinCtrl::msw_rescale().
GetValue()
int SpinInput::GetValue () const
{
    return val;
}
References val.
keyPressed()
void SpinInput::keyPressed (wxKeyEvent & event) private
{
    switch (event.GetKeyCode()) {
    case WXK_UP:
    case WXK_DOWN:
        long value;
        if (!text_ctrl->GetValue().ToLong(&value)) { value = val; }
        if (event.GetKeyCode() == WXK_DOWN && value > min) {
            --value;
        } else if (event.GetKeyCode() == WXK_UP && value + 1 < max) {
            ++value;
        }
        if (value != val) {
            SetValue(value);
            sendSpinEvent();
        }
        break;
    default: event.Skip(); break;
    }
}
References max, min, sendSpinEvent(), SetValue(), text_ctrl, and val.
Referenced by Create().
messureSize()
void SpinInput::messureSize () private
{
    wxSize size = GetSize();
    wxSize textSize = text_ctrl->GetSize();
    int h = textSize.y + 8;
    if (size.y < h) {
        size.y = h;
    }
    wxSize minSize = size;
    minSize.x      = GetMinWidth();
    StaticBox::SetSize(size);
    SetMinSize(size);
    wxSize btnSize = {14, (size.y - 4) / 2};
    btnSize.x = btnSize.x * btnSize.y / 10;
    wxClientDC dc(this);
    labelSize  = dc.GetMultiLineTextExtent(GetLabel());
    textSize.x = size.x - labelSize.x - btnSize.x - 16;
    text_ctrl->SetSize(textSize);
    text_ctrl->SetPosition({6 + btnSize.x, (size.y - textSize.y) / 2});
    button_inc->SetSize(btnSize);
    button_dec->SetSize(btnSize);
    button_inc->SetPosition({3, size.y / 2 - btnSize.y - 1});
    button_dec->SetPosition({3, size.y / 2 + 1});
}
References button_dec, button_inc, labelSize, size, and text_ctrl.
Referenced by Create(), Rescale(), and SetLabel().
mouseWheelMoved()
void SpinInput::mouseWheelMoved (wxMouseEvent & event) private
{
    auto delta = event.GetWheelRotation() < 0 ? 1 : -1;
    SetValue(val + delta);
    sendSpinEvent();
    text_ctrl->SetFocus();
}
References delta, sendSpinEvent(), SetValue(), text_ctrl, and val.
onTextEnter()
void SpinInput::onTextEnter (wxCommandEvent & event) private
{
    long value;
    if (!text_ctrl->GetValue().ToLong(&value)) { value = val; }
    if (value != val) {
        SetValue(value);
        sendSpinEvent();
    }
    event.SetId(GetId());
    ProcessEventLocally(event);
}
References sendSpinEvent(), SetValue(), text_ctrl, and val.
Referenced by Create(), and onTextLostFocus().
onTextLostFocus()
void SpinInput::onTextLostFocus (wxEvent & event) private
{
    timer.Stop();
    for (auto * child : GetChildren())
        if (auto btn = dynamic_cast<Button*>(child))
            if (btn->HasCapture())
                btn->ReleaseMouse();
    wxCommandEvent e;
    onTextEnter(e);
    // pass to outer
    event.SetId(GetId());
    ProcessEventLocally(event);
    e.Skip();
}
References onTextEnter(), and timer.
Referenced by Create().
onTimer()
void SpinInput::onTimer (wxTimerEvent & evnet) private
{
    if (delta < -1 || delta > 1) {
        delta /= 2;
        return;
    }
    SetValue(val + delta);
    sendSpinEvent();
}
References delta, sendSpinEvent(), SetValue(), and val.
Referenced by Create().
paintEvent()
void SpinInput::paintEvent (wxPaintEvent & evt) private
{
    // depending on your system you may need to look at double-buffered dcs
    wxPaintDC dc(this);
    render(dc);
}
References render().
render()
void SpinInput::render (wxDC & dc) private
{
    StaticBox::render(dc);
    int    states = state_handler.states();
    wxSize size = GetSize();
    // draw seperator of buttons
    wxPoint pt = button_inc->GetPosition();
    pt.y = size.y / 2;
    dc.SetPen(wxPen(border_color.defaultColor()));
    dc.DrawLine(pt, pt + wxSize{button_inc->GetSize().x - 2, 0});
    // draw label
    auto label = GetLabel();
    if (!label.IsEmpty()) {
        pt.x = size.x - labelSize.x - 5;
        pt.y = (size.y - labelSize.y) / 2;
        dc.SetFont(GetFont());
        dc.SetTextForeground(label_color.colorForStates(states));
        dc.DrawText(label, pt);
    }
}
References button_inc, StateColor::colorForStates(), label_color, labelSize, StaticBox::render(), and size.
Referenced by paintEvent().
Rescale()
void SpinInput::Rescale ()
{
    button_inc->Rescale();
    button_dec->Rescale();
    messureSize();
}
References button_dec, button_inc, messureSize(), and Button::Rescale().
Referenced by Slic3r::GUI::SpinCtrl::msw_rescale(), and SetSize().
sendSpinEvent()
void SpinInput::sendSpinEvent () private
{
    wxCommandEvent event(wxEVT_SPINCTRL, GetId());
    event.SetEventObject(this);
    GetEventHandler()->ProcessEvent(event);
}
Referenced by createButton(), keyPressed(), mouseWheelMoved(), onTextEnter(), and onTimer().
SetCornerRadius()
void SpinInput::SetCornerRadius (double radius)
{
    this->radius = radius;
    Refresh();
}
SetLabel()
void SpinInput::SetLabel (const wxString & label)
{
    wxWindow::SetLabel(label);
    messureSize();
    Refresh();
}
References messureSize().
SetLabelColor()
void SpinInput::SetLabelColor (StateColor const & color)
{
    label_color = color;
    state_handler.update_binds();
}
References label_color.
SetRange()
void SpinInput::SetRange (int min, int max)
{
    this->min = min;
    this->max = max;
}
References max, and min.
Referenced by Create().
SetSize()
void SpinInput::SetSize (wxSize const & size)
{
    StaticBox::SetSize(size);
    Rescale();
}
References Rescale(), and size.
Referenced by Slic3r::GUI::SpinCtrl::msw_rescale().
SetTextColor()
void SpinInput::SetTextColor (StateColor const & color)
{
    text_color = color;
    state_handler.update_binds();
}
References text_color.
SetValue() [1/2]
void SpinInput::SetValue (const wxString & text)
{
    long value;
    if ( text.ToLong(&value) )
        SetValue(value);
}
References SetValue().
Referenced by Slic3r::GUI::SpinCtrl::BUILD(), Create(), createButton(), keyPressed(), mouseWheelMoved(), onTextEnter(), onTimer(), Slic3r::GUI::SpinCtrl::propagate_value(), Slic3r::GUI::SpinCtrl::set_value(), and SetValue().
SetValue() [2/2]
void SpinInput::SetValue (int value)
{
    if (value < min) value = min;
    else if (value > max) value = max;
    this->val = value;
    text_ctrl->SetValue(wxString::FromDouble(value));
}
References max, min, text_ctrl, and val.
Member Data Documentation
button_dec
Button* SpinInput::button_dec private
Referenced by Create(), Enable(), messureSize(), and Rescale().
button_inc
Button* SpinInput::button_inc private
Referenced by Create(), Enable(), messureSize(), render(), and Rescale().
delta
int SpinInput::delta private
Referenced by Create(), createButton(), mouseWheelMoved(), and onTimer().
label_color
StateColor SpinInput::label_color private
Referenced by Create(), render(), and SetLabelColor().
labelSize
wxSize SpinInput::labelSize private
Referenced by messureSize(), and render().
max
int SpinInput::max private
Referenced by SpinInput(), Create(), keyPressed(), SetRange(), and SetValue().
min
int SpinInput::min private
Referenced by SpinInput(), Create(), keyPressed(), SetRange(), and SetValue().
SpinInputHeight
const int SpinInput::SpinInputHeight = 50 static private
SpinInputWidth
const int SpinInput::SpinInputWidth = 200 static private
text_color
StateColor SpinInput::text_color private
Referenced by Create(), Enable(), and SetTextColor().
text_ctrl
wxTextCtrl* SpinInput::text_ctrl private
Referenced by Create(), createButton(), DoSetToolTipText(), Enable(), GetTextCtrl(), keyPressed(), messureSize(), mouseWheelMoved(), onTextEnter(), and SetValue().
timer
wxTimer SpinInput::timer private
Referenced by Create(), createButton(), and onTextLostFocus().
val
int SpinInput::val private
Referenced by createButton(), GetValue(), keyPressed(), mouseWheelMoved(), onTextEnter(), onTimer(), and SetValue().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/SpinInput.hpp
src/slic3r/GUI/Widgets/SpinInput.cpp