OrcaSlicer: src/qhull/src/libqhullcpp/QhullVertex.cpp File Reference
QhullVertex.cpp File Reference
#include "libqhullcpp/QhullVertex.h"
#include "libqhullcpp/Qhull.h"
#include "libqhullcpp/QhullPoint.h"
#include "libqhullcpp/QhullFacetSet.h"
#include "libqhullcpp/QhullFacet.h"
Namespaces
namespace orgQhull
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
Functions
Global functions
ostream & operator<< (ostream &os, const QhullVertex::PrintVertex &pr)
Duplicate of qh_printvertex [io_r.c].
Function Documentation
operator<<()
ostream & operator<< (ostream & os, const QhullVertex::PrintVertex & pr)
Duplicate of qh_printvertex [io_r.c].
{
    QhullVertex v= *pr.vertex;
    QhullPoint p= v.point();
    if(*pr.print_message){
        os << pr.print_message << " ";
    }else{
        os << "- ";
    }
    os << "p" << p.id() << " (v" << v.id() << "): ";
    const realT *c= p.coordinates();
    for(int k= p.dimension(); k--; ){
        os << " " << *c++; // FIXUP QH11010 %5.2g
    }
    if(v.getVertexT()->deleted){
        os << " deleted";
    }
    if(v.getVertexT()->delridge){
        os << " ridgedeleted";
    }
    os << endl;
    if(v.neighborFacetsDefined()){
        QhullFacetSetIterator i= v.neighborFacets();
        if(i.hasNext()){
            os << " neighborFacets:";
            countT count= 0;
            while(i.hasNext()){
                if(++count % 100 == 0){
                    os << endl << "     ";
                }
                QhullFacet f= i.next();
                os << " f" << f.id();
            }
            os << endl;
        }
    }
    return os;
}//<< PrintVertex
References orgQhull::QhullPoint::coordinates(), count, vertexT::deleted, vertexT::delridge, orgQhull::QhullPoint::dimension(), orgQhull::QhullVertex::getVertexT(), orgQhull::QhullFacet::id(), orgQhull::QhullPoint::id(), orgQhull::QhullVertex::id(), orgQhull::QhullVertex::neighborFacets(), orgQhull::QhullVertex::neighborFacetsDefined(), orgQhull::QhullFacet::next(), orgQhull::QhullVertex::point(), and realT.