OrcaSlicer: src/qhull/src/libqhull/poly.h File Reference
poly.h File Reference
#include "libqhull.h"
Macros
#define qh_ALGORITHMfault 0
#define qh_DATAfault 1
#define qh_DUPLICATEridge (facetT *)1L
#define qh_MERGEridge (facetT *)2L
#define FORALLfacet_(facetlist) if (facetlist) for (facet=(facetlist); facet && facet->next; facet= facet->next)
#define FORALLnew_facets for (newfacet=qh newfacet_list;newfacet && newfacet->next;newfacet=newfacet->next)
#define FORALLvertex_(vertexlist) for (vertex=(vertexlist);vertex && vertex->next;vertex= vertex->next)
#define FORALLvisible_facets for (visible=qh visible_list; visible && visible->visible; visible= visible->next)
#define FORALLsame_(newfacet) for (same= newfacet->f.samecycle; same != newfacet; same= same->f.samecycle)
#define FORALLsame_cycle_(newfacet)
#define FOREACHneighborA_(facet) FOREACHsetelement_(facetT, facet->neighbors, neighborA)
#define FOREACHvisible_(facets) FOREACHsetelement_(facetT, facets, visible)
#define FOREACHnewfacet_(facets) FOREACHsetelement_(facetT, facets, newfacet)
#define FOREACHvertexA_(vertices) FOREACHsetelement_(vertexT, vertices, vertexA)
#define FOREACHvertexreverse12_(vertices) FOREACHsetelementreverse12_(vertexT, vertices, vertex)
Functions
void qh_appendfacet (facetT *facet)
void qh_appendvertex (vertexT *vertex)
void qh_attachnewfacets (void)
boolT qh_checkflipped (facetT *facet, realT *dist, boolT allerror)
void qh_delfacet (facetT *facet)
void qh_deletevisible (void)
setT * qh_facetintersect (facetT *facetA, facetT *facetB, int *skipAp, int *skipBp, int extra)
int qh_gethash (int hashsize, setT *set, int size, int firstindex, void *skipelem)
facetT * qh_makenewfacet (setT *vertices, boolT toporient, facetT *facet)
void qh_makenewplanes (void)
facetT * qh_makenew_nonsimplicial (facetT *visible, vertexT *apex, int *numnew)
facetT * qh_makenew_simplicial (facetT *visible, vertexT *apex, int *numnew)
void qh_matchneighbor (facetT *newfacet, int newskip, int hashsize, int *hashcount)
void qh_matchnewfacets (void)
boolT qh_matchvertices (int firstindex, setT *verticesA, int skipA, setT *verticesB, int *skipB, boolT *same)
facetT * qh_newfacet (void)
ridgeT * qh_newridge (void)
int qh_pointid (pointT *point)
void qh_removefacet (facetT *facet)
void qh_removevertex (vertexT *vertex)
void qh_updatevertices (void)
void qh_addhash (void *newelem, setT *hashtable, int hashsize, int hash)
void qh_check_bestdist (void)
void qh_check_dupridge (facetT *facet1, realT dist1, facetT *facet2, realT dist2)
void qh_check_maxout (void)
void qh_check_output (void)
void qh_check_point (pointT *point, facetT *facet, realT *maxoutside, realT *maxdist, facetT **errfacet1, facetT **errfacet2)
void qh_check_points (void)
void qh_checkconvex (facetT *facetlist, int fault)
void qh_checkfacet (facetT *facet, boolT newmerge, boolT *waserrorp)
void qh_checkflipped_all (facetT *facetlist)
void qh_checkpolygon (facetT *facetlist)
void qh_checkvertex (vertexT *vertex)
void qh_clearcenters (qh_CENTER type)
void qh_createsimplex (setT *vertices)
void qh_delridge (ridgeT *ridge)
void qh_delvertex (vertexT *vertex)
setT * qh_facet3vertex (facetT *facet)
facetT * qh_findbestfacet (pointT *point, boolT bestoutside, realT *bestdist, boolT *isoutside)
facetT * qh_findbestlower (facetT *upperfacet, pointT *point, realT *bestdistp, int *numpart)
facetT * qh_findfacet_all (pointT *point, realT *bestdist, boolT *isoutside, int *numpart)
int qh_findgood (facetT *facetlist, int goodhorizon)
void qh_findgood_all (facetT *facetlist)
void qh_furthestnext (void)
void qh_furthestout (facetT *facet)
void qh_infiniteloop (facetT *facet)
void qh_initbuild (void)
void qh_initialhull (setT *vertices)
setT * qh_initialvertices (int dim, setT *maxpoints, pointT *points, int numpoints)
vertexT * qh_isvertex (pointT *point, setT *vertices)
vertexT * qh_makenewfacets (pointT *point)
void qh_matchduplicates (facetT *atfacet, int atskip, int hashsize, int *hashcount)
void qh_nearcoplanar (void)
vertexT * qh_nearvertex (facetT *facet, pointT *point, realT *bestdistp)
int qh_newhashtable (int newsize)
vertexT * qh_newvertex (pointT *point)
ridgeT * qh_nextridge3d (ridgeT *atridge, facetT *facet, vertexT **vertexp)
void qh_outcoplanar (void)
pointT * qh_point (int id)
void qh_point_add (setT *set, pointT *point, void *elem)
setT * qh_pointfacet (void)
setT * qh_pointvertex (void)
void qh_prependfacet (facetT *facet, facetT **facetlist)
void qh_printhashtable (FILE *fp)
void qh_printlists (void)
void qh_resetlists (boolT stats, boolT resetVisible)
void qh_setvoronoi_all (void)
void qh_triangulate (void)
void qh_triangulate_facet (facetT *facetA, vertexT **first_vertex)
void qh_triangulate_link (facetT *oldfacetA, facetT *facetA, facetT *oldfacetB, facetT *facetB)
void qh_triangulate_mirror (facetT *facetA, facetT *facetB)
void qh_triangulate_null (facetT *facetA)
void qh_vertexintersect (setT **vertexsetA, setT *vertexsetB)
setT * qh_vertexintersect_new (setT *vertexsetA, setT *vertexsetB)
void qh_vertexneighbors (void)
boolT qh_vertexsubset (setT *vertexsetA, setT *vertexsetB)
Macro Definition Documentation
FORALLfacet_
#define FORALLfacet_ (facetlist) if (facetlist) for (facet=(facetlist); facet && facet->next; facet= facet->next)
FORALLnew_facets
#define FORALLnew_facets for (newfacet=qh newfacet_list;newfacet && newfacet->next;newfacet=newfacet->next)
FORALLsame_
#define FORALLsame_ (newfacet) for (same= newfacet->f.samecycle; same != newfacet; same= same->f.samecycle)
FORALLsame_cycle_
#define FORALLsame_cycle_ (newfacet)
Value:
     for (same= newfacet->f.samecycle; \
         same; same= (same == newfacet ?  NULL : same->f.samecycle))
FORALLvertex_
#define FORALLvertex_ (vertexlist) for (vertex=(vertexlist);vertex && vertex->next;vertex= vertex->next)
FORALLvisible_facets
#define FORALLvisible_facets for (visible=qh visible_list; visible && visible->visible; visible= visible->next)
FOREACHneighborA_
#define FOREACHneighborA_ (facet) FOREACHsetelement_(facetT, facet->neighbors, neighborA)
FOREACHnewfacet_
#define FOREACHnewfacet_ (facets) FOREACHsetelement_(facetT, facets, newfacet)
FOREACHvertexA_
#define FOREACHvertexA_ (vertices) FOREACHsetelement_(vertexT, vertices, vertexA)
FOREACHvertexreverse12_
#define FOREACHvertexreverse12_ (vertices) FOREACHsetelementreverse12_(vertexT, vertices, vertex)
FOREACHvisible_
#define FOREACHvisible_ (facets) FOREACHsetelement_(facetT, facets, visible)
qh_ALGORITHMfault
#define qh_ALGORITHMfault 0
qh_DATAfault
#define qh_DATAfault 1
qh_DUPLICATEridge
#define qh_DUPLICATEridge (facetT *)1L
qh_MERGEridge
#define qh_MERGEridge (facetT *)2L
Function Documentation
qh_addhash()
void qh_addhash (void * newelem, setT * hashtable, int hashsize, int hash)
{
  int scan;
  void *elem;
  for (scan= (int)hash; (elem= SETelem_(hashtable, scan));
       scan= (++scan >= hashsize ? 0 : scan)) {
    if (elem == newelem)
      break;
  }
  /* loop terminates because qh_HASHfactor >= 1.1 by qh_initbuffers */
  if (!elem)
    SETelem_(hashtable, scan)= newelem;
} /* addhash */
References hash(), and SETelem_.
Referenced by qh_matchneighbor(), and qh_matchneighbor().
qh_appendfacet()
void qh_appendfacet (facetT * facet)
{
  facetT *tail= qh facet_tail;
  if (tail == qh newfacet_list)
    qh newfacet_list= facet;
  if (tail == qh facet_next)
    qh facet_next= facet;
  facet->previous= tail->previous;
  facet->next= tail;
  if (tail->previous)
    tail->previous->next= facet;
  else
    qh facet_list= facet;
  tail->previous= facet;
  qh num_facets++;
  trace4((qh ferr, 4044, "qh_appendfacet: append f%d to facet_list\n", facet->id));
} /* appendfacet */
References facetT::id, facetT::next, facetT::previous, qh, tail(), and trace4.
Referenced by qh_checkconnect(), qh_checkconnect(), qh_createsimplex(), qh_createsimplex(), qh_findgooddist(), qh_findgooddist(), qh_findhorizon(), qh_findhorizon(), qh_makenewfacet(), qh_mergecycle_facets(), qh_mergecycle_facets(), qh_mergefacet(), qh_mergefacet(), qh_partitionpoint(), and qh_partitionpoint().
qh_appendvertex()
void qh_appendvertex (vertexT * vertex)
{
  vertexT *tail= qh vertex_tail;
  if (tail == qh newvertex_list)
    qh newvertex_list= vertex;
  vertex->newlist= True;
  vertex->previous= tail->previous;
  vertex->next= tail;
  if (tail->previous)
    tail->previous->next= vertex;
  else
    qh vertex_list= vertex;
  tail->previous= vertex;
  qh num_vertices++;
  trace4((qh ferr, 4045, "qh_appendvertex: append v%d to vertex_list\n", vertex->id));
} /* appendvertex */
References qh, tail(), trace4, and True.
Referenced by qh_createsimplex(), qh_createsimplex(), qh_makenewfacet(), qh_makenewfacets(), qh_makenewfacets(), qh_mergesimplex(), qh_mergesimplex(), qh_newvertices(), and qh_newvertices().
qh_attachnewfacets()
void qh_attachnewfacets (void)
{
  facetT *newfacet= NULL, *neighbor, **neighborp, *horizon, *visible;
  ridgeT *ridge, **ridgep;
  qh NEWfacets= True;
  trace3((qh ferr, 3012, "qh_attachnewfacets: delete interior ridges\n"));
  qh visit_id++;
  FORALLvisible_facets {
    visible->visitid= qh visit_id;
    if (visible->ridges) {
      FOREACHridge_(visible->ridges) {
        neighbor= otherfacet_(ridge, visible);
        if (neighbor->visitid == qh visit_id
            || (!neighbor->visible && neighbor->simplicial)) {
          if (!neighbor->visible)  /* delete ridge for simplicial horizon */
            qh_setdel(neighbor->ridges, ridge);
          qh_setfree(&(ridge->vertices)); /* delete on 2nd visit */
          qh_memfree(ridge, (int)sizeof(ridgeT));
        }
      }
      SETfirst_(visible->ridges)= NULL;
    }
    SETfirst_(visible->neighbors)= NULL;
  }
  trace1((qh ferr, 1017, "qh_attachnewfacets: attach horizon facets to new facets\n"));
  FORALLnew_facets {
    horizon= SETfirstt_(newfacet->neighbors, facetT);
    if (horizon->simplicial) {
      visible= NULL;
      FOREACHneighbor_(horizon) {   /* may have more than one horizon ridge */
        if (neighbor->visible) {
          if (visible) {
            if (qh_setequal_skip(newfacet->vertices, 0, horizon->vertices,
                                  SETindex_(horizon->neighbors, neighbor))) {
              visible= neighbor;
              break;
            }
          }else
            visible= neighbor;
        }
      }
      if (visible) {
        visible->f.replace= newfacet;
        qh_setreplace(horizon->neighbors, visible, newfacet);
      }else {
        qh_fprintf(qh ferr, 6102, "qhull internal error (qh_attachnewfacets): couldn't find visible facet for horizon f%d of newfacet f%d\n",
                 horizon->id, newfacet->id);
        qh_errexit2(qh_ERRqhull, horizon, newfacet);
      }
    }else { /* non-simplicial, with a ridge for newfacet */
      FOREACHneighbor_(horizon) {    /* may hold for many new facets */
        if (neighbor->visible) {
          neighbor->f.replace= newfacet;
          qh_setdelnth(horizon->neighbors,
                        SETindex_(horizon->neighbors, neighbor));
          neighborp--; /* repeat */
        }
      }
      qh_setappend(&horizon->neighbors, newfacet);
      ridge= SETfirstt_(newfacet->ridges, ridgeT);
      if (ridge->top == horizon)
        ridge->bottom= newfacet;
      else
        ridge->top= newfacet;
      }
  } /* newfacets */
  if (qh PRINTstatistics) {
    FORALLvisible_facets {
      if (!visible->f.replace)
        zinc_(Zinsidevisible);
    }
  }
} /* attachnewfacets */
References ridgeT::bottom, FORALLnew_facets, FORALLvisible_facets, FOREACHneighbor_, FOREACHridge_, facetT::id, facetT::neighbors, NULL, otherfacet_, qh, qh_errexit2(), qh_ERRqhull, qh_fprintf(), qh_memfree(), qh_setappend(), qh_setdel(), qh_setdelnth(), qh_setequal_skip(), qh_setfree(), qh_setreplace(), facetT::ridges, SETfirst_, SETfirstt_, SETindex_, ridgeT::top, trace1, trace3, True, facetT::vertices, ridgeT::vertices, and zinc_.
Referenced by qh_addpoint(), and qh_addpoint().
qh_check_bestdist()
void qh_check_bestdist (void)
{
  boolT waserror= False, unassigned;
  facetT *facet, *bestfacet, *errfacet1= NULL, *errfacet2= NULL;
  facetT *facetlist;
  realT dist, maxoutside, maxdist= -REALmax;
  pointT *point;
  int numpart= 0, facet_i, facet_n, notgood= 0, notverified= 0;
  setT *facets;
  trace1((qh ferr, 1020, "qh_check_bestdist: check points below nearest facet.  Facet_list f%d\n",
      qh facet_list->id));
  maxoutside= qh_maxouter();
  maxoutside += qh DISTround;
  /* one more qh.DISTround for check computation */
  trace1((qh ferr, 1021, "qh_check_bestdist: check that all points are within %2.2g of best facet\n", maxoutside));
  facets= qh_pointfacet(/*qh.facet_list*/);
  if (!qh_QUICKhelp && qh PRINTprecision)
    qh_fprintf(qh ferr, 8091, "\n\
qhull output completed.  Verifying that %d points are\n\
below %2.2g of the nearest %sfacet.\n",
             qh_setsize(facets), maxoutside, (qh ONLYgood ?  "good " : ""));
  FOREACHfacet_i_(facets) {  /* for each point with facet assignment */
    if (facet)
      unassigned= False;
    else {
      unassigned= True;
      facet= qh facet_list;
    }
    point= qh_point(facet_i);
    if (point == qh GOODpointp)
      continue;
    qh_distplane(point, facet, &dist);
    numpart++;
    bestfacet= qh_findbesthorizon(!qh_IScheckmax, point, facet, qh_NOupper, &dist, &numpart);
    /* occurs after statistics reported */
    maximize_(maxdist, dist);
    if (dist > maxoutside) {
      if (qh ONLYgood && !bestfacet->good
          && !((bestfacet= qh_findgooddist(point, bestfacet, &dist, &facetlist))
               && dist > maxoutside))
        notgood++;
      else {
        waserror= True;
        qh_fprintf(qh ferr, 6109, "qhull precision error: point p%d is outside facet f%d, distance= %6.8g maxoutside= %6.8g\n",
                facet_i, bestfacet->id, dist, maxoutside);
        if (errfacet1 != bestfacet) {
          errfacet2= errfacet1;
          errfacet1= bestfacet;
        }
      }
    }else if (unassigned && dist < -qh MAXcoplanar)
      notverified++;
  }
  qh_settempfree(&facets);
  if (notverified && !qh DELAUNAY && !qh_QUICKhelp && qh PRINTprecision)
    qh_fprintf(qh ferr, 8092, "\n%d points were well inside the hull.  If the hull contains\n\
a lens-shaped component, these points were not verified.  Use\n\
options 'Qci Tv' to verify all points.\n", notverified);
  if (maxdist > qh outside_err) {
    qh_fprintf(qh ferr, 6110, "qhull precision error (qh_check_bestdist): a coplanar point is %6.2g from convex hull.  The maximum value(qh.outside_err) is %6.2g\n",
              maxdist, qh outside_err);
    qh_errexit2(qh_ERRprec, errfacet1, errfacet2);
  }else if (waserror && qh outside_err > REALmax/2)
    qh_errexit2(qh_ERRprec, errfacet1, errfacet2);
  /* else if waserror, the error was logged to qh.ferr but does not effect the output */
  trace0((qh ferr, 20, "qh_check_bestdist: max distance outside %2.2g\n", maxdist));
} /* check_bestdist */
References boolT, False, FOREACHfacet_i_, facetT::good, facetT::id, maximize_, NULL, pointT, qh, qh_distplane(), qh_errexit2(), qh_ERRprec, qh_findbesthorizon(), qh_findgooddist(), qh_fprintf(), qh_IScheckmax, qh_maxouter(), qh_NOupper, qh_point(), qh_pointfacet(), qh_QUICKhelp, qh_setsize(), qh_settempfree(), REALmax, realT, trace0, trace1, and True.
Referenced by qh_check_points(), and qh_check_points().
qh_check_dupridge()
void qh_check_dupridge (facetT * facet1, realT dist1, facetT * facet2, realT dist2)
{
  vertexT *vertex, **vertexp, *vertexA, **vertexAp;
  realT dist, innerplane, mergedist, outerplane, prevdist, ratio;
  realT minvertex= REALmax;
  mergedist= fmin_(dist1, dist2);
  qh_outerinner(NULL, &outerplane, &innerplane);  /* ratio from qh_printsummary */
  prevdist= fmax_(outerplane, innerplane);
  maximize_(prevdist, qh ONEmerge + qh DISTround);
  maximize_(prevdist, qh MINoutside + qh DISTround);
  ratio= mergedist/prevdist;
  FOREACHvertex_(facet1->vertices) {     /* The duplicate ridge is between facet1 and facet2, so either facet can be tested */
    FOREACHvertexA_(facet1->vertices) {
      if (vertex > vertexA){   /* Test each pair once */
        dist= qh_pointdist(vertex->point, vertexA->point, qh hull_dim);
        minimize_(minvertex, dist);
      }
    }
  }
  trace0((qh ferr, 16, "qh_check_dupridge: duplicate ridge between f%d and f%d due to nearly-coincident vertices (%2.2g), dist %2.2g, reverse dist %2.2g, ratio %2.2g while processing p%d\n",
        facet1->id, facet2->id, minvertex, dist1, dist2, ratio, qh furthest_id));
  if (ratio > qh_WIDEduplicate) {
    qh_fprintf(qh ferr, 6271, "qhull precision error (qh_check_dupridge): wide merge (%.0f times wider) due to duplicate ridge with nearly coincident points (%2.2g) between f%d and f%d, merge dist %2.2g, while processing p%d\n- Ignore error with option 'Q12'\n- To be fixed in a later version of Qhull\n",
          ratio, minvertex, facet1->id, facet2->id, mergedist, qh furthest_id);
    if (qh DELAUNAY)
      qh_fprintf(qh ferr, 8145, "- A bounding box for the input sites may alleviate this error.\n");
    if(minvertex > qh_WIDEduplicate*prevdist)
      qh_fprintf(qh ferr, 8146, "- Vertex distance %2.2g is greater than %d times maximum distance %2.2g\n  Please report to bradb@shore.net with steps to reproduce and all output\n",
          minvertex, qh_WIDEduplicate, prevdist);
    if (!qh NOwide)
      qh_errexit2(qh_ERRqhull, facet1, facet2);
  }
} /* check_dupridge */
References fmax_, fmin_, FOREACHvertex_, FOREACHvertexA_, facetT::id, maximize_, minimize_, NULL, vertexT::point, qh, qh_errexit2(), qh_ERRqhull, qh_fprintf(), qh_outerinner(), qh_pointdist(), qh_WIDEduplicate, REALmax, realT, trace0, and facetT::vertices.
Referenced by qh_forcedmerges(), and qh_forcedmerges().
qh_check_maxout()
void qh_check_maxout (void)
{
  facetT *facet, *bestfacet, *neighbor, **neighborp, *facetlist;
  realT dist, maxoutside, minvertex, old_maxoutside;
  pointT *point;
  int numpart= 0, facet_i, facet_n, notgood= 0;
  setT *facets, *vertices;
  vertexT *vertex;
  trace1((qh ferr, 1022, "qh_check_maxout: check and update maxoutside for each facet.\n"));
  maxoutside= minvertex= 0;
  if (qh VERTEXneighbors
  && (qh PRINTsummary || qh KEEPinside || qh KEEPcoplanar
        || qh TRACElevel || qh PRINTstatistics
        || qh PRINTout[0] == qh_PRINTsummary || qh PRINTout[0] == qh_PRINTnone)) {
    trace1((qh ferr, 1023, "qh_check_maxout: determine actual maxoutside and minvertex\n"));
    vertices= qh_pointvertex(/*qh.facet_list*/);
    FORALLvertices {
      FOREACHneighbor_(vertex) {
        zinc_(Zdistvertex);  /* distance also computed by main loop below */
        qh_distplane(vertex->point, neighbor, &dist);
        minimize_(minvertex, dist);
        if (-dist > qh TRACEdist || dist > qh TRACEdist
        || neighbor == qh tracefacet || vertex == qh tracevertex)
          qh_fprintf(qh ferr, 8093, "qh_check_maxout: p%d(v%d) is %.2g from f%d\n",
                    qh_pointid(vertex->point), vertex->id, dist, neighbor->id);
      }
    }
    if (qh MERGING) {
      wmin_(Wminvertex, qh min_vertex);
    }
    qh min_vertex= minvertex;
    qh_settempfree(&vertices);
  }
  facets= qh_pointfacet(/*qh.facet_list*/);
  do {
    old_maxoutside= fmax_(qh max_outside, maxoutside);
    FOREACHfacet_i_(facets) {     /* for each point with facet assignment */
      if (facet) {
        point= qh_point(facet_i);
        if (point == qh GOODpointp)
          continue;
        zzinc_(Ztotcheck);
        qh_distplane(point, facet, &dist);
        numpart++;
        bestfacet= qh_findbesthorizon(qh_IScheckmax, point, facet, !qh_NOupper, &dist, &numpart);
        if (bestfacet && dist > maxoutside) {
          if (qh ONLYgood && !bestfacet->good
          && !((bestfacet= qh_findgooddist(point, bestfacet, &dist, &facetlist))
               && dist > maxoutside))
            notgood++;
          else
            maxoutside= dist;
        }
        if (dist > qh TRACEdist || (bestfacet && bestfacet == qh tracefacet))
          qh_fprintf(qh ferr, 8094, "qh_check_maxout: p%d is %.2g above f%d\n",
                     qh_pointid(point), dist, (bestfacet ? bestfacet->id : UINT_MAX));
      }
    }
  }while
    (maxoutside > 2*old_maxoutside);
    /* if qh.maxoutside increases substantially, qh_SEARCHdist is not valid
          e.g., RBOX 5000 s Z1 G1e-13 t1001200614 | qhull */
  zzadd_(Zcheckpart, numpart);
  qh_settempfree(&facets);
  wval_(Wmaxout)= maxoutside - qh max_outside;
  wmax_(Wmaxoutside, qh max_outside);
  qh max_outside= maxoutside;
  qh_nearcoplanar(/*qh.facet_list*/);
  qh maxoutdone= True;
  trace1((qh ferr, 1024, "qh_check_maxout: maxoutside %2.2g, min_vertex %2.2g, outside of not good %d\n",
       maxoutside, qh min_vertex, notgood));
} /* check_maxout */
References fmax_, FORALLvertices, FOREACHfacet_i_, FOREACHneighbor_, facetT::good, facetT::id, minimize_, pointT, qh, qh_distplane(), qh_findbesthorizon(), qh_findgooddist(), qh_fprintf(), qh_IScheckmax, qh_nearcoplanar(), qh_NOupper, qh_point(), qh_pointfacet(), qh_pointid(), qh_pointvertex(), qh_PRINTnone, qh_PRINTsummary, qh_settempfree(), realT, trace1, True, wmax_, wmin_, wval_, Zcheckpart, zinc_, Ztotcheck, zzadd_, and zzinc_.
Referenced by addDelaunay(), addDelaunay(), adddiamond(), adddiamond(), addhalf(), addhalf(), qh_qhull(), and qh_qhull().
qh_check_output()
void qh_check_output (void)
{
  int i;
  if (qh STOPcone)
    return;
  if (qh VERIFYoutput | qh IStracing | qh CHECKfrequently) {
    qh_checkpolygon(qh facet_list);
    qh_checkflipped_all(qh facet_list);
    qh_checkconvex(qh facet_list, qh_ALGORITHMfault);
  }else if (!qh MERGING && qh_newstats(qhstat precision, &i)) {
    qh_checkflipped_all(qh facet_list);
    qh_checkconvex(qh facet_list, qh_ALGORITHMfault);
  }
} /* check_output */
qh_check_point()
void qh_check_point (pointT * point, facetT * facet, realT * maxoutside, realT * maxdist, facetT ** errfacet1, facetT ** errfacet2)
{
  realT dist;
  /* occurs after statistics reported */
  qh_distplane(point, facet, &dist);
  if (dist > *maxoutside) {
    if (*errfacet1 != facet) {
      *errfacet2= *errfacet1;
      *errfacet1= facet;
    }
    qh_fprintf(qh ferr, 6111, "qhull precision error: point p%d is outside facet f%d, distance= %6.8g maxoutside= %6.8g\n",
              qh_pointid(point), facet->id, dist, *maxoutside);
  }
  maximize_(*maxdist, dist);
} /* qh_check_point */
References facetT::id, maximize_, qh, qh_distplane(), qh_fprintf(), qh_pointid(), and realT.
Referenced by qh_check_points().
qh_check_points()
void qh_check_points (void)
{
  facetT *facet, *errfacet1= NULL, *errfacet2= NULL;
  realT total, maxoutside, maxdist= -REALmax;
  pointT *point, **pointp, *pointtemp;
  boolT testouter;
  maxoutside= qh_maxouter();
  maxoutside += qh DISTround;
  /* one more qh.DISTround for check computation */
  trace1((qh ferr, 1025, "qh_check_points: check all points below %2.2g of all facet planes\n",
          maxoutside));
  if (qh num_good)   /* miss counts other_points and !good facets */
     total= (float)qh num_good * (float)qh num_points;
  else
     total= (float)qh num_facets * (float)qh num_points;
  if (total >= qh_VERIFYdirect && !qh maxoutdone) {
    if (!qh_QUICKhelp && qh SKIPcheckmax && qh MERGING)
      qh_fprintf(qh ferr, 7075, "qhull input warning: merging without checking outer planes('Q5' or 'Po').\n\
Verify may report that a point is outside of a facet.\n");
    qh_check_bestdist();
  }else {
    if (qh_MAXoutside && qh maxoutdone)
      testouter= True;
    else
      testouter= False;
    if (!qh_QUICKhelp) {
      if (qh MERGEexact)
        qh_fprintf(qh ferr, 7076, "qhull input warning: exact merge ('Qx').  Verify may report that a point\n\
is outside of a facet.  See qh-optq.htm#Qx\n");
      else if (qh SKIPcheckmax || qh NOnearinside)
        qh_fprintf(qh ferr, 7077, "qhull input warning: no outer plane check ('Q5') or no processing of\n\
near-inside points ('Q8').  Verify may report that a point is outside\n\
of a facet.\n");
    }
    if (qh PRINTprecision) {
      if (testouter)
        qh_fprintf(qh ferr, 8098, "\n\
Output completed.  Verifying that all points are below outer planes of\n\
all %sfacets.  Will make %2.0f distance computations.\n",
              (qh ONLYgood ?  "good " : ""), total);
      else
        qh_fprintf(qh ferr, 8099, "\n\
Output completed.  Verifying that all points are below %2.2g of\n\
all %sfacets.  Will make %2.0f distance computations.\n",
              maxoutside, (qh ONLYgood ?  "good " : ""), total);
    }
    FORALLfacets {
      if (!facet->good && qh ONLYgood)
        continue;
      if (facet->flipped)
        continue;
      if (!facet->normal) {
        qh_fprintf(qh ferr, 7061, "qhull warning (qh_check_points): missing normal for facet f%d\n", facet->id);
        continue;
      }
      if (testouter) {
#if qh_MAXoutside
        maxoutside= facet->maxoutside + 2* qh DISTround;
        /* one DISTround to actual point and another to computed point */
#endif
      }
      FORALLpoints {
        if (point != qh GOODpointp)
          qh_check_point(point, facet, &maxoutside, &maxdist, &errfacet1, &errfacet2);
      }
      FOREACHpoint_(qh other_points) {
        if (point != qh GOODpointp)
          qh_check_point(point, facet, &maxoutside, &maxdist, &errfacet1, &errfacet2);
      }
    }
    if (maxdist > qh outside_err) {
      qh_fprintf(qh ferr, 6112, "qhull precision error (qh_check_points): a coplanar point is %6.2g from convex hull.  The maximum value(qh.outside_err) is %6.2g\n",
                maxdist, qh outside_err );
      qh_errexit2( qh_ERRprec, errfacet1, errfacet2 );
    }else if (errfacet1 && qh outside_err > REALmax/2)
        qh_errexit2( qh_ERRprec, errfacet1, errfacet2 );
    /* else if errfacet1, the error was logged to qh.ferr but does not effect the output */
    trace0((qh ferr, 21, "qh_check_points: max distance outside %2.2g\n", maxdist));
  }
} /* check_points */
qh_checkconvex()
void qh_checkconvex (facetT * facetlist, int fault)
{
  facetT *facet, *neighbor, **neighborp, *errfacet1=NULL, *errfacet2=NULL;
  vertexT *vertex;
  realT dist;
  pointT *centrum;
  boolT waserror= False, centrum_warning= False, tempcentrum= False, allsimplicial;
  int neighbor_i;
  trace1((qh ferr, 1026, "qh_checkconvex: check all ridges are convex\n"));
  if (!qh RERUN) {
    zzval_(Zconcaveridges)= 0;
    zzval_(Zcoplanarridges)= 0;
  }
  FORALLfacet_(facetlist) {
    if (facet->flipped) {
      qh_precision("flipped facet");
      qh_fprintf(qh ferr, 6113, "qhull precision error: f%d is flipped(interior point is outside)\n",
               facet->id);
      errfacet1= facet;
      waserror= True;
      continue;
    }
    if (qh MERGING && (!qh ZEROcentrum || !facet->simplicial || facet->tricoplanar))
      allsimplicial= False;
    else {
      allsimplicial= True;
      neighbor_i= 0;
      FOREACHneighbor_(facet) {
        vertex= SETelemt_(facet->vertices, neighbor_i++, vertexT);
        if (!neighbor->simplicial || neighbor->tricoplanar) {
          allsimplicial= False;
          continue;
        }
        qh_distplane(vertex->point, neighbor, &dist);
        if (dist > -qh DISTround) {
          if (fault == qh_DATAfault) {
            qh_precision("coplanar or concave ridge");
            qh_fprintf(qh ferr, 6114, "qhull precision error: initial simplex is not convex. Distance=%.2g\n", dist);
            qh_errexit(qh_ERRsingular, NULL, NULL);
          }
          if (dist > qh DISTround) {
            zzinc_(Zconcaveridges);
            qh_precision("concave ridge");
            qh_fprintf(qh ferr, 6115, "qhull precision error: f%d is concave to f%d, since p%d(v%d) is %6.4g above\n",
              facet->id, neighbor->id, qh_pointid(vertex->point), vertex->id, dist);
            errfacet1= facet;
            errfacet2= neighbor;
            waserror= True;
          }else if (qh ZEROcentrum) {
            if (dist > 0) {     /* qh_checkzero checks that dist < - qh DISTround */
              zzinc_(Zcoplanarridges);
              qh_precision("coplanar ridge");
              qh_fprintf(qh ferr, 6116, "qhull precision error: f%d is clearly not convex to f%d, since p%d(v%d) is %6.4g above\n",
                facet->id, neighbor->id, qh_pointid(vertex->point), vertex->id, dist);
              errfacet1= facet;
              errfacet2= neighbor;
              waserror= True;
            }
          }else {
            zzinc_(Zcoplanarridges);
            qh_precision("coplanar ridge");
            trace0((qh ferr, 22, "qhull precision error: f%d may be coplanar to f%d, since p%d(v%d) is within %6.4g during p%d\n",
              facet->id, neighbor->id, qh_pointid(vertex->point), vertex->id, dist, qh furthest_id));
          }
        }
      }
    }
    if (!allsimplicial) {
      if (qh CENTERtype == qh_AScentrum) {
        if (!facet->center)
          facet->center= qh_getcentrum(facet);
        centrum= facet->center;
      }else {
        if (!centrum_warning && (!facet->simplicial || facet->tricoplanar)) {
           centrum_warning= True;
           qh_fprintf(qh ferr, 7062, "qhull warning: recomputing centrums for convexity test.  This may lead to false, precision errors.\n");
        }
        centrum= qh_getcentrum(facet);
        tempcentrum= True;
      }
      FOREACHneighbor_(facet) {
        if (qh ZEROcentrum && facet->simplicial && neighbor->simplicial)
          continue;
        if (facet->tricoplanar || neighbor->tricoplanar)
          continue;
        zzinc_(Zdistconvex);
        qh_distplane(centrum, neighbor, &dist);
        if (dist > qh DISTround) {
          zzinc_(Zconcaveridges);
          qh_precision("concave ridge");
          qh_fprintf(qh ferr, 6117, "qhull precision error: f%d is concave to f%d.  Centrum of f%d is %6.4g above f%d\n",
            facet->id, neighbor->id, facet->id, dist, neighbor->id);
          errfacet1= facet;
          errfacet2= neighbor;
          waserror= True;
        }else if (dist >= 0.0) {   /* if arithmetic always rounds the same,
                                     can test against centrum radius instead */
          zzinc_(Zcoplanarridges);
          qh_precision("coplanar ridge");
          qh_fprintf(qh ferr, 6118, "qhull precision error: f%d is coplanar or concave to f%d.  Centrum of f%d is %6.4g above f%d\n",
            facet->id, neighbor->id, facet->id, dist, neighbor->id);
          errfacet1= facet;
          errfacet2= neighbor;
          waserror= True;
        }
      }
      if (tempcentrum)
        qh_memfree(centrum, qh normal_size);
    }
  }
  if (waserror && !qh FORCEoutput)
    qh_errexit2(qh_ERRprec, errfacet1, errfacet2);
} /* checkconvex */
References boolT, facetT::center, False, facetT::flipped, FORALLfacet_, FOREACHneighbor_, facetT::id, NULL, pointT, qh, qh_AScentrum, qh_DATAfault, qh_distplane(), qh_errexit(), qh_errexit2(), qh_ERRprec, qh_ERRsingular, qh_fprintf(), qh_getcentrum(), qh_memfree(), qh_pointid(), qh_precision(), realT, SETelemt_, facetT::simplicial, trace0, trace1, facetT::tricoplanar, True, facetT::vertices, Zconcaveridges, Zcoplanarridges, Zdistconvex, zzinc_, and zzval_.
Referenced by qh_all_merges(), qh_all_merges(), qh_build_withrestart(), qh_build_withrestart(), qh_check_output(), and qh_initialhull().
qh_checkfacet()
void qh_checkfacet (facetT * facet, boolT newmerge, boolT * waserrorp)
{
  facetT *neighbor, **neighborp, *errother=NULL;
  ridgeT *ridge, **ridgep, *errridge= NULL, *ridge2;
  vertexT *vertex, **vertexp;
  unsigned previousid= INT_MAX;
  int numneighbors, numvertices, numridges=0, numRvertices=0;
  boolT waserror= False;
  int skipA, skipB, ridge_i, ridge_n, i;
  setT *intersection;
  if (facet->visible) {
    qh_fprintf(qh ferr, 6119, "qhull internal error (qh_checkfacet): facet f%d is on the visible_list\n",
      facet->id);
    qh_errexit(qh_ERRqhull, facet, NULL);
  }
  if (!facet->normal) {
    qh_fprintf(qh ferr, 6120, "qhull internal error (qh_checkfacet): facet f%d does not have  a normal\n",
      facet->id);
    waserror= True;
  }
  qh_setcheck(facet->vertices, "vertices for f", facet->id);
  qh_setcheck(facet->ridges, "ridges for f", facet->id);
  qh_setcheck(facet->outsideset, "outsideset for f", facet->id);
  qh_setcheck(facet->coplanarset, "coplanarset for f", facet->id);
  qh_setcheck(facet->neighbors, "neighbors for f", facet->id);
  FOREACHvertex_(facet->vertices) {
    if (vertex->deleted) {
      qh_fprintf(qh ferr, 6121, "qhull internal error (qh_checkfacet): deleted vertex v%d in f%d\n", vertex->id, facet->id);
      qh_errprint("ERRONEOUS", NULL, NULL, NULL, vertex);
      waserror= True;
    }
    if (vertex->id >= previousid) {
      qh_fprintf(qh ferr, 6122, "qhull internal error (qh_checkfacet): vertices of f%d are not in descending id order at v%d\n", facet->id, vertex->id);
      waserror= True;
      break;
    }
    previousid= vertex->id;
  }
  numneighbors= qh_setsize(facet->neighbors);
  numvertices= qh_setsize(facet->vertices);
  numridges= qh_setsize(facet->ridges);
  if (facet->simplicial) {
    if (numvertices+numneighbors != 2*qh hull_dim
    && !facet->degenerate && !facet->redundant) {
      qh_fprintf(qh ferr, 6123, "qhull internal error (qh_checkfacet): for simplicial facet f%d, #vertices %d + #neighbors %d != 2*qh hull_dim\n",
                facet->id, numvertices, numneighbors);
      qh_setprint(qh ferr, "", facet->neighbors);
      waserror= True;
    }
  }else { /* non-simplicial */
    if (!newmerge
    &&(numvertices < qh hull_dim || numneighbors < qh hull_dim)
    && !facet->degenerate && !facet->redundant) {
      qh_fprintf(qh ferr, 6124, "qhull internal error (qh_checkfacet): for facet f%d, #vertices %d or #neighbors %d < qh hull_dim\n",
         facet->id, numvertices, numneighbors);
       waserror= True;
    }
    /* in 3-d, can get a vertex twice in an edge list, e.g., RBOX 1000 s W1e-13 t995849315 D2 | QHULL d Tc Tv TP624 TW1e-13 T4 */
    if (numridges < numneighbors
    ||(qh hull_dim == 3 && numvertices > numridges && !qh NEWfacets)
    ||(qh hull_dim == 2 && numridges + numvertices + numneighbors != 6)) {
      if (!facet->degenerate && !facet->redundant) {
        qh_fprintf(qh ferr, 6125, "qhull internal error (qh_checkfacet): for facet f%d, #ridges %d < #neighbors %d or(3-d) > #vertices %d or(2-d) not all 2\n",
            facet->id, numridges, numneighbors, numvertices);
        waserror= True;
      }
    }
  }
  FOREACHneighbor_(facet) {
    if (neighbor == qh_MERGEridge || neighbor == qh_DUPLICATEridge) {
      qh_fprintf(qh ferr, 6126, "qhull internal error (qh_checkfacet): facet f%d still has a MERGE or DUP neighbor\n", facet->id);
      qh_errexit(qh_ERRqhull, facet, NULL);
    }
    neighbor->seen= True;
  }
  FOREACHneighbor_(facet) {
    if (!qh_setin(neighbor->neighbors, facet)) {
      qh_fprintf(qh ferr, 6127, "qhull internal error (qh_checkfacet): facet f%d has neighbor f%d, but f%d does not have neighbor f%d\n",
              facet->id, neighbor->id, neighbor->id, facet->id);
      errother= neighbor;
      waserror= True;
    }
    if (!neighbor->seen) {
      qh_fprintf(qh ferr, 6128, "qhull internal error (qh_checkfacet): facet f%d has a duplicate neighbor f%d\n",
              facet->id, neighbor->id);
      errother= neighbor;
      waserror= True;
    }
    neighbor->seen= False;
  }
  FOREACHridge_(facet->ridges) {
    qh_setcheck(ridge->vertices, "vertices for r", ridge->id);
    ridge->seen= False;
  }
  FOREACHridge_(facet->ridges) {
    if (ridge->seen) {
      qh_fprintf(qh ferr, 6129, "qhull internal error (qh_checkfacet): facet f%d has a duplicate ridge r%d\n",
              facet->id, ridge->id);
      errridge= ridge;
      waserror= True;
    }
    ridge->seen= True;
    numRvertices= qh_setsize(ridge->vertices);
    if (numRvertices != qh hull_dim - 1) {
      qh_fprintf(qh ferr, 6130, "qhull internal error (qh_checkfacet): ridge between f%d and f%d has %d vertices\n",
                ridge->top->id, ridge->bottom->id, numRvertices);
      errridge= ridge;
      waserror= True;
    }
    neighbor= otherfacet_(ridge, facet);
    neighbor->seen= True;
    if (!qh_setin(facet->neighbors, neighbor)) {
      qh_fprintf(qh ferr, 6131, "qhull internal error (qh_checkfacet): for facet f%d, neighbor f%d of ridge r%d not in facet\n",
           facet->id, neighbor->id, ridge->id);
      errridge= ridge;
      waserror= True;
    }
  }
  if (!facet->simplicial) {
    FOREACHneighbor_(facet) {
      if (!neighbor->seen) {
        qh_fprintf(qh ferr, 6132, "qhull internal error (qh_checkfacet): facet f%d does not have a ridge for neighbor f%d\n",
              facet->id, neighbor->id);
        errother= neighbor;
        waserror= True;
      }
      intersection= qh_vertexintersect_new(facet->vertices, neighbor->vertices);
      qh_settemppush(intersection);
      FOREACHvertex_(facet->vertices) {
        vertex->seen= False;
        vertex->seen2= False;
      }
      FOREACHvertex_(intersection)
        vertex->seen= True;
      FOREACHridge_(facet->ridges) {
        if (neighbor != otherfacet_(ridge, facet))
            continue;
        FOREACHvertex_(ridge->vertices) {
          if (!vertex->seen) {
            qh_fprintf(qh ferr, 6133, "qhull internal error (qh_checkfacet): vertex v%d in r%d not in f%d intersect f%d\n",
                  vertex->id, ridge->id, facet->id, neighbor->id);
            qh_errexit(qh_ERRqhull, facet, ridge);
          }
          vertex->seen2= True;
        }
      }
      if (!newmerge) {
        FOREACHvertex_(intersection) {
          if (!vertex->seen2) {
            if (qh IStracing >=3 || !qh MERGING) {
              qh_fprintf(qh ferr, 6134, "qhull precision error (qh_checkfacet): vertex v%d in f%d intersect f%d but\n\
 not in a ridge.  This is ok under merging.  Last point was p%d\n",
                     vertex->id, facet->id, neighbor->id, qh furthest_id);
              if (!qh FORCEoutput && !qh MERGING) {
                qh_errprint("ERRONEOUS", facet, neighbor, NULL, vertex);
                if (!qh MERGING)
                  qh_errexit(qh_ERRqhull, NULL, NULL);
              }
            }
          }
        }
      }
      qh_settempfree(&intersection);
    }
  }else { /* simplicial */
    FOREACHneighbor_(facet) {
      if (neighbor->simplicial) {
        skipA= SETindex_(facet->neighbors, neighbor);
        skipB= qh_setindex(neighbor->neighbors, facet);
        if (skipA<0 || skipB<0 || !qh_setequal_skip(facet->vertices, skipA, neighbor->vertices, skipB)) {
          qh_fprintf(qh ferr, 6135, "qhull internal error (qh_checkfacet): facet f%d skip %d and neighbor f%d skip %d do not match \n",
                   facet->id, skipA, neighbor->id, skipB);
          errother= neighbor;
          waserror= True;
        }
      }
    }
  }
  if (qh hull_dim < 5 && (qh IStracing > 2 || qh CHECKfrequently)) {
    FOREACHridge_i_(facet->ridges) {           /* expensive */
      for (i=ridge_i+1; i < ridge_n; i++) {
        ridge2= SETelemt_(facet->ridges, i, ridgeT);
        if (qh_setequal(ridge->vertices, ridge2->vertices)) {
          qh_fprintf(qh ferr, 6227, "Qhull internal error (qh_checkfacet): ridges r%d and r%d have the same vertices\n",
                  ridge->id, ridge2->id);
          errridge= ridge;
          waserror= True;
        }
      }
    }
  }
  if (waserror) {
    qh_errprint("ERRONEOUS", facet, errother, errridge, NULL);
    *waserrorp= True;
  }
} /* checkfacet */
References boolT, ridgeT::bottom, facetT::coplanarset, facetT::degenerate, False, FOREACHneighbor_, FOREACHridge_, FOREACHridge_i_, FOREACHvertex_, facetT::id, ridgeT::id, facetT::neighbors, facetT::normal, NULL, otherfacet_, facetT::outsideset, qh, qh_DUPLICATEridge, qh_errexit(), qh_errprint(), qh_ERRqhull, qh_fprintf(), qh_MERGEridge, qh_setcheck(), qh_setequal(), qh_setequal_skip(), qh_setin(), qh_setindex(), qh_setprint(), qh_setsize(), qh_settempfree(), qh_settemppush(), qh_vertexintersect_new(), facetT::redundant, facetT::ridges, facetT::seen, ridgeT::seen, SETelemt_, SETindex_, facetT::simplicial, ridgeT::top, True, facetT::vertices, ridgeT::vertices, and facetT::visible.
Referenced by qh_checkpolygon(), qh_tracemerge(), and qh_tracemerge().
qh_checkflipped()
boolT qh_checkflipped (facetT * facet, realT * dist, boolT allerror)
{
  realT dist;
  if (facet->flipped && !distp)
    return False;
  zzinc_(Zdistcheck);
  qh_distplane(qh interior_point, facet, &dist);
  if (distp)
    *distp= dist;
  if ((allerror && dist > -qh DISTround)|| (!allerror && dist >= 0.0)) {
    facet->flipped= True;
    zzinc_(Zflippedfacets);
    trace0((qh ferr, 19, "qh_checkflipped: facet f%d is flipped, distance= %6.12g during p%d\n",
              facet->id, dist, qh furthest_id));
    qh_precision("flipped facet");
    return False;
  }
  return True;
} /* checkflipped */
References False, facetT::flipped, facetT::id, qh, qh_distplane(), qh_precision(), realT, trace0, True, Zdistcheck, Zflippedfacets, and zzinc_.
Referenced by qh_checkflipped_all(), qh_checkflipped_all(), qh_initialhull(), qh_initialhull(), and qh_matchnewfacets().
qh_checkflipped_all()
void qh_checkflipped_all (facetT * facetlist)
{
  facetT *facet;
  boolT waserror= False;
  realT dist;
  if (facetlist == qh facet_list)
    zzval_(Zflippedfacets)= 0;
  FORALLfacet_(facetlist) {
    if (facet->normal && !qh_checkflipped(facet, &dist, !qh_ALL)) {
      qh_fprintf(qh ferr, 6136, "qhull precision error: facet f%d is flipped, distance= %6.12g\n",
              facet->id, dist);
      if (!qh FORCEoutput) {
        qh_errprint("ERRONEOUS", facet, NULL, NULL, NULL);
        waserror= True;
      }
    }
  }
  if (waserror) {
    qh_fprintf(qh ferr, 8101, "\n\
A flipped facet occurs when its distance to the interior point is\n\
greater than %2.2g, the maximum roundoff error.\n", -qh DISTround);
    qh_errexit(qh_ERRprec, NULL, NULL);
  }
} /* checkflipped_all */
References boolT, False, FORALLfacet_, facetT::id, facetT::normal, NULL, qh, qh_ALL, qh_checkflipped(), qh_errexit(), qh_ERRprec, qh_errprint(), qh_fprintf(), realT, True, Zflippedfacets, and zzval_.
Referenced by qh_check_output(), qh_matchnewfacets(), and qh_matchnewfacets().
qh_checkpolygon()
void qh_checkpolygon (facetT * facetlist)
{
  facetT *facet;
  vertexT *vertex, **vertexp, *vertexlist;
  int numfacets= 0, numvertices= 0, numridges= 0;
  int totvneighbors= 0, totvertices= 0;
  boolT waserror= False, nextseen= False, visibleseen= False;
  trace1((qh ferr, 1027, "qh_checkpolygon: check all facets from f%d\n", facetlist->id));
  if (facetlist != qh facet_list || qh ONLYgood)
    nextseen= True;
  FORALLfacet_(facetlist) {
    if (facet == qh visible_list)
      visibleseen= True;
    if (!facet->visible) {
      if (!nextseen) {
        if (facet == qh facet_next)
          nextseen= True;
        else if (qh_setsize(facet->outsideset)) {
          if (!qh NARROWhull
#if !qh_COMPUTEfurthest
               || facet->furthestdist >= qh MINoutside
#endif
                        ) {
            qh_fprintf(qh ferr, 6137, "qhull internal error (qh_checkpolygon): f%d has outside points before qh facet_next\n",
                     facet->id);
            qh_errexit(qh_ERRqhull, facet, NULL);
          }
        }
      }
      numfacets++;
      qh_checkfacet(facet, False, &waserror);
    }
  }
  if (qh visible_list && !visibleseen && facetlist == qh facet_list) {
    qh_fprintf(qh ferr, 6138, "qhull internal error (qh_checkpolygon): visible list f%d no longer on facet list\n", qh visible_list->id);
    qh_printlists();
    qh_errexit(qh_ERRqhull, qh visible_list, NULL);
  }
  if (facetlist == qh facet_list)
    vertexlist= qh vertex_list;
  else if (facetlist == qh newfacet_list)
    vertexlist= qh newvertex_list;
  else
    vertexlist= NULL;
  FORALLvertex_(vertexlist) {
    vertex->seen= False;
    vertex->visitid= 0;
  }
  FORALLfacet_(facetlist) {
    if (facet->visible)
      continue;
    if (facet->simplicial)
      numridges += qh hull_dim;
    else
      numridges += qh_setsize(facet->ridges);
    FOREACHvertex_(facet->vertices) {
      vertex->visitid++;
      if (!vertex->seen) {
        vertex->seen= True;
        numvertices++;
        if (qh_pointid(vertex->point) == qh_IDunknown) {
          qh_fprintf(qh ferr, 6139, "qhull internal error (qh_checkpolygon): unknown point %p for vertex v%d first_point %p\n",
                   vertex->point, vertex->id, qh first_point);
          waserror= True;
        }
      }
    }
  }
  qh vertex_visit += (unsigned int)numfacets;
  if (facetlist == qh facet_list) {
    if (numfacets != qh num_facets - qh num_visible) {
      qh_fprintf(qh ferr, 6140, "qhull internal error (qh_checkpolygon): actual number of facets is %d, cumulative facet count is %d - %d visible facets\n",
              numfacets, qh num_facets, qh num_visible);
      waserror= True;
    }
    qh vertex_visit++;
    if (qh VERTEXneighbors) {
      FORALLvertices {
        qh_setcheck(vertex->neighbors, "neighbors for v", vertex->id);
        if (vertex->deleted)
          continue;
        totvneighbors += qh_setsize(vertex->neighbors);
      }
      FORALLfacet_(facetlist)
        totvertices += qh_setsize(facet->vertices);
      if (totvneighbors != totvertices) {
        qh_fprintf(qh ferr, 6141, "qhull internal error (qh_checkpolygon): vertex neighbors inconsistent.  Totvneighbors %d, totvertices %d\n",
                totvneighbors, totvertices);
        waserror= True;
      }
    }
    if (numvertices != qh num_vertices - qh_setsize(qh del_vertices)) {
      qh_fprintf(qh ferr, 6142, "qhull internal error (qh_checkpolygon): actual number of vertices is %d, cumulative vertex count is %d\n",
              numvertices, qh num_vertices - qh_setsize(qh del_vertices));
      waserror= True;
    }
    if (qh hull_dim == 2 && numvertices != numfacets) {
      qh_fprintf(qh ferr, 6143, "qhull internal error (qh_checkpolygon): #vertices %d != #facets %d\n",
        numvertices, numfacets);
      waserror= True;
    }
    if (qh hull_dim == 3 && numvertices + numfacets - numridges/2 != 2) {
      qh_fprintf(qh ferr, 7063, "qhull warning: #vertices %d + #facets %d - #edges %d != 2\n\
        A vertex appears twice in a edge list.  May occur during merging.",
        numvertices, numfacets, numridges/2);
      /* occurs if lots of merging and a vertex ends up twice in an edge list.  e.g., RBOX 1000 s W1e-13 t995849315 D2 | QHULL d Tc Tv */
    }
  }
  if (waserror)
    qh_errexit(qh_ERRqhull, NULL, NULL);
} /* checkpolygon */
References boolT, False, FORALLfacet_, FORALLvertex_, FORALLvertices, FOREACHvertex_, facetT::furthestdist, facetT::id, int, NULL, facetT::outsideset, qh, qh_checkfacet(), qh_COMPUTEfurthest, qh_errexit(), qh_ERRqhull, qh_fprintf(), qh_IDunknown, qh_pointid(), qh_printlists(), qh_setcheck(), qh_setsize(), facetT::ridges, facetT::simplicial, trace1, True, facetT::vertices, and facetT::visible.
Referenced by qh_addpoint(), qh_addpoint(), qh_check_output(), qh_initialhull(), qh_prepare_output(), qh_prepare_output(), and qh_triangulate().
qh_checkvertex()
void qh_checkvertex (vertexT * vertex)
{
  boolT waserror= False;
  facetT *neighbor, **neighborp, *errfacet=NULL;
  if (qh_pointid(vertex->point) == qh_IDunknown) {
    qh_fprintf(qh ferr, 6144, "qhull internal error (qh_checkvertex): unknown point id %p\n", vertex->point);
    waserror= True;
  }
  if (vertex->id >= qh vertex_id) {
    qh_fprintf(qh ferr, 6145, "qhull internal error (qh_checkvertex): unknown vertex id %d\n", vertex->id);
    waserror= True;
  }
  if (!waserror && !vertex->deleted) {
    if (qh_setsize(vertex->neighbors)) {
      FOREACHneighbor_(vertex) {
        if (!qh_setin(neighbor->vertices, vertex)) {
          qh_fprintf(qh ferr, 6146, "qhull internal error (qh_checkvertex): neighbor f%d does not contain v%d\n", neighbor->id, vertex->id);
          errfacet= neighbor;
          waserror= True;
        }
      }
    }
  }
  if (waserror) {
    qh_errprint("ERRONEOUS", NULL, NULL, NULL, vertex);
    qh_errexit(qh_ERRqhull, errfacet, NULL);
  }
} /* checkvertex */
References boolT, False, FOREACHneighbor_, facetT::id, NULL, qh, qh_errexit(), qh_errprint(), qh_ERRqhull, qh_fprintf(), qh_IDunknown, qh_pointid(), qh_setin(), qh_setsize(), True, and facetT::vertices.
Referenced by qh_tracemerge(), and qh_tracemerge().
qh_clearcenters()
void qh_clearcenters (qh_CENTER type)
{
  facetT *facet;
  if (qh CENTERtype != type) {
    FORALLfacets {
      if (facet->tricoplanar && !facet->keepcentrum)
          facet->center= NULL;  /* center is owned by the ->keepcentrum facet */
      else if (qh CENTERtype == qh_ASvoronoi){
        if (facet->center) {
          qh_memfree(facet->center, qh center_size);
          facet->center= NULL;
        }
      }else /* qh.CENTERtype == qh_AScentrum */ {
        if (facet->center) {
          qh_memfree(facet->center, qh normal_size);
          facet->center= NULL;
        }
      }
    }
    qh CENTERtype= type;
  }
  trace2((qh ferr, 2043, "qh_clearcenters: switched to center type %d\n", type));
} /* clearcenters */
References facetT::center, FORALLfacets, facetT::keepcentrum, NULL, qh, qh_ASvoronoi, qh_memfree(), trace2, and facetT::tricoplanar.
Referenced by qh_eachvoronoi_all(), qh_eachvoronoi_all(), qh_markvoronoi(), qh_markvoronoi(), qh_prepare_output(), qh_prepare_output(), qh_printbegin(), qh_printbegin(), qh_setvoronoi_all(), and qh_triangulate().
qh_createsimplex()
void qh_createsimplex (setT * vertices)
{
  facetT *facet= NULL, *newfacet;
  boolT toporient= True;
  int vertex_i, vertex_n, nth;
  setT *newfacets= qh_settemp(qh hull_dim+1);
  vertexT *vertex;
  qh facet_list= qh newfacet_list= qh facet_tail= qh_newfacet();
  qh num_facets= qh num_vertices= qh num_visible= 0;
  qh vertex_list= qh newvertex_list= qh vertex_tail= qh_newvertex(NULL);
  FOREACHvertex_i_(vertices) {
    newfacet= qh_newfacet();
    newfacet->vertices= qh_setnew_delnthsorted(vertices, vertex_n,
                                                vertex_i, 0);
    newfacet->toporient= (unsigned char)toporient;
    qh_appendfacet(newfacet);
    newfacet->newfacet= True;
    qh_appendvertex(vertex);
    qh_setappend(&newfacets, newfacet);
    toporient ^= True;
  }
  FORALLnew_facets {
    nth= 0;
    FORALLfacet_(qh newfacet_list) {
      if (facet != newfacet)
        SETelem_(newfacet->neighbors, nth++)= facet;
    }
    qh_settruncate(newfacet->neighbors, qh hull_dim);
  }
  qh_settempfree(&newfacets);
  trace1((qh ferr, 1028, "qh_createsimplex: created simplex\n"));
} /* createsimplex */
References boolT, FORALLfacet_, FORALLnew_facets, FOREACHvertex_i_, NULL, qh, qh_appendfacet(), qh_appendvertex(), qh_newfacet(), qh_newvertex(), qh_setappend(), qh_setnew_delnthsorted(), qh_settemp(), qh_settempfree(), qh_settruncate(), SETelem_, trace1, and True.
Referenced by qh_initialhull().
qh_deletevisible()
void qh_deletevisible (void)
{
  facetT *visible, *nextfacet;
  vertexT *vertex, **vertexp;
  int numvisible= 0, numdel= qh_setsize(qh del_vertices);
  trace1((qh ferr, 1018, "qh_deletevisible: delete %d visible facets and %d vertices\n",
         qh num_visible, numdel));
  for (visible= qh visible_list; visible && visible->visible;
                visible= nextfacet) { /* deleting current */
    nextfacet= visible->next;
    numvisible++;
    qh_delfacet(visible);
  }
  if (numvisible != qh num_visible) {
    qh_fprintf(qh ferr, 6103, "qhull internal error (qh_deletevisible): qh num_visible %d is not number of visible facets %d\n",
             qh num_visible, numvisible);
    qh_errexit(qh_ERRqhull, NULL, NULL);
  }
  qh num_visible= 0;
  zadd_(Zvisfacettot, numvisible);
  zmax_(Zvisfacetmax, numvisible);
  zzadd_(Zdelvertextot, numdel);
  zmax_(Zdelvertexmax, numdel);
  FOREACHvertex_(qh del_vertices)
    qh_delvertex(vertex);
  qh_settruncate(qh del_vertices, 0);
} /* deletevisible */
References FOREACHvertex_, facetT::next, NULL, qh, qh_delfacet(), qh_delvertex(), qh_errexit(), qh_ERRqhull, qh_fprintf(), qh_setsize(), qh_settruncate(), trace1, facetT::visible, zadd_, Zdelvertextot, zmax_, and zzadd_.
Referenced by qh_addpoint(), qh_addpoint(), qh_qhull(), and qh_qhull().
qh_delfacet()
void qh_delfacet (facetT * facet)
{
  void **freelistp; /* used if !qh_NOmem by qh_memfree_() */
  trace4((qh ferr, 4046, "qh_delfacet: delete f%d\n", facet->id));
  if (facet == qh tracefacet)
    qh tracefacet= NULL;
  if (facet == qh GOODclosest)
    qh GOODclosest= NULL;
  qh_removefacet(facet);
  if (!facet->tricoplanar || facet->keepcentrum) {
    qh_memfree_(facet->normal, qh normal_size, freelistp);
    if (qh CENTERtype == qh_ASvoronoi) {   /* braces for macro calls */
      qh_memfree_(facet->center, qh center_size, freelistp);
    }else /* AScentrum */ {
      qh_memfree_(facet->center, qh normal_size, freelistp);
    }
  }
  qh_setfree(&(facet->neighbors));
  if (facet->ridges)
    qh_setfree(&(facet->ridges));
  qh_setfree(&(facet->vertices));
  if (facet->outsideset)
    qh_setfree(&(facet->outsideset));
  if (facet->coplanarset)
    qh_setfree(&(facet->coplanarset));
  qh_memfree_(facet, (int)sizeof(facetT), freelistp);
} /* delfacet */
References facetT::center, facetT::coplanarset, facetT::id, facetT::keepcentrum, facetT::neighbors, facetT::normal, NULL, facetT::outsideset, qh, qh_ASvoronoi, qh_memfree_, qh_removefacet(), qh_setfree(), facetT::ridges, trace4, facetT::tricoplanar, and facetT::vertices.
Referenced by qh_addpoint(), qh_addpoint(), qh_deletevisible(), qh_freebuild(), qh_freebuild(), qh_triangulate(), and qh_triangulate().
qh_delridge()
void qh_delridge (ridgeT * ridge)
{
  void **freelistp; /* used if !qh_NOmem by qh_memfree_() */
  qh_setdel(ridge->top->ridges, ridge);
  qh_setdel(ridge->bottom->ridges, ridge);
  qh_setfree(&(ridge->vertices));
  qh_memfree_(ridge, (int)sizeof(ridgeT), freelistp);
} /* delridge */
References ridgeT::bottom, qh_memfree_, qh_setdel(), qh_setfree(), facetT::ridges, ridgeT::top, and ridgeT::vertices.
Referenced by qh_mergeridges(), qh_mergeridges(), qh_renameridgevertex(), and qh_renameridgevertex().
qh_delvertex()
void qh_delvertex (vertexT * vertex)
{
  if (vertex == qh tracevertex)
    qh tracevertex= NULL;
  qh_removevertex(vertex);
  qh_setfree(&vertex->neighbors);
  qh_memfree(vertex, (int)sizeof(vertexT));
} /* delvertex */
References NULL, qh, qh_memfree(), qh_removevertex(), and qh_setfree().
Referenced by qh_addpoint(), qh_addpoint(), qh_deletevisible(), qh_deletevisible(), qh_freebuild(), and qh_freebuild().
qh_facet3vertex()
setT * qh_facet3vertex (facetT * facet)
{
  ridgeT *ridge, *firstridge;
  vertexT *vertex;
  int cntvertices, cntprojected=0;
  setT *vertices;
  cntvertices= qh_setsize(facet->vertices);
  vertices= qh_settemp(cntvertices);
  if (facet->simplicial) {
    if (cntvertices != 3) {
      qh_fprintf(qh ferr, 6147, "qhull internal error (qh_facet3vertex): only %d vertices for simplicial facet f%d\n",
                  cntvertices, facet->id);
      qh_errexit(qh_ERRqhull, facet, NULL);
    }
    qh_setappend(&vertices, SETfirst_(facet->vertices));
    if (facet->toporient ^ qh_ORIENTclock)
      qh_setappend(&vertices, SETsecond_(facet->vertices));
    else
      qh_setaddnth(&vertices, 0, SETsecond_(facet->vertices));
    qh_setappend(&vertices, SETelem_(facet->vertices, 2));
  }else {
    ridge= firstridge= SETfirstt_(facet->ridges, ridgeT);   /* no infinite */
    while ((ridge= qh_nextridge3d(ridge, facet, &vertex))) {
      qh_setappend(&vertices, vertex);
      if (++cntprojected > cntvertices || ridge == firstridge)
        break;
    }
    if (!ridge || cntprojected != cntvertices) {
      qh_fprintf(qh ferr, 6148, "qhull internal error (qh_facet3vertex): ridges for facet %d don't match up.  got at least %d\n",
                  facet->id, cntprojected);
      qh_errexit(qh_ERRqhull, facet, ridge);
    }
  }
  return vertices;
} /* facet3vertex */
References facetT::id, NULL, qh, qh_errexit(), qh_ERRqhull, qh_fprintf(), qh_nextridge3d(), qh_ORIENTclock, qh_setaddnth(), qh_setappend(), qh_setsize(), qh_settemp(), facetT::ridges, SETelem_, SETfirst_, SETfirstt_, SETsecond_, facetT::simplicial, facetT::toporient, and facetT::vertices.
Referenced by qh_printfacet3geom_nonsimplicial(), qh_printfacet3geom_nonsimplicial(), qh_printfacet3geom_simplicial(), qh_printfacet3geom_simplicial(), qh_printfacet3math(), qh_printfacet3math(), qh_printfacet3vertex(), and qh_printfacet3vertex().
qh_facetintersect()
setT * qh_facetintersect (facetT * facetA, facetT * facetB, int * skipAp, int * skipBp, int extra)
{
  setT *intersect;
  int dim= qh hull_dim, i, j;
  facetT **neighborsA, **neighborsB;
  neighborsA= SETaddr_(facetA->neighbors, facetT);
  neighborsB= SETaddr_(facetB->neighbors, facetT);
  i= j= 0;
  if (facetB == *neighborsA++)
    *skipA= 0;
  else if (facetB == *neighborsA++)
    *skipA= 1;
  else if (facetB == *neighborsA++)
    *skipA= 2;
  else {
    for (i=3; i < dim; i++) {
      if (facetB == *neighborsA++) {
        *skipA= i;
        break;
      }
    }
  }
  if (facetA == *neighborsB++)
    *skipB= 0;
  else if (facetA == *neighborsB++)
    *skipB= 1;
  else if (facetA == *neighborsB++)
    *skipB= 2;
  else {
    for (j=3; j < dim; j++) {
      if (facetA == *neighborsB++) {
        *skipB= j;
        break;
      }
    }
  }
  if (i >= dim || j >= dim) {
    qh_fprintf(qh ferr, 6104, "qhull internal error (qh_facetintersect): f%d or f%d not in others neighbors\n",
            facetA->id, facetB->id);
    qh_errexit2(qh_ERRqhull, facetA, facetB);
  }
  intersect= qh_setnew_delnthsorted(facetA->vertices, qh hull_dim, *skipA, prepend);
  trace4((qh ferr, 4047, "qh_facetintersect: f%d skip %d matches f%d skip %d\n",
          facetA->id, *skipA, facetB->id, *skipB));
  return(intersect);
} /* facetintersect */
References facetT::id, facetT::neighbors, qh, qh_errexit2(), qh_ERRqhull, qh_fprintf(), qh_setnew_delnthsorted(), SETaddr_, trace4, and facetT::vertices.
Referenced by qh_makenew_simplicial().
qh_findbestfacet()
facetT * qh_findbestfacet (pointT * point, boolT bestoutside, realT * bestdist, boolT * isoutside)
{
  facetT *bestfacet= NULL;
  int numpart, totpart= 0;
  bestfacet= qh_findbest(point, qh facet_list,
                            bestoutside, !qh_ISnewfacets, bestoutside /* qh_NOupper */,
                            bestdist, isoutside, &totpart);
  if (*bestdist < -qh DISTround) {
    bestfacet= qh_findfacet_all(point, bestdist, isoutside, &numpart);
    totpart += numpart;
    if ((isoutside && *isoutside && bestoutside)
    || (isoutside && !*isoutside && bestfacet->upperdelaunay)) {
      bestfacet= qh_findbest(point, bestfacet,
                            bestoutside, False, bestoutside,
                            bestdist, isoutside, &totpart);
      totpart += numpart;
    }
  }
  trace3((qh ferr, 3014, "qh_findbestfacet: f%d dist %2.2g isoutside %d totpart %d\n",
      bestfacet->id, *bestdist, (isoutside ? *isoutside : UINT_MAX), totpart));
  return bestfacet;
} /* findbestfacet */
qh_findbestlower()
facetT * qh_findbestlower (facetT * upperfacet, pointT * point, realT * bestdistp, int * numpart)
{
  facetT *neighbor, **neighborp, *bestfacet= NULL;
  realT bestdist= -REALmax/2 /* avoid underflow */;
  realT dist;
  vertexT *vertex;
  boolT isoutside= False;  /* not used */
  zinc_(Zbestlower);
  FOREACHneighbor_(upperfacet) {
    if (neighbor->upperdelaunay || neighbor->flipped)
      continue;
    (*numpart)++;
    qh_distplane(point, neighbor, &dist);
    if (dist > bestdist) {
      bestfacet= neighbor;
      bestdist= dist;
    }
  }
  if (!bestfacet) {
    zinc_(Zbestlowerv);
    /* rarely called, numpart does not count nearvertex computations */
    vertex= qh_nearvertex(upperfacet, point, &dist);
    qh_vertexneighbors();
    FOREACHneighbor_(vertex) {
      if (neighbor->upperdelaunay || neighbor->flipped)
        continue;
      (*numpart)++;
      qh_distplane(point, neighbor, &dist);
      if (dist > bestdist) {
        bestfacet= neighbor;
        bestdist= dist;
      }
    }
  }
  if (!bestfacet) {
    zinc_(Zbestlowerall);  /* invoked once per point in outsideset */
    zmax_(Zbestloweralln, qh num_facets);
    /* [dec'15] Previously reported as QH6228 */
    trace3((qh ferr, 3025, "qh_findbestlower: all neighbors of facet %d are flipped or upper Delaunay.  Search all facets\n",
        upperfacet->id));
    /* rarely called */
    bestfacet= qh_findfacet_all(point, &bestdist, &isoutside, numpart);
  }
  *bestdistp= bestdist;
  trace3((qh ferr, 3015, "qh_findbestlower: f%d dist %2.2g for f%d p%d\n",
          bestfacet->id, bestdist, upperfacet->id, qh_pointid(point)));
  return bestfacet;
} /* findbestlower */
References boolT, False, facetT::flipped, FOREACHneighbor_, facetT::id, NULL, qh, qh_distplane(), qh_findfacet_all(), qh_nearvertex(), qh_pointid(), qh_vertexneighbors(), REALmax, realT, trace3, facetT::upperdelaunay, zinc_, and zmax_.
Referenced by qh_findbest(), and qh_findbest().
qh_findfacet_all()
facetT * qh_findfacet_all (pointT * point, realT * bestdist, boolT * isoutside, int * numpart)
{
  facetT *bestfacet= NULL, *facet;
  realT dist;
  int totpart= 0;
  *bestdist= -REALmax;
  *isoutside= False;
  FORALLfacets {
    if (facet->flipped || !facet->normal)
      continue;
    totpart++;
    qh_distplane(point, facet, &dist);
    if (dist > *bestdist) {
      *bestdist= dist;
      bestfacet= facet;
      if (dist > qh MINoutside) {
        *isoutside= True;
        break;
      }
    }
  }
  *numpart= totpart;
  trace3((qh ferr, 3016, "qh_findfacet_all: f%d dist %2.2g isoutside %d totpart %d\n",
          getid_(bestfacet), *bestdist, *isoutside, totpart));
  return bestfacet;
} /* findfacet_all */
References False, FORALLfacets, getid_, NULL, qh, qh_distplane(), REALmax, realT, trace3, and True.
Referenced by qh_findbestfacet(), and qh_findbestlower().
qh_findgood()
int qh_findgood (facetT * facetlist, int goodhorizon)
{
  facetT *facet, *bestfacet= NULL;
  realT angle, bestangle= REALmax, dist;
  int  numgood=0;
  FORALLfacet_(facetlist) {
    if (facet->good)
      numgood++;
  }
  if (qh GOODvertex>0 && !qh MERGING) {
    FORALLfacet_(facetlist) {
      if (!qh_isvertex(qh GOODvertexp, facet->vertices)) {
        facet->good= False;
        numgood--;
      }
    }
  }
  if (qh GOODpoint && numgood) {
    FORALLfacet_(facetlist) {
      if (facet->good && facet->normal) {
        zinc_(Zdistgood);
        qh_distplane(qh GOODpointp, facet, &dist);
        if ((qh GOODpoint > 0) ^ (dist > 0.0)) {
          facet->good= False;
          numgood--;
        }
      }
    }
  }
  if (qh GOODthreshold && (numgood || goodhorizon || qh GOODclosest)) {
    FORALLfacet_(facetlist) {
      if (facet->good && facet->normal) {
        if (!qh_inthresholds(facet->normal, &angle)) {
          facet->good= False;
          numgood--;
          if (angle < bestangle) {
            bestangle= angle;
            bestfacet= facet;
          }
        }
      }
    }
    if (!numgood && (!goodhorizon || qh GOODclosest)) {
      if (qh GOODclosest) {
        if (qh GOODclosest->visible)
          qh GOODclosest= NULL;
        else {
          qh_inthresholds(qh GOODclosest->normal, &angle);
          if (angle < bestangle)
            bestfacet= qh GOODclosest;
        }
      }
      if (bestfacet && bestfacet != qh GOODclosest) {
        if (qh GOODclosest)
          qh GOODclosest->good= False;
        qh GOODclosest= bestfacet;
        bestfacet->good= True;
        numgood++;
        trace2((qh ferr, 2044, "qh_findgood: f%d is closest(%2.2g) to thresholds\n",
           bestfacet->id, bestangle));
        return numgood;
      }
    }else if (qh GOODclosest) { /* numgood > 0 */
      qh GOODclosest->good= False;
      qh GOODclosest= NULL;
    }
  }
  zadd_(Zgoodfacet, numgood);
  trace2((qh ferr, 2045, "qh_findgood: found %d good facets with %d good horizon\n",
               numgood, goodhorizon));
  if (!numgood && qh GOODvertex>0 && !qh MERGING)
    return goodhorizon;
  return numgood;
} /* findgood */
References False, FORALLfacet_, facetT::good, facetT::id, facetT::normal, NULL, qh, qh_distplane(), qh_inthresholds(), qh_isvertex(), REALmax, realT, trace2, True, facetT::vertices, zadd_, and zinc_.
Referenced by qh_addpoint(), qh_addpoint(), qh_findgood_all(), and qh_initbuild().
qh_findgood_all()
void qh_findgood_all (facetT * facetlist)
{
  facetT *facet, *bestfacet=NULL;
  realT angle, bestangle= REALmax;
  int  numgood=0, startgood;
  if (!qh GOODvertex && !qh GOODthreshold && !qh GOODpoint
  && !qh SPLITthresholds)
    return;
  if (!qh ONLYgood)
    qh_findgood(qh facet_list, 0);
  FORALLfacet_(facetlist) {
    if (facet->good)
      numgood++;
  }
  if (qh GOODvertex <0 || (qh GOODvertex > 0 && qh MERGING)) {
    FORALLfacet_(facetlist) {
      if (facet->good && ((qh GOODvertex > 0) ^ !!qh_isvertex(qh GOODvertexp, facet->vertices))) {
        if (!--numgood) {
          if (qh ONLYgood) {
            qh_fprintf(qh ferr, 7064, "qhull warning: good vertex p%d does not match last good facet f%d.  Ignored.\n",
               qh_pointid(qh GOODvertexp), facet->id);
            return;
          }else if (qh GOODvertex > 0)
            qh_fprintf(qh ferr, 7065, "qhull warning: point p%d is not a vertex('QV%d').\n",
                qh GOODvertex-1, qh GOODvertex-1);
          else
            qh_fprintf(qh ferr, 7066, "qhull warning: point p%d is a vertex for every facet('QV-%d').\n",
                -qh GOODvertex - 1, -qh GOODvertex - 1);
        }
        facet->good= False;
      }
    }
  }
  startgood= numgood;
  if (qh SPLITthresholds) {
    FORALLfacet_(facetlist) {
      if (facet->good) {
        if (!qh_inthresholds(facet->normal, &angle)) {
          facet->good= False;
          numgood--;
          if (angle < bestangle) {
            bestangle= angle;
            bestfacet= facet;
          }
        }
      }
    }
    if (!numgood && bestfacet) {
      bestfacet->good= True;
      numgood++;
      trace0((qh ferr, 23, "qh_findgood_all: f%d is closest(%2.2g) to thresholds\n",
           bestfacet->id, bestangle));
      return;
    }
  }
  qh num_good= numgood;
  trace0((qh ferr, 24, "qh_findgood_all: %d good facets remain out of %d facets\n",
        numgood, startgood));
} /* findgood_all */
References False, FORALLfacet_, facetT::good, facetT::id, facetT::normal, NULL, qh, qh_findgood(), qh_fprintf(), qh_inthresholds(), qh_isvertex(), qh_pointid(), REALmax, realT, trace0, True, and facetT::vertices.
Referenced by qh_prepare_output(), qh_prepare_output(), qh_printneighborhood(), and qh_printneighborhood().
qh_furthestnext()
void qh_furthestnext (void)
{
  facetT *facet, *bestfacet= NULL;
  realT dist, bestdist= -REALmax;
  FORALLfacets {
    if (facet->outsideset) {
#if qh_COMPUTEfurthest
      pointT *furthest;
      furthest= (pointT*)qh_setlast(facet->outsideset);
      zinc_(Zcomputefurthest);
      qh_distplane(furthest, facet, &dist);
#else
      dist= facet->furthestdist;
#endif
      if (dist > bestdist) {
        bestfacet= facet;
        bestdist= dist;
      }
    }
  }
  if (bestfacet) {
    qh_removefacet(bestfacet);
    qh_prependfacet(bestfacet, &qh facet_next);
    trace1((qh ferr, 1029, "qh_furthestnext: made f%d next facet(dist %.2g)\n",
            bestfacet->id, bestdist));
  }
} /* furthestnext */
References FORALLfacets, facetT::furthestdist, facetT::id, NULL, facetT::outsideset, pointT, qh, qh_distplane(), qh_prependfacet(), qh_removefacet(), qh_setlast(), REALmax, realT, trace1, and zinc_.
Referenced by qh_initbuild(), qh_initbuild(), qh_nextfurthest(), and qh_nextfurthest().
qh_furthestout()
void qh_furthestout (facetT * facet)
{
  pointT *point, **pointp, *bestpoint= NULL;
  realT dist, bestdist= -REALmax;
  FOREACHpoint_(facet->outsideset) {
    qh_distplane(point, facet, &dist);
    zinc_(Zcomputefurthest);
    if (dist > bestdist) {
      bestpoint= point;
      bestdist= dist;
    }
  }
  if (bestpoint) {
    qh_setdel(facet->outsideset, point);
    qh_setappend(&facet->outsideset, point);
#if !qh_COMPUTEfurthest
    facet->furthestdist= bestdist;
#endif
  }
  facet->notfurthest= False;
  trace3((qh ferr, 3017, "qh_furthestout: p%d is furthest outside point of f%d\n",
          qh_pointid(point), facet->id));
} /* furthestout */
References False, FOREACHpoint_, facetT::furthestdist, facetT::id, facetT::notfurthest, NULL, facetT::outsideset, pointT, qh, qh_distplane(), qh_pointid(), qh_setappend(), qh_setdel(), REALmax, realT, trace3, and zinc_.
Referenced by qh_nextfurthest(), and qh_nextfurthest().
qh_gethash()
int qh_gethash (int hashsize, setT * set, int size, int firstindex, void * skipelem)
{
  void **elemp= SETelemaddr_(set, firstindex, void);
  ptr_intT hash = 0, elem;
  unsigned result;
  int i;
#ifdef _MSC_VER                   /* Microsoft Visual C++ -- warn about 64-bit issues */
#pragma warning(push)            /* WARN64 -- ptr_intT holds a 64-bit pointer */
#pragma warning(disable : 4311)  /* 'type cast': pointer truncation from 'void*' to 'ptr_intT' */
#endif
  switch (size-firstindex) {
  case 1:
    hash= (ptr_intT)(*elemp) - (ptr_intT) skipelem;
    break;
  case 2:
    hash= (ptr_intT)(*elemp) + (ptr_intT)elemp[1] - (ptr_intT) skipelem;
    break;
  case 3:
    hash= (ptr_intT)(*elemp) + (ptr_intT)elemp[1] + (ptr_intT)elemp[2]
      - (ptr_intT) skipelem;
    break;
  case 4:
    hash= (ptr_intT)(*elemp) + (ptr_intT)elemp[1] + (ptr_intT)elemp[2]
      + (ptr_intT)elemp[3] - (ptr_intT) skipelem;
    break;
  case 5:
    hash= (ptr_intT)(*elemp) + (ptr_intT)elemp[1] + (ptr_intT)elemp[2]
      + (ptr_intT)elemp[3] + (ptr_intT)elemp[4] - (ptr_intT) skipelem;
    break;
  case 6:
    hash= (ptr_intT)(*elemp) + (ptr_intT)elemp[1] + (ptr_intT)elemp[2]
      + (ptr_intT)elemp[3] + (ptr_intT)elemp[4]+ (ptr_intT)elemp[5]
      - (ptr_intT) skipelem;
    break;
  default:
    hash= 0;
    i= 3;
    do {     /* this is about 10% in 10-d */
      if ((elem= (ptr_intT)*elemp++) != (ptr_intT)skipelem) {
        hash ^= (elem << i) + (elem >> (32-i));
        i += 3;
        if (i >= 32)
          i -= 32;
      }
    }while (*elemp);
    break;
  }
  if (hashsize<0) {
    qh_fprintf(qh ferr, 6202, "qhull internal error: negative hashsize %d passed to qh_gethash [poly.c]\n", hashsize);
    qh_errexit2(qh_ERRqhull, NULL, NULL);
  }
  result= (unsigned)hash;
  result %= (unsigned)hashsize;
  /* result= 0; for debugging */
  return result;
#ifdef _MSC_VER
#pragma warning(pop)
#endif
} /* gethash */
References hash(), NULL, qh, qh_errexit2(), qh_ERRqhull, qh_fprintf(), SETelemaddr_, and size.
Referenced by qh_hashridge(), qh_hashridge(), qh_hashridge_find(), qh_hashridge_find(), qh_matchduplicates(), qh_matchduplicates(), and qh_matchneighbor().
qh_infiniteloop()
void qh_infiniteloop (facetT * facet)
{
  qh_fprintf(qh ferr, 6149, "qhull internal error (qh_infiniteloop): potential infinite loop detected\n");
  qh_errexit(qh_ERRqhull, facet, NULL);
} /* qh_infiniteloop */
References NULL, qh, qh_errexit(), qh_ERRqhull, and qh_fprintf().
Referenced by qh_mergecycle_all(), qh_mergecycle_all(), qh_mergecycle_neighbors(), qh_mergecycle_neighbors(), qh_partitionvisible(), and qh_partitionvisible().
qh_initbuild()
void qh_initbuild (void)
{
  setT *maxpoints, *vertices;
  facetT *facet;
  int i, numpart;
  realT dist;
  boolT isoutside;
  qh furthest_id= qh_IDunknown;
  qh lastreport= 0;
  qh facet_id= qh vertex_id= qh ridge_id= 0;
  qh visit_id= qh vertex_visit= 0;
  qh maxoutdone= False;
  if (qh GOODpoint > 0)
    qh GOODpointp= qh_point(qh GOODpoint-1);
  else if (qh GOODpoint < 0)
    qh GOODpointp= qh_point(-qh GOODpoint-1);
  if (qh GOODvertex > 0)
    qh GOODvertexp= qh_point(qh GOODvertex-1);
  else if (qh GOODvertex < 0)
    qh GOODvertexp= qh_point(-qh GOODvertex-1);
  if ((qh GOODpoint
       && (qh GOODpointp < qh first_point  /* also catches !GOODpointp */
           || qh GOODpointp > qh_point(qh num_points-1)))
    || (qh GOODvertex
        && (qh GOODvertexp < qh first_point  /* also catches !GOODvertexp */
            || qh GOODvertexp > qh_point(qh num_points-1)))) {
    qh_fprintf(qh ferr, 6150, "qhull input error: either QGn or QVn point is > p%d\n",
             qh num_points-1);
    qh_errexit(qh_ERRinput, NULL, NULL);
  }
  maxpoints= qh_maxmin(qh first_point, qh num_points, qh hull_dim);
  if (qh SCALElast)
    qh_scalelast(qh first_point, qh num_points, qh hull_dim,
               qh MINlastcoord, qh MAXlastcoord, qh MAXwidth);
  qh_detroundoff();
  if (qh DELAUNAY && qh upper_threshold[qh hull_dim-1] > REALmax/2
                  && qh lower_threshold[qh hull_dim-1] < -REALmax/2) {
    for (i=qh_PRINTEND; i--; ) {
      if (qh PRINTout[i] == qh_PRINTgeom && qh DROPdim < 0
          && !qh GOODthreshold && !qh SPLITthresholds)
        break;  /* in this case, don't set upper_threshold */
    }
    if (i < 0) {
      if (qh UPPERdelaunay) { /* matches qh.upperdelaunay in qh_setfacetplane */
        qh lower_threshold[qh hull_dim-1]= qh ANGLEround * qh_ZEROdelaunay;
        qh GOODthreshold= True;
      }else {
        qh upper_threshold[qh hull_dim-1]= -qh ANGLEround * qh_ZEROdelaunay;
        if (!qh GOODthreshold)
          qh SPLITthresholds= True; /* build upper-convex hull even if Qg */
          /* qh_initqhull_globals errors if Qg without Pdk/etc. */
      }
    }
  }
  vertices= qh_initialvertices(qh hull_dim, maxpoints, qh first_point, qh num_points);
  qh_initialhull(vertices);  /* initial qh facet_list */
  qh_partitionall(vertices, qh first_point, qh num_points);
  if (qh PRINToptions1st || qh TRACElevel || qh IStracing) {
    if (qh TRACElevel || qh IStracing)
      qh_fprintf(qh ferr, 8103, "\nTrace level %d for %s | %s\n",
         qh IStracing ? qh IStracing : qh TRACElevel, qh rbox_command, qh qhull_command);
    qh_fprintf(qh ferr, 8104, "Options selected for Qhull %s:\n%s\n", qh_version, qh qhull_options);
  }
  qh_resetlists(False, qh_RESETvisible /*qh.visible_list newvertex_list newfacet_list */);
  qh facet_next= qh facet_list;
  qh_furthestnext(/* qh.facet_list */);
  if (qh PREmerge) {
    qh cos_max= qh premerge_cos;
    qh centrum_radius= qh premerge_centrum;
  }
  if (qh ONLYgood) {
    if (qh GOODvertex > 0 && qh MERGING) {
      qh_fprintf(qh ferr, 6151, "qhull input error: 'Qg QVn' (only good vertex) does not work with merging.\nUse 'QJ' to joggle the input or 'Q0' to turn off merging.\n");
      qh_errexit(qh_ERRinput, NULL, NULL);
    }
    if (!(qh GOODthreshold || qh GOODpoint
         || (!qh MERGEexact && !qh PREmerge && qh GOODvertexp))) {
      qh_fprintf(qh ferr, 6152, "qhull input error: 'Qg' (ONLYgood) needs a good threshold('Pd0D0'), a\n\
good point(QGn or QG-n), or a good vertex with 'QJ' or 'Q0' (QVn).\n");
      qh_errexit(qh_ERRinput, NULL, NULL);
    }
    if (qh GOODvertex > 0  && !qh MERGING  /* matches qh_partitionall */
        && !qh_isvertex(qh GOODvertexp, vertices)) {
      facet= qh_findbestnew(qh GOODvertexp, qh facet_list,
                          &dist, !qh_ALL, &isoutside, &numpart);
      zadd_(Zdistgood, numpart);
      if (!isoutside) {
        qh_fprintf(qh ferr, 6153, "qhull input error: point for QV%d is inside initial simplex.  It can not be made a vertex.\n",
               qh_pointid(qh GOODvertexp));
        qh_errexit(qh_ERRinput, NULL, NULL);
      }
      if (!qh_addpoint(qh GOODvertexp, facet, False)) {
        qh_settempfree(&vertices);
        qh_settempfree(&maxpoints);
        return;
      }
    }
    qh_findgood(qh facet_list, 0);
  }
  qh_settempfree(&vertices);
  qh_settempfree(&maxpoints);
  trace1((qh ferr, 1030, "qh_initbuild: initial hull created and points partitioned\n"));
} /* initbuild */
References boolT, False, NULL, qh, qh_addpoint(), qh_ALL, qh_detroundoff(), qh_errexit(), qh_ERRinput, qh_findbestnew(), qh_findgood(), qh_fprintf(), qh_furthestnext(), qh_IDunknown, qh_initialhull(), qh_initialvertices(), qh_isvertex(), qh_maxmin(), qh_partitionall(), qh_point(), qh_pointid(), qh_PRINTEND, qh_PRINTgeom, qh_resetlists(), qh_RESETvisible, qh_scalelast(), qh_settempfree(), qh_version, qh_ZEROdelaunay, REALmax, realT, trace1, True, and zadd_.
Referenced by qh_build_withrestart(), qh_build_withrestart(), qh_qhull(), and qh_qhull().
qh_initialhull()
void qh_initialhull (setT * vertices)
{
  facetT *facet, *firstfacet, *neighbor, **neighborp;
  realT dist, angle, minangle= REALmax;
#ifndef qh_NOtrace
  int k;
#endif
  qh_createsimplex(vertices);  /* qh.facet_list */
  qh_resetlists(False, qh_RESETvisible);
  qh facet_next= qh facet_list;      /* advance facet when processed */
  qh interior_point= qh_getcenter(vertices);
  firstfacet= qh facet_list;
  qh_setfacetplane(firstfacet);
  zinc_(Znumvisibility); /* needs to be in printsummary */
  qh_distplane(qh interior_point, firstfacet, &dist);
  if (dist > 0) {
    FORALLfacets
      facet->toporient ^= (unsigned char)True;
  }
  FORALLfacets
    qh_setfacetplane(facet);
  FORALLfacets {
    if (!qh_checkflipped(facet, NULL, qh_ALL)) {/* due to axis-parallel facet */
      trace1((qh ferr, 1031, "qh_initialhull: initial orientation incorrect.  Correct all facets\n"));
      facet->flipped= False;
      FORALLfacets {
        facet->toporient ^= (unsigned char)True;
        qh_orientoutside(facet);
      }
      break;
    }
  }
  FORALLfacets {
    if (!qh_checkflipped(facet, NULL, !qh_ALL)) {  /* can happen with 'R0.1' */
      if (qh DELAUNAY && ! qh ATinfinity) {
        if (qh UPPERdelaunay)
          qh_fprintf(qh ferr, 6240, "Qhull precision error: Initial simplex is cocircular or cospherical.  Option 'Qs' searches all points.  Can not compute the upper Delaunay triangulation or upper Voronoi diagram of cocircular/cospherical points.\n");
        else
          qh_fprintf(qh ferr, 6239, "Qhull precision error: Initial simplex is cocircular or cospherical.  Use option 'Qz' for the Delaunay triangulation or Voronoi diagram of cocircular/cospherical points.  Option 'Qz' adds a point \"at infinity\".    Use option 'Qs' to search all points for the initial simplex.\n");
        qh_errexit(qh_ERRinput, NULL, NULL);
      }
      qh_precision("initial simplex is flat");
      qh_fprintf(qh ferr, 6154, "Qhull precision error: Initial simplex is flat (facet %d is coplanar with the interior point)\n",
                 facet->id);
      qh_errexit(qh_ERRsingular, NULL, NULL);  /* calls qh_printhelp_singular */
    }
    FOREACHneighbor_(facet) {
      angle= qh_getangle(facet->normal, neighbor->normal);
      minimize_( minangle, angle);
    }
  }
  if (minangle < qh_MAXnarrow && !qh NOnarrow) {
    realT diff= 1.0 + minangle;
    qh NARROWhull= True;
    qh_option("_narrow-hull", NULL, &diff);
    if (minangle < qh_WARNnarrow && !qh RERUN && qh PRINTprecision)
      qh_printhelp_narrowhull(qh ferr, minangle);
  }
  zzval_(Zprocessed)= qh hull_dim+1;
  qh_checkpolygon(qh facet_list);
  qh_checkconvex(qh facet_list,   qh_DATAfault);
#ifndef qh_NOtrace
  if (qh IStracing >= 1) {
    qh_fprintf(qh ferr, 8105, "qh_initialhull: simplex constructed, interior point:");
    for (k=0; k < qh hull_dim; k++)
      qh_fprintf(qh ferr, 8106, " %6.4g", qh interior_point[k]);
    qh_fprintf(qh ferr, 8107, "\n");
  }
#endif
} /* initialhull */
References False, facetT::flipped, FORALLfacets, FOREACHneighbor_, facetT::id, minimize_, facetT::normal, NULL, qh, qh_ALL, qh_checkconvex(), qh_checkflipped(), qh_checkpolygon(), qh_createsimplex(), qh_DATAfault, qh_distplane(), qh_errexit(), qh_ERRinput, qh_ERRsingular, qh_fprintf(), qh_getangle(), qh_getcenter(), qh_MAXnarrow, qh_option(), qh_orientoutside(), qh_precision(), qh_printhelp_narrowhull(), qh_resetlists(), qh_RESETvisible, qh_setfacetplane(), qh_WARNnarrow, REALmax, realT, facetT::toporient, trace1, True, zinc_, Znumvisibility, Zprocessed, and zzval_.
Referenced by qh_initbuild().
qh_initialvertices()
setT * qh_initialvertices (int dim, setT * maxpoints, pointT * points, int numpoints)
{
  pointT *point, **pointp;
  setT *vertices, *simplex, *tested;
  realT randr;
  int idx, point_i, point_n, k;
  boolT nearzero= False;
  vertices= qh_settemp(dim + 1);
  simplex= qh_settemp(dim+1);
  if (qh ALLpoints)
    qh_maxsimplex(dim, NULL, points, numpoints, &simplex);
  else if (qh RANDOMoutside) {
    while (qh_setsize(simplex) != dim+1) {
      randr= qh_RANDOMint;
      randr= randr/(qh_RANDOMmax+1);
      idx= (int)floor(qh num_points * randr);
      while (qh_setin(simplex, qh_point(idx))) {
        idx++; /* in case qh_RANDOMint always returns the same value */
        idx= idx < qh num_points ? idx : 0;
      }
      qh_setappend(&simplex, qh_point(idx));
    }
  }else if (qh hull_dim >= qh_INITIALmax) {
    tested= qh_settemp(dim+1);
    qh_setappend(&simplex, SETfirst_(maxpoints));   /* max and min X coord */
    qh_setappend(&simplex, SETsecond_(maxpoints));
    qh_maxsimplex(fmin_(qh_INITIALsearch, dim), maxpoints, points, numpoints, &simplex);
    k= qh_setsize(simplex);
    FOREACHpoint_i_(maxpoints) {
      if (point_i & 0x1) {     /* first pick up max. coord. points */
        if (!qh_setin(simplex, point) && !qh_setin(tested, point)){
          qh_detsimplex(point, simplex, k, &nearzero);
          if (nearzero)
            qh_setappend(&tested, point);
          else {
            qh_setappend(&simplex, point);
            if (++k == dim)  /* use search for last point */
              break;
          }
        }
      }
    }
    while (k != dim && (point= (pointT*)qh_setdellast(maxpoints))) {
      if (!qh_setin(simplex, point) && !qh_setin(tested, point)){
        qh_detsimplex(point, simplex, k, &nearzero);
        if (nearzero)
          qh_setappend(&tested, point);
        else {
          qh_setappend(&simplex, point);
          k++;
        }
      }
    }
    idx= 0;
    while (k != dim && (point= qh_point(idx++))) {
      if (!qh_setin(simplex, point) && !qh_setin(tested, point)){
        qh_detsimplex(point, simplex, k, &nearzero);
        if (!nearzero){
          qh_setappend(&simplex, point);
          k++;
        }
      }
    }
    qh_settempfree(&tested);
    qh_maxsimplex(dim, maxpoints, points, numpoints, &simplex);
  }else
    qh_maxsimplex(dim, maxpoints, points, numpoints, &simplex);
  FOREACHpoint_(simplex)
    qh_setaddnth(&vertices, 0, qh_newvertex(point)); /* descending order */
  qh_settempfree(&simplex);
  return vertices;
} /* initialvertices */
References boolT, False, floor(), fmin_, FOREACHpoint_, FOREACHpoint_i_, int, NULL, pointT, qh, qh_detsimplex(), qh_INITIALmax, qh_INITIALsearch, qh_maxsimplex(), qh_newvertex(), qh_point(), qh_setaddnth(), qh_setappend(), qh_setdellast(), qh_setin(), qh_setsize(), qh_settemp(), qh_settempfree(), realT, SETfirst_, and SETsecond_.
Referenced by qh_initbuild().
qh_isvertex()
vertexT * qh_isvertex (pointT * point, setT * vertices)
{
  vertexT *vertex, **vertexp;
  FOREACHvertex_(vertices) {
    if (vertex->point == point)
      return vertex;
  }
  return NULL;
} /* isvertex */
References FOREACHvertex_, and NULL.
qh_makenew_nonsimplicial()
facetT * qh_makenew_nonsimplicial (facetT * visible, vertexT * apex, int * numnew)
{
  void **freelistp; /* used if !qh_NOmem by qh_memfree_() */
  ridgeT *ridge, **ridgep;
  facetT *neighbor, *newfacet= NULL, *samecycle;
  setT *vertices;
  boolT toporient;
  int ridgeid;
  FOREACHridge_(visible->ridges) {
    ridgeid= ridge->id;
    neighbor= otherfacet_(ridge, visible);
    if (neighbor->visible) {
      if (!qh ONLYgood) {
        if (neighbor->visitid == qh visit_id) {
          qh_setfree(&(ridge->vertices));  /* delete on 2nd visit */
          qh_memfree_(ridge, (int)sizeof(ridgeT), freelistp);
        }
      }
    }else {  /* neighbor is an horizon facet */
      toporient= (ridge->top == visible);
      vertices= qh_setnew(qh hull_dim); /* makes sure this is quick */
      qh_setappend(&vertices, apex);
      qh_setappend_set(&vertices, ridge->vertices);
      newfacet= qh_makenewfacet(vertices, toporient, neighbor);
      (*numnew)++;
      if (neighbor->coplanar) {
        newfacet->mergehorizon= True;
        if (!neighbor->seen) {
          newfacet->f.samecycle= newfacet;
          neighbor->f.newcycle= newfacet;
        }else {
          samecycle= neighbor->f.newcycle;
          newfacet->f.samecycle= samecycle->f.samecycle;
          samecycle->f.samecycle= newfacet;
        }
      }
      if (qh ONLYgood) {
        if (!neighbor->simplicial)
          qh_setappend(&(newfacet->ridges), ridge);
      }else {  /* qh_attachnewfacets */
        if (neighbor->seen) {
          if (neighbor->simplicial) {
            qh_fprintf(qh ferr, 6105, "qhull internal error (qh_makenew_nonsimplicial): simplicial f%d sharing two ridges with f%d\n",
                   neighbor->id, visible->id);
            qh_errexit2(qh_ERRqhull, neighbor, visible);
          }
          qh_setappend(&(neighbor->neighbors), newfacet);
        }else
          qh_setreplace(neighbor->neighbors, visible, newfacet);
        if (neighbor->simplicial) {
          qh_setdel(neighbor->ridges, ridge);
          qh_setfree(&(ridge->vertices));
          qh_memfree(ridge, (int)sizeof(ridgeT));
        }else {
          qh_setappend(&(newfacet->ridges), ridge);
          if (toporient)
            ridge->top= newfacet;
          else
            ridge->bottom= newfacet;
        }
      trace4((qh ferr, 4048, "qh_makenew_nonsimplicial: created facet f%d from v%d and r%d of horizon f%d\n",
            newfacet->id, apex->id, ridgeid, neighbor->id));
      }
    }
    neighbor->seen= True;
  } /* for each ridge */
  if (!qh ONLYgood)
    SETfirst_(visible->ridges)= NULL;
  return newfacet;
} /* makenew_nonsimplicial */
References boolT, ridgeT::bottom, facetT::coplanar, facetT::f, FOREACHridge_, facetT::id, ridgeT::id, vertexT::id, facetT::mergehorizon, facetT::neighbors, NULL, otherfacet_, qh, qh_errexit2(), qh_ERRqhull, qh_fprintf(), qh_makenewfacet(), qh_memfree(), qh_memfree_, qh_setappend(), qh_setappend_set(), qh_setdel(), qh_setfree(), qh_setnew(), qh_setreplace(), facetT::ridges, facetT::seen, SETfirst_, facetT::simplicial, ridgeT::top, trace4, True, ridgeT::vertices, facetT::visible, and facetT::visitid.
Referenced by qh_makenewfacets(), qh_makenewfacets(), qh_triangulate_facet(), and qh_triangulate_facet().
qh_makenew_simplicial()
facetT * qh_makenew_simplicial (facetT * visible, vertexT * apex, int * numnew)
{
  facetT *neighbor, **neighborp, *newfacet= NULL;
  setT *vertices;
  boolT flip, toporient;
  int horizonskip= 0, visibleskip= 0;
  FOREACHneighbor_(visible) {
    if (!neighbor->seen && !neighbor->visible) {
      vertices= qh_facetintersect(neighbor,visible, &horizonskip, &visibleskip, 1);
      SETfirst_(vertices)= apex;
      flip= ((horizonskip & 0x1) ^ (visibleskip & 0x1));
      if (neighbor->toporient)
        toporient= horizonskip & 0x1;
      else
        toporient= (horizonskip & 0x1) ^ 0x1;
      newfacet= qh_makenewfacet(vertices, toporient, neighbor);
      (*numnew)++;
      if (neighbor->coplanar && (qh PREmerge || qh MERGEexact)) {
#ifndef qh_NOmerge
        newfacet->f.samecycle= newfacet;
        newfacet->mergehorizon= True;
#endif
      }
      if (!qh ONLYgood)
        SETelem_(neighbor->neighbors, horizonskip)= newfacet;
      trace4((qh ferr, 4049, "qh_makenew_simplicial: create facet f%d top %d from v%d and horizon f%d skip %d top %d and visible f%d skip %d, flip? %d\n",
            newfacet->id, toporient, apex->id, neighbor->id, horizonskip,
              neighbor->toporient, visible->id, visibleskip, flip));
    }
  }
  return newfacet;
} /* makenew_simplicial */
References boolT, facetT::coplanar, facetT::f, FOREACHneighbor_, facetT::id, vertexT::id, facetT::mergehorizon, facetT::neighbors, NULL, qh, qh_facetintersect(), qh_makenewfacet(), facetT::seen, SETelem_, SETfirst_, facetT::toporient, trace4, True, and facetT::visible.
Referenced by qh_makenewfacets(), and qh_makenewfacets().
qh_makenewfacet()
facetT * qh_makenewfacet (setT * vertices, boolT toporient, facetT * facet)
{
  facetT *newfacet;
  vertexT *vertex, **vertexp;
  FOREACHvertex_(vertices) {
    if (!vertex->newlist) {
      qh_removevertex(vertex);
      qh_appendvertex(vertex);
    }
  }
  newfacet= qh_newfacet();
  newfacet->vertices= vertices;
  newfacet->toporient= (unsigned char)toporient;
  if (horizon)
    qh_setappend(&(newfacet->neighbors), horizon);
  qh_appendfacet(newfacet);
  return(newfacet);
} /* makenewfacet */
References FOREACHvertex_, facetT::neighbors, qh_appendfacet(), qh_appendvertex(), qh_newfacet(), qh_removevertex(), qh_setappend(), facetT::toporient, and facetT::vertices.
Referenced by qh_makenew_nonsimplicial(), and qh_makenew_simplicial().
qh_makenewfacets()
vertexT * qh_makenewfacets (pointT * point)
{
  facetT *visible, *newfacet= NULL, *newfacet2= NULL, *neighbor, **neighborp;
  vertexT *apex;
  int numnew=0;
  qh newfacet_list= qh facet_tail;
  qh newvertex_list= qh vertex_tail;
  apex= qh_newvertex(point);
  qh_appendvertex(apex);
  qh visit_id++;
  if (!qh ONLYgood)
    qh NEWfacets= True;
  FORALLvisible_facets {
    FOREACHneighbor_(visible)
      neighbor->seen= False;
    if (visible->ridges) {
      visible->visitid= qh visit_id;
      newfacet2= qh_makenew_nonsimplicial(visible, apex, &numnew);
    }
    if (visible->simplicial)
      newfacet= qh_makenew_simplicial(visible, apex, &numnew);
    if (!qh ONLYgood) {
      if (newfacet2)  /* newfacet is null if all ridges defined */
        newfacet= newfacet2;
      if (newfacet)
        visible->f.replace= newfacet;
      else
        zinc_(Zinsidevisible);
      SETfirst_(visible->neighbors)= NULL;
    }
  }
  trace1((qh ferr, 1032, "qh_makenewfacets: created %d new facets from point p%d to horizon\n",
          numnew, qh_pointid(point)));
  if (qh IStracing >= 4)
    qh_printfacetlist(qh newfacet_list, NULL, qh_ALL);
  return apex;
} /* makenewfacets */
References facetT::f, False, FORALLvisible_facets, FOREACHneighbor_, facetT::neighbors, NULL, qh, qh_ALL, qh_appendvertex(), qh_makenew_nonsimplicial(), qh_makenew_simplicial(), qh_newvertex(), qh_pointid(), qh_printfacetlist(), facetT::ridges, SETfirst_, facetT::simplicial, trace1, True, facetT::visitid, and zinc_.
Referenced by qh_addpoint(), and qh_addpoint().
qh_makenewplanes()
void qh_makenewplanes (void)
{
  facetT *newfacet;
  FORALLnew_facets {
    if (!newfacet->mergehorizon)
      qh_setfacetplane(newfacet);
  }
  if (qh JOGGLEmax < REALmax/2)
    minimize_(qh min_vertex, -wwval_(Wnewvertexmax));
} /* makenewplanes */
References FORALLnew_facets, facetT::mergehorizon, minimize_, qh, qh_setfacetplane(), REALmax, Wnewvertexmax, and wwval_.
Referenced by qh_addpoint(), and qh_addpoint().
qh_matchduplicates()
void qh_matchduplicates (facetT * atfacet, int atskip, int hashsize, int * hashcount)
{
  boolT same, ismatch;
  int hash, scan;
  facetT *facet, *newfacet, *maxmatch= NULL, *maxmatch2= NULL, *nextfacet;
  int skip, newskip, nextskip= 0, maxskip= 0, maxskip2= 0, makematch;
  realT maxdist= -REALmax, mindist, dist2, low, high;
  hash= qh_gethash(hashsize, atfacet->vertices, qh hull_dim, 1,
                     SETelem_(atfacet->vertices, atskip));
  trace2((qh ferr, 2046, "qh_matchduplicates: find duplicate matches for f%d skip %d hash %d hashcount %d\n",
          atfacet->id, atskip, hash, *hashcount));
  for (makematch= 0; makematch < 2; makematch++) {
    qh visit_id++;
    for (newfacet= atfacet, newskip= atskip; newfacet; newfacet= nextfacet, newskip= nextskip) {
      zinc_(Zhashlookup);
      nextfacet= NULL;
      newfacet->visitid= qh visit_id;
      for (scan= hash; (facet= SETelemt_(qh hash_table, scan, facetT));
           scan= (++scan >= hashsize ? 0 : scan)) {
        if (!facet->dupridge || facet->visitid == qh visit_id)
          continue;
        zinc_(Zhashtests);
        if (qh_matchvertices(1, newfacet->vertices, newskip, facet->vertices, &skip, &same)) {
          ismatch= (same == (boolT)(newfacet->toporient ^ facet->toporient));
          if (SETelemt_(facet->neighbors, skip, facetT) != qh_DUPLICATEridge) {
            if (!makematch) {
              qh_fprintf(qh ferr, 6155, "qhull internal error (qh_matchduplicates): missing dupridge at f%d skip %d for new f%d skip %d hash %d\n",
                     facet->id, skip, newfacet->id, newskip, hash);
              qh_errexit2(qh_ERRqhull, facet, newfacet);
            }
          }else if (ismatch && makematch) {
            if (SETelemt_(newfacet->neighbors, newskip, facetT) == qh_DUPLICATEridge) {
              SETelem_(facet->neighbors, skip)= newfacet;
              if (newfacet->tricoplanar)
                SETelem_(newfacet->neighbors, newskip)= facet;
              else
                SETelem_(newfacet->neighbors, newskip)= qh_MERGEridge;
              *hashcount -= 2; /* removed two unmatched facets */
              trace4((qh ferr, 4059, "qh_matchduplicates: duplicate f%d skip %d matched with new f%d skip %d merge\n",
                    facet->id, skip, newfacet->id, newskip));
            }
          }else if (ismatch) {
            mindist= qh_getdistance(facet, newfacet, &low, &high);
            dist2= qh_getdistance(newfacet, facet, &low, &high);
            minimize_(mindist, dist2);
            if (mindist > maxdist) {
              maxdist= mindist;
              maxmatch= facet;
              maxskip= skip;
              maxmatch2= newfacet;
              maxskip2= newskip;
            }
            trace3((qh ferr, 3018, "qh_matchduplicates: duplicate f%d skip %d new f%d skip %d at dist %2.2g, max is now f%d f%d\n",
                    facet->id, skip, newfacet->id, newskip, mindist,
                    maxmatch->id, maxmatch2->id));
          }else { /* !ismatch */
            nextfacet= facet;
            nextskip= skip;
          }
        }
        if (makematch && !facet
        && SETelemt_(facet->neighbors, skip, facetT) == qh_DUPLICATEridge) {
          qh_fprintf(qh ferr, 6156, "qhull internal error (qh_matchduplicates): no MERGEridge match for duplicate f%d skip %d at hash %d\n",
                     newfacet->id, newskip, hash);
          qh_errexit(qh_ERRqhull, newfacet, NULL);
        }
      }
    } /* end of for each new facet at hash */
    if (!makematch) {
      if (!maxmatch) {
        qh_fprintf(qh ferr, 6157, "qhull internal error (qh_matchduplicates): no maximum match at duplicate f%d skip %d at hash %d\n",
                     atfacet->id, atskip, hash);
        qh_errexit(qh_ERRqhull, atfacet, NULL);
      }
      SETelem_(maxmatch->neighbors, maxskip)= maxmatch2; /* maxmatch!=0 by QH6157 */
      SETelem_(maxmatch2->neighbors, maxskip2)= maxmatch;
      *hashcount -= 2; /* removed two unmatched facets */
      zzinc_(Zmultiridge);
      trace0((qh ferr, 25, "qh_matchduplicates: duplicate f%d skip %d matched with new f%d skip %d keep\n",
              maxmatch->id, maxskip, maxmatch2->id, maxskip2));
      qh_precision("ridge with multiple neighbors");
      if (qh IStracing >= 4)
        qh_errprint("DUPLICATED/MATCH", maxmatch, maxmatch2, NULL, NULL);
    }
  }
} /* matchduplicates */
References boolT, facetT::dupridge, hash(), facetT::id, minimize_, facetT::neighbors, NULL, qh, qh_DUPLICATEridge, qh_errexit(), qh_errexit2(), qh_errprint(), qh_ERRqhull, qh_fprintf(), qh_getdistance(), qh_gethash(), qh_matchvertices(), qh_MERGEridge, qh_precision(), REALmax, realT, SETelem_, SETelemt_, facetT::toporient, trace0, trace2, trace3, trace4, facetT::tricoplanar, facetT::vertices, facetT::visitid, zinc_, Zmultiridge, and zzinc_.
Referenced by qh_matchnewfacets(), and qh_matchnewfacets().
qh_matchneighbor()
void qh_matchneighbor (facetT * newfacet, int newskip, int hashsize, int * hashcount)
{
  boolT newfound= False;   /* True, if new facet is already in hash chain */
  boolT same, ismatch;
  int hash, scan;
  facetT *facet, *matchfacet;
  int skip, matchskip;
  hash= qh_gethash(hashsize, newfacet->vertices, qh hull_dim, 1,
                     SETelem_(newfacet->vertices, newskip));
  trace4((qh ferr, 4050, "qh_matchneighbor: newfacet f%d skip %d hash %d hashcount %d\n",
          newfacet->id, newskip, hash, *hashcount));
  zinc_(Zhashlookup);
  for (scan= hash; (facet= SETelemt_(qh hash_table, scan, facetT));
       scan= (++scan >= hashsize ? 0 : scan)) {
    if (facet == newfacet) {
      newfound= True;
      continue;
    }
    zinc_(Zhashtests);
    if (qh_matchvertices(1, newfacet->vertices, newskip, facet->vertices, &skip, &same)) {
      if (SETelem_(newfacet->vertices, newskip) ==
          SETelem_(facet->vertices, skip)) {
        qh_precision("two facets with the same vertices");
        qh_fprintf(qh ferr, 6106, "qhull precision error: Vertex sets are the same for f%d and f%d.  Can not force output.\n",
          facet->id, newfacet->id);
        qh_errexit2(qh_ERRprec, facet, newfacet);
      }
      ismatch= (same == (boolT)((newfacet->toporient ^ facet->toporient)));
      matchfacet= SETelemt_(facet->neighbors, skip, facetT);
      if (ismatch && !matchfacet) {
        SETelem_(facet->neighbors, skip)= newfacet;
        SETelem_(newfacet->neighbors, newskip)= facet;
        (*hashcount)--;
        trace4((qh ferr, 4051, "qh_matchneighbor: f%d skip %d matched with new f%d skip %d\n",
           facet->id, skip, newfacet->id, newskip));
        return;
      }
      if (!qh PREmerge && !qh MERGEexact) {
        qh_precision("a ridge with more than two neighbors");
        qh_fprintf(qh ferr, 6107, "qhull precision error: facets f%d, f%d and f%d meet at a ridge with more than 2 neighbors.  Can not continue.\n",
                 facet->id, newfacet->id, getid_(matchfacet));
        qh_errexit2(qh_ERRprec, facet, newfacet);
      }
      SETelem_(newfacet->neighbors, newskip)= qh_DUPLICATEridge;
      newfacet->dupridge= True;
      if (!newfacet->normal)
        qh_setfacetplane(newfacet);
      qh_addhash(newfacet, qh hash_table, hashsize, hash);
      (*hashcount)++;
      if (!facet->normal)
        qh_setfacetplane(facet);
      if (matchfacet != qh_DUPLICATEridge) {
        SETelem_(facet->neighbors, skip)= qh_DUPLICATEridge;
        facet->dupridge= True;
        if (!facet->normal)
          qh_setfacetplane(facet);
        if (matchfacet) {
          matchskip= qh_setindex(matchfacet->neighbors, facet);
          if (matchskip<0) {
              qh_fprintf(qh ferr, 6260, "qhull internal error (qh_matchneighbor): matchfacet f%d is in f%d neighbors but not vice versa.  Can not continue.\n",
                  matchfacet->id, facet->id);
              qh_errexit2(qh_ERRqhull, matchfacet, facet);
          }
          SETelem_(matchfacet->neighbors, matchskip)= qh_DUPLICATEridge; /* matchskip>=0 by QH6260 */
          matchfacet->dupridge= True;
          if (!matchfacet->normal)
            qh_setfacetplane(matchfacet);
          qh_addhash(matchfacet, qh hash_table, hashsize, hash);
          *hashcount += 2;
        }
      }
      trace4((qh ferr, 4052, "qh_matchneighbor: new f%d skip %d duplicates ridge for f%d skip %d matching f%d ismatch %d at hash %d\n",
           newfacet->id, newskip, facet->id, skip,
           (matchfacet == qh_DUPLICATEridge ? -2 : getid_(matchfacet)),
           ismatch, hash));
      return; /* end of duplicate ridge */
    }
  }
  if (!newfound)
    SETelem_(qh hash_table, scan)= newfacet;  /* same as qh_addhash */
  (*hashcount)++;
  trace4((qh ferr, 4053, "qh_matchneighbor: no match for f%d skip %d at hash %d\n",
           newfacet->id, newskip, hash));
} /* matchneighbor */
References boolT, facetT::dupridge, False, getid_, hash(), facetT::id, facetT::neighbors, facetT::normal, qh, qh_addhash(), qh_DUPLICATEridge, qh_errexit2(), qh_ERRprec, qh_ERRqhull, qh_fprintf(), qh_gethash(), qh_matchvertices(), qh_precision(), qh_setfacetplane(), qh_setindex(), SETelem_, SETelemt_, facetT::toporient, trace4, True, facetT::vertices, and zinc_.
Referenced by qh_matchnewfacets().
qh_matchnewfacets()
void qh_matchnewfacets (void)
{
  int numnew=0, hashcount=0, newskip;
  facetT *newfacet, *neighbor;
  int dim= qh hull_dim, hashsize, neighbor_i, neighbor_n;
  setT *neighbors;
#ifndef qh_NOtrace
  int facet_i, facet_n, numfree= 0;
  facetT *facet;
#endif
  trace1((qh ferr, 1019, "qh_matchnewfacets: match neighbors for new facets.\n"));
  FORALLnew_facets {
    numnew++;
    {  /* inline qh_setzero(newfacet->neighbors, 1, qh hull_dim); */
      neighbors= newfacet->neighbors;
      neighbors->e[neighbors->maxsize].i= dim+1; /*may be overwritten*/
      memset((char *)SETelemaddr_(neighbors, 1, void), 0, dim * SETelemsize);
    }
  }
  qh_newhashtable(numnew*(qh hull_dim-1)); /* twice what is normally needed,
                                     but every ridge could be DUPLICATEridge */
  hashsize= qh_setsize(qh hash_table);
  FORALLnew_facets {
    for (newskip=1; newskip<qh hull_dim; newskip++) /* furthest/horizon already matched */
      /* hashsize>0 because hull_dim>1 and numnew>0 */
      qh_matchneighbor(newfacet, newskip, hashsize, &hashcount);
#if 0   /* use the following to trap hashcount errors */
    {
      int count= 0, k;
      facetT *facet, *neighbor;
      count= 0;
      FORALLfacet_(qh newfacet_list) {  /* newfacet already in use */
        for (k=1; k < qh hull_dim; k++) {
          neighbor= SETelemt_(facet->neighbors, k, facetT);
          if (!neighbor || neighbor == qh_DUPLICATEridge)
            count++;
        }
        if (facet == newfacet)
          break;
      }
      if (count != hashcount) {
        qh_fprintf(qh ferr, 8088, "qh_matchnewfacets: after adding facet %d, hashcount %d != count %d\n",
                 newfacet->id, hashcount, count);
        qh_errexit(qh_ERRqhull, newfacet, NULL);
      }
    }
#endif  /* end of trap code */
  }
  if (hashcount) {
    FORALLnew_facets {
      if (newfacet->dupridge) {
        FOREACHneighbor_i_(newfacet) {
          if (neighbor == qh_DUPLICATEridge) {
            qh_matchduplicates(newfacet, neighbor_i, hashsize, &hashcount);
                    /* this may report MERGEfacet */
          }
        }
      }
    }
  }
  if (hashcount) {
    qh_fprintf(qh ferr, 6108, "qhull internal error (qh_matchnewfacets): %d neighbors did not match up\n",
        hashcount);
    qh_printhashtable(qh ferr);
    qh_errexit(qh_ERRqhull, NULL, NULL);
  }
#ifndef qh_NOtrace
  if (qh IStracing >= 2) {
    FOREACHfacet_i_(qh hash_table) {
      if (!facet)
        numfree++;
    }
    qh_fprintf(qh ferr, 8089, "qh_matchnewfacets: %d new facets, %d unused hash entries .  hashsize %d\n",
             numnew, numfree, qh_setsize(qh hash_table));
  }
#endif /* !qh_NOtrace */
  qh_setfree(&qh hash_table);
  if (qh PREmerge || qh MERGEexact) {
    if (qh IStracing >= 4)
      qh_printfacetlist(qh newfacet_list, NULL, qh_ALL);
    FORALLnew_facets {
      if (newfacet->normal)
        qh_checkflipped(newfacet, NULL, qh_ALL);
    }
  }else if (qh FORCEoutput)
    qh_checkflipped_all(qh newfacet_list);  /* prints warnings for flipped */
} /* matchnewfacets */
References count, facetT::dupridge, setT::e, FORALLfacet_, FORALLnew_facets, FOREACHfacet_i_, FOREACHneighbor_i_, setelemT::i, facetT::id, setT::maxsize, memset, facetT::neighbors, facetT::normal, NULL, qh, qh_ALL, qh_checkflipped(), qh_checkflipped_all(), qh_DUPLICATEridge, qh_errexit(), qh_ERRqhull, qh_fprintf(), qh_matchduplicates(), qh_matchneighbor(), qh_newhashtable(), qh_printfacetlist(), qh_printhashtable(), qh_setfree(), qh_setsize(), SETelemaddr_, SETelemsize, SETelemt_, and trace1.
Referenced by qh_addpoint(), qh_addpoint(), qh_triangulate_facet(), and qh_triangulate_facet().
qh_matchvertices()
boolT qh_matchvertices (int firstindex, setT * verticesA, int skipA, setT * verticesB, int * skipB, boolT * same)
{
  vertexT **elemAp, **elemBp, **skipBp=NULL, **skipAp;
  elemAp= SETelemaddr_(verticesA, firstindex, vertexT);
  elemBp= SETelemaddr_(verticesB, firstindex, vertexT);
  skipAp= SETelemaddr_(verticesA, skipA, vertexT);
  do if (elemAp != skipAp) {
    while (*elemAp != *elemBp++) {
      if (skipBp)
        return False;
      skipBp= elemBp;  /* one extra like FOREACH */
    }
  }while (*(++elemAp));
  if (!skipBp)
    skipBp= ++elemBp;
  *skipB= SETindex_(verticesB, skipB); /* i.e., skipBp - verticesB */
  *same= !((skipA & 0x1) ^ (*skipB & 0x1)); /* result is 0 or 1 */
  trace4((qh ferr, 4054, "qh_matchvertices: matched by skip %d(v%d) and skip %d(v%d) same? %d\n",
          skipA, (*skipAp)->id, *skipB, (*(skipBp-1))->id, *same));
  return(True);
} /* matchvertices */
References False, NULL, qh, SETelemaddr_, SETindex_, trace4, and True.
Referenced by qh_matchduplicates(), qh_matchduplicates(), and qh_matchneighbor().
qh_nearcoplanar()
void qh_nearcoplanar (void)
{
  facetT *facet;
  pointT *point, **pointp;
  int numpart;
  realT dist, innerplane;
  if (!qh KEEPcoplanar && !qh KEEPinside) {
    FORALLfacets {
      if (facet->coplanarset)
        qh_setfree( &facet->coplanarset);
    }
  }else if (!qh KEEPcoplanar || !qh KEEPinside) {
    qh_outerinner(NULL, NULL, &innerplane);
    if (qh JOGGLEmax < REALmax/2)
      innerplane -= qh JOGGLEmax * sqrt((realT)qh hull_dim);
    numpart= 0;
    FORALLfacets {
      if (facet->coplanarset) {
        FOREACHpoint_(facet->coplanarset) {
          numpart++;
          qh_distplane(point, facet, &dist);
          if (dist < innerplane) {
            if (!qh KEEPinside)
              SETref_(point)= NULL;
          }else if (!qh KEEPcoplanar)
            SETref_(point)= NULL;
        }
        qh_setcompact(facet->coplanarset);
      }
    }
    zzadd_(Zcheckpart, numpart);
  }
} /* nearcoplanar */
References facetT::coplanarset, FORALLfacets, FOREACHpoint_, NULL, pointT, qh, qh_distplane(), qh_outerinner(), qh_setcompact(), qh_setfree(), REALmax, realT, SETref_, sqrt(), Zcheckpart, and zzadd_.
Referenced by addDelaunay(), addDelaunay(), adddiamond(), adddiamond(), addhalf(), addhalf(), qh_check_maxout(), qh_check_maxout(), qh_qhull(), and qh_qhull().
qh_nearvertex()
vertexT * qh_nearvertex (facetT * facet, pointT * point, realT * bestdistp)
{
  realT bestdist= REALmax, dist;
  vertexT *bestvertex= NULL, *vertex, **vertexp, *apex;
  coordT *center;
  facetT *neighbor, **neighborp;
  setT *vertices;
  int dim= qh hull_dim;
  if (qh DELAUNAY)
    dim--;
  if (facet->tricoplanar) {
    if (!qh VERTEXneighbors || !facet->center) {
      qh_fprintf(qh ferr, 6158, "qhull internal error (qh_nearvertex): qh.VERTEXneighbors and facet->center required for tricoplanar facets\n");
      qh_errexit(qh_ERRqhull, facet, NULL);
    }
    vertices= qh_settemp(qh TEMPsize);
    apex= SETfirstt_(facet->vertices, vertexT);
    center= facet->center;
    FOREACHneighbor_(apex) {
      if (neighbor->center == center) {
        FOREACHvertex_(neighbor->vertices)
          qh_setappend(&vertices, vertex);
      }
    }
  }else
    vertices= facet->vertices;
  FOREACHvertex_(vertices) {
    dist= qh_pointdist(vertex->point, point, -dim);
    if (dist < bestdist) {
      bestdist= dist;
      bestvertex= vertex;
    }
  }
  if (facet->tricoplanar)
    qh_settempfree(&vertices);
  *bestdistp= sqrt(bestdist);
  if (!bestvertex) {
      qh_fprintf(qh ferr, 6261, "qhull internal error (qh_nearvertex): did not find bestvertex for f%d p%d\n", facet->id, qh_pointid(point));
      qh_errexit(qh_ERRqhull, facet, NULL);
  }
  trace3((qh ferr, 3019, "qh_nearvertex: v%d dist %2.2g for f%d p%d\n",
        bestvertex->id, *bestdistp, facet->id, qh_pointid(point))); /* bestvertex!=0 by QH2161 */
  return bestvertex;
} /* nearvertex */
Referenced by qh_findbestlower().
qh_newfacet()
facetT * qh_newfacet (void)
{
  facetT *facet;
  void **freelistp; /* used if !qh_NOmem by qh_memalloc_() */
  qh_memalloc_((int)sizeof(facetT), freelistp, facet, facetT);
  memset((char *)facet, (size_t)0, sizeof(facetT));
  if (qh facet_id == qh tracefacet_id)
    qh tracefacet= facet;
  facet->id= qh facet_id++;
  facet->neighbors= qh_setnew(qh hull_dim);
#if !qh_COMPUTEfurthest
  facet->furthestdist= 0.0;
#endif
#if qh_MAXoutside
  if (qh FORCEoutput && qh APPROXhull)
    facet->maxoutside= qh MINoutside;
  else
    facet->maxoutside= qh DISTround;
#endif
  facet->simplicial= True;
  facet->good= True;
  facet->newfacet= True;
  trace4((qh ferr, 4055, "qh_newfacet: created facet f%d\n", facet->id));
  return(facet);
} /* newfacet */
References facetT::furthestdist, facetT::good, facetT::id, memset, facetT::neighbors, facetT::newfacet, qh, qh_memalloc_, qh_setnew(), facetT::simplicial, trace4, and True.
Referenced by qh_createsimplex(), qh_createsimplex(), qh_makenewfacet(), and qh_makenewfacet().
qh_newhashtable()
int qh_newhashtable (int newsize)
{
  int size;
  size= ((newsize+1)*qh_HASHfactor) | 0x1;  /* odd number */
  while (True) {
    if (newsize<0 || size<0) {
        qh_fprintf(qhmem.ferr, 6236, "qhull error (qh_newhashtable): negative request (%d) or size (%d).  Did int overflow due to high-D?\n", newsize, size); /* WARN64 */
        qh_errexit(qhmem_ERRmem, NULL, NULL);
    }
    if ((size%3) && (size%5))
      break;
    size += 2;
    /* loop terminates because there is an infinite number of primes */
  }
  qh hash_table= qh_setnew(size);
  qh_setzero(qh hash_table, 0, size);
  return size;
} /* newhashtable */
References qhmemT::ferr, NULL, qh, qh_errexit(), qh_fprintf(), qh_HASHfactor, qh_setnew(), qh_setzero(), qhmem, qhmem_ERRmem, size, and True.
Referenced by qh_find_newvertex(), qh_find_newvertex(), qh_matchnewfacets(), and qh_matchnewfacets().
qh_newridge()
ridgeT * qh_newridge (void)
{
  ridgeT *ridge;
  void **freelistp;   /* used if !qh_NOmem by qh_memalloc_() */
  qh_memalloc_((int)sizeof(ridgeT), freelistp, ridge, ridgeT);
  memset((char *)ridge, (size_t)0, sizeof(ridgeT));
  zinc_(Ztotridges);
  if (qh ridge_id == UINT_MAX) {
    qh_fprintf(qh ferr, 7074, "\
qhull warning: more than 2^32 ridges.  Qhull results are OK.  Since the ridge ID wraps around to 0, two ridges may have the same identifier.\n");
  }
  ridge->id= qh ridge_id++;
  trace4((qh ferr, 4056, "qh_newridge: created ridge r%d\n", ridge->id));
  return(ridge);
} /* newridge */
References ridgeT::id, memset, qh, qh_fprintf(), qh_memalloc_, trace4, and zinc_.
Referenced by qh_makeridges(), qh_makeridges(), qh_mergecycle_ridges(), and qh_mergecycle_ridges().
qh_newvertex()
vertexT * qh_newvertex (pointT * point)
{
  vertexT *vertex;
  zinc_(Ztotvertices);
  vertex= (vertexT *)qh_memalloc((int)sizeof(vertexT));
  memset((char *) vertex, (size_t)0, sizeof(vertexT));
  if (qh vertex_id == UINT_MAX) {
    qh_memfree(vertex, (int)sizeof(vertexT));
    qh_fprintf(qh ferr, 6159, "qhull error: more than 2^32 vertices.  vertexT.id field overflows.  Vertices would not be sorted correctly.\n");
    qh_errexit(qh_ERRqhull, NULL, NULL);
  }
  if (qh vertex_id == qh tracevertex_id)
    qh tracevertex= vertex;
  vertex->id= qh vertex_id++;
  vertex->point= point;
  trace4((qh ferr, 4060, "qh_newvertex: vertex p%d(v%d) created\n", qh_pointid(vertex->point),
          vertex->id));
  return(vertex);
} /* newvertex */
References memset, NULL, qh, qh_errexit(), qh_ERRqhull, qh_fprintf(), qh_memalloc(), qh_memfree(), qh_pointid(), trace4, and zinc_.
Referenced by qh_createsimplex(), qh_initialvertices(), and qh_makenewfacets().
qh_nextridge3d()
ridgeT * qh_nextridge3d (ridgeT * atridge, facetT * facet, vertexT ** vertexp)
{
  vertexT *atvertex, *vertex, *othervertex;
  ridgeT *ridge, **ridgep;
  if ((atridge->top == facet) ^ qh_ORIENTclock)
    atvertex= SETsecondt_(atridge->vertices, vertexT);
  else
    atvertex= SETfirstt_(atridge->vertices, vertexT);
  FOREACHridge_(facet->ridges) {
    if (ridge == atridge)
      continue;
    if ((ridge->top == facet) ^ qh_ORIENTclock) {
      othervertex= SETsecondt_(ridge->vertices, vertexT);
      vertex= SETfirstt_(ridge->vertices, vertexT);
    }else {
      vertex= SETsecondt_(ridge->vertices, vertexT);
      othervertex= SETfirstt_(ridge->vertices, vertexT);
    }
    if (vertex == atvertex) {
      if (vertexp)
        *vertexp= othervertex;
      return ridge;
    }
  }
  return NULL;
} /* nextridge3d */
References FOREACHridge_, NULL, qh_ORIENTclock, facetT::ridges, SETfirstt_, SETsecondt_, ridgeT::top, and ridgeT::vertices.
Referenced by orgQhull::QhullRidge::hasNextRidge3d(), orgQhull::QhullRidge::nextRidge3d(), qh_printfacetridges(), and qh_printfacetridges().
qh_outcoplanar()
void qh_outcoplanar (void)
{
  pointT *point, **pointp;
  facetT *facet;
  realT dist;
  trace1((qh ferr, 1033, "qh_outcoplanar: move outsideset to coplanarset for qh NARROWhull\n"));
  FORALLfacets {
    FOREACHpoint_(facet->outsideset) {
      qh num_outside--;
      if (qh KEEPcoplanar || qh KEEPnearinside) {
        qh_distplane(point, facet, &dist);
        zinc_(Zpartition);
        qh_partitioncoplanar(point, facet, &dist);
      }
    }
    qh_setfree(&facet->outsideset);
  }
} /* outcoplanar */
References FORALLfacets, FOREACHpoint_, facetT::outsideset, pointT, qh, qh_distplane(), qh_partitioncoplanar(), qh_setfree(), realT, trace1, zinc_, and Zpartition.
Referenced by qh_buildhull(), and qh_buildhull().
qh_point()
pointT * qh_point (int id)
{
  if (id < 0)
    return NULL;
  if (id < qh num_points)
    return qh first_point + id * qh hull_dim;
  id -= qh num_points;
  if (id < qh_setsize(qh other_points))
    return SETelemt_(qh other_points, id, pointT);
  return NULL;
} /* point */
Referenced by qh_check_bestdist(), qh_check_maxout(), qh_initbuild(), and qh_initialvertices().
qh_point_add()
void qh_point_add (setT * set, pointT * point, void * elem)
{
  int id, size;
  SETreturnsize_(set, size);
  if ((id= qh_pointid(point)) < 0)
    qh_fprintf(qh ferr, 7067, "qhull internal warning (point_add): unknown point %p id %d\n",
      point, id);
  else if (id >= size) {
    qh_fprintf(qh ferr, 6160, "qhull internal errror(point_add): point p%d is out of bounds(%d)\n",
             id, size);
    qh_errexit(qh_ERRqhull, NULL, NULL);
  }else
    SETelem_(set, id)= elem;
} /* point_add */
References NULL, qh, qh_errexit(), qh_ERRqhull, qh_fprintf(), qh_pointid(), SETelem_, SETreturnsize_, and size.
Referenced by qh_pointfacet(), qh_pointvertex(), qh_printvneighbors(), and qh_printvneighbors().
qh_pointfacet()
setT * qh_pointfacet (void)
{
  int numpoints= qh num_points + qh_setsize(qh other_points);
  setT *facets;
  facetT *facet;
  vertexT *vertex, **vertexp;
  pointT *point, **pointp;
  facets= qh_settemp(numpoints);
  qh_setzero(facets, 0, numpoints);
  qh vertex_visit++;
  FORALLfacets {
    FOREACHvertex_(facet->vertices) {
      if (vertex->visitid != qh vertex_visit) {
        vertex->visitid= qh vertex_visit;
        qh_point_add(facets, vertex->point, facet);
      }
    }
    FOREACHpoint_(facet->coplanarset)
      qh_point_add(facets, point, facet);
    FOREACHpoint_(facet->outsideset)
      qh_point_add(facets, point, facet);
  }
  return facets;
} /* pointfacet */
Referenced by qh_check_bestdist(), and qh_check_maxout().
qh_pointid()
int qh_pointid (pointT * point)
{
  ptr_intT offset, id;
  if (!point)
    return qh_IDnone;
  else if (point == qh interior_point)
    return qh_IDinterior;
  else if (point >= qh first_point
  && point < qh first_point + qh num_points * qh hull_dim) {
    offset= (ptr_intT)(point - qh first_point);
    id= offset / qh hull_dim;
  }else if ((id= qh_setindex(qh other_points, point)) != -1)
    id += qh num_points;
  else
    return qh_IDunknown;
  return (int)id;
} /* pointid */
Referenced by qh_updatevertices().
qh_pointvertex()
setT * qh_pointvertex (void)
{
  int numpoints= qh num_points + qh_setsize(qh other_points);
  setT *vertices;
  vertexT *vertex;
  vertices= qh_settemp(numpoints);
  qh_setzero(vertices, 0, numpoints);
  FORALLvertices
    qh_point_add(vertices, vertex->point, vertex);
  return vertices;
} /* pointvertex */
Referenced by qh_check_maxout().
qh_prependfacet()
void qh_prependfacet (facetT * facet, facetT ** facetlist)
{
  facetT *prevfacet, *list;
  trace4((qh ferr, 4061, "qh_prependfacet: prepend f%d before f%d\n",
          facet->id, getid_(*facetlist)));
  if (!*facetlist)
    (*facetlist)= qh facet_tail;
  list= *facetlist;
  prevfacet= list->previous;
  facet->previous= prevfacet;
  if (prevfacet)
    prevfacet->next= facet;
  list->previous= facet;
  facet->next= *facetlist;
  if (qh facet_list == list)  /* this may change *facetlist */
    qh facet_list= facet;
  if (qh facet_next == list)
    qh facet_next= facet;
  *facetlist= facet;
  qh num_facets++;
} /* prependfacet */
References getid_, facetT::id, facetT::next, facetT::previous, qh, and trace4.
Referenced by qh_furthestnext(), qh_nextfurthest(), qh_nextfurthest(), qh_willdelete(), and qh_willdelete().
qh_printhashtable()
void qh_printhashtable (FILE * fp)
{
  facetT *facet, *neighbor;
  int id, facet_i, facet_n, neighbor_i= 0, neighbor_n= 0;
  vertexT *vertex, **vertexp;
  FOREACHfacet_i_(qh hash_table) {
    if (facet) {
      FOREACHneighbor_i_(facet) {
        if (!neighbor || neighbor == qh_MERGEridge || neighbor == qh_DUPLICATEridge)
          break;
      }
      if (neighbor_i == neighbor_n)
        continue;
      qh_fprintf(fp, 9283, "hash %d f%d ", facet_i, facet->id);
      FOREACHvertex_(facet->vertices)
        qh_fprintf(fp, 9284, "v%d ", vertex->id);
      qh_fprintf(fp, 9285, "\n neighbors:");
      FOREACHneighbor_i_(facet) {
        if (neighbor == qh_MERGEridge)
          id= -3;
        else if (neighbor == qh_DUPLICATEridge)
          id= -2;
        else
          id= getid_(neighbor);
        qh_fprintf(fp, 9286, " %d", id);
      }
      qh_fprintf(fp, 9287, "\n");
    }
  }
} /* printhashtable */
References FOREACHfacet_i_, FOREACHneighbor_i_, FOREACHvertex_, getid_, facetT::id, qh, qh_DUPLICATEridge, qh_fprintf(), qh_MERGEridge, and facetT::vertices.
Referenced by qh_matchnewfacets(), and qh_matchnewfacets().
qh_printlists()
void qh_printlists (void)
{
  facetT *facet;
  vertexT *vertex;
  int count= 0;
  qh_fprintf(qh ferr, 8108, "qh_printlists: facets:");
  FORALLfacets {
    if (++count % 100 == 0)
      qh_fprintf(qh ferr, 8109, "\n     ");
    qh_fprintf(qh ferr, 8110, " %d", facet->id);
  }
  qh_fprintf(qh ferr, 8111, "\n  new facets %d visible facets %d next facet for qh_addpoint %d\n  vertices(new %d):",
     getid_(qh newfacet_list), getid_(qh visible_list), getid_(qh facet_next),
     getid_(qh newvertex_list));
  count = 0;
  FORALLvertices {
    if (++count % 100 == 0)
      qh_fprintf(qh ferr, 8112, "\n     ");
    qh_fprintf(qh ferr, 8113, " %d", vertex->id);
  }
  qh_fprintf(qh ferr, 8114, "\n");
} /* printlists */
References count, FORALLfacets, FORALLvertices, getid_, facetT::id, qh, and qh_fprintf().
Referenced by qh_addpoint(), qh_addpoint(), qh_all_merges(), qh_all_merges(), qh_checkpolygon(), qh_checkpolygon(), qh_findhorizon(), qh_findhorizon(), qh_premerge(), and qh_premerge().
qh_removefacet()
void qh_removefacet (facetT * facet)
{
  facetT *next= facet->next, *previous= facet->previous;
  if (facet == qh newfacet_list)
    qh newfacet_list= next;
  if (facet == qh facet_next)
    qh facet_next= next;
  if (facet == qh visible_list)
    qh visible_list= next;
  if (previous) {
    previous->next= next;
    next->previous= previous;
  }else {  /* 1st facet in qh facet_list */
    qh facet_list= next;
    qh facet_list->previous= NULL;
  }
  qh num_facets--;
  trace4((qh ferr, 4057, "qh_removefacet: remove f%d from facet_list\n", facet->id));
} /* removefacet */
References facetT::id, facetT::next, NULL, facetT::previous, qh, and trace4.
Referenced by qh_checkconnect(), qh_checkconnect(), qh_delfacet(), qh_findgooddist(), qh_findgooddist(), qh_findhorizon(), qh_findhorizon(), qh_furthestnext(), qh_furthestnext(), qh_mergecycle_facets(), qh_mergecycle_facets(), qh_mergefacet(), qh_mergefacet(), qh_nextfurthest(), qh_nextfurthest(), qh_partitionpoint(), qh_partitionpoint(), qh_willdelete(), and qh_willdelete().
qh_removevertex()
void qh_removevertex (vertexT * vertex)
{
  vertexT *next= vertex->next, *previous= vertex->previous;
  if (vertex == qh newvertex_list)
    qh newvertex_list= next;
  if (previous) {
    previous->next= next;
    next->previous= previous;
  }else {  /* 1st vertex in qh vertex_list */
    qh vertex_list= vertex->next;
    qh vertex_list->previous= NULL;
  }
  qh num_vertices--;
  trace4((qh ferr, 4058, "qh_removevertex: remove v%d from vertex_list\n", vertex->id));
} /* removevertex */
References vertexT::next, NULL, vertexT::previous, qh, and trace4.
Referenced by qh_delvertex(), qh_delvertex(), qh_makenewfacet(), qh_mergesimplex(), qh_mergesimplex(), qh_newvertices(), and qh_newvertices().
qh_resetlists()
void qh_resetlists (boolT stats, boolT resetVisible)
{
  vertexT *vertex;
  facetT *newfacet, *visible;
  int totnew=0, totver=0;
  if (stats) {
    FORALLvertex_(qh newvertex_list)
      totver++;
    FORALLnew_facets
      totnew++;
    zadd_(Zvisvertextot, totver);
    zmax_(Zvisvertexmax, totver);
    zadd_(Znewfacettot, totnew);
    zmax_(Znewfacetmax, totnew);
  }
  FORALLvertex_(qh newvertex_list)
    vertex->newlist= False;
  qh newvertex_list= NULL;
  FORALLnew_facets
    newfacet->newfacet= False;
  qh newfacet_list= NULL;
  if (resetVisible) {
    FORALLvisible_facets {
      visible->f.replace= NULL;
      visible->visible= False;
    }
    qh num_visible= 0;
  }
  qh visible_list= NULL; /* may still have visible facets via qh_triangulate */
  qh NEWfacets= False;
} /* resetlists */
References facetT::f, False, FORALLnew_facets, FORALLvertex_, FORALLvisible_facets, facetT::newfacet, NULL, qh, facetT::visible, zadd_, and zmax_.
Referenced by qh_addpoint(), qh_addpoint(), qh_initbuild(), qh_initialhull(), qh_qhull(), qh_qhull(), qh_triangulate(), and qh_triangulate_facet().
qh_setvoronoi_all()
void qh_setvoronoi_all (void)
{
  facetT *facet;
  qh_clearcenters(qh_ASvoronoi);
  qh_vertexneighbors();
  FORALLfacets {
    if (!facet->normal || !facet->upperdelaunay || qh UPPERdelaunay) {
      if (!facet->center)
        facet->center= qh_facetcenter(facet->vertices);
    }
  }
} /* setvoronoi_all */
qh_triangulate()
void qh_triangulate (void)
{
  facetT *facet, *nextfacet, *owner;
  int onlygood= qh ONLYgood;
  facetT *neighbor, *visible= NULL, *facet1, *facet2, *new_facet_list= NULL;
  facetT *orig_neighbor= NULL, *otherfacet;
  vertexT *new_vertex_list= NULL;
  mergeT *merge;
  mergeType mergetype;
  int neighbor_i, neighbor_n;
  if (qh hasTriangulation)
      return;
  trace1((qh ferr, 1034, "qh_triangulate: triangulate non-simplicial facets\n"));
  if (qh hull_dim == 2)
    return;
  if (qh VORONOI) {  /* otherwise lose Voronoi centers [could rebuild vertex set from tricoplanar] */
    qh_clearcenters(qh_ASvoronoi);
    qh_vertexneighbors();
  }
  qh ONLYgood= False; /* for makenew_nonsimplicial */
  qh visit_id++;
  qh NEWfacets= True;
  qh degen_mergeset= qh_settemp(qh TEMPsize);
  qh newvertex_list= qh vertex_tail;
  for (facet= qh facet_list; facet && facet->next; facet= nextfacet) { /* non-simplicial facets moved to end */
    nextfacet= facet->next;
    if (facet->visible || facet->simplicial)
      continue;
    /* triangulate all non-simplicial facets, otherwise merging does not work, e.g., RBOX c P-0.1 P+0.1 P+0.1 D3 | QHULL d Qt Tv */
    if (!new_facet_list)
      new_facet_list= facet;  /* will be moved to end */
    qh_triangulate_facet(facet, &new_vertex_list);
  }
  trace2((qh ferr, 2047, "qh_triangulate: delete null facets from f%d -- apex same as second vertex\n", getid_(new_facet_list)));
  for (facet= new_facet_list; facet && facet->next; facet= nextfacet) { /* null facets moved to end */
    nextfacet= facet->next;
    if (facet->visible)
      continue;
    if (facet->ridges) {
      if (qh_setsize(facet->ridges) > 0) {
        qh_fprintf(qh ferr, 6161, "qhull error (qh_triangulate): ridges still defined for f%d\n", facet->id);
        qh_errexit(qh_ERRqhull, facet, NULL);
      }
      qh_setfree(&facet->ridges);
    }
    if (SETfirst_(facet->vertices) == SETsecond_(facet->vertices)) {
      zinc_(Ztrinull);
      qh_triangulate_null(facet);
    }
  }
  trace2((qh ferr, 2048, "qh_triangulate: delete %d or more mirror facets -- same vertices and neighbors\n", qh_setsize(qh degen_mergeset)));
  qh visible_list= qh facet_tail;
  while ((merge= (mergeT*)qh_setdellast(qh degen_mergeset))) {
    facet1= merge->facet1;
    facet2= merge->facet2;
    mergetype= merge->type;
    qh_memfree(merge, (int)sizeof(mergeT));
    if (mergetype == MRGmirror) {
      zinc_(Ztrimirror);
      qh_triangulate_mirror(facet1, facet2);
    }
  }
  qh_settempfree(&qh degen_mergeset);
  trace2((qh ferr, 2049, "qh_triangulate: update neighbor lists for vertices from v%d\n", getid_(new_vertex_list)));
  qh newvertex_list= new_vertex_list;  /* all vertices of new facets */
  qh visible_list= NULL;
  qh_updatevertices(/*qh.newvertex_list, empty newfacet_list and visible_list*/);
  qh_resetlists(False, !qh_RESETvisible /*qh.newvertex_list, empty newfacet_list and visible_list*/);
  trace2((qh ferr, 2050, "qh_triangulate: identify degenerate tricoplanar facets from f%d\n", getid_(new_facet_list)));
  trace2((qh ferr, 2051, "qh_triangulate: and replace facet->f.triowner with tricoplanar facets that own center, normal, etc.\n"));
  FORALLfacet_(new_facet_list) {
    if (facet->tricoplanar && !facet->visible) {
      FOREACHneighbor_i_(facet) {
        if (neighbor_i == 0) {  /* first iteration */
          if (neighbor->tricoplanar)
            orig_neighbor= neighbor->f.triowner;
          else
            orig_neighbor= neighbor;
        }else {
          if (neighbor->tricoplanar)
            otherfacet= neighbor->f.triowner;
          else
            otherfacet= neighbor;
          if (orig_neighbor == otherfacet) {
            zinc_(Ztridegen);
            facet->degenerate= True;
            break;
          }
        }
      }
    }
  }
  trace2((qh ferr, 2052, "qh_triangulate: delete visible facets -- non-simplicial, null, and mirrored facets\n"));
  owner= NULL;
  visible= NULL;
  for (facet= new_facet_list; facet && facet->next; facet= nextfacet) { /* may delete facet */
    nextfacet= facet->next;
    if (facet->visible) {
      if (facet->tricoplanar) { /* a null or mirrored facet */
        qh_delfacet(facet);
        qh num_visible--;
      }else {  /* a non-simplicial facet followed by its tricoplanars */
        if (visible && !owner) {
          /*  RBOX 200 s D5 t1001471447 | QHULL Qt C-0.01 Qx Qc Tv Qt -- f4483 had 6 vertices/neighbors and 8 ridges */
          trace2((qh ferr, 2053, "qh_triangulate: all tricoplanar facets degenerate for non-simplicial facet f%d\n",
                       visible->id));
          qh_delfacet(visible);
          qh num_visible--;
        }
        visible= facet;
        owner= NULL;
      }
    }else if (facet->tricoplanar) {
      if (facet->f.triowner != visible || visible==NULL) {
        qh_fprintf(qh ferr, 6162, "qhull error (qh_triangulate): tricoplanar facet f%d not owned by its visible, non-simplicial facet f%d\n", facet->id, getid_(visible));
        qh_errexit2(qh_ERRqhull, facet, visible);
      }
      if (owner)
        facet->f.triowner= owner;
      else if (!facet->degenerate) {
        owner= facet;
        nextfacet= visible->next; /* rescan tricoplanar facets with owner, visible!=0 by QH6162 */
        facet->keepcentrum= True;  /* one facet owns ->normal, etc. */
        facet->coplanarset= visible->coplanarset;
        facet->outsideset= visible->outsideset;
        visible->coplanarset= NULL;
        visible->outsideset= NULL;
        if (!qh TRInormals) { /* center and normal copied to tricoplanar facets */
          visible->center= NULL;
          visible->normal= NULL;
        }
        qh_delfacet(visible);
        qh num_visible--;
      }
    }
  }
  if (visible && !owner) {
    trace2((qh ferr, 2054, "qh_triangulate: all tricoplanar facets degenerate for last non-simplicial facet f%d\n",
                 visible->id));
    qh_delfacet(visible);
    qh num_visible--;
  }
  qh NEWfacets= False;
  qh ONLYgood= onlygood; /* restore value */
  if (qh CHECKfrequently)
    qh_checkpolygon(qh facet_list);
  qh hasTriangulation= True;
} /* triangulate */
qh_triangulate_facet()
void qh_triangulate_facet (facetT * facetA, vertexT ** first_vertex)
{
  facetT *newfacet;
  facetT *neighbor, **neighborp;
  vertexT *apex;
  int numnew=0;
  trace3((qh ferr, 3020, "qh_triangulate_facet: triangulate facet f%d\n", facetA->id));
  if (qh IStracing >= 4)
    qh_printfacet(qh ferr, facetA);
  FOREACHneighbor_(facetA) {
    neighbor->seen= False;
    neighbor->coplanar= False;
  }
  if (qh CENTERtype == qh_ASvoronoi && !facetA->center  /* matches upperdelaunay in qh_setfacetplane() */
        && fabs_(facetA->normal[qh hull_dim -1]) >= qh ANGLEround * qh_ZEROdelaunay) {
    facetA->center= qh_facetcenter(facetA->vertices);
  }
  qh_willdelete(facetA, NULL);
  qh newfacet_list= qh facet_tail;
  facetA->visitid= qh visit_id;
  apex= SETfirstt_(facetA->vertices, vertexT);
  qh_makenew_nonsimplicial(facetA, apex, &numnew);
  SETfirst_(facetA->neighbors)= NULL;
  FORALLnew_facets {
    newfacet->tricoplanar= True;
    newfacet->f.trivisible= facetA;
    newfacet->degenerate= False;
    newfacet->upperdelaunay= facetA->upperdelaunay;
    newfacet->good= facetA->good;
    if (qh TRInormals) { /* 'Q11' triangulate duplicates ->normal and ->center */
      newfacet->keepcentrum= True;
      if(facetA->normal){
        newfacet->normal= qh_memalloc(qh normal_size);
        memcpy((char *)newfacet->normal, facetA->normal, qh normal_size);
      }
      if (qh CENTERtype == qh_AScentrum)
        newfacet->center= qh_getcentrum(newfacet);
      else if (qh CENTERtype == qh_ASvoronoi && facetA->center){
        newfacet->center= qh_memalloc(qh center_size);
        memcpy((char *)newfacet->center, facetA->center, qh center_size);
      }
    }else {
      newfacet->keepcentrum= False;
      /* one facet will have keepcentrum=True at end of qh_triangulate */
      newfacet->normal= facetA->normal;
      newfacet->center= facetA->center;
    }
    newfacet->offset= facetA->offset;
#if qh_MAXoutside
    newfacet->maxoutside= facetA->maxoutside;
#endif
  }
  qh_matchnewfacets(/*qh.newfacet_list*/);
  zinc_(Ztricoplanar);
  zadd_(Ztricoplanartot, numnew);
  zmax_(Ztricoplanarmax, numnew);
  qh visible_list= NULL;
  if (!(*first_vertex))
    (*first_vertex)= qh newvertex_list;
  qh newvertex_list= NULL;
  qh_updatevertices(/*qh.newfacet_list, qh.empty visible_list and qh.newvertex_list*/);
  qh_resetlists(False, !qh_RESETvisible /*qh.newfacet_list, qh.empty visible_list and qh.newvertex_list*/);
} /* triangulate_facet */
References facetT::center, facetT::coplanar, facetT::degenerate, facetT::f, fabs_, False, FORALLnew_facets, FOREACHneighbor_, facetT::good, facetT::id, facetT::keepcentrum, memcpy, facetT::neighbors, facetT::normal, NULL, facetT::offset, qh, qh_AScentrum, qh_ASvoronoi, qh_facetcenter(), qh_getcentrum(), qh_makenew_nonsimplicial(), qh_matchnewfacets(), qh_memalloc(), qh_printfacet(), qh_resetlists(), qh_RESETvisible, qh_updatevertices(), qh_willdelete(), qh_ZEROdelaunay, facetT::seen, SETfirst_, SETfirstt_, trace3, facetT::tricoplanar, True, facetT::upperdelaunay, facetT::vertices, facetT::visitid, zadd_, zinc_, and zmax_.
Referenced by qh_triangulate().
qh_triangulate_link()
void qh_triangulate_link (facetT * oldfacetA, facetT * facetA, facetT * oldfacetB, facetT * facetB)
{
  int errmirror= False;
  trace3((qh ferr, 3021, "qh_triangulate_link: relink old facets f%d and f%d between neighbors f%d and f%d\n",
         oldfacetA->id, oldfacetB->id, facetA->id, facetB->id));
  if (qh_setin(facetA->neighbors, facetB)) {
    if (!qh_setin(facetB->neighbors, facetA))
      errmirror= True;
    else
      qh_appendmergeset(facetA, facetB, MRGmirror, NULL);
  }else if (qh_setin(facetB->neighbors, facetA))
    errmirror= True;
  if (errmirror) {
    qh_fprintf(qh ferr, 6163, "qhull error (qh_triangulate_link): mirror facets f%d and f%d do not match for old facets f%d and f%d\n",
       facetA->id, facetB->id, oldfacetA->id, oldfacetB->id);
    qh_errexit2(qh_ERRqhull, facetA, facetB);
  }
  qh_setreplace(facetB->neighbors, oldfacetB, facetA);
  qh_setreplace(facetA->neighbors, oldfacetA, facetB);
} /* triangulate_link */
References False, facetT::id, MRGmirror, facetT::neighbors, NULL, qh, qh_appendmergeset(), qh_errexit2(), qh_ERRqhull, qh_fprintf(), qh_setin(), qh_setreplace(), trace3, and True.
Referenced by qh_triangulate_mirror(), and qh_triangulate_null().
qh_triangulate_mirror()
void qh_triangulate_mirror (facetT * facetA, facetT * facetB)
{
  facetT *neighbor, *neighborB;
  int neighbor_i, neighbor_n;
  trace3((qh ferr, 3022, "qh_triangulate_mirror: delete mirrored facets f%d and f%d\n",
         facetA->id, facetB->id));
  FOREACHneighbor_i_(facetA) {
    neighborB= SETelemt_(facetB->neighbors, neighbor_i, facetT);
    if (neighbor == neighborB)
      continue; /* occurs twice */
    qh_triangulate_link(facetA, neighbor, facetB, neighborB);
  }
  qh_willdelete(facetA, NULL);
  qh_willdelete(facetB, NULL);
} /* triangulate_mirror */
References FOREACHneighbor_i_, facetT::id, facetT::neighbors, NULL, qh, qh_triangulate_link(), qh_willdelete(), SETelemt_, and trace3.
Referenced by qh_triangulate().
qh_triangulate_null()
void qh_triangulate_null (facetT * facetA)
{
  facetT *neighbor, *otherfacet;
  trace3((qh ferr, 3023, "qh_triangulate_null: delete null facet f%d\n", facetA->id));
  neighbor= SETfirstt_(facetA->neighbors, facetT);
  otherfacet= SETsecondt_(facetA->neighbors, facetT);
  qh_triangulate_link(facetA, neighbor, facetA, otherfacet);
  qh_willdelete(facetA, NULL);
} /* triangulate_null */
References facetT::id, facetT::neighbors, NULL, qh, qh_triangulate_link(), qh_willdelete(), SETfirstt_, SETsecondt_, and trace3.
Referenced by qh_triangulate().
qh_updatevertices()
void qh_updatevertices (void)
{
  facetT *newfacet= NULL, *neighbor, **neighborp, *visible;
  vertexT *vertex, **vertexp;
  trace3((qh ferr, 3013, "qh_updatevertices: delete interior vertices and update vertex->neighbors\n"));
  if (qh VERTEXneighbors) {
    FORALLvertex_(qh newvertex_list) {
      FOREACHneighbor_(vertex) {
        if (neighbor->visible)
          SETref_(neighbor)= NULL;
      }
      qh_setcompact(vertex->neighbors);
    }
    FORALLnew_facets {
      FOREACHvertex_(newfacet->vertices)
        qh_setappend(&vertex->neighbors, newfacet);
    }
    FORALLvisible_facets {
      FOREACHvertex_(visible->vertices) {
        if (!vertex->newlist && !vertex->deleted) {
          FOREACHneighbor_(vertex) { /* this can happen under merging */
            if (!neighbor->visible)
              break;
          }
          if (neighbor)
            qh_setdel(vertex->neighbors, visible);
          else {
            vertex->deleted= True;
            qh_setappend(&qh del_vertices, vertex);
            trace2((qh ferr, 2041, "qh_updatevertices: delete vertex p%d(v%d) in f%d\n",
                  qh_pointid(vertex->point), vertex->id, visible->id));
          }
        }
      }
    }
  }else {  /* !VERTEXneighbors */
    FORALLvisible_facets {
      FOREACHvertex_(visible->vertices) {
        if (!vertex->newlist && !vertex->deleted) {
          vertex->deleted= True;
          qh_setappend(&qh del_vertices, vertex);
          trace2((qh ferr, 2042, "qh_updatevertices: delete vertex p%d(v%d) in f%d\n",
                  qh_pointid(vertex->point), vertex->id, visible->id));
        }
      }
    }
  }
} /* updatevertices */
References FORALLnew_facets, FORALLvertex_, FORALLvisible_facets, FOREACHneighbor_, FOREACHvertex_, NULL, qh, qh_pointid(), qh_setappend(), qh_setcompact(), qh_setdel(), SETref_, trace2, trace3, True, and facetT::vertices.
Referenced by qh_addpoint(), qh_addpoint(), qh_triangulate(), qh_triangulate(), qh_triangulate_facet(), and qh_triangulate_facet().
qh_vertexintersect()
void qh_vertexintersect (setT ** vertexsetA, setT * vertexsetB)
{
  setT *intersection;
  intersection= qh_vertexintersect_new(*vertexsetA, vertexsetB);
  qh_settempfree(vertexsetA);
  *vertexsetA= intersection;
  qh_settemppush(intersection);
} /* vertexintersect */
References qh_settempfree(), qh_settemppush(), and qh_vertexintersect_new().
Referenced by qh_neighbor_intersections(), and qh_neighbor_intersections().
qh_vertexintersect_new()
setT * qh_vertexintersect_new (setT * vertexsetA, setT * vertexsetB)
{
  setT *intersection= qh_setnew(qh hull_dim - 1);
  vertexT **vertexA= SETaddr_(vertexsetA, vertexT);
  vertexT **vertexB= SETaddr_(vertexsetB, vertexT);
  while (*vertexA && *vertexB) {
    if (*vertexA  == *vertexB) {
      qh_setappend(&intersection, *vertexA);
      vertexA++; vertexB++;
    }else {
      if ((*vertexA)->id > (*vertexB)->id)
        vertexA++;
      else
        vertexB++;
    }
  }
  return intersection;
} /* vertexintersect_new */
References qh, qh_setappend(), qh_setnew(), and SETaddr_.
Referenced by qh_checkfacet(), qh_neighbor_intersections(), qh_neighbor_intersections(), qh_rename_sharedvertex(), qh_rename_sharedvertex(), and qh_vertexintersect().
qh_vertexneighbors()
void qh_vertexneighbors (void)
{
  facetT *facet;
  vertexT *vertex, **vertexp;
  if (qh VERTEXneighbors)
    return;
  trace1((qh ferr, 1035, "qh_vertexneighbors: determining neighboring facets for each vertex\n"));
  qh vertex_visit++;
  FORALLfacets {
    if (facet->visible)
      continue;
    FOREACHvertex_(facet->vertices) {
      if (vertex->visitid != qh vertex_visit) {
        vertex->visitid= qh vertex_visit;
        vertex->neighbors= qh_setnew(qh hull_dim);
      }
      qh_setappend(&vertex->neighbors, facet);
    }
  }
  qh VERTEXneighbors= True;
} /* vertexneighbors */
References FORALLfacets, FOREACHvertex_, qh, qh_setappend(), qh_setnew(), trace1, True, facetT::vertices, and facetT::visible.
Referenced by orgQhull::Qhull::defineVertexNeighborFacets(), qh_eachvoronoi_all(), qh_eachvoronoi_all(), qh_findbestlower(), qh_findbestlower(), qh_markvoronoi(), qh_markvoronoi(), qh_mergecycle(), qh_mergecycle(), qh_mergefacet(), qh_mergefacet(), qh_prepare_output(), qh_prepare_output(), qh_printextremes_d(), qh_printextremes_d(), qh_printvneighbors(), qh_printvneighbors(), qh_setvoronoi_all(), qh_setvoronoi_all(), qh_test_vneighbors(), qh_test_vneighbors(), qh_triangulate(), and qh_triangulate().
qh_vertexsubset()
boolT qh_vertexsubset (setT * vertexsetA, setT * vertexsetB)
{
  vertexT **vertexA= (vertexT **) SETaddr_(vertexsetA, vertexT);
  vertexT **vertexB= (vertexT **) SETaddr_(vertexsetB, vertexT);
  while (True) {
    if (!*vertexA)
      return True;
    if (!*vertexB)
      return False;
    if ((*vertexA)->id > (*vertexB)->id)
      return False;
    if (*vertexA  == *vertexB)
      vertexA++;
    vertexB++;
  }
  return False; /* avoid warnings */
} /* vertexsubset */
References False, SETaddr_, and True.