OrcaSlicer: Slic3r::GUI::MachineListModel Class Reference
Slic3r::GUI::MachineListModel Class Reference
#include <src/slic3r/GUI/SelectMachine.hpp>
Public Types
enum {
Col_MachineName = 0 , Col_MachineSN = 1 , Col_MachineBind = 2 , Col_MachinePrintingStatus = 3 ,
Col_MachineIPAddress = 4 , Col_MachineConnection = 5 , Col_MachineTaskName = 6 , Col_Max = 7
}
Public Member Functions
MachineListModel ()
virtual unsigned int GetColumnCount () const wxOVERRIDE
virtual wxString GetColumnType (unsigned int col) const wxOVERRIDE
virtual void GetValueByRow (wxVariant &variant, unsigned int row, unsigned int col) const wxOVERRIDE
virtual bool GetAttrByRow (unsigned int row, unsigned int col, wxDataViewItemAttr &attr) const wxOVERRIDE
virtual bool SetValueByRow (const wxVariant &variant, unsigned int row, unsigned int col) wxOVERRIDE
void display_machines (std::map< std::string, MachineObject * > list)
void add_machine (MachineObject *obj, bool reset=true)
int find_row_by_sn (wxString sn)
Private Attributes
wxArrayString m_values [Col_Max]
wxArrayString m_nameColValues
wxArrayString m_snColValues
wxArrayString m_bindColValues
wxArrayString m_connectionColValues
wxArrayString m_printingStatusValues
wxArrayString m_ipAddressValues
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Col_MachineName
Col_MachineSN
Col_MachineBind
Col_MachinePrintingStatus
Col_MachineIPAddress
Col_MachineConnection
Col_MachineTaskName
Col_Max
         {
        Col_MachineName           = 0,
        Col_MachineSN             = 1,
        Col_MachineBind           = 2,
        Col_MachinePrintingStatus = 3,
        Col_MachineIPAddress      = 4,
        Col_MachineConnection     = 5,
        Col_MachineTaskName       = 6,
        Col_Max                   = 7
    };
Constructor & Destructor Documentation
MachineListModel()
Slic3r::GUI::MachineListModel::MachineListModel ()
: wxDataViewVirtualListModel(INITIAL_NUMBER_OF_MACHINES) { ; }
Member Function Documentation
add_machine()
void Slic3r::GUI::MachineListModel::add_machine (MachineObject * obj, bool reset = true)
{
    m_values[Col_MachineName].Add(from_u8(obj->dev_name));
    m_values[Col_MachineSN].Add(from_u8(obj->dev_id));
    m_values[Col_MachinePrintingStatus].Add(from_u8(obj->print_status));
    m_values[Col_MachineIPAddress].Add(from_u8(obj->dev_ip));
    m_values[Col_MachineConnection].Add(obj->is_online() ? _L("Online") : _L("Offline"));
    if (reset) Reset(m_values[Col_MachineName].GetCount());
}
References _L, Col_MachineConnection, Col_MachineIPAddress, Col_MachineName, Col_MachinePrintingStatus, Col_MachineSN, Slic3r::MachineObject::dev_id, Slic3r::MachineObject::dev_ip, Slic3r::MachineObject::dev_name, Slic3r::GUI::from_u8(), Slic3r::MachineObject::is_online(), m_values, and Slic3r::MachineObject::print_status.
Referenced by display_machines().
display_machines()
void Slic3r::GUI::MachineListModel::display_machines (std::map< std::string, MachineObject * > list)
{
    for (int i = 0; i < Col_Max; i++) { m_values[i].clear(); }
    std::vector<MachineObject *>                     list_array;
    std::map<std::string, MachineObject *>::iterator it;
    for (it = list.begin(); it != list.end(); it++) { list_array.push_back(it->second); }
    std::sort(list_array.begin(), list_array.end(), [](MachineObject *obj1, MachineObject *obj2) { return obj1->dev_name < obj2->dev_name; });
    std::vector<MachineObject *>::iterator iter;
    for (iter = list_array.begin(); iter != list_array.end(); iter++) { this->add_machine(*iter, false); }
    Reset(list_array.size());
}
References add_machine(), Col_Max, and m_values.
find_row_by_sn()
int Slic3r::GUI::MachineListModel::find_row_by_sn (wxString sn)
{
    wxVariant val;
    for (int i = 0; i < this->GetCount(); i++) {
        GetValueByRow(val, i, Col_MachineSN);
        if (val == sn) { return i; }
    }
    return -1;
}
References Col_MachineSN, and GetValueByRow().
GetAttrByRow()
bool Slic3r::GUI::MachineListModel::GetAttrByRow (unsigned int row, unsigned int col, wxDataViewItemAttr & attr) const virtual
{ return true; }
GetColumnCount()
virtual unsigned int Slic3r::GUI::MachineListModel::GetColumnCount () const inline virtual
{ return Col_Max; }
References Col_Max.
GetColumnType()
virtual wxString Slic3r::GUI::MachineListModel::GetColumnType (unsigned int col) const inline virtual
{ return "string"; }
GetValueByRow()
void Slic3r::GUI::MachineListModel::GetValueByRow (wxVariant & variant, unsigned int row, unsigned int col) const virtual
{
    if (row > m_values[col].GetCount())
        variant = wxString::Format("virtual row %d", row);
    else
        variant = m_values[col][row];
}
References col(), m_values, and row().
Referenced by find_row_by_sn().
SetValueByRow()
bool Slic3r::GUI::MachineListModel::SetValueByRow (const wxVariant & variant, unsigned int row, unsigned int col) virtual
{
    if (row >= m_values[col].GetCount()) return false;
    m_values[col][row] = variant.GetString();
    return true;
}
References col(), m_values, and row().
Member Data Documentation
m_bindColValues
wxArrayString Slic3r::GUI::MachineListModel::m_bindColValues private
m_connectionColValues
wxArrayString Slic3r::GUI::MachineListModel::m_connectionColValues private
m_ipAddressValues
wxArrayString Slic3r::GUI::MachineListModel::m_ipAddressValues private
m_nameColValues
wxArrayString Slic3r::GUI::MachineListModel::m_nameColValues private
m_printingStatusValues
wxArrayString Slic3r::GUI::MachineListModel::m_printingStatusValues private
m_snColValues
wxArrayString Slic3r::GUI::MachineListModel::m_snColValues private
m_values
wxArrayString Slic3r::GUI::MachineListModel::m_values[Col_Max] private
Referenced by add_machine(), display_machines(), GetValueByRow(), and SetValueByRow().
The documentation for this class was generated from the following files:
src/slic3r/GUI/SelectMachine.hpp
src/slic3r/GUI/SelectMachine.cpp