OrcaSlicer: src/slic3r/GUI/Auxiliary.hpp File Reference
Auxiliary.hpp File Reference
#include "Tabbook.hpp"
#include <wx/notebook.h>
#include <wx/scrolwin.h>
#include <wx/sizer.h>
#include <wx/bmpcbox.h>
#include <wx/bmpbuttn.h>
#include <wx/treectrl.h>
#include <wx/imaglist.h>
#include <wx/artprov.h>
#include <wx/xrc/xmlres.h>
#include <wx/string.h>
#include <wx/stattext.h>
#include <wx/gdicmn.h>
#include <wx/font.h>
#include <wx/colour.h>
#include <wx/settings.h>
#include <wx/grid.h>
#include <wx/dataview.h>
#include <wx/panel.h>
#include <wx/statline.h>
#include <wx/bitmap.h>
#include <wx/image.h>
#include <wx/icon.h>
#include <wx/button.h>
#include <wx/gbsizer.h>
#include <wx/statbox.h>
#include <wx/tglbtn.h>
#include <wx/popupwin.h>
#include <wx/spinctrl.h>
#include <wx/webrequest.h>
#include <map>
#include <vector>
#include <memory>
#include "Event.hpp"
#include "libslic3r/ProjectTask.hpp"
#include "wxExtensions.hpp"
#include "slic3r/GUI/DeviceManager.hpp"
#include "slic3r/GUI/MonitorBasePanel.h"
#include "slic3r/GUI/StatusPanel.hpp"
#include "slic3r/GUI/UpgradePanel.hpp"
#include "slic3r/GUI/AmsWidgets.hpp"
#include "Widgets/SideTools.hpp"
Classes
class Slic3r::GUI::AuFile
class Slic3r::GUI::AuFiles
class Slic3r::GUI::AuFolderPanel
class Slic3r::GUI::DesignerPanel
class Slic3r::GUI::AuxiliaryPanel
Namespaces
namespace Slic3r
namespace Slic3r::GUI
Macros
#define AUFILE_GREY700 wxColour(107, 107, 107)
#define AUFILE_GREY500 wxColour(158, 158, 158)
#define AUFILE_GREY300 wxColour(238, 238, 238)
#define AUFILE_GREY200 wxColour(248, 248, 248)
#define AUFILE_BRAND wxColour(0, 150, 136)
#define AUFILE_BRAND_TRANSPARENT wxColour(215, 232, 222)
#define AUFILE_PICTURES_SIZE wxSize(FromDIP(168), FromDIP(168))
#define AUFILE_PICTURES_PANEL_SIZE wxSize(FromDIP(168), FromDIP(208))
#define AUFILE_SIZE wxSize(FromDIP(168), FromDIP(168))
#define AUFILE_PANEL_SIZE wxSize(FromDIP(168), FromDIP(208))
#define AUFILE_TEXT_HEIGHT FromDIP(40)
#define AUFILE_ROUNDING FromDIP(5)
Enumerations
enum AuxiliaryFolderType {
MODEL_PICTURE , BILL_OF_MATERIALS , ASSEMBLY_GUIDE , OTHERS ,
THUMBNAILS , DESIGNER , AddFileButton
}
enum ValidationType { Valid , NoValid , Warning }
Functions
Slic3r::GUI::WX_DEFINE_ARRAY (AuFiles *, AuFilesHash)
Slic3r::GUI::wxDECLARE_EVENT (EVT_AUXILIARY_IMPORT, wxCommandEvent)
Slic3r::GUI::wxDECLARE_EVENT (EVT_AUXILIARY_UPDATE_COVER, wxCommandEvent)
Slic3r::GUI::wxDECLARE_EVENT (EVT_AUXILIARY_UPDATE_DELETE, wxCommandEvent)
Slic3r::GUI::wxDECLARE_EVENT (EVT_AUXILIARY_UPDATE_RENAME, wxCommandEvent)
Variables
static const std::array< wxString, 5 > s_default_folders = {("Model Pictures"), ("Bill of Materials"), ("Assembly Guide"), ("Others"), (".thumbnails")}
Class Documentation
Slic3r::GUI::AuFiles
class Slic3r::GUI::AuFiles
Class Members
AuFile * file
wxString path
Macro Definition Documentation
AUFILE_BRAND
#define AUFILE_BRAND wxColour(0, 150, 136)
AUFILE_BRAND_TRANSPARENT
#define AUFILE_BRAND_TRANSPARENT wxColour(215, 232, 222)
AUFILE_GREY200
#define AUFILE_GREY200 wxColour(248, 248, 248)
AUFILE_GREY300
#define AUFILE_GREY300 wxColour(238, 238, 238)
AUFILE_GREY500
#define AUFILE_GREY500 wxColour(158, 158, 158)
AUFILE_GREY700
#define AUFILE_GREY700 wxColour(107, 107, 107)
AUFILE_PANEL_SIZE
#define AUFILE_PANEL_SIZE wxSize(FromDIP(168), FromDIP(208))
AUFILE_PICTURES_PANEL_SIZE
#define AUFILE_PICTURES_PANEL_SIZE wxSize(FromDIP(168), FromDIP(208))
AUFILE_PICTURES_SIZE
#define AUFILE_PICTURES_SIZE wxSize(FromDIP(168), FromDIP(168))
AUFILE_ROUNDING
#define AUFILE_ROUNDING FromDIP(5)
AUFILE_SIZE
#define AUFILE_SIZE wxSize(FromDIP(168), FromDIP(168))
AUFILE_TEXT_HEIGHT
#define AUFILE_TEXT_HEIGHT FromDIP(40)
Enumeration Type Documentation
AuxiliaryFolderType
enum AuxiliaryFolderType
Enumerator
MODEL_PICTURE
BILL_OF_MATERIALS
ASSEMBLY_GUIDE
OTHERS
THUMBNAILS
DESIGNER
AddFileButton
{
    MODEL_PICTURE,
    BILL_OF_MATERIALS,
    ASSEMBLY_GUIDE,
    OTHERS,
    THUMBNAILS,
    DESIGNER,
    AddFileButton,
};
ValidationType
enum ValidationType
Enumerator
Valid
NoValid
Warning
{ Valid, NoValid, Warning };
Variable Documentation
s_default_folders
const std::array<wxString, 5> s_default_folders = {("Model Pictures"), ("Bill of Materials"), ("Assembly Guide"), ("Others"), (".thumbnails")} static
Referenced by Slic3r::GUI::AuFolderPanel::AuFolderPanel(), AuxiliaryModel::Init(), Slic3r::GUI::AuxiliaryPanel::init_auxiliary(), Slic3r::GUI::AuFolderPanel::on_add(), Slic3r::GUI::AuxiliaryPanel::on_import_file(), Slic3r::GUI::AuFile::on_input_enter(), Slic3r::GUI::AuFile::on_set_cover(), Slic3r::GUI::AuFile::on_set_delete(), Slic3r::GUI::AuxiliaryPanel::Reload(), AuxiliaryModel::Reload(), and Slic3r::GUI::ProjectPanel::Reload().