OrcaSlicer: Slic3r::Preset Class Reference
Slic3r::Preset Class Reference
#include <src/libslic3r/Preset.hpp>
Public Types
enum Type {
TYPE_INVALID , TYPE_PRINT , TYPE_SLA_PRINT , TYPE_FILAMENT ,
TYPE_SLA_MATERIAL , TYPE_PRINTER , TYPE_COUNT , TYPE_PHYSICAL_PRINTER ,
TYPE_MODEL
}
Public Member Functions
bool is_user () const
void load_info (const std::string &file)
void save_info (std::string file="")
void remove_files ()
void save (DynamicPrintConfig *parent_config)
std::string label (bool no_alias) const
void set_dirty (const DynamicPrintConfig &config)
void set_dirty (bool dirty=true)
void reset_dirty ()
std::string & inherits ()
const std::string & inherits () const
std::string & compatible_prints_condition ()
const std::string & compatible_prints_condition () const
std::string & compatible_printers_condition ()
const std::string & compatible_printers_condition () const
PrinterTechnology printer_technology () const
PrinterTechnology & printer_technology_ref ()
void set_visible_from_appconfig (const AppConfig &app_config)
void set_num_extruders (unsigned int n)
bool operator< (const Preset &other) const
std::string get_filament_type (std::string &display_filament_type)
std::string get_printer_type (PresetBundle *preset_bundle)
std::string get_current_printer_type (PresetBundle *preset_bundle)
bool is_custom_defined ()
bool has_lidar (PresetBundle *preset_bundle)
BedType get_default_bed_type (PresetBundle *preset_bundle)
bool has_cali_lines (PresetBundle *preset_bundle)
Preset (Type type, const std::string &name, bool is_default=false)
Static Public Member Functions
static std::string get_type_string (Preset::Type type)
static std::string get_iot_type_string (Preset::Type type)
static Preset::Type get_type_from_string (std::string type_str)
static std::string & inherits (DynamicPrintConfig &cfg)
static std::string & compatible_prints_condition (DynamicPrintConfig &cfg)
static std::string & compatible_printers_condition (DynamicPrintConfig &cfg)
static PrinterTechnology printer_technology (const DynamicPrintConfig &cfg)
static const std::vector< std::string > & print_options ()
static const std::vector< std::string > & filament_options ()
static const std::vector< std::string > & printer_options ()
static const std::vector< std::string > & nozzle_options ()
static const std::vector< std::string > & machine_limits_options ()
static const std::vector< std::string > & sla_printer_options ()
static const std::vector< std::string > & sla_material_options ()
static const std::vector< std::string > & sla_print_options ()
static void update_suffix_modified (const std::string &new_suffix_modified)
static const std::string & suffix_modified ()
static std::string remove_suffix_modified (const std::string &name)
static void normalize (DynamicPrintConfig &config)
static std::string remove_invalid_keys (DynamicPrintConfig &config, const DynamicPrintConfig &default_config)
Public Attributes
Type type = TYPE_INVALID
bool is_default = false
bool is_external = false
bool is_system = false
bool is_visible = true
bool is_dirty = false
bool is_compatible = true
bool is_project_embedded = false
ConfigSubstitutions * loading_substitutions {nullptr}
std::string name
std::string file
const VendorProfile * vendor = nullptr
bool loaded = false
DynamicPrintConfig config
std::string alias
std::vector< std::string > renamed_from
Semver version
std::string ini_str
std::string setting_id
std::string filament_id
std::string user_id
std::string base_id
std::string sync_info
std::string custom_defined
long long updated_time {0}
std::map< std::string, std::string > key_values
Protected Member Functions
Preset ()=default
Friends
class PresetCollection
class PresetBundle
Detailed Description
Member Enumeration Documentation
Type
enum Slic3r::Preset::Type
Enumerator
TYPE_INVALID
TYPE_PRINT
TYPE_SLA_PRINT
TYPE_FILAMENT
TYPE_SLA_MATERIAL
TYPE_PRINTER
TYPE_COUNT
TYPE_PHYSICAL_PRINTER
TYPE_MODEL
    {
        TYPE_INVALID,
        TYPE_PRINT,
        TYPE_SLA_PRINT,
        TYPE_FILAMENT,
        TYPE_SLA_MATERIAL,
        TYPE_PRINTER,
        TYPE_COUNT,
        // This type is here to support PresetConfigSubstitutions for physical printers, however it does not belong to the Preset class,
        // PhysicalPrinter class is used instead.
        TYPE_PHYSICAL_PRINTER,
        // BBS: model config
        TYPE_MODEL,
    };
Constructor & Destructor Documentation
Preset() [1/2]
Slic3r::Preset::Preset (Type type, const std::string & name, bool is_default = false) inline
: type(type), is_default(is_default), name(name) {}
Preset() [2/2]
Slic3r::Preset::Preset () protected default
Member Function Documentation
compatible_printers_condition() [1/3]
std::string & Slic3r::Preset::compatible_printers_condition () inline
{
    assert(this->type == TYPE_PRINT || this->type == TYPE_SLA_PRINT || this->type == TYPE_FILAMENT || this->type == TYPE_SLA_MATERIAL);
        return Preset::compatible_printers_condition(this->config);
    }
References compatible_printers_condition(), TYPE_FILAMENT, TYPE_PRINT, TYPE_SLA_MATERIAL, and TYPE_SLA_PRINT.
Referenced by compatible_printers_condition(), Slic3r::PresetBundle::full_fff_config(), and Slic3r::PresetBundle::load_config_file_config().
compatible_printers_condition() [2/3]
const std::string & Slic3r::Preset::compatible_printers_condition () const inline
{ return const_cast<Preset*>(this)->compatible_printers_condition(); }
References compatible_printers_condition().
Referenced by compatible_printers_condition().
compatible_printers_condition() [3/3]
static std::string & Slic3r::Preset::compatible_printers_condition (DynamicPrintConfig & cfg) inline static
{ return cfg.option<ConfigOptionString>("compatible_printers_condition", true)->value; }
References Slic3r::ConfigBase::option().
Referenced by Slic3r::PresetBundle::PresetBundle(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetBundle::full_sla_config(), and Slic3r::is_compatible_with_printer().
compatible_prints_condition() [1/3]
std::string & Slic3r::Preset::compatible_prints_condition () inline
{
    assert(this->type == TYPE_FILAMENT || this->type == TYPE_SLA_MATERIAL);
        return Preset::compatible_prints_condition(this->config);
    }
References compatible_prints_condition(), TYPE_FILAMENT, and TYPE_SLA_MATERIAL.
Referenced by compatible_prints_condition(), Slic3r::PresetBundle::full_fff_config(), and Slic3r::PresetBundle::load_config_file_config().
compatible_prints_condition() [2/3]
const std::string & Slic3r::Preset::compatible_prints_condition () const inline
{ return const_cast<Preset*>(this)->compatible_prints_condition(); }
References compatible_prints_condition().
Referenced by compatible_prints_condition().
compatible_prints_condition() [3/3]
static std::string & Slic3r::Preset::compatible_prints_condition (DynamicPrintConfig & cfg) inline static
{ return cfg.option<ConfigOptionString>("compatible_prints_condition", true)->value; }
References Slic3r::ConfigBase::option().
Referenced by Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetBundle::full_sla_config(), and Slic3r::is_compatible_with_print().
filament_options()
const std::vector< std::string > & Slic3r::Preset::filament_options () static
{ return s_Preset_filament_options; }
References Slic3r::s_Preset_filament_options.
Referenced by normalize().
get_current_printer_type()
std::string Slic3r::Preset::get_current_printer_type (PresetBundle * preset_bundle)
{
    if (preset_bundle) {
        auto config = &(this->config);
        std::string vendor_name;
        for (auto vendor_profile : preset_bundle->vendors) {
            for (auto vendor_model : vendor_profile.second.models)
                if (vendor_model.name == config->opt_string("printer_model")) {
                    vendor_name = vendor_profile.first;
                    return vendor_model.model_id;
                }
        }
    }
    return "";
}
References config, Slic3r::DynamicConfig::opt_string(), and Slic3r::PresetBundle::vendors.
get_default_bed_type()
BedType Slic3r::Preset::get_default_bed_type (PresetBundle * preset_bundle)
{
    if (config.has("default_bed_type") && !config.opt_string("default_bed_type").empty()) {
        try {
            std::string str_bed_type = config.opt_string("default_bed_type");
            int bed_type_value = atoi(str_bed_type.c_str());
            return BedType(bed_type_value);
        } catch(...) {
            ;
        }
    }
    std::string model_id = this->get_printer_type(preset_bundle);
    if (model_id == "BL-P001" || model_id == "BL-P002") {
        return BedType::btPC;
    } else if (model_id == "C11") {
        return BedType::btPEI;
    }
    return BedType::btPEI;
}
References Slic3r::btPC, Slic3r::btPEI, config, get_printer_type(), Slic3r::ConfigOptionResolver::has(), and Slic3r::DynamicConfig::opt_string().
get_filament_type()
std::string Slic3r::Preset::get_filament_type (std::string & display_filament_type)
{
    return config.get_filament_type(display_filament_type);
}
References config, and Slic3r::DynamicPrintConfig::get_filament_type().
get_iot_type_string()
std::string Slic3r::Preset::get_iot_type_string (Preset::Type type) static
{
    switch (type) {
    case Preset::Type::TYPE_FILAMENT:
        return PRESET_IOT_FILAMENT_TYPE;
    case Preset::Type::TYPE_PRINT:
        return PRESET_IOT_PRINT_TYPE;
    case Preset::Type::TYPE_PRINTER:
        return PRESET_IOT_PRINTER_TYPE;
    default:
        return "invalid";
    }
}
References PRESET_IOT_FILAMENT_TYPE, PRESET_IOT_PRINT_TYPE, PRESET_IOT_PRINTER_TYPE, type, TYPE_FILAMENT, TYPE_PRINT, and TYPE_PRINTER.
Referenced by Slic3r::PresetCollection::get_differed_values_to_update().
get_printer_type()
std::string Slic3r::Preset::get_printer_type (PresetBundle * preset_bundle)
{
    if (preset_bundle) {
        auto config = &preset_bundle->printers.get_edited_preset().config;
        std::string vendor_name;
        for (auto vendor_profile : preset_bundle->vendors) {
            for (auto vendor_model : vendor_profile.second.models)
                if (vendor_model.name == config->opt_string("printer_model"))
                {
                    vendor_name = vendor_profile.first;
                    return vendor_model.model_id;
                }
        }
    }
    return "";
}
References config, Slic3r::PresetCollection::get_edited_preset(), Slic3r::DynamicConfig::opt_string(), Slic3r::PresetBundle::printers, and Slic3r::PresetBundle::vendors.
Referenced by get_default_bed_type(), has_cali_lines(), and Slic3r::GUI::SelectMachineDialog::is_same_printer_model().
get_type_from_string()
Preset::Type Slic3r::Preset::get_type_from_string (std::string type_str) static
{
    if (type_str.compare(PRESET_PRINT_NAME) == 0 || type_str.compare(PRESET_IOT_PRINT_TYPE) == 0)
        return Preset::Type::TYPE_PRINT;
    else if (type_str.compare(PRESET_FILAMENT_NAME) == 0 || type_str.compare(PRESET_IOT_FILAMENT_TYPE) == 0)
        return Preset::Type::TYPE_FILAMENT;
    else if (type_str.compare(PRESET_PRINTER_NAME) == 0 || type_str.compare(PRESET_IOT_PRINTER_TYPE) == 0)
        return Preset::Type::TYPE_PRINTER;
    else
        return Preset::Type::TYPE_INVALID;
}
References PRESET_FILAMENT_NAME, PRESET_IOT_FILAMENT_TYPE, PRESET_IOT_PRINT_TYPE, PRESET_IOT_PRINTER_TYPE, PRESET_PRINT_NAME, PRESET_PRINTER_NAME, TYPE_FILAMENT, TYPE_INVALID, TYPE_PRINT, and TYPE_PRINTER.
Referenced by Slic3r::PresetCollection::load_project_embedded_presets().
get_type_string()
std::string Slic3r::Preset::get_type_string (Preset::Type type) static
{
    switch (type) {
        case Preset::Type::TYPE_FILAMENT:
            return PRESET_FILAMENT_NAME;
        case Preset::Type::TYPE_PRINT:
            return PRESET_PRINT_NAME;
        case Preset::Type::TYPE_PRINTER:
            return PRESET_PRINTER_NAME;
        case Preset::Type::TYPE_PHYSICAL_PRINTER:
            return "physical_printer";
        case Preset::Type::TYPE_INVALID:
            return "invalid";
        default:
            return "invalid";
    }
}
References PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, PRESET_PRINTER_NAME, type, TYPE_FILAMENT, TYPE_INVALID, TYPE_PHYSICAL_PRINTER, TYPE_PRINT, and TYPE_PRINTER.
Referenced by Slic3r::GUI::SavePresetDialog::Item::Item(), Slic3r::GUI::Tab::delete_preset(), Slic3r::PresetCollection::get_project_embedded_presets(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::PresetCollection::reset_project_embedded_presets(), Slic3r::PresetCollection::select_preset(), Slic3r::PresetCollection::select_preset_by_name(), and Slic3r::PresetCollection::select_preset_by_name_strict().
has_cali_lines()
bool Slic3r::Preset::has_cali_lines (PresetBundle * preset_bundle)
{
    std::string model_id = this->get_printer_type(preset_bundle);
    if (model_id == "BL-P001" || model_id == "BL-P002") {
        return true;
    }
    return false;
}
References get_printer_type().
has_lidar()
bool Slic3r::Preset::has_lidar (PresetBundle * preset_bundle)
{
    bool has_lidar = false;
    if (preset_bundle) {
        auto config = &preset_bundle->printers.get_edited_preset().config;
        std::string vendor_name;
        for (auto vendor_profile : preset_bundle->vendors) {
            for (auto vendor_model : vendor_profile.second.models)
                if (vendor_model.name == config->opt_string("printer_model"))
                {
                    vendor_name = vendor_profile.first;
                    break;
                }
        }
        if (!vendor_name.empty())
            has_lidar = vendor_name.compare("BBL") == 0 ? true : false;
    }
    return has_lidar;
}
References config, Slic3r::PresetCollection::get_edited_preset(), has_lidar(), Slic3r::DynamicConfig::opt_string(), Slic3r::PresetBundle::printers, and Slic3r::PresetBundle::vendors.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::Plater::_calib_pa_pattern(), Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), has_lidar(), Slic3r::GUI::MainFrame::load_printer_url(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::BackgroundSlicingProcess::process_fff(), Slic3r::GUI::Plater::reslice(), Slic3r::GUI::TabFilament::toggle_options(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::Sidebar::update_all_preset_comboboxes().
inherits() [1/3]
std::string & Slic3r::Preset::inherits () inline
{ return Preset::inherits(this->config); }
References inherits().
Referenced by Slic3r::PresetBundle::full_fff_config(), inherits(), inherits(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::PresetCollection::load_external_preset(), and Slic3r::PresetCollection::save_user_presets().
inherits() [2/3]
const std::string & Slic3r::Preset::inherits () const inline
{ return Preset::inherits(const_cast<Preset*>(this)->config); }
References config, and inherits().
inherits() [3/3]
static std::string & Slic3r::Preset::inherits (DynamicPrintConfig & cfg) inline static
{ return cfg.option<ConfigOptionString>("inherits", true)->value; }
References Slic3r::ConfigBase::option().
Referenced by Slic3r::PresetBundle::PresetBundle(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetBundle::full_sla_config(), Slic3r::PresetCollection::get_differed_values_to_update(), Slic3r::PresetCollection::get_preset_differed_for_save(), Slic3r::PresetCollection::get_preset_parent(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::is_compatible_with_parent_printer(), Slic3r::PresetCollection::load_user_preset(), and Slic3r::PresetCollection::save_current_preset().
is_custom_defined()
bool Slic3r::Preset::is_custom_defined ()
{
    if (custom_defined == "1")
        return true;
    return false;
}
References custom_defined.
Referenced by Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::save_user_presets(), and Slic3r::GUI::GUI_App::sync_preset().
is_user()
bool Slic3r::Preset::is_user () const inline
{ return ! this->is_default && ! this->is_system && ! this->is_project_embedded; }
References is_project_embedded.
Referenced by Slic3r::PresetCollection::get_user_presets(), save(), Slic3r::PresetCollection::save_user_presets(), Slic3r::GUI::Tab::select_preset(), and Slic3r::GUI::GUI_App::sync_preset().
label()
std::string Slic3r::Preset::label (bool no_alias) const
{
    return (this->is_dirty ? g_suffix_modified : "")
        + ((no_alias || this->alias.empty()) ? this->name : this->alias);
}
References alias, is_dirty, and name.
Referenced by Slic3r::GUI::PlaterPresetComboBox::get_preset_name(), Slic3r::GUI::TabPresetComboBox::get_preset_name(), and Slic3r::GUI::TabPresetComboBox::update_dirty().
load_info()
void Slic3r::Preset::load_info (const std::string & file)
{
    try {
        boost::property_tree::ptree tree;
        boost::nowide::ifstream ifs(file);
        boost::property_tree::read_ini(ifs, tree);
        if (tree.empty()) return;
        for (const boost::property_tree::ptree::value_type &v : tree) {
            if (v.first.compare("sync_info") == 0)
                this->sync_info = v.second.get_value<std::string>();
            else if (v.first.compare("user_id") == 0)
                this->user_id = v.second.get_value<std::string>();
            else if (v.first.compare("setting_id") == 0) {
                this->setting_id = v.second.get_value<std::string>();
                if (this->setting_id.compare("null") == 0)
                    this->setting_id.clear();
            }
            else if (v.first.compare("base_id") == 0) {
                this->base_id = v.second.get_value<std::string>();
                if (this->base_id.compare("null") == 0)
                    this->base_id.clear();
            }
            else if (v.first.compare("updated_time") == 0) {
                std::string time = v.second.get_value<std::string>();
                this->updated_time = std::atoll(time.c_str());
            }
        }
    }
    catch (...) {
        return;
    }
    //TODO: workaround for current info file convert, will remove it later
    if (this->updated_time == 0) {
        this->updated_time = (long long)Slic3r::Utils::get_current_time_utc();
        //this->sync_info = "update";
        BOOST_LOG_TRIVIAL(info) << boost::format("old info file, updated time to %1%") % this->updated_time;
        save_info();
    }
}
References base_id, file, Slic3r::Utils::get_current_time_utc(), long, save_info(), setting_id, sync_info, updated_time, and user_id.
Referenced by Slic3r::PresetCollection::load_presets().
machine_limits_options()
const std::vector< std::string > & Slic3r::Preset::machine_limits_options () static
{ return s_Preset_machine_limits_options; }
References Slic3r::s_Preset_machine_limits_options.
normalize()
void Slic3r::Preset::normalize (DynamicPrintConfig & config) static
{
    // BBS
    auto* filament_diameter = dynamic_cast<const ConfigOptionFloats*>(config.option("filament_diameter"));
    if (filament_diameter != nullptr)
        // Loaded the FFF Printer settings. Verify, that all extruder dependent values have enough values.
        config.set_num_filaments((unsigned int)filament_diameter->values.size());
    if (config.option("filament_diameter") != nullptr) {
        // This config contains single or multiple filament presets.
        // Ensure that the filament preset vector options contain the correct number of values.
        // BBS
        size_t n = (filament_diameter == nullptr) ? 1 : filament_diameter->values.size();
        const auto &defaults = FullPrintConfig::defaults();
        for (const std::string &key : Preset::filament_options()) {
            if (key == "compatible_prints" || key == "compatible_printers")
                continue;
            auto *opt = config.option(key, false);
            /*assert(opt != nullptr);
            assert(opt->is_vector());*/
            if (opt != nullptr && opt->is_vector())
                static_cast<ConfigOptionVectorBase*>(opt)->resize(n, defaults.option(key));
        }
        // The following keys are mandatory for the UI, but they are not part of FullPrintConfig, therefore they are handled separately.
        for (const std::string &key : { "filament_settings_id" }) {
            auto *opt = config.option(key, false);
            assert(opt == nullptr || opt->type() == coStrings);
            if (opt != nullptr && opt->type() == coStrings)
                static_cast<ConfigOptionStrings*>(opt)->values.resize(n, std::string());
        }
    }
    handle_legacy_sla(config);
}
References config, Slic3r::coStrings, filament_options(), Slic3r::handle_legacy_sla(), n, Slic3r::ConfigBase::option(), Slic3r::ConfigOptionVector< T >::resize(), Slic3r::ConfigOptionVectorBase::resize(), and Slic3r::DynamicPrintConfig::set_num_filaments().
Referenced by Slic3r::PresetBundle::import_presets(), Slic3r::PresetBundle::load_config_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::load_user_preset(), and Slic3r::PresetBundle::load_vendor_configs_from_json().
nozzle_options()
const std::vector< std::string > & Slic3r::Preset::nozzle_options () static
{ return print_config_def.extruder_option_keys(); }
References Slic3r::PrintConfigDef::extruder_option_keys(), and Slic3r::print_config_def.
Referenced by printer_options().
operator<()
bool Slic3r::Preset::operator< (const Preset & other) const inline
{ return this->name < other.name; }
References name.
print_options()
const std::vector< std::string > & Slic3r::Preset::print_options () static
{ return s_Preset_print_options; }
References Slic3r::s_Preset_print_options.
Referenced by Slic3r::CLI::run().
printer_options()
const std::vector< std::string > & Slic3r::Preset::printer_options () static
{
    static std::vector<std::string> s_opts = [](){
        std::vector<std::string> opts = s_Preset_printer_options;
        append(opts, s_Preset_machine_limits_options);
        append(opts, Preset::nozzle_options());
        return opts;
    }();
    return s_opts;
}
References Slic3r::append(), nozzle_options(), Slic3r::s_Preset_machine_limits_options, and Slic3r::s_Preset_printer_options.
printer_technology() [1/2]
PrinterTechnology Slic3r::Preset::printer_technology () const inline
{ return Preset::printer_technology(this->config); }
References printer_technology().
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::GUI::Plater::priv::load_files(), printer_technology(), Slic3r::GUI::PhysicalPrinterDialog::update(), and Slic3r::PresetBundle::validate_printers().
printer_technology() [2/2]
static PrinterTechnology Slic3r::Preset::printer_technology (const DynamicPrintConfig & cfg) inline static
{
        auto *opt = cfg.option<ConfigOptionEnum<PrinterTechnology>>("printer_technology");
        // The following assert may trigger when importing some legacy profile,
        // but it is safer to keep it here to capture the cases where the "printer_technology" key is queried, where it should not.
//        assert(opt != nullptr);
        return (opt == nullptr) ? ptFFF : opt->value;
    }
References Slic3r::ConfigBase::option(), and Slic3r::ptFFF.
Referenced by Slic3r::GUI::TabPrinter::apply_extruder_cnt_from_cache(), Slic3r::GUI::GUI_App::apply_keeped_preset_modifications(), Slic3r::GUI::TabPrinter::build(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::TabPrinter::cache_extruder_cnt(), Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes(), Slic3r::GUI::Tab::compatible_widget_create(), Slic3r::PresetBundle::export_selections(), Slic3r::GUI::GUI_App::extruders_cnt(), Slic3r::GUI::GUI_App::extruders_edited_cnt(), Slic3r::PresetBundle::full_config(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::GUI::GUI_App::get_selected_presets(), Slic3r::GUI::GUI_App::has_current_preset_changes(), Slic3r::GUI::GUI_App::has_unsaved_preset_changes(), Slic3r::GUI::Tab::load_current_preset(), Slic3r::GUI::GUI_App::load_current_presets(), Slic3r::PresetBundle::load_selections(), Slic3r::GUI::Plater::merge(), Slic3r::GUI::Plater::segment(), Slic3r::GUI::Tab::select_preset(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabFilament::update(), Slic3r::GUI::TabPrinter::update(), Slic3r::GUI::TabSLAMaterial::update(), Slic3r::GUI::TabSLAPrint::update(), Slic3r::GUI::PresetComboBox::update(), Slic3r::GUI::Sidebar::update_all_preset_comboboxes(), Slic3r::GUI::DiffPresetDialog::update_compatibility(), Slic3r::PresetBundle::update_compatible(), Slic3r::PresetBundle::update_multi_material_filament_presets(), Slic3r::GUI::TabPrinter::update_pages(), Slic3r::GUI::Sidebar::update_presets(), Slic3r::GUI::GUI_App::update_saved_preset_from_current_preset(), and Slic3r::GUI::DiffPresetDialog::update_tree().
printer_technology_ref()
PrinterTechnology & Slic3r::Preset::printer_technology_ref () inline
{ return this->config.option<ConfigOptionEnum<PrinterTechnology>>("printer_technology", true)->value; }
References Slic3r::ConfigBase::option().
remove_files()
void Slic3r::Preset::remove_files ()
{
    //BBS: add project embedded preset logic
    if (this->is_project_embedded)
        return;
    // Erase the preset file.
    boost::nowide::remove(this->file.c_str());
    fs::path idx_path(this->file);
    idx_path.replace_extension(".info");
    if (fs::exists(idx_path))
        boost::nowide::remove(idx_path.string().c_str());
}
References file, and is_project_embedded.
Referenced by Slic3r::PresetCollection::delete_current_preset(), Slic3r::PresetCollection::delete_preset(), and Slic3r::PresetCollection::reset().
remove_invalid_keys()
std::string Slic3r::Preset::remove_invalid_keys (DynamicPrintConfig & config, const DynamicPrintConfig & default_config) static
{
    std::string incorrect_keys;
    for (const std::string &key : config.keys())
        if (! default_config.has(key)) {
            if (incorrect_keys.empty())
                incorrect_keys = key;
            else {
                incorrect_keys += ", ";
                incorrect_keys += key;
            }
            config.erase(key);
        }
    return incorrect_keys;
}
References config, Slic3r::DynamicConfig::erase(), Slic3r::ConfigOptionResolver::has(), and Slic3r::DynamicConfig::keys().
Referenced by Slic3r::PresetBundle::import_presets(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::load_user_preset(), and Slic3r::PresetBundle::load_vendor_configs_from_json().
remove_suffix_modified()
std::string Slic3r::Preset::remove_suffix_modified (const std::string & name) static
{
    return boost::algorithm::starts_with(name, g_suffix_modified) ?
        name.substr(g_suffix_modified.size()) :
        name;
}
References Slic3r::g_suffix_modified, and name.
Referenced by Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::PhysicalPrinter::get_preset_name(), Slic3r::GUI::Plater::priv::on_select_preset(), Slic3r::PresetCollection::select_preset_by_name(), Slic3r::PresetBundle::set_filament_preset(), Slic3r::GUI::PresetComboBox::update_ams_color(), and Slic3r::GUI::TabPresetComboBox::update_dirty().
reset_dirty()
void Slic3r::Preset::reset_dirty () inline
{ this->is_dirty = false; }
save()
void Slic3r::Preset::save (DynamicPrintConfig * parent_config)
{
    //BBS: add project embedded preset logic
    if (this->is_project_embedded)
        return;
    //BBS: change to json format
    //this->config.save(this->file);
    std::string from_str;
    if (this->is_user())
        from_str = std::string("User");
    else if (this->is_project_embedded)
        from_str = std::string("Project");
    else if (this->is_system)
        from_str = std::string("System");
    else
        from_str = std::string("Default");
    //BBS: only save difference if it has parent
    if (parent_config) {
        DynamicPrintConfig temp_config;
        std::vector<std::string> dirty_options = config.diff(*parent_config);
        for (auto option: dirty_options)
        {
            ConfigOption *opt_src = config.option(option);
            ConfigOption *opt_dst = temp_config.option(option, true);
            opt_dst->set(opt_src);
        }
        temp_config.save_to_json(this->file, this->name, from_str, this->version.to_string(), this->custom_defined);
    }
    else
        this->config.save_to_json(this->file, this->name, from_str, this->version.to_string(), this->custom_defined);
    fs::path idx_file(this->file);
    idx_file.replace_extension(".info");
    this->save_info(idx_file.string());
}
References config, custom_defined, Slic3r::DynamicConfig::diff(), file, is_project_embedded, is_system, is_user(), name, Slic3r::ConfigBase::option(), save_info(), Slic3r::ConfigBase::save_to_json(), Slic3r::ConfigOption::set(), Slic3r::Semver::to_string(), and version.
Referenced by Slic3r::PresetBundle::import_presets(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::save_current_preset(), and Slic3r::PresetCollection::save_user_presets().
save_info()
void Slic3r::Preset::save_info (std::string file = "")
{
    //BBS: add project embedded preset logic
    if (this->is_project_embedded)
        return;
    if (file.empty()) {
        fs::path idx_file(this->file);
        idx_file.replace_extension(".info");
        file = idx_file.string();
    }
    boost::nowide::ofstream c;
    c.open(file, std::ios::out | std::ios::trunc);
    std::string sync_info_to_save;
    //BBS: hold is used for stop requesting to server this time
    if (this->sync_info.compare("hold") != 0)
        sync_info_to_save = this->sync_info;
    c << "sync_info" << " = " << sync_info_to_save << std::endl;
    c << "user_id" << " = " << this->user_id << std::endl;
    c << "setting_id" << " = " << this->setting_id << std::endl;
    c << "base_id" << " = " << this->base_id << std::endl;
    c << "updated_time" << " = " << std::to_string(this->updated_time) << std::endl;
    c.close();
}
References base_id, file, is_project_embedded, setting_id, sync_info, updated_time, and user_id.
Referenced by load_info(), save(), Slic3r::GUI::Tab::save_preset(), and Slic3r::PresetCollection::set_sync_info_and_save().
set_dirty() [1/2]
void Slic3r::Preset::set_dirty (bool dirty = true) inline
{ this->is_dirty = dirty; }
set_dirty() [2/2]
void Slic3r::Preset::set_dirty (const DynamicPrintConfig & config) inline
{ this->is_dirty = ! this->config.diff(config).empty(); }
References config, and Slic3r::DynamicConfig::diff().
set_num_extruders()
void Slic3r::Preset::set_num_extruders (unsigned int n) inline
{ this->config.set_num_extruders(n); }
References n, and Slic3r::DynamicPrintConfig::set_num_extruders().
Referenced by Slic3r::GUI::TabPrinter::apply_extruder_cnt_from_cache(), and Slic3r::GUI::TabPrinter::extruders_count_changed().
set_visible_from_appconfig()
void Slic3r::Preset::set_visible_from_appconfig (const AppConfig & app_config)
{
    //BBS: add config related log
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": name %1%, is_visible %2%")%name % is_visible;
    if (vendor == nullptr) { return; }
    if (type == TYPE_PRINTER) {
        const std::string &model = config.opt_string("printer_model");
        const std::string &variant = config.opt_string("printer_variant");
        if (model.empty() || variant.empty())
          return;
        is_visible = app_config.get_variant(vendor->id, model, variant);
    } else if (type == TYPE_FILAMENT || type == TYPE_SLA_MATERIAL) {
      const std::string &section_name = (type == TYPE_FILAMENT) ? AppConfig::SECTION_FILAMENTS : AppConfig::SECTION_MATERIALS;
      if (app_config.has_section(section_name)) {
            // Check whether this profile is marked as "installed" in PrusaSlicer.ini,
        // or whether a profile is marked as "installed", which this profile may have been renamed from.
        const std::map<std::string, std::string> &installed = app_config.get_section(section_name);
        auto has = [&installed](const std::string &name) {
          auto it = installed.find(name);
        return it != installed.end() && ! it->second.empty();
        };
        is_visible = has(this->name);
        for (auto it = this->renamed_from.begin(); ! is_visible && it != this->renamed_from.end(); ++ it)
          is_visible = has(*it);
      }
    }
    //BBS: add config related log
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": name %1%, is_visible set to %2%")%name % is_visible;
}
References config, Slic3r::AppConfig::get_section(), Slic3r::AppConfig::get_variant(), Slic3r::AppConfig::has_section(), Slic3r::VendorProfile::id, is_visible, name, Slic3r::DynamicConfig::opt_string(), renamed_from, Slic3r::AppConfig::SECTION_FILAMENTS, Slic3r::AppConfig::SECTION_MATERIALS, type, TYPE_FILAMENT, TYPE_PRINTER, TYPE_SLA_MATERIAL, and vendor.
sla_material_options()
const std::vector< std::string > & Slic3r::Preset::sla_material_options () static
{ return s_Preset_sla_material_options; }
References Slic3r::s_Preset_sla_material_options.
sla_print_options()
const std::vector< std::string > & Slic3r::Preset::sla_print_options () static
{ return s_Preset_sla_print_options; }
References Slic3r::s_Preset_sla_print_options.
sla_printer_options()
const std::vector< std::string > & Slic3r::Preset::sla_printer_options () static
{ return s_Preset_sla_printer_options; }
References Slic3r::s_Preset_sla_printer_options.
suffix_modified()
const std::string & Slic3r::Preset::suffix_modified () static
{
    return g_suffix_modified;
}
References Slic3r::g_suffix_modified.
Referenced by Slic3r::GUI::PlaterPresetComboBox::switch_to_tab().
update_suffix_modified()
void Slic3r::Preset::update_suffix_modified (const std::string & new_suffix_modified) static
{
    g_suffix_modified = new_suffix_modified;
}
References Slic3r::g_suffix_modified.
Referenced by Slic3r::GUI::GUI_App::load_language().
Friends And Related Symbol Documentation
PresetBundle
friend class PresetBundle friend
PresetCollection
friend class PresetCollection friend
Member Data Documentation
alias
std::string Slic3r::Preset::alias
Referenced by Slic3r::GUI::Materials::get_printer_counter(), label(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::PresetCollection::save_current_preset(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::PresetBundle::update_compatible(), Slic3r::GUI::PageMaterials::update_lists(), Slic3r::PresetCollection::update_map_alias_to_profile_name(), and Slic3r::GUI::ConfigWizard::priv::update_materials().
base_id
std::string Slic3r::Preset::base_id
Referenced by Slic3r::PresetCollection::get_differed_values_to_update(), Slic3r::PresetBundle::import_presets(), load_info(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetCollection::save_current_preset(), save_info(), Slic3r::PresetCollection::save_user_presets(), and Slic3r::GUI::GUI_App::sync_preset().
config
DynamicPrintConfig Slic3r::Preset::config
Referenced by Slic3r::PresetBundle::PresetBundle(), Slic3r::PresetCollection::PresetCollection(), Slic3r::_BBS_3MF_Exporter::_add_project_embedded_presets_to_archive(), Slic3r::_BBS_3MF_Importer::_extract_project_embedded_presets_from_archive(), Slic3r::GUI::TabPrinter::build(), Slic3r::GUI::TabPrinter::build_fff(), Slic3r::GUI::TabPrinter::cache_extruder_cnt(), Slic3r::GUI::Bed3D::detect_type(), Slic3r::PresetCollection::dirty_options(), Slic3r::PresetCollection::dirty_options_without_option_list(), Slic3r::GUI::GUI_App::extruders_cnt(), Slic3r::GUI::GUI_App::extruders_edited_cnt(), Slic3r::PrinterPresetCollection::find_system_preset_by_model_and_variant(), Slic3r::GUI::Plater::force_filament_colors_update(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetBundle::full_sla_config(), Slic3r::GUI::PresetComboBox::get_bmp(), get_current_printer_type(), get_default_bed_type(), Slic3r::PresetCollection::get_differed_values_to_update(), Slic3r::GUI::Materials::get_filament_type(), get_filament_type(), Slic3r::GUI::Materials::get_filament_vendor(), Slic3r::GUI::Materials::get_material_type(), Slic3r::GUI::Materials::get_material_vendor(), Slic3r::PresetCollection::get_preset_differed_for_save(), get_printer_type(), Slic3r::GUI::PresetComboBox::get_tooltip(), has_lidar(), Slic3r::PresetBundle::import_presets(), inherits(), Slic3r::GUI::GCodeViewer::init(), Slic3r::is_compatible_with_parent_printer(), Slic3r::is_compatible_with_print(), Slic3r::is_compatible_with_printer(), Slic3r::is_compatible_with_printer(), Slic3r::PresetCollection::is_dirty(), Slic3r::GUI::is_support_filament(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::GUI::Tab::load_current_preset(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::GUI::MainFrame::load_printer_url(), Slic3r::PhysicalPrinterCollection::load_printers_from_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetBundle::load_selections(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::GUI::Tab::may_discard_current_dirty_preset(), normalize(), remove_invalid_keys(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::PresetBundle::reset_project_embedded_presets(), Slic3r::CLI::run(), save(), Slic3r::PresetBundle::save_changes_for_preset(), Slic3r::PresetCollection::save_current_preset(), Slic3r::PresetCollection::save_user_presets(), Slic3r::GUI::Tab::select_preset(), Slic3r::GUI::Plater::set_bed_shape(), Slic3r::PresetBundle::set_calibrate_printer(), set_dirty(), Slic3r::GUI::TabPrintModel::set_model_config(), set_visible_from_appconfig(), Slic3r::PresetUtils::system_printer_model(), Slic3r::GUI::anonymous_namespace{HintNotification.cpp}::tag_check_material(), Slic3r::GUI::TabFilament::toggle_options(), Slic3r::GUI::TabSLAMaterial::toggle_options(), Slic3r::GUI::ConfigManipulation::toggle_print_fff_options(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::Sidebar::update_all_preset_comboboxes(), Slic3r::GUI::PresetComboBox::update_ams_color(), Slic3r::PresetBundle::update_compatible(), Slic3r::PresetCollection::update_compatible_internal(), Slic3r::PhysicalPrinter::update_from_preset(), Slic3r::PresetBundle::update_multi_material_filament_presets(), Slic3r::GUI::Sidebar::update_presets(), and Slic3r::GUI::DiffPresetDialog::update_tree().
custom_defined
std::string Slic3r::Preset::custom_defined
Referenced by is_custom_defined(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_presets(), and save().
filament_id
std::string Slic3r::Preset::filament_id
Referenced by Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::load_user_preset(), and Slic3r::PresetBundle::load_vendor_configs_from_json().
file
std::string Slic3r::Preset::file
Referenced by Slic3r::_BBS_3MF_Exporter::_add_project_embedded_presets_to_archive(), Slic3r::_BBS_3MF_Importer::_extract_project_embedded_presets_from_archive(), Slic3r::PresetBundle::import_presets(), Slic3r::PresetCollection::load_external_preset(), load_info(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), remove_files(), save(), Slic3r::PresetCollection::save_current_preset(), save_info(), and Slic3r::PresetCollection::save_user_presets().
ini_str
std::string Slic3r::Preset::ini_str
is_compatible
bool Slic3r::Preset::is_compatible = true
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::GUI::SavePresetDialog::Item::update(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), Slic3r::GUI::PresetComboBox::update(), Slic3r::PresetBundle::update_compatible(), Slic3r::PresetCollection::update_compatible_internal(), and Slic3r::GUI::PhysicalPrinterDialog::update_preset_input().
is_default
bool Slic3r::Preset::is_default = false
Referenced by Slic3r::GUI::SavePresetDialog::Item::Item(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::Tab::compatible_widget_create(), Slic3r::PresetCollection::delete_current_preset(), Slic3r::PresetCollection::delete_preset(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetCollection::get_differed_values_to_update(), Slic3r::PresetCollection::get_preset_differed_for_save(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::is_compatible_with_print(), Slic3r::is_compatible_with_printer(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::merge_presets(), Slic3r::PresetCollection::reset(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::PresetCollection::save_current_preset(), Slic3r::PresetCollection::select_preset(), Slic3r::GUI::SavePresetDialog::Item::update(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), Slic3r::GUI::PresetComboBox::update(), Slic3r::GUI::Tab::update_btns_enabling(), Slic3r::PresetBundle::update_compatible(), Slic3r::GUI::Tab::update_preset_description_line(), Slic3r::GUI::PhysicalPrinterDialog::update_preset_input(), Slic3r::GUI::Tab::update_ui_items_related_on_parent_preset(), and Slic3r::PresetCollection::update_vendor_ptrs_after_copy().
is_dirty
bool Slic3r::Preset::is_dirty = false
Referenced by Slic3r::_BBS_3MF_Importer::_extract_project_embedded_presets_from_archive(), label(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::select_preset(), Slic3r::GUI::TabPrint::update(), and Slic3r::PresetCollection::update_dirty().
is_external
bool Slic3r::Preset::is_external = false
Referenced by Slic3r::_BBS_3MF_Importer::_extract_project_embedded_presets_from_archive(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::PresetBundle::import_presets(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::merge_presets(), Slic3r::PresetCollection::reset(), Slic3r::PresetCollection::save_current_preset(), Slic3r::PresetBundle::update_compatible(), and Slic3r::PresetCollection::update_vendor_ptrs_after_copy().
is_project_embedded
bool Slic3r::Preset::is_project_embedded = false
Referenced by Slic3r::GUI::SavePresetDialog::Item::Item(), Slic3r::_BBS_3MF_Importer::_extract_project_embedded_presets_from_archive(), Slic3r::PresetCollection::get_differed_values_to_update(), Slic3r::PresetCollection::get_project_embedded_presets(), is_user(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_project_embedded_presets(), remove_files(), Slic3r::CLI::run(), save(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::PresetCollection::save_current_preset(), save_info(), Slic3r::GUI::Tab::select_preset(), Slic3r::GUI::SavePresetDialog::Item::update(), Slic3r::GUI::PlaterPresetComboBox::update(), and Slic3r::GUI::TabPresetComboBox::update().
is_system
bool Slic3r::Preset::is_system = false
Referenced by Slic3r::GUI::SavePresetDialog::Item::Item(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::PresetCollection::delete_current_preset(), Slic3r::PresetCollection::delete_preset(), Slic3r::GUI::Bed3D::detect_type(), Slic3r::PrinterPresetCollection::find_system_preset_by_model_and_variant(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetCollection::get_differed_values_to_update(), Slic3r::PresetCollection::get_preset_differed_for_save(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::GUI::GCodeViewer::init(), Slic3r::is_compatible_with_printer(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetBundle::load_installed_filaments(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::PresetCollection::reset(), save(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::PresetCollection::save_current_preset(), Slic3r::PresetCollection::select_preset(), Slic3r::GUI::Plater::set_bed_shape(), Slic3r::PresetCollection::system_preset_names(), Slic3r::GUI::SavePresetDialog::Item::update(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), Slic3r::GUI::TabPrint::update(), Slic3r::GUI::PresetComboBox::update(), Slic3r::GUI::Tab::update_btns_enabling(), Slic3r::GUI::Tab::update_preset_description_line(), and Slic3r::GUI::PhysicalPrinterDialog::update_preset_input().
is_visible
bool Slic3r::Preset::is_visible = true
Referenced by Slic3r::GUI::PresetComboBox::add_ams_filaments(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::save_current_preset(), set_visible_from_appconfig(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update().
key_values
std::map<std::string, std::string> Slic3r::Preset::key_values
loaded
bool Slic3r::Preset::loaded = false
Referenced by Slic3r::_BBS_3MF_Importer::_extract_project_embedded_presets_from_archive(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), and Slic3r::PresetCollection::load_user_preset().
loading_substitutions
ConfigSubstitutions* Slic3r::Preset::loading_substitutions {nullptr}
Referenced by Slic3r::_BBS_3MF_Importer::_extract_project_embedded_presets_from_archive(), and Slic3r::PresetCollection::load_project_embedded_presets().
name
std::string Slic3r::Preset::name
Referenced by Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::SavePresetDialog::Item::Item(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::_BBS_3MF_Exporter::_add_project_embedded_presets_to_archive(), Slic3r::GUI::SavePresetDialog::Item::accept(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::Tab::compatible_widget_create(), Slic3r::GUI::Tab::delete_preset(), Slic3r::PresetBundle::export_current_configs(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetCollection::get_differed_values_to_update(), Slic3r::GUI::PresetComboBox::get_preset_name(), Slic3r::PresetCollection::get_selected_preset_name(), Slic3r::GUI::PresetComboBox::get_tooltip(), Slic3r::is_compatible_with_print(), Slic3r::is_compatible_with_printer(), Slic3r::is_compatible_with_printer(), Slic3r::PresetBundle::is_the_only_edited_filament(), label(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::PhysicalPrinterCollection::load_printers_from_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetBundle::load_selections(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetBundle::load_user_presets(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::GUI::ConfigWizard::priv::load_vendors(), Slic3r::PresetCollection::merge_presets(), operator<(), remove_suffix_modified(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::PresetBundle::reset_project_embedded_presets(), Slic3r::CLI::run(), save(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::PresetCollection::save_current_preset(), Slic3r::GUI::Tab::save_preset(), Slic3r::PresetCollection::save_user_presets(), Slic3r::PresetCollection::select_preset(), Slic3r::GUI::Tab::select_preset(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::PresetBundle::set_calibrate_printer(), Slic3r::PresetCollection::set_sync_info_and_save(), set_visible_from_appconfig(), Slic3r::GUI::GUI_App::sync_preset(), Slic3r::PresetCollection::system_preset_names(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::UnsavedChangesDialog::update(), Slic3r::GUI::PresetComboBox::update(), Slic3r::PresetBundle::update_compatible(), Slic3r::PresetCollection::update_compatible_internal(), Slic3r::GUI::PresetComboBox::update_from_bundle(), Slic3r::PhysicalPrinter::update_from_preset(), Slic3r::GUI::PageMaterials::update_lists(), Slic3r::PresetCollection::update_map_alias_to_profile_name(), Slic3r::PresetCollection::update_map_system_profile_renamed(), Slic3r::PresetBundle::update_multi_material_filament_presets(), Slic3r::PresetBundle::update_selections(), Slic3r::PresetBundle::update_system_preset_setting_ids(), and Slic3r::GUI::DiffPresetDialog::update_tree().
renamed_from
std::vector<std::string> Slic3r::Preset::renamed_from
Referenced by Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::PresetCollection::save_current_preset(), set_visible_from_appconfig(), Slic3r::PresetCollection::system_preset_names(), and Slic3r::PresetCollection::update_map_system_profile_renamed().
setting_id
std::string Slic3r::Preset::setting_id
Referenced by Slic3r::GUI::SavePresetDialog::Item::accept(), Slic3r::PresetBundle::import_presets(), load_info(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::PresetCollection::save_current_preset(), save_info(), Slic3r::PresetCollection::save_user_presets(), Slic3r::GUI::Tab::select_preset(), Slic3r::PresetCollection::set_sync_info_and_save(), Slic3r::GUI::GUI_App::sync_preset(), and Slic3r::PresetBundle::update_system_preset_setting_ids().
sync_info
std::string Slic3r::Preset::sync_info
Referenced by Slic3r::GUI::SavePresetDialog::Item::accept(), load_info(), Slic3r::PresetCollection::load_user_preset(), save_info(), Slic3r::GUI::Tab::save_preset(), Slic3r::PresetCollection::save_user_presets(), Slic3r::PresetCollection::set_sync_info_and_save(), and Slic3r::GUI::GUI_App::sync_preset().
type
Type Slic3r::Preset::type = TYPE_INVALID
Referenced by Slic3r::_BBS_3MF_Exporter::_add_project_embedded_presets_to_archive(), Slic3r::PresetCollection::get_differed_values_to_update(), Slic3r::PresetBundle::get_differed_values_to_update(), get_iot_type_string(), Slic3r::PresetBundle::get_preset_differed_for_save(), get_type_string(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::CLI::run(), Slic3r::GUI::UnsavedChangesDialog::save(), set_visible_from_appconfig(), and Slic3r::GUI::GUI_App::sync_preset().
updated_time
long long Slic3r::Preset::updated_time {0}
Referenced by Slic3r::PresetCollection::get_differed_values_to_update(), load_info(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetCollection::save_current_preset(), and save_info().
user_id
std::string Slic3r::Preset::user_id
Referenced by load_info(), Slic3r::PresetCollection::load_user_preset(), save_info(), and Slic3r::GUI::Tab::save_preset().
vendor
const VendorProfile* Slic3r::Preset::vendor = nullptr
Referenced by Slic3r::GUI::Materials::filter_presets(), Slic3r::PresetCollection::get_preset_with_vendor_profile(), Slic3r::PresetBundle::load_installed_filaments(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::PresetCollection::merge_presets(), Slic3r::PresetCollection::save_current_preset(), set_visible_from_appconfig(), Slic3r::PresetUtils::system_printer_bed_model(), Slic3r::PresetUtils::system_printer_bed_texture(), Slic3r::PresetUtils::system_printer_hotend_model(), Slic3r::PresetUtils::system_printer_model(), Slic3r::GUI::ConfigWizard::priv::update_materials(), and Slic3r::PresetCollection::update_vendor_ptrs_after_copy().
version
Semver Slic3r::Preset::version
Referenced by Slic3r::_BBS_3MF_Exporter::_add_project_embedded_presets_to_archive(), Slic3r::_BBS_3MF_Importer::_extract_project_embedded_presets_from_archive(), Slic3r::PresetCollection::get_differed_values_to_update(), Slic3r::PresetBundle::import_presets(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetBundle::load_vendor_configs_from_json(), and save().
The documentation for this class was generated from the following files:
src/libslic3r/Preset.hpp
src/libslic3r/Preset.cpp