OrcaSlicer: Slic3r::BBLStatusBarSend Class Reference
Slic3r::BBLStatusBarSend Class Reference
#include <src/slic3r/GUI/BBLStatusBarSend.hpp>
Public Types
using CancelFn = std::function< void()>
Cancel callback function type.
Public Member Functions
BBLStatusBarSend (wxWindow *parent=nullptr, int id=-1)
~BBLStatusBarSend ()=default
int get_progress () const
void set_prog_block ()
void set_progress (int) override
int get_range () const override
void set_range (int=100) override
void clear_percent () override
void show_networking_test (wxString msg) override
void show_progress (bool)
void start_busy (int=100)
void stop_busy ()
void set_cancel_callback_fina (BBLStatusBarSend::CancelFn ccb)
bool is_busy () const
void set_cancel_callback (CancelFn=CancelFn()) override
void reset_cancel_callback ()
wxPanel * get_panel ()
bool is_english_text (wxString str)
bool format_text (wxStaticText *dc, int width, const wxString &text, wxString &multiline_text)
void set_status_text (const wxString &txt)
void set_percent_text (const wxString &txt)
void msw_rescale ()
void set_status_text (const std::string &txt)
void set_status_text (const char *txt) override
wxString get_status_text () const
void set_font (const wxFont &font)
void set_object_info (const wxString &txt)
void set_slice_info (const wxString &txt)
void show_slice_info (bool show)
bool is_slice_info_shown ()
bool update_status (wxString &msg, bool &was_cancel, int percent=-1, bool yield=true)
void reset ()
void show_cancel_button ()
void hide_cancel_button ()
void change_button_label (wxString name)
Private Attributes
wxPanel * m_self
wxGauge * m_prog
Label * m_hyperlink
Button * m_cancelbutton
wxStaticText * m_status_text
wxStaticText * m_stext_percent
wxBoxSizer * m_sizer
wxBoxSizer * m_sizer_eline
wxWindow * block_left
wxWindow * block_right
bool m_busy = false
bool m_was_cancelled = false
CancelFn m_cancel_cb
CancelFn m_cancel_cb_fina
Detailed Description
Member Typedef Documentation
CancelFn
using Slic3r::ProgressIndicator::CancelFn = std::function<void()> inherited
Cancel callback function type.
Constructor & Destructor Documentation
BBLStatusBarSend()
Slic3r::BBLStatusBarSend::BBLStatusBarSend (wxWindow * parent = nullptr, int id = -1)
 : m_self{new wxPanel(parent, id == -1 ? wxID_ANY : id)}
    , m_sizer(new wxBoxSizer(wxHORIZONTAL))
{
    m_self->SetBackgroundColour(wxColour(255,255,255));
    wxBoxSizer *m_sizer_body = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *m_sizer_bottom = new wxBoxSizer(wxHORIZONTAL);
    m_status_text = new wxStaticText(m_self, wxID_ANY, wxEmptyString);
    m_status_text->SetForegroundColour(wxColour(107, 107, 107));
    m_status_text->SetFont(::Label::Body_13);
    m_status_text->SetSize(wxSize(m_self->FromDIP(300), m_self->FromDIP(46)));
    m_status_text->SetMaxSize(wxSize(m_self->FromDIP(300), m_self->FromDIP(46)));
    m_prog = new wxGauge(m_self, wxID_ANY, 100, wxDefaultPosition, wxSize(-1, m_self->FromDIP(6)), wxGA_HORIZONTAL);
    m_prog->SetMinSize(wxSize(m_self->FromDIP(300),m_self->FromDIP(6)));
    m_prog->SetValue(0);
    StateColor btn_bd_white(std::pair<wxColour, int>(*wxWHITE, StateColor::Disabled), std::pair<wxColour, int>(wxColour(38, 46, 48), StateColor::Enabled));
    m_cancelbutton = new Button(m_self, _L("Cancel"));
    m_cancelbutton->SetMinSize(wxSize(m_self->FromDIP(58), m_self->FromDIP(22)));
    m_cancelbutton->SetMaxSize(wxSize(m_self->FromDIP(58), m_self->FromDIP(22)));
    m_cancelbutton->SetBackgroundColor(wxColour(255, 255, 255));
    m_cancelbutton->SetBorderColor(btn_bd_white);
    m_cancelbutton->SetCornerRadius(m_self->FromDIP(12));
    m_cancelbutton->Bind(wxEVT_BUTTON,
        [this](wxCommandEvent &evt) {
        m_was_cancelled = true;
        if (m_cancel_cb_fina)
            m_cancel_cb_fina();
    });
    m_stext_percent = new wxStaticText(m_self, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, 0);
    m_stext_percent->SetForegroundColour(wxColour(107, 107, 107));
    m_stext_percent->SetFont(::Label::Body_13);
    m_stext_percent->Wrap(-1);
    m_hyperlink = new Label(m_self, _L("Check the status of current system services"));
    m_hyperlink->SetForegroundColour(0x00AE42);
    m_hyperlink->SetFont(::Label::Body_12);
    m_hyperlink->Hide();
    m_sizer_bottom->Add(m_prog, 1, wxALIGN_CENTER, 0);
    m_sizer_bottom->Add(m_stext_percent, 0, wxALIGN_CENTER | wxLEFT | wxRIGHT, 10);
    m_sizer_bottom->Add(m_hyperlink, 0, wxALIGN_CENTER, 10);
    m_sizer_bottom->Add(0, 0, 1, wxEXPAND, 0);
    m_sizer_bottom->Add(m_cancelbutton, 0, wxALIGN_CENTER, 0);
    m_sizer_body->Add(m_status_text, 0, wxALL, 0);
    m_sizer_body->Add(0, 0, 0, wxTOP, 1);
    m_sizer_body->Add(m_sizer_bottom, 1, wxEXPAND, 0);
    m_sizer->Add(m_sizer_body, 1, wxALIGN_CENTER, 0);
    m_self->SetSizer(m_sizer);
    m_self->Layout();
    m_sizer->Fit(m_self);
    //set_prog_block();
}
References _L, Label::Body_12, Label::Body_13, StateColor::Disabled, StateColor::Enabled, m_cancel_cb_fina, m_cancelbutton, m_hyperlink, m_prog, m_self, m_sizer, m_status_text, m_stext_percent, m_was_cancelled, StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), StaticBox::SetCornerRadius(), Button::SetMinSize(), wxEVT_BUTTON, wxGauge, and wxStaticText.
~BBLStatusBarSend()
Slic3r::BBLStatusBarSend::~BBLStatusBarSend () default
Member Function Documentation
change_button_label()
void Slic3r::BBLStatusBarSend::change_button_label (wxString name)
{
    m_cancelbutton->SetLabel(name);
}
References m_cancelbutton, and Button::SetLabel().
clear_percent()
void Slic3r::BBLStatusBarSend::clear_percent () override virtual
Implements Slic3r::ProgressIndicator.
{
    //set_percent_text(wxEmptyString);
    m_cancelbutton->Hide();
}
References m_cancelbutton.
format_text()
bool Slic3r::BBLStatusBarSend::format_text (wxStaticText * dc, int width, const wxString & text, wxString & multiline_text)
{
    bool multiline = false;
    multiline_text = text;
    if (width > 0 && dc->GetTextExtent(text).x > width) {
        size_t start = 0;
        while (true) {
            size_t idx = size_t(-1);
            for (size_t i = start; i < multiline_text.Len(); i++) {
                if (multiline_text[i] == ' ') {
                    if (dc->GetTextExtent(multiline_text.SubString(start, i)).x < width)
                        idx = i;
                    else {
                        if (idx == size_t(-1)) idx = i;
                        break;
                    }
                }
            }
            if (idx == size_t(-1)) break;
            multiline = true;
            multiline_text[idx] = '\n';
            start = idx + 1;
            if (dc->GetTextExtent(multiline_text.Mid(start)).x < width) break;
        }
    }
    return multiline;
    //return dc->GetTextExtent(multiline_text);
}
References start.
Referenced by set_status_text().
get_panel()
wxPanel * Slic3r::BBLStatusBarSend::get_panel ()
{
    return m_self;
}
References m_self.
get_progress()
int Slic3r::BBLStatusBarSend::get_progress () const
{
    return m_prog->GetValue();
}
References m_prog.
get_range()
int Slic3r::BBLStatusBarSend::get_range () const override virtual
Implements Slic3r::ProgressIndicator.
{
    return m_prog->GetRange();
}
References m_prog.
get_status_text()
wxString Slic3r::BBLStatusBarSend::get_status_text () const
{
    return m_status_text->GetLabelText();
}
References m_status_text.
hide_cancel_button()
void Slic3r::BBLStatusBarSend::hide_cancel_button ()
{
    m_sizer->Hide(m_cancelbutton);
    m_sizer->Layout();
}
References m_cancelbutton, and m_sizer.
Referenced by stop_busy().
is_busy()
bool Slic3r::BBLStatusBarSend::is_busy () const inline
{ return m_busy; }
References m_busy.
is_english_text()
bool Slic3r::BBLStatusBarSend::is_english_text (wxString str)
{
    std::regex reg("^[0-9a-zA-Z]+$");
    std::smatch matchResult;
    std::string pattern_Special = "{}[]<>~!@#$%^&*(),.?/ :";
    for (auto i = 0; i < str.Length(); i++) {
        std::string regex_str = wxString(str[i]).ToStdString();
        if (std::regex_match(regex_str, matchResult, reg)) {
            continue;
        }
        else {
            int result = pattern_Special.find(regex_str.c_str());
            if (result < 0 || result > pattern_Special.length()) {
                return false;
            }
        }
    }
    return true;
}
is_slice_info_shown()
bool Slic3r::BBLStatusBarSend::is_slice_info_shown ()
msw_rescale()
void Slic3r::BBLStatusBarSend::msw_rescale ()
{
    //set_prog_block();
    m_cancelbutton->SetMinSize(wxSize(m_self->FromDIP(56), m_self->FromDIP(24)));
}
References m_cancelbutton, m_self, and Button::SetMinSize().
reset()
void Slic3r::BBLStatusBarSend::reset ()
{
    m_hyperlink->Hide();
    m_prog->Show();
    m_stext_percent->Show();
    m_cancelbutton->Show();
    m_was_cancelled = false;
    set_status_text("");
    set_progress(0);
    set_percent_text(wxString::Format("%d%%", 0));
}
References m_cancelbutton, m_hyperlink, m_prog, m_stext_percent, m_was_cancelled, set_percent_text(), set_progress(), and set_status_text().
reset_cancel_callback()
void Slic3r::BBLStatusBarSend::reset_cancel_callback () inline
{ set_cancel_callback(); }
References set_cancel_callback().
set_cancel_callback()
void Slic3r::BBLStatusBarSend::set_cancel_callback (BBLStatusBarSend::CancelFn ccb = CancelFn()) override virtual
Implements Slic3r::ProgressIndicator.
{
    /*  m_cancel_cb = ccb;
      if (ccb) {
          m_sizer->Show(m_cancelbutton);
      }
      else {
          m_sizer->Hide(m_cancelbutton);
      }
      m_sizer->Layout();*/
}
Referenced by reset_cancel_callback().
set_cancel_callback_fina()
void Slic3r::BBLStatusBarSend::set_cancel_callback_fina (BBLStatusBarSend::CancelFn ccb)
{
    m_cancel_cb_fina = ccb;
     if (ccb) {
        m_sizer->Show(m_cancelbutton);
    } else {
        m_sizer->Hide(m_cancelbutton);
    }
}
References m_cancel_cb_fina, m_cancelbutton, and m_sizer.
set_font()
void Slic3r::BBLStatusBarSend::set_font (const wxFont & font)
{
    m_self->SetFont(font);
}
References m_self.
set_object_info()
void Slic3r::BBLStatusBarSend::set_object_info (const wxString & txt)
set_percent_text()
void Slic3r::BBLStatusBarSend::set_percent_text (const wxString & txt)
{
    m_stext_percent->SetLabelText(txt);
}
References m_stext_percent.
Referenced by reset(), and set_progress().
set_prog_block()
void Slic3r::BBLStatusBarSend::set_prog_block ()
{
    //block_left->SetPosition(wxPoint(0, 0));
    //block_right->SetPosition(wxPoint(m_prog->GetSize().GetWidth() - 2, 0));
}
set_progress()
void Slic3r::BBLStatusBarSend::set_progress (int val) override virtual
Implements Slic3r::ProgressIndicator.
{
    //set_prog_block();
    if(val < 0)
        return;
    //add the logic for arrange/orient jobs, which don't call stop_busy
    if (!m_prog->IsShown()) {
        m_sizer->Show(m_prog);
        m_sizer->Show(m_cancelbutton);
    }
    m_prog->SetValue(val);
    set_percent_text(wxString::Format("%d%%", val));
    m_sizer->Layout();
}
References m_cancelbutton, m_prog, m_sizer, and set_percent_text().
Referenced by reset(), and update_status().
set_range()
void Slic3r::BBLStatusBarSend::set_range (int val = 100) override virtual
Implements Slic3r::ProgressIndicator.
{
    if(val != m_prog->GetRange()) {
        m_prog->SetRange(val);
    }
}
References m_prog.
set_slice_info()
void Slic3r::BBLStatusBarSend::set_slice_info (const wxString & txt)
set_status_text() [1/3]
void Slic3r::BBLStatusBarSend::set_status_text (const char * txt) override virtual
Implements Slic3r::ProgressIndicator.
{
    this->set_status_text(wxString::FromUTF8(txt));
}
References set_status_text().
set_status_text() [2/3]
void Slic3r::BBLStatusBarSend::set_status_text (const std::string & txt)
{
    this->set_status_text(txt.c_str());
}
References set_status_text().
set_status_text() [3/3]
void Slic3r::BBLStatusBarSend::set_status_text (const wxString & txt)
{
    //auto txtss = "Sending the printing task has timed out.\nPlease try again!";
    //auto txtss = "The printing project is being uploaded... 25%%";
    //m_status_text->SetLabelText(txtss);
    wxString str;
    format_text(m_status_text, m_self->FromDIP(300), txt, str);
    m_status_text->SetLabelText(str);
    m_self->Layout();
    //if (is_english_text(str)) m_status_text->Wrap(m_self->FromDIP(280));
}
References format_text(), m_self, and m_status_text.
Referenced by reset(), set_status_text(), set_status_text(), show_networking_test(), and update_status().
show_cancel_button()
void Slic3r::BBLStatusBarSend::show_cancel_button ()
{
    m_sizer->Show(m_cancelbutton);
    m_sizer->Layout();
}
References m_cancelbutton, and m_sizer.
Referenced by start_busy().
show_networking_test()
void Slic3r::BBLStatusBarSend::show_networking_test (wxString msg) override virtual
Implements Slic3r::ProgressIndicator.
{
    std::string url;
    std::string country_code = Slic3r::GUI::wxGetApp().app_config->get_country_code();
    if (country_code == "US") {
        url = "https://status.bambulab.com";
    }
    else if (country_code == "CN") {
        url = "https://status.bambulab.cn";
    }
    else if (country_code == "ENV_CN_DEV") {
        url = "https://status.bambu-lab.com";
    }
    else if (country_code == "ENV_CN_QA") {
        url = "https://status.bambu-lab.com";
    }
    else if (country_code == "ENV_CN_PRE") {
        url = "https://status.bambu-lab.com";
    }
    else {
        url = "https://status.bambu-lab.com";
    }
    m_hyperlink->Bind(wxEVT_LEFT_DOWN, [this, url](auto& e) {
        wxLaunchDefaultBrowser(url);
    });
    m_hyperlink->Bind(wxEVT_ENTER_WINDOW, [this, url](auto& e) {
        m_hyperlink->SetCursor(wxCURSOR_HAND);
    });
    m_hyperlink->Bind(wxEVT_LEAVE_WINDOW, [this, url](auto& e) {
        m_hyperlink->SetCursor(wxCURSOR_ARROW);
    });
    set_status_text(msg);
    m_prog->Hide();
    m_stext_percent->Hide();
    m_hyperlink->Show();
    m_cancelbutton->Show();
    m_self->Layout();
    m_sizer->Layout();
}
References m_cancelbutton, m_hyperlink, m_prog, m_self, m_sizer, m_stext_percent, and set_status_text().
show_progress()
void Slic3r::BBLStatusBarSend::show_progress (bool show)
{
    if (show) {
        m_sizer->Show(m_prog);
        m_sizer->Layout();
    }
    else {
        m_sizer->Hide(m_prog);
        m_sizer->Layout();
    }
}
References m_prog, and m_sizer.
Referenced by start_busy(), and stop_busy().
show_slice_info()
void Slic3r::BBLStatusBarSend::show_slice_info (bool show)
start_busy()
void Slic3r::BBLStatusBarSend::start_busy (int rate = 100)
{
    m_busy = true;
    show_progress(true);
    show_cancel_button();
}
References m_busy, show_cancel_button(), and show_progress().
stop_busy()
void Slic3r::BBLStatusBarSend::stop_busy ()
{
    show_progress(false);
    hide_cancel_button();
    m_prog->SetValue(0);
    m_sizer->Layout();
    m_busy = false;
}
References hide_cancel_button(), m_busy, m_prog, m_sizer, and show_progress().
update_status()
bool Slic3r::BBLStatusBarSend::update_status (wxString & msg, bool & was_cancel, int percent = -1, bool yield = true)
{
    //auto test_txt = _L("Unkown Error.") + _L("status=150, body=Timeout was reached: Connection timed out after 10009 milliseconds [Error 28]");
    set_status_text(msg);
    if (percent >= 0)
        this->set_progress(percent);
    if (yield)
        wxEventLoopBase::GetActive()->YieldFor(wxEVT_CATEGORY_UI | wxEVT_CATEGORY_USER_INPUT);
    was_cancel = m_was_cancelled;
    return true;
}
References m_was_cancelled, set_progress(), and set_status_text().
Member Data Documentation
block_left
wxWindow* Slic3r::BBLStatusBarSend::block_left private
block_right
wxWindow* Slic3r::BBLStatusBarSend::block_right private
m_busy
bool Slic3r::BBLStatusBarSend::m_busy = false private
Referenced by is_busy(), start_busy(), and stop_busy().
m_cancel_cb
CancelFn Slic3r::BBLStatusBarSend::m_cancel_cb private
m_cancel_cb_fina
CancelFn Slic3r::BBLStatusBarSend::m_cancel_cb_fina private
Referenced by BBLStatusBarSend(), and set_cancel_callback_fina().
m_cancelbutton
Button* Slic3r::BBLStatusBarSend::m_cancelbutton private
Referenced by BBLStatusBarSend(), change_button_label(), clear_percent(), hide_cancel_button(), msw_rescale(), reset(), set_cancel_callback_fina(), set_progress(), show_cancel_button(), and show_networking_test().
m_hyperlink
Label* Slic3r::BBLStatusBarSend::m_hyperlink private
Referenced by BBLStatusBarSend(), reset(), and show_networking_test().
m_prog
wxGauge* Slic3r::BBLStatusBarSend::m_prog private
Referenced by BBLStatusBarSend(), get_progress(), get_range(), reset(), set_progress(), set_range(), show_networking_test(), show_progress(), and stop_busy().
m_self
wxPanel* Slic3r::BBLStatusBarSend::m_self private
Referenced by BBLStatusBarSend(), get_panel(), msw_rescale(), set_font(), set_status_text(), and show_networking_test().
m_sizer
wxBoxSizer* Slic3r::BBLStatusBarSend::m_sizer private
Referenced by BBLStatusBarSend(), hide_cancel_button(), set_cancel_callback_fina(), set_progress(), show_cancel_button(), show_networking_test(), show_progress(), and stop_busy().
m_sizer_eline
wxBoxSizer* Slic3r::BBLStatusBarSend::m_sizer_eline private
m_status_text
wxStaticText* Slic3r::BBLStatusBarSend::m_status_text private
Referenced by BBLStatusBarSend(), get_status_text(), and set_status_text().
m_stext_percent
wxStaticText* Slic3r::BBLStatusBarSend::m_stext_percent private
Referenced by BBLStatusBarSend(), reset(), set_percent_text(), and show_networking_test().
m_was_cancelled
bool Slic3r::BBLStatusBarSend::m_was_cancelled = false private
Referenced by BBLStatusBarSend(), reset(), and update_status().
The documentation for this class was generated from the following files:
src/slic3r/GUI/BBLStatusBarSend.hpp
src/slic3r/GUI/BBLStatusBarSend.cpp