OrcaSlicer: src/qhull/src/qhalf/qhalf_r.c File Reference
qhalf_r.c File Reference
#include "libqhull_r/libqhull_r.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <math.h>
Functions
int isatty (int)
int main (int argc, char *argv[])
Variables
char hidden_options [] =" d n v Qbb QbB Qf Qg Qm Qr QR Qv Qx Qz TR E V Fa FA FC FD FS Ft FV Gt Q0 Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8 Q9 "
char qh_prompta []
char qh_promptb []
char qh_promptc []
char qh_promptd []
char output neighborhood of facet n Pp do not report precision problems n n list of all options n one line descriptions of all options n V version n
char qh_prompt2 []
char qh_prompt3 []
Function Documentation
isatty()
int isatty (int)
Referenced by main().
main()
int main (int argc, char * argv[])
{
  int curlong, totlong; /* used !qh_NOmem */
  int exitcode, numpoints, dim;
  coordT *points;
  boolT ismalloc;
  qhT qh_qh;
  qhT *qh= &qh_qh;
  QHULL_LIB_CHECK /* Check for compatible library */
  if ((argc == 1) && isatty( 0 /*stdin*/)) {
    fprintf(stdout, qh_prompt2, qh_version);
    exit(qh_ERRnone);
  }
  if (argc > 1 && *argv[1] == '-' && !*(argv[1]+1)) {
    fprintf(stdout, qh_prompta, qh_version,
        qh_promptb, qh_promptc, qh_promptd, qh_prompte);
    exit(qh_ERRnone);
  }
  if (argc > 1 && *argv[1] == '.' && !*(argv[1]+1)) {
    fprintf(stdout, qh_prompt3, qh_version);
    exit(qh_ERRnone);
  }
  if (argc > 1 && *argv[1] == '-' && *(argv[1]+1)=='V') {
      fprintf(stdout, "%s\n", qh_version2);
      exit(qh_ERRnone);
  }
  qh_init_A(qh, stdin, stdout, stderr, argc, argv);  /* sets qh->qhull_command */
  exitcode= setjmp(qh->errexit); /* simple statement for CRAY J916 */
  if (!exitcode) {
    qh->NOerrexit = False;
    qh_option(qh, "Halfspace", NULL, NULL);
    qh->HALFspace= True;    /* 'H'   */
    qh_checkflags(qh, qh->qhull_command, hidden_options);
    qh_initflags(qh, qh->qhull_command);
    if (qh->SCALEinput) {
      fprintf(qh->ferr, "\
qhull error: options 'Qbk:n' and 'QBk:n' are not used with qhalf.\n\
             Use 'Qbk:0Bk:0 to drop dimension k.\n");
      qh_errexit(qh, qh_ERRinput, NULL, NULL);
    }
    points= qh_readpoints(qh, &numpoints, &dim, &ismalloc);
    if (dim >= 5) {
      qh_option(qh, "Qxact_merge", NULL, NULL);
      qh->MERGEexact= True; /* 'Qx' always */
    }
    qh_init_B(qh, points, numpoints, dim, ismalloc);
    qh_qhull(qh);
    qh_check_output(qh);
    qh_produce_output(qh);
    if (qh->VERIFYoutput && !qh->FORCEoutput && !qh->STOPpoint && !qh->STOPcone)
      qh_check_points(qh);
    exitcode= qh_ERRnone;
  }
  qh->NOerrexit= True;  /* no more setjmp */
#ifdef qh_NOmem
  qh_freeqhull(qh, qh_ALL);
#else
  qh_freeqhull(qh, !qh_ALL);
  qh_memfreeshort(qh, &curlong, &totlong);
  if (curlong || totlong)
    qh_fprintf_stderr(6263, "qhull internal warning (main): did not free %d bytes of long memory(%d pieces)\n",
       totlong, curlong);
#endif
  return exitcode;
} /* main */
References boolT, coordT, False, hidden_options, isatty(), NULL, qh, qh_ALL, qh_check_output(), qh_check_points(), qh_checkflags(), qh_errexit(), qh_ERRinput, qh_ERRnone, qh_fprintf_stderr(), qh_freeqhull(), qh_init_A(), qh_init_B(), qh_initflags(), qh_memfreeshort(), qh_option(), qh_produce_output(), qh_prompt2, qh_prompt3, qh_prompta, qh_promptb, qh_promptc, qh_promptd, qh_qh, qh_qhull(), qh_readpoints(), qh_version, qh_version2, QHULL_LIB_CHECK, and True.
Variable Documentation
hidden_options
char hidden_options[] =" d n v Qbb QbB Qf Qg Qm Qr QR Qv Qx Qz TR E V Fa FA FC FD FS Ft FV Gt Q0 Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8 Q9 "
Referenced by main().
n
char output neighborhood of facet n Pp do not report precision problems n n list of all options n one line descriptions of all options n V version n
qh_prompt2
char qh_prompt2[]
Referenced by main().
qh_prompt3
char qh_prompt3[]
Initial value:
= "\n\
Qhull %s.\n\
Except for 'F.' and 'PG', upper_case options take an argument.\n\
\n\
 incidences     Geomview       mathematica    OFF_format     point_dual\n\
 summary        facet_dump\n\
\n\
 Fc_redundant   Fd_cdd_in      FF_dump_xridge FIDs           Fmerges\n\
 Fneighbors     FN_intersect   FOptions       Fp_coordinates FP_nearest\n\
 FQhalf         Fsummary       Fv_halfspace   FMaple         Fx_non_redundant\n\
\n\
 Gvertices      Gpoints        Gall_points    Gno_planes     Ginner\n\
 Gcentrums      Ghyperplanes   Gridges        Gouter         GDrop_dim\n\
\n\
 PArea_keep     Pdrop d0:0D0   Pgood          PFacet_area_keep\n\
 PGood_neighbors PMerge_keep   Poutput_forced Pprecision_not\n\
\n\
 Qbk:0Bk:0_drop Qcoplanar      QG_half_good   Qi_redundant   QJoggle\n\
 Qsearch_1st    Qtriangulate   QVertex_good\n\
\n\
 T4_trace       Tcheck_often   Tstatistics    Tverify        Tz_stdout\n\
 TFacet_log     TInput_file    TPoint_trace   TMerge_trace   TOutput_file\n\
 TWide_trace    TVertex_stop   TCone_stop\n\
\n\
 Angle_max      Centrum_size   Random_dist    Ucoplanar_max  Wide_outside\n\
"
Referenced by main().
qh_prompta
char qh_prompta[]
Initial value:
= "\n\
qhalf- compute the intersection of halfspaces about a point\n\
    http://www.qhull.org  %s\n\
\n\
input (stdin):\n\
    optional interior point: dimension, 1, coordinates\n\
    first lines: dimension+1 and number of halfspaces\n\
    other lines: halfspace coefficients followed by offset\n\
    comments:    start with a non-numeric character\n\
\n\
options:\n\
    Hn,n - specify coordinates of interior point\n\
    Qt   - triangulated output\n\
    QJ   - joggled input instead of merged facets\n\
    Qc   - keep coplanar halfspaces\n\
    Qi   - keep other redundant halfspaces\n\
\n\
Qhull control options:\n\
    QJn  - randomly joggle input in range [-n,n]\n\
%s%s%s%s"
Referenced by main().
qh_promptb
char qh_promptb[]
Initial value:
= "\
    Qbk:0Bk:0 - remove k-th coordinate from input\n\
    Qs   - search all halfspaces for the initial simplex\n\
    QGn  - print intersection if visible to halfspace n, -n for not\n\
    QVn  - print intersections for halfspace n, -n if not\n\
\n\
"
Referenced by main().
qh_promptc
char qh_promptc[]
Referenced by main().
qh_promptd
char qh_promptd[]
Referenced by main().