OrcaSlicer: Slic3r::DeviceManager Class Reference
Slic3r::DeviceManager Class Reference
#include <src/slic3r/GUI/DeviceManager.hpp>
Public Member Functions
DeviceManager (NetworkAgent *agent=nullptr)
~DeviceManager ()
void set_agent (NetworkAgent *agent)
void check_pushing ()
MachineObject * get_default_machine ()
MachineObject * get_local_selected_machine ()
MachineObject * get_local_machine (std::string dev_id)
MachineObject * get_user_machine (std::string dev_id)
MachineObject * get_my_machine (std::string dev_id)
void erase_user_machine (std::string dev_id)
void clean_user_info ()
bool set_selected_machine (std::string dev_id, bool need_disconnect=false)
MachineObject * get_selected_machine ()
std::map< std::string, MachineObject * > get_my_machine_list ()
std::string get_first_online_user_machine ()
void modify_device_name (std::string dev_id, std::string dev_name)
void update_user_machine_list_info ()
void parse_user_print_info (std::string body)
void on_machine_alive (std::string json_str)
void disconnect_all ()
int query_bind_status (std::string &msg)
std::map< std::string, MachineObject * > get_local_machine_list ()
void load_last_machine ()
Static Public Member Functions
static std::string parse_printer_type (std::string type_str)
static std::string get_printer_display_name (std::string type_str)
static std::string get_printer_thumbnail_img (std::string type_str)
static std::string get_ftp_folder (std::string type_str)
static bool is_function_supported (std::string type_str, std::string function_name)
static std::vector< std::string > get_resolution_supported (std::string type_str)
static bool get_bed_temperature_limit (std::string type_str, int &limit)
static bool load_functional_config (std::string config_file)
static bool load_filaments_blacklist_config (std::string config_file)
static void check_filaments_in_blacklist (std::string tag_vendor, std::string tag_type, bool &in_blacklist, std::string &ac, std::string &info)
static std::string load_gcode (std::string type_str, std::string gcode_file)
Public Attributes
std::mutex listMutex
std::string selected_machine
std::string local_selected_machine
std::map< std::string, MachineObject * > localMachineList
std::map< std::string, MachineObject * > userMachineList
Static Public Attributes
static json function_table = json::object()
static json filaments_blacklist = json::object()
Private Attributes
NetworkAgent * m_agent { nullptr }
Detailed Description
Constructor & Destructor Documentation
DeviceManager()
Slic3r::DeviceManager::DeviceManager (NetworkAgent * agent = nullptr)
{
    m_agent = agent;
}
References m_agent.
~DeviceManager()
Slic3r::DeviceManager::~DeviceManager ()
{
    for (auto it = localMachineList.begin(); it != localMachineList.end(); it++) {
        if (it->second) {
            delete it->second;
            it->second = nullptr;
        }
    }
    localMachineList.clear();
    for (auto it = userMachineList.begin(); it != userMachineList.end(); it++) {
        if (it->second) {
            delete it->second;
            it->second = nullptr;
        }
    }
    userMachineList.clear();
}
References localMachineList, and userMachineList.
Member Function Documentation
check_filaments_in_blacklist()
void Slic3r::DeviceManager::check_filaments_in_blacklist (std::string tag_vendor, std::string tag_type, bool & in_blacklist, std::string & ac, std::string & info) static
{
    in_blacklist = false;
    if (filaments_blacklist.contains("blacklist")) {
        for (auto prohibited_filament : filaments_blacklist["blacklist"]) {
            std::string vendor;
            std::string type;
            std::string action;
            std::string description;
            if (prohibited_filament.contains("vendor") &&
                prohibited_filament.contains("type") &&
                prohibited_filament.contains("action") &&
                prohibited_filament.contains("description"))
            {
                vendor = prohibited_filament["vendor"].get<std::string>();
                type = prohibited_filament["type"].get<std::string>();
                action = prohibited_filament["action"].get<std::string>();
                description = prohibited_filament["description"].get<std::string>();
            }
            else {
                return;
            }
            std::transform(vendor.begin(), vendor.end(), vendor.begin(), ::tolower);
            std::transform(tag_vendor.begin(), tag_vendor.end(), tag_vendor.begin(), ::tolower);
            std::transform(tag_type.begin(), tag_type.end(), tag_type.begin(), ::tolower);
            std::transform(type.begin(), type.end(), type.begin(), ::tolower);
            //third party
            if (vendor == "third party") {
                if ("bambulab" != vendor && tag_type == type) {
                    in_blacklist = true;
                    ac = action;
                    info = description;
                    return;
                }
            }
            else {
                if (vendor == tag_vendor && tag_type == type) {
                    in_blacklist = true;
                    ac = action;
                    info = description;
                    return;
                }
            }
        }
    }
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), and filaments_blacklist.
Referenced by Slic3r::GUI::AMSMaterialsSetting::on_select_ok().
check_pushing()
void Slic3r::DeviceManager::check_pushing ()
{
    MachineObject* obj = this->get_selected_machine();
    if (obj) {
        std::chrono::system_clock::time_point start = std::chrono::system_clock::now();
        auto internal = std::chrono::duration_cast<std::chrono::milliseconds>(start - obj->last_update_time);
        if (internal.count() > TIMEOUT_FOR_STRAT && internal.count() < 1000 * 60 * 60 * 300) {
            BOOST_LOG_TRIVIAL(info) << "command_pushing: diff = " << internal.count();
            obj->command_pushing("start");
        }
    }
}
References Slic3r::MachineObject::command_pushing(), get_selected_machine(), Slic3r::MachineObject::last_update_time, start, and TIMEOUT_FOR_STRAT.
Referenced by Slic3r::GUI::MonitorPanel::update_all(), and Slic3r::GUI::SelectMachineDialog::update_show_status().
clean_user_info()
void Slic3r::DeviceManager::clean_user_info ()
{
    BOOST_LOG_TRIVIAL(trace) << "DeviceManager::clean_user_info";
    // reset selected_machine
    selected_machine = "";
    local_selected_machine = "";
    // clean access code
    for (auto it = userMachineList.begin(); it != userMachineList.end(); it++) {
        it->second->set_access_code("");
    }
    // clean user list
    for (auto it = userMachineList.begin(); it != userMachineList.end(); it++) {
        if (it->second) {
            delete it->second;
            it->second = nullptr;
        }
    }
    userMachineList.clear();
}
References local_selected_machine, selected_machine, Slic3r::trace(), and userMachineList.
Referenced by Slic3r::GUI::GUI_App::request_user_logout().
disconnect_all()
void Slic3r::DeviceManager::disconnect_all ()
{
}
erase_user_machine()
void Slic3r::DeviceManager::erase_user_machine (std::string dev_id)
{
    userMachineList.erase(dev_id);
}
References userMachineList.
Referenced by Slic3r::GUI::UnBindMachineDialog::on_unbind_printer().
get_bed_temperature_limit()
bool Slic3r::DeviceManager::get_bed_temperature_limit (std::string type_str, int & limit) static
{
    bool result = false;
    if (DeviceManager::function_table.contains("printers")) {
        for (auto printer : DeviceManager::function_table["printers"]) {
            if (printer.contains("model_id") && printer["model_id"].get<std::string>() == type_str) {
                if (printer.contains("bed_temperature_limit")) {
                    limit = printer["bed_temperature_limit"].get<int>();
                    return true;
                }
            }
        }
    }
    return result;
}
References Slic3r::contains(), and function_table.
Referenced by Slic3r::MachineObject::get_bed_temperature_limit().
get_default_machine()
MachineObject * Slic3r::DeviceManager::get_default_machine ()
{
    std::string dev_id;
    if (m_agent) {
        m_agent->get_user_selected_machine();
    }
    if (dev_id.empty()) return nullptr;
    auto it = userMachineList.find(dev_id);
    if (it == userMachineList.end()) return nullptr;
    return it->second;
}
References Slic3r::NetworkAgent::get_user_selected_machine(), m_agent, and userMachineList.
Referenced by Slic3r::GUI::UpgradePanel::Show().
get_first_online_user_machine()
std::string Slic3r::DeviceManager::get_first_online_user_machine ()
{
    for (auto it = userMachineList.begin(); it != userMachineList.end(); it++) {
        if (it->second && it->second->is_online()) {
            return it->second->dev_id;
        }
    }
    return "";
}
References userMachineList.
Referenced by Slic3r::GUI::MonitorPanel::update_side_panel().
get_ftp_folder()
std::string Slic3r::DeviceManager::get_ftp_folder (std::string type_str) static
{
    if (DeviceManager::function_table.contains("printers")) {
        for (auto printer : DeviceManager::function_table["printers"]) {
            if (printer.contains("model_id") && printer["model_id"].get<std::string>() == type_str) {
                if (printer.contains("ftp_folder")) {
                    return printer["ftp_folder"].get<std::string>();
                }
            }
        }
    }
    return "";
}
References Slic3r::contains(), and function_table.
Referenced by Slic3r::MachineObject::get_ftp_folder().
get_local_machine()
MachineObject * Slic3r::DeviceManager::get_local_machine (std::string dev_id)
{
    if (dev_id.empty()) return nullptr;
    auto it = localMachineList.find(dev_id);
    if (it == localMachineList.end()) return nullptr;
    return it->second;
}
References localMachineList.
Referenced by get_local_selected_machine(), and Slic3r::GUI::UnBindMachineDialog::on_unbind_printer().
get_local_machine_list()
std::map< std::string, MachineObject * > Slic3r::DeviceManager::get_local_machine_list ()
{
    std::map<std::string, MachineObject*> result;
    std::map<std::string, MachineObject*>::iterator it;
    for (it = localMachineList.begin(); it != localMachineList.end(); it++) {
        if (it->second->m_is_online) {
            result.insert(std::make_pair(it->first, it->second));
        }
    }
    return result;
}
References localMachineList.
Referenced by Slic3r::GUI::SelectMachineDialog::update_lan_machine_list(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), and Slic3r::GUI::SelectMachineDialog::update_user_printer().
get_local_selected_machine()
MachineObject * Slic3r::DeviceManager::get_local_selected_machine ()
{
    return get_local_machine(local_selected_machine);
}
References get_local_machine(), and local_selected_machine.
get_my_machine()
MachineObject * Slic3r::DeviceManager::get_my_machine (std::string dev_id)
{
    auto list = get_my_machine_list();
    auto it = list.find(dev_id);
    if (it != list.end()) {
        return it->second;
    }
    return nullptr;
}
References get_my_machine_list().
Referenced by Slic3r::GUI::GUI_App::init_networking_callbacks(), Slic3r::GUI::MonitorPanel::update_all(), Slic3r::GUI::SelectMachineDialog::update_show_status(), and Slic3r::GUI::SendToPrinterDialog::update_show_status().
get_my_machine_list()
std::map< std::string, MachineObject * > Slic3r::DeviceManager::get_my_machine_list ()
{
    std::map<std::string, MachineObject*> result;
    for (auto it = userMachineList.begin(); it != userMachineList.end(); it++) {
        if (!it->second)
            continue;
        if (!it->second->is_lan_mode_printer())
            result.insert(std::make_pair(it->first, it->second));
    }
    for (auto it = localMachineList.begin(); it != localMachineList.end(); it++) {
        if (!it->second)
            continue;
        if (it->second->has_access_right() && it->second->is_avaliable() && it->second->is_lan_mode_printer()) {
            // remove redundant in userMachineList
            if (result.find(it->first) == result.end()) {
                result.emplace(std::make_pair(it->first, it->second));
            }
        }
    }
    return result;
}
References localMachineList, and userMachineList.
Referenced by get_my_machine(), set_selected_machine(), Slic3r::GUI::SelectMachinePopup::update_user_devices(), Slic3r::GUI::SelectMachineDialog::update_user_printer(), and Slic3r::GUI::SendToPrinterDialog::update_user_printer().
get_printer_display_name()
std::string Slic3r::DeviceManager::get_printer_display_name (std::string type_str) static
{
    if (DeviceManager::function_table.contains("printers")) {
        for (auto printer : DeviceManager::function_table["printers"]) {
            if (printer.contains("model_id") && printer["model_id"].get<std::string>() == type_str) {
                if (printer.contains("display_name")) {
                    return printer["display_name"].get<std::string>();
                }
            }
        }
    }
    return "";
}
References Slic3r::contains(), and function_table.
Referenced by Slic3r::MachineObject::get_preset_printer_model_name().
get_printer_thumbnail_img()
std::string Slic3r::DeviceManager::get_printer_thumbnail_img (std::string type_str) static
{
    if (DeviceManager::function_table.contains("printers")) {
        for (auto printer : DeviceManager::function_table["printers"]) {
            if (printer.contains("model_id") && printer["model_id"].get<std::string>() == type_str) {
                if (printer.contains("printer_thumbnail_image")) {
                    return printer["printer_thumbnail_image"].get<std::string>();
                }
            }
        }
    }
    return "";
}
References Slic3r::contains(), and function_table.
Referenced by Slic3r::MachineObject::get_preset_printer_thumbnail_img().
get_resolution_supported()
std::vector< std::string > Slic3r::DeviceManager::get_resolution_supported (std::string type_str) static
{
    std::vector<std::string> resolution_supported;
    if (DeviceManager::function_table.contains("printers")) {
        for (auto printer : DeviceManager::function_table["printers"]) {
            if (printer.contains("model_id") && printer["model_id"].get<std::string>() == type_str) {
                if (printer.contains("camera_resolution")) {
                    for (auto res : printer["camera_resolution"])
                        resolution_supported.emplace_back(res.get<std::string>());
                }
            }
        }
    }
    return resolution_supported;
}
References Slic3r::contains(), and function_table.
Referenced by Slic3r::MachineObject::get_resolution_supported().
get_selected_machine()
MachineObject * Slic3r::DeviceManager::get_selected_machine ()
{
    if (selected_machine.empty()) return nullptr;
    MachineObject* obj = get_user_machine(selected_machine);
    if (obj)
        return obj;
    // return local machine has access code
    auto it = localMachineList.find(selected_machine);
    if (it != localMachineList.end()) {
        if (it->second->has_access_right())
            return it->second;
    }
    return nullptr;
}
References get_user_machine(), localMachineList, and selected_machine.
Referenced by Slic3r::GUI::CameraPopup::check_func_supported(), check_pushing(), Slic3r::GUI::GUI_App::init_networking_callbacks(), Slic3r::GUI::MonitorPanel::init_timer(), Slic3r::GUI::SelectMachineDialog::is_same_printer_model(), Slic3r::GUI::SelectMachineDialog::on_ok(), Slic3r::GUI::SendToPrinterDialog::on_ok(), Slic3r::GUI::SelectMachineDialog::on_ok_btn(), Slic3r::GUI::MonitorPanel::on_select_printer(), Slic3r::GUI::SelectMachineDialog::popup_filament_backup(), Slic3r::GUI::SelectMachineDialog::set_default(), Slic3r::GUI::MonitorPanel::Show(), Slic3r::GUI::GUI_App::show_modal_ip_address_enter_dialog(), Slic3r::GUI::AMSLib::Update(), Slic3r::GUI::MonitorPanel::update_all(), Slic3r::GUI::SelectMachineDialog::update_user_printer(), and Slic3r::GUI::SendToPrinterDialog::update_user_printer().
get_user_machine()
MachineObject * Slic3r::DeviceManager::get_user_machine (std::string dev_id)
{
    if (!Slic3r::GUI::wxGetApp().is_user_login())
        return nullptr;
    std::map<std::string, MachineObject*>::iterator it = userMachineList.find(dev_id);
    if (it == userMachineList.end()) return nullptr;
    return it->second;
}
References userMachineList.
Referenced by get_selected_machine(), and Slic3r::GUI::GUI_App::init_networking_callbacks().
is_function_supported()
bool Slic3r::DeviceManager::is_function_supported (std::string type_str, std::string function_name) static
{
    if (DeviceManager::function_table.contains("printers")) {
        for (auto printer : DeviceManager::function_table["printers"]) {
            if (printer.contains("model_id") && printer["model_id"].get<std::string>() == type_str) {
                if (printer.contains("func")) {
                    if (printer["func"].contains(function_name))
                        return printer["func"][function_name].get<bool>();
                }
            }
        }
    }
    return true;
}
References Slic3r::contains(), and function_table.
Referenced by Slic3r::MachineObject::is_function_supported().
load_filaments_blacklist_config()
bool Slic3r::DeviceManager::load_filaments_blacklist_config (std::string config_file) static
{
    filaments_blacklist = json::object();
    std::ifstream json_file(config_file.c_str());
    try {
        if (json_file.is_open()) {
            json_file >> filaments_blacklist;
            return true;
        }
        else {
            BOOST_LOG_TRIVIAL(error) << "load filaments blacklist config failed, file = " << config_file;
        }
    }
    catch (...) {
        BOOST_LOG_TRIVIAL(error) << "load filaments blacklist config failed, file = " << config_file;
        return false;
    }
    return true;
}
References error, filaments_blacklist, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::object().
Referenced by Slic3r::GUI::GUI_App::post_init().
load_functional_config()
bool Slic3r::DeviceManager::load_functional_config (std::string config_file) static
{
    std::ifstream json_file(config_file.c_str());
    try {
        if (json_file.is_open()) {
            json_file >> DeviceManager::function_table;
            return true;
        } else {
            BOOST_LOG_TRIVIAL(error) << "load functional config failed, file = " << config_file;
        }
    }
    catch(...) {
        BOOST_LOG_TRIVIAL(error) << "load functional config failed, file = " << config_file;
        return false;
    }
    return true;
}
References error, and function_table.
Referenced by Slic3r::GUI::GUI_App::post_init().
load_gcode()
std::string Slic3r::DeviceManager::load_gcode (std::string type_str, std::string gcode_file) static
{
    std::string gcode_full_path = Slic3r::resources_dir() + "/printers/" + gcode_file;
    std::ifstream gcode(encode_path(gcode_full_path.c_str()).c_str());
    try {
        std::stringstream gcode_str;
        if (gcode.is_open()) {
            gcode_str << gcode.rdbuf();
            gcode.close();
            return gcode_str.str();
        }
    } catch(...) {
        BOOST_LOG_TRIVIAL(error) << "load gcode file failed, file = " << gcode_file << ", path = " << gcode_full_path;
    }
    return "";
}
References Slic3r::encode_path(), error, and Slic3r::resources_dir().
Referenced by Slic3r::MachineObject::command_ams_switch(), and Slic3r::MachineObject::command_unload_filament().
load_last_machine()
void Slic3r::DeviceManager::load_last_machine ()
{
    if (userMachineList.empty()) return;
    else if (userMachineList.size() == 1) {
        this->set_selected_machine(userMachineList.begin()->second->dev_id);
    } else {
        if (m_agent) {
            std::string last_monitor_machine = m_agent->get_user_selected_machine();
            bool found = false;
            for (auto it = userMachineList.begin(); it != userMachineList.end(); it++) {
                if (last_monitor_machine == it->first) {
                    this->set_selected_machine(last_monitor_machine);
                    found = true;
                }
            }
            if (!found)
                this->set_selected_machine(userMachineList.begin()->second->dev_id);
        }
    }
}
References Slic3r::NetworkAgent::get_user_selected_machine(), m_agent, set_selected_machine(), and userMachineList.
Referenced by Slic3r::GUI::MonitorPanel::Show().
modify_device_name()
void Slic3r::DeviceManager::modify_device_name (std::string dev_id, std::string dev_name)
{
    BOOST_LOG_TRIVIAL(trace) << "modify_device_name";
    if (m_agent) {
        int result = m_agent->modify_printer_name(dev_id, dev_name);
        if (result == 0) {
            update_user_machine_list_info();
        }
    }
}
References m_agent, Slic3r::NetworkAgent::modify_printer_name(), Slic3r::trace(), and update_user_machine_list_info().
Referenced by Slic3r::GUI::EditDevNameDialog::on_edit_name().
on_machine_alive()
void Slic3r::DeviceManager::on_machine_alive (std::string json_str)
{
    try {
        BOOST_LOG_TRIVIAL(trace) << "DeviceManager::SsdpDiscovery, json" << json_str;
        json j = json::parse(json_str);
        std::string dev_name        = j["dev_name"].get<std::string>();
        std::string dev_id          = j["dev_id"].get<std::string>();
        std::string dev_ip          = j["dev_ip"].get<std::string>();
        std::string printer_type_str= j["dev_type"].get<std::string>();
        std::string printer_signal  = j["dev_signal"].get<std::string>();
        std::string connect_type    = j["connect_type"].get<std::string>();
        std::string bind_state      = j["bind_state"].get<std::string>();
        std::string sec_link = "";
        if (j.contains("sec_link")) {
            sec_link = j["sec_link"].get<std::string>();
        }
        MachineObject* obj;
        /* update userMachineList info */
        auto it = userMachineList.find(dev_id);
        if (it != userMachineList.end()) {
            it->second->dev_ip          = dev_ip;
            it->second->bind_state      = bind_state;
            it->second->bind_sec_link   = sec_link;
        }
        /* update localMachineList */
        it = localMachineList.find(dev_id);
        if (it != localMachineList.end()) {
            // update properties
            /* ip changed */
            obj = it->second;
            if (obj->dev_ip.compare(dev_ip) != 0 && !obj->dev_ip.empty()) {
                BOOST_LOG_TRIVIAL(info) << "MachineObject IP changed from " << obj->dev_ip << " to " << dev_ip;
                obj->dev_ip = dev_ip;
                /* ip changed reconnect mqtt */
            }
            obj->wifi_signal        = printer_signal;
            obj->dev_connection_type= connect_type;
            obj->bind_state         = bind_state;
            obj->bind_sec_link      = sec_link;
            obj->printer_type = MachineObject::parse_printer_type(printer_type_str);
            // U0 firmware
            if (obj->dev_connection_type.empty() && obj->bind_state.empty())
                obj->bind_state = "free";
            BOOST_LOG_TRIVIAL(debug) << "SsdpDiscovery:: Update Machine Info, printer_sn = " << dev_id << ", signal = " << printer_signal;
            obj->last_alive = Slic3r::Utils::get_current_time_utc();
            obj->m_is_online = true;
            /* if (!obj->dev_ip.empty()) {
                 Slic3r::GUI::wxGetApp().app_config->set_str("ip_address", obj->dev_id, obj->dev_ip);
                 Slic3r::GUI::wxGetApp().app_config->save();
             }*/
        }
        else {
            /* insert a new machine */
            obj = new MachineObject(m_agent, dev_name, dev_id, dev_ip);
            obj->printer_type = MachineObject::parse_printer_type(printer_type_str);
            obj->wifi_signal = printer_signal;
            obj->dev_connection_type = connect_type;
            obj->bind_state     = bind_state;
            obj->bind_sec_link  = sec_link;
            //load access code
            AppConfig* config = Slic3r::GUI::wxGetApp().app_config;
            if (config) {
                obj->set_access_code(Slic3r::GUI::wxGetApp().app_config->get("access_code", dev_id));
                obj->set_user_access_code(Slic3r::GUI::wxGetApp().app_config->get("user_access_code", dev_id));
            }
            localMachineList.insert(std::make_pair(dev_id, obj));
            /* if (!obj->dev_ip.empty()) {
                 Slic3r::GUI::wxGetApp().app_config->set_str("ip_address", obj->dev_id, obj->dev_ip);
                 Slic3r::GUI::wxGetApp().app_config->save();
             }*/
            BOOST_LOG_TRIVIAL(debug) << "SsdpDiscovery::New Machine, ip = " << dev_ip << ", printer_name= " << dev_name << ", printer_type = " << printer_type_str << ", signal = " << printer_signal;
        }
    }
    catch (...) {
        ;
    }
}
References Slic3r::MachineObject::bind_sec_link, Slic3r::MachineObject::bind_state, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), Slic3r::MachineObject::dev_connection_type, Slic3r::MachineObject::dev_ip, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), Slic3r::Utils::get_current_time_utc(), Slic3r::MachineObject::last_alive, localMachineList, m_agent, Slic3r::MachineObject::m_is_online, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), Slic3r::MachineObject::parse_printer_type(), Slic3r::MachineObject::printer_type, Slic3r::MachineObject::set_access_code(), Slic3r::MachineObject::set_user_access_code(), Slic3r::trace(), userMachineList, and Slic3r::MachineObject::wifi_signal.
Referenced by Slic3r::GUI::GUI_App::post_init(), and Slic3r::GUI::GUI_App::restart_networking().
parse_printer_type()
std::string Slic3r::DeviceManager::parse_printer_type (std::string type_str) static
{
    if (DeviceManager::function_table.contains("printers")) {
        for (auto printer : DeviceManager::function_table["printers"]) {
            if (printer.contains("model_id") && printer["model_id"].get<std::string>() == type_str) {
                if (printer.contains("printer_type")) {
                    return printer["printer_type"].get<std::string>();
                }
            }
        }
    }
    return "";
}
References Slic3r::contains(), and function_table.
Referenced by Slic3r::MachineObject::parse_printer_type().
parse_user_print_info()
void Slic3r::DeviceManager::parse_user_print_info (std::string body)
{
    BOOST_LOG_TRIVIAL(trace) << "DeviceManager::parse_user_print_info";
    std::lock_guard<std::mutex> lock(listMutex);
    std::set<std::string> new_list;
    try {
        json j = json::parse(body);
        if (j.contains("devices") && !j["devices"].is_null()) {
            for (auto& elem : j["devices"]) {
                MachineObject* obj = nullptr;
                std::string dev_id;
                if (!elem["dev_id"].is_null()) {
                    dev_id = elem["dev_id"].get<std::string>();
                    new_list.insert(dev_id);
                }
                std::map<std::string, MachineObject*>::iterator iter = userMachineList.find(dev_id);
                if (iter != userMachineList.end()) {
                    /* update field */
                    obj = iter->second;
                    obj->dev_id = dev_id;
                }
                else {
                    obj = new MachineObject(m_agent, "", "", "");
                    if (m_agent) {
                        obj->set_bind_status(m_agent->get_user_name());
                    }
                    obj->dev_ip = Slic3r::GUI::wxGetApp().app_config->get("ip_address", dev_id);
                    userMachineList.insert(std::make_pair(dev_id, obj));
                }
                if (!obj) continue;
                if (!elem["dev_id"].is_null())
                    obj->dev_id = elem["dev_id"].get<std::string>();
                if (!elem["dev_name"].is_null())
                    obj->dev_name = elem["dev_name"].get<std::string>();
                if (!elem["dev_online"].is_null())
                    obj->m_is_online = elem["dev_online"].get<bool>();
                if (elem.contains("dev_model_name") && !elem["dev_model_name"].is_null())
                    obj->printer_type = elem["dev_model_name"].get<std::string>();
                if (!elem["task_status"].is_null())
                    obj->iot_print_status = elem["task_status"].get<std::string>();
                if (elem.contains("dev_product_name") && !elem["dev_product_name"].is_null())
                    obj->product_name = elem["dev_product_name"].get<std::string>();
                if (elem.contains("dev_access_code") && !elem["dev_access_code"].is_null()) {
                    std::string acc_code = elem["dev_access_code"].get<std::string>();
                    acc_code.erase(std::remove(acc_code.begin(), acc_code.end(), '\n'), acc_code.end());
                    obj->set_access_code(acc_code);
                }
            }
            //remove MachineObject from userMachineList
            std::map<std::string, MachineObject*>::iterator iterat;
            for (iterat = userMachineList.begin(); iterat != userMachineList.end(); ) {
                if (new_list.find(iterat->first) == new_list.end()) {
                    iterat = userMachineList.erase(iterat);
                }
                else {
                    iterat++;
                }
            }
        }
    }
    catch (std::exception& e) {
        ;
    }
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), Slic3r::MachineObject::dev_id, Slic3r::MachineObject::dev_ip, Slic3r::MachineObject::dev_name, Slic3r::NetworkAgent::get_user_name(), Slic3r::MachineObject::iot_print_status, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::is_null(), listMutex, m_agent, Slic3r::MachineObject::m_is_online, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), Slic3r::MachineObject::printer_type, Slic3r::MachineObject::product_name, Slic3r::MachineObject::set_access_code(), Slic3r::MachineObject::set_bind_status(), Slic3r::trace(), and userMachineList.
Referenced by Slic3r::GUI::SelectMachinePopup::update_user_devices(), update_user_machine_list_info(), Slic3r::GUI::SelectMachineDialog::update_user_printer(), and Slic3r::GUI::SendToPrinterDialog::update_user_printer().
query_bind_status()
int Slic3r::DeviceManager::query_bind_status (std::string & msg)
{
    if (!m_agent) {
        msg = "";
        return -1;
    }
    BOOST_LOG_TRIVIAL(trace) << "DeviceManager::query_bind_status";
    std::map<std::string, MachineObject*>::iterator it;
    std::vector<std::string> query_list;
    for (it = localMachineList.begin(); it != localMachineList.end(); it++) {
        query_list.push_back(it->first);
    }
    unsigned int http_code;
    std::string http_body;
    int result = m_agent->query_bind_status(query_list, &http_code, &http_body);
    if (result < 0) {
        msg = (boost::format("code=%1%,body=%2") % http_code % http_body).str();
    } else {
        msg = "";
        try {
            json j = json::parse(http_body);
            if (j.contains("bind_list")) {
                for (auto& item : j["bind_list"]) {
                    auto it = localMachineList.find(item["dev_id"].get<std::string>());
                    if (it != localMachineList.end()) {
                        if (!item["user_id"].is_null())
                            it->second->bind_user_id = item["user_id"].get<std::string>();
                        if (!item["user_name"].is_null())
                            it->second->bind_user_name = item["user_name"].get<std::string>();
                        else
                            it->second->bind_user_name = "Free";
                    }
                }
            }
        } catch(...) {
            ;
        }
    }
    return result;
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), localMachineList, m_agent, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), Slic3r::NetworkAgent::query_bind_status(), and Slic3r::trace().
set_agent()
void Slic3r::DeviceManager::set_agent (NetworkAgent * agent)
{
    m_agent = agent;
}
References m_agent.
Referenced by Slic3r::GUI::GUI_App::on_init_network().
set_selected_machine()
bool Slic3r::DeviceManager::set_selected_machine (std::string dev_id, bool need_disconnect = false)
{
    BOOST_LOG_TRIVIAL(info) << "set_selected_machine=" << dev_id;
    auto my_machine_list = get_my_machine_list();
    auto it = my_machine_list.find(dev_id);
    // disconnect last
    auto last_selected = my_machine_list.find(selected_machine);
    if (last_selected != my_machine_list.end()) {
        if (last_selected->second->connection_type() == "lan") {
            if (last_selected->second->is_connecting() && !need_disconnect)
                return false;
            if (!need_disconnect) {m_agent->disconnect_printer();}
        }
    }
    // connect curr
    if (it != my_machine_list.end()) {
        if (selected_machine == dev_id) {
            if (it->second->connection_type() != "lan") {
                // only reset update time
                it->second->reset_update_time();
                return true;
            } else {
                // lan mode printer reconnect printer
                if (m_agent) {
                    if (!need_disconnect) {m_agent->disconnect_printer();}
                    it->second->reset();
                    it->second->connect();
                    it->second->set_lan_mode_connection_state(true);
                }
            }
        } else {
            if (m_agent) {
                if (it->second->connection_type() != "lan" || it->second->connection_type().empty()) {
                    if (m_agent->get_user_selected_machine() != dev_id) {
                        BOOST_LOG_TRIVIAL(info) << "static: set_selected_machine: same dev_id = " << dev_id;
                        m_agent->set_user_selected_machine(dev_id);
                        it->second->reset();
                    } else {
                        it->second->reset_update_time();
                    }
                } else {
                    it->second->reset();
                    it->second->connect();
                    it->second->set_lan_mode_connection_state(true);
                }
            }
        }
    }
    selected_machine = dev_id;
    return true;
}
References Slic3r::NetworkAgent::disconnect_printer(), get_my_machine_list(), Slic3r::NetworkAgent::get_user_selected_machine(), m_agent, selected_machine, and Slic3r::NetworkAgent::set_user_selected_machine().
Referenced by Slic3r::GUI::GUI_App::init_networking_callbacks(), load_last_machine(), Slic3r::GUI::MonitorPanel::on_select_printer(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::SendToPrinterDialog::on_selection_changed(), Slic3r::GUI::GUI_App::on_set_selected_machine(), Slic3r::GUI::Plater::print_job_finished(), and Slic3r::GUI::MonitorPanel::update_all().
update_user_machine_list_info()
void Slic3r::DeviceManager::update_user_machine_list_info ()
{
    if (!m_agent) return;
    BOOST_LOG_TRIVIAL(debug) << "update_user_machine_list_info";
    unsigned int http_code;
    std::string body;
    int result = m_agent->get_user_print_info(&http_code, &body);
    if (result == 0) {
        parse_user_print_info(body);
    }
}
References Slic3r::NetworkAgent::get_user_print_info(), m_agent, and parse_user_print_info().
Referenced by modify_device_name(), Slic3r::GUI::GUI_App::on_user_login_handle(), and Slic3r::GUI::BindJob::process().
Member Data Documentation
filaments_blacklist
json Slic3r::DeviceManager::filaments_blacklist = json::object() static
Referenced by check_filaments_in_blacklist(), and load_filaments_blacklist_config().
function_table
json Slic3r::DeviceManager::function_table = json::object() static
Referenced by get_bed_temperature_limit(), get_ftp_folder(), get_printer_display_name(), get_printer_thumbnail_img(), get_resolution_supported(), is_function_supported(), load_functional_config(), and parse_printer_type().
listMutex
std::mutex Slic3r::DeviceManager::listMutex
Referenced by parse_user_print_info().
local_selected_machine
std::string Slic3r::DeviceManager::local_selected_machine
Referenced by clean_user_info(), and get_local_selected_machine().
localMachineList
std::map<std::string, MachineObject*> Slic3r::DeviceManager::localMachineList
Referenced by ~DeviceManager(), get_local_machine(), get_local_machine_list(), get_my_machine_list(), get_selected_machine(), on_machine_alive(), and query_bind_status().
m_agent
NetworkAgent* Slic3r::DeviceManager::m_agent { nullptr } private
Referenced by DeviceManager(), get_default_machine(), load_last_machine(), modify_device_name(), on_machine_alive(), parse_user_print_info(), query_bind_status(), set_agent(), set_selected_machine(), and update_user_machine_list_info().
selected_machine
std::string Slic3r::DeviceManager::selected_machine
Referenced by clean_user_info(), get_selected_machine(), and set_selected_machine().
userMachineList
std::map<std::string, MachineObject*> Slic3r::DeviceManager::userMachineList
Referenced by ~DeviceManager(), clean_user_info(), erase_user_machine(), get_default_machine(), get_first_online_user_machine(), get_my_machine_list(), get_user_machine(), load_last_machine(), on_machine_alive(), and parse_user_print_info().
The documentation for this class was generated from the following files:
src/slic3r/GUI/DeviceManager.hpp
src/slic3r/GUI/DeviceManager.cpp