OrcaSlicer: XML_Memory_Handling_Suite Struct Reference
XML_Memory_Handling_Suite Struct Reference
#include <src/expat/expat.h>
Public Attributes
void *(* malloc_fcn)(size_t size)
void *(* realloc_fcn)(void *ptr, size_t size)
void(* free_fcn)(void *ptr)
Detailed Description
Member Data Documentation
free_fcn
void(* XML_Memory_Handling_Suite::free_fcn) (void *ptr)
Referenced by dtdCopy(), dtdDestroy(), dtdReset(), hashTableClear(), hashTableDestroy(), lookup(), parserCreate(), and poolDestroy().
malloc_fcn
void *(* XML_Memory_Handling_Suite::malloc_fcn) (size_t size)
Referenced by dtdCopy(), dtdCreate(), lookup(), parserCreate(), and poolGrow().
realloc_fcn
void *(* XML_Memory_Handling_Suite::realloc_fcn) (void *ptr, size_t size)
Referenced by parserCreate(), and poolGrow().
The documentation for this struct was generated from the following file:
src/expat/expat.h