OrcaSlicer: Slic3r::GUI::AmsRMArrow Class Reference
Slic3r::GUI::AmsRMArrow Class Reference
#include <src/slic3r/GUI/AmsMappingPopup.hpp>
Public Member Functions
AmsRMArrow (wxWindow *parent)
~AmsRMArrow ()
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void doRender (wxDC &dc)
Private Attributes
ScalableBitmap m_bitmap_left
ScalableBitmap m_bitmap_right
ScalableBitmap m_bitmap_down
Detailed Description
Constructor & Destructor Documentation
AmsRMArrow()
Slic3r::GUI::AmsRMArrow::AmsRMArrow (wxWindow * parent)
{
    wxWindow::Create(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize);
    SetBackgroundColour(*wxWHITE);
    Bind(wxEVT_PAINT, &AmsRMArrow::paintEvent, this);
    m_bitmap_left = ScalableBitmap(this, "replace_arrow_left", 7);
    m_bitmap_right = ScalableBitmap(this, "replace_arrow_right", 7);
    m_bitmap_down = ScalableBitmap(this, "replace_arrow_down", 7);
        SetSize(wxSize(FromDIP(16), FromDIP(32)));
        SetMinSize(wxSize(FromDIP(16), FromDIP(32)));
        SetMaxSize(wxSize(FromDIP(16), FromDIP(32)));
}
References m_bitmap_down, m_bitmap_left, m_bitmap_right, and paintEvent().
~AmsRMArrow()
Slic3r::GUI::AmsRMArrow::~AmsRMArrow () inline
{};
Member Function Documentation
doRender()
void Slic3r::GUI::AmsRMArrow::doRender (wxDC & dc)
{
    wxSize size = GetSize();
    dc.SetPen(wxPen(wxColour(0, 174, 66)));
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    dc.SetPen(wxPen(wxColour(0xACACAC)));
    dc.SetBrush(wxBrush(wxColour(0xACACAC)));
    dc.DrawCircle(size.x / 2, size.y / 2, FromDIP(7));
}
References size.
Referenced by render().
paintEvent()
void Slic3r::GUI::AmsRMArrow::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    render(dc);
}
References render().
Referenced by AmsRMArrow().
render()
void Slic3r::GUI::AmsRMArrow::render (wxDC & dc)
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({ 0, 0 }, size, &dc, { 0, 0 });
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References doRender(), and size.
Referenced by paintEvent().
Member Data Documentation
m_bitmap_down
ScalableBitmap Slic3r::GUI::AmsRMArrow::m_bitmap_down private
Referenced by AmsRMArrow().
m_bitmap_left
ScalableBitmap Slic3r::GUI::AmsRMArrow::m_bitmap_left private
Referenced by AmsRMArrow().
m_bitmap_right
ScalableBitmap Slic3r::GUI::AmsRMArrow::m_bitmap_right private
Referenced by AmsRMArrow().
The documentation for this class was generated from the following files:
src/slic3r/GUI/AmsMappingPopup.hpp
src/slic3r/GUI/AmsMappingPopup.cpp