OrcaSlicer: orgQhull::QhullLinkedList< T >::iterator Class Reference
orgQhull::QhullLinkedList< T >::iterator Class Reference
#include <src/qhull/src/libqhullcpp/QhullLinkedList.h>
Public Types
typedef std::bidirectional_iterator_tag iterator_category
typedef T value_type
typedef value_type * pointer
typedef value_type & reference
typedef ptrdiff_t difference_type
Public Member Functions
iterator ()
iterator (const T &t)
Automatic conversion to iterator.
iterator (const iterator &o)
iterator & operator= (const iterator &o)
const T & operator* () const
T & operator* ()
const T * operator-> () const
T * operator-> ()
bool operator== (const iterator &o) const
bool operator!= (const iterator &o) const
bool operator== (const const_iterator &o) const
bool operator!= (const const_iterator &o) const
iterator & operator++ ()
iterator operator++ (int)
iterator & operator-- ()
iterator operator-- (int)
iterator operator- (int j) const
iterator & operator+= (int j)
iterator & operator-= (int j)
Iterator
iterator operator+ (int j) const
Private Attributes
T i
Friends
class const_iterator
Detailed Description
template<typename T>
class orgQhull::QhullLinkedList< T >::iterator
Member Typedef Documentation
difference_type
template<typename T > typedef ptrdiff_t orgQhull::QhullLinkedList< T >::iterator::difference_type
iterator_category
template<typename T > typedef std::bidirectional_iterator_tag orgQhull::QhullLinkedList< T >::iterator::iterator_category
pointer
template<typename T > typedef value_type* orgQhull::QhullLinkedList< T >::iterator::pointer
reference
template<typename T > typedef value_type& orgQhull::QhullLinkedList< T >::iterator::reference
value_type
template<typename T > typedef T orgQhull::QhullLinkedList< T >::iterator::value_type
Constructor & Destructor Documentation
iterator() [1/3]
template<typename T > orgQhull::QhullLinkedList< T >::iterator::iterator () inline
: i() {}
Referenced by orgQhull::QhullLinkedList< T >::iterator::operator+().
iterator() [2/3]
template<typename T > orgQhull::QhullLinkedList< T >::iterator::iterator (const T & t) inline
Automatic conversion to iterator.
iterator() [3/3]
template<typename T > orgQhull::QhullLinkedList< T >::iterator::iterator (const iterator & o) inline
: i(o.i) {}
Member Function Documentation
operator!=() [1/2]
template<typename T > bool orgQhull::QhullLinkedList< T >::iterator::operator!= (const const_iterator & o) const inline
{ return !operator==(o); }
References orgQhull::QhullLinkedList< T >::iterator::operator==().
operator!=() [2/2]
template<typename T > bool orgQhull::QhullLinkedList< T >::iterator::operator!= (const iterator & o) const inline
{ return !operator==(o); }
References orgQhull::QhullLinkedList< T >::iterator::operator==().
operator*() [1/2]
template<typename T > T & orgQhull::QhullLinkedList< T >::iterator::operator* () inline
{ return i; }
References orgQhull::QhullLinkedList< T >::iterator::i.
operator*() [2/2]
template<typename T > const T & orgQhull::QhullLinkedList< T >::iterator::operator* () const inline
{ return i; }
References orgQhull::QhullLinkedList< T >::iterator::i.
operator+()
template<typename T > QhullLinkedList< T >::iterator orgQhull::QhullLinkedList< T >::iterator::operator+ (int j) const
{
    T n= i;
    if(j>0){
        while(j--){
            n= n.next();
        }
    }else{
        while(j++){
            n= n.previous();
        }
    }
    return iterator(n);
}//operator+
References orgQhull::QhullLinkedList< T >::iterator::iterator(), orgQhull::QhullLinkedList< T >::iterator::i, and n.
Referenced by orgQhull::QhullLinkedList< T >::iterator::operator-().
operator++() [1/2]
template<typename T > iterator & orgQhull::QhullLinkedList< T >::iterator::operator++ () inline
{ i= i.next(); return *this; }
References orgQhull::QhullLinkedList< T >::iterator::i.
operator++() [2/2]
template<typename T > iterator orgQhull::QhullLinkedList< T >::iterator::operator++ (int) inline
{ iterator o= i; i= i.next(); return o; }
References orgQhull::QhullLinkedList< T >::iterator::i.
operator+=()
template<typename T > iterator & orgQhull::QhullLinkedList< T >::iterator::operator+= (int j) inline
{ return (*this= *this + j); }
operator-()
template<typename T > iterator orgQhull::QhullLinkedList< T >::iterator::operator- (int j) const inline
{ return operator+(-j); }
References orgQhull::QhullLinkedList< T >::iterator::operator+().
operator--() [1/2]
template<typename T > iterator & orgQhull::QhullLinkedList< T >::iterator::operator-- () inline
{ i= i.previous(); return *this; }
References orgQhull::QhullLinkedList< T >::iterator::i.
operator--() [2/2]
template<typename T > iterator orgQhull::QhullLinkedList< T >::iterator::operator-- (int) inline
{ iterator o= i; i= i.previous(); return o; }
References orgQhull::QhullLinkedList< T >::iterator::i.
operator-=()
template<typename T > iterator & orgQhull::QhullLinkedList< T >::iterator::operator-= (int j) inline
{ return (*this= *this - j); }
operator->() [1/2]
template<typename T > T * orgQhull::QhullLinkedList< T >::iterator::operator-> () inline
{ return &i; }
References orgQhull::QhullLinkedList< T >::iterator::i.
operator->() [2/2]
template<typename T > const T * orgQhull::QhullLinkedList< T >::iterator::operator-> () const inline
{ return &i; }
References orgQhull::QhullLinkedList< T >::iterator::i.
operator=()
template<typename T > iterator & orgQhull::QhullLinkedList< T >::iterator::operator= (const iterator & o) inline
{ i= o.i; return *this; }
References orgQhull::QhullLinkedList< T >::iterator::i.
operator==() [1/2]
template<typename T > bool orgQhull::QhullLinkedList< T >::iterator::operator== (const const_iterator & o) const inline
{ return i==reinterpret_cast<const iterator &>(o).i; }
References orgQhull::QhullLinkedList< T >::iterator::i.
operator==() [2/2]
template<typename T > bool orgQhull::QhullLinkedList< T >::iterator::operator== (const iterator & o) const inline
{ return i == o.i; }
References orgQhull::QhullLinkedList< T >::iterator::i.
Referenced by orgQhull::QhullLinkedList< T >::iterator::operator!=(), and orgQhull::QhullLinkedList< T >::iterator::operator!=().
Friends And Related Symbol Documentation
const_iterator
template<typename T > friend class const_iterator friend
Member Data Documentation
i
template<typename T > T orgQhull::QhullLinkedList< T >::iterator::i private
Referenced by orgQhull::QhullLinkedList< T >::iterator::operator*(), orgQhull::QhullLinkedList< T >::iterator::operator*(), orgQhull::QhullLinkedList< T >::iterator::operator+(), orgQhull::QhullLinkedList< T >::iterator::operator++(), orgQhull::QhullLinkedList< T >::iterator::operator++(), orgQhull::QhullLinkedList< T >::iterator::operator--(), orgQhull::QhullLinkedList< T >::iterator::operator--(), orgQhull::QhullLinkedList< T >::iterator::operator->(), orgQhull::QhullLinkedList< T >::iterator::operator->(), orgQhull::QhullLinkedList< T >::iterator::operator=(), orgQhull::QhullLinkedList< T >::iterator::operator==(), and orgQhull::QhullLinkedList< T >::iterator::operator==().
The documentation for this class was generated from the following file:
src/qhull/src/libqhullcpp/QhullLinkedList.h