OrcaSlicer: Slic3r::GUI::AmsMapingTipPopup Class Reference
Slic3r::GUI::AmsMapingTipPopup Class Reference
#include <src/slic3r/GUI/AmsMappingPopup.hpp>
Public Member Functions
AmsMapingTipPopup (wxWindow *parent)
~AmsMapingTipPopup ()
void paintEvent (wxPaintEvent &evt)
virtual void OnDismiss () wxOVERRIDE
virtual bool ProcessLeftDown (wxMouseEvent &event) wxOVERRIDE
bool Create (wxWindow *parent, int flags=wxBORDER_NONE)
Public Attributes
wxPanel * m_panel_enable_ams
wxStaticText * m_title_enable_ams
wxStaticText * m_tip_enable_ams
wxPanel * m_split_lines
wxPanel * m_panel_disable_ams
wxStaticText * m_title_disable_ams
wxStaticText * m_tip_disable_ams
Detailed Description
Constructor & Destructor Documentation
AmsMapingTipPopup()
Slic3r::GUI::AmsMapingTipPopup::AmsMapingTipPopup (wxWindow * parent)
    :PopupWindow(parent, wxBORDER_NONE)
{
    SetBackgroundColour(*wxWHITE);
    wxBoxSizer *m_sizer_main = new wxBoxSizer(wxVERTICAL);
    m_sizer_main->Add(0, 0, 1, wxTOP, FromDIP(28));
    wxBoxSizer *m_sizer_body = new wxBoxSizer(wxHORIZONTAL);
    m_sizer_body->Add(0, 0, 0, wxEXPAND | wxLEFT, FromDIP(20));
    m_panel_enable_ams = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(FromDIP(220), -1), wxTAB_TRAVERSAL);
    m_panel_enable_ams->SetBackgroundColour(*wxWHITE);
    wxBoxSizer *sizer_enable_ams = new wxBoxSizer(wxVERTICAL);
    m_title_enable_ams = new wxStaticText(m_panel_enable_ams, wxID_ANY, _L("Enable AMS"), wxDefaultPosition, wxDefaultSize, 0);
    m_title_enable_ams->SetForegroundColour(*wxBLACK);
    m_title_enable_ams->SetBackgroundColour(*wxWHITE);
    m_title_enable_ams->Wrap(-1);
    sizer_enable_ams->Add(m_title_enable_ams, 0, 0, 0);
    m_tip_enable_ams = new wxStaticText(m_panel_enable_ams, wxID_ANY, _L("Print with filaments in the AMS"), wxDefaultPosition, wxDefaultSize, 0);
    m_tip_enable_ams->SetMinSize(wxSize(FromDIP(200), FromDIP(50)));
    m_tip_enable_ams->Wrap(FromDIP(200));
    m_tip_enable_ams->SetForegroundColour(*wxBLACK);
    m_tip_enable_ams->SetBackgroundColour(*wxWHITE);
    sizer_enable_ams->Add(m_tip_enable_ams, 0, wxTOP, 8);
    wxBoxSizer *sizer_enable_ams_img;
    sizer_enable_ams_img = new wxBoxSizer(wxVERTICAL);
    auto img_enable_ams = new wxStaticBitmap(m_panel_enable_ams, wxID_ANY, create_scaled_bitmap("monitor_upgrade_ams", this, 108), wxDefaultPosition,
                                             wxSize(FromDIP(118), FromDIP(108)), 0);
    sizer_enable_ams_img->Add(img_enable_ams, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_enable_ams->Add(sizer_enable_ams_img, 1, wxEXPAND | wxTOP, FromDIP(20));
    m_panel_enable_ams->SetSizer(sizer_enable_ams);
    m_panel_enable_ams->Layout();
    m_sizer_body->Add(m_panel_enable_ams, 0, 0, 0);
    m_split_lines = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(1, FromDIP(150)), wxTAB_TRAVERSAL);
    m_split_lines->SetBackgroundColour(wxColour(238, 238, 238));
    m_sizer_body->Add(m_split_lines, 0, wxALIGN_CENTER_VERTICAL | wxLEFT | wxRIGHT, FromDIP(10));
    m_panel_disable_ams = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(FromDIP(220), -1), wxTAB_TRAVERSAL);
    m_panel_disable_ams->SetBackgroundColour(*wxWHITE);
    wxBoxSizer *sizer_disable_ams;
    sizer_disable_ams = new wxBoxSizer(wxVERTICAL);
    m_title_disable_ams = new wxStaticText(m_panel_disable_ams, wxID_ANY, _L("Disable AMS"), wxDefaultPosition, wxDefaultSize, 0);
    m_title_disable_ams->SetBackgroundColour(*wxWHITE);
    m_title_disable_ams->SetForegroundColour(*wxBLACK);
    m_title_disable_ams->Wrap(-1);
    sizer_disable_ams->Add(m_title_disable_ams, 0, 0, 0);
    m_tip_disable_ams = new wxStaticText(m_panel_disable_ams, wxID_ANY, _L("Print with the filament mounted on the back of chassis"), wxDefaultPosition, wxDefaultSize, 0);
    m_tip_disable_ams->SetMinSize(wxSize(FromDIP(200), FromDIP(50)));
    m_tip_disable_ams->Wrap(FromDIP(200));
    m_tip_disable_ams->SetForegroundColour(*wxBLACK);
    m_tip_disable_ams->SetBackgroundColour(*wxWHITE);
    sizer_disable_ams->Add(m_tip_disable_ams, 0, wxTOP, FromDIP(8));
    wxBoxSizer *sizer_disable_ams_img;
    sizer_disable_ams_img = new wxBoxSizer(wxVERTICAL);
    auto img_disable_ams = new wxStaticBitmap(m_panel_disable_ams, wxID_ANY, create_scaled_bitmap("disable_ams_demo_icon", this, 95), wxDefaultPosition,
                                              wxSize(FromDIP(95), FromDIP(109)), 0);
    sizer_disable_ams_img->Add(img_disable_ams, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    sizer_disable_ams->Add(sizer_disable_ams_img, 1, wxEXPAND | wxTOP, FromDIP(20));
    m_panel_disable_ams->SetSizer(sizer_disable_ams);
    m_panel_disable_ams->Layout();
    m_sizer_body->Add(m_panel_disable_ams, 0, 0, 0);
    m_sizer_body->Add(0, 0, 0, wxEXPAND | wxRIGHT, FromDIP(20));
    m_sizer_main->Add(m_sizer_body, 0, wxEXPAND, 0);
    m_sizer_main->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(28));
    this->SetSizer(m_sizer_main);
    this->Layout();
    this->Fit();
    Bind(wxEVT_PAINT, &AmsMapingTipPopup::paintEvent, this);
}
References _L, create_scaled_bitmap(), m_panel_disable_ams, m_panel_enable_ams, m_split_lines, m_tip_disable_ams, m_tip_enable_ams, m_title_disable_ams, m_title_enable_ams, paintEvent(), and wxStaticText.
~AmsMapingTipPopup()
Slic3r::GUI::AmsMapingTipPopup::~AmsMapingTipPopup () inline
{};
Member Function Documentation
Create()
bool PopupWindow::Create (wxWindow * parent, int flags = wxBORDER_NONE) inherited
{
    if (!wxPopupTransientWindow::Create(parent, style))
        return false;
#ifdef __WXGTK__
    GetTopParent(parent)->Bind(wxEVT_ACTIVATE, &PopupWindow::topWindowActiavate, this);
#endif
    return true;
}
References GetTopParent(), and style.
Referenced by PopupWindow::PopupWindow(), and DropDown::Create().
OnDismiss()
void Slic3r::GUI::AmsMapingTipPopup::OnDismiss () virtual
{}
paintEvent()
void Slic3r::GUI::AmsMapingTipPopup::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    dc.SetPen(wxColour(0xAC, 0xAC, 0xAC));
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    dc.DrawRoundedRectangle(0, 0, GetSize().x, GetSize().y, 0);
}
Referenced by AmsMapingTipPopup().
ProcessLeftDown()
bool Slic3r::GUI::AmsMapingTipPopup::ProcessLeftDown (wxMouseEvent & event) virtual
{
    return PopupWindow::ProcessLeftDown(event); }
Member Data Documentation
m_panel_disable_ams
wxPanel* Slic3r::GUI::AmsMapingTipPopup::m_panel_disable_ams
Referenced by AmsMapingTipPopup().
m_panel_enable_ams
wxPanel* Slic3r::GUI::AmsMapingTipPopup::m_panel_enable_ams
Referenced by AmsMapingTipPopup().
m_split_lines
wxPanel* Slic3r::GUI::AmsMapingTipPopup::m_split_lines
Referenced by AmsMapingTipPopup().
m_tip_disable_ams
wxStaticText* Slic3r::GUI::AmsMapingTipPopup::m_tip_disable_ams
Referenced by AmsMapingTipPopup().
m_tip_enable_ams
wxStaticText* Slic3r::GUI::AmsMapingTipPopup::m_tip_enable_ams
Referenced by AmsMapingTipPopup().
m_title_disable_ams
wxStaticText* Slic3r::GUI::AmsMapingTipPopup::m_title_disable_ams
Referenced by AmsMapingTipPopup().
m_title_enable_ams
wxStaticText* Slic3r::GUI::AmsMapingTipPopup::m_title_enable_ams
Referenced by AmsMapingTipPopup().
The documentation for this class was generated from the following files:
src/slic3r/GUI/AmsMappingPopup.hpp
src/slic3r/GUI/AmsMappingPopup.cpp