OrcaSlicer: Slic3r::GUI::ObjectLayers::PlusMinusButton Class Reference
Slic3r::GUI::ObjectLayers::PlusMinusButton Class Reference
#include <src/slic3r/GUI/GUI_ObjectLayers.hpp>
Public Member Functions
PlusMinusButton (wxWindow *parent, const ScalableBitmap &bitmap, std::pair< coordf_t, coordf_t > range)
void SetBitmap_ (const ScalableBitmap &bmp)
bool SetBitmap_ (const std::string &bmp_name)
void SetBitmapDisabled_ (const ScalableBitmap &bmp)
int GetBitmapHeight ()
void UseDefaultBitmapDisabled ()
void msw_rescale ()
Public Attributes
std::pair< coordf_t, coordf_t > range
Private Attributes
wxWindow * m_parent { nullptr }
std::string m_current_icon_name
std::string m_disabled_icon_name
int m_width {-1}
int m_height {-1}
bool m_use_default_disabled_bitmap {false}
int m_px_cnt { 16 }
bool m_has_border {false}
Detailed Description
Constructor & Destructor Documentation
PlusMinusButton()
Slic3r::GUI::ObjectLayers::PlusMinusButton::PlusMinusButton (wxWindow * parent, const ScalableBitmap & bitmap, std::pair< coordf_t, coordf_t > range) inline
: ScalableButton(parent, wxID_ANY, bitmap), range(range) {}
Member Function Documentation
GetBitmapHeight()
int ScalableButton::GetBitmapHeight () inherited
{
#ifdef __APPLE__
    return GetBitmap().GetScaledHeight();
#else
    return GetBitmap().GetHeight();
#endif
}
msw_rescale()
void ScalableButton::msw_rescale () inherited
{
    Slic3r::GUI::wxGetApp().UpdateDarkUI(this, m_has_border);
    if (!m_current_icon_name.empty()) {
        wxBitmap bmp = create_scaled_bitmap(m_current_icon_name, m_parent, m_px_cnt);
        SetBitmap(bmp);
        // BBS: why disappear on hover? why current HBITMAP differ from other
        //SetBitmapCurrent(bmp);
        //SetBitmapPressed(bmp);
        //SetBitmapFocus(bmp);
        if (!m_disabled_icon_name.empty())
            SetBitmapDisabled(create_scaled_bitmap(m_disabled_icon_name, m_parent, m_px_cnt));
        else if (m_use_default_disabled_bitmap)
            SetBitmapDisabled(create_scaled_bitmap(m_current_icon_name, m_parent, m_px_cnt, true));
    }
    if (m_width > 0 || m_height>0)
    {
        const int em = em_unit(m_parent);
        wxSize size(m_width * em, m_height * em);
        SetMinSize(size);
    }
}
References create_scaled_bitmap(), em_unit(), ScalableButton::m_current_icon_name, ScalableButton::m_disabled_icon_name, ScalableButton::m_has_border, ScalableButton::m_height, ScalableButton::m_parent, ScalableButton::m_px_cnt, ScalableButton::m_use_default_disabled_bitmap, ScalableButton::m_width, and size.
Referenced by Slic3r::GUI::ObjectLayers::msw_rescale(), Slic3r::GUI::ConfigOptionsGroup::msw_rescale(), Slic3r::GUI::ParamsPanel::msw_rescale(), Slic3r::GUI::PlaterPresetComboBox::msw_rescale(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::StatusPanel::on_sys_color_changed(), and Slic3r::GUI::ObjectLayers::sys_color_changed().
SetBitmap_() [1/2]
void ScalableButton::SetBitmap_ (const ScalableBitmap & bmp) inherited
{
    SetBitmap(bmp.bmp());
    m_current_icon_name = bmp.name();
}
References ScalableBitmap::bmp(), ScalableButton::m_current_icon_name, and ScalableBitmap::name().
Referenced by Slic3r::GUI::StatusPanel::StatusPanel(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Slic3r::GUI::StatusPanel::reset_printing_values(), and Slic3r::GUI::StatusPanel::update_subtask().
SetBitmap_() [2/2]
bool ScalableButton::SetBitmap_ (const std::string & bmp_name) inherited
{
    m_current_icon_name = bmp_name;
    if (m_current_icon_name.empty())
        return false;
    wxBitmap bmp = create_scaled_bitmap(m_current_icon_name, m_parent, m_px_cnt);
    SetBitmap(bmp);
    SetBitmapCurrent(bmp);
    SetBitmapPressed(bmp);
    SetBitmapFocus(bmp);
    if (m_use_default_disabled_bitmap)
        SetBitmapDisabled(create_scaled_bitmap(m_current_icon_name, m_parent, m_px_cnt, true));
    return true;
}
References create_scaled_bitmap(), ScalableButton::m_current_icon_name, ScalableButton::m_parent, ScalableButton::m_px_cnt, and ScalableButton::m_use_default_disabled_bitmap.
SetBitmapDisabled_()
void ScalableButton::SetBitmapDisabled_ (const ScalableBitmap & bmp) inherited
{
    SetBitmapDisabled(bmp.bmp());
    m_disabled_icon_name = bmp.name();
}
References ScalableBitmap::bmp(), ScalableButton::m_disabled_icon_name, and ScalableBitmap::name().
UseDefaultBitmapDisabled()
void ScalableButton::UseDefaultBitmapDisabled () inherited
{
    m_use_default_disabled_bitmap = true;
    SetBitmapDisabled(create_scaled_bitmap(m_current_icon_name, m_parent, m_px_cnt, true));
}
References create_scaled_bitmap(), ScalableButton::m_current_icon_name, ScalableButton::m_parent, ScalableButton::m_px_cnt, and ScalableButton::m_use_default_disabled_bitmap.
Member Data Documentation
m_current_icon_name
std::string ScalableButton::m_current_icon_name private inherited
Referenced by ScalableButton::ScalableButton(), ScalableButton::msw_rescale(), ScalableButton::SetBitmap_(), ScalableButton::SetBitmap_(), and ScalableButton::UseDefaultBitmapDisabled().
m_disabled_icon_name
std::string ScalableButton::m_disabled_icon_name private inherited
Referenced by ScalableButton::msw_rescale(), and ScalableButton::SetBitmapDisabled_().
m_has_border
bool ScalableButton::m_has_border {false} private inherited
Referenced by ScalableButton::msw_rescale().
m_height
int ScalableButton::m_height {-1} private inherited
Referenced by ScalableButton::ScalableButton(), and ScalableButton::msw_rescale().
m_parent
wxWindow* ScalableButton::m_parent { nullptr } private inherited
Referenced by ScalableButton::ScalableButton(), ScalableButton::msw_rescale(), ScalableButton::SetBitmap_(), and ScalableButton::UseDefaultBitmapDisabled().
m_px_cnt
int ScalableButton::m_px_cnt { 16 } private inherited
Referenced by ScalableButton::ScalableButton(), ScalableButton::msw_rescale(), ScalableButton::SetBitmap_(), and ScalableButton::UseDefaultBitmapDisabled().
m_use_default_disabled_bitmap
bool ScalableButton::m_use_default_disabled_bitmap {false} private inherited
Referenced by ScalableButton::ScalableButton(), ScalableButton::msw_rescale(), ScalableButton::SetBitmap_(), and ScalableButton::UseDefaultBitmapDisabled().
m_width
int ScalableButton::m_width {-1} private inherited
Referenced by ScalableButton::ScalableButton(), and ScalableButton::msw_rescale().
range
std::pair<coordf_t, coordf_t> Slic3r::GUI::ObjectLayers::PlusMinusButton::range
Referenced by Slic3r::GUI::ObjectLayers::create_layer().
The documentation for this class was generated from the following file:
src/slic3r/GUI/GUI_ObjectLayers.hpp