OrcaSlicer: Slic3r::GUI::MenuFactory Class Reference
Slic3r::GUI::MenuFactory Class Reference
#include <src/slic3r/GUI/GUI_Factories.hpp>
Public Member Functions
MenuFactory ()
~MenuFactory ()=default
void init (wxWindow *parent)
void update ()
void update_object_menu ()
void update_default_menu ()
void msw_rescale ()
void sys_color_changed ()
wxMenu * default_menu ()
wxMenu * object_menu ()
wxMenu * sla_object_menu ()
wxMenu * part_menu ()
wxMenu * instance_menu ()
wxMenu * layer_menu ()
wxMenu * multi_selection_menu ()
wxMenu * plate_menu ()
wxMenu * assemble_object_menu ()
wxMenu * assemble_part_menu ()
wxMenu * assemble_multi_selection_menu ()
Static Public Member Functions
static std::vector< wxBitmap > get_volume_bitmaps ()
static void sys_color_changed (wxMenuBar *menu_bar)
Static Public Attributes
static const std::vector< std::pair< std::string, std::string > > ADD_VOLUME_MENU_ITEMS
Private Types
enum MenuType { mtObjectFFF = 0 , mtObjectSLA , mtCount }
Private Member Functions
void create_default_menu ()
void create_common_object_menu (wxMenu *menu)
void create_object_menu ()
void create_sla_object_menu ()
void create_part_menu ()
void create_plate_menu ()
void create_extra_object_menu ()
void create_bbl_part_menu ()
void create_bbl_assemble_object_menu ()
void create_bbl_assemble_part_menu ()
wxMenu * append_submenu_add_generic (wxMenu *menu, ModelVolumeType type)
void append_menu_items_add_volume (wxMenu *menu)
wxMenuItem * append_menu_item_layers_editing (wxMenu *menu)
wxMenuItem * append_menu_item_settings (wxMenu *menu)
wxMenuItem * append_menu_item_change_type (wxMenu *menu)
wxMenuItem * append_menu_item_instance_to_object (wxMenu *menu)
wxMenuItem * append_menu_item_printable (wxMenu *menu)
void append_menu_item_rename (wxMenu *menu)
wxMenuItem * append_menu_item_fix_through_netfabb (wxMenu *menu)
void append_menu_item_export_stl (wxMenu *menu, bool is_mulity_menu=false)
void append_menu_item_reload_from_disk (wxMenu *menu)
void append_menu_item_replace_with_stl (wxMenu *menu)
void append_menu_item_change_extruder (wxMenu *menu)
void append_menu_item_set_visible (wxMenu *menu)
void append_menu_item_delete (wxMenu *menu)
void append_menu_item_edit_text (wxMenu *menu)
void append_menu_item_scale_selection_to_fit_print_volume (wxMenu *menu)
void append_menu_items_convert_unit (wxMenu *menu)
void append_menu_items_flush_options (wxMenu *menu)
void append_menu_item_merge_to_multipart_object (wxMenu *menu)
void append_menu_item_merge_to_single_object (wxMenu *menu)
void append_menu_item_merge_parts_to_single_part (wxMenu *menu)
void append_menu_items_mirror (wxMenu *menu)
void append_menu_item_invalidate_cut_info (wxMenu *menu)
void append_menu_item_clone (wxMenu *menu)
void append_menu_item_simplify (wxMenu *menu)
void append_menu_item_center (wxMenu *menu)
void append_menu_item_per_object_process (wxMenu *menu)
void append_menu_item_per_object_settings (wxMenu *menu)
void append_menu_item_change_filament (wxMenu *menu)
void append_menu_item_set_printable (wxMenu *menu)
void append_menu_item_locked (wxMenu *menu)
void append_menu_item_fill_bed (wxMenu *menu)
Private Attributes
wxWindow * m_parent {nullptr}
MenuWithSeparators m_object_menu
MenuWithSeparators m_part_menu
MenuWithSeparators m_sla_object_menu
MenuWithSeparators m_default_menu
MenuWithSeparators m_instance_menu
MenuWithSeparators m_plate_menu
MenuWithSeparators m_assemble_object_menu
MenuWithSeparators m_assemble_part_menu
std::array< wxMenuItem *, mtCount > items_increase
std::array< wxMenuItem *, mtCount > items_decrease
std::array< wxMenuItem *, mtCount > items_set_number_of_copies
Detailed Description
Member Enumeration Documentation
MenuType
enum Slic3r::GUI::MenuFactory::MenuType private
Enumerator
mtObjectFFF
mtObjectSLA
mtCount
                  {
        mtObjectFFF = 0,
        mtObjectSLA,
        mtCount
    };
Constructor & Destructor Documentation
MenuFactory()
Slic3r::GUI::MenuFactory::MenuFactory ()
{
    for (int i = 0; i < mtCount; i++) {
        items_increase[i] = nullptr;
        items_decrease[i] = nullptr;
        items_set_number_of_copies[i] = nullptr;
    }
}
~MenuFactory()
Slic3r::GUI::MenuFactory::~MenuFactory () default
Member Function Documentation
append_menu_item_center()
void Slic3r::GUI::MenuFactory::append_menu_item_center (wxMenu * menu) private
{
     append_menu_item(menu, wxID_ANY, _L("Center") , "",
        [this](wxCommandEvent&) {
            plater()->center_selection();
        }, "", nullptr,
        []() {
            if (plater()->canvas3D()->get_canvas_type() != GLCanvas3D::ECanvasType::CanvasView3D)
                return false;
            else {
                Selection& selection = plater()->get_view3D_canvas3D()->get_selection();
                PartPlate* plate = plater()->get_partplate_list().get_selected_plate();
                Vec3d model_pos = selection.get_bounding_box().center();
                Vec3d center_pos = plate->get_center_origin();
                return !( (model_pos.x() == center_pos.x()) && (model_pos.y() == center_pos.y()) );
            } //disable if model is at center / not in View3D
        }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::canvas3D(), Slic3r::BoundingBox3Base< PointClass >::center(), Slic3r::GUI::Plater::center_selection(), Slic3r::GUI::Selection::get_bounding_box(), Slic3r::GUI::GLCanvas3D::get_canvas_type(), Slic3r::GUI::PartPlate::get_center_origin(), Slic3r::GUI::Plater::get_partplate_list(), Slic3r::GUI::PartPlateList::get_selected_plate(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Plater::get_view3D_canvas3D(), and Slic3r::GUI::plater().
append_menu_item_change_extruder()
void Slic3r::GUI::MenuFactory::append_menu_item_change_extruder (wxMenu * menu) private
{
    // BBS
    const std::vector<wxString> names = { _L("Change filament"), _L("Set filament for selected items") };
    // Delete old menu item
    for (const wxString& name : names) {
        const int item_id = menu->FindItem(name);
        if (item_id != wxNOT_FOUND)
            menu->Destroy(item_id);
    }
    const int filaments_cnt = filaments_count();
    if (filaments_cnt <= 1)
        return;
    wxDataViewItemArray sels;
    obj_list()->GetSelections(sels);
    if (sels.IsEmpty())
        return;
    std::vector<wxBitmap*> icons = get_extruder_color_icons(true);
    wxMenu* extruder_selection_menu = new wxMenu();
    const wxString& name = sels.Count() == 1 ? names[0] : names[1];
    int initial_extruder = -1; // negative value for multiple object/part selection
    if (sels.Count() == 1) {
        const ModelConfig& config = obj_list()->get_item_config(sels[0]);
        // BBS: set default extruder to 1
        initial_extruder = config.has("extruder") ? config.extruder() : 1;
    }
    for (int i = 0; i <= filaments_cnt; i++)
    {
        bool is_active_extruder = i == initial_extruder;
        int icon_idx = i == 0 ? 0 : i - 1;
        const wxString& item_name = (i == 0 ? _L("Default") : wxString::Format(_L("Filament %d"), i)) +
            (is_active_extruder ? " (" + _L("active") + ")" : "");
        if (icon_idx >= 0 && icon_idx < icons.size()) {
            append_menu_item(
                extruder_selection_menu, wxID_ANY, item_name, "", [i](wxCommandEvent &) { obj_list()->set_extruder_for_selected_items(i); }, *icons[icon_idx], menu,
                [is_active_extruder]() { return !is_active_extruder; }, m_parent);
        } else {
            append_menu_item(
                extruder_selection_menu, wxID_ANY, item_name, "", [i](wxCommandEvent &) { obj_list()->set_extruder_for_selected_items(i); }, "", menu,
                [is_active_extruder]() { return !is_active_extruder; }, m_parent);
        }
    }
    menu->AppendSubMenu(extruder_selection_menu, name);
}
References _L, append_menu_item(), Slic3r::ModelConfig::extruder(), Slic3r::GUI::filaments_count(), get_extruder_color_icons(), Slic3r::GUI::ObjectList::get_item_config(), Slic3r::ModelConfig::has(), Slic3r::GUI::obj_list(), and Slic3r::GUI::ObjectList::set_extruder_for_selected_items().
append_menu_item_change_filament()
void Slic3r::GUI::MenuFactory::append_menu_item_change_filament (wxMenu * menu) private
{
    const std::vector<wxString> names = { _L("Change Filament"), _L("Set Filament for selected items") };
    // Delete old menu item
    for (const wxString& name : names) {
        const int item_id = menu->FindItem(name);
        if (item_id != wxNOT_FOUND)
            menu->Destroy(item_id);
    }
    int filaments_cnt = filaments_count();
    if (filaments_cnt <= 1)
        return;
    wxDataViewItemArray sels;
    obj_list()->GetSelections(sels);
    if (sels.IsEmpty())
        return;
    if (sels.Count() == 1) {
        const auto sel_vol = obj_list()->get_selected_model_volume();
        if (sel_vol && sel_vol->type() != ModelVolumeType::MODEL_PART && sel_vol->type() != ModelVolumeType::PARAMETER_MODIFIER)
            return;
    }
    std::vector<wxBitmap*> icons = get_extruder_color_icons(true);
    if (icons.size() < filaments_cnt) {
        BOOST_LOG_TRIVIAL(warning) << boost::format("Warning: icons size %1%, filaments_cnt=%2%")%icons.size()%filaments_cnt;
        if (icons.size() <= 1)
            return;
        else
            filaments_cnt = icons.size();
    }
    wxMenu* extruder_selection_menu = new wxMenu();
    const wxString& name = sels.Count() == 1 ? names[0] : names[1];
    int initial_extruder = -1; // negative value for multiple object/part selection
    if (sels.Count() == 1) {
        const ModelConfig& config = obj_list()->get_item_config(sels[0]);
        // BBS
        const auto sel_vol = obj_list()->get_selected_model_volume();
        if (sel_vol && sel_vol->type() == ModelVolumeType::PARAMETER_MODIFIER)
            initial_extruder = config.has("extruder") ? config.extruder() : 0;
        else
            initial_extruder = config.has("extruder") ? config.extruder() : 1;
    }
    // BBS
    bool has_modifier = false;
    for (auto sel : sels) {
        if (obj_list()->GetModel()->GetVolumeType(sel) == ModelVolumeType::PARAMETER_MODIFIER) {
            has_modifier = true;
            break;
        }
    }
    for (int i = has_modifier ? 0 : 1; i <= filaments_cnt; i++)
    {
        // BBS
        //bool is_active_extruder = i == initial_extruder;
        bool is_active_extruder = false;
        const wxString& item_name = (i == 0 ? _L("Default") : wxString::Format(_L("Filament %d"), i)) +
            (is_active_extruder ? " (" + _L("current") + ")" : "");
        append_menu_item(extruder_selection_menu, wxID_ANY, item_name, "",
            [i](wxCommandEvent&) { obj_list()->set_extruder_for_selected_items(i); }, i == 0 ? wxNullBitmap : *icons[i - 1], menu,
            [is_active_extruder]() { return !is_active_extruder; }, m_parent);
    }
    menu->Append(wxID_ANY, name, extruder_selection_menu, _L("Change Filament"));
}
References _L, append_menu_item(), Slic3r::ModelConfig::extruder(), Slic3r::GUI::filaments_count(), get_extruder_color_icons(), Slic3r::GUI::ObjectList::get_item_config(), Slic3r::GUI::ObjectList::get_selected_model_volume(), Slic3r::GUI::ObjectList::GetModel(), Slic3r::GUI::ObjectDataViewModel::GetVolumeType(), Slic3r::ModelConfig::has(), Slic3r::MODEL_PART, Slic3r::GUI::obj_list(), Slic3r::PARAMETER_MODIFIER, and Slic3r::GUI::ObjectList::set_extruder_for_selected_items().
append_menu_item_change_type()
wxMenuItem * Slic3r::GUI::MenuFactory::append_menu_item_change_type (wxMenu * menu) private
{
    return append_menu_item(menu, wxID_ANY, _L("Change type"), "",
        [](wxCommandEvent&) { obj_list()->change_part_type(); }, "", menu,
        []() {
            wxDataViewItem item = obj_list()->GetSelection();
            return item.IsOk() || obj_list()->GetModel()->GetItemType(item) == itVolume;
        }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::ObjectList::change_part_type(), Slic3r::GUI::ObjectDataViewModel::GetItemType(), Slic3r::GUI::ObjectList::GetModel(), Slic3r::GUI::itVolume, and Slic3r::GUI::obj_list().
append_menu_item_clone()
void Slic3r::GUI::MenuFactory::append_menu_item_clone (wxMenu * menu) private
{
    append_menu_item(menu, wxID_ANY, _L("Clone") , "",
        [this](wxCommandEvent&) {
            plater()->clone_selection();
        }, "", nullptr,
        []() {
            return true;
        }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::clone_selection(), and Slic3r::GUI::plater().
append_menu_item_delete()
void Slic3r::GUI::MenuFactory::append_menu_item_delete (wxMenu * menu) private
{
#ifdef __WINDOWS__
    append_menu_item(menu, wxID_ANY, _L("Delete") + "\t" + _L("Del"), _L("Delete the selected object"),
        [](wxCommandEvent&) { plater()->remove_selected(); }, "menu_delete", nullptr,
        []() { return plater()->can_delete(); }, m_parent);
#else
    append_menu_item(menu, wxID_ANY, _L("Delete") + "\tBackSpace", _L("Delete the selected object"),
        [](wxCommandEvent&) { plater()->remove_selected(); }, "", nullptr,
        []() { return plater()->can_delete(); }, m_parent);
#endif
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_delete(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::remove_selected().
append_menu_item_edit_text()
void Slic3r::GUI::MenuFactory::append_menu_item_edit_text (wxMenu * menu) private
{
#ifdef __WINDOWS__
    append_menu_item(
        menu, wxID_ANY, _L("Edit Text"), "", [](wxCommandEvent &) { plater()->edit_text(); }, "", nullptr,
        []() { return plater()->can_edit_text(); }, m_parent);
#else
    append_menu_item(
        menu, wxID_ANY, _L("Edit Text"), "", [](wxCommandEvent &) { plater()->edit_text(); }, "", nullptr,
        []() { return plater()->can_edit_text(); }, m_parent);
#endif
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_edit_text(), Slic3r::GUI::Plater::edit_text(), and Slic3r::GUI::plater().
append_menu_item_export_stl()
void Slic3r::GUI::MenuFactory::append_menu_item_export_stl (wxMenu * menu, bool is_mulity_menu = false) private
{
    append_menu_item(menu, wxID_ANY, _L("Export as STL") + dots, "",
        [](wxCommandEvent&) { plater()->export_stl(false, true); }, "", nullptr,
        [is_mulity_menu]() {
            const Selection& selection = plater()->canvas3D()->get_selection();
            if (is_mulity_menu)
                return selection.is_multiple_full_instance() || selection.is_multiple_full_object();
            else
                return selection.is_single_full_instance() || selection.is_single_full_object();
        }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_multiple_full_instance(), Slic3r::GUI::Selection::is_multiple_full_object(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_full_object(), and Slic3r::GUI::plater().
append_menu_item_fill_bed()
void Slic3r::GUI::MenuFactory::append_menu_item_fill_bed (wxMenu * menu) private
{
    append_menu_item(
        menu, wxID_ANY, _L("Fill bed with copies"), _L("Fill the remaining area of bed with copies of the selected object"),
        [](wxCommandEvent &) { plater()->fill_bed_with_instances(); }, "", nullptr, []() { return plater()->can_increase_instances(); }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_increase_instances(), Slic3r::GUI::Plater::fill_bed_with_instances(), and Slic3r::GUI::plater().
append_menu_item_fix_through_netfabb()
wxMenuItem * Slic3r::GUI::MenuFactory::append_menu_item_fix_through_netfabb (wxMenu * menu) private
{
    if (!is_windows10())
        return nullptr;
    wxMenuItem* menu_item = append_menu_item(menu, wxID_ANY, _L("Fix model"), "",
        [](wxCommandEvent&) { obj_list()->fix_through_netfabb(); }, "", menu,
        []() {return plater()->can_fix_through_netfabb(); }, plater());
    return menu_item;
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_fix_through_netfabb(), Slic3r::GUI::ObjectList::fix_through_netfabb(), Slic3r::is_windows10(), Slic3r::GUI::obj_list(), and Slic3r::GUI::plater().
append_menu_item_instance_to_object()
wxMenuItem * Slic3r::GUI::MenuFactory::append_menu_item_instance_to_object (wxMenu * menu) private
{
    wxMenuItem* menu_item = append_menu_item(menu, wxID_ANY, _L("Set as an individual object"), "",
        [](wxCommandEvent&) { obj_list()->split_instances(); }, "", menu);
    /* New behavior logic:
     * 1. Split Object to several separated object, if ALL instances are selected
     * 2. Separate selected instances from the initial object to the separated object,
     *    if some (not all) instances are selected
     */
    m_parent->Bind(wxEVT_UPDATE_UI, [](wxUpdateUIEvent& evt)
        {
            const Selection& selection = plater()->canvas3D()->get_selection();
            evt.SetText(selection.is_single_full_object() ?
                _L("Set as individual objects") : _L("Set as an individual object"));
            evt.Enable(plater()->can_set_instance_to_object());
        }, menu_item->GetId());
    return menu_item;
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_set_instance_to_object(), Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_single_full_object(), Slic3r::GUI::obj_list(), Slic3r::GUI::plater(), and Slic3r::GUI::ObjectList::split_instances().
append_menu_item_invalidate_cut_info()
void Slic3r::GUI::MenuFactory::append_menu_item_invalidate_cut_info (wxMenu * menu) private
{
    const wxString menu_name = _L("Invalidate cut info");
    auto menu_item_id = menu->FindItem(menu_name);
    if (menu_item_id != wxNOT_FOUND)
        // Delete old menu item if selected object isn't cut
        menu->Destroy(menu_item_id);
    if (obj_list()->has_selected_cut_object())
        append_menu_item(menu, wxID_ANY, menu_name, "", [](wxCommandEvent &) { obj_list()->invalidate_cut_info_for_selection(); },
            "", menu, []() { return true; }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::ObjectList::invalidate_cut_info_for_selection(), and Slic3r::GUI::obj_list().
append_menu_item_layers_editing()
wxMenuItem * Slic3r::GUI::MenuFactory::append_menu_item_layers_editing (wxMenu * menu) private
{
    return append_menu_item(menu, wxID_ANY, _L("Height range Modifier"), "",
        [](wxCommandEvent&) { obj_list()->layers_editing(); wxGetApp().params_panel()->switch_to_object(); }, "", menu,
        []() { return obj_list()->is_instance_or_object_selected(); }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::ObjectList::is_instance_or_object_selected(), Slic3r::GUI::ObjectList::layers_editing(), and Slic3r::GUI::obj_list().
append_menu_item_locked()
void Slic3r::GUI::MenuFactory::append_menu_item_locked (wxMenu * menu) private
{
    const std::vector<wxString> names = { _L("Unlock"), _L("Lock") };
    // Delete old menu item
    for (const wxString& name : names) {
        const int item_id = menu->FindItem(name);
        if (item_id != wxNOT_FOUND)
            menu->Destroy(item_id);
    }
    PartPlate* plate = plater()->get_partplate_list().get_selected_plate();
    assert(plate);
    wxString lock_text = plate->is_locked() ? names[0] : names[1];
    auto item = append_menu_item(menu, wxID_ANY, lock_text, "",
        [plate](wxCommandEvent&) {
            bool lock = plate->is_locked();
            plate->lock(!lock);
        }, "", nullptr, []() { return true; }, m_parent);
    m_parent->Bind(wxEVT_UPDATE_UI, [](wxUpdateUIEvent& evt) {
        PartPlate* plate = plater()->get_partplate_list().get_selected_plate();
        assert(plate);
        //bool check = plate->is_locked();
        //evt.Check(check);
        plater()->set_current_canvas_as_dirty();
    }, item->GetId());
}
References _L, append_menu_item(), Slic3r::GUI::Plater::get_partplate_list(), Slic3r::GUI::PartPlateList::get_selected_plate(), Slic3r::GUI::PartPlate::is_locked(), Slic3r::GUI::PartPlate::lock(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::set_current_canvas_as_dirty().
append_menu_item_merge_parts_to_single_part()
void Slic3r::GUI::MenuFactory::append_menu_item_merge_parts_to_single_part (wxMenu * menu) private
{
    menu->AppendSeparator();
    append_menu_item(menu, wxID_ANY, _L("Assemble"), _L("Assemble the selected parts to a single part"),
        [](wxCommandEvent&) { obj_list()->merge_volumes(); }, "", menu,
        []() { return true; }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::ObjectList::merge_volumes(), and Slic3r::GUI::obj_list().
append_menu_item_merge_to_multipart_object()
void Slic3r::GUI::MenuFactory::append_menu_item_merge_to_multipart_object (wxMenu * menu) private
{
    append_menu_item(menu, wxID_ANY, _L("Assemble"), _L("Assemble the selected objects to an object with multiple parts"),
        [](wxCommandEvent&) { obj_list()->merge(true); }, "", menu,
        []() { return obj_list()->can_merge_to_multipart_object(); }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::ObjectList::can_merge_to_multipart_object(), Slic3r::GUI::ObjectList::merge(), and Slic3r::GUI::obj_list().
append_menu_item_merge_to_single_object()
void Slic3r::GUI::MenuFactory::append_menu_item_merge_to_single_object (wxMenu * menu) private
{
    menu->AppendSeparator();
    append_menu_item(menu, wxID_ANY, _L("Assemble"), _L("Assemble the selected objects to an object with single part"),
        [](wxCommandEvent&) { obj_list()->merge(false); }, "", menu,
        []() { return obj_list()->can_merge_to_single_object(); }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::ObjectList::can_merge_to_single_object(), Slic3r::GUI::ObjectList::merge(), and Slic3r::GUI::obj_list().
append_menu_item_per_object_process()
void Slic3r::GUI::MenuFactory::append_menu_item_per_object_process (wxMenu * menu) private
{
    const std::vector<wxString> names = { _L("Edit Process Settings"), _L("Edit Process Settings") };
    append_menu_item(menu, wxID_ANY, names[0], names[1],
        [](wxCommandEvent&) {
            wxGetApp().obj_list()->switch_to_object_process();
        }, "", nullptr,
        []() {
            Selection& selection = plater()->canvas3D()->get_selection();
            return selection.is_single_full_object() ||
                selection.is_multiple_full_object() ||
                selection.is_single_full_instance() ||
                selection.is_multiple_full_instance() ||
                selection.is_single_volume() ||
                selection.is_multiple_volume();
        }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_multiple_full_instance(), Slic3r::GUI::Selection::is_multiple_full_object(), Slic3r::GUI::Selection::is_multiple_volume(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_full_object(), Slic3r::GUI::Selection::is_single_volume(), and Slic3r::GUI::plater().
append_menu_item_per_object_settings()
void Slic3r::GUI::MenuFactory::append_menu_item_per_object_settings (wxMenu * menu) private
{
    const std::vector<wxString> names = { _L("Edit in Parameter Table"), _L("Edit print parameters for a single object") };
    // Delete old menu item
    for (const wxString& name : names) {
        const int item_id = menu->FindItem(name);
        if (item_id != wxNOT_FOUND)
            menu->Destroy(item_id);
    }
    append_menu_item(menu, wxID_ANY, names[0], names[1],
        [](wxCommandEvent&) {
            plater()->PopupObjectTableBySelection();
        }, "", nullptr,
        []() {
            Selection& selection = plater()->canvas3D()->get_selection();
            return selection.is_single_full_object() || selection.is_single_full_instance() || selection.is_single_volume();
        }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_full_object(), Slic3r::GUI::Selection::is_single_volume(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::PopupObjectTableBySelection().
append_menu_item_printable()
wxMenuItem * Slic3r::GUI::MenuFactory::append_menu_item_printable (wxMenu * menu) private
{
    // BBS: to be checked
    wxMenuItem* menu_item_printable = append_menu_check_item(menu, wxID_ANY, _L("Printable"), "",
        [](wxCommandEvent&) { obj_list()->toggle_printable_state(); }, menu);
    m_parent->Bind(wxEVT_UPDATE_UI, [](wxUpdateUIEvent& evt) {
        ObjectList* list = obj_list();
        wxDataViewItemArray sels;
        list->GetSelections(sels);
        wxDataViewItem frst_item = sels[0];
        ItemType type = list->GetModel()->GetItemType(frst_item);
        bool check;
        if (type != itInstance && type != itObject)
            check = false;
        else {
            int obj_idx = list->GetModel()->GetObjectIdByItem(frst_item);
            int inst_idx = type == itObject ? 0 : list->GetModel()->GetInstanceIdByItem(frst_item);
            check = list->object(obj_idx)->instances[inst_idx]->printable;
        }
        evt.Check(check);
        plater()->set_current_canvas_as_dirty();
        }, menu_item_printable->GetId());
    return menu_item_printable;
}
References _L, append_menu_check_item(), Slic3r::GUI::ObjectDataViewModel::GetInstanceIdByItem(), Slic3r::GUI::ObjectDataViewModel::GetItemType(), Slic3r::GUI::ObjectList::GetModel(), Slic3r::GUI::ObjectDataViewModel::GetObjectIdByItem(), Slic3r::ModelObject::instances, Slic3r::GUI::itInstance, Slic3r::GUI::itObject, Slic3r::GUI::obj_list(), Slic3r::GUI::ObjectList::object(), Slic3r::GUI::plater(), Slic3r::GUI::Plater::set_current_canvas_as_dirty(), and Slic3r::GUI::ObjectList::toggle_printable_state().
append_menu_item_reload_from_disk()
void Slic3r::GUI::MenuFactory::append_menu_item_reload_from_disk (wxMenu * menu) private
{
    append_menu_item(menu, wxID_ANY, _L("Reload from disk"), _L("Reload the selected parts from disk"),
        [](wxCommandEvent&) { plater()->reload_from_disk(); }, "", menu,
        []() { return plater()->can_reload_from_disk(); }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_reload_from_disk(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::reload_from_disk().
append_menu_item_rename()
void Slic3r::GUI::MenuFactory::append_menu_item_rename (wxMenu * menu) private
{
    append_menu_item(menu, wxID_ANY, _L("Rename"), "",
        [](wxCommandEvent&) { obj_list()->rename_item(); }, "", menu);
    menu->AppendSeparator();
}
References _L, append_menu_item(), Slic3r::GUI::obj_list(), and Slic3r::GUI::ObjectList::rename_item().
append_menu_item_replace_with_stl()
void Slic3r::GUI::MenuFactory::append_menu_item_replace_with_stl (wxMenu * menu) private
{
    append_menu_item(menu, wxID_ANY, _L("Replace with STL"), _L("Replace the selected part with new STL"),
        [](wxCommandEvent &) { plater()->replace_with_stl(); }, "", menu,
        []() { return plater()->can_replace_with_stl(); }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_replace_with_stl(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::replace_with_stl().
append_menu_item_scale_selection_to_fit_print_volume()
void Slic3r::GUI::MenuFactory::append_menu_item_scale_selection_to_fit_print_volume (wxMenu * menu) private
{
    append_menu_item(menu, wxID_ANY, _L("Scale to build volume"), _L("Scale an object to fit the build volume"),
        [](wxCommandEvent&) { plater()->scale_selection_to_fit_print_volume(); }, "", menu);
}
References _L, append_menu_item(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::scale_selection_to_fit_print_volume().
append_menu_item_set_printable()
void Slic3r::GUI::MenuFactory::append_menu_item_set_printable (wxMenu * menu) private
{
    const Selection& selection = plater()->canvas3D()->get_selection();
    bool all_printable = true;
    ObjectList* list = obj_list();
    wxDataViewItemArray sels;
    list->GetSelections(sels);
    for (wxDataViewItem item : sels) {
        ItemType type = list->GetModel()->GetItemType(item);
        bool check;
        if (type != itInstance && type != itObject)
            continue;
        else {
            int obj_idx = list->GetModel()->GetObjectIdByItem(item);
            int inst_idx = type == itObject ? 0 : list->GetModel()->GetInstanceIdByItem(item);
            all_printable &= list->object(obj_idx)->instances[inst_idx]->printable;
        }
    }
    wxString menu_text = all_printable ? _L("Set Unprintable") : _L("Set Printable");
    append_menu_item(menu, wxID_ANY, menu_text, "", [this, all_printable](wxCommandEvent&) {
        Selection& selection = plater()->canvas3D()->get_selection();
        selection.set_printable(!all_printable);
        }, "", nullptr, []() { return true; }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::ObjectDataViewModel::GetInstanceIdByItem(), Slic3r::GUI::ObjectDataViewModel::GetItemType(), Slic3r::GUI::ObjectList::GetModel(), Slic3r::GUI::ObjectDataViewModel::GetObjectIdByItem(), Slic3r::ModelObject::instances, Slic3r::GUI::itInstance, Slic3r::GUI::itObject, Slic3r::GUI::obj_list(), Slic3r::GUI::ObjectList::object(), Slic3r::GUI::plater(), and Slic3r::GUI::Selection::set_printable().
append_menu_item_set_visible()
void Slic3r::GUI::MenuFactory::append_menu_item_set_visible (wxMenu * menu) private
{
    bool has_one_shown = false;
    const Selection& selection = plater()->canvas3D()->get_selection();
    for (unsigned int i : selection.get_volume_idxs()) {
        has_one_shown |= selection.get_volume(i)->visible;
    }
    append_menu_item(menu, wxID_ANY, has_one_shown ?_L("Hide") : _L("Show"), "",
        [has_one_shown](wxCommandEvent&) { plater()->set_selected_visible(!has_one_shown); }, "", nullptr,
        []() { return true; }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::set_selected_visible().
append_menu_item_settings()
wxMenuItem * Slic3r::GUI::MenuFactory::append_menu_item_settings (wxMenu * menu) private
{
    MenuWithSeparators* menu = dynamic_cast<MenuWithSeparators*>(menu_);
    const wxString menu_name = _L("Add settings");
    // Delete old items from settings popupmenu
    auto settings_id = menu->FindItem(menu_name);
    if (settings_id != wxNOT_FOUND)
        menu->Destroy(settings_id);
    for (auto& it : FREQ_SETTINGS_BUNDLE_FFF)
    {
        settings_id = menu->FindItem(_(it.first));
        if (settings_id != wxNOT_FOUND)
            menu->Destroy(settings_id);
    }
    for (auto& it : FREQ_SETTINGS_BUNDLE_SLA)
    {
        settings_id = menu->FindItem(_(it.first));
        if (settings_id != wxNOT_FOUND)
            menu->Destroy(settings_id);
    }
    menu->DestroySeparators(); // delete old separators
    // If there are selected more then one instance but not all of them
    // don't add settings menu items
    const Selection& selection = get_selection();
    if ((selection.is_multiple_full_instance() && !selection.is_single_full_object()) ||
        selection.is_multiple_volume() || selection.is_mixed()) // more than one volume(part) is selected on the scene
        return nullptr;
    const auto sel_vol = obj_list()->get_selected_model_volume();
    if (sel_vol && sel_vol->type() >= ModelVolumeType::SUPPORT_ENFORCER)
        return nullptr;
    // Create new items for settings popupmenu
    if (printer_technology() == ptFFF ||
        (menu->GetMenuItems().size() > 0 && !menu->GetMenuItems().back()->IsSeparator()))
        ;// menu->SetFirstSeparator();
    // detect itemm for adding of the setting
    ObjectList* object_list = obj_list();
    ObjectDataViewModel* obj_model = list_model();
    const wxDataViewItem sel_item = // when all instances in object are selected
                                    object_list->GetSelectedItemsCount() > 1 && selection.is_single_full_object() ?
                                    obj_model->GetItemById(selection.get_object_idx()) :
                                    object_list->GetSelection();
    if (!sel_item)
        return nullptr;
    // If we try to add settings for object/part from 3Dscene,
    // for the second try there is selected ItemSettings in ObjectList.
    // So, check if selected item isn't SettingsItem. And get a SettingsItem's parent item, if yes
    wxDataViewItem item = obj_model->GetItemType(sel_item) & itSettings ? obj_model->GetParent(sel_item) : sel_item;
    const ItemType item_type = obj_model->GetItemType(item);
    const bool is_object_settings = !(item_type& itVolume || item_type & itLayer);
    // Add frequently settings
    // BBS remvoe freq setting popupmenu
    // create_freq_settings_popupmenu(menu, is_object_settings, item);
    //menu->SetSecondSeparator();
    // Add full settings list
    auto  menu_item = new wxMenuItem(menu, wxID_ANY, menu_name);
    menu_item->SetBitmap(create_scaled_bitmap("cog"));
    menu_item->SetSubMenu(create_settings_popupmenu(menu, is_object_settings, item));
    return menu->Append(menu_item);
}
References _, _L, create_scaled_bitmap(), Slic3r::GUI::create_settings_popupmenu(), MenuWithSeparators::DestroySeparators(), Slic3r::GUI::FREQ_SETTINGS_BUNDLE_FFF, Slic3r::GUI::FREQ_SETTINGS_BUNDLE_SLA, Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::ObjectList::get_selected_model_volume(), Slic3r::GUI::get_selection(), Slic3r::GUI::ObjectDataViewModel::GetItemById(), Slic3r::GUI::ObjectDataViewModel::GetItemType(), Slic3r::GUI::ObjectDataViewModel::GetParent(), Slic3r::GUI::Selection::is_mixed(), Slic3r::GUI::Selection::is_multiple_full_instance(), Slic3r::GUI::Selection::is_multiple_volume(), Slic3r::GUI::Selection::is_single_full_object(), Slic3r::GUI::itLayer, Slic3r::GUI::itSettings, Slic3r::GUI::itVolume, Slic3r::GUI::list_model(), Slic3r::GUI::obj_list(), Slic3r::printer_technology(), Slic3r::ptFFF, and Slic3r::SUPPORT_ENFORCER.
append_menu_item_simplify()
void Slic3r::GUI::MenuFactory::append_menu_item_simplify (wxMenu * menu) private
{
    wxMenuItem* menu_item = append_menu_item(menu, wxID_ANY, _L("Simplify Model"), "",
        [](wxCommandEvent&) { obj_list()->simplify(); }, "", menu,
        []() {return plater()->can_simplify(); }, m_parent);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_simplify(), Slic3r::GUI::obj_list(), Slic3r::GUI::plater(), and Slic3r::GUI::ObjectList::simplify().
append_menu_items_add_volume()
void Slic3r::GUI::MenuFactory::append_menu_items_add_volume (wxMenu * menu) private
{
    // Update "add" items(delete old & create new)  settings popupmenu
    for (auto& item : ADD_VOLUME_MENU_ITEMS) {
        const auto settings_id = menu->FindItem(_(item.first));
        if (settings_id != wxNOT_FOUND)
            menu->Destroy(settings_id);
    }
    for (size_t type = 0; type < ADD_VOLUME_MENU_ITEMS.size(); type++)
    {
        auto& item = ADD_VOLUME_MENU_ITEMS[type];
        wxMenu* sub_menu = append_submenu_add_generic(menu, ModelVolumeType(type));
        append_submenu(menu, sub_menu, wxID_ANY, _(item.first), "", item.second,
            []() { return obj_list()->is_instance_or_object_selected(); }, m_parent);
    }
    append_menu_item_layers_editing(menu);
}
References _, and append_submenu().
append_menu_items_convert_unit()
void Slic3r::GUI::MenuFactory::append_menu_items_convert_unit (wxMenu * menu) private
{
    std::vector<int> obj_idxs, vol_idxs;
    obj_list()->get_selection_indexes(obj_idxs, vol_idxs);
    if (obj_idxs.empty() && vol_idxs.empty())
        return;
    auto volume_respects_conversion = [](ModelVolume* volume, ConversionType conver_type)
    {
        return  (conver_type == ConversionType::CONV_FROM_INCH && volume->source.is_converted_from_inches) ||
            (conver_type == ConversionType::CONV_TO_INCH && !volume->source.is_converted_from_inches) ||
            (conver_type == ConversionType::CONV_FROM_METER && volume->source.is_converted_from_meters) ||
            (conver_type == ConversionType::CONV_TO_METER && !volume->source.is_converted_from_meters);
    };
    auto can_append = [obj_idxs, vol_idxs, volume_respects_conversion](ConversionType conver_type)
    {
        ModelObjectPtrs objects;
        for (int obj_idx : obj_idxs) {
            ModelObject* object = obj_list()->object(obj_idx);
            if (vol_idxs.empty()) {
                for (ModelVolume* volume : object->volumes)
                    if (volume_respects_conversion(volume, conver_type))
                        return false;
            }
            else {
                for (int vol_idx : vol_idxs)
                    if (volume_respects_conversion(object->volumes[vol_idx], conver_type))
                        return false;
            }
        }
        return true;
    };
    std::vector<std::pair<ConversionType, wxString>> items = {
        {ConversionType::CONV_FROM_INCH , _L("Convert from inch") },
        {ConversionType::CONV_TO_INCH   , _L("Restore to inch") },
        {ConversionType::CONV_FROM_METER, _L("Convert from meter") },
        {ConversionType::CONV_TO_METER  , _L("Restore to meter") } };
    for (auto item : items) {
        int menu_id = menu->FindItem(item.second);
        if (can_append(item.first)) {
            // Add menu item if it doesn't exist
            if (menu_id == wxNOT_FOUND)
                append_menu_item(menu, wxID_ANY, item.second, item.second,
                    [item](wxCommandEvent&) { plater()->convert_unit(item.first); }, "", menu,
                    []() { return true; }, m_parent);
        }
        else if (menu_id != wxNOT_FOUND) {
            // Delete menu item
            menu->Destroy(menu_id);
        }
    }
}
References _L, append_menu_item(), Slic3r::CONV_FROM_INCH, Slic3r::CONV_FROM_METER, Slic3r::CONV_TO_INCH, Slic3r::CONV_TO_METER, Slic3r::GUI::ObjectList::get_selection_indexes(), Slic3r::GUI::obj_list(), and Slic3r::GUI::ObjectList::object().
append_menu_items_flush_options()
void Slic3r::GUI::MenuFactory::append_menu_items_flush_options (wxMenu * menu) private
{
    const wxString name = _L("Flush Options");
    // Delete old menu item
    const int item_id = menu->FindItem(name);
    if (item_id != wxNOT_FOUND)
        menu->Destroy(item_id);
    bool show_flush_option_menu = false;
    ObjectList* object_list = obj_list();
    const Selection& selection = get_selection();
    if (selection.get_object_idx() < 0)
        return;
    if (wxGetApp().plater()->get_partplate_list().get_curr_plate()->contains(selection.get_bounding_box())) {
        auto plate_extruders = wxGetApp().plater()->get_partplate_list().get_curr_plate()->get_extruders();
        for (auto extruder : plate_extruders) {
            if (extruder != plate_extruders[0])
                show_flush_option_menu = true;
        }
    }
    if (!show_flush_option_menu)
        return;
    DynamicPrintConfig& global_config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
    ModelConfig& select_object_config = object_list->object(selection.get_object_idx())->config;
    auto keys = select_object_config.keys();
    for (auto key : FREQ_SETTINGS_BUNDLE_FFF["Flush options"]) {
        if (find(keys.begin(), keys.end(), key) == keys.end()) {
            const ConfigOption* option = global_config.option(key);
            select_object_config.set_key_value(key, option->clone());
        }
    }
    wxMenu* flush_options_menu = new wxMenu();
    append_menu_check_item(flush_options_menu, wxID_ANY, _L("Flush into objects' infill"), "",
        [&select_object_config](wxCommandEvent&) {
            const ConfigOption* option = select_object_config.option(FREQ_SETTINGS_BUNDLE_FFF["Flush options"][0]);
            select_object_config.set_key_value(FREQ_SETTINGS_BUNDLE_FFF["Flush options"][0], new ConfigOptionBool(!option->getBool()));
            wxGetApp().obj_settings()->UpdateAndShow(true);
        }, menu, []() {return true; }, [&select_object_config]() {const ConfigOption* option = select_object_config.option(FREQ_SETTINGS_BUNDLE_FFF["Flush options"][0]); return option->getBool(); }, m_parent);
    append_menu_check_item(flush_options_menu, wxID_ANY, _L("Flush into this object"), "",
        [&select_object_config](wxCommandEvent&) {
            const ConfigOption* option = select_object_config.option(FREQ_SETTINGS_BUNDLE_FFF["Flush options"][1]);
            select_object_config.set_key_value(FREQ_SETTINGS_BUNDLE_FFF["Flush options"][1], new ConfigOptionBool(!option->getBool()));
            wxGetApp().obj_settings()->UpdateAndShow(true);
        }, menu, []() {return true; }, [&select_object_config]() {const ConfigOption* option = select_object_config.option(FREQ_SETTINGS_BUNDLE_FFF["Flush options"][1]); return option->getBool(); }, m_parent);
    append_menu_check_item(flush_options_menu, wxID_ANY, _L("Flush into objects' support"), "",
        [&select_object_config](wxCommandEvent&) {
            const ConfigOption* option = select_object_config.option(FREQ_SETTINGS_BUNDLE_FFF["Flush options"][2]);
            select_object_config.set_key_value(FREQ_SETTINGS_BUNDLE_FFF["Flush options"][2], new ConfigOptionBool(!option->getBool()));
            wxGetApp().obj_settings()->UpdateAndShow(true);
        }, menu, []() {return true; }, [&select_object_config]() {const ConfigOption* option = select_object_config.option(FREQ_SETTINGS_BUNDLE_FFF["Flush options"][2]); return option->getBool(); }, m_parent);
    size_t i = 0;
    for (auto node = menu->GetMenuItems().GetFirst(); node; node = node->GetNext())
    {
        i++;
        wxMenuItem* item = node->GetData();
        if (item->GetItemLabelText() == _L("Edit in Parameter Table"))
            break;
    }
    menu->Insert(i, wxID_ANY, _L("Flush Options"), flush_options_menu);
}
References _L, append_menu_check_item(), Slic3r::ConfigOption::clone(), Slic3r::ModelObject::config, Slic3r::contains(), Slic3r::GUI::FREQ_SETTINGS_BUNDLE_FFF, Slic3r::GUI::Selection::get_bounding_box(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::get_selection(), Slic3r::ConfigOption::getBool(), Slic3r::ModelConfig::keys(), Slic3r::GUI::obj_list(), Slic3r::GUI::ObjectList::object(), Slic3r::ModelConfig::option(), Slic3r::ConfigBase::option(), Slic3r::GUI::plater(), and Slic3r::ModelConfig::set_key_value().
append_menu_items_mirror()
void Slic3r::GUI::MenuFactory::append_menu_items_mirror (wxMenu * menu) private
{
    wxMenu* mirror_menu = new wxMenu();
    if (!mirror_menu)
        return;
    append_menu_item(mirror_menu, wxID_ANY, _L("Along X axis"), _L("Mirror along the X axis"),
        [](wxCommandEvent&) { plater()->mirror(X); }, "", menu);
    append_menu_item(mirror_menu, wxID_ANY, _L("Along Y axis"), _L("Mirror along the Y axis"),
        [](wxCommandEvent&) { plater()->mirror(Y); }, "", menu);
    append_menu_item(mirror_menu, wxID_ANY, _L("Along Z axis"), _L("Mirror along the Z axis"),
        [](wxCommandEvent&) { plater()->mirror(Z); }, "", menu);
    append_submenu(menu, mirror_menu, wxID_ANY, _L("Mirror"), _L("Mirror object"), "",
        []() { return plater()->can_mirror(); }, m_parent);
}
References _L, append_menu_item(), append_submenu(), Slic3r::GUI::Plater::can_mirror(), Slic3r::GUI::Plater::mirror(), Slic3r::GUI::plater(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
append_submenu_add_generic()
wxMenu * Slic3r::GUI::MenuFactory::append_submenu_add_generic (wxMenu * menu, ModelVolumeType type) private
{
    auto sub_menu = new wxMenu;
    if (type != ModelVolumeType::INVALID) {
        append_menu_item(sub_menu, wxID_ANY, _L("Load..."), "",
            [type](wxCommandEvent&) { obj_list()->load_subobject(type); }, "", menu);
        sub_menu->AppendSeparator();
    }
    for (auto &item : {L("Orca Cube"), L("3DBenchy"), L("Autodesk FDM Test"),
                       L("Voron Cube")}) {
        append_menu_item(
            sub_menu, wxID_ANY, _(item), "",
            [type, item](wxCommandEvent &) {
              std::vector<boost::filesystem::path> input_files;
              std::string file_name = item;
              if (file_name == L("Orca Cube"))
                file_name = "OrcaCube_v2.3mf";
              else if (file_name == L("3DBenchy"))
                file_name = "3DBenchy.stl";
              else if (file_name == L("Autodesk FDM Test"))
                file_name = "ksr_fdmtest_v4.stl";
              else if (file_name == L("Voron Cube"))
                file_name = "Voron_Design_Cube_v7.stl";
              else
                return;
              input_files.push_back(
                  (boost::filesystem::path(Slic3r::resources_dir()) /
                   "handy_models" / file_name));
              plater()->load_files(input_files, LoadStrategy::LoadModel);
            },
            "", menu);
    }
    sub_menu->AppendSeparator();
    for (auto &item : {L("Cube"), L("Cylinder"), L("Sphere"), L("Cone")}) {
        append_menu_item(
            sub_menu, wxID_ANY, _(item), "",
            [type, item](wxCommandEvent &) {
              obj_list()->load_generic_subobject(item, type);
            },
            "", menu);
    }
    return sub_menu;
}
References _, _L, append_menu_item(), Slic3r::INVALID, L, Slic3r::GUI::Plater::load_files(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_subobject(), Slic3r::LoadModel, Slic3r::GUI::obj_list(), Slic3r::GUI::plater(), and Slic3r::resources_dir().
assemble_multi_selection_menu()
wxMenu * Slic3r::GUI::MenuFactory::assemble_multi_selection_menu ()
{
    wxDataViewItemArray sels;
    obj_list()->GetSelections(sels);
    for (const wxDataViewItem& item : sels)
        if (!(list_model()->GetItemType(item) & (itVolume | itObject | itInstance)))
            // show this menu only for Objects(Instances mixed with Objects)/Volumes selection
            return nullptr;
    wxMenu* menu = new MenuWithSeparators();
    append_menu_item_set_visible(menu);
    //append_menu_item_fix_through_netfabb(menu);
    //append_menu_item_simplify(menu);
    append_menu_item_delete(menu);
    menu->AppendSeparator();
    append_menu_item_change_extruder(menu);
    return menu;
}
References Slic3r::GUI::itInstance, Slic3r::GUI::itObject, Slic3r::GUI::itVolume, Slic3r::GUI::list_model(), and Slic3r::GUI::obj_list().
assemble_object_menu()
wxMenu * Slic3r::GUI::MenuFactory::assemble_object_menu ()
{
    wxMenu* menu = new MenuWithSeparators();
    // Set Visible
    append_menu_item_set_visible(menu);
    // Delete
    append_menu_item_delete(menu);
    //append_menu_item_fix_through_netfabb(menu);
    //append_menu_item_simplify(menu);
    menu->AppendSeparator();
    // Set filament
    append_menu_item_change_extruder(menu);
    //append_menu_item_per_object_settings(menu);
    return menu;
}
assemble_part_menu()
wxMenu * Slic3r::GUI::MenuFactory::assemble_part_menu ()
{
    wxMenu* menu = new MenuWithSeparators();
    append_menu_item_set_visible(menu);
    append_menu_item_delete(menu);
    //append_menu_item_simplify(menu);
    menu->AppendSeparator();
    append_menu_item_change_extruder(menu);
    //append_menu_item_per_object_settings(menu);
    return menu;
}
create_bbl_assemble_object_menu()
void Slic3r::GUI::MenuFactory::create_bbl_assemble_object_menu () private
{
    // Delete
    append_menu_item_delete(&m_assemble_object_menu);
    // Object Repair
    append_menu_item_fix_through_netfabb(&m_assemble_object_menu);
    // Object Simplify
    append_menu_item_simplify(&m_assemble_object_menu);
    m_assemble_object_menu.AppendSeparator();
}
create_bbl_assemble_part_menu()
void Slic3r::GUI::MenuFactory::create_bbl_assemble_part_menu () private
{
    wxMenu* menu = &m_assemble_part_menu;
    append_menu_item_delete(menu);
    append_menu_item_simplify(menu);
    menu->AppendSeparator();
}
create_bbl_part_menu()
void Slic3r::GUI::MenuFactory::create_bbl_part_menu () private
{
    wxMenu* menu = &m_part_menu;
    append_menu_item_delete(menu);
    append_menu_item_edit_text(menu);
    append_menu_item_fix_through_netfabb(menu);
    append_menu_item_simplify(menu);
    append_menu_item_center(menu);
    append_menu_items_mirror(menu);
    wxMenu* split_menu = new wxMenu();
    if (!split_menu)
        return;
    append_menu_item(split_menu, wxID_ANY, _L("To objects"), _L("Split the selected object into mutiple objects"),
        [](wxCommandEvent&) { plater()->split_object(); }, "split_objects", menu,
        []() { return plater()->can_split(true); }, m_parent);
    append_menu_item(split_menu, wxID_ANY, _L("To parts"), _L("Split the selected object into mutiple parts"),
        [](wxCommandEvent&) { plater()->split_volume(); }, "split_parts", menu,
        []() { return plater()->can_split(false); }, m_parent);
    append_submenu(menu, split_menu, wxID_ANY, _L("Split"), _L("Split the selected object"), "",
        []() { return plater()->can_split(true); }, m_parent);
    menu->AppendSeparator();
    append_menu_item_per_object_settings(menu);
    append_menu_item_change_type(menu);
    append_menu_item_reload_from_disk(menu);
    append_menu_item_replace_with_stl(menu);
}
References _L, append_menu_item(), append_submenu(), Slic3r::GUI::Plater::can_split(), Slic3r::GUI::plater(), Slic3r::GUI::Plater::split_object(), and Slic3r::GUI::Plater::split_volume().
create_common_object_menu()
void Slic3r::GUI::MenuFactory::create_common_object_menu (wxMenu * menu) private
{
    append_menu_item_rename(menu);
    // BBS
    //append_menu_items_instance_manipulation(menu);
    // Delete menu was moved to be after +/- instace to make it more difficult to be selected by mistake.
    append_menu_item_delete(menu);
    //append_menu_item_instance_to_object(menu);
    menu->AppendSeparator();
    // BBS
    append_menu_item_reload_from_disk(menu);
    append_menu_item_export_stl(menu);
    // "Scale to print volume" makes a sense just for whole object
    append_menu_item_scale_selection_to_fit_print_volume(menu);
    append_menu_item_fix_through_netfabb(menu);
    append_menu_items_mirror(menu);
}
create_default_menu()
void Slic3r::GUI::MenuFactory::create_default_menu () private
{
    wxMenu* sub_menu = append_submenu_add_generic(&m_default_menu, ModelVolumeType::INVALID);
#ifdef __WINDOWS__
    append_submenu(&m_default_menu, sub_menu, wxID_ANY, _L("Add Primitive"), "", "menu_add_part",
        []() {return true; }, m_parent);
#else
    append_submenu(&m_default_menu, sub_menu, wxID_ANY, _L("Add Primitive"), "", "",
        []() {return true; }, m_parent);
#endif
    m_default_menu.AppendSeparator();
    append_menu_check_item(&m_default_menu, wxID_ANY, _L("Show Labels"), "",
        [](wxCommandEvent&) { plater()->show_view3D_labels(!plater()->are_view3D_labels_shown()); plater()->get_current_canvas3D()->post_event(SimpleEvent(wxEVT_PAINT)); }, &m_default_menu,
        []() { return plater()->is_view3D_shown(); }, [this]() { return plater()->are_view3D_labels_shown(); }, m_parent);
}
References _L, append_menu_check_item(), append_submenu(), Slic3r::GUI::Plater::are_view3D_labels_shown(), Slic3r::GUI::Plater::get_current_canvas3D(), Slic3r::INVALID, Slic3r::GUI::Plater::is_view3D_shown(), Slic3r::GUI::plater(), Slic3r::GUI::GLCanvas3D::post_event(), and Slic3r::GUI::Plater::show_view3D_labels().
create_extra_object_menu()
void Slic3r::GUI::MenuFactory::create_extra_object_menu () private
{
    append_menu_item_fill_bed(&m_object_menu);
    // Object Clone
    append_menu_item_clone(&m_object_menu);
    // Object Repair
    append_menu_item_fix_through_netfabb(&m_object_menu);
    // Object Simplify
    append_menu_item_simplify(&m_object_menu);
    // Object Center
    append_menu_item_center(&m_object_menu);
    // Object Split
    wxMenu* split_menu = new wxMenu();
    if (!split_menu)
        return;
    append_menu_item(split_menu, wxID_ANY, _L("To objects"), _L("Split the selected object into multiple objects"),
        [](wxCommandEvent&) { plater()->split_object(); }, "split_objects", &m_object_menu,
        []() { return plater()->can_split(true); }, m_parent);
    append_menu_item(split_menu, wxID_ANY, _L("To parts"), _L("Split the selected object into multiple parts"),
        [](wxCommandEvent&) { plater()->split_volume(); }, "split_parts", &m_object_menu,
        []() { return plater()->can_split(false); }, m_parent);
    append_submenu(&m_object_menu, split_menu, wxID_ANY, _L("Split"), _L("Split the selected object"), "",
        []() { return plater()->can_split(true); }, m_parent);
    // Mirror
    append_menu_items_mirror(&m_object_menu);
    // Delete
    append_menu_item_delete(&m_object_menu);
    m_object_menu.AppendSeparator();
    // Modifier Part
    // BBS
    append_menu_items_add_volume(&m_object_menu);
    m_object_menu.AppendSeparator();
    // Set filament insert menu item here
    // Set Printable
    wxMenuItem* menu_item_printable = append_menu_item_printable(&m_object_menu);
    append_menu_item_per_object_process(&m_object_menu);
    // Enter per object parameters
    append_menu_item_per_object_settings(&m_object_menu);
    m_object_menu.AppendSeparator();
    append_menu_item_reload_from_disk(&m_object_menu);
    append_menu_item_replace_with_stl(&m_object_menu);
    append_menu_item_export_stl(&m_object_menu);
}
References _L, append_menu_item(), append_submenu(), Slic3r::GUI::Plater::can_split(), Slic3r::GUI::plater(), Slic3r::GUI::Plater::split_object(), and Slic3r::GUI::Plater::split_volume().
create_object_menu()
void Slic3r::GUI::MenuFactory::create_object_menu () private
{
    create_common_object_menu(&m_object_menu);
    wxMenu* split_menu = new wxMenu();
    if (!split_menu)
        return;
    append_menu_item(split_menu, wxID_ANY, _L("To objects"), _L("Split the selected object into multiple objects"),
        [](wxCommandEvent&) { plater()->split_object(); }, "split_objects", &m_object_menu,
        []() { return plater()->can_split(true); }, m_parent);
    append_menu_item(split_menu, wxID_ANY, _L("To parts"), _L("Split the selected object into multiple parts"),
        [](wxCommandEvent&) { plater()->split_volume(); }, "split_parts", &m_object_menu,
        []() { return plater()->can_split(false); }, m_parent);
    append_submenu(&m_object_menu, split_menu, wxID_ANY, _L("Split"), _L("Split the selected object"), "",
        []() { return plater()->can_split(true) || plater()->can_split(false); }, m_parent);
    m_object_menu.AppendSeparator();
    // BBS: remove Layers Editing
    m_object_menu.AppendSeparator();
    // "Add (volumes)" popupmenu will be added later in append_menu_items_add_volume()
}
References _L, append_menu_item(), append_submenu(), Slic3r::GUI::Plater::can_split(), Slic3r::GUI::plater(), Slic3r::GUI::Plater::split_object(), and Slic3r::GUI::Plater::split_volume().
create_part_menu()
void Slic3r::GUI::MenuFactory::create_part_menu () private
{
    wxMenu* menu = &m_part_menu;
    append_menu_item_rename(menu);
    append_menu_item_delete(menu);
    append_menu_item_reload_from_disk(menu);
    append_menu_item_export_stl(menu);
    append_menu_item_fix_through_netfabb(menu);
    append_menu_items_mirror(menu);
    append_menu_item_merge_parts_to_single_part(menu);
    append_menu_item(menu, wxID_ANY, _L("Split"), _L("Split the selected object into multiple parts"),
        [](wxCommandEvent&) { plater()->split_volume(); }, "split_parts", nullptr,
        []() { return plater()->can_split(false); }, m_parent);
    menu->AppendSeparator();
    append_menu_item_change_type(menu);
    append_menu_items_mirror(&m_part_menu);
    append_menu_item(&m_part_menu, wxID_ANY, _L("Split"), _L("Split the selected object into multiple parts"),
        [](wxCommandEvent&) { plater()->split_volume(); }, "split_parts", nullptr,
        []() { return plater()->can_split(false); }, m_parent);
    m_part_menu.AppendSeparator();
    append_menu_item_per_object_settings(&m_part_menu);
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_split(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::split_volume().
create_plate_menu()
void Slic3r::GUI::MenuFactory::create_plate_menu () private
{
    wxMenu* menu = &m_plate_menu;
    // select objects on current plate
    append_menu_item(menu, wxID_ANY, _L("Select All"), _L("select all objects on current plate"),
        [](wxCommandEvent&) {
            plater()->select_curr_plate_all();
        }, "", nullptr, []() {
            PartPlate* plate = plater()->get_partplate_list().get_selected_plate();
            assert(plate);
            return !plate->get_objects().empty();
        }, m_parent);
    // delete objects on current plate
    append_menu_item(menu, wxID_ANY, _L("Delete All"), _L("delete all objects on current plate"),
        [](wxCommandEvent&) {
            plater()->remove_curr_plate_all();
        }, "", nullptr, []() {
            PartPlate* plate = plater()->get_partplate_list().get_selected_plate();
            assert(plate);
            return !plate->get_objects().empty();
        }, m_parent);
    // arrange objects on current plate
    append_menu_item(menu, wxID_ANY, _L("Arrange"), _L("arrange current plate"),
        [](wxCommandEvent&) {
            PartPlate* plate = plater()->get_partplate_list().get_selected_plate();
            assert(plate);
            plater()->set_prepare_state(Job::PREPARE_STATE_MENU);
            plater()->arrange();
        }, "", nullptr,
        []() {
            return !plater()->get_partplate_list().get_selected_plate()->get_objects().empty();
        },
        m_parent);
    // orient objects on current plate
    append_menu_item(menu, wxID_ANY, _L("Auto Rotate"), _L("auto rotate current plate"),
        [](wxCommandEvent&) {
            PartPlate* plate = plater()->get_partplate_list().get_selected_plate();
            assert(plate);
            //BBS TODO call auto rotate for current plate
            plater()->set_prepare_state(Job::PREPARE_STATE_MENU);
            plater()->orient();
        }, "", nullptr,
        []() {
            return !plater()->get_partplate_list().get_selected_plate()->get_objects().empty();
        }, m_parent);
    // delete current plate
#ifdef __WINDOWS__
    append_menu_item(menu, wxID_ANY, _L("Delete Plate"), _L("Remove the selected plate"),
        [](wxCommandEvent&) { plater()->delete_plate(); }, "menu_delete", nullptr,
        []() { return plater()->can_delete_plate(); }, m_parent);
#else
    append_menu_item(menu, wxID_ANY, _L("Delete Plate"), _L("Remove the selected plate"),
        [](wxCommandEvent&) { plater()->delete_plate(); }, "", nullptr,
        []() { return plater()->can_delete_plate(); }, m_parent);
#endif
    // add shapes
    menu->AppendSeparator();
    wxMenu* sub_menu = append_submenu_add_generic(menu, ModelVolumeType::INVALID);
#ifdef __WINDOWS__
    append_submenu(menu, sub_menu, wxID_ANY, _L("Add Primitive"), "", "menu_add_part",
        []() {return true; }, m_parent);
#else
    append_submenu(menu, sub_menu, wxID_ANY, _L("Add Primitive"), "", "",
        []() {return true; }, m_parent);
#endif
    return;
}
References _L, append_menu_item(), append_submenu(), Slic3r::GUI::Plater::arrange(), Slic3r::GUI::Plater::can_delete_plate(), Slic3r::GUI::Plater::delete_plate(), Slic3r::GUI::PartPlate::get_objects(), Slic3r::GUI::Plater::get_partplate_list(), Slic3r::GUI::PartPlateList::get_selected_plate(), Slic3r::INVALID, Slic3r::GUI::Plater::orient(), Slic3r::GUI::plater(), Slic3r::GUI::Plater::remove_curr_plate_all(), Slic3r::GUI::Plater::select_curr_plate_all(), and Slic3r::GUI::Plater::set_prepare_state().
create_sla_object_menu()
void Slic3r::GUI::MenuFactory::create_sla_object_menu () private
{
    create_common_object_menu(&m_sla_object_menu);
    append_menu_item(&m_sla_object_menu, wxID_ANY, _L("Split"), _L("Split the selected object into multiple objects"),
        [](wxCommandEvent&) { plater()->split_object(); }, "split_objects", nullptr,
        []() { return plater()->can_split(true); }, m_parent);
    m_sla_object_menu.AppendSeparator();
    // Add the automatic rotation sub-menu
    append_menu_item(&m_sla_object_menu, wxID_ANY, _L("Auto orientation"), _L("Auto orient the object to improve print quality."),
        [](wxCommandEvent&) { plater()->optimize_rotation(); });
}
References _L, append_menu_item(), Slic3r::GUI::Plater::can_split(), Slic3r::GUI::Plater::optimize_rotation(), Slic3r::GUI::plater(), and Slic3r::GUI::Plater::split_object().
default_menu()
wxMenu * Slic3r::GUI::MenuFactory::default_menu ()
{
    return &m_default_menu;
}
get_volume_bitmaps()
std::vector< wxBitmap > Slic3r::GUI::MenuFactory::get_volume_bitmaps () static
{
    std::vector<wxBitmap> volume_bmps;
    volume_bmps.reserve(ADD_VOLUME_MENU_ITEMS.size());
    for (auto item : ADD_VOLUME_MENU_ITEMS){
        if(!item.second.empty()){
            volume_bmps.push_back(create_scaled_bitmap(item.second));
        }
    }
    return volume_bmps;
}
References create_scaled_bitmap().
Referenced by Slic3r::GUI::ObjectDataViewModel::ObjectDataViewModel(), and Slic3r::GUI::ObjectDataViewModel::Rescale().
init()
void Slic3r::GUI::MenuFactory::init (wxWindow * parent)
{
    m_parent = parent;
    create_default_menu();
    //BBS
    //create_object_menu();
    create_sla_object_menu();
    //create_part_menu();
    create_extra_object_menu();
    create_bbl_part_menu();
    create_bbl_assemble_object_menu();
    create_bbl_assemble_part_menu();
    //BBS: add part plate related logic
    create_plate_menu();
    // create "Instance to Object" menu item
    append_menu_item_instance_to_object(&m_instance_menu);
}
instance_menu()
wxMenu * Slic3r::GUI::MenuFactory::instance_menu ()
{
    return &m_instance_menu;
}
layer_menu()
wxMenu * Slic3r::GUI::MenuFactory::layer_menu ()
{
    MenuWithSeparators* menu = new MenuWithSeparators();
    append_menu_item_settings(menu);
    return menu;
}
msw_rescale()
void Slic3r::GUI::MenuFactory::msw_rescale ()
{
    for (MenuWithSeparators* menu : { &m_object_menu, &m_sla_object_menu, &m_part_menu, &m_default_menu })
        msw_rescale_menu(dynamic_cast<wxMenu*>(menu));
}
References msw_rescale_menu().
multi_selection_menu()
wxMenu * Slic3r::GUI::MenuFactory::multi_selection_menu ()
{
    //BBS
    wxDataViewItemArray sels;
    obj_list()->GetSelections(sels);
    bool multi_volume = true;
    for (const wxDataViewItem& item : sels) {
        multi_volume = list_model()->GetItemType(item) & itVolume;
        if (!(list_model()->GetItemType(item) & (itVolume | itObject | itInstance)))
            // show this menu only for Objects(Instances mixed with Objects)/Volumes selection
            return nullptr;
    }
    wxMenu* menu = new MenuWithSeparators();
    if (!multi_volume) {
        int index = 0;
        if (obj_list()->can_merge_to_multipart_object()) {
            append_menu_item_merge_to_multipart_object(menu);
            index++;
        }
        append_menu_item_center(menu);
        append_menu_item_fix_through_netfabb(menu);
        //append_menu_item_simplify(menu);
        append_menu_item_delete(menu);
        menu->AppendSeparator();
        //BBS
        append_menu_item_change_filament(menu);
        append_menu_item_set_printable(menu);
        append_menu_item_per_object_process(menu);
        menu->AppendSeparator();
        append_menu_items_convert_unit(menu);
        menu->AppendSeparator();
        append_menu_item_export_stl(menu, true);
    }
    else {
        append_menu_item_center(menu);
        append_menu_item_fix_through_netfabb(menu);
        //append_menu_item_simplify(menu);
        append_menu_item_delete(menu);
        append_menu_items_convert_unit(menu);
        wxMenu* split_menu = new wxMenu();
        if (split_menu) {
            append_menu_item(split_menu, wxID_ANY, _L("To objects"), _L("Split the selected object into multiple objects"),
                [](wxCommandEvent&) { plater()->split_object(); }, "split_objects", menu,
                []() { return plater()->can_split(true); }, m_parent);
            append_menu_item(split_menu, wxID_ANY, _L("To parts"), _L("Split the selected object into multiple parts"),
                [](wxCommandEvent&) { plater()->split_volume(); }, "split_parts", menu,
                []() { return plater()->can_split(false); }, m_parent);
            append_submenu(menu, split_menu, wxID_ANY, _L("Split"), _L("Split the selected object"), "",
                []() { return plater()->can_split(true); }, m_parent);
        }
        menu->AppendSeparator();
        append_menu_item_change_filament(menu);
    }
    return menu;
}
References _L, append_menu_item(), append_submenu(), Slic3r::GUI::Plater::can_split(), Slic3r::GUI::ObjectDataViewModel::GetItemType(), Slic3r::GUI::itInstance, Slic3r::GUI::itObject, Slic3r::GUI::itVolume, Slic3r::GUI::list_model(), Slic3r::GUI::obj_list(), Slic3r::GUI::plater(), Slic3r::GUI::Plater::split_object(), and Slic3r::GUI::Plater::split_volume().
object_menu()
wxMenu * Slic3r::GUI::MenuFactory::object_menu ()
{
    append_menu_item_change_filament(&m_object_menu);
    append_menu_items_convert_unit(&m_object_menu);
    append_menu_items_flush_options(&m_object_menu);
    append_menu_item_invalidate_cut_info(&m_object_menu);
    return &m_object_menu;
}
part_menu()
wxMenu * Slic3r::GUI::MenuFactory::part_menu ()
{
    append_menu_items_convert_unit(&m_part_menu);
    append_menu_item_change_filament(&m_part_menu);
    append_menu_item_per_object_settings(&m_part_menu);
    return &m_part_menu;
}
plate_menu()
wxMenu * Slic3r::GUI::MenuFactory::plate_menu ()
{
    append_menu_item_locked(&m_plate_menu);
    return &m_plate_menu;
}
sla_object_menu()
wxMenu * Slic3r::GUI::MenuFactory::sla_object_menu ()
{
    append_menu_items_convert_unit(&m_sla_object_menu);
    append_menu_item_settings(&m_sla_object_menu);
    //update_menu_items_instance_manipulation(mtObjectSLA);
    return &m_sla_object_menu;
}
sys_color_changed() [1/2]
void Slic3r::GUI::MenuFactory::sys_color_changed ()
{
    for (MenuWithSeparators* menu : { &m_object_menu, &m_sla_object_menu, &m_part_menu, &m_default_menu }) {
        msw_rescale_menu(dynamic_cast<wxMenu*>(menu));// msw_rescale_menu updates just icons, so use it
#ifdef _WIN32
        // but under MSW we have to update item's bachground color
        for (wxMenuItem* item : menu->GetMenuItems())
            update_menu_item_def_colors(item);
#endif
    }
}
References msw_rescale_menu().
Referenced by Slic3r::GUI::MainFrame::on_sys_color_changed().
sys_color_changed() [2/2]
void Slic3r::GUI::MenuFactory::sys_color_changed (wxMenuBar * menu_bar) static
{
    // BBS: fix
#if 0
    for (size_t id = 0; id < menubar->GetMenuCount(); id++) {
        wxMenu* menu = menubar->GetMenu(id);
        msw_rescale_menu(menu);
#ifdef _WIN32
        // but under MSW we have to update item's bachground color
        for (wxMenuItem* item : menu->GetMenuItems())
            update_menu_item_def_colors(item);
#endif
    }
    menubar->Refresh();
#endif
}
References msw_rescale_menu().
update()
void Slic3r::GUI::MenuFactory::update ()
{
    update_default_menu();
    update_object_menu();
}
update_default_menu()
void Slic3r::GUI::MenuFactory::update_default_menu ()
{
    for (auto& name : { _L("Add Primitive") , _L("Show Labels") }) {
        const auto menu_item_id = m_default_menu.FindItem(name);
        if (menu_item_id != wxNOT_FOUND)
            m_default_menu.Destroy(menu_item_id);
    }
    create_default_menu();
}
References _L.
update_object_menu()
void Slic3r::GUI::MenuFactory::update_object_menu ()
{
    append_menu_items_add_volume(&m_object_menu);
}
Member Data Documentation
ADD_VOLUME_MENU_ITEMS
const std::vector< std::pair< std::string, std::string > > Slic3r::GUI::MenuFactory::ADD_VOLUME_MENU_ITEMS static
Initial value:
= {
        {L("Add part"),              "menu_add_part" },
        {L("Add negative part"),     "menu_add_negative" },
        {L("Add modifier"),          "menu_add_modifier"},
        {L("Add support blocker"),   "menu_support_blocker"},
        {L("Add support enforcer"),  "menu_support_enforcer"}
}
items_decrease
std::array<wxMenuItem*, mtCount> Slic3r::GUI::MenuFactory::items_decrease private
items_increase
std::array<wxMenuItem*, mtCount> Slic3r::GUI::MenuFactory::items_increase private
items_set_number_of_copies
std::array<wxMenuItem*, mtCount> Slic3r::GUI::MenuFactory::items_set_number_of_copies private
m_assemble_object_menu
MenuWithSeparators Slic3r::GUI::MenuFactory::m_assemble_object_menu private
m_assemble_part_menu
MenuWithSeparators Slic3r::GUI::MenuFactory::m_assemble_part_menu private
m_default_menu
MenuWithSeparators Slic3r::GUI::MenuFactory::m_default_menu private
m_instance_menu
MenuWithSeparators Slic3r::GUI::MenuFactory::m_instance_menu private
m_object_menu
MenuWithSeparators Slic3r::GUI::MenuFactory::m_object_menu private
m_parent
wxWindow* Slic3r::GUI::MenuFactory::m_parent {nullptr} private
m_part_menu
MenuWithSeparators Slic3r::GUI::MenuFactory::m_part_menu private
m_plate_menu
MenuWithSeparators Slic3r::GUI::MenuFactory::m_plate_menu private
m_sla_object_menu
MenuWithSeparators Slic3r::GUI::MenuFactory::m_sla_object_menu private
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_Factories.hpp
src/slic3r/GUI/GUI_Factories.cpp