OrcaSlicer: Slic3r::_BBS_3MF_Exporter Class Reference
Slic3r::_BBS_3MF_Exporter Class Reference
Classes
struct BuildItem
struct ObjectData
Public Member Functions
bool save_model_to_file (StoreParams &store_params)
bool save_object_mesh (const std::string &temp_path, ModelObject const &object, int obj_id)
void log_errors ()
Protected Member Functions
void add_error (const std::string &error) const
void clear_errors ()
Private Types
typedef std::map< const ModelVolume *, int > VolumeToObjectIDMap
typedef std::vector< BuildItem > BuildItemsList
typedef std::map< ModelObject const *, ObjectData > ObjectToObjectDataMap
Private Member Functions
bool _save_model_to_file (const std::string &filename, Model &model, PlateDataPtrs &plate_data_list, std::vector< Preset * > &project_presets, const DynamicPrintConfig *config, const std::vector< ThumbnailData * > &thumbnail_data, const std::vector< ThumbnailData * > &top_thumbnail_data, const std::vector< ThumbnailData * > &pick_thumbnail_data, Export3mfProgressFn proFn, const std::vector< ThumbnailData * > &calibration_data, const std::vector< PlateBBoxData * > &id_bboxes, BBLProject *project=nullptr, int export_plate_idx=-1)
bool _add_file_to_archive (mz_zip_archive &archive, const std::string &path_in_zip, const std::string &file_path)
bool _add_content_types_file_to_archive (mz_zip_archive &archive)
bool _add_thumbnail_file_to_archive (mz_zip_archive &archive, const ThumbnailData &thumbnail_data, const char *local_path, int index)
bool _add_calibration_file_to_archive (mz_zip_archive &archive, const ThumbnailData &thumbnail_data, int index)
bool _add_bbox_file_to_archive (mz_zip_archive &archive, const PlateBBoxData &id_bboxes, int index)
bool _add_relationships_file_to_archive (mz_zip_archive &archive, std::string const &from={}, std::vector< std::string > const &targets={}, std::vector< std::string > const &types={}, PackingTemporaryData data=PackingTemporaryData(), int export_plate_idx=-1) const
bool _add_model_file_to_archive (const std::string &filename, mz_zip_archive &archive, const Model &model, ObjectToObjectDataMap &objects_data, Export3mfProgressFn proFn=nullptr, BBLProject *project=nullptr) const
bool _add_object_to_model_stream (mz_zip_writer_staged_context &context, ObjectData const &object_data) const
void _add_object_components_to_stream (std::stringstream &stream, ObjectData const &object_data) const
bool _add_mesh_to_object_stream (std::function< bool(std::string &, bool)> const &flush, ObjectData const &object_data) const
bool _add_build_to_model_stream (std::stringstream &stream, const BuildItemsList &build_items) const
bool _add_layer_height_profile_file_to_archive (mz_zip_archive &archive, Model &model)
bool _add_layer_config_ranges_file_to_archive (mz_zip_archive &archive, Model &model)
bool _add_sla_support_points_file_to_archive (mz_zip_archive &archive, Model &model)
bool _add_sla_drain_holes_file_to_archive (mz_zip_archive &archive, Model &model)
bool _add_print_config_file_to_archive (mz_zip_archive &archive, const DynamicPrintConfig &config)
bool _add_project_config_file_to_archive (mz_zip_archive &archive, const DynamicPrintConfig &config, Model &model)
bool _add_project_embedded_presets_to_archive (mz_zip_archive &archive, Model &model, std::vector< Preset * > project_presets)
bool _add_model_config_file_to_archive (mz_zip_archive &archive, const Model &model, PlateDataPtrs &plate_data_list, const ObjectToObjectDataMap &objects_data, int export_plate_idx=-1, bool save_gcode=true, bool use_loaded_id=false)
bool _add_cut_information_file_to_archive (mz_zip_archive &archive, Model &model)
bool _add_slice_info_config_file_to_archive (mz_zip_archive &archive, const Model &model, PlateDataPtrs &plate_data_list, const ObjectToObjectDataMap &objects_data)
bool _add_gcode_file_to_archive (mz_zip_archive &archive, const Model &model, PlateDataPtrs &plate_data_list, Export3mfProgressFn proFn=nullptr)
bool _add_custom_gcode_per_print_z_file_to_archive (mz_zip_archive &archive, Model &model, const DynamicPrintConfig *config)
bool _add_auxiliary_dir_to_archive (mz_zip_archive &archive, const std::string &aux_dir, PackingTemporaryData &data)
Static Private Member Functions
static int convert_instance_id_to_resource_id (const Model &model, int obj_id, int instance_id)
Private Attributes
bool m_fullpath_sources { true }
bool m_zip64 { true }
bool m_production_ext { false }
bool m_skip_static { false }
bool m_from_backup_save { false }
bool m_split_model { false }
bool m_save_gcode { false }
bool m_skip_model { false }
bool m_skip_auxiliary { false }
bool m_use_loaded_id { false }
bool m_share_mesh { false }
std::string m_thumbnail_middle = PRINTER_THUMBNAIL_MIDDLE_FILE
std::string m_thumbnail_small = PRINTER_THUMBNAIL_SMALL_FILE
std::map< void const *, std::pair< ObjectData *, ModelVolume const * > > m_shared_meshes
std::map< ModelVolume const *, std::pair< std::string, int > > m_volume_paths
boost::mutex mutex
std::vector< std::string > m_errors
Detailed Description
Class Documentation
Slic3r::_BBS_3MF_Exporter::ObjectData
struct Slic3r::_BBS_3MF_Exporter::ObjectData
Class Members
int backup_id
ModelObject const * object
int object_id = 0
bool share_mesh = false
string sub_path
VolumeToObjectIDMap volumes_objectID
Member Typedef Documentation
BuildItemsList
typedef std::vector<BuildItem> Slic3r::_BBS_3MF_Exporter::BuildItemsList private
ObjectToObjectDataMap
typedef std::map<ModelObject const *, ObjectData> Slic3r::_BBS_3MF_Exporter::ObjectToObjectDataMap private
VolumeToObjectIDMap
typedef std::map<const ModelVolume*, int> Slic3r::_BBS_3MF_Exporter::VolumeToObjectIDMap private
Member Function Documentation
_add_auxiliary_dir_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_auxiliary_dir_to_archive (mz_zip_archive & archive, const std::string & aux_dir, PackingTemporaryData & data) private
{
    bool result = true;
    if (aux_dir.empty()) {
        //no accessory directories
        return result;
    }
    boost::filesystem::path dir = boost::filesystem::path(aux_dir);
    if (!boost::filesystem::exists(dir))
    {
        //no accessory directories
        return result;
    }
    static std::string const nocomp_exts[] = {".png", ".jpg", ".mp4", ".jpeg"};
    std::deque<boost::filesystem::path> directories({dir});
    int root_dir_len = dir.string().length() + 1;
    //boost file access
    while (!directories.empty()) {
        boost::filesystem::directory_iterator iterator(directories.front());
        directories.pop_front();
        for (auto &dir_entry : iterator)
        {
            std::string src_file;
            std::string dst_in_3mf;
            if (boost::filesystem::is_directory(dir_entry.path()))
            {
                directories.push_back(dir_entry.path());
                continue;
            }
            if (boost::filesystem::is_regular_file(dir_entry.path()) && !m_skip_auxiliary)
            {
                src_file = dir_entry.path().string();
                dst_in_3mf = dir_entry.path().string();
                dst_in_3mf.replace(0, root_dir_len, AUXILIARY_DIR);
                std::replace(dst_in_3mf.begin(), dst_in_3mf.end(), '\\', '/');
                if (_3MF_COVER_FILE.compare(1, _3MF_COVER_FILE.length() - 1, dst_in_3mf) == 0) {
                    data._3mf_thumbnail = dst_in_3mf;
                } else if (m_thumbnail_small.compare(1, m_thumbnail_small.length() - 1, dst_in_3mf) == 0) {
                    data._3mf_printer_thumbnail_small = dst_in_3mf;
                    if (m_thumbnail_middle == m_thumbnail_small) data._3mf_printer_thumbnail_middle = dst_in_3mf;
                } else if (m_thumbnail_middle.compare(1, m_thumbnail_middle.length() - 1, dst_in_3mf) == 0) {
                    data._3mf_printer_thumbnail_middle = dst_in_3mf;
                }
                result &= _add_file_to_archive(archive, dst_in_3mf, src_file);
            }
        }
    }
    return result;
}
References _3MF_COVER_FILE, Slic3r::PackingTemporaryData::_3mf_printer_thumbnail_middle, Slic3r::PackingTemporaryData::_3mf_printer_thumbnail_small, Slic3r::PackingTemporaryData::_3mf_thumbnail, and AUXILIARY_DIR.
_add_bbox_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_bbox_file_to_archive (mz_zip_archive & archive, const PlateBBoxData & id_bboxes, int index) private
    {
        bool res = false;
        nlohmann::json j;
        id_bboxes.to_json(j);
        std::string out = j.dump();
        std::string json_file_name = (boost::format(PATTERN_CONFIG_FILE_FORMAT) % (index + 1)).str();
        if (!mz_zip_writer_add_mem(&archive, json_file_name.c_str(), (const void*)out.data(), out.length(), MZ_DEFAULT_COMPRESSION)) {
            add_error("Unable to add json file to archive");
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Unable to add json file to archive\n");
            return false;
        }
        return true;
    }
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), error, MZ_DEFAULT_COMPRESSION, mz_zip_writer_add_mem(), out, PATTERN_CONFIG_FILE_FORMAT, and Slic3r::PlateBBoxData::to_json().
_add_build_to_model_stream()
bool Slic3r::_BBS_3MF_Exporter::_add_build_to_model_stream (std::stringstream & stream, const BuildItemsList & build_items) const private
    {
        // This happens for empty projects
        if (build_items.size() == 0) {
            return true;
        }
        stream << " <" << BUILD_TAG;
        if (m_production_ext)
            stream << " " << PUUID_ATTR << "=\"" << BUILD_UUID << "\"";
        stream << ">\n";
        for (const BuildItem& item : build_items) {
            stream << "  <" << ITEM_TAG << " " << OBJECTID_ATTR << "=\"" << item.id;
            if (m_production_ext)
                stream << "\" " << PUUID_ATTR << "=\"" << hex_wrap<boost::uint32_t>{item.id} << BUILD_UUID_SUFFIX;
            if (!item.path.empty())
                stream << "\" " << PPATH_ATTR << "=\"" << xml_escape(item.path);
            stream << "\" " << TRANSFORM_ATTR << "=\"";
            for (unsigned c = 0; c < 4; ++c) {
                for (unsigned r = 0; r < 3; ++r) {
                    stream << item.transform(r, c);
                    if (r != 2 || c != 3)
                        stream << " ";
                }
            }
            stream << "\" " << PRINTABLE_ATTR << "=\"" << item.printable << "\"/>\n";
        }
        stream << " </" << BUILD_TAG << ">\n";
        return true;
    }
References BUILD_TAG, BUILD_UUID, BUILD_UUID_SUFFIX, ITEM_TAG, OBJECTID_ATTR, PPATH_ATTR, PRINTABLE_ATTR, PUUID_ATTR, TRANSFORM_ATTR, and Slic3r::xml_escape().
_add_calibration_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_calibration_file_to_archive (mz_zip_archive & archive, const ThumbnailData & thumbnail_data, int index) private
    {
        bool res = false;
        /*size_t png_size = 0;
        void* png_data = tdefl_write_image_to_png_file_in_memory_ex((const void*)thumbnail_data.pixels.data(), thumbnail_data.width, thumbnail_data.height, 4, &png_size, MZ_DEFAULT_COMPRESSION, 1);
        if (png_data != nullptr) {
            std::string thumbnail_name = (boost::format(PATTERN_FILE_FORMAT) % (index + 1)).str();
            res = mz_zip_writer_add_mem(&archive, thumbnail_name.c_str(), (const void*)png_data, png_size, MZ_NO_COMPRESSION);
            mz_free(png_data);
        }
        if (!res) {
            add_error("Unable to add thumbnail file to archive");
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Unable to add thumbnail file to archive\n");
        }*/
        return res;
    }
_add_content_types_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_content_types_file_to_archive (mz_zip_archive & archive) private
    {
        std::stringstream stream;
        stream << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
        stream << "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">\n";
        stream << " <Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>\n";
        stream << " <Default Extension=\"model\" ContentType=\"application/vnd.ms-package.3dmanufacturing-3dmodel+xml\"/>\n";
        stream << " <Default Extension=\"png\" ContentType=\"image/png\"/>\n";
        stream << " <Default Extension=\"gcode\" ContentType=\"text/x.gcode\"/>\n";
        stream << "</Types>";
        std::string out = stream.str();
        if (!mz_zip_writer_add_mem(&archive, CONTENT_TYPES_FILE.c_str(), (const void*)out.data(), out.length(), MZ_DEFAULT_COMPRESSION)) {
            add_error("Unable to add content types file to archive");
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Unable to add content types file to archive\n");
            return false;
        }
        return true;
    }
References CONTENT_TYPES_FILE, error, MZ_DEFAULT_COMPRESSION, mz_zip_writer_add_mem(), and out.
_add_custom_gcode_per_print_z_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_custom_gcode_per_print_z_file_to_archive (mz_zip_archive & archive, Model & model, const DynamicPrintConfig * config) private
{
    //BBS: add plate tree related logic
    std::string out = "";
    bool has_custom_gcode = false;
    pt::ptree tree;
    pt::ptree& main_tree = tree.add("custom_gcodes_per_layer", "");
    for (auto custom_gcodes : model.plates_custom_gcodes) {
            has_custom_gcode = true;
            pt::ptree& plate_tree = main_tree.add("plate", "");
            pt::ptree& plate_idx_tree = plate_tree.add("plate_info", "");
            plate_idx_tree.put("<xmlattr>.id", custom_gcodes.first + 1);
            // store data of custom_gcode_per_print_z
            for (const CustomGCode::Item& code : custom_gcodes.second.gcodes) {
                pt::ptree& code_tree = plate_tree.add("layer", "");
                code_tree.put("<xmlattr>.top_z", code.print_z);
                code_tree.put("<xmlattr>.type", static_cast<int>(code.type));
                code_tree.put("<xmlattr>.extruder", code.extruder);
                code_tree.put("<xmlattr>.color", code.color);
                code_tree.put("<xmlattr>.extra", code.extra);
                //BBS
                std::string gcode = //code.type == CustomGCode::ColorChange ? config->opt_string("color_change_gcode")    :
                    code.type == CustomGCode::PausePrint ? config->opt_string("machine_pause_gcode") :
                    code.type == CustomGCode::Template ? config->opt_string("template_custom_gcode") :
                    code.type == CustomGCode::ToolChange ? "tool_change" : code.extra;
                code_tree.put("<xmlattr>.gcode", gcode);
            }
            pt::ptree& mode_tree = plate_tree.add("mode", "");
            // store mode of a custom_gcode_per_print_z
            mode_tree.put("<xmlattr>.value", custom_gcodes.second.mode == CustomGCode::Mode::SingleExtruder ? CustomGCode::SingleExtruderMode :
                custom_gcodes.second.mode == CustomGCode::Mode::MultiAsSingle ? CustomGCode::MultiAsSingleMode :
                CustomGCode::MultiExtruderMode);
    }
    if (has_custom_gcode) {
        std::ostringstream oss;
        boost::property_tree::write_xml(oss, tree);
        out = oss.str();
        // Post processing("beautification") of the output string
        boost::replace_all(out, "><", ">\n<");
    }
    if (!out.empty()) {
        if (!mz_zip_writer_add_mem(&archive, CUSTOM_GCODE_PER_PRINT_Z_FILE.c_str(), (const void*)out.data(), out.length(), MZ_DEFAULT_COMPRESSION)) {
            add_error("Unable to add custom Gcodes per print_z file to archive");
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Unable to add custom Gcodes per print_z file to archive\n");
            return false;
        }
    }
    return true;
}
References CUSTOM_GCODE_PER_PRINT_Z_FILE, error, MZ_DEFAULT_COMPRESSION, mz_zip_writer_add_mem(), Slic3r::DynamicConfig::opt_string(), out, and Slic3r::Model::plates_custom_gcodes.
_add_cut_information_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_cut_information_file_to_archive (mz_zip_archive & archive, Model & model) private
    {
        std::string out = "";
        pt::ptree   tree;
        unsigned int object_cnt = 0;
        for (const ModelObject *object : model.objects) {
            object_cnt++;
            pt::ptree &obj_tree = tree.add("objects.object", "");
            obj_tree.put("<xmlattr>.id", object_cnt);
            // Store info for cut_id
            pt::ptree &cut_id_tree = obj_tree.add("cut_id", "");
            // store cut_id atributes
            cut_id_tree.put("<xmlattr>.id", object->cut_id.id().id);
            cut_id_tree.put("<xmlattr>.check_sum", object->cut_id.check_sum());
            cut_id_tree.put("<xmlattr>.connectors_cnt", object->cut_id.connectors_cnt());
            int volume_idx = -1;
            for (const ModelVolume *volume : object->volumes) {
                ++volume_idx;
                if (volume->is_cut_connector()) {
                    pt::ptree &connectors_tree = obj_tree.add("connectors.connector", "");
                    connectors_tree.put("<xmlattr>.volume_id", volume_idx);
                    connectors_tree.put("<xmlattr>.type", int(volume->cut_info.connector_type));
                    connectors_tree.put("<xmlattr>.radius", volume->cut_info.radius);
                    connectors_tree.put("<xmlattr>.height", volume->cut_info.height);
                    connectors_tree.put("<xmlattr>.r_tolerance", volume->cut_info.radius_tolerance);
                    connectors_tree.put("<xmlattr>.h_tolerance", volume->cut_info.height_tolerance);
                }
            }
        }
        if (!tree.empty()) {
            std::ostringstream oss;
            pt::write_xml(oss, tree);
            out = oss.str();
            // Post processing("beautification") of the output string for a better preview
            boost::replace_all(out, "><object", ">\n <object");
            boost::replace_all(out, "><cut_id", ">\n  <cut_id");
            boost::replace_all(out, "></cut_id>", ">\n  </cut_id>");
            boost::replace_all(out, "><connectors", ">\n  <connectors");
            boost::replace_all(out, "></connectors>", ">\n  </connectors>");
            boost::replace_all(out, "><connector", ">\n   <connector");
            boost::replace_all(out, "></connector>", ">\n   </connector>");
            boost::replace_all(out, "></object>", ">\n </object>");
            // OR just
            boost::replace_all(out, "><", ">\n<");
        }
        if (!out.empty()) {
            if (!mz_zip_writer_add_mem(&archive, CUT_INFORMATION_FILE.c_str(), (const void *) out.data(), out.length(), MZ_DEFAULT_COMPRESSION)) {
                add_error("Unable to add cut information file to archive");
                return false;
            }
        }
        return true;
    }
References CUT_INFORMATION_FILE, MZ_DEFAULT_COMPRESSION, mz_zip_writer_add_mem(), Slic3r::Model::objects, and out.
_add_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_file_to_archive (mz_zip_archive & archive, const std::string & path_in_zip, const std::string & file_path) private
    {
        static std::string const nocomp_exts[] = {".png", ".jpg", ".mp4", ".jpeg", ".zip", ".3mf"};
        auto end = nocomp_exts + sizeof(nocomp_exts) / sizeof(nocomp_exts[0]);
        bool nocomp = std::find_if(nocomp_exts, end, [&path_in_zip](auto & ext) { return boost::algorithm::ends_with(path_in_zip, ext); }) != end;
#if WRITE_ZIP_LANGUAGE_ENCODING
        bool result = mz_zip_writer_add_file(&archive, path_in_zip.c_str(), encode_path(src_file_path.c_str()).c_str(), NULL, 0, nocomp ? MZ_NO_COMPRESSION : MZ_DEFAULT_LEVEL);
#else
        std::string native_path = encode_path(path_in_zip.c_str());
        std::string extra = ZipUnicodePathExtraField::encode(path_in_zip, native_path);
        bool result = mz_zip_writer_add_file_ex(&archive, native_path.c_str(), encode_path(src_file_path.c_str()).c_str(), NULL, 0, nocomp ? MZ_ZIP_FLAG_ASCII_FILENAME : MZ_DEFAULT_COMPRESSION,
                extra.c_str(), extra.length(), extra.c_str(), extra.length());
#endif
        if (!result) {
            add_error("Unable to add file " + src_file_path + " to archive");
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", Unable to add file %1% to archive %2%\n") % src_file_path % path_in_zip;
        } else {
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", add file %1% to archive %2%\n") % src_file_path % path_in_zip;
        }
        return result;
    }
References ZipUnicodePathExtraField::encode(), Slic3r::encode_path(), end, error, MZ_DEFAULT_COMPRESSION, MZ_DEFAULT_LEVEL, MZ_NO_COMPRESSION, MZ_ZIP_FLAG_ASCII_FILENAME, mz_zip_writer_add_file(), mz_zip_writer_add_file_ex(), and NULL.
_add_gcode_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_gcode_file_to_archive (mz_zip_archive & archive, const Model & model, PlateDataPtrs & plate_data_list, Export3mfProgressFn proFn = nullptr) private
{
    bool result = true;
    bool cb_cancel = false;
    PlateDataPtrs plate_data_list2;
    for (unsigned int i = 0; i < (unsigned int)plate_data_list.size(); ++i)
    {
        if (proFn) {
            proFn(EXPORT_STAGE_ADD_GCODE, i, plate_data_list.size(), cb_cancel);
            if (cb_cancel)
                return false;
        }
        PlateData* plate_data = plate_data_list[i];
        if (!plate_data->gcode_file.empty() && plate_data->is_sliced_valid && boost::filesystem::exists(plate_data->gcode_file)) {
            plate_data_list2.push_back(plate_data);
        }
    }
    boost::mutex mutex;
    tbb::parallel_for(tbb::blocked_range<size_t>(0, plate_data_list2.size(), 1), [this, &plate_data_list2, &root_archive = archive, &mutex, &result](const tbb::blocked_range<size_t>& range) {
        for (int i = range.begin(); i < range.end(); ++i) {
            PlateData* plate_data = plate_data_list2[i];
            auto src_gcode_file = plate_data->gcode_file;
            std::string gcode_in_3mf = (boost::format(GCODE_FILE_FORMAT) % (plate_data->plate_index + 1)).str();
            plate_data->gcode_file = gcode_in_3mf;
            mz_zip_archive archive;
            mz_zip_writer_staged_context context;
            mz_zip_zero_struct(&archive);
            mz_zip_writer_init_heap(&archive, 0, 1024 * 1024);
            {
                mz_zip_writer_add_staged_open(&archive, &context, gcode_in_3mf.c_str(), m_zip64 ? (uint64_t(1) << 30) * 16 : (uint64_t(1) << 32) - 1, nullptr, nullptr, 0,
                    MZ_DEFAULT_COMPRESSION, nullptr, 0, nullptr, 0);
                boost::filesystem::path src_gcode_path(src_gcode_file);
                if (!boost::filesystem::exists(src_gcode_path)) {
                    BOOST_LOG_TRIVIAL(error) << "Gcode is missing, filename = " << src_gcode_file;
                    result = false;
                }
                boost::filesystem::ifstream ifs(src_gcode_file, std::ios::binary);
                std::string buf(64 * 1024, 0);
                while (ifs) {
                    ifs.read(buf.data(), buf.size());
                    mz_zip_writer_add_staged_data(&context, buf.data(), ifs.gcount());
                }
                mz_zip_writer_add_staged_finish(&context);
            }
            void *ppBuf; size_t pSize;
            mz_zip_writer_finalize_heap_archive(&archive, &ppBuf, &pSize);
            mz_zip_writer_end(&archive);
            mz_zip_zero_struct(&archive);
            mz_zip_reader_init_mem(&archive, ppBuf, pSize, 0);
            {
                boost::unique_lock l(mutex);
                mz_zip_writer_add_from_zip_reader(&root_archive, &archive, 0);
            }
            mz_zip_reader_end(&archive);
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", store  %1% to 3mf %2%\n") % src_gcode_file % gcode_in_3mf;
        }
    });
    return result;
}
References Slic3r::EXPORT_STAGE_ADD_GCODE, Slic3r::PlateData::gcode_file, int, Slic3r::PlateData::is_sliced_valid, and Slic3r::range().
_add_layer_config_ranges_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_layer_config_ranges_file_to_archive (mz_zip_archive & archive, Model & model) private
    {
        std::string out = "";
        pt::ptree tree;
        unsigned int object_cnt = 0;
        for (const ModelObject* object : model.objects) {
            object_cnt++;
            const t_layer_config_ranges& ranges = object->layer_config_ranges;
            if (!ranges.empty())
            {
                pt::ptree& obj_tree = tree.add("objects.object","");
                obj_tree.put("<xmlattr>.id", object_cnt);
                // Store the layer config ranges.
                for (const auto& range : ranges) {
                    pt::ptree& range_tree = obj_tree.add("range", "");
                    // store minX and maxZ
                    range_tree.put("<xmlattr>.min_z", range.first.first);
                    range_tree.put("<xmlattr>.max_z", range.first.second);
                    // store range configuration
                    const ModelConfig& config = range.second;
                    for (const std::string& opt_key : config.keys()) {
                        pt::ptree& opt_tree = range_tree.add("option", config.opt_serialize(opt_key));
                        opt_tree.put("<xmlattr>.opt_key", opt_key);
                    }
                }
            }
        }
        if (!tree.empty()) {
            std::ostringstream oss;
            pt::write_xml(oss, tree);
            out = oss.str();
            // Post processing("beautification") of the output string for a better preview
            boost::replace_all(out, "><object",      ">\n <object");
            boost::replace_all(out, "><range",       ">\n  <range");
            boost::replace_all(out, "><option",      ">\n   <option");
            boost::replace_all(out, "></range>",     ">\n  </range>");
            boost::replace_all(out, "></object>",    ">\n </object>");
            // OR just
            boost::replace_all(out, "><",            ">\n<");
        }
        if (!out.empty()) {
            if (!mz_zip_writer_add_mem(&archive, LAYER_CONFIG_RANGES_FILE.c_str(), (const void*)out.data(), out.length(), MZ_DEFAULT_COMPRESSION)) {
                add_error("Unable to add layer heights profile file to archive");
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format("Unable to add layer heights profile file to archive\n");
                return false;
            }
        }
        return true;
    }
References error, Slic3r::ModelConfig::keys(), LAYER_CONFIG_RANGES_FILE, MZ_DEFAULT_COMPRESSION, mz_zip_writer_add_mem(), Slic3r::Model::objects, Slic3r::ModelConfig::opt_serialize(), out, and Slic3r::range().
_add_layer_height_profile_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_layer_height_profile_file_to_archive (mz_zip_archive & archive, Model & model) private
    {
        assert(is_decimal_separator_point());
        std::string out = "";
        char buffer[1024];
        unsigned int count = 0;
        for (const ModelObject* object : model.objects) {
            ++count;
            const std::vector<double>& layer_height_profile = object->layer_height_profile.get();
            if (layer_height_profile.size() >= 4 && layer_height_profile.size() % 2 == 0) {
                sprintf(buffer, "object_id=%d|", count);
                out += buffer;
                // Store the layer height profile as a single semicolon separated list.
                for (size_t i = 0; i < layer_height_profile.size(); ++i) {
                    sprintf(buffer, (i == 0) ? "%f" : ";%f", layer_height_profile[i]);
                    out += buffer;
                }
                out += "\n";
            }
        }
        if (!out.empty()) {
            if (!mz_zip_writer_add_mem(&archive, BBS_LAYER_HEIGHTS_PROFILE_FILE.c_str(), (const void*)out.data(), out.length(), MZ_DEFAULT_COMPRESSION)) {
                add_error("Unable to add layer heights profile file to archive");
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format("Unable to add layer heights profile file to archive\n");
                return false;
            }
        }
        return true;
    }
References BBS_LAYER_HEIGHTS_PROFILE_FILE, buffer, count, error, Slic3r::is_decimal_separator_point(), MZ_DEFAULT_COMPRESSION, mz_zip_writer_add_mem(), Slic3r::Model::objects, and out.
_add_mesh_to_object_stream()
bool Slic3r::_BBS_3MF_Exporter::_add_mesh_to_object_stream (std::function< bool(std::string &, bool)> const & flush, ObjectData const & object_data) const private
    {
        std::string output_buffer;
#if 0
        auto flush = [this, &output_buffer, &context](bool force = false) {
            if ((force && ! output_buffer.empty()) || output_buffer.size() >= 65536 * 16) {
                if (! mz_zip_writer_add_staged_data(&context, output_buffer.data(), output_buffer.size())) {
                    add_error("Error during writing or compression");
                    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Error during writing or compression\n");
                    return false;
                }
                output_buffer.clear();
            }
            return true;
        };
#endif
        /*output_buffer += "   <";
        output_buffer += MESH_TAG;
        output_buffer += ">\n    <";
        output_buffer += VERTICES_TAG;
        output_buffer += ">\n";*/
        auto format_coordinate = [](float f, char *buf) -> char* {
            assert(is_decimal_separator_point());
#if EXPORT_3MF_USE_SPIRIT_KARMA_FP
            // Slightly faster than sprintf("%.9g"), but there is an issue with the karma floating point formatter,
            // https://github.com/boostorg/spirit/pull/586
            // where the exported string is one digit shorter than it should be to guarantee lossless round trip.
            // The code is left here for the ocasion boost guys improve.
            coordinate_type_fixed      const coordinate_fixed      = coordinate_type_fixed();
            coordinate_type_scientific const coordinate_scientific = coordinate_type_scientific();
            // Format "f" in a fixed format.
            char *ptr = buf;
            boost::spirit::karma::generate(ptr, coordinate_fixed, f);
            // Format "f" in a scientific format.
            char *ptr2 = ptr;
            boost::spirit::karma::generate(ptr2, coordinate_scientific, f);
            // Return end of the shorter string.
            auto len2 = ptr2 - ptr;
            if (ptr - buf > len2) {
                // Move the shorter scientific form to the front.
                memcpy(buf, ptr, len2);
                ptr = buf + len2;
            }
            // Return pointer to the end.
            return ptr;
#else
            // Round-trippable float, shortest possible.
            return buf + sprintf(buf, "%.9g", f);
#endif
        };
        auto const & object = *object_data.object;
        char buf[256];
        unsigned int vertices_count = 0;
        //unsigned int triangles_count = 0;
        for (ModelVolume* volume : object.volumes) {
            if (volume == nullptr)
                continue;
            int volume_id = object_data.volumes_objectID.find(volume)->second;
            if (m_share_mesh && volume_id == 0)
                continue;
      //if (!volume->mesh().stats().repaired())
      //  throw Slic3r::FileIOError("store_3mf() requires repair()");
            const indexed_triangle_set &its = volume->mesh().its;
            if (its.vertices.empty()) {
                add_error("Found invalid mesh");
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Found invalid mesh\n");
                return false;
            }
            std::string type = (volume->type() == ModelVolumeType::MODEL_PART)?"model":"other";
            output_buffer += "  <";
            output_buffer += OBJECT_TAG;
            output_buffer += " id=\"";
            output_buffer += std::to_string(volume_id);
            /*if (m_production_ext) {
                std::stringstream stream;
                reset_stream(stream);
                stream << "\" " << PUUID_ATTR << "=\"" << hex_wrap<boost::uint32_t>{(boost::uint32_t)backup_id} << OBJECT_UUID_SUFFIX;
                //output_buffer += "\" ";
                //output_buffer += PUUID_ATTR;
                //output_buffer += "=\"";
                //output_buffer += std::to_string(hex_wrap<boost::uint32_t>{(boost::uint32_t)backup_id});
                //output_buffer += OBJECT_UUID_SUFFIX;
                output_buffer += stream.str();
            }*/
            output_buffer += "\" type=\"";
            output_buffer += type;
            output_buffer += "\">\n";
            output_buffer += "   <";
            output_buffer += MESH_TAG;
            output_buffer += ">\n    <";
            output_buffer += VERTICES_TAG;
            output_buffer += ">\n";
            vertices_count += (int)its.vertices.size();
            for (size_t i = 0; i < its.vertices.size(); ++i) {
                //don't save the volume's matrix into vertex data
                //add the shared mesh logic
                //Vec3f v = (matrix * its.vertices[i].cast<double>()).cast<float>();
                Vec3f v = its.vertices[i];
                char* ptr = buf;
                boost::spirit::karma::generate(ptr, boost::spirit::lit("     <") << VERTEX_TAG << " x=\"");
                ptr = format_coordinate(v.x(), ptr);
                boost::spirit::karma::generate(ptr, "\" y=\"");
                ptr = format_coordinate(v.y(), ptr);
                boost::spirit::karma::generate(ptr, "\" z=\"");
                ptr = format_coordinate(v.z(), ptr);
                boost::spirit::karma::generate(ptr, "\"/>\n");
                *ptr = '\0';
                output_buffer += buf;
                if (!flush(output_buffer, false))
                    return false;
            }
        //}
            output_buffer += "    </";
            output_buffer += VERTICES_TAG;
            output_buffer += ">\n    <";
            output_buffer += TRIANGLES_TAG;
            output_buffer += ">\n";
        //for (ModelVolume* volume : object.volumes) {
        //    if (volume == nullptr)
        //        continue;
            //BBS: as we stored matrix seperately, not multiplied into vertex
            //we don't need to consider this left hand case specially
            //bool is_left_handed = volume->is_left_handed();
            bool is_left_handed = false;
            //VolumeToOffsetsMap::iterator volume_it = volumes_objectID.find(volume);
            //assert(volume_it != volumes_objectID.end());
            //const indexed_triangle_set &its = volume->mesh().its;
            // updates triangle offsets
            //unsigned int first_triangle_id = triangles_count;
            //triangles_count += (int)its.indices.size();
            //unsigned int last_triangle_id = triangles_count - 1;
            for (int i = 0; i < int(its.indices.size()); ++ i) {
                {
                    const Vec3i &idx = its.indices[i];
                    char *ptr = buf;
                    boost::spirit::karma::generate(ptr, boost::spirit::lit("     <") << TRIANGLE_TAG <<
                        " v1=\"" << boost::spirit::int_ <<
                        "\" v2=\"" << boost::spirit::int_ <<
                        "\" v3=\"" << boost::spirit::int_ << "\"",
                        idx[is_left_handed ? 2 : 0],
                        idx[1],
                        idx[is_left_handed ? 0 : 2]);
                    *ptr = '\0';
                    output_buffer += buf;
                }
                std::string custom_supports_data_string = volume->supported_facets.get_triangle_as_string(i);
                if (! custom_supports_data_string.empty()) {
                    output_buffer += " ";
                    output_buffer += CUSTOM_SUPPORTS_ATTR;
                    output_buffer += "=\"";
                    output_buffer += custom_supports_data_string;
                    output_buffer += "\"";
                }
                std::string custom_seam_data_string = volume->seam_facets.get_triangle_as_string(i);
                if (! custom_seam_data_string.empty()) {
                    output_buffer += " ";
                    output_buffer += CUSTOM_SEAM_ATTR;
                    output_buffer += "=\"";
                    output_buffer += custom_seam_data_string;
                    output_buffer += "\"";
                }
                std::string mmu_painting_data_string = volume->mmu_segmentation_facets.get_triangle_as_string(i);
                if (! mmu_painting_data_string.empty()) {
                    output_buffer += " ";
                    output_buffer += MMU_SEGMENTATION_ATTR;
                    output_buffer += "=\"";
                    output_buffer += mmu_painting_data_string;
                    output_buffer += "\"";
                }
                // BBS
                if (i < its.properties.size()) {
                    std::string prop_str = its.properties[i].to_string();
                    if (!prop_str.empty()) {
                        output_buffer += " ";
                        output_buffer += FACE_PROPERTY_ATTR;
                        output_buffer += "=\"";
                        output_buffer += prop_str;
                        output_buffer += "\"";
                    }
                }
                output_buffer += "/>\n";
                if (! flush(output_buffer, false))
                    return false;
            }
            output_buffer += "    </";
            output_buffer += TRIANGLES_TAG;
            output_buffer += ">\n   </";
            output_buffer += MESH_TAG;
            output_buffer += ">\n";
            output_buffer +=  "  </";
            output_buffer += OBJECT_TAG;
            output_buffer += ">\n";
        }
        // Force flush.
        return flush(output_buffer, true);
    }
References CUSTOM_SEAM_ATTR, CUSTOM_SUPPORTS_ATTR, error, FACE_PROPERTY_ATTR, indexed_triangle_set::indices, int, Slic3r::is_decimal_separator_point(), memcpy, MESH_TAG, MMU_SEGMENTATION_ATTR, mz_zip_writer_add_staged_data(), Slic3r::_BBS_3MF_Exporter::ObjectData::object, OBJECT_TAG, indexed_triangle_set::properties, ptr, TRIANGLE_TAG, TRIANGLES_TAG, VERTEX_TAG, indexed_triangle_set::vertices, VERTICES_TAG, and Slic3r::_BBS_3MF_Exporter::ObjectData::volumes_objectID.
_add_model_config_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive (mz_zip_archive & archive, const Model & model, PlateDataPtrs & plate_data_list, const ObjectToObjectDataMap & objects_data, int export_plate_idx = -1, bool save_gcode = true, bool use_loaded_id = false) private
    {
        std::stringstream stream;
        // Store mesh transformation in full precision, as the volumes are stored transformed and they need to be transformed back
        // when loaded as accurately as possible.
    stream << std::setprecision(std::numeric_limits<double>::max_digits10);
        stream << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
        stream << "<" << CONFIG_TAG << ">\n";
        if (!m_skip_model)
        for (const ObjectToObjectDataMap::value_type& obj_metadata : objects_data) {
            auto object_data = obj_metadata.second;
            const ModelObject *obj = object_data.object;
            if (obj != nullptr) {
                // Output of instances count added because of github #3435, currently not used by PrusaSlicer
                //stream << "  <"  << OBJECT_TAG << " " << ID_ATTR << "=\"" << obj_metadata.first << "\" " << INSTANCESCOUNT_ATTR << "=\"" << obj->instances.size() << "\">\n";
                stream << "  <" << OBJECT_TAG << " " << ID_ATTR << "=\"" << object_data.object_id << "\">\n";
                // stores object's name
                if (!obj->name.empty())
                    stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"name\" " << VALUE_ATTR << "=\"" << xml_escape(obj->name) << "\"/>\n";
                //BBS: store object's module name
                if (!obj->module_name.empty())
                    stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"module\" " << VALUE_ATTR << "=\"" << xml_escape(obj->module_name) << "\"/>\n";
                // stores object's config data
                for (const std::string& key : obj->config.keys()) {
                    stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << key << "\" " << VALUE_ATTR << "=\"" << obj->config.opt_serialize(key) << "\"/>\n";
                }
                for (const ModelVolume* volume : obj_metadata.second.object->volumes) {
                    if (volume != nullptr) {
                        const VolumeToObjectIDMap& objectIDs = obj_metadata.second.volumes_objectID;
                        VolumeToObjectIDMap::const_iterator it = objectIDs.find(volume);
                        if (it != objectIDs.end()) {
                            // stores volume's offsets
                            stream << "    <" << PART_TAG << " ";
                            //stream << FIRST_TRIANGLE_ID_ATTR << "=\"" << it->second.first_triangle_id << "\" ";
                            //stream << LAST_TRIANGLE_ID_ATTR << "=\"" << it->second.last_triangle_id << "\" ";
                            int volume_id = it->second;
                            if (m_share_mesh && volume_id == 0)
                                volume_id = m_volume_paths.find(volume)->second.second;
                            stream << ID_ATTR << "=\"" << volume_id << "\" ";
                            stream << SUBTYPE_ATTR << "=\"" << ModelVolume::type_to_string(volume->type()) << "\">\n";
                            //stream << "    <" << PART_TAG << " " << ID_ATTR << "=\"" << it->second << "\" " << SUBTYPE_ATTR << "=\"" << ModelVolume::type_to_string(volume->type()) << "\">\n";
                            // stores volume's name
                            if (!volume->name.empty())
                                stream << "      <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << NAME_KEY << "\" " << VALUE_ATTR << "=\"" << xml_escape(volume->name) << "\"/>\n";
                                //stream << "      <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << NAME_KEY << "\" " << VALUE_ATTR << "=\"" << xml_escape(volume->name) << "\"/>\n";
                            // stores volume's modifier field (legacy, to support old slicers)
                            /*if (volume->is_modifier())
                                stream << "      <" << METADATA_TAG << " " << TYPE_ATTR << "=\"" << PART_TYPE << "\" " << KEY_ATTR << "=\"" << MODIFIER_KEY << "\" " << VALUE_ATTR << "=\"1\"/>\n";
                            // stores volume's type (overrides the modifier field above)
                            stream << "      <" << METADATA_TAG << " " << TYPE_ATTR << "=\"" << PART_TYPE << "\" " << KEY_ATTR << "=\"" << PART_TYPE_KEY << "\" " <<
                                VALUE_ATTR << "=\"" << ModelVolume::type_to_string(volume->type()) << "\"/>\n";*/
                            // stores volume's local matrix
                            stream << "      <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << MATRIX_KEY << "\" " << VALUE_ATTR << "=\"";
                            Transform3d matrix = volume->get_matrix() * volume->source.transform.get_matrix();
                            for (int r = 0; r < 4; ++r) {
                                for (int c = 0; c < 4; ++c) {
                                    stream << matrix(r, c);
                                    if (r != 3 || c != 3)
                                        stream << " ";
                                }
                            }
                            stream << "\"/>\n";
                            // stores volume's source data
{
                                std::string input_file = xml_escape(m_fullpath_sources ? volume->source.input_file : boost::filesystem::path(volume->source.input_file).filename().string());
                                //std::string prefix = std::string("      <") + METADATA_TAG + " " + KEY_ATTR + "=\"";
                                std::string prefix = std::string("      <") + METADATA_TAG + " " + KEY_ATTR + "=\"";
                                if (! volume->source.input_file.empty()) {
                                    stream << prefix << SOURCE_FILE_KEY      << "\" " << VALUE_ATTR << "=\"" << input_file << "\"/>\n";
                                    stream << prefix << SOURCE_OBJECT_ID_KEY << "\" " << VALUE_ATTR << "=\"" << volume->source.object_idx << "\"/>\n";
                                    stream << prefix << SOURCE_VOLUME_ID_KEY << "\" " << VALUE_ATTR << "=\"" << volume->source.volume_idx << "\"/>\n";
                                    stream << prefix << SOURCE_OFFSET_X_KEY  << "\" " << VALUE_ATTR << "=\"" << volume->source.mesh_offset(0) << "\"/>\n";
                                    stream << prefix << SOURCE_OFFSET_Y_KEY  << "\" " << VALUE_ATTR << "=\"" << volume->source.mesh_offset(1) << "\"/>\n";
                                    stream << prefix << SOURCE_OFFSET_Z_KEY  << "\" " << VALUE_ATTR << "=\"" << volume->source.mesh_offset(2) << "\"/>\n";
                                }
                                assert(! volume->source.is_converted_from_inches || ! volume->source.is_converted_from_meters);
                                if (volume->source.is_converted_from_inches)
                                    stream << prefix << SOURCE_IN_INCHES << "\" " << VALUE_ATTR << "=\"1\"/>\n";
                                else if (volume->source.is_converted_from_meters)
                                    stream << prefix << SOURCE_IN_METERS << "\" " << VALUE_ATTR << "=\"1\"/>\n";
                            }
                            // stores volume's config data
                            for (const std::string& key : volume->config.keys()) {
                                stream << "      <" << METADATA_TAG << " "<< KEY_ATTR << "=\"" << key << "\" " << VALUE_ATTR << "=\"" << volume->config.opt_serialize(key) << "\"/>\n";
                            }
                            const TextInfo &text_info = volume->get_text_info();
                            if (!text_info.m_text.empty())
                                _add_text_info_to_archive(stream, text_info);
                            // stores mesh's statistics
                            const RepairedMeshErrors& stats = volume->mesh().stats().repaired_errors;
                            stream << "      <" << MESH_STAT_TAG << " ";
                            stream << MESH_STAT_EDGES_FIXED        << "=\"" << stats.edges_fixed        << "\" ";
                            stream << MESH_STAT_DEGENERATED_FACETS << "=\"" << stats.degenerate_facets  << "\" ";
                            stream << MESH_STAT_FACETS_REMOVED     << "=\"" << stats.facets_removed     << "\" ";
                            stream << MESH_STAT_FACETS_RESERVED    << "=\"" << stats.facets_reversed    << "\" ";
                            stream << MESH_STAT_BACKWARDS_EDGES    << "=\"" << stats.backwards_edges    << "\"/>\n";
                            stream << "    </" << PART_TAG << ">\n";
                        }
                    }
                }
                stream << "  </" << OBJECT_TAG << ">\n";
            }
        }
        //BBS: store plate related logic
        std::vector<std::string> gcode_paths;
        for (unsigned int i = 0; i < (unsigned int)plate_data_list.size(); ++i)
        {
            PlateData* plate_data = plate_data_list[i];
            int instance_size = plate_data->objects_and_instances.size();
            if (plate_data != nullptr) {
                stream << "  <" << PLATE_TAG << ">\n";
                //plate index
                stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << PLATERID_ATTR << "\" " << VALUE_ATTR << "=\"" << plate_data->plate_index + 1 << "\"/>\n";
                stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << PLATER_NAME_ATTR << "\" " << VALUE_ATTR << "=\"" << xml_escape(plate_data->plate_name) << "\"/>\n";
                stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << LOCK_ATTR << "\" " << VALUE_ATTR << "=\"" << std::boolalpha<< plate_data->locked<< "\"/>\n";
                ConfigOption* bed_type_opt = plate_data->config.option("curr_bed_type");
                t_config_enum_names bed_type_names = ConfigOptionEnum<BedType>::get_enum_names();
                if (bed_type_opt != nullptr && bed_type_names.size() > bed_type_opt->getInt())
                    stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << BED_TYPE_ATTR << "\" " << VALUE_ATTR << "=\"" << bed_type_names[bed_type_opt->getInt()] << "\"/>\n";
                ConfigOption* print_sequence_opt = plate_data->config.option("print_sequence");
                t_config_enum_names print_sequence_names = ConfigOptionEnum<PrintSequence>::get_enum_names();
                if (print_sequence_opt != nullptr && print_sequence_names.size() > print_sequence_opt->getInt())
                    stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << PRINT_SEQUENCE_ATTR << "\" " << VALUE_ATTR << "=\"" << print_sequence_names[print_sequence_opt->getInt()] << "\"/>\n";
                if (save_gcode)
                    stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << GCODE_FILE_ATTR << "\" " << VALUE_ATTR << "=\"" << std::boolalpha << xml_escape(plate_data->gcode_file) << "\"/>\n";
                if (!plate_data->gcode_file.empty()) {
                    gcode_paths.push_back(plate_data->gcode_file);
                }
                if (plate_data->plate_thumbnail.is_valid()) {
                    std::string thumbnail_file_in_3mf = (boost::format(THUMBNAIL_FILE_FORMAT) % (plate_data->plate_index + 1)).str();
                    stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << THUMBNAIL_FILE_ATTR << "\" " << VALUE_ATTR << "=\"" << std::boolalpha << thumbnail_file_in_3mf << "\"/>\n";
                }
                else if (!plate_data->thumbnail_file.empty() && (boost::filesystem::exists(plate_data->thumbnail_file))){
                    std::string thumbnail_file_in_3mf = (boost::format(THUMBNAIL_FILE_FORMAT) % (plate_data->plate_index + 1)).str();
                    stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << THUMBNAIL_FILE_ATTR << "\" " << VALUE_ATTR << "=\"" << std::boolalpha << thumbnail_file_in_3mf << "\"/>\n";
                }
                if (!plate_data->top_file.empty()) {
                    std::string top_file_in_3mf = (boost::format(TOP_FILE_FORMAT) % (plate_data->plate_index + 1)).str();
                    stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << TOP_FILE_ATTR << "\" " << VALUE_ATTR << "=\"" << std::boolalpha << top_file_in_3mf << "\"/>\n";
                }
                if (!plate_data->pick_file.empty()) {
                    std::string pick_file_in_3mf = (boost::format(PICK_FILE_FORMAT) % (plate_data->plate_index + 1)).str();
                    stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << PICK_FILE_ATTR << "\" " << VALUE_ATTR << "=\"" << std::boolalpha << pick_file_in_3mf << "\"/>\n";
                }
                /*if (!plate_data->pattern_file.empty()) {
                    std::string pattern_file_in_3mf = (boost::format(PATTERN_FILE_FORMAT) % (plate_data->plate_index + 1)).str();
                    stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << PATTERN_FILE_ATTR << "\" " << VALUE_ATTR << "=\"" << std::boolalpha << pattern_file_in_3mf << "\"/>\n";
                }*/
                if (!plate_data->pattern_bbox_file.empty()) {
                    std::string pattern_bbox_file_in_3mf = (boost::format(PATTERN_CONFIG_FILE_FORMAT) % (plate_data->plate_index + 1)).str();
                    stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << PATTERN_BBOX_FILE_ATTR << "\" " << VALUE_ATTR << "=\"" << std::boolalpha << pattern_bbox_file_in_3mf << "\"/>\n";
                }
                if (!m_skip_model && instance_size > 0)
                {
                    for (unsigned int j = 0; j < instance_size; ++j)
                    {
                        stream << "    <" << INSTANCE_TAG << ">\n";
                        int obj_id = plate_data->objects_and_instances[j].first;
                        int inst_id = plate_data->objects_and_instances[j].second;
                        int identify_id = 0;
                        ModelObject* obj = NULL;
                        ModelInstance* inst = NULL;
                        if (obj_id >= model.objects.size()) {
                            BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << ":" << __LINE__ << boost::format("invalid object id %1%\n")%obj_id;
                        }
                        else
                            obj =  model.objects[obj_id];
                        if (obj && (inst_id >= obj->instances.size())) {
                            BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << ":" << __LINE__ << boost::format("invalid instance id %1%\n")%inst_id;
                        }
                        else if (obj){
                            inst =  obj->instances[inst_id];
                            if (use_loaded_id && (inst->loaded_id > 0))
                                identify_id = inst->loaded_id;
                            else
                                identify_id = inst->id().id;
                        }
                        obj_id = objects_data.find(obj)->second.object_id;
                        stream << "      <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << OBJECT_ID_ATTR << "\" " << VALUE_ATTR << "=\"" << obj_id << "\"/>\n";
                        stream << "      <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << INSTANCEID_ATTR << "\" " << VALUE_ATTR << "=\"" << inst_id << "\"/>\n";
                        stream << "      <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << IDENTIFYID_ATTR << "\" " << VALUE_ATTR << "=\"" << identify_id << "\"/>\n";
                        stream << "    </" << INSTANCE_TAG << ">\n";
                    }
                }
                stream << "  </" << PLATE_TAG << ">\n";
            }
        }
        // write model rels
        if (save_gcode)
            _add_relationships_file_to_archive(archive, BBS_MODEL_CONFIG_RELS_FILE, gcode_paths, {"http://schemas.bambulab.com/package/2021/gcode"}, Slic3r::PackingTemporaryData(), export_plate_idx);
        if (!m_skip_model) {
        //BBS: store assemble related info
        stream << "  <" << ASSEMBLE_TAG << ">\n";
        for (const ObjectToObjectDataMap::value_type& obj_metadata : objects_data) {
            auto object_data = obj_metadata.second;
            const ModelObject* obj = object_data.object;
            if (obj != nullptr) {
                for (int instance_idx = 0; instance_idx < obj->instances.size(); ++instance_idx) {
                    if (obj->instances[instance_idx]->is_assemble_initialized()) {
                        stream << "   <" << ASSEMBLE_ITEM_TAG << " " << OBJECT_ID_ATTR << "=\"" << object_data.object_id << "\" ";
                        stream << INSTANCEID_ATTR << "=\"" << instance_idx << "\" " << TRANSFORM_ATTR << "=\"";
                            for (unsigned c = 0; c < 4; ++c) {
                                for (unsigned r = 0; r < 3; ++r) {
                                    const Transform3d assemble_trans = obj->instances[instance_idx]->get_assemble_transformation().get_matrix();
                                    stream << assemble_trans(r, c);
                                    if (r != 2 || c != 3)
                                        stream << " ";
                                }
                            }
                        stream << "\" ";
                        stream << OFFSET_ATTR << "=\"";
                        const Vec3d ofs2ass = obj->instances[instance_idx]->get_offset_to_assembly();
                        stream << ofs2ass(0) << " " << ofs2ass(1) << " " << ofs2ass(2);
                    stream << "\" />\n";
                    }
                }
            }
        }
        stream << "  </" << ASSEMBLE_TAG << ">\n";
        }
        stream << "</" << CONFIG_TAG << ">\n";
        std::string out = stream.str();
        if (!mz_zip_writer_add_mem(&archive, BBS_MODEL_CONFIG_FILE.c_str(), (const void*)out.data(), out.length(), MZ_DEFAULT_COMPRESSION)) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format("Unable to add model config file to archive\n");
            add_error("Unable to add model config file to archive");
            return false;
        }
        return true;
    }
References Slic3r::_add_text_info_to_archive(), ASSEMBLE_ITEM_TAG, ASSEMBLE_TAG, Slic3r::RepairedMeshErrors::backwards_edges, BBS_MODEL_CONFIG_FILE, BBS_MODEL_CONFIG_RELS_FILE, BED_TYPE_ATTR, Slic3r::PlateData::config, Slic3r::ModelObject::config, CONFIG_TAG, Slic3r::RepairedMeshErrors::degenerate_facets, Slic3r::RepairedMeshErrors::edges_fixed, error, Slic3r::RepairedMeshErrors::facets_removed, Slic3r::RepairedMeshErrors::facets_reversed, Slic3r::PlateData::gcode_file, GCODE_FILE_ATTR, Slic3r::ConfigOption::getInt(), Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), ID_ATTR, IDENTIFYID_ATTR, INSTANCE_TAG, INSTANCEID_ATTR, Slic3r::ModelObject::instances, int, Slic3r::ThumbnailData::is_valid(), KEY_ATTR, Slic3r::ModelConfig::keys(), Slic3r::ModelInstance::loaded_id, LOCK_ATTR, Slic3r::PlateData::locked, Slic3r::TextInfo::m_text, MATRIX_KEY, MESH_STAT_BACKWARDS_EDGES, MESH_STAT_DEGENERATED_FACETS, MESH_STAT_EDGES_FIXED, MESH_STAT_FACETS_REMOVED, MESH_STAT_FACETS_RESERVED, MESH_STAT_TAG, METADATA_TAG, Slic3r::ModelObject::module_name, MZ_DEFAULT_COMPRESSION, mz_zip_writer_add_mem(), Slic3r::ModelObject::name, NAME_KEY, NULL, OBJECT_ID_ATTR, OBJECT_TAG, Slic3r::Model::objects, Slic3r::PlateData::objects_and_instances, OFFSET_ATTR, Slic3r::ModelConfig::opt_serialize(), Slic3r::ConfigBase::option(), out, PART_TAG, Slic3r::PlateData::pattern_bbox_file, PATTERN_BBOX_FILE_ATTR, PATTERN_CONFIG_FILE_FORMAT, Slic3r::PlateData::pick_file, PICK_FILE_ATTR, PICK_FILE_FORMAT, Slic3r::PlateData::plate_index, Slic3r::PlateData::plate_name, PLATE_TAG, Slic3r::PlateData::plate_thumbnail, PLATER_NAME_ATTR, PLATERID_ATTR, PRINT_SEQUENCE_ATTR, SOURCE_FILE_KEY, SOURCE_IN_INCHES, SOURCE_IN_METERS, SOURCE_OBJECT_ID_KEY, SOURCE_OFFSET_X_KEY, SOURCE_OFFSET_Y_KEY, SOURCE_OFFSET_Z_KEY, SOURCE_VOLUME_ID_KEY, SUBTYPE_ATTR, Slic3r::PlateData::thumbnail_file, THUMBNAIL_FILE_ATTR, THUMBNAIL_FILE_FORMAT, Slic3r::PlateData::top_file, TOP_FILE_ATTR, TOP_FILE_FORMAT, TRANSFORM_ATTR, VALUE_ATTR, and Slic3r::xml_escape().
_add_model_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_model_file_to_archive (const std::string & filename, mz_zip_archive & archive, const Model & model, ObjectToObjectDataMap & objects_data, Export3mfProgressFn proFn = nullptr, BBLProject * project = nullptr) const private
    {
        bool sub_model = !objects_data.empty();
        bool write_object = sub_model || !m_split_model;
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__ << boost::format(", filename %1%, m_split_model %2%,  sub_model %3%")%filename % m_split_model % sub_model;
#if WRITE_ZIP_LANGUAGE_ENCODING
        auto & zip_filename = filename;
#else
        std::string zip_filename = encode_path(filename.c_str());
        std::string extra = sub_model ? ZipUnicodePathExtraField::encode(filename, zip_filename) : "";
#endif
        mz_zip_writer_staged_context context;
        if (!mz_zip_writer_add_staged_open(&archive, &context, sub_model ? zip_filename.c_str() : MODEL_FILE.c_str(),
            m_zip64 ?
                // Maximum expected and allowed 3MF file size is 16GiB.
                // This switches the ZIP file to a 64bit mode, which adds a tiny bit of overhead to file records.
                (uint64_t(1) << 30) * 16 :
                // Maximum expected 3MF file size is 4GB-1. This is a workaround for interoperability with Windows 10 3D model fixing API, see
                // GH issue #6193.
                (uint64_t(1) << 32) - 1,
#if WRITE_ZIP_LANGUAGE_ENCODING
            nullptr, nullptr, 0, MZ_DEFAULT_LEVEL, nullptr, 0, nullptr, 0)) {
#else
            nullptr, nullptr, 0, MZ_DEFAULT_COMPRESSION, extra.c_str(), extra.length(), extra.c_str(), extra.length())) {
#endif
            add_error("Unable to add model file to archive");
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Unable to add model file to archive\n");
            return false;
        }
        {
            std::stringstream stream;
            reset_stream(stream);
            stream << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
            stream << "<" << MODEL_TAG << " unit=\"millimeter\" xml:lang=\"en-US\" xmlns=\"http://schemas.microsoft.com/3dmanufacturing/core/2015/02\" xmlns:slic3rpe=\"http://schemas.slic3r.org/3mf/2017/06\"";
            if (m_production_ext)
                stream << " xmlns:p=\"http://schemas.microsoft.com/3dmanufacturing/production/2015/06\" requiredextensions=\"p\"";
            stream << ">\n";
            std::string origin;
            std::string name;
            std::string user_name;
            std::string user_id;
            std::string design_cover;
            std::string license;
            std::string description;
            std::string copyright;
            std::string rating;
            std::string model_id;
            std::string region_code;
            if (model.design_info) {
                 user_name = model.design_info->Designer;
                 user_id = model.design_info->DesignerUserId;
                 BOOST_LOG_TRIVIAL(trace) << "design_info, save_3mf found designer = " << user_name;
                 BOOST_LOG_TRIVIAL(trace) << "design_info, save_3mf found designer_user_id = " << user_id;
            }
            if (project) {
                model_id    = project->project_model_id;
                region_code = project->project_country_code;
            }
            if (model.model_info) {
                design_cover = model.model_info->cover_file;
                license      = model.model_info->license;
                description  = model.model_info->description;
                copyright    = model.model_info->copyright;
                name         = model.model_info->model_name;
                origin       = model.model_info->origin;
                BOOST_LOG_TRIVIAL(trace) << "design_info, save_3mf found designer_cover = " << design_cover;
            }
            // remember to use metadata_item_map to store metadata info
            std::map<std::string, std::string> metadata_item_map;
            if (!sub_model) {
                // update metadat_items
                if (model.model_info && model.model_info.get()) {
                    metadata_item_map = model.model_info.get()->metadata_items;
                }
                metadata_item_map[BBL_MODEL_NAME_TAG]           = xml_escape(name);
                metadata_item_map[BBL_ORIGIN_TAG]               = xml_escape(origin);
                metadata_item_map[BBL_DESIGNER_TAG]             = xml_escape(user_name);
                metadata_item_map[BBL_DESIGNER_USER_ID_TAG]     = user_id;
                metadata_item_map[BBL_DESIGNER_COVER_FILE_TAG]  = xml_escape(design_cover);
                metadata_item_map[BBL_DESCRIPTION_TAG]          = xml_escape(description);
                metadata_item_map[BBL_COPYRIGHT_TAG]            = xml_escape(copyright);
                metadata_item_map[BBL_LICENSE_TAG]              = xml_escape(license);
                /* save model info */
                if (!model_id.empty()) {
                    metadata_item_map[BBL_MODEL_ID_TAG] = model_id;
                    metadata_item_map[BBL_REGION_TAG]   = region_code;
                }
                std::string date = Slic3r::Utils::utc_timestamp(Slic3r::Utils::get_current_time_utc());
                // keep only the date part of the string
                date = date.substr(0, 10);
                metadata_item_map[BBL_CREATION_DATE_TAG] = date;
                metadata_item_map[BBL_MODIFICATION_TAG]  = date;
                //SoftFever: write BambuStudio tag to keep it compatible
                metadata_item_map[BBL_APPLICATION_TAG] = (boost::format("%1%-%2%") % "BambuStudio" % SLIC3R_VERSION).str();
            }
            metadata_item_map[BBS_3MF_VERSION] = std::to_string(VERSION_BBS_3MF);
            // store metadata info
            for (auto item : metadata_item_map) {
                BOOST_LOG_TRIVIAL(info) << "bbs_3mf: save key= " << item.first << ", value = " << item.second;
                stream << " <" << METADATA_TAG << " name=\"" << item.first << "\">"
                       << xml_escape(item.second) << "</" << METADATA_TAG << ">\n";
            }
            stream << " <" << RESOURCES_TAG << ">\n";
            std::string buf = stream.str();
            if (! buf.empty() && ! mz_zip_writer_add_staged_data(&context, buf.data(), buf.size())) {
                add_error("Unable to add model file to archive");
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Unable to add model file to archive\n");
                return false;
            }
        }
        // Instance transformations, indexed by the 3MF object ID (which is a linear serialization of all instances of all ModelObjects).
        BuildItemsList build_items;
        // The object_id here is a one based identifier of the first instance of a ModelObject in the 3MF file, where
        // all the object instances of all ModelObjects are stored and indexed in a 1 based linear fashion.
        // Therefore the list of object_ids here may not be continuous.
        unsigned int object_id = 1;
        unsigned int object_index = 0;
        bool cb_cancel = false;
        std::vector<std::string> object_paths;
        // if (!m_skip_model) {
            for (ModelObject* obj : model.objects) {
                if (sub_model && obj != objects_data.begin()->second.object) continue;
                if (proFn) {
                    proFn(EXPORT_STAGE_ADD_MODELS, object_index++, model.objects.size(), cb_cancel);
                    if (cb_cancel)
                        return false;
                }
                if (obj == nullptr)
                    continue;
                // Index of an object in the 3MF file corresponding to the 1st instance of a ModelObject.
                ObjectToObjectDataMap::iterator object_it = objects_data.begin();
                if (!sub_model) {
                    // For backup, use backup id as object id
                    int backup_id = const_cast<Model&>(model).get_object_backup_id(*obj);
                    if (m_from_backup_save) object_id = backup_id;
                    object_it = objects_data.insert({obj, {obj, backup_id} }).first;
                    auto & object_data = object_it->second;
                    if (m_split_model) {
                        auto filename = boost::format("3D/Objects/%s_%d.model") % obj->name % backup_id;
                        object_data.sub_path = "/" + filename.str();
                        object_paths.push_back(filename.str());
                    }
                    auto &volumes_objectID = object_data.volumes_objectID;
                    unsigned int volume_id = object_id, volume_count = 0;
                    for (ModelVolume *volume : obj->volumes) {
                        if (volume == nullptr)
                            continue;
                        volume_count++;
                        if (m_share_mesh) {
                            auto iter = m_shared_meshes.find(volume->mesh_ptr());
                            if (iter != m_shared_meshes.end())
{
                                const ModelVolume* shared_volume = iter->second.second;
                                if ((shared_volume->supported_facets.equals(volume->supported_facets))
                                    && (shared_volume->seam_facets.equals(volume->seam_facets))
                                    && (shared_volume->mmu_segmentation_facets.equals(volume->mmu_segmentation_facets)))
{
                                    auto data = iter->second.first;
                                    const_cast<_BBS_3MF_Exporter *>(this)->m_volume_paths.insert({volume, {data->sub_path, data->volumes_objectID.find(iter->second.second)->second}});
                                    volumes_objectID.insert({volume, 0});
                                    object_data.share_mesh = true;
                                    continue;
                                }
                            }
                            const_cast<_BBS_3MF_Exporter *>(this)->m_shared_meshes.insert({volume->mesh_ptr(), {&object_data, volume}});
                        }
                        if (m_from_backup_save)
                            volume_id = (volume_count << 16 | backup_id);
                        volumes_objectID.insert({volume, volume_id});
                        volume_id++;
                    }
                    if (!m_from_backup_save) object_id = volume_id;
                    object_data.object_id = object_id;
                }
                if (m_skip_model) continue;
                if (write_object) {
                    // Store geometry of all ModelVolumes contained in a single ModelObject into a single 3MF indexed triangle set object.
                    // object_it->second.volumes_objectID will contain the offsets of the ModelVolumes in that single indexed triangle set.
                    // object_id will be increased to point to the 1st instance of the next ModelObject.
                    if (!_add_object_to_model_stream(context, object_it->second)) {
                        add_error("Unable to add object to archive");
                        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Unable to add object to archive\n");
                        return false;
                    }
                }
                if (sub_model) break;
                unsigned int count = 0;
                for (const ModelInstance* instance : obj->instances) {
                    Transform3d t = instance->get_matrix();
                    // instance_id is just a 1 indexed index in build_items.
                    //assert(m_skip_static || curr_id == build_items.size() + 1);
                    build_items.emplace_back("", object_it->second.object_id, t, instance->printable);
                    count++;
                }
                if (!m_from_backup_save) object_id++;
            }
        // }
        {
            std::stringstream stream;
            reset_stream(stream);
            if (!m_skip_model && !sub_model) {
                for (auto object : model.objects) {
                    auto &data = objects_data[object];
                    _add_object_components_to_stream(stream, data);
                }
            }
            stream << " </" << RESOURCES_TAG << ">\n";
            // Store the transformations of all the ModelInstances of all ModelObjects, indexed in a linear fashion.
            if (!_add_build_to_model_stream(stream, build_items)) {
                add_error("Unable to add build to archive");
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Unable to add build to archive\n");
                return false;
            }
            stream << "</" << MODEL_TAG << ">\n";
            std::string buf = stream.str();
            if ((! buf.empty() && ! mz_zip_writer_add_staged_data(&context, buf.data(), buf.size())) ||
                ! mz_zip_writer_add_staged_finish(&context)) {
                add_error("Unable to add model file to archive");
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Unable to add model file to archive\n");
                return false;
            }
        }
        if (m_skip_model || write_object) return true;
        // write model rels
        _add_relationships_file_to_archive(archive, MODEL_RELS_FILE, object_paths, {"http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"});
        if (!m_from_backup_save) {
            boost::mutex mutex;
            tbb::parallel_for(tbb::blocked_range<size_t>(0, objects_data.size(), 1), [this, &mutex, &model, objects = model.objects, &objects_data, &object_paths, main = &archive, project](const tbb::blocked_range<size_t>& range) {
                for (size_t i = range.begin(); i < range.end(); ++i) {
                    auto iter = objects_data.find(objects[i]);
                    ObjectToObjectDataMap objects_data2;
                    objects_data2.insert(*iter);
                    auto & object = *iter->second.object;
                    mz_zip_archive archive;
                    mz_zip_zero_struct(&archive);
                    mz_zip_writer_init_heap(&archive, 0, 1024 * 1024);
                    CNumericLocalesSetter locales_setter;
                    _add_model_file_to_archive(object_paths[i], archive, model, objects_data2, nullptr, project);
                    iter->second = objects_data2.begin()->second;
                    void *ppBuf; size_t pSize;
                    mz_zip_writer_finalize_heap_archive(&archive, &ppBuf, &pSize);
                    mz_zip_writer_end(&archive);
                    mz_zip_zero_struct(&archive);
                    mz_zip_reader_init_mem(&archive, ppBuf, pSize, 0);
                    {
                        boost::unique_lock l(mutex);
                        mz_zip_writer_add_from_zip_reader(main, &archive, 0);
                    }
                    mz_zip_reader_end(&archive);
                }
            });
        }
        return true;
    }
References BBL_APPLICATION_TAG, BBL_COPYRIGHT_TAG, BBL_CREATION_DATE_TAG, BBL_DESCRIPTION_TAG, BBL_DESIGNER_COVER_FILE_TAG, BBL_DESIGNER_TAG, BBL_DESIGNER_USER_ID_TAG, BBL_LICENSE_TAG, BBL_MODEL_ID_TAG, BBL_MODEL_NAME_TAG, BBL_MODIFICATION_TAG, BBL_ORIGIN_TAG, BBL_REGION_TAG, BBS_3MF_VERSION, Slic3r::Model::design_info, ZipUnicodePathExtraField::encode(), Slic3r::encode_path(), Slic3r::FacetsAnnotation::equals(), error, Slic3r::EXPORT_STAGE_ADD_MODELS, Slic3r::Utils::get_current_time_utc(), METADATA_TAG, Slic3r::ModelVolume::mmu_segmentation_facets, MODEL_FILE, Slic3r::Model::model_info, MODEL_TAG, MZ_DEFAULT_COMPRESSION, MZ_DEFAULT_LEVEL, mz_zip_writer_add_staged_data(), mz_zip_writer_add_staged_open(), Slic3r::Model::objects, Slic3r::reset_stream(), RESOURCES_TAG, Slic3r::ModelVolume::seam_facets, Slic3r::ModelVolume::supported_facets, Slic3r::trace(), Slic3r::Utils::utc_timestamp(), VERSION_BBS_3MF, WRITE_ZIP_LANGUAGE_ENCODING, and Slic3r::xml_escape().
_add_object_components_to_stream()
void Slic3r::_BBS_3MF_Exporter::_add_object_components_to_stream (std::stringstream & stream, ObjectData const & object_data) const private
    {
        auto &       object = *object_data.object;
        stream << "  <" << OBJECT_TAG << " id=\"" << object_data.object_id;
        if (m_production_ext)
            stream << "\" " << PUUID_ATTR << "=\"" << hex_wrap<boost::uint32_t>{(boost::uint32_t)object_data.backup_id}
                    << (object_data.share_mesh ? OBJECT_UUID_SUFFIX2 : OBJECT_UUID_SUFFIX);
        stream << "\" type=\"model\">\n";
        stream << "   <" << COMPONENTS_TAG << ">\n";
        for (unsigned int index = 0; index < object.volumes.size(); index ++) {
            ModelVolume *volume    = object.volumes[index];
            unsigned int volume_id = object_data.volumes_objectID.find(volume)->second;
            auto * ppath = &object_data.sub_path;
            auto iter = m_volume_paths.find(volume);
            if (iter != m_volume_paths.end()) {
                ppath = &iter->second.first;
                volume_id = iter->second.second;
            }
            //add the transform of the volume
            if (ppath->empty())
                stream << "    <" << COMPONENT_TAG << " objectid=\"" << volume_id; // << "\"/>\n";
            else
                stream << "    <" << COMPONENT_TAG << " p:path=\"" << xml_escape(*ppath) << "\" objectid=\"" << volume_id; // << "\"/>\n";
            const Transform3d &transf = volume->get_matrix();
            stream << "\" " << TRANSFORM_ATTR << "=\"";
            for (unsigned c = 0; c < 4; ++c) {
                for (unsigned r = 0; r < 3; ++r) {
                    stream << transf(r, c);
                    if (r != 2 || c != 3)
                        stream << " ";
                }
            }
            stream << "\"/>\n";
        }
        stream << "   </" << COMPONENTS_TAG << ">\n";
        stream << "  </" << OBJECT_TAG << ">\n";
    }
References Slic3r::_BBS_3MF_Exporter::ObjectData::backup_id, COMPONENT_TAG, COMPONENTS_TAG, Slic3r::_BBS_3MF_Exporter::ObjectData::object, Slic3r::_BBS_3MF_Exporter::ObjectData::object_id, OBJECT_TAG, OBJECT_UUID_SUFFIX, OBJECT_UUID_SUFFIX2, PUUID_ATTR, Slic3r::_BBS_3MF_Exporter::ObjectData::share_mesh, Slic3r::_BBS_3MF_Exporter::ObjectData::sub_path, TRANSFORM_ATTR, Slic3r::_BBS_3MF_Exporter::ObjectData::volumes_objectID, and Slic3r::xml_escape().
_add_object_to_model_stream()
bool Slic3r::_BBS_3MF_Exporter::_add_object_to_model_stream (mz_zip_writer_staged_context & context, ObjectData const & object_data) const private
    {
        // backup: make _add_mesh_to_object_stream() reusable
        auto flush = [this, &context](std::string & buf, bool force = false) {
            if ((force && !buf.empty()) || buf.size() >= 65536 * 16) {
                if (!mz_zip_writer_add_staged_data(&context, buf.data(), buf.size())) {
                    add_error("Error during writing or compression");
                    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Error during writing or compression\n");
                    return false;
                }
                buf.clear();
            }
            return true;
        };
        if (!_add_mesh_to_object_stream(flush, object_data)) {
            add_error("Unable to add mesh to archive");
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Unable to add mesh to archive\n");
            return false;
        }
        // Move all components to main model
        //_add_object_components_to_stream(stream, object_data);
        return true;
    }
References error, and mz_zip_writer_add_staged_data().
_add_print_config_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_print_config_file_to_archive (mz_zip_archive & archive, const DynamicPrintConfig & config) private
    {
        assert(is_decimal_separator_point());
        char buffer[1024];
        sprintf(buffer, "; %s\n\n", header_slic3r_generated().c_str());
        std::string out = buffer;
        for (const std::string &key : config.keys())
            if (key != "compatible_printers")
                out += "; " + key + " = " + config.opt_serialize(key) + "\n";
        if (!out.empty()) {
            if (!mz_zip_writer_add_mem(&archive, BBS_PRINT_CONFIG_FILE.c_str(), (const void*)out.data(), out.length(), MZ_DEFAULT_COMPRESSION)) {
                add_error("Unable to add print config file to archive");
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format("Unable to add print config file to archive\n");
                return false;
            }
        }
        return true;
    }
References BBS_PRINT_CONFIG_FILE, buffer, error, Slic3r::header_slic3r_generated(), Slic3r::is_decimal_separator_point(), Slic3r::DynamicConfig::keys(), MZ_DEFAULT_COMPRESSION, mz_zip_writer_add_mem(), Slic3r::ConfigBase::opt_serialize(), and out.
_add_project_config_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_project_config_file_to_archive (mz_zip_archive & archive, const DynamicPrintConfig & config, Model & model) private
    {
        const std::string& temp_path = model.get_backup_path();
        std::string temp_file = temp_path + std::string("/") + "_temp_1.config";
        config.save_to_json(temp_file, std::string("project_settings"), std::string("project"), std::string(SLIC3R_VERSION));
        return _add_file_to_archive(archive, BBS_PROJECT_CONFIG_FILE, temp_file);
    }
References BBS_PROJECT_CONFIG_FILE, Slic3r::Model::get_backup_path(), and Slic3r::ConfigBase::save_to_json().
_add_project_embedded_presets_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_project_embedded_presets_to_archive (mz_zip_archive & archive, Model & model, std::vector< Preset * > project_presets) private
    {
        char buffer[1024];
        sprintf(buffer, "; %s\n\n", header_slic3r_generated().c_str());
        std::string out = buffer;
        int print_count = 0, filament_count = 0, printer_count = 0;
        const std::string& temp_path = model.get_backup_path();
        for (int i = 0; i < project_presets.size(); i++)
        {
            Preset* preset = project_presets[i];
            if (preset) {
                preset->file = temp_path + std::string("/") + "_temp_1.config";
                DynamicPrintConfig& config = preset->config;
                //config.save(preset->file);
                config.save_to_json(preset->file, preset->name, std::string("project"), preset->version.to_string());
                std::string dest_file;
                if (preset->type == Preset::TYPE_PRINT) {
                    dest_file = (boost::format(EMBEDDED_PRINT_FILE_FORMAT) % (print_count + 1)).str();
                    print_count++;
                }
                else if (preset->type == Preset::TYPE_FILAMENT) {
                    dest_file = (boost::format(EMBEDDED_FILAMENT_FILE_FORMAT) % (filament_count + 1)).str();
                    filament_count++;
                }
                else if (preset->type == Preset::TYPE_PRINTER) {
                    dest_file = (boost::format(EMBEDDED_PRINTER_FILE_FORMAT) % (printer_count + 1)).str();
                    printer_count++;
                }
                else
                    continue;
                _add_file_to_archive(archive, dest_file, preset->file);
            }
        }
        return true;
    }
References buffer, Slic3r::Preset::config, EMBEDDED_FILAMENT_FILE_FORMAT, EMBEDDED_PRINT_FILE_FORMAT, EMBEDDED_PRINTER_FILE_FORMAT, Slic3r::Preset::file, Slic3r::Model::get_backup_path(), Slic3r::header_slic3r_generated(), Slic3r::Preset::name, out, Slic3r::ConfigBase::save_to_json(), Slic3r::Semver::to_string(), Slic3r::Preset::type, and Slic3r::Preset::version.
_add_relationships_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_relationships_file_to_archive (mz_zip_archive & archive, std::string const & from = {}, std::vector< std::string > const & targets = {}, std::vector< std::string > const & types = {}, PackingTemporaryData data = PackingTemporaryData(), int export_plate_idx = -1) const private
    {
        std::stringstream stream;
        stream << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
        stream << "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">\n";
        if (from.empty()) {
            stream << " <Relationship Target=\"/" << MODEL_FILE << "\" Id=\"rel-1\" Type=\"http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel\"/>\n";
            if (data._3mf_thumbnail.empty()) {
                if (export_plate_idx < 0) {
                    stream << " <Relationship Target=\"/" << THUMBNAIL_FILE
                           << "\" Id=\"rel-2\" Type=\"http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail\"/>\n";
                } else {
                    std::string thumbnail_file_str = (boost::format("Metadata/plate_%1%.png") % (export_plate_idx + 1)).str();
                    stream << " <Relationship Target=\"/" << xml_escape(thumbnail_file_str)
                        << "\" Id=\"rel-2\" Type=\"http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail\"/>\n";
                }
            } else {
                stream << " <Relationship Target=\"/" << xml_escape(data._3mf_thumbnail)
                       << "\" Id=\"rel-2\" Type=\"http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail\"/>\n";
            }
            if (!data._3mf_printer_thumbnail_middle.empty()) {
                stream << " <Relationship Target=\"/" << xml_escape(data._3mf_printer_thumbnail_middle)
                       << "\" Id=\"rel-4\" Type=\"http://schemas.bambulab.com/package/2021/cover-thumbnail-middle\"/>\n";
            }
            if (!data._3mf_printer_thumbnail_small.empty())
                stream << " <Relationship Target=\"/" << xml_escape(data._3mf_printer_thumbnail_small)
                       << "\" Id=\"rel-5\" Type=\"http://schemas.bambulab.com/package/2021/cover-thumbnail-small\"/>\n";
        }
        else if (targets.empty()) {
            return false;
        }
        else {
            int i = 0;
            for (auto & path : targets) {
                for (auto & type : types)
                    stream << " <Relationship Target=\"/" << xml_escape(path) << "\" Id=\"rel-" << std::to_string(++i) << "\" Type=\"" << type << "\"/>\n";
            }
        }
        stream << "</Relationships>";
        std::string out = stream.str();
        if (!mz_zip_writer_add_mem(&archive, from.empty() ? RELATIONSHIPS_FILE.c_str() : from.c_str(), (const void*)out.data(), out.length(), MZ_DEFAULT_COMPRESSION)) {
            add_error("Unable to add relationships file to archive");
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Unable to add relationships file to archive\n");
            return false;
        }
        return true;
    }
References Slic3r::PackingTemporaryData::_3mf_printer_thumbnail_middle, Slic3r::PackingTemporaryData::_3mf_printer_thumbnail_small, Slic3r::PackingTemporaryData::_3mf_thumbnail, error, MODEL_FILE, MZ_DEFAULT_COMPRESSION, mz_zip_writer_add_mem(), out, RELATIONSHIPS_FILE, THUMBNAIL_FILE, and Slic3r::xml_escape().
_add_sla_drain_holes_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_sla_drain_holes_file_to_archive (mz_zip_archive & archive, Model & model) private
_add_sla_support_points_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_sla_support_points_file_to_archive (mz_zip_archive & archive, Model & model) private
_add_slice_info_config_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive (mz_zip_archive & archive, const Model & model, PlateDataPtrs & plate_data_list, const ObjectToObjectDataMap & objects_data) private
    {
        std::stringstream stream;
        // Store mesh transformation in full precision, as the volumes are stored transformed and they need to be transformed back
        // when loaded as accurately as possible.
    stream << std::setprecision(std::numeric_limits<double>::max_digits10);
        stream << std::setiosflags(std::ios::fixed) << std::setprecision(2);
        stream << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
        stream << "<" << CONFIG_TAG << ">\n";
        // save slice header for debug
        stream << "  <" << SLICE_HEADER_TAG << ">\n";
        stream << "    <" << SLICE_HEADER_ITEM_TAG << " " << KEY_ATTR << "=\"" << "X-BBL-Client-Type"    << "\" " << VALUE_ATTR << "=\"" << "slicer" << "\"/>\n";
        stream << "    <" << SLICE_HEADER_ITEM_TAG << " " << KEY_ATTR << "=\"" << "X-BBL-Client-Version" << "\" " << VALUE_ATTR << "=\"" << convert_to_full_version(SLIC3R_VERSION) << "\"/>\n";
        stream << "  </" << SLICE_HEADER_TAG << ">\n";
        for (unsigned int i = 0; i < (unsigned int)plate_data_list.size(); ++i)
        {
            PlateData* plate_data = plate_data_list[i];
            //int instance_size = plate_data->objects_and_instances.size();
            if (plate_data != nullptr && plate_data->is_sliced_valid) {
                stream << "  <" << PLATE_TAG << ">\n";
                //plate index
                stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << PLATE_IDX_ATTR        << "\" " << VALUE_ATTR << "=\"" << plate_data->plate_index + 1 << "\"/>\n";
                stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << SLICE_PREDICTION_ATTR << "\" " << VALUE_ATTR << "=\"" << plate_data->get_gcode_prediction_str() << "\"/>\n";
                stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << SLICE_WEIGHT_ATTR      << "\" " << VALUE_ATTR << "=\"" <<  plate_data->get_gcode_weight_str() << "\"/>\n";
                stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << OUTSIDE_ATTR      << "\" " << VALUE_ATTR << "=\"" << std::boolalpha<< plate_data->toolpath_outside << "\"/>\n";
                stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << SUPPORT_USED_ATTR << "\" " << VALUE_ATTR << "=\"" << std::boolalpha<< plate_data->is_support_used << "\"/>\n";
                stream << "    <" << METADATA_TAG << " " << KEY_ATTR << "=\"" << LABEL_OBJECT_ENABLED_ATTR << "\" " << VALUE_ATTR << "=\"" << std::boolalpha<< plate_data->is_label_object_enabled << "\"/>\n";
                for (auto it = plate_data->objects_and_instances.begin(); it != plate_data->objects_and_instances.end(); it++)
                {
                        int obj_id = it->first;
                        int inst_id = it->second;
                        int identify_id = 0;
                        ModelObject* obj = NULL;
                        ModelInstance* inst = NULL;
                        if (obj_id >= model.objects.size()) {
                            BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << ":" << __LINE__ << boost::format("invalid object id %1%\n")%obj_id;
                            continue;
                        }
                        obj =  model.objects[obj_id];
                        if (obj && (inst_id >= obj->instances.size())) {
                            BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << ":" << __LINE__ << boost::format("invalid instance id %1%\n")%inst_id;
                            continue;
                        }
                        inst =  obj->instances[inst_id];
                        if (m_use_loaded_id && (inst->loaded_id > 0))
                            identify_id = inst->loaded_id;
                        else
                            identify_id = inst->id().id;
                        bool skipped = std::find(plate_data->skipped_objects.begin(), plate_data->skipped_objects.end(), identify_id) !=
                                       plate_data->skipped_objects.end();
                        stream << "    <" << OBJECT_TAG << " " << IDENTIFYID_ATTR << "=\"" << std::to_string(identify_id) << "\" " << NAME_ATTR << "=\"" << xml_escape(obj->name)
                               << "\" " << SKIPPED_ATTR << "=\"" << (skipped ? "true" : "false")
                               << "\" />\n";
                }
                for (auto it = plate_data->slice_filaments_info.begin(); it != plate_data->slice_filaments_info.end(); it++)
                {
                    stream << "    <" << FILAMENT_TAG << " " << FILAMENT_ID_TAG << "=\"" << std::to_string(it->id + 1) << "\" "
                           << FILAMENT_TYPE_TAG << "=\"" << it->type << "\" "
                           << FILAMENT_COLOR_TAG << "=\"" << it->color << "\" "
                           << FILAMENT_USED_M_TAG << "=\"" << it->used_m << "\" "
                           << FILAMENT_USED_G_TAG << "=\"" << it->used_g << "\" />\n";
                }
                for (auto it = plate_data->warnings.begin(); it != plate_data->warnings.end(); it++) {
                    stream << "    <" << SLICE_WARNING_TAG << " msg=\"" << it->msg << "\" level=\"" << std::to_string(it->level) << "\" error_code =\"" << it->error_code << "\"  />\n";
                }
                stream << "  </" << PLATE_TAG << ">\n";
            }
        }
        stream << "</" << CONFIG_TAG << ">\n";
        std::string out = stream.str();
        if (!mz_zip_writer_add_mem(&archive, SLICE_INFO_CONFIG_FILE.c_str(), (const void*)out.data(), out.length(), MZ_DEFAULT_COMPRESSION)) {
            add_error("Unable to add model config file to archive");
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", store  slice-info to 3mf,  length %1%, failed\n") % out.length();
            return false;
        }
        return true;
    }
References CONFIG_TAG, Slic3r::convert_to_full_version(), error, FILAMENT_COLOR_TAG, FILAMENT_ID_TAG, FILAMENT_TAG, FILAMENT_TYPE_TAG, FILAMENT_USED_G_TAG, FILAMENT_USED_M_TAG, Slic3r::PlateData::get_gcode_prediction_str(), Slic3r::PlateData::get_gcode_weight_str(), Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), IDENTIFYID_ATTR, Slic3r::ModelObject::instances, int, Slic3r::PlateData::is_label_object_enabled, Slic3r::PlateData::is_sliced_valid, Slic3r::PlateData::is_support_used, KEY_ATTR, LABEL_OBJECT_ENABLED_ATTR, Slic3r::ModelInstance::loaded_id, METADATA_TAG, MZ_DEFAULT_COMPRESSION, mz_zip_writer_add_mem(), Slic3r::ModelObject::name, NAME_ATTR, NULL, OBJECT_TAG, Slic3r::Model::objects, Slic3r::PlateData::objects_and_instances, out, OUTSIDE_ATTR, PLATE_IDX_ATTR, Slic3r::PlateData::plate_index, PLATE_TAG, SKIPPED_ATTR, Slic3r::PlateData::skipped_objects, Slic3r::PlateData::slice_filaments_info, SLICE_HEADER_ITEM_TAG, SLICE_HEADER_TAG, SLICE_INFO_CONFIG_FILE, SLICE_PREDICTION_ATTR, SLICE_WARNING_TAG, SLICE_WEIGHT_ATTR, SUPPORT_USED_ATTR, Slic3r::PlateData::toolpath_outside, VALUE_ATTR, Slic3r::PlateData::warnings, and Slic3r::xml_escape().
_add_thumbnail_file_to_archive()
bool Slic3r::_BBS_3MF_Exporter::_add_thumbnail_file_to_archive (mz_zip_archive & archive, const ThumbnailData & thumbnail_data, const char * local_path, int index) private
    {
        bool res = false;
        size_t png_size = 0;
        void* png_data = tdefl_write_image_to_png_file_in_memory_ex((const void*)thumbnail_data.pixels.data(), thumbnail_data.width, thumbnail_data.height, 4, &png_size, MZ_DEFAULT_COMPRESSION, 1);
        if (png_data != nullptr) {
            std::string thumbnail_name = (boost::format("%1%_%2%.png")%local_path % (index + 1)).str();
            res = mz_zip_writer_add_mem(&archive, thumbnail_name.c_str(), (const void*)png_data, png_size, MZ_NO_COMPRESSION);
            mz_free(png_data);
        }
        if (!res) {
            add_error("Unable to add thumbnail file to archive");
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Unable to add thumbnail file to archive\n");
        }
        return res;
    }
References error, Slic3r::ThumbnailData::height, MZ_DEFAULT_COMPRESSION, mz_free(), MZ_NO_COMPRESSION, mz_zip_writer_add_mem(), Slic3r::ThumbnailData::pixels, tdefl_write_image_to_png_file_in_memory_ex(), and Slic3r::ThumbnailData::width.
_save_model_to_file()
bool Slic3r::_BBS_3MF_Exporter::_save_model_to_file (const std::string & filename, Model & model, PlateDataPtrs & plate_data_list, std::vector< Preset * > & project_presets, const DynamicPrintConfig * config, const std::vector< ThumbnailData * > & thumbnail_data, const std::vector< ThumbnailData * > & top_thumbnail_data, const std::vector< ThumbnailData * > & pick_thumbnail_data, Export3mfProgressFn proFn, const std::vector< ThumbnailData * > & calibration_data, const std::vector< PlateBBoxData * > & id_bboxes, BBLProject * project = nullptr, int export_plate_idx = -1) private
    {
        PackingTemporaryData temp_data;
        mz_zip_archive archive;
        mz_zip_zero_struct(&archive);
        bool cb_cancel = false;
        //BBS progress point
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ <<
                boost::format(",before open zip writer, m_skip_static %1%, m_save_gcode %2%, m_use_loaded_id %3%")%m_skip_static %m_save_gcode %m_use_loaded_id;
        if (proFn) {
            proFn(EXPORT_STAGE_OPEN_3MF, 0, 1, cb_cancel);
            if (cb_cancel)
                return false;
        }
        if (!open_zip_writer(&archive, filename)) {
            add_error("Unable to open the file"+filename);
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Unable to open the file\n");
            return false;
        }
        struct close_lock
        {
            mz_zip_archive & archive;
            std::string const * filename;
            ~close_lock() {
                close_zip_writer(&archive);
                if (filename)
                boost::filesystem::remove(*filename);
            }
        } lock{ archive, &filename};
        //BBS progress point
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", before add _add_content_types_file_to_archive\n");
        if (proFn) {
            proFn(EXPORT_STAGE_CONTENT_TYPES, 0, 1, cb_cancel);
            if (cb_cancel)
                return false;
        }
        // Adds content types file ("[Content_Types].xml";).
        // The content of this file is the same for each OrcaSlicer 3mf.
        if (!_add_content_types_file_to_archive(archive)) {
            return false;
        }
        //BBS progress point
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__ << boost::format(",before add thumbnails, count %1%") % thumbnail_data.size();
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(",top&&pick thumbnails, count %1%")%top_thumbnail_data.size();
        //BBS: add thumbnail for each plate
        if (!m_skip_static) {
            std::vector<bool> thumbnail_status(plate_data_list.size(), false);
            std::vector<bool> top_thumbnail_status(plate_data_list.size(), false);
            std::vector<bool> pick_thumbnail_status(plate_data_list.size(), false);
            if ((thumbnail_data.size() > 0)&&(thumbnail_data.size() > plate_data_list.size())) {
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", thumbnail_data size %1% > plate count %2%")
                    % thumbnail_data.size() %plate_data_list.size();
                return false;
            }
            if ((top_thumbnail_data.size() > 0)&&(top_thumbnail_data.size() > plate_data_list.size())) {
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", top_thumbnail_data size %1% > plate count %2%")
                    % top_thumbnail_data.size() %plate_data_list.size();
                return false;
            }
            if ((pick_thumbnail_data.size() > 0)&&(pick_thumbnail_data.size() > plate_data_list.size())) {
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", pick_thumbnail_data size %1% > plate count %2%")
                    % pick_thumbnail_data.size() %plate_data_list.size();
                return false;
            }
            if (top_thumbnail_data.size() != pick_thumbnail_data.size()) {
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", top_thumbnail_data size %1% != pick_thumbnail_data size %2%")
                    % top_thumbnail_data.size() %pick_thumbnail_data.size();
                return false;
            }
            if (proFn) {
                proFn(EXPORT_STAGE_ADD_THUMBNAILS, 0, plate_data_list.size(), cb_cancel);
                if (cb_cancel)
                    return false;
            }
            for (unsigned int index = 0; index < thumbnail_data.size(); index++)
            {
                if (thumbnail_data[index]->is_valid())
                {
                    if (!_add_thumbnail_file_to_archive(archive, *thumbnail_data[index], "Metadata/plate", index)) {
                        return false;
                    }
                    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(",add thumbnail %1%'s data into 3mf")%(index+1);
                    thumbnail_status[index] = true;
                }
            }
            // Adds the file Metadata/top_i.png and Metadata/pick_i.png
            for (unsigned int index = 0; index < top_thumbnail_data.size(); index++)
            {
                if (top_thumbnail_data[index]->is_valid())
                {
                    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(",add top thumbnail %1%'s data into 3mf")%(index+1);
                    if (!_add_thumbnail_file_to_archive(archive, *top_thumbnail_data[index], "Metadata/top", index)) {
                        return false;
                    }
                    top_thumbnail_status[index] = true;
                }
                if (pick_thumbnail_data[index]->is_valid())
                {
                    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(",add pick thumbnail %1%'s data into 3mf")%(index+1);
                    if (!_add_thumbnail_file_to_archive(archive, *pick_thumbnail_data[index], "Metadata/pick", index)) {
                        return false;
                    }
                    pick_thumbnail_status[index] = true;
                }
            }
            for (int i = 0; i < plate_data_list.size(); i++) {
                PlateData *plate_data = plate_data_list[i];
                if (!thumbnail_status[i] && !plate_data->thumbnail_file.empty() && (boost::filesystem::exists(plate_data->thumbnail_file))){
                    std::string dst_in_3mf = (boost::format("Metadata/plate_%1%.png") % (i + 1)).str();
                    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", add thumbnail %1% from file %2%") % (i+1) %plate_data->thumbnail_file;
                    if (!_add_file_to_archive(archive, dst_in_3mf, plate_data->thumbnail_file)) {
                        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", add thumbnail %1% from file %2% failed\n") % (i+1) %plate_data->thumbnail_file;
                        return false;
                    }
                }
                if (!top_thumbnail_status[i] && !plate_data->top_file.empty() && (boost::filesystem::exists(plate_data->top_file))){
                    std::string dst_in_3mf = (boost::format("Metadata/top_%1%.png") % (i + 1)).str();
                    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", add top thumbnail %1% from file %2%") % (i+1) %plate_data->top_file;
                    if (!_add_file_to_archive(archive, dst_in_3mf, plate_data->top_file)) {
                        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", add top thumbnail %1% failed") % (i+1);
                        return false;
                    }
                    top_thumbnail_status[i] = true;
                }
                if (!pick_thumbnail_status[i] && !plate_data->pick_file.empty() && (boost::filesystem::exists(plate_data->pick_file))){
                    std::string dst_in_3mf = (boost::format("Metadata/pick_%1%.png") % (i + 1)).str();
                    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", add pick thumbnail %1% from file %2%") % (i+1) %plate_data->pick_file;
                    if (!_add_file_to_archive(archive, dst_in_3mf, plate_data->pick_file)) {
                        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", add pick thumbnail %1% failed") % (i+1);
                        return false;
                    }
                    pick_thumbnail_status[i] = true;
                }
            }
            if (proFn) {
                proFn(EXPORT_STAGE_ADD_THUMBNAILS, plate_data_list.size(), plate_data_list.size(), cb_cancel);
                if (cb_cancel)
                    return false;
            }
        }
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(",before add calibration thumbnails, count %1%\n")%calibration_data.size();
        //BBS add calibration thumbnail for each plate
        if (!m_skip_static && calibration_data.size() > 0) {
            // Adds the file Metadata/calibration_p[X].png.
            for (unsigned int index = 0; index < calibration_data.size(); index++)
            {
                if (proFn) {
                    proFn(EXPORT_STAGE_ADD_THUMBNAILS, index, calibration_data.size(), cb_cancel);
                    if (cb_cancel)
                        return false;
                }
                if (calibration_data[index]->is_valid())
                {
                    if (!_add_calibration_file_to_archive(archive, *calibration_data[index], index)) {
                        close_zip_writer(&archive);
                        boost::filesystem::remove(filename);
                        return false;
                    }
                }
            }
        }
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(",before add calibration boundingbox, count %1%\n")%id_bboxes.size();
        if (!m_skip_static && id_bboxes.size() > 0) {
            // Adds the file Metadata/calibration_p[X].png.
            for (unsigned int index = 0; index < id_bboxes.size(); index++)
            {
                // BBS: save bounding box to json
                if (id_bboxes[index]->is_valid()) {
                    if (!_add_bbox_file_to_archive(archive, *id_bboxes[index], index)) {
                        close_zip_writer(&archive);
                        boost::filesystem::remove(filename);
                        return false;
                    }
                }
            }
        }
        //BBS progress point
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", before add models\n");
        if (proFn) {
            proFn(EXPORT_STAGE_ADD_MODELS, 0, 1, cb_cancel);
            if (cb_cancel)
                return false;
        }
        // Adds model file ("3D/3dmodel.model").
        // This is the one and only file that contains all the geometry (vertices and triangles) of all ModelVolumes.
        ObjectToObjectDataMap objects_data;
        //if (!m_skip_model)
        {
            if (!_add_model_file_to_archive(filename, archive, model, objects_data, proFn, project)) { return false; }
            // Adds layer height profile file ("Metadata/Slic3r_PE_layer_heights_profile.txt").
            // All layer height profiles of all ModelObjects are stored here, indexed by 1 based index of the ModelObject in Model.
            // The index differes from the index of an object ID of an object instance of a 3MF file!
            if (!_add_layer_height_profile_file_to_archive(archive, model)) {
                close_zip_writer(&archive);
                boost::filesystem::remove(filename);
                return false;
            }
            // BBS progress point
            /*BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format("export 3mf EXPORT_STAGE_ADD_LAYER_RANGE\n");
            if (proFn) {
                proFn(EXPORT_STAGE_ADD_LAYER_RANGE, 0, 1, cb_cancel);
                if (cb_cancel)
                    return false;
            }*/
            // Adds layer config ranges file ("Metadata/Slic3r_PE_layer_config_ranges.txt").
            // All layer height profiles of all ModelObjects are stored here, indexed by 1 based index of the ModelObject in Model.
            // The index differes from the index of an object ID of an object instance of a 3MF file!
            if (!_add_layer_config_ranges_file_to_archive(archive, model)) {
                close_zip_writer(&archive);
                boost::filesystem::remove(filename);
                return false;
            }
            // BBS progress point
            /*BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format("export 3mf EXPORT_STAGE_ADD_SUPPORT\n");
            if (proFn) {
                proFn(EXPORT_STAGE_ADD_SUPPORT, 0, 1, cb_cancel);
                if (cb_cancel)
                    return false;
            }
            // Adds sla support points file ("Metadata/Slic3r_PE_sla_support_points.txt").
            // All  sla support points of all ModelObjects are stored here, indexed by 1 based index of the ModelObject in Model.
            // The index differes from the index of an object ID of an object instance of a 3MF file!
            if (!_add_sla_support_points_file_to_archive(archive, model)) {
                return false;
            }
            if (!_add_sla_drain_holes_file_to_archive(archive, model)) {
                return false;
            }*/
            // BBS progress point
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__ << boost::format(", before add custom gcodes\n");
            if (proFn) {
                proFn(EXPORT_STAGE_ADD_CUSTOM_GCODE, 0, 1, cb_cancel);
                if (cb_cancel) return false;
            }
            // Adds custom gcode per height file ("Metadata/Prusa_Slicer_custom_gcode_per_print_z.xml").
            // All custom gcode per height of whole Model are stored here
            if (!_add_custom_gcode_per_print_z_file_to_archive(archive, model, config)) { return false; }
            // BBS progress point
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__ << boost::format(", before add project_settings\n");
            if (proFn) {
                proFn(EXPORT_STAGE_ADD_PRINT_CONFIG, 0, 1, cb_cancel);
                if (cb_cancel) return false;
            }
            // Adds slic3r print config file ("Metadata/Slic3r_PE.config").
            // This file contains the content of FullPrintConfing / SLAFullPrintConfig.
            if (config != nullptr) {
                // BBS: change to json format
                // if (!_add_print_config_file_to_archive(archive, *config)) {
                if (!_add_project_config_file_to_archive(archive, *config, model)) { return false; }
            }
            // BBS progress point
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__ << boost::format(", before add project embedded settings\n");
            if (proFn) {
                proFn(EXPORT_STAGE_ADD_CONFIG_FILE, 0, 1, cb_cancel);
                if (cb_cancel) return false;
            }
            // BBS: add project config
            if (project_presets.size() > 0) {
                // BBS: add project embedded preset files
                _add_project_embedded_presets_to_archive(archive, model, project_presets);
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__ << boost::format(", finished add project embedded settings, size %1%\n")%project_presets.size();
                if (proFn) {
                    proFn(EXPORT_STAGE_ADD_PROJECT_CONFIG, 0, 1, cb_cancel);
                    if (cb_cancel) return false;
                }
            }
        }
        // add plate_N.gcode.md5 to file
        if (!m_skip_static && m_save_gcode) {
            for (int i = 0; i < plate_data_list.size(); i++) {
                PlateData *plate_data = plate_data_list[i];
                if (!plate_data->gcode_file.empty() && plate_data->is_sliced_valid && boost::filesystem::exists(plate_data->gcode_file)) {
                    unsigned char digest[16];
                    MD5_CTX       ctx;
                    MD5_Init(&ctx);
                    auto                        src_gcode_file = plate_data->gcode_file;
                    boost::filesystem::ifstream ifs(src_gcode_file, std::ios::binary);
                    std::string                 buf(64 * 1024, 0);
                    const std::size_t &         size      = boost::filesystem::file_size(src_gcode_file);
                    std::size_t                 left_size = size;
                    while (ifs) {
                        ifs.read(buf.data(), buf.size());
                        int read_bytes = ifs.gcount();
                        MD5_Update(&ctx, (unsigned char *) buf.data(), read_bytes);
                    }
                    MD5_Final(digest, &ctx);
                    char md5_str[33];
                    for (int j = 0; j < 16; j++) { sprintf(&md5_str[j * 2], "%02X", (unsigned int) digest[j]); }
                    plate_data->gcode_file_md5 = std::string(md5_str);
                    std::string target_file    = (boost::format("Metadata/plate_%1%.gcode.md5") % (plate_data->plate_index + 1)).str();
                    if (!mz_zip_writer_add_mem(&archive, target_file.c_str(), (const void *) plate_data->gcode_file_md5.c_str(), plate_data->gcode_file_md5.length(),
                                               MZ_DEFAULT_COMPRESSION)) {
                        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__
                                                 << boost::format(", store  gcode md5 to 3mf's %1%,  length %2%, failed\n") %target_file %plate_data->gcode_file_md5.length();
                        return false;
                    }
                }
            }
        }
        // Adds gcode files ("Metadata/plate_1.gcode, plate_2.gcode, ...)
        // Before _add_model_config_file_to_archive, because we modify plate_data
        //if (!m_skip_static && !_add_gcode_file_to_archive(archive, model, plate_data_list, proFn)) {
        if (!m_skip_static && m_save_gcode && !_add_gcode_file_to_archive(archive, model, plate_data_list, proFn)) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", _add_gcode_file_to_archive failed\n");
            return false;
        }
        // Adds slic3r model config file ("Metadata/Slic3r_PE_model.config").
        // This file contains all the attributes of all ModelObjects and their ModelVolumes (names, parameter overrides).
        // As there is just a single Indexed Triangle Set data stored per ModelObject, offsets of volumes into their respective Indexed Triangle Set data
        // is stored here as well.
        if (!_add_model_config_file_to_archive(archive, model, plate_data_list, objects_data, export_plate_idx, m_save_gcode, m_use_loaded_id)) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", _add_model_config_file_to_archive failed\n");
            return false;
        }
        if (!_add_cut_information_file_to_archive(archive, model)) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", _add_cut_information_file_to_archive failed\n");
            return false;
        }
        //BBS progress point
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", before add sliced info to 3mf\n");
        if (proFn) {
            proFn(EXPORT_STAGE_ADD_SLICE_INFO, 0, 1, cb_cancel);
            if (cb_cancel)
                return false;
        }
        // Adds sliced info of plate file ("Metadata/slice_info.config")
        // This file contains all sliced info of all plates
        if (!_add_slice_info_config_file_to_archive(archive, model, plate_data_list, objects_data)) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", _add_slice_info_config_file_to_archive failed\n");
            return false;
        }
        //BBS progress point
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", before add auxiliary dir to 3mf\n");
        if (proFn) {
            proFn(EXPORT_STAGE_ADD_AUXILIARIES, 0, 1, cb_cancel);
            if (cb_cancel)
                return false;
        }
        if (!m_skip_static && !_add_auxiliary_dir_to_archive(archive, model.get_auxiliary_file_temp_path(), temp_data)) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", _add_auxiliary_dir_to_archive failed\n");
            return false;
        }
        //BBS progress point
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", before add relation file to 3mf\n");
        if (proFn) {
            proFn(EXPORT_STAGE_ADD_RELATIONS, 0, 1, cb_cancel);
            if (cb_cancel)
                return false;
        }
        // Adds relationships file ("_rels/.rels").
        // The content of this file is the same for each OrcaSlicer 3mf.
        // The relationshis file contains a reference to the geometry file "3D/3dmodel.model", the name was chosen to be compatible with CURA.
        if (!_add_relationships_file_to_archive(archive, {}, {}, {}, temp_data, export_plate_idx)) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", _add_relationships_file_to_archive failed\n");
            return false;
        }
        if (!mz_zip_writer_finalize_archive(&archive)) {
            add_error("Unable to finalize the archive");
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Unable to finalize the archive\n");
            return false;
        }
        //BBS progress point
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", finished exporting 3mf\n");
        if (proFn) {
            proFn(EXPORT_STAGE_FINISH, 0, 1, cb_cancel);
            if (cb_cancel)
                return false;
        }
        lock.filename = nullptr;
        return true;
    }
References Slic3r::close_zip_writer(), error, Slic3r::EXPORT_STAGE_ADD_AUXILIARIES, Slic3r::EXPORT_STAGE_ADD_CONFIG_FILE, Slic3r::EXPORT_STAGE_ADD_CUSTOM_GCODE, Slic3r::EXPORT_STAGE_ADD_MODELS, Slic3r::EXPORT_STAGE_ADD_PRINT_CONFIG, Slic3r::EXPORT_STAGE_ADD_PROJECT_CONFIG, Slic3r::EXPORT_STAGE_ADD_RELATIONS, Slic3r::EXPORT_STAGE_ADD_SLICE_INFO, Slic3r::EXPORT_STAGE_ADD_THUMBNAILS, Slic3r::EXPORT_STAGE_CONTENT_TYPES, Slic3r::EXPORT_STAGE_FINISH, Slic3r::EXPORT_STAGE_OPEN_3MF, Slic3r::PlateData::gcode_file, Slic3r::PlateData::gcode_file_md5, Slic3r::Model::get_auxiliary_file_temp_path(), Slic3r::PlateData::is_sliced_valid, MZ_DEFAULT_COMPRESSION, mz_zip_writer_add_mem(), mz_zip_writer_finalize_archive(), mz_zip_zero_struct(), Slic3r::open_zip_writer(), Slic3r::PlateData::pick_file, Slic3r::PlateData::plate_index, size, Slic3r::PlateData::thumbnail_file, and Slic3r::PlateData::top_file.
add_error()
void Slic3r::_BBS_3MF_Base::add_error (const std::string & error) const inline protected inherited
{ boost::unique_lock l(mutex); m_errors.push_back(error); }
References error, Slic3r::_BBS_3MF_Base::m_errors, and Slic3r::_BBS_3MF_Base::mutex.
Referenced by Slic3r::_BBS_3MF_Importer::_load_model_from_file(), Slic3r::_BBS_3MF_Importer::ObjectImporter::extract_object_model(), Slic3r::_BBS_3MF_Importer::get_thumbnail(), and Slic3r::_BBS_3MF_Importer::load_gcode_3mf_from_stream().
clear_errors()
void Slic3r::_BBS_3MF_Base::clear_errors () inline protected inherited
{ m_errors.clear(); }
References Slic3r::_BBS_3MF_Base::m_errors.
Referenced by Slic3r::_BBS_3MF_Importer::~_BBS_3MF_Importer(), and Slic3r::_BBS_3MF_Importer::load_model_from_file().
convert_instance_id_to_resource_id()
static int Slic3r::_BBS_3MF_Exporter::convert_instance_id_to_resource_id (const Model & model, int obj_id, int instance_id) inline static private
        {
            int resource_id = 1;
            for (int i = 0; i < obj_id; ++i)
            {
                resource_id += model.objects[i]->volumes.size() + 1;
            }
            resource_id += model.objects[obj_id]->volumes.size();
            return resource_id;
        }
References Slic3r::Model::objects.
log_errors()
void Slic3r::_BBS_3MF_Base::log_errors () inline inherited
        {
            for (const std::string& error : m_errors)
                BOOST_LOG_TRIVIAL(error) << error;
        }
References error, and Slic3r::_BBS_3MF_Base::m_errors.
Referenced by Slic3r::bbs_3mf_get_thumbnail(), Slic3r::load_bbs_3mf(), Slic3r::load_gcode_3mf_from_stream(), and Slic3r::store_bbs_3mf().
save_model_to_file()
bool Slic3r::_BBS_3MF_Exporter::save_model_to_file (StoreParams & store_params)
    {
        clear_errors();
        m_fullpath_sources = store_params.strategy & SaveStrategy::FullPathSources;
        m_zip64 = store_params.strategy & SaveStrategy::Zip64;
        m_production_ext = store_params.strategy & SaveStrategy::ProductionExt;
        m_skip_static = store_params.strategy & SaveStrategy::SkipStatic;
        m_split_model = store_params.strategy & SaveStrategy::SplitModel;
        m_save_gcode = store_params.strategy & SaveStrategy::WithGcode;
        m_skip_model  = store_params.strategy & SaveStrategy::SkipModel;
        m_skip_auxiliary = store_params.strategy & SaveStrategy::SkipAuxiliary;
        m_share_mesh       = store_params.strategy & SaveStrategy::ShareMesh;
        m_from_backup_save = store_params.strategy & SaveStrategy::Backup;
        m_use_loaded_id = store_params.strategy & SaveStrategy::UseLoadedId;
        if (auto info = store_params.model->model_info) {
            if (auto iter = info->metadata_items.find("Thumbnail_Small"); iter != info->metadata_items.end())
                m_thumbnail_small = iter->second;
            if (auto iter = info->metadata_items.find("Thumbnail_Middle"); iter != info->metadata_items.end())
                m_thumbnail_middle = iter->second;
        }
        boost::system::error_code ec;
        std::string filename = std::string(store_params.path);
        boost::filesystem::remove(filename + ".tmp", ec);
        bool result = _save_model_to_file(filename + ".tmp", *store_params.model, store_params.plate_data_list, store_params.project_presets, store_params.config,
            store_params.thumbnail_data, store_params.top_thumbnail_data, store_params.pick_thumbnail_data, store_params.proFn,
            store_params.calibration_thumbnail_data, store_params.id_bboxes, store_params.project, store_params.export_plate_idx);
        if (result) {
            boost::filesystem::rename(filename + ".tmp", filename, ec);
            if (ec) {
                add_error("Failed to rename file: " + ec.message());
                boost::filesystem::remove(filename + ".tmp", ec);
                return false;
            }
            if (!(store_params.strategy & SaveStrategy::Silence))
                boost::filesystem::save_string_file(store_params.model->get_backup_path() + "/origin.txt", filename);
        }
        return result;
    }
References Slic3r::StoreParams::calibration_thumbnail_data, Slic3r::StoreParams::config, Slic3r::StoreParams::export_plate_idx, Slic3r::Model::get_backup_path(), Slic3r::StoreParams::id_bboxes, Slic3r::StoreParams::model, Slic3r::Model::model_info, Slic3r::StoreParams::path, Slic3r::StoreParams::pick_thumbnail_data, Slic3r::StoreParams::plate_data_list, Slic3r::StoreParams::proFn, Slic3r::StoreParams::project, Slic3r::StoreParams::project_presets, Slic3r::StoreParams::strategy, Slic3r::StoreParams::thumbnail_data, and Slic3r::StoreParams::top_thumbnail_data.
Referenced by Slic3r::store_bbs_3mf().
save_object_mesh()
bool Slic3r::_BBS_3MF_Exporter::save_object_mesh (const std::string & temp_path, ModelObject const & object, int obj_id)
    {
        m_production_ext = true;
        m_from_backup_save = true;
        Model const & model = *object.get_model();
        mz_zip_archive archive;
        mz_zip_zero_struct(&archive);
        auto filename = boost::format("3D/Objects/%s_%d.model") % object.name % obj_id;
        std::string filepath = temp_path + "/" + filename.str();
        std::string filepath_tmp = filepath + ".tmp";
        boost::system::error_code ec;
        boost::filesystem::remove(filepath_tmp, ec);
        if (!open_zip_writer(&archive, filepath_tmp)) {
            add_error("Unable to open the file"+filepath_tmp);
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Unable to open the file\n");
            return false;
        }
        struct close_lock
        {
            mz_zip_archive & archive;
            std::string const * filename;
            void close() {
                close_zip_writer(&archive);
                filename = nullptr;
            }
            ~close_lock() {
                if (filename) {
                    close_zip_writer(&archive);
                    boost::filesystem::remove(*filename);
                }
            }
        } lock{archive, &filepath_tmp};
        ObjectToObjectDataMap objects_data;
        auto & volumes_objectID = objects_data.insert({&object, {&object, obj_id}}).first->second.volumes_objectID;
        unsigned int volume_count = 0;
        for (ModelVolume *volume : object.volumes) {
            if (volume == nullptr) continue;
            volumes_objectID.insert({volume, (++volume_count << 16 | obj_id)});
        }
        _add_model_file_to_archive(filename.str(), archive, model, objects_data);
        mz_zip_writer_finalize_archive(&archive);
        lock.close();
        boost::filesystem::rename(filepath_tmp, filepath, ec);
        return true;
    }
References Slic3r::close_zip_writer(), error, mz_zip_writer_finalize_archive(), mz_zip_zero_struct(), and Slic3r::open_zip_writer().
Referenced by Slic3r::_BBS_Backup_Manager::process_task().
Member Data Documentation
m_errors
std::vector<std::string> Slic3r::_BBS_3MF_Base::m_errors mutable private inherited
Referenced by Slic3r::_BBS_3MF_Base::add_error(), Slic3r::_BBS_3MF_Base::clear_errors(), and Slic3r::_BBS_3MF_Base::log_errors().
m_from_backup_save
bool Slic3r::_BBS_3MF_Exporter::m_from_backup_save { false } private
m_fullpath_sources
bool Slic3r::_BBS_3MF_Exporter::m_fullpath_sources { true } private
m_production_ext
bool Slic3r::_BBS_3MF_Exporter::m_production_ext { false } private
m_save_gcode
bool Slic3r::_BBS_3MF_Exporter::m_save_gcode { false } private
m_share_mesh
bool Slic3r::_BBS_3MF_Exporter::m_share_mesh { false } private
m_shared_meshes
std::map<void const *, std::pair<ObjectData*, ModelVolume const *> > Slic3r::_BBS_3MF_Exporter::m_shared_meshes private
m_skip_auxiliary
bool Slic3r::_BBS_3MF_Exporter::m_skip_auxiliary { false } private
m_skip_model
bool Slic3r::_BBS_3MF_Exporter::m_skip_model { false } private
m_skip_static
bool Slic3r::_BBS_3MF_Exporter::m_skip_static { false } private
m_split_model
bool Slic3r::_BBS_3MF_Exporter::m_split_model { false } private
m_thumbnail_middle
std::string Slic3r::_BBS_3MF_Exporter::m_thumbnail_middle = PRINTER_THUMBNAIL_MIDDLE_FILE private
m_thumbnail_small
std::string Slic3r::_BBS_3MF_Exporter::m_thumbnail_small = PRINTER_THUMBNAIL_SMALL_FILE private
m_use_loaded_id
bool Slic3r::_BBS_3MF_Exporter::m_use_loaded_id { false } private
m_volume_paths
std::map<ModelVolume const *, std::pair<std::string, int> > Slic3r::_BBS_3MF_Exporter::m_volume_paths private
m_zip64
bool Slic3r::_BBS_3MF_Exporter::m_zip64 { true } private
mutex
boost::mutex Slic3r::_BBS_3MF_Base::mutex mutable private inherited
Referenced by Slic3r::_BBS_3MF_Importer::_load_model_from_file(), and Slic3r::_BBS_3MF_Base::add_error().
The documentation for this class was generated from the following file:
src/libslic3r/Format/bbs_3mf.cpp