OrcaSlicer: src/slic3r/GUI/Widgets/AxisCtrlButton.cpp File Reference
AxisCtrlButton.cpp File Reference
#include "AxisCtrlButton.hpp"
#include "Label.hpp"
#include <wx/dcgraph.h>
Macros
#define OUTER_SIZE FromDIP(105)
#define INNER_SIZE FromDIP(58)
#define HOME_SIZE FromDIP(23)
#define BLANK_SIZE FromDIP(24)
#define GAP_SIZE FromDIP(4)
Variables
StateColor blank_bg (StateColor(std::make_pair(wxColour("#FFFFFF"),(int) StateColor::Normal)))
static const wxColour BUTTON_BG_COL = wxColour("#EEEEEE")
static const wxColour BUTTON_IN_BG_COL = wxColour("#CECECE")
static const wxColour bd = wxColour(0, 150, 136)
static const wxColour text_num_color = wxColour(0x898989)
static const wxColour BUTTON_PRESS_COL = wxColour(172, 172, 172)
static const double sqrt2 = std::sqrt(2)
Macro Definition Documentation
BLANK_SIZE
#define BLANK_SIZE FromDIP(24)
GAP_SIZE
#define GAP_SIZE FromDIP(4)
HOME_SIZE
#define HOME_SIZE FromDIP(23)
INNER_SIZE
#define INNER_SIZE FromDIP(58)
OUTER_SIZE
#define OUTER_SIZE FromDIP(105)
Variable Documentation
bd
const wxColour bd = wxColour(0, 150, 136) static
Referenced by AxisCtrlButton::AxisCtrlButton(), Slic3r::GUI::MsgDialog::add_button(), igl::flip_avoiding::get_smallest_pos_quad_zero(), Slic3r::FakeWipeTower::getFakeExtrusionPathsFromWipeTower(), incircleexact(), insphere(), insphereadapt(), insphereexact(), inspherefast(), insphereslow(), Slic3r::GUI::MsgDialog::on_dpi_changed(), orient3dexact(), and Slic3r::FakeWipeTower::set_fake_extrusion_data().
blank_bg
StateColor blank_bg(StateColor(std::make_pair(wxColour("#FFFFFF"),(int) StateColor::Normal))) (StateColor(std::make_pair(wxColour("#FFFFFF"),(int) StateColor::Normal)))
Referenced by AxisCtrlButton::render().
BUTTON_BG_COL
const wxColour BUTTON_BG_COL = wxColour("#EEEEEE") static
Referenced by AxisCtrlButton::AxisCtrlButton(), and AxisCtrlButton::render().
BUTTON_IN_BG_COL
const wxColour BUTTON_IN_BG_COL = wxColour("#CECECE") static
Referenced by AxisCtrlButton::AxisCtrlButton(), and AxisCtrlButton::render().
BUTTON_PRESS_COL
const wxColour BUTTON_PRESS_COL = wxColour(172, 172, 172) static
Referenced by AxisCtrlButton::AxisCtrlButton().
sqrt2
const double sqrt2 = std::sqrt(2) static
Referenced by AxisCtrlButton::render().
text_num_color
const wxColour text_num_color = wxColour(0x898989) static
Referenced by AxisCtrlButton::render().