OrcaSlicer: Slic3r::GUI::ObjectGrid Class Reference
Slic3r::GUI::ObjectGrid Class Reference
#include <src/slic3r/GUI/GUI_ObjectTable.hpp>
Public Member Functions
ObjectGrid (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxWANTS_CHARS, const wxString &name=wxASCII_STR(wxGridNameStr))
~ObjectGrid ()
bool OnCellLeftClick (wxGridEvent &event, int row, int col, ConfigOptionType type)
void OnRangeSelected (wxGridRangeSelectEvent &ev)
void OnColHeadLeftClick (wxGridEvent &event)
virtual void DrawColLabels (wxDC &dc, const wxArrayInt &cols)
virtual void DrawColLabel (wxDC &dc, int col)
Public Attributes
wxString input_string
wxString m_cell_data
Protected Member Functions
void OnKeyDown (wxKeyEvent &)
void OnKeyUp (wxKeyEvent &)
void OnChar (wxKeyEvent &)
Private Member Functions
wxDECLARE_EVENT_TABLE ()
void paste_data (wxTextDataObject &text_data)
Private Attributes
wxGridBlockCoords m_selected_block
Friends
class ObjectGridTable
class ObjectTablePanel
Detailed Description
Constructor & Destructor Documentation
ObjectGrid()
Slic3r::GUI::ObjectGrid::ObjectGrid (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxWANTS_CHARS, const wxString & name = wxASCII_STR(wxGridNameStr)) inline
        :wxGrid(parent, id, pos, size, style, name)
    {
    }
~ObjectGrid()
Slic3r::GUI::ObjectGrid::~ObjectGrid () inline
{}
Member Function Documentation
DrawColLabel()
void Slic3r::GUI::ObjectGrid::DrawColLabel (wxDC & dc, int col) virtual
{
    if ( GetColWidth(col) <= 0 || m_colLabelHeight <= 0 )
        return;
    ObjectGridTable *table = dynamic_cast<ObjectGridTable *>(this->GetTable());
    if (table) {
        ObjectGridTable::ObjectGridCol* grid_col = table->get_grid_col(col);
        if (grid_col->b_icon)
            return;
        ObjectGridTable::ObjectGridCol* grid_next_col = table->get_grid_col(col+1);
        int colLeft = GetColLeft(col);
        int colWidth;
        if (grid_next_col&&grid_next_col->b_icon)
            colWidth = GetColWidth(col) + GetColWidth(col + 1);
        else
            colWidth = GetColWidth(col);
        wxRect rect(colLeft, 0, colWidth, m_colLabelHeight);
        wxGridColumnHeaderRendererDefault render;
        // It is reported that we need to erase the background to avoid display
        // artefacts, see #12055.
        {
            wxDCBrushChanger setBrush(dc, m_colLabelWin->GetBackgroundColour());
            wxDCPenChanger setPen(dc, *wxTRANSPARENT_PEN);
            dc.DrawRectangle(rect);
        }
        //render.DrawBorder(*this, dc, rect);
        int hAlign, vAlign;
        GetColLabelAlignment(&hAlign, &vAlign);
        const int orient = GetColLabelTextOrientation();
        render.DrawLabel(*this, dc, GetColLabelValue(col), rect, hAlign, vAlign, orient);
    }
}
References Slic3r::GUI::ObjectGridTable::ObjectGridCol::b_icon, col(), and Slic3r::GUI::ObjectGridTable::get_grid_col().
DrawColLabels()
void Slic3r::GUI::ObjectGrid::DrawColLabels (wxDC & dc, const wxArrayInt & cols) virtual
{
    wxGrid::DrawColLabels( dc, cols );
}
OnCellLeftClick()
bool Slic3r::GUI::ObjectGrid::OnCellLeftClick (wxGridEvent & event, int row, int col, ConfigOptionType type)
OnChar()
void Slic3r::GUI::ObjectGrid::OnChar (wxKeyEvent & event) protected
{
    auto keycode = event.GetKeyCode();
    if (keycode >= 0x20 && keycode <= 0x7F) {
        input_string = event.GetUnicodeKey();
    }
    event.Skip();
}
References input_string.
OnColHeadLeftClick()
void Slic3r::GUI::ObjectGrid::OnColHeadLeftClick (wxGridEvent & event)
{
    bool consumed = false;
    int col = event.GetCol();
    ObjectGridTable *table = dynamic_cast<ObjectGridTable *>(this->GetTable());
    if (table) {
        table->sort_by_col(col);
        consumed = true;
    }
    if (!consumed)
        event.Skip();
    else
        Refresh();
}
References col(), and Slic3r::GUI::ObjectGridTable::sort_by_col().
OnKeyDown()
void Slic3r::GUI::ObjectGrid::OnKeyDown (wxKeyEvent & event) protected
{
  // see include/wx/defs.h enum wxKeyCode
  int keyCode = event.GetKeyCode();
  int ctrlMask = wxMOD_CONTROL;
  int shiftMask = wxMOD_SHIFT;
  // Coordinates of the selected block to copy to clipboard.
  wxGridBlockCoords selection;
  wxTextDataObject text_data;
  if ((event.GetModifiers() & ctrlMask) != 0) {
    // CTRL is pressed
    switch (keyCode) {
    case 'c':
    case 'C':
    {
      // Check if we have any selected blocks and if we don't
      // have too many of them.
      const wxGridBlocks blocks = GetSelectedBlocks();
      wxGridBlocks::iterator iter = blocks.begin();
      if (iter == blocks.end())
      {
        // No selection, copy just the current cell.
        if (m_currentCellCoords == wxGridNoCellCoords)
        {
          // But we don't even have it -- nothing to do then.
          event.Skip();
          break;
        }
        selection = wxGridBlockCoords(GetGridCursorRow(),
          GetGridCursorCol(),
          GetGridCursorRow(),
          GetGridCursorCol());
      }
      else // We do have at least one selected block.
      {
        selection = *blocks.begin();
      }
      m_selected_block = selection;
      ObjectGridTable* table = dynamic_cast<ObjectGridTable*>(this->GetTable());
      if (GetGridCursorCol() == ObjectGridTable::col_printable ||
        GetGridCursorCol() == ObjectGridTable::col_enable_support) {
        m_cell_data = table->GetValueAsBool(GetGridCursorRow(), GetGridCursorCol()) ? wxT("1") : wxT("0");
      }
            else if (GetGridCursorCol() == ObjectGridTable::col_filaments) {
                m_cell_data = table->GetValue(GetGridCursorRow(), GetGridCursorCol());
            }
      else {
        m_cell_data = table->GetValue(GetGridCursorRow(), GetGridCursorCol());
      }
      break;
    }
    case 'v':
    case 'V': {
      wxTheClipboard->GetData(text_data);
      if (!m_cell_data.empty()) {
        text_data.SetText(m_cell_data);
      }
      paste_data(text_data);
      break;
    }
    case 'f':
    case 'F':
      //TODO: search
      break;
    case 'z':
    case 'Z':
      //TODO:
      break;
    default:
      event.Skip();
    }
  }
    event.Skip();
}
References Slic3r::GUI::ObjectGridTable::col_enable_support, Slic3r::GUI::ObjectGridTable::col_filaments, Slic3r::GUI::ObjectGridTable::col_printable, Slic3r::GUI::ObjectGridTable::GetValue(), Slic3r::GUI::ObjectGridTable::GetValueAsBool(), m_cell_data, m_selected_block, and paste_data().
OnKeyUp()
void Slic3r::GUI::ObjectGrid::OnKeyUp (wxKeyEvent & event) protected
{
    event.Skip();
}
OnRangeSelected()
void Slic3r::GUI::ObjectGrid::OnRangeSelected (wxGridRangeSelectEvent & ev)
{
  ev.Skip();
}
paste_data()
void Slic3r::GUI::ObjectGrid::paste_data (wxTextDataObject & text_data) private
{
    wxString buf = text_data.GetText();
    int clip_size = buf.size();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", clip_size %1%, pasted_data %2%") %clip_size %buf;
    if (clip_size <= 0)
        return;
    int src_top_row = m_selected_block.GetTopRow();
    int src_bottom_row = m_selected_block.GetBottomRow();
    int src_left_col = m_selected_block.GetLeftCol();
    int src_right_col = m_selected_block.GetRightCol();
    int src_row_cnt = src_bottom_row - src_top_row + 1;
    int src_col_cnt = src_right_col -src_left_col + 1;
    const wxGridBlocks blocks = GetSelectedBlocks();
    wxGridBlocks::iterator iter = blocks.begin();
    wxGridBlockCoords selection;
    if (iter == blocks.end())
    {
        // No selection, copy just the current cell.
        if (m_currentCellCoords == wxGridNoCellCoords)
        {
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", no selection and no current , can not paste");
            return;
        }
        selection = wxGridBlockCoords(GetGridCursorRow(),
            GetGridCursorCol(),
            GetGridCursorRow(),
            GetGridCursorCol());
    }
    else // We do have at least one selected block.
    {
        selection = *blocks.begin();
    }
    int dst_top_row = selection.GetTopRow();
    int dst_bottom_row = selection.GetBottomRow();
    int dst_left_col = selection.GetLeftCol();
    int dst_right_col = selection.GetRightCol();
    int dst_row_cnt = dst_bottom_row - dst_top_row + 1;
    int dst_col_cnt = dst_right_col - dst_left_col + 1;
    wxArrayString string_array;
    auto split = [](wxString& source, wxArrayString& array) {
        wxString temp = source;
        wxChar split_char1 = '\t';
        wxChar split_char2 = '\n';
        bool finished = false;
        while (!finished && (temp.Length() > 0)) {
            int pos = temp.find(split_char2);
            if (pos == 0)
            {
                temp = temp.substr(1);
                continue;
            }
            wxString temp_line;
            if (pos == wxString::npos)
            {
                temp_line = temp;
                finished = true;
            }
            else
            {
                temp_line = temp.substr(0, pos);
                temp = temp.substr(pos+1);
            }
            while(true) {
                pos = temp_line.find(split_char1);
                if (pos == 0)
                {
                    temp_line = temp_line.substr(1);
                    continue;
                }
                else if (pos == wxString::npos)
                {
                    if (temp_line.Length() > 0)
                    {
                        array.push_back(temp_line.Trim());
                        break;
                    }
                }
                else
                {
                    array.push_back(temp_line.substr(0, pos));
                    temp_line = temp_line.substr(pos+1);
                }
            }
        }
    };
    ObjectGridTable* grid_table = dynamic_cast <ObjectGridTable * >(GetTable());
    if ((src_row_cnt == 1) && (src_col_cnt == 1))
    {
        if ((dst_col_cnt != 1) || (dst_left_col != src_left_col)) {
            wxLogWarning(_L("one cell can only be copied to one or multiple cells in the same column"));
        }
        else {
      split(buf, string_array);
      wxString source_string = string_array[0];
      if (string_array.GetCount() <= 0) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(", can not split pasted data %1%") % buf;
        return;
      }
      for (int i = 0; i < dst_row_cnt; i++)
      {
        if (!this->IsReadOnly(dst_top_row + i, dst_left_col)) {
          grid_table->SetValue(dst_top_row + i, dst_left_col, source_string);
          grid_table->OnCellValueChanged(dst_top_row + i, dst_left_col);
        }
      }
        }
    }
    else {
        wxLogWarning(_L("multiple cells copy is not supported"));
        /*if ((src_col_cnt != 1) || (dst_left_col != src_left_col))
            wxLogWarning(_L("multiple columns copy is not supported"));
        else {
            split(buf, string_array);
            int count = string_array.GetCount();
            if ((count <= 0) || (count != src_row_cnt* src_col_cnt )){
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(", can not split pasted data %1%, count %2%, src_row_cnt %3%, src_col_cnt %4%")%buf %count %src_row_cnt %src_col_cnt;
                return;
            }
            for ( int i = 0; i < src_row_cnt; i++ )
                for ( int j = 0; j < src_col_cnt; j++ )
                {
                    if (!this->IsReadOnly(dst_top_row+i, dst_left_col+j)) {
                        grid_table->SetValue(dst_top_row+i, dst_left_col+j, string_array[i*src_col_cnt+j]);
                        grid_table->OnCellValueChanged(dst_top_row+i, dst_left_col+j);
                    }
                }
        }*/
    }
    this->ForceRefresh();
}
References _L, error, m_selected_block, Slic3r::GUI::ObjectGridTable::OnCellValueChanged(), and Slic3r::GUI::ObjectGridTable::SetValue().
Referenced by OnKeyDown().
wxDECLARE_EVENT_TABLE()
Slic3r::GUI::ObjectGrid::wxDECLARE_EVENT_TABLE () private
Friends And Related Symbol Documentation
ObjectGridTable
friend class ObjectGridTable friend
ObjectTablePanel
friend class ObjectTablePanel friend
Member Data Documentation
input_string
wxString Slic3r::GUI::ObjectGrid::input_string
Referenced by Slic3r::GUI::GridCellTextEditor::BeginEdit(), Slic3r::GUI::ObjectTablePanel::OnCellLeftClick(), and OnChar().
m_cell_data
wxString Slic3r::GUI::ObjectGrid::m_cell_data
Referenced by OnKeyDown().
m_selected_block
wxGridBlockCoords Slic3r::GUI::ObjectGrid::m_selected_block private
Referenced by OnKeyDown(), and paste_data().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectTable.hpp
src/slic3r/GUI/GUI_ObjectTable.cpp