OrcaSlicer: src/qhull/src/libqhullcpp/QhullRidge.cpp File Reference
QhullRidge.cpp File Reference
#include "libqhullcpp/QhullRidge.h"
#include "libqhullcpp/QhullSets.h"
#include "libqhullcpp/QhullVertex.h"
#include "libqhullcpp/Qhull.h"
Namespaces
namespace orgQhull
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
Functions
Global functions
ostream & operator<< (ostream &os, const QhullRidge &r)
ostream & operator<< (ostream &os, const QhullRidge::PrintRidge &pr)
Duplicate of qh_printridge [io_r.c].
Function Documentation
operator<<() [1/2]
ostream & operator<< (ostream & os, const QhullRidge & r)
{
    os << r.print("");
    return os;
}//<< QhullRidge
References orgQhull::QhullRidge::print().
operator<<() [2/2]
ostream & operator<< (ostream & os, const QhullRidge::PrintRidge & pr)
Duplicate of qh_printridge [io_r.c].
{
    if(*pr.print_message){
        os << pr.print_message << " ";
    }else{
        os << "     - ";
    }
    QhullRidge r= *pr.ridge;
    os << "r" << r.id();
    if(r.getRidgeT()->tested){
        os << " tested";
    }
    if(r.getRidgeT()->nonconvex){
        os << " nonconvex";
    }
    os << endl;
    os << r.vertices().print("           vertices:");
    if(r.getRidgeT()->top && r.getRidgeT()->bottom){
        os << "           between f" << r.topFacet().id() << " and f" << r.bottomFacet().id() << endl;
    }else if(r.getRidgeT()->top){
        os << "           top f" << r.topFacet().id() << endl;
    }else if(r.getRidgeT()->bottom){
        os << "           bottom f" << r.bottomFacet().id() << endl;
    }
    return os;
}//<< PrintRidge
References ridgeT::bottom, orgQhull::QhullRidge::bottomFacet(), orgQhull::QhullRidge::getRidgeT(), orgQhull::QhullFacet::id(), orgQhull::QhullRidge::id(), ridgeT::nonconvex, orgQhull::QhullVertexSet::print(), ridgeT::tested, ridgeT::top, orgQhull::QhullRidge::topFacet(), and orgQhull::QhullRidge::vertices().