OrcaSlicer: Slic3r::GUI::ObjectTablePanel Class Reference
Slic3r::GUI::ObjectTablePanel Class Reference
#include <src/slic3r/GUI/GUI_ObjectTable.hpp>
Public Member Functions
void OnCellLeftClick (wxGridEvent &)
void OnRowSize (wxGridSizeEvent &)
void OnColSize (wxGridSizeEvent &)
void OnSelectCell (wxGridEvent &)
void OnRangeSelected (wxGridRangeSelectEvent &)
void OnCellValueChanged (wxGridEvent &)
ObjectTablePanel (wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size, long style, const wxString &name, Plater *platerObj, Model *modelObj)
~ObjectTablePanel ()
void load_data ()
void SetSelection (int object_id, int volume_id)
void sort_by_default ()
wxSize get_init_size ()
void resetAllValuesInSideWindow (int row, bool is_object, ModelObject *object, ModelConfig *config, const std::string &category)
void set_default_filaments_and_colors ()
Public Attributes
int range_select_left_col
int range_select_right_col
int range_select_top_row
int range_select_bottom_row
std::vector< wxString > m_filaments_name
std::vector< wxColour > m_filaments_colors
int m_filaments_count { 1 }
Private Member Functions
int init_bitmap ()
int init_filaments_and_colors ()
wxDECLARE_ABSTRACT_CLASS (ObjectGrid)
wxDECLARE_EVENT_TABLE ()
Private Attributes
wxColour m_bg_colour
wxColour m_hover_colour
wxBoxSizer * m_top_sizer {nullptr}
wxBoxSizer * m_page_sizer {nullptr}
wxBoxSizer * m_page_top_sizer {nullptr}
wxTextCtrl * m_search_line { nullptr }
ObjectGrid * m_object_grid {nullptr}
ObjectGridTable * m_object_grid_table {nullptr}
wxStaticText * m_page_text {nullptr}
ScalableButton * m_global_reset {nullptr}
wxScrolledWindow * m_side_window {nullptr}
ObjectTableSettings * m_object_settings { nullptr }
Model * m_model {nullptr}
ModelConfig * m_config {nullptr}
Plater * m_plater {nullptr}
int m_cur_row { -1 }
int m_cur_col { -1 }
wxFloatingPointValidator< float > m_float_validator
wxBitmap m_undo_bitmap
std::vector< wxBitmap * > m_color_bitmaps
ScalableBitmap m_bmp_reset
ScalableBitmap m_bmp_reset_disable
Friends
class ObjectGridTable
Detailed Description
Constructor & Destructor Documentation
ObjectTablePanel()
Slic3r::GUI::ObjectTablePanel::ObjectTablePanel (wxWindow * parent, wxWindowID id, const wxPoint & pos, const wxSize & size, long style, const wxString & name, Plater * platerObj, Model * modelObj)
~ObjectTablePanel()
Slic3r::GUI::ObjectTablePanel::~ObjectTablePanel ()
{
    //do it in the grid
    /*if (m_object_grid_table) {
        m_object_grid_table->release_object_configs();
        delete m_object_grid_table;
        m_object_grid_table = nullptr;
    }*/
    if (m_top_sizer)
        m_top_sizer->Clear(true);
    delete m_object_settings;
    m_filaments_name.clear();
    m_filaments_colors.clear();
}
References m_filaments_colors, m_filaments_name, m_object_settings, and m_top_sizer.
Member Function Documentation
get_init_size()
wxSize Slic3r::GUI::ObjectTablePanel::get_init_size ()
{
    wxSize size;
    int width = 0, height = 0;
    //compute height
    int row_count = m_object_grid_table->GetNumberRows();
    if (row_count >= g_overflow_row_count) {
        height = row_count * g_min_row_size;
    }
    else {
        for (int index = 0; index < m_object_grid_table->GetNumberRows(); index++)
        {
            height += m_object_grid->GetRowSize(index);
        }
    }
    height += g_extra_height;
    if (height < (g_min_row_count * g_min_row_size))
        height = g_min_row_count * g_min_row_size;
    //compute width
    for (int index = 0; index < m_object_grid_table->GetNumberCols(); index++)
    {
        width += m_object_grid->GetColSize(index);
    }
    width += g_vscroll_width + g_min_setting_width;
    size.Set(width, height);
    return size;
}
References Slic3r::GUI::g_extra_height, Slic3r::GUI::g_min_row_count, Slic3r::GUI::g_min_row_size, Slic3r::GUI::g_min_setting_width, Slic3r::GUI::g_overflow_row_count, Slic3r::GUI::g_vscroll_width, Slic3r::GUI::ObjectGridTable::GetNumberCols(), Slic3r::GUI::ObjectGridTable::GetNumberRows(), m_object_grid, m_object_grid_table, and size.
Referenced by Slic3r::GUI::ObjectTableDialog::ObjectTableDialog(), OnColSize(), and OnRowSize().
init_bitmap()
int Slic3r::GUI::ObjectTablePanel::init_bitmap () private
{
    m_undo_bitmap = create_scaled_bitmap("lock_normal", nullptr, 18);
    m_color_bitmaps = get_extruder_color_icons();
    return 0;
}
References create_scaled_bitmap(), get_extruder_color_icons(), m_color_bitmaps, and m_undo_bitmap.
init_filaments_and_colors()
int Slic3r::GUI::ObjectTablePanel::init_filaments_and_colors () private
{
    //DynamicPrintConfig&  global_config   = wxGetApp().preset_bundle->prints.get_edited_preset().config;
    const DynamicPrintConfig* global_config = m_plater->config();
    const std::vector<std::string> filament_presets = wxGetApp().preset_bundle->filament_presets;
    m_filaments_count = filament_presets.size();
    if (m_filaments_count <= 0) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(", can not get filaments, count: %1%, set to default") %m_filaments_count;
        set_default_filaments_and_colors();
        return -1;
    }
    const ConfigOptionStrings* filament_opt = dynamic_cast<const ConfigOptionStrings*>(global_config->option("filament_colour"));
    if (filament_opt == nullptr) {
        set_default_filaments_and_colors();
        return -1;
    }
    m_filaments_colors.resize(m_filaments_count);
    m_filaments_name.resize(m_filaments_count);
    unsigned int color_count = filament_opt->values.size();
    if (color_count != m_filaments_count) {
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(", invalid color count:%1%, extruder count: %2%") %color_count %m_filaments_count;
    }
    unsigned int i = 0;
    unsigned char rgb[3];
    while (i < m_filaments_count) {
        const std::string& txt_color = global_config->opt_string("filament_colour", i);
        if (i < color_count) {
            if (Slic3r::GUI::BitmapCache::parse_color(txt_color, rgb))
            {
                m_filaments_colors[i] = wxColour(rgb[0], rgb[1], rgb[2]);
            }
            else
            {
                m_filaments_colors[i] = *wxGREEN;
            }
        }
        else {
            m_filaments_colors[i] = *wxGREEN;
        }
        //parse the filaments
        m_filaments_name[i] = wxString(std::to_string(i+1) + ": " + filament_presets[i]);
        i++;
    }
    return 0;
}
References Slic3r::GUI::Plater::config(), error, m_filaments_colors, m_filaments_count, m_filaments_name, m_plater, Slic3r::DynamicConfig::opt_string(), Slic3r::ConfigBase::option(), Slic3r::GUI::BitmapCache::parse_color(), set_default_filaments_and_colors(), and Slic3r::ConfigOptionVector< T >::values.
load_data()
void Slic3r::GUI::ObjectTablePanel::load_data ()
{
    int rows, cols;
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(", enter");
    m_object_grid_table->construct_object_configs(m_object_grid);
    m_object_grid->AssignTable(m_object_grid_table);
    rows = m_object_grid_table->get_row_count();
    cols = m_object_grid_table->get_col_count();
    //construct tables
    //m_object_grid->CreateGrid(rows, cols, wxGridSelectCells);
#if HAS_COL_HEADER
    m_object_grid->SetColLabelAlignment(wxALIGN_LEFT, wxALIGN_CENTER);
    m_object_grid->SetColLabelValue(ObjectGridTable::col_printable, _L("Printable"));
    m_object_grid->SetColLabelValue(ObjectGridTable::col_printable_reset, "");
    m_object_grid->SetColLabelValue(ObjectGridTable::col_plate_index, wxString::Format("%S%S", _L("Plate"), wxString::FromUTF8("\u2191\u2193")));
    /*m_object_grid->SetColLabelValue(ObjectGridTable::col_assemble_name, L("Module"));*/
    m_object_grid->SetColLabelValue(ObjectGridTable::col_name, wxString::Format("%S%S", _L("Name"), wxString::FromUTF8("\u2191\u2193")));
    m_object_grid->SetColLabelValue(ObjectGridTable::col_filaments, wxString::Format("%S%S", _L("Filament"), wxString::FromUTF8("\u2191\u2193")));
    m_object_grid->SetColLabelValue(ObjectGridTable::col_filaments_reset, "");
    m_object_grid->SetColLabelValue(ObjectGridTable::col_layer_height, _L("Layer height"));
    m_object_grid->SetColLabelValue(ObjectGridTable::col_layer_height_reset, "");
    m_object_grid->SetColLabelValue(ObjectGridTable::col_wall_loops, _L("Wall loops"));
    m_object_grid->SetColLabelValue(ObjectGridTable::col_wall_loops_reset, "");
    m_object_grid->SetColLabelValue(ObjectGridTable::col_fill_density, _L("Infill density(%)"));
    m_object_grid->SetColLabelValue(ObjectGridTable::col_fill_density_reset, "");
    m_object_grid->SetColLabelValue(ObjectGridTable::col_enable_support, _L("Support"));
    m_object_grid->SetColLabelValue(ObjectGridTable::col_enable_support_reset, "");
    m_object_grid->SetColLabelValue(ObjectGridTable::col_brim_type, _L("Brim"));
    m_object_grid->SetColLabelValue(ObjectGridTable::col_brim_type_reset, "");
    m_object_grid->SetColLabelValue(ObjectGridTable::col_speed_perimeter, _L("Outer wall speed"));
    m_object_grid->SetColLabelValue(ObjectGridTable::col_speed_perimeter_reset, "");
    m_object_grid->SetLabelFont(Label::Head_13);
    m_object_grid->SetLabelTextColour(StateColor::darkModeColorFor(wxColour("#303A3C")));
    m_object_grid->SetLabelBackgroundColour( wxColour("#FFFFFF"));
#else
    m_object_grid->HideColLabels();
#endif
    m_object_grid->HideRowLabels();
    m_object_grid->EnableGridLines (false);
    m_object_grid->EnableDragColSize(false);
    m_object_grid->EnableDragGridSize(false);
    m_object_grid->EnableDragRowSize(false);
    /*set the first row as label*/
    //format
    wxGridCellAttr *attr;
    attr = new wxGridCellAttr;
    //attr->SetBackgroundColour(wxColour(191, 191, 255));
    attr->SetBackgroundColour(*wxWHITE);
    attr->SetTextColour(*wxBLACK);
    attr->SetAlignment(wxALIGN_LEFT, wxALIGN_CENTRE);
    attr->SetReadOnly(true);
    m_object_grid->SetRowAttr (0, attr);
#if HAS_COL_HEADER
    m_object_grid->SetRowSize(0, 0);
#endif
    //merges
    m_object_grid->SetCellSize(0, ObjectGridTable::col_printable, 1, 2);
    //m_object_grid->SetCellSize(0, ObjectGridTable::col_assemble_name, 1, 1);
    m_object_grid->SetCellSize(0, ObjectGridTable::col_name, 1, 1);
    m_object_grid->SetCellSize(0, ObjectGridTable::col_filaments, 1, 1);
    m_object_grid->SetCellSize(0, ObjectGridTable::col_layer_height, 1, 2);
    m_object_grid->SetCellSize(0, ObjectGridTable::col_wall_loops, 1, 2);
    m_object_grid->SetCellSize(0, ObjectGridTable::col_fill_density, 1, 2);
    m_object_grid->SetCellSize(0, ObjectGridTable::col_enable_support, 1, 2);
    m_object_grid->SetCellSize(0, ObjectGridTable::col_brim_type, 1, 2);
    m_object_grid->SetCellSize(0, ObjectGridTable::col_speed_perimeter, 1, 2);
    //m_object_grid->SetSelectionForeground(wxColour(0xDB,0xFD,0xE7));
    //m_object_grid->SetSelectionBackground(*wxWHITE);
    m_object_grid->SetDefaultCellBackgroundColour(StateColor::darkModeColorFor(*wxWHITE));
    for (int col = 0; col < cols; col++)
    {
        ObjectGridTable::ObjectGridCol* grid_col = m_object_grid_table->get_grid_col(col);
        m_object_grid->SetColSize(col, grid_col->size);
        for (int row = 1; row < rows; row++)
        {
            ObjectGridTable::ObjectGridRow* grid_row = m_object_grid_table->get_grid_row(row-1);
            m_object_grid->SetCellAlignment(row, col, grid_col->horizontal_align, wxALIGN_CENTRE );
            m_object_grid->SetCellOverflow(row, col, false);
            //m_object_grid->SetCellBackgroundColour (row, col, *wxLIGHT_GREY);
            m_object_grid->SetCellBackgroundColour (row, col, StateColor::darkModeColorFor(*wxWHITE));
            m_object_grid->SetCellTextColour(row, col,StateColor::darkModeColorFor(wxColour(*wxBLACK)));
            //set the render and editor
            if (grid_col->b_icon) {
                m_object_grid->SetCellRenderer(row, col, new GridCellIconRenderer());
                m_object_grid->SetReadOnly(row, col);
            }
            //else if (grid_col->b_for_object && (grid_row->row_type == ObjectGridTable::row_volume)) {
            //    /*m_object_grid->SetReadOnly(row, col);
            //    m_object_grid->SetCellEditor(row, col, new wxGridCellAutoWrapStringEditor());
            //    m_object_grid->SetCellRenderer(row, col, new wxGridCellAutoWrapStringRenderer());*/
            //}
            else {
                if (!grid_col->b_editable)
                    m_object_grid->SetReadOnly(row, col);
                //set editor
                switch (grid_col->type)
                {
                    case coString:
                        m_object_grid->SetCellEditor(row, col, new GridCellTextEditor());
                        //m_object_grid->SetCellRenderer(row, col, new wxGridCellAutoWrapStringRenderer());
                        m_object_grid->SetCellFitMode(row, col, wxGridFitMode::Ellipsize());
                        break;
                    case coBool:
                        m_object_grid->SetCellEditor(row, col, new GridCellSupportEditor());
                        //m_object_grid->SetCellEditor(row, col, new wxGridCellBoolEditor());
                        //m_object_grid->SetCellRenderer(row, col, new GridCellSupportRenderer());
                        m_object_grid->SetCellRenderer(row, col, new GridCellSupportRenderer());
                        break;
                    case coInt:
                        m_object_grid->SetCellEditor(row, col, new GridCellTextEditor());
                        m_object_grid->SetCellRenderer(row, col, new  wxGridCellNumberRenderer());
                        break;
                    case coEnum:
                        if (col == ObjectGridTable::col_filaments) {
                            if (grid_row->model_volume_type != ModelVolumeType::NEGATIVE_VOLUME) {
                                GridCellFilamentsEditor* filament_editor = new GridCellFilamentsEditor(grid_col->choice_count, grid_col->choices, false, &m_color_bitmaps);
                                m_object_grid->SetCellEditor(row, col, filament_editor);
                                m_object_grid->SetCellRenderer(row, col, new GridCellFilamentsRenderer());
                            }
                            else {
                                m_object_grid->SetCellEditor(row, col, new GridCellTextEditor());
                                auto gcfil = new GridCellFilamentsRenderer();
                                m_object_grid->SetCellRenderer(row, col, gcfil);
                                m_object_grid->SetReadOnly(row, col);
                                //m_object_grid->SetCellFitMode(row, col,  wxGridFitMode::Ellipsize());
                            }
                        }
                        else {
                            GridCellChoiceEditor* combo_editor = new GridCellChoiceEditor(grid_col->choice_count, grid_col->choices);
                            m_object_grid->SetCellEditor(row, col, combo_editor);
                            m_object_grid->SetCellRenderer(row, col, new wxGridCellChoiceRenderer());
                        }
                        break;
                    case coFloat: {
            m_object_grid->SetCellEditor(row, col, new GridCellTextEditor());
            if (col == ObjectGridTable::col_speed_perimeter) {
              m_object_grid->SetCellRenderer(row, col, new wxGridCellFloatRenderer(6, 0));
            }
            else {
              m_object_grid->SetCellRenderer(row, col, new wxGridCellFloatRenderer(6, 2));
            }
            break;
                    }
                    case coPercent:
                    {
                        m_object_grid->SetCellEditor(row, col, new GridCellTextEditor());
                        m_object_grid->SetCellRenderer(row, col, new wxGridCellFloatRenderer(6,1));
                        break;
                    }
                    default:
                        break;
                }
                if (col == ObjectGridTable::col_name) {
                    m_object_grid->SetCellFont(row, col, Label::Body_13);
                    /* if (grid_row->row_type == ObjectGridTable::row_object)
                         m_object_grid->SetCellFont(row, col, Label::Head_14);
                     else
                         m_object_grid->SetCellFont(row, col, Label::Body_14);*/
                }
            }
        }
    }
    for (int i = 0; i < ObjectGridTable::col_max; i++)
    {
        ObjectGridTable::ObjectGridCol *grid_col = m_object_grid_table->get_grid_col(i);
        if (grid_col->size > 0) {
            int fit_size1 = m_object_grid->GetColSize(i);
            m_object_grid->SetColSize(i, grid_col->size);
        }
    }
    m_object_grid->Fit();
    for (int i = 0; i < ObjectGridTable::col_max; i++) {
        switch (i) {
      /* case ObjectGridTable::col_printable: {
         m_object_grid->SetColSize(i, m_object_grid->GetColSize(i) - FromDIP(28) - FromDIP(5));
         break;
       }*/
    case ObjectGridTable::col_printable_reset:
      m_object_grid->SetColSize(i, FromDIP(0));
      break;
        case ObjectGridTable::col_name:
            m_object_grid->SetColSize(i, FromDIP(140));
            break;
       /* case ObjectGridTable::col_filaments:
            m_object_grid->SetColSize(i, FromDIP(55));
            break;*/
        case ObjectGridTable::col_filaments_reset:
            m_object_grid->SetColSize(i, FromDIP(0));
            break;
        case ObjectGridTable::col_layer_height: {
            auto width = m_object_grid->GetColSize(i) - FromDIP(28);
            if (width < m_object_grid->GetTextExtent(("000.00")).x) {
                width = m_object_grid->GetTextExtent(("000.00")).x;
            }
            m_object_grid->SetColSize(i, width);
            break;
        }
        case ObjectGridTable::col_layer_height_reset:
            m_object_grid->SetColSize(i, FromDIP(28));
            break;
        case ObjectGridTable::col_wall_loops: {
      auto width = m_object_grid->GetColSize(i) - FromDIP(28);
      if (width < m_object_grid->GetTextExtent(("000.00")).x) {
        width = m_object_grid->GetTextExtent(("000.00")).x;
      }
      m_object_grid->SetColSize(i, width);
            break;
        }
        case ObjectGridTable::col_wall_loops_reset:
            m_object_grid->SetColSize(i, FromDIP(28));
            break;
        case ObjectGridTable::col_fill_density:
            m_object_grid->SetColSize(i, m_object_grid->GetColSize(i) - FromDIP(28));
            break;
        case ObjectGridTable::col_fill_density_reset:
            m_object_grid->SetColSize(i, FromDIP(28));
            break;
        case ObjectGridTable::col_enable_support:
            m_object_grid->SetColSize(i, m_object_grid->GetColSize(i) - FromDIP(28));
            break;
        case ObjectGridTable::col_enable_support_reset:
            m_object_grid->SetColSize(i, FromDIP(28));
            break;
        case ObjectGridTable::col_brim_type:
            m_object_grid->SetColSize(i, FromDIP(56));
            break;
        case ObjectGridTable::col_brim_type_reset:
            m_object_grid->SetColSize(i, FromDIP(28));
            break;
        case ObjectGridTable::col_speed_perimeter: {
            auto width = m_object_grid->GetColSize(i) - FromDIP(28);
            if (width < m_object_grid->GetTextExtent(("000.00")).x) { width = m_object_grid->GetTextExtent(("000.00")).x; }
            m_object_grid->SetColSize(i, width);
            break;
        }
        case ObjectGridTable::col_speed_perimeter_reset:
            m_object_grid->SetColSize(i, FromDIP(28));
            break;
        }
    }
    m_object_grid->SetGridLineColour(*wxWHITE);
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(", finished, got %1% rows, %2% cols") %m_object_grid_table->GetNumberRows() %m_object_grid_table->GetNumberCols() ;
}
References _L, Slic3r::GUI::ObjectGridTable::ObjectGridCol::b_editable, Slic3r::GUI::ObjectGridTable::ObjectGridCol::b_icon, Label::Body_13, Slic3r::GUI::ObjectGridTable::ObjectGridCol::choice_count, Slic3r::GUI::ObjectGridTable::ObjectGridCol::choices, Slic3r::coBool, Slic3r::coEnum, Slic3r::coFloat, Slic3r::coInt, col(), Slic3r::GUI::ObjectGridTable::col_brim_type, Slic3r::GUI::ObjectGridTable::col_brim_type_reset, Slic3r::GUI::ObjectGridTable::col_enable_support, Slic3r::GUI::ObjectGridTable::col_enable_support_reset, Slic3r::GUI::ObjectGridTable::col_filaments, Slic3r::GUI::ObjectGridTable::col_filaments_reset, Slic3r::GUI::ObjectGridTable::col_fill_density, Slic3r::GUI::ObjectGridTable::col_fill_density_reset, Slic3r::GUI::ObjectGridTable::col_layer_height, Slic3r::GUI::ObjectGridTable::col_layer_height_reset, Slic3r::GUI::ObjectGridTable::col_max, Slic3r::GUI::ObjectGridTable::col_name, Slic3r::GUI::ObjectGridTable::col_plate_index, Slic3r::GUI::ObjectGridTable::col_printable, Slic3r::GUI::ObjectGridTable::col_printable_reset, Slic3r::GUI::ObjectGridTable::col_speed_perimeter, Slic3r::GUI::ObjectGridTable::col_speed_perimeter_reset, Slic3r::GUI::ObjectGridTable::col_wall_loops, Slic3r::GUI::ObjectGridTable::col_wall_loops_reset, Slic3r::GUI::ObjectGridTable::construct_object_configs(), Slic3r::coPercent, Slic3r::coString, StateColor::darkModeColorFor(), Slic3r::GUI::ObjectGridTable::get_col_count(), Slic3r::GUI::ObjectGridTable::get_grid_col(), Slic3r::GUI::ObjectGridTable::get_grid_row(), Slic3r::GUI::ObjectGridTable::get_row_count(), Slic3r::GUI::ObjectGridTable::GetNumberCols(), Slic3r::GUI::ObjectGridTable::GetNumberRows(), Label::Head_13, Slic3r::GUI::ObjectGridTable::ObjectGridCol::horizontal_align, m_color_bitmaps, m_object_grid, m_object_grid_table, Slic3r::GUI::ObjectGridTable::ObjectGridRow::model_volume_type, Slic3r::NEGATIVE_VOLUME, row(), Slic3r::GUI::ObjectGridTable::ObjectGridCol::size, and Slic3r::GUI::ObjectGridTable::ObjectGridCol::type.
OnCellLeftClick()
void Slic3r::GUI::ObjectTablePanel::OnCellLeftClick (wxGridEvent & ev)
{
    int row = ev.GetRow();
    int col = ev.GetCol();
    ConfigOptionType type     = coNone;
    bool             consumed = m_object_grid_table->OnCellLeftClick(row, col, type);
    if (consumed) {
        m_object_grid->ClearSelection();
        m_object_grid->SelectBlock(row, col-1, row, col-1, true);
        //return;
    }
    m_object_grid->input_string = wxEmptyString;
    ev.Skip();
    //consumed = m_object_grid->OnCellLeftClick(ev, row, col, type);
    //if (!consumed) ev.Skip();
}
References col(), Slic3r::coNone, Slic3r::GUI::ObjectGrid::input_string, m_object_grid, m_object_grid_table, Slic3r::GUI::ObjectGridTable::OnCellLeftClick(), and row().
OnCellValueChanged()
void Slic3r::GUI::ObjectTablePanel::OnCellValueChanged (wxGridEvent & ev)
{
    int row = ev.GetRow();
    int col = ev.GetCol();
    m_object_grid_table->OnCellValueChanged(row, col);
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format("cell (%1%, %2%) changed from %3% to %4%") %row %col %ev.GetString() % m_object_grid->GetCellValue(row, col);
    ev.Skip();
}
References col(), m_object_grid, m_object_grid_table, Slic3r::GUI::ObjectGridTable::OnCellValueChanged(), and row().
OnColSize()
void Slic3r::GUI::ObjectTablePanel::OnColSize (wxGridSizeEvent & ev)
{
    wxSize panel_size = get_init_size();
    g_dialog_max_width = (panel_size.GetWidth() > g_max_size_from_parent.GetWidth())?g_max_size_from_parent.GetWidth():panel_size.GetWidth();
    g_dialog_max_height =(panel_size.GetHeight() > g_max_size_from_parent.GetHeight())?g_max_size_from_parent.GetHeight():panel_size.GetHeight();
    this->SetMaxSize(wxSize(g_dialog_max_width, g_dialog_max_height));
    wxSize current_size = GetParent()->GetSize();
    //if (current_size.GetWidth() < g_dialog_max_width)
        GetParent()->SetMaxSize(wxSize(g_dialog_max_width, g_dialog_max_height));
    GetParent()->SetSize(wxSize(g_dialog_max_width, g_dialog_max_height));
}
References Slic3r::GUI::g_dialog_max_height, Slic3r::GUI::g_dialog_max_width, Slic3r::GUI::g_max_size_from_parent, and get_init_size().
OnRangeSelected()
void Slic3r::GUI::ObjectTablePanel::OnRangeSelected (wxGridRangeSelectEvent & ev)
{
    range_select_left_col = ev.GetLeftCol();
    range_select_right_col = ev.GetRightCol();
    range_select_top_row = ev.GetTopRow();
    range_select_bottom_row = ev.GetBottomRow();
    ev.Skip();
}
References range_select_bottom_row, range_select_left_col, range_select_right_col, and range_select_top_row.
OnRowSize()
void Slic3r::GUI::ObjectTablePanel::OnRowSize (wxGridSizeEvent & ev)
{
    wxSize panel_size = get_init_size();
    g_dialog_max_width = (panel_size.GetWidth() > g_max_size_from_parent.GetWidth())?g_max_size_from_parent.GetWidth():panel_size.GetWidth();
    g_dialog_max_height =(panel_size.GetHeight() > g_max_size_from_parent.GetHeight())?g_max_size_from_parent.GetHeight():panel_size.GetHeight();
    this->SetMaxSize(wxSize(g_dialog_max_width, g_dialog_max_height));
    wxSize current_size = GetParent()->GetSize();
    //if (current_size.GetHeight() < g_dialog_max_height)
        GetParent()->SetMaxSize(wxSize(g_dialog_max_width, g_dialog_max_height));
    GetParent()->SetSize(wxSize(g_dialog_max_width, g_dialog_max_height));
}
References Slic3r::GUI::g_dialog_max_height, Slic3r::GUI::g_dialog_max_width, Slic3r::GUI::g_max_size_from_parent, and get_init_size().
OnSelectCell()
void Slic3r::GUI::ObjectTablePanel::OnSelectCell (wxGridEvent & ev)
{
    int row = ev.GetRow();
    int col = ev.GetCol();
    if ((row == m_cur_row) && (col == m_cur_col))
    {
        //the same cel selected
        return;
    }
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format("cell (%1%, %2%) selected") %row %col;
    m_object_grid_table->OnSelectCell(row, col);
    m_cur_row = row;
    m_cur_col = col;
    ev.Skip();
}
References col(), m_cur_col, m_cur_row, m_object_grid_table, Slic3r::GUI::ObjectGridTable::OnSelectCell(), and row().
resetAllValuesInSideWindow()
void Slic3r::GUI::ObjectTablePanel::resetAllValuesInSideWindow (int row, bool is_object, ModelObject * object, ModelConfig * config, const std::string & category)
{
    //
    m_object_settings->resetAllValues(row, is_object, object, config, category);
}
References m_object_settings, Slic3r::GUI::ObjectTableSettings::resetAllValues(), and row().
Referenced by Slic3r::GUI::ObjectGridTable::resetValuesInCurrentCell().
set_default_filaments_and_colors()
void Slic3r::GUI::ObjectTablePanel::set_default_filaments_and_colors () inline
    {
        m_filaments_count = 1;
        m_filaments_colors.push_back(*wxGREEN);
        m_filaments_name.push_back("Generic PLA");
    }
References m_filaments_colors, m_filaments_count, and m_filaments_name.
Referenced by init_filaments_and_colors().
SetSelection()
void Slic3r::GUI::ObjectTablePanel::SetSelection (int object_id, int volume_id)
{
    m_object_grid_table->SetSelection(object_id, volume_id);
}
References m_object_grid_table, and Slic3r::GUI::ObjectGridTable::SetSelection().
Referenced by Slic3r::GUI::ObjectTableDialog::Popup().
sort_by_default()
void Slic3r::GUI::ObjectTablePanel::sort_by_default () inline
{ m_object_grid_table->sort_by_default(); }
References m_object_grid_table, and Slic3r::GUI::ObjectGridTable::sort_by_default().
Referenced by Slic3r::GUI::ObjectTableDialog::Popup().
wxDECLARE_ABSTRACT_CLASS()
Slic3r::GUI::ObjectTablePanel::wxDECLARE_ABSTRACT_CLASS (ObjectGrid) private
wxDECLARE_EVENT_TABLE()
Slic3r::GUI::ObjectTablePanel::wxDECLARE_EVENT_TABLE () private
Friends And Related Symbol Documentation
ObjectGridTable
friend class ObjectGridTable friend
Member Data Documentation
m_bg_colour
wxColour Slic3r::GUI::ObjectTablePanel::m_bg_colour private
m_bmp_reset
ScalableBitmap Slic3r::GUI::ObjectTablePanel::m_bmp_reset private
m_bmp_reset_disable
ScalableBitmap Slic3r::GUI::ObjectTablePanel::m_bmp_reset_disable private
m_color_bitmaps
std::vector<wxBitmap*> Slic3r::GUI::ObjectTablePanel::m_color_bitmaps private
Referenced by Slic3r::GUI::ObjectGridTable::get_color_bitmap(), init_bitmap(), load_data(), and Slic3r::GUI::ObjectGridTable::update_row_properties().
m_config
ModelConfig* Slic3r::GUI::ObjectTablePanel::m_config {nullptr} private
m_cur_col
int Slic3r::GUI::ObjectTablePanel::m_cur_col { -1 } private
Referenced by OnSelectCell().
m_cur_row
int Slic3r::GUI::ObjectTablePanel::m_cur_row { -1 } private
Referenced by OnSelectCell().
m_filaments_colors
std::vector<wxColour> Slic3r::GUI::ObjectTablePanel::m_filaments_colors
Referenced by ~ObjectTablePanel(), init_filaments_and_colors(), and set_default_filaments_and_colors().
m_filaments_count
int Slic3r::GUI::ObjectTablePanel::m_filaments_count { 1 }
Referenced by Slic3r::GUI::ObjectGridTable::init_cols(), init_filaments_and_colors(), Slic3r::GUI::ObjectGridTable::OnCellLeftClick(), set_default_filaments_and_colors(), and Slic3r::GUI::ObjectGridTable::SetValue().
m_filaments_name
std::vector<wxString> Slic3r::GUI::ObjectTablePanel::m_filaments_name
Referenced by ~ObjectTablePanel(), Slic3r::GUI::ObjectGridTable::init_cols(), init_filaments_and_colors(), and set_default_filaments_and_colors().
m_float_validator
wxFloatingPointValidator<float> Slic3r::GUI::ObjectTablePanel::m_float_validator private
m_global_reset
ScalableButton* Slic3r::GUI::ObjectTablePanel::m_global_reset {nullptr} private
m_hover_colour
wxColour Slic3r::GUI::ObjectTablePanel::m_hover_colour private
m_model
Model* Slic3r::GUI::ObjectTablePanel::m_model {nullptr} private
Referenced by Slic3r::GUI::ObjectGridTable::construct_object_configs(), Slic3r::GUI::ObjectGridTable::OnCellLeftClick(), Slic3r::GUI::ObjectGridTable::OnCellValueChanged(), Slic3r::GUI::ObjectGridTable::OnSelectCell(), Slic3r::GUI::ObjectGridTable::reload_cell_data(), Slic3r::GUI::ObjectGridTable::resetValuesInCurrentCell(), Slic3r::GUI::ObjectGridTable::SetValue(), and Slic3r::GUI::ObjectGridTable::SetValueAsBool().
m_object_grid
ObjectGrid* Slic3r::GUI::ObjectTablePanel::m_object_grid {nullptr} private
Referenced by get_init_size(), load_data(), Slic3r::GUI::ObjectGridTable::OnCellLeftClick(), OnCellLeftClick(), OnCellValueChanged(), Slic3r::GUI::ObjectGridTable::reload_cell_data(), Slic3r::GUI::ObjectGridTable::SetSelection(), Slic3r::GUI::ObjectGridTable::SetValueAsBool(), Slic3r::GUI::ObjectGridTable::update_row_properties(), and Slic3r::GUI::ObjectGridTable::update_volume_values_from_object().
m_object_grid_table
ObjectGridTable* Slic3r::GUI::ObjectTablePanel::m_object_grid_table {nullptr} private
Referenced by get_init_size(), load_data(), OnCellLeftClick(), OnCellValueChanged(), OnSelectCell(), SetSelection(), and sort_by_default().
m_object_settings
ObjectTableSettings* Slic3r::GUI::ObjectTablePanel::m_object_settings { nullptr } private
Referenced by ~ObjectTablePanel(), Slic3r::GUI::ObjectGridTable::OnCellLeftClick(), Slic3r::GUI::ObjectGridTable::OnCellValueChanged(), Slic3r::GUI::ObjectGridTable::OnSelectCell(), and resetAllValuesInSideWindow().
m_page_sizer
wxBoxSizer* Slic3r::GUI::ObjectTablePanel::m_page_sizer {nullptr} private
m_page_text
wxStaticText* Slic3r::GUI::ObjectTablePanel::m_page_text {nullptr} private
m_page_top_sizer
wxBoxSizer* Slic3r::GUI::ObjectTablePanel::m_page_top_sizer {nullptr} private
m_plater
Plater* Slic3r::GUI::ObjectTablePanel::m_plater {nullptr} private
Referenced by Slic3r::GUI::ObjectGridTable::construct_object_configs(), and init_filaments_and_colors().
m_search_line
wxTextCtrl* Slic3r::GUI::ObjectTablePanel::m_search_line { nullptr } private
m_side_window
wxScrolledWindow* Slic3r::GUI::ObjectTablePanel::m_side_window {nullptr} private
Referenced by Slic3r::GUI::ObjectGridTable::OnCellLeftClick(), Slic3r::GUI::ObjectGridTable::OnCellValueChanged(), and Slic3r::GUI::ObjectGridTable::OnSelectCell().
m_top_sizer
wxBoxSizer* Slic3r::GUI::ObjectTablePanel::m_top_sizer {nullptr} private
Referenced by ~ObjectTablePanel().
m_undo_bitmap
wxBitmap Slic3r::GUI::ObjectTablePanel::m_undo_bitmap private
Referenced by Slic3r::GUI::ObjectGridTable::get_undo_bitmap(), and init_bitmap().
range_select_bottom_row
int Slic3r::GUI::ObjectTablePanel::range_select_bottom_row
Referenced by OnRangeSelected().
range_select_left_col
int Slic3r::GUI::ObjectTablePanel::range_select_left_col
Referenced by OnRangeSelected().
range_select_right_col
int Slic3r::GUI::ObjectTablePanel::range_select_right_col
Referenced by OnRangeSelected().
range_select_top_row
int Slic3r::GUI::ObjectTablePanel::range_select_top_row
Referenced by OnRangeSelected().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectTable.hpp
src/slic3r/GUI/GUI_ObjectTable.cpp