OrcaSlicer: Slic3r::GUI::MaterialItem Class Reference
Slic3r::GUI::MaterialItem Class Reference
#include <src/slic3r/GUI/AmsMappingPopup.hpp>
Public Member Functions
MaterialItem (wxWindow *parent, wxColour mcolour, wxString mname)
~MaterialItem ()
void msw_rescale ()
void set_ams_info (wxColour col, wxString txt)
void on_normal ()
void on_selected ()
void on_warning ()
void on_left_down (wxMouseEvent &evt)
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void doRender (wxDC &dc)
Public Attributes
wxPanel * m_main_panel
wxColour m_material_coloul
wxString m_material_name
wxColour m_ams_coloul
wxString m_ams_name
ScalableBitmap m_arraw_bitmap_gray
ScalableBitmap m_arraw_bitmap_white
bool m_selected {false}
bool m_warning {false}
Detailed Description
Constructor & Destructor Documentation
MaterialItem()
Slic3r::GUI::MaterialItem::MaterialItem (wxWindow * parent, wxColour mcolour, wxString mname)
 : wxPanel(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize)
 {
    m_arraw_bitmap_gray =  ScalableBitmap(this, "drop_down", FromDIP(12));
    m_arraw_bitmap_white =  ScalableBitmap(this, "topbar_dropdown", FromDIP(12));
    m_material_coloul = mcolour;
    m_material_name = mname;
    m_ams_coloul      = wxColour(0xEE,0xEE,0xEE);
#ifdef __WINDOWS__
    SetDoubleBuffered(true);
#endif //__WINDOWS__
    SetSize(MATERIAL_ITEM_SIZE);
    SetMinSize(MATERIAL_ITEM_SIZE);
    SetMaxSize(MATERIAL_ITEM_SIZE);
    SetBackgroundColour(*wxWHITE);
    Bind(wxEVT_PAINT, &MaterialItem::paintEvent, this);
    wxGetApp().UpdateDarkUI(this);
 }
References m_ams_coloul, m_arraw_bitmap_gray, m_arraw_bitmap_white, m_material_coloul, m_material_name, MATERIAL_ITEM_SIZE, and paintEvent().
~MaterialItem()
Slic3r::GUI::MaterialItem::~MaterialItem ()
{}
Member Function Documentation
doRender()
void Slic3r::GUI::MaterialItem::doRender (wxDC & dc)
{
    //top
    dc.SetPen(*wxTRANSPARENT_PEN);
    dc.SetBrush(wxBrush(m_material_coloul));
    dc.DrawRoundedRectangle(FromDIP(1), FromDIP(1), MATERIAL_ITEM_REAL_SIZE.x, FromDIP(18), 5);
    //bottom
    dc.SetPen(*wxTRANSPARENT_PEN);
    dc.SetBrush(wxBrush(wxColour(m_ams_coloul)));
    dc.DrawRoundedRectangle(FromDIP(1), FromDIP(18), MATERIAL_ITEM_REAL_SIZE.x, FromDIP(16), 5);
    dc.SetPen(*wxTRANSPARENT_PEN);
    dc.SetBrush(wxBrush(m_material_coloul));
    dc.DrawRectangle(FromDIP(1), FromDIP(11), MATERIAL_ITEM_REAL_SIZE.x, FromDIP(8));
    dc.SetPen(*wxTRANSPARENT_PEN);
    dc.SetBrush(wxBrush(m_ams_coloul));
    dc.DrawRectangle(FromDIP(1), FromDIP(18), MATERIAL_ITEM_REAL_SIZE.x, FromDIP(8));
#if __APPLE__
    if (m_material_coloul == *wxWHITE || m_ams_coloul == *wxWHITE) {
        dc.SetPen(wxColour(0xAC, 0xAC, 0xAC));
        dc.SetBrush(*wxTRANSPARENT_BRUSH);
        dc.DrawRoundedRectangle(1, 1, MATERIAL_ITEM_SIZE.x - 1, MATERIAL_ITEM_SIZE.y - 1, 5);
    }
    if (m_selected) {
        dc.SetPen(wxColour(0x00, 0xAE, 0x42));
        dc.SetBrush(*wxTRANSPARENT_BRUSH);
        dc.DrawRoundedRectangle(1, 1, MATERIAL_ITEM_SIZE.x - 1, MATERIAL_ITEM_SIZE.y - 1, 5);
    }
#else
    if (m_material_coloul == *wxWHITE || m_ams_coloul == *wxWHITE) {
        dc.SetPen(wxColour(0xAC, 0xAC, 0xAC));
        dc.SetBrush(*wxTRANSPARENT_BRUSH);
        dc.DrawRoundedRectangle(0, 0, MATERIAL_ITEM_SIZE.x, MATERIAL_ITEM_SIZE.y, 5);
    }
    if (m_selected) {
        dc.SetPen(wxColour(0x00, 0xAE, 0x42));
        dc.SetBrush(*wxTRANSPARENT_BRUSH);
        dc.DrawRoundedRectangle(0, 0, MATERIAL_ITEM_SIZE.x, MATERIAL_ITEM_SIZE.y, 5);
    }
#endif
    //arrow
    if ( (m_ams_coloul.Red() > 160 && m_ams_coloul.Green() > 160 && m_ams_coloul.Blue() > 160) &&
        (m_ams_coloul.Red() < 180 && m_ams_coloul.Green() < 180 && m_ams_coloul.Blue() < 180)) {
        dc.DrawBitmap(m_arraw_bitmap_white.bmp(), GetSize().x - m_arraw_bitmap_white.GetBmpSize().x - FromDIP(7),  GetSize().y - m_arraw_bitmap_white.GetBmpSize().y);
    }
    else {
        dc.DrawBitmap(m_arraw_bitmap_gray.bmp(), GetSize().x - m_arraw_bitmap_gray.GetBmpSize().x - FromDIP(7),  GetSize().y - m_arraw_bitmap_gray.GetBmpSize().y);
    }
}
References ScalableBitmap::bmp(), ScalableBitmap::GetBmpSize(), m_ams_coloul, m_arraw_bitmap_gray, m_arraw_bitmap_white, m_material_coloul, m_selected, MATERIAL_ITEM_REAL_SIZE, and MATERIAL_ITEM_SIZE.
Referenced by render().
msw_rescale()
void Slic3r::GUI::MaterialItem::msw_rescale ()
{}
on_left_down()
void Slic3r::GUI::MaterialItem::on_left_down (wxMouseEvent & evt)
on_normal()
void Slic3r::GUI::MaterialItem::on_normal ()
{
    if (m_selected || m_warning) {
        m_selected = false;
        m_warning  = false;
        Refresh();
    }
}
References m_selected, and m_warning.
on_selected()
void Slic3r::GUI::MaterialItem::on_selected ()
{
    if (!m_selected) {
        m_selected = true;
        Refresh();
    }
}
References m_selected.
Referenced by Slic3r::GUI::SelectMachineDialog::set_default().
on_warning()
void Slic3r::GUI::MaterialItem::on_warning ()
{
    if (!m_warning) {
        m_warning = true;
        Refresh();
    }
}
References m_warning.
paintEvent()
void Slic3r::GUI::MaterialItem::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    render(dc);
    //PrepareDC(buffdc);
    //PrepareDC(dc);
}
References render().
Referenced by MaterialItem().
render()
void Slic3r::GUI::MaterialItem::render (wxDC & dc)
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({0, 0}, size, &dc, {0, 0});
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
    // materials name
    dc.SetFont(::Label::Body_13);
    auto material_name_colour = m_material_coloul.GetLuminance() < 0.5 ? *wxWHITE : wxColour(0x26, 0x2E, 0x30);
    dc.SetTextForeground(material_name_colour);
    if (dc.GetTextExtent(m_material_name).x > GetSize().x - 10) {
        dc.SetFont(::Label::Body_10);
    }
    auto material_txt_size = dc.GetTextExtent(m_material_name);
    dc.DrawText(m_material_name, wxPoint((MATERIAL_ITEM_SIZE.x - material_txt_size.x) / 2, (FromDIP(22) - material_txt_size.y) / 2));
    // mapping num
    dc.SetFont(::Label::Body_10);
    dc.SetTextForeground(m_ams_coloul.GetLuminance() < 0.5 ? *wxWHITE : wxColour(0x26, 0x2E, 0x30));
    wxString mapping_txt = wxEmptyString;
    if (m_ams_name.empty()) {
        mapping_txt = "-";
    } else {
        mapping_txt = m_ams_name;
    }
    auto mapping_txt_size = dc.GetTextExtent(mapping_txt);
    dc.DrawText(mapping_txt, wxPoint((MATERIAL_ITEM_SIZE.x - mapping_txt_size.x) / 2, FromDIP(20) + (FromDIP(14) - mapping_txt_size.y) / 2));
}
References Label::Body_10, Label::Body_13, doRender(), m_ams_coloul, m_ams_name, m_material_coloul, m_material_name, MATERIAL_ITEM_SIZE, and size.
Referenced by paintEvent().
set_ams_info()
void Slic3r::GUI::MaterialItem::set_ams_info (wxColour col, wxString txt)
{
    auto need_refresh = false;
    if (m_ams_coloul != col) { m_ams_coloul = col; need_refresh = true;}
    if (m_ams_name != txt) {m_ams_name   = txt;need_refresh = true;}
    if (need_refresh) { Refresh();}
}
References col(), m_ams_coloul, and m_ams_name.
Referenced by Slic3r::GUI::SelectMachineDialog::on_set_finish_mapping(), Slic3r::GUI::SelectMachineDialog::reset_ams_material(), and Slic3r::GUI::SelectMachineDialog::sync_ams_mapping_result().
Member Data Documentation
m_ams_coloul
wxColour Slic3r::GUI::MaterialItem::m_ams_coloul
Referenced by MaterialItem(), doRender(), render(), and set_ams_info().
m_ams_name
wxString Slic3r::GUI::MaterialItem::m_ams_name
Referenced by render(), and set_ams_info().
m_arraw_bitmap_gray
ScalableBitmap Slic3r::GUI::MaterialItem::m_arraw_bitmap_gray
Referenced by MaterialItem(), and doRender().
m_arraw_bitmap_white
ScalableBitmap Slic3r::GUI::MaterialItem::m_arraw_bitmap_white
Referenced by MaterialItem(), and doRender().
m_main_panel
wxPanel* Slic3r::GUI::MaterialItem::m_main_panel
m_material_coloul
wxColour Slic3r::GUI::MaterialItem::m_material_coloul
Referenced by MaterialItem(), doRender(), and render().
m_material_name
wxString Slic3r::GUI::MaterialItem::m_material_name
Referenced by MaterialItem(), and render().
m_selected
bool Slic3r::GUI::MaterialItem::m_selected {false}
Referenced by doRender(), on_normal(), and on_selected().
m_warning
bool Slic3r::GUI::MaterialItem::m_warning {false}
Referenced by on_normal(), and on_warning().
The documentation for this class was generated from the following files:
src/slic3r/GUI/AmsMappingPopup.hpp
src/slic3r/GUI/AmsMappingPopup.cpp