OrcaSlicer: Slic3r::GUI::GridCellTextEditor Class Reference
Slic3r::GUI::GridCellTextEditor Class Reference
#include <src/slic3r/GUI/GUI_ObjectTable.hpp>
Public Member Functions
GridCellTextEditor ()
~GridCellTextEditor ()
virtual void Create (wxWindow *parent, wxWindowID id, wxEvtHandler *evtHandler) wxOVERRIDE
void StartingKey (wxKeyEvent &event) wxOVERRIDE
virtual void SetSize (const wxRect &rect) wxOVERRIDE
virtual void BeginEdit (int row, int col, wxGrid *grid) wxOVERRIDE
virtual bool EndEdit (int row, int col, const wxGrid *grid, const wxString &oldval, wxString *newval) wxOVERRIDE
virtual void ApplyEdit (int row, int col, wxGrid *grid) wxOVERRIDE
Protected Member Functions
::TextInput * Text () const
wxDECLARE_NO_COPY_CLASS (GridCellTextEditor)
Private Attributes
wxString m_value
Detailed Description
Constructor & Destructor Documentation
GridCellTextEditor()
Slic3r::GUI::GridCellTextEditor::GridCellTextEditor ()
: wxGridCellTextEditor() {}
~GridCellTextEditor()
Slic3r::GUI::GridCellTextEditor::~GridCellTextEditor ()
{}
Member Function Documentation
ApplyEdit()
void Slic3r::GUI::GridCellTextEditor::ApplyEdit (int row, int col, wxGrid * grid) virtual
{
    grid->GetTable()->SetValue(row, col, m_value);
    m_value.clear();
}
References col(), Slic3r::grid(), m_value, and row().
BeginEdit()
void Slic3r::GUI::GridCellTextEditor::BeginEdit (int row, int col, wxGrid * grid) virtual
{
    ObjectGridTable *               table    = dynamic_cast<ObjectGridTable *>(grid->GetTable());
    ObjectGridTable::ObjectGridCol *grid_col = table->get_grid_col(col);
    ObjectGridTable::ObjectGridRow *grid_row = table->get_grid_row(row - 1);
    auto val = table->GetValue(row, col);
    ObjectGrid* ogrid = dynamic_cast<ObjectGrid*>(grid);
  if (!ogrid->input_string.empty()) {
    Text()->GetTextCtrl()->SetValue(ogrid->input_string);
  }
  else {
    Text()->GetTextCtrl()->SetValue(val);
  }
    Text()->SetFocus();
    Text()->GetTextCtrl()->SetInsertionPointEnd();
    m_control->Bind(wxEVT_TEXT_ENTER, [this, row, col, grid](wxCommandEvent &e) {
        grid->HideCellEditControl();
        grid->SaveEditControlValue();
        e.Skip();
    });
    m_control->Bind(wxEVT_CHAR_HOOK, [this, row, col, grid](wxKeyEvent &e) {
    if (e.GetKeyCode() == WXK_ESCAPE) {
            grid->HideCellEditControl();
            grid->SaveEditControlValue();
    }
        e.Skip();
    });
}
References col(), Slic3r::GUI::ObjectGridTable::get_grid_col(), Slic3r::GUI::ObjectGridTable::get_grid_row(), TextInput::GetTextCtrl(), Slic3r::GUI::ObjectGridTable::GetValue(), Slic3r::grid(), Slic3r::GUI::ObjectGrid::input_string, row(), and Text().
Create()
void Slic3r::GUI::GridCellTextEditor::Create (wxWindow * parent, wxWindowID id, wxEvtHandler * evtHandler) virtual
{
    ::TextInput *text_input = new ::TextInput(parent, wxEmptyString, wxEmptyString, wxEmptyString, wxDefaultPosition, wxSize(-1, -1), wxTE_PROCESS_ENTER);
    m_control               = text_input;
    wxGridCellEditor::Create(parent, id, evtHandler);
}
EndEdit()
bool Slic3r::GUI::GridCellTextEditor::EndEdit (int row, int col, const wxGrid * grid, const wxString & oldval, wxString * newval) virtual
{
    ObjectGridTable *               table    = dynamic_cast<ObjectGridTable *>(grid->GetTable());
    ObjectGridTable::ObjectGridCol *grid_col = table->get_grid_col(col);
    ObjectGridTable::ObjectGridRow *grid_row = table->get_grid_row(row - 1);
    wxCHECK_MSG(m_control, false, "wxGridCellTextEditor must be created first!");
    const wxString value = Text()->GetTextCtrl()->GetValue();
    if (value == m_value) return false;
    m_value = value;
    if (newval) *newval = m_value;
    return true;
}
References col(), Slic3r::GUI::ObjectGridTable::get_grid_col(), Slic3r::GUI::ObjectGridTable::get_grid_row(), TextInput::GetTextCtrl(), Slic3r::grid(), m_value, row(), and Text().
SetSize()
void Slic3r::GUI::GridCellTextEditor::SetSize (const wxRect & rect) virtual
{ wxGridCellTextEditor::SetSize(rect); }
StartingKey()
void Slic3r::GUI::GridCellTextEditor::StartingKey (wxKeyEvent & event)
{}
Text()
::TextInput * Slic3r::GUI::GridCellTextEditor::Text () const inline protected
{ return (::TextInput *) m_control; }
Referenced by BeginEdit(), and EndEdit().
wxDECLARE_NO_COPY_CLASS()
Slic3r::GUI::GridCellTextEditor::wxDECLARE_NO_COPY_CLASS (GridCellTextEditor) protected
Member Data Documentation
m_value
wxString Slic3r::GUI::GridCellTextEditor::m_value private
Referenced by ApplyEdit(), and EndEdit().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectTable.hpp
src/slic3r/GUI/GUI_ObjectTable.cpp