OrcaSlicer: wxMediaCtrl2 Class Reference
wxMediaCtrl2 Class Reference
#include <src/slic3r/GUI/wxMediaCtrl2.h>
Public Member Functions
wxMediaCtrl2 (wxWindow *parent)
void Load (wxURI url)
void Play ()
void Stop ()
void SetIdleImage (wxString const &image)
int GetLastError () const
wxSize GetVideoSize () const
Protected Member Functions
wxSize DoGetBestSize () const override
void DoSetSize (int x, int y, int width, int height, int sizeFlags) override
Private Attributes
wxString m_idle_image
int m_error = 0
bool m_loaded = false
Detailed Description
Constructor & Destructor Documentation
wxMediaCtrl2()
wxMediaCtrl2::wxMediaCtrl2 (wxWindow * parent)
{
#ifdef __WIN32__
    auto hModExe = GetModuleHandle(NULL);
    // BOOST_LOG_TRIVIAL(info) << "wxMediaCtrl2: GetModuleHandle " << hModExe;
    auto NvOptimusEnablement = (DWORD *) GetProcAddress(hModExe, "NvOptimusEnablement");
    auto AmdPowerXpressRequestHighPerformance = (int *) GetProcAddress(hModExe, "AmdPowerXpressRequestHighPerformance");
    if (NvOptimusEnablement) {
        // BOOST_LOG_TRIVIAL(info) << "wxMediaCtrl2: NvOptimusEnablement " << *NvOptimusEnablement;
        *NvOptimusEnablement = 0;
    }
    if (AmdPowerXpressRequestHighPerformance) {
        // BOOST_LOG_TRIVIAL(info) << "wxMediaCtrl2: AmdPowerXpressRequestHighPerformance " << *AmdPowerXpressRequestHighPerformance;
        *AmdPowerXpressRequestHighPerformance = 0;
    }
#endif
    wxMediaCtrl::Create(parent, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxMEDIACTRLPLAYERCONTROLS_NONE);
#ifdef __LINUX__
    /* Register only after we have created the wxMediaCtrl, since only then are we guaranteed to have fired up Gstreamer's plugin registry. */
    gstbambusrc_register();
    Bind(wxEVT_MEDIA_LOADED, [this](auto & e) {
        m_loaded = true;
    });
#endif
}
References gstbambusrc_register(), m_loaded, and NULL.
Member Function Documentation
DoGetBestSize()
wxSize wxMediaCtrl2::DoGetBestSize () const override protected
{
    return {-1, -1};
}
DoSetSize()
void wxMediaCtrl2::DoSetSize (int x, int y, int width, int height, int sizeFlags) override protected
{
#ifdef __WXMAC__
    wxWindow::DoSetSize(x, y, width, height, sizeFlags);
#else
    wxMediaCtrl::DoSetSize(x, y, width, height, sizeFlags);
#endif
    if (sizeFlags & wxSIZE_USE_EXISTING) return;
    wxSize size = GetVideoSize();
    if (size.GetWidth() <= 0)
        size = wxSize{16, 9};
    int maxHeight = (width * size.GetHeight() + size.GetHeight() - 1) / size.GetWidth();
    if (maxHeight != GetMaxHeight()) {
        // BOOST_LOG_TRIVIAL(info) << "wxMediaCtrl2::DoSetSize: width: " << width << ", height: " << height << ", maxHeight: " << maxHeight;
        SetMaxSize({-1, maxHeight});
        CallAfter([this] {
            if (auto p = GetParent()) {
                p->Layout();
                p->Refresh();
            }
        });
    }
}
References GetVideoSize(), and size.
GetLastError()
int wxMediaCtrl2::GetLastError () const
{
#ifdef __LINUX__
    return gst_bambu_last_error;
#else
    return m_error;
#endif
}
References gst_bambu_last_error, and m_error.
GetVideoSize()
wxSize wxMediaCtrl2::GetVideoSize () const
{
#ifdef __LINUX__
    // Gstreamer doesn't give us a VideoSize until we're playing, which
    // confuses the MediaPlayCtrl into claiming that it is stuck
    // "Loading...".  Fake it out for now.
    return m_loaded ? wxSize(1280, 720) : wxSize{};
#else
    return m_imp ? m_imp->GetVideoSize() : wxSize(0, 0);
#endif
}
References m_loaded.
Referenced by DoSetSize().
Load()
void wxMediaCtrl2::Load (wxURI url)
{
#ifdef __WIN32__
    if (m_imp == nullptr) {
        CallAfter([] {
            auto res = wxMessageBox(_L("Windows Media Player is required for this task! Do you want to enable 'Windows Media Player' for your operation system?"), _L("Error"), wxOK | wxCANCEL);
            if (res == wxOK) {
                wxString url = IsWindows10OrGreater()
                        ? "ms-settings:optionalfeatures?activationSource=SMC-Article-14209"
                        : "https://support.microsoft.com/en-au/windows/get-windows-media-player-81718e0d-cfce-25b1-aee3-94596b658287";
                wxExecute("cmd /c start " + url, wxEXEC_HIDE_CONSOLE);
            }
        });
        m_error = 100;
        wxMediaEvent event(wxEVT_MEDIA_STATECHANGED);
        event.SetId(GetId());
        event.SetEventObject(this);
        wxPostEvent(this, event);
        return;
    }
    {
        wxRegKey key1(wxRegKey::HKCR, L"CLSID\\" CLSID_BAMBU_SOURCE L"\\InProcServer32");
        wxString path = key1.Exists() ? key1.QueryDefaultValue() : wxString{};
        wxRegKey key2(wxRegKey::HKCR, "bambu");
        wxString clsid;
        if (key2.Exists())
            key2.QueryRawValue("Source Filter", clsid);
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": clsid %1% path %2%") % clsid % path;
        if (path.empty() || !wxFile::Exists(path) || clsid != CLSID_BAMBU_SOURCE) {
            std::string             data_dir_str = Slic3r::data_dir();
            boost::filesystem::path data_dir_path(data_dir_str);
            auto                    dll_path = data_dir_path / "plugins" / "BambuSource.dll";
            if (boost::filesystem::exists(dll_path)) {
                CallAfter(
                    [dll_path] {
                    int res = wxMessageBox(_L("BambuSource has not correctly been registered for media playing! Press Yes to re-register it."), _L("Error"), wxYES_NO);
                    if (res == wxYES) {
                        wstring quoted_dll_path = L"\"" + dll_path.wstring() + "\"";
                        SHELLEXECUTEINFO info{sizeof(info), 0, NULL, L"runas", L"regsvr32", quoted_dll_path.c_str(), SW_HIDE };
                        ::ShellExecuteEx(&info);
                    }
                });
            } else {
                CallAfter([] {
                    wxMessageBox(_L("Missing BambuSource component registered for media playing! Please re-install BambuStutio or seek after-sales help."), _L("Error"), wxOK);
                });
            }
            m_error = clsid != CLSID_BAMBU_SOURCE ? 101 : path.empty() ? 102 : 103;
            wxMediaEvent event(wxEVT_MEDIA_STATECHANGED);
            event.SetId(GetId());
            event.SetEventObject(this);
            wxPostEvent(this, event);
            return;
        }
        wxRegKey keyWmp(wxRegKey::HKCU, "SOFTWARE\\Microsoft\\MediaPlayer\\Player\\Extensions\\.");
        keyWmp.Create();
        long permissions = 0;
        if (keyWmp.HasValue("Permissions"))
            keyWmp.QueryValue("Permissions", &permissions);
        if ((permissions & 32) == 0) {
            permissions |= 32;
            keyWmp.SetValue("Permissions", permissions);
        }
    }
    url = wxURI(url.BuildURI().append("&hwnd=").append(
        boost::lexical_cast<std::string>(GetHandle())));
#endif
#ifdef __WXGTK3__
    GstElementFactory *factory;
    int hasplugins = 1;
    factory = gst_element_factory_find("h264parse");
    if (!factory) {
        hasplugins = 0;
    } else {
        gst_object_unref(factory);
    }
    factory = gst_element_factory_find("openh264dec");
    if (!factory) {
        factory = gst_element_factory_find("avdec_h264");
    }
    if (!factory) {
        factory = gst_element_factory_find("vaapih264dec");
    }
    if (!factory) {
        hasplugins = 0;
    } else {
        gst_object_unref(factory);
    }
    if (!hasplugins) {
        CallAfter([] {
            wxMessageBox(_L("Your system is missing H.264 codecs for GStreamer, which are required to play video.  (Try installing the gstreamer1.0-plugins-bad or gstreamer1.0-libav packages, then restart Orca Slicer?)"), _L("Error"), wxOK);
        });
        m_error = 101;
        wxMediaEvent event(wxEVT_MEDIA_STATECHANGED);
        event.SetId(GetId());
        event.SetEventObject(this);
        wxPostEvent(this, event);
        return;
    }
    wxLog::EnableLogging(false);
#endif
    m_error = 0;
    m_loaded = false;
    wxMediaCtrl::Load(url);
#ifdef __WXGTK3__
        wxMediaEvent event(wxEVT_MEDIA_STATECHANGED);
        event.SetId(GetId());
        event.SetEventObject(this);
        wxPostEvent(this, event);
#endif
}
References _L, CLSID_BAMBU_SOURCE, Slic3r::data_dir(), L, m_error, m_loaded, and NULL.
Play()
void wxMediaCtrl2::Play ()
{ wxMediaCtrl::Play(); }
Referenced by Slic3r::GUI::MediaPlayCtrl::MediaPlayCtrl().
SetIdleImage()
void wxMediaCtrl2::SetIdleImage (wxString const & image)
Stop()
void wxMediaCtrl2::Stop ()
{
#ifdef __WIN32__
    wxMediaCtrl::Load(wxURI());
#else
    wxMediaCtrl::Stop();
#endif
}
Member Data Documentation
m_error
int wxMediaCtrl2::m_error = 0 private
Referenced by GetLastError(), and Load().
m_idle_image
wxString wxMediaCtrl2::m_idle_image private
m_loaded
bool wxMediaCtrl2::m_loaded = false private
Referenced by wxMediaCtrl2(), GetVideoSize(), and Load().
The documentation for this class was generated from the following files:
src/slic3r/GUI/wxMediaCtrl2.h
src/slic3r/GUI/MediaPlayCtrl.cpp
src/slic3r/GUI/wxMediaCtrl2.cpp
src/slic3r/GUI/wxMediaCtrl2.mm